elastic/integrations

.github/workflows/bump-elastic-stack-version.yml

Our actions started failing after the time of this upgrade, revert it to see if it fixes the issue.

Revert update of updatecli

---

packages/checkpoint/changelog.yml
packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
packages/checkpoint/manifest.yml

- Situations may arise where event.original is set to non-standard or incorrect value by some external source, such as Logstash. Since the value we need is the contents of the message field, the value of event.original will be set to the value of message in all cases.
- Add remove processor to delete message field to mimic behavior of the old rename processor.
```
cd packages/checkpoint
```
- Relates elastic/sdh-beats#4977

[checkpoint] Ensure event.original is always set to message

---

packages/ti_abusech/changelog.yml
packages/ti_abusech/data_stream/malware/fields/ecs.yml
packages/ti_abusech/data_stream/malwarebazaar/fields/ecs.yml
packages/ti_abusech/data_stream/threatfox/fields/ecs.yml
packages/ti_abusech/data_stream/url/fields/ecs.yml
packages/ti_abusech/docs/README.md
packages/ti_abusech/manifest.yml

```
Fix ECS date mapping for threat fields.
ecs@mappings component template is missing threat fields 
mapped as date. Example: fields such as first_seen, last_seen, 
modified_at are being mapped as keyword in transform's source 
datastream-backed indices. The transform's destination indices
are not effected as they are not datastream-backed and mappings
are explicitly defined as date. This causes field type conflicts.
- Explicitly add ECS threat fields that are of type date into 
source data-stream backed fields.
```
- Relates https://github.com/elastic/integrations/issues/10612

ti_abusech: Fix ECS date mapping on threat fields.

---

packages/ti_misp/_dev/deploy/docker/files/config.yml
packages/ti_misp/changelog.yml
packages/ti_misp/data_stream/threat/fields/ecs.yml
packages/ti_misp/data_stream/threat_attributes/_dev/test/pipeline/test-misp-sample-ndjson.log-expected.json
packages/ti_misp/data_stream/threat_attributes/elasticsearch/ingest_pipeline/default.yml
packages/ti_misp/data_stream/threat_attributes/fields/fields.yml
packages/ti_misp/data_stream/threat_attributes/sample_event.json
packages/ti_misp/docs/README.md
packages/ti_misp/elasticsearch/transform/latest_ioc/fields/fields.yml
packages/ti_misp/manifest.yml

```
Fix ECS date mapping for threat fields.
ecs@mappings component template is missing threat fields 
mapped as date. Example: fields such as first_seen, last_seen, 
modified_at are being mapped as keyword in transform's source 
datastream-backed indices. The transform's destination indices
are not effected as they are not datastream-backed and mappings
are explicitly defined as date. This causes field type conflicts.
- Explicitly add ECS threat fields that are of type date into 
source data-stream backed fields.
- Fix first_seen, last_seen date processors with microseconds.
- Add missing first_seen, last_seen fields.
```
- Relates https://github.com/elastic/integrations/issues/10612

ti_misp: Fix ECS date mapping on threat fields.

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/data_stream/result/fields/osquery.yml
packages/osquery_manager/manifest.yml

Upgrades osquery mappings to match osquery 5.12.1 schema.
- Requires https://github.com/elastic/beats/pull/40368

Osquery_manager: Upgrade osquery mappings to match osquery 5.12.1 schema

---

.github/CODEOWNERS
packages/system/changelog.yml
packages/system/data_stream/auth/_dev/test/pipeline/test-host-syslog-processor.json
packages/system/data_stream/auth/_dev/test/pipeline/test-host-syslog-processor.json-expected.json
packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
packages/system/manifest.yml

Before the syslog processor was added to the default filebeat yaml configuration, process.name was set by a Grok ingest pipeline. However, when the syslog processor was added a condition was also added to the Grok ingest pipeline, `if: ctx.log?.syslog == null`. This condition always evaluates to false when the data is supplied by the syslog processor, and therefore `process.name` is not extraced from the syslog message. This commit copies the process name from `log.syslog.appname` to `process.name` before an pipeline processors which use it are executed. With this change, `process.name`, `event.category`, and `event.type` are now populated when data arrives from the syslog processor.
And add tests.
```
~/git/integrations/main/packages/system$ elastic-package test pipeline -d auth -v
```
- …

Copy log.syslog.appname to process.name

---

packages/awsfargate/_dev/build/docs/README.md
packages/awsfargate/changelog.yml
packages/awsfargate/docs/README.md
packages/awsfargate/manifest.yml

Clarify the AWS Fargate integration documentation, saying that this integration supports Amazon ECS clusters only. Unfortunately, today, it does not support EKS clusters managing nodes with a Fargate profile.
More than one user contacted the support team, asking why the AWS Fargate doesn't work on the EKS cluster. The docs state that it works with ECS clusters only, but more is needed.

AWS Fargate: Add disclaimer that integration supports ECS only

---

.buildkite/scripts/find_oldest_supported_version.py
.buildkite/scripts/trigger_integrations_in_parallel.sh

Retry forever if the artifacts API is not available, and assume it will come back at some point.
If it doesn't come back, the job would fail in any case.

Retry requests to artifacts API from CI jobs

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bumping the next pre-release version 1.11.0 in preview mode. Also updating the 1.9.* changelogs that were still mentioning preview versions

[Cloud Security] Bump 1.11.0 pre-release version and update 1.9.0 changelogs

---

packages/auditd_manager/data_stream/auditd/_dev/deploy/agent/custom-agent.yml
packages/auditd_manager/data_stream/auditd/_dev/test/system/test-default-config.yml

Once `elastic-package` v0.101.1 has been updated in this repository, `auditd_manager` can start using independent Elastic Agents and for that it is needed to migrate from the old custom agents.
```shell
cd packages/auditd_manager
elastic-package stack up -v -d --version 8.7.1
elastic-package test system -v --defer-cleanup 240s
elastic-package stack down -v
```
- Relates #10201 
- Depends on #10384
- Relates #10390

Update auditd manager independent agent

---

packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/knowledge_base/_dev/test/system/test-1_invalid-config.yml
packages/qualys_vmdr/data_stream/knowledge_base/agent/stream/input.yml.hbs
packages/qualys_vmdr/manifest.yml

```
[qualys_vmdr] Fix CEL access to unset state.params in knowledge_base (#10677)
When the `input_parameters` variable is not set, `state.params` is not
set. The CEL program needs to account for that possibility when it
accesses it. It was already handled correctly for the
asset_host_detection data stream, and the user_activity data stream
doesn't have that variable.
Co-authored-by: Dan Kortschak <dan.kortschak@elastic.co>
```

[qualys_vmdr] Fix CEL access to unset state.params in knowledge_base

---

packages/prisma_cloud/changelog.yml
packages/prisma_cloud/data_stream/host/agent/stream/input.yml.hbs
packages/prisma_cloud/data_stream/host_profile/agent/stream/input.yml.hbs
packages/prisma_cloud/manifest.yml

```
[prisma_cloud] Fix null checks in host_profile CEL program (#)
Requests made by the host and host_profile data streams sometime return
successful (HTTP 200) responses with the body set to the string `null`.
The CEL programs of both data streams did check for this, but the
host_profile data stream was missing checks in two places.
This change adds those missing checks in host_profile. It also
simplifies the calculation of the `new_offset` value, and applies that
simplification to the host data stream as well.
The host and host_profile data streams both use APIs provided by the
Cloud Workload Protection (CWP) module.
This is the relevant API documentation:
- https://pan.dev/prisma-cloud/api/cwpp/get-profiles-host/
- https://pan.dev/prisma-cloud/api/cwpp/get-hosts/
However, the `null` …
```

[prisma_cloud] Fix null checks in host_profile CEL program

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/agent/stream/aws.yml.hbs
packages/cloud_asset_inventory/data_stream/asset_inventory/agent/stream/azure.yml.hbs
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml

This PR adds support for second data stream in Cloud Asset inventory - Azure. It also sets a new cloudbeat configuration parameter `config.v1.asset_inventory_provider` where necessary.
Introduce support for Azure data stream in Cloud Asset Inventory
Closes https://github.com/elastic/security-team/issues/10084

[Cloud Asset Inventory] Add Azure Inventory

---

packages/azure/_dev/build/docs/README.md
packages/azure/changelog.yml
packages/azure/docs/README.md
packages/azure/manifest.yml

Extend the Azure Logs integration docs adding a section dedicated to setting up event hub partitions.
The existing docs didn't cover event hub partitions, leaving the responsibility of reading the Microsoft documentation. This PR gives guidance on the event hub partitions, linking to Microsoft docs for advanced use cases.
- https://github.com/elastic/integrations/issues/10557

Azure Logs: Expand the integration docs adding a section for Event Hub partitions

---

.buildkite/pull-requests.json

Allow `github-actions[bot]` user to trigger PR builds (like updatecli Pull Requests) in Buildkite.

[CI] Allow github-actions bot user to trigger builds

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/1d71c6c70e9ff046d4493a0c696b34db6c4a9596
None
None

[Security Rules] Update security rules package to v8.14.8

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/eae3fb54e54132c858f6e56fec714e617d543968
None
None

[Security Rules] Update security rules package to v8.15.2

---

packages/fortinet_fortiproxy/changelog.yml
packages/fortinet_fortiproxy/data_stream/log/_dev/test/pipeline/test-example.log-expected.json
packages/fortinet_fortiproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/fortinet_fortiproxy/data_stream/log/fields/ecs.yml
packages/fortinet_fortiproxy/docs/README.md
packages/fortinet_fortiproxy/manifest.yml

- Remap the devname vendor field to observer.name
- Remap the url vendor field to url.original and run through uri_parts processor
```
cd packages/fortinet_fortiproxy
```
- Relates #10659
- Note: Waiting on clarification of session ID fields and any other ECS remappings.

[fortinet_fortiproxy] Remap devname to observer.name and process url field

---

packages/sophos_central/_dev/build/docs/README.md
packages/sophos_central/changelog.yml
packages/sophos_central/docs/README.md
packages/sophos_central/manifest.yml

Update docs for `token_url` configuration.
[The input](https://github.com/elastic/integrations/blob/main/packages/sophos_central/data_stream/alert/agent/stream/httpjson.yml.hbs#L9) already appends the token url path `/api/v2/oauth2/token`
to the `auth.oauth2.token_url`, needing the user to configure only 
the base url for `token_url` parameter. For example: `https://id.sophos.com`.
The current README doc doesn't indicate that the url path needs to be
removed when configuring `token_url`. This can lead to duplicate url path 
in the `auth.oauth2.token_url`, for example: 
`https://id.sophos.com/api/v2/oauth2/token/api/v2/oauth2/token`. 
The PR addresses this by updating the README doc.

sophos_central: Update docs for token_url configuration

---

packages/jumpcloud/changelog.yml
packages/jumpcloud/data_stream/events/elasticsearch/ingest_pipeline/default.yml
packages/jumpcloud/manifest.yml

```
Populate `event.outcome` based on `sso_token_success`, when present
The `sso_token_success` field isn't in the API documentation, but we
do have a field definition for it and we see it returned with
`"event_type": "sso_auth"` (without the `success` field).
```

Populate `event.outcome` based on `sso_token_success`, when present

---

.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml

Update junit buildkite plugin and enable reporting the skipped tests in the corresponding annotations.
Skipped tests just are shown if there is any test failing. 
Example of how these skipped tests are shown in the buildkite build:

[CI] Report skipped tests in junit annotations

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/kibana/dashboard/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824.json
packages/elastic_agent/manifest.yml
packages/elastic_agent/validation.yml

This commit re-adds a search that was removed by accident from the
[Elastic Agent] Agent Info dashboard and add an exception to the lint
so the package can be compiled.
1. Build the elastic-agent package
2. go to the dashboard: https://127.0.0.1:5601/app/dashboards#/view/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824
- https://github.com/elastic/integrations/pull/10217

Add search reference that was removed from Elastic-Agent dashboard

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/fields/related.yml
packages/cloud_asset_inventory/manifest.yml

Based on product decision, in the asset inventory integration, we are moving away from `related.entities` and towards `related.entity`
- Related https://github.com/elastic/security-team/issues/10080
- Related https://github.com/elastic/integrations/pull/10688
- Counterpart of https://github.com/elastic/cloudbeat/pull/2398

Rename from `related.entities` to `related.entity`

---

packages/keycloak/changelog.yml
packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/events.yml
packages/keycloak/manifest.yml

Fixed a condition in a `drop` processor for the Keycloak ingest pipeline, where the value was missing.
To help identify the pipeline error, some tags have been added to the more elaborate processors in the pipeline.
Before the change, ingesting an event into the pipeline as follows:
```
POST /_ingest/pipeline/logs-keycloak.log-1.22.2/_simulate
{
"docs": [
{
"_index": "index",
"_id": "id",
"_source": {
"message": "2024-07-17 12:05:32,104 INFO [org.keycloak.events] (main-thread-1) type=\"LOGOUT\", realmId=\"12345678-9abc-def0-1234-56789abcdef0\", clientId=\"user-console\", userId=\"abcdef12-3456-7890-abcd-ef1234567890\", sessionId=\"abcd1234-5678-90ab-cdef-1234567890ab\", ipAddress=\"192.168.1.1\", auth_method=\"oauth2\", auth_type=\"token\", response_type=\"token\", …
```

[Keycloak] Fix missing value in pipeline condition

---

packages/linux/changelog.yml
packages/linux/data_stream/service/agent/stream/stream.yml.hbs
packages/linux/manifest.yml

Since #10314 Linux Metrics Service fails with below message:
```[constant_keyword] field [event.module] only accepts values that are equal to the value defined in the mappings [linux], but got [system]```
This fixes this issue, by adding a single processor to the datastream.

Fix event.module for Linux Metrics Service

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/kibana/index_pattern/cloud_security_posture-07a5e6d6-982d-4c7c-a845-5f2be43279c9.json
packages/cloud_security_posture/kibana/index_pattern/cloud_security_posture-c406d945-a359-4c04-9a6a-65d66de8706b.json.json
packages/cloud_security_posture/manifest.yml

Revert cloud security vulnerability data views.
In [this GitHub pull request](https://github.com/elastic/integrations/pull/10692), we deprecated all cloud security data views. We should postpone deprecating the vulnerability data views until the requirements are more clearly defined.

Revert vuln data views

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_ad/data_stream/user/manifest.yml
packages/entityanalytics_ad/manifest.yml

See title.
- For elastic/beats#40482

entityanalytics_ad: expose paging size configuration to user

---

packages/aws_bedrock/changelog.yml
packages/aws_bedrock/data_stream/runtime/elasticsearch/ingest_pipeline/default.yml
packages/aws_bedrock/manifest.yml
packages/awsfirehose/changelog.yml
packages/awsfirehose/data_stream/metrics/routing_rules.yml
packages/awsfirehose/manifest.yml

This PR is to add Firehose support for AWS/Bedrock runtime metrics.
- add AWS/Bedrock to metrics rerouting
- add dot expander processor to expand fields with dots into object fields which allows fields with dots to be accessible by other processors later.

Add AWS Bedrock runtime metrics to Firehose rerouting

---

packages/jamf_protect/changelog.yml
packages/jamf_protect/data_stream/telemetry/_dev/test/pipeline/test-jamf-protect-telemetry-sample-logs.log-expected.json
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_authentication.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_btm_launch_item_add.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_btm_launch_item_remove.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_exec.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_attribute_set.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_attribute_value_add.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_attribute_value_remove.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_create_group.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_create_user.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_delete_group.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_delete_user.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_disable_user.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_enable_user.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_group_add.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_group_remove.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_group_set.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_od_modify_password.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_profile_add.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_profile_remove.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_screensharing_attach.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_screensharing_detach.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_object_process.yml
packages/jamf_protect/data_stream/telemetry/sample_event.json
packages/jamf_protect/docs/README.md
packages/jamf_protect/manifest.yml

Type of change:
- Enhancement
- Added `process.name` field, this for preparations for Event Visualiser
- Minor enhancements to `od*` pipeline events
- `pipeline_event_od_group_add` -> added `event.type` field
- `pipeline_event_od_group_remove` -> added `event.type` field
- Minor enhancements to `screensharing*` events
- `pipeline_event_screensharing_attach` added `jamf_protect.telemetry.source_address_type` field
- `pipeline_event_screensharing_detach` added `jamf_protect.telemetry.source_address_type` field
`elastic-package test system`
```
2024/08/19 16:45:26  INFO Write container logs to file: /Users/thijs.xhaflaire/Documents/GitHub/Elastic/integrations/build/container-logs/jamf-protect-webtraffic-http-endpoint-1724078726146769000.log
--- Test results for package: jamf_protect - START …
```

Adding process.name field and minor enhancements to od* events.

---

packages/lmd/changelog.yml
packages/lmd/elasticsearch/transform/pivot_transform/transform.yml
packages/lmd/manifest.yml

The "scripted_metric" aggregation is being deprecated in Serverless as it was causing OOM errors. As a result, we're removing this aggregation from the LMD pivot transform and replacing it with alternatives like min, max, and bucket_script.
- Tested the pivot transform after replacing the `scripted_metric` with `min`, `max`, and `bucket_script`, and it’s producing the same results as before after comparison. A screenshot showing this is included in the comments.
-

[LMD] Remove "scripted_metric" aggregation from the pivot transform

---

packages/beaconing/manifest.yml
packages/ded/manifest.yml
packages/dga/manifest.yml
packages/lmd/manifest.yml
packages/problemchild/manifest.yml

The maintainer of these packages is the elastic/sec-applied-ml team. The elastic/ml-ui team maintains the ML platform, and helps review changes to these packages, but the maintainer and owner is the security protections applied ML team.
No changelog is being added because this change does not affect users.
- Relates #10354

Update owner for Team:Security-Applied ML packages

---

packages/dga/changelog.yml
packages/dga/fields/base-fields.yml
packages/dga/fields/custom.yml
packages/dga/manifest.yml
packages/problemchild/changelog.yml
packages/problemchild/fields/base-fields.yml
packages/problemchild/fields/custom.yml
packages/problemchild/manifest.yml

Adds `fields/custom.yml` files back to the DGA and Living off the Land (ProblemChild) integration packages. These files are used for integration testing done upstream.
Build with `elastic-package`.
- https://github.com/elastic/security-ml/issues/474

Add back custom.yml files to LotL, DGA packages

---

packages/microsoft_defender_cloud/changelog.yml
packages/microsoft_defender_cloud/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_defender_cloud/manifest.yml

Store eventhub metdata inside `azure-eventhub` field instead of `azure`.
In `microsoft_defender_cloud `, the field `azure.eventhub` comes from `Azure EventHub` 
input and is mapped as `keyword`. But `Azure` integration's `eventhub` datastream 
uses `azure.eventhub` field as an object to store custom fields. This is a design decision 
for most integrations to map custom fields into `package.datastream`. This causes conflict 
when users setup both `microsoft_defender_cloud.event` and `azure.eventhub` datastreams. 
Most `Azure` datastreams rename the top level `azure` field coming from the input into 
`azure-eventhub`, which stores the metadata for eventhub. To avoid conflict in similar way, 
`microsoft_defender_cloud ` also need to rename `azure` to `azure-eventhub`.
NOTE: Bumping major …

microsoft_defender_cloud: Store eventhub metdata inside azure-eventhub field.

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.20.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/47b8de3869b96a2ee7539086235bd01af7d7075f
None
None

[Security Rules] Update security rules package to v8.12.20

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b6e86490f34e333bf3ae265e53bea6d9e5ddb3f7
None
None

[Security Rules] Update security rules package to v8.14.9

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/bd1a7cac711fcfdea06ae09a41869afe553a9540
None
None

[Security Rules] Update security rules package to v8.13.15

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/7b81effebcca27cb52cfba5cdd3eda1654f0b007
None
None

[Security Rules] Update security rules package to v8.15.3

---

.buildkite/pipeline.yml

Show always the annotation related to JUnit reports.
This would help to show always the skipped tests.
- Build: https://buildkite.com/elastic/integrations/builds/14778

[CI] Show always junit reports/annotation

---

packages/crowdstrike/_dev/deploy/docker/files/config-alert.yml
packages/crowdstrike/_dev/deploy/docker/files/config-host.yml
packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/alert/agent/stream/cel.yml.hbs
packages/crowdstrike/data_stream/host/agent/stream/cel.yml.hbs
packages/crowdstrike/manifest.yml

Return empty `events` array when no `resources` in `alert` and `host` data-streams.
When there are no `resources` in first API call, current CEL code returns `state`.
But this `state` doesn't have `events` inside it. As per [CEL docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-cel.html#input-state-cel:~:text=The%20events%20field%20must%20be%20present), the `events` field 
is necessary. Without this, the following errors appear and lead to restarting of input.
```
{"log.level":"error","@timestamp":"2024-08-21T06:26:37.252Z","message":"unexpected missing events array from evaluation","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"input_source":"http://svc-crowdstrike-host:8090","i …
```

crowdstrike: Return empty events array when no resources in alert, host.

---

packages/mysql/changelog.yml
packages/mysql/data_stream/performance/elasticsearch/ingest_pipeline/default.yml
packages/mysql/data_stream/performance/fields/fields.yml
packages/mysql/manifest.yml

- Enhancement
- Update kibana version to `8.15.0`.
- Add `schemaname` field in the performance data stream
- Closes #9239

[O11y][MYSQL] Add `schemaname` field in the performance data stream

---

packages/system/changelog.yml
packages/system/kibana/dashboard/system-71f720f0-ff18-11e9-8405-516218e3d268.json
packages/system/manifest.yml

- Bug
See title 
Related: https://github.com/elastic/integrations/issues/10431 -> All visualizations implemented here work, except this one. A missed ")" is causing this to break.

[system] Fix broken visualization for User Renamed Metric in User Management Events Dashboard

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_asa/manifest.yml

Handle "Account has been locked out" reason parsing
- Closes https://github.com/elastic/integrations/issues/10738

[cisco_asa] Handle "Account has been locked out" reason parsing

---

packages/cef/changelog.yml
packages/cef/data_stream/log/agent/stream/log.yml.hbs
packages/cef/data_stream/log/agent/stream/tcp.yml.hbs
packages/cef/data_stream/log/agent/stream/udp.yml.hbs
packages/cef/data_stream/log/manifest.yml
packages/cef/manifest.yml

Make dataset name configurable
- Closes https://github.com/elastic/integrations/issues/5379
Example of customized dataset names with the policy

[cef] Make dataset name configurable

---

packages/amazon_security_lake/_dev/build/docs/README.md
packages/amazon_security_lake/changelog.yml
packages/amazon_security_lake/data_stream/event/agent/stream/aws-s3.yml.hbs
packages/amazon_security_lake/data_stream/event/manifest.yml
packages/amazon_security_lake/docs/README.md
packages/amazon_security_lake/manifest.yml

- Bug
SQS notification config settings were removed due to an internal update error in this [PR](https://github.com/elastic/integrations/pull/10144). This caused successive confusing documentation issues that were resolved in this [PR](https://github.com/elastic/integrations/pull/10799). All of this was unnecessary and the original removal was an error in itself and this PR tries to rectify this mistake and make it easier for users to use the integration.
- Relates #10144, #10799

[Amazon Security Lake] - Re-enable SQS notification settings 

---

packages/gcp_metrics/changelog.yml
packages/gcp_metrics/fields/input.yml
packages/gcp_metrics/manifest.yml

- WHAT: Set kibana restriction to 8.15.0, where the scope for the geo_point was reduced, see - [PR](https://github.com/elastic/elasticsearch/pull/108349)
- WHY:  The problem is mainly with the *.location field - that is considered as a `geo_point` type https://github.com/elastic/elasticsearch/blob/v8.14.3/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json#L187-L196
This behavior is changed in this [PR](https://github.com/elastic/elasticsearch/pull/108349) and will be available in 8.15
-

[gcp_metrics] Set kibana restriction to 8.15.0, where the scope for the geo_point was reduced

---

packages/aws_logs/changelog.yml
packages/aws_logs/data_stream/generic/manifest.yml
packages/aws_logs/manifest.yml

- Enhancement
WHAT: Update the file selector field of `Collect Logs from S3 Bucket` datastream to be able to receive multiline configurations
WHY: It is needed in order to be able to provide specific parsers confguration to specific file selectors. Otherwise the parsers is not applied to the files selected
1. Clone this PR
2. Navigate to `/integrations/packages/aws_logs`
3. Run elastic-package build
4. Run `elastic-package stack up -d -v --version=8.15.0` within the same folder. This will create a local elastic stack
5. Create an agent policy with aws_custom_logs integration
6.  In the policy enable `Collect Logs from S3 Bucket` datastream
7. Under the `advanced options` update `File Selectors field`
```yaml
- regex: .*windows-events-.*
parsers:
- multiline:
pattern: …
```

[aws custom logs] Updating file selector field to receive mutline configurations

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/audit_logs/fields/fields.yml
packages/kubernetes/docs/audit-logs.md
packages/kubernetes/manifest.yml

- Enhancement
- Changed the group field from text to keyboard, the group field contains unique values. It will valuable to filtering and creating graphs.

chore: group to keyword

---

packages/abnormal_security/_dev/deploy/docker/files/config.yml
packages/abnormal_security/changelog.yml
packages/abnormal_security/data_stream/threat/agent/stream/cel.yml.hbs
packages/abnormal_security/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/abnormal_security/data_stream/threat/sample_event.json
packages/abnormal_security/docs/README.md
packages/abnormal_security/manifest.yml

Type of change
- Enhancement
Update the pagination termination condition for the `threat` data stream so that pagination stops whenever `nextPageNumber` is not found in the response body. This should apply to both the `/v1/threats` and `/v1/threats/:id` endpoints.
- Move to integrations/packages/abnormal_security directory.

[abnormal_security] Update pagination termination condition

---

packages/fortinet_fortiproxy/changelog.yml
packages/fortinet_fortiproxy/data_stream/log/agent/stream/udp.yml.hbs
packages/fortinet_fortiproxy/manifest.yml

- Fix udp_options in UDP agent file having incorrect variable

[fortinet_fortiproxy] Fix udp_options in UDP agent file

---

packages/kubernetes/changelog.yml
packages/kubernetes/kibana/dashboard/kubernetes-0a672d50-bcb1-11ec-b64f-7dd6e8e82013.json
packages/kubernetes/kibana/dashboard/kubernetes-3912d9a0-bcb2-11ec-b64f-7dd6e8e82013.json
packages/kubernetes/kibana/dashboard/kubernetes-5be46210-bcb1-11ec-b64f-7dd6e8e82013.json
packages/kubernetes/kibana/dashboard/kubernetes-85879010-bcb1-11ec-b64f-7dd6e8e82013.json
packages/kubernetes/kibana/dashboard/kubernetes-f4dc26db-1b53-4ea2-a78b-1bfab8ea267c.json
packages/kubernetes/manifest.yml

- Bug
- WHAT: Updated the Top Memory and Top CPU visualisations of `Cluster Overview Dashboard` in order to use the **container.id** filter
- WHY:  The kubernetes.container.name used in previous visualisations was not unique for all kinds of k8s resources (eg. the kubernetes.container.name is the same for all pods of same daemonset and this was creating false calculations)
Additionally we removed all median functions from or visualisations and replaced them either with Average or Last value
The updated dashboards where the median has been removed are:
- Cronjobs
- Deployments
- Volume 
- Daemonsets
0. Prequisite to have a local k8s cluster. Use kind and run `kind create cluster`
1. Install kube-state-metrics in your k8s cluster
2. Clone this branch
3. Change to directory …

[k8s Integratiion] Adding container.id as filter of Cluster Overview and removing median filter occurencies

---

.github/workflows/updatecli/updatecli.d/sync-packages-to-bug-issue-template.yml

Keep the list of packages in the bug issue template in sync with the packages contained in
the repo by utilizing updatecli.
Closes: #10565
You can view an example of this automation's output at https://github.com/andrewkroh/integrations/pull/3.

[ci] automate updates to .github/ISSUE_TEMPLATE/integration_bug.yml

---

packages/wiz/changelog.yml
packages/wiz/data_stream/cloud_configuration_finding/_dev/test/pipeline/test-cloud-configuration-finding.log-expected.json
packages/wiz/data_stream/cloud_configuration_finding/elasticsearch/ingest_pipeline/default.yml
packages/wiz/manifest.yml

Cloud Security features in Kibana rely on the lowercase value of `result.evaluation`. Fixing `cloud_configuration_finding` ingest pipeline to provide the lowercased values
see https://github.com/elastic/integrations/pull/10790
- relates https://github.com/elastic/security-team/issues/9662

wiz: fix result.evaluation to be lowercased in cloud_configuration_finding

---

.github/workflows/updatecli/updatecli.d/bump-latest-snapshot-version.yml

Enable updatecli targets to update weekly pipeline with the latest snapshot.

[CI] Enable updatecli targets for weekly pipeline

---

packages/microsoft_sqlserver/_dev/deploy/docker/Dockerfile
packages/sql_input/_dev/deploy/docker/docker-compose.yml

Update the bin directory for `sqlcmd` because for 2019-latest the directory has changed and also how it works. Please see [this](https://github.com/elastic/integrations/issues/10889#issuecomment-2310917114) comment and [this](https://github.com/elastic/integrations/issues/10889#issuecomment-2314312934) comment for more details. As this is a change that affects only development, no CHANGELOG entry is needed.
- Closes #10889

packages/microsoft_sqlserver: Fix `HEALTHCHECK`

---

packages/microsoft_sqlserver/_dev/build/docs/README.md
packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/docs/README.md
packages/microsoft_sqlserver/manifest.yml

This update to the MSSQL integration documentation includes information indicating that, by default, the system-level database `transaction_log` metrics for SQL Server instances are collected. Metrics for user-level databases can be collected either by specifying a list of user databases or, alternatively, by enabling the `Fetch from all databases` toggle to collect metrics from all databases on the server.

packages/microsoft_sqlserver: Update documentation

---

packages/kibana/changelog.yml
packages/kibana/data_stream/status/fields/fields.yml
packages/kibana/data_stream/status/sample_event.json
packages/kibana/docs/README.md
packages/kibana/manifest.yml

https://github.com/elastic/beats/pull/40275 added some new fields to the `status` metricset of the `kibana` module, but they are missing in the `kibana` integration
See title
Closes https://github.com/elastic/integrations/issues/10623

Adding missing fields in the status metricset of the kibana integration

---

packages/cisco_ios/changelog.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-parsing-issue-5150.log
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-parsing-issue-5150.log-expected.json
packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ios/manifest.yml

Fix CISCO-IOS integration failed to parse logs coming from different application versions.
This fixes yet another SDH coming from the user that provided yet another sample of logs that have a different format.
@pkoutsovasilis I noticed the difference in the expected output files between 8.15 and 8.16 version of the stack when running the pipeline tests. Few files for the community_id added when running pipeline test against 8.16:
```
"network": {
"community_id": "1:NCx7UOZoQUvxIB+uzqMmGnZTSzI=",
```
Assuming this might be expected due to this change https://github.com/elastic/elasticsearch/pull/111528. But wanted to get your 👀  on this in case if this is not expected from Elasticsearch side.
This PR includes the files regenerated with 8.15 at the moment. Will see if CI complains, then can …

[cisco_ios] Fix CISCO-IOS integration failed to parse logs coming from different application versions

---

packages/jamf_protect/changelog.yml
packages/jamf_protect/data_stream/alerts/_dev/test/pipeline/test-jamf-protect-alerts-sample-logs.log-expected.json
packages/jamf_protect/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/jamf_protect/data_stream/alerts/fields/base-fields.yml
packages/jamf_protect/data_stream/alerts/sample_event.json
packages/jamf_protect/docs/README.md
packages/jamf_protect/kibana/dashboard/jamf_protect-e9b86210-c65c-11ee-882f-57f79af43d7f.json
packages/jamf_protect/manifest.yml

jamf_protect: fix up dashboard filters

---

packages/nginx_ingress_controller/changelog.yml
packages/nginx_ingress_controller/data_stream/access/fields/fields.yml
packages/nginx_ingress_controller/docs/README.md
packages/nginx_ingress_controller/manifest.yml

- WHAT: In this [PR](https://github.com/elastic/integrations/pull/10293) I've changed type of the `remote_ip_list` from `array` (this type is not available anymore) to `ip`, that introduce a breaking change, but it should be a `keyword`
- WHY:  2 reasons: to revert introduced breaking change; align with the nginx package `remote_ip_list` [field](https://github.com/elastic/integrations/blob/main/packages/nginx/data_stream/access/fields/fields.yml#L4-L7)
-

[Nginx_ingress_controller] fix nginx_ingress_controller.access.remote_ip_list field mapping

---

packages/abnormal_security/changelog.yml
packages/abnormal_security/data_stream/threat/agent/stream/cel.yml.hbs
packages/abnormal_security/data_stream/threat/sample_event.json
packages/abnormal_security/docs/README.md
packages/abnormal_security/manifest.yml

Type of change
- Bug
When we receive empty threat data, CEL stores the `worklist` as `{"total": 0, "threats": [], "pageNumber": 1}` instead of an empty object `{}`. As a result, in the next interval, the condition `size(state.worklist) > 0` evaluates to true, preventing the CEL from making REST calls to the `/threats` endpoint and causing it to get stuck in a loop until it is restarted.
To address this issue, we updated the condition to `size(state.worklist.threats) > 0` for the `threat` data stream, ensuring that empty threat arrays are handled correctly and REST calls continue during subsequent intervals.
- Move to integrations/packages/abnormal_security directory.
- Run the …

[abnormal_security] Update data-collection to handle empty threats

---

.buildkite/pipeline.schedule-daily.yml
.buildkite/pipeline.yml
.buildkite/scripts/common.sh
dev/testsreporter/_static/summary.tmpl
dev/testsreporter/format.go
dev/testsreporter/format_test.go
dev/testsreporter/packageerror.go
dev/testsreporter/testsreporter.go
dev/testsreporter/testsreporter_test.go
magefile.go

Moved from https://github.com/elastic/integrations/pull/10919.
Add a new daily build with logsdb enabled for logs data streams.

Add daily build with logsdb enabled

---

.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml

Enable Elastic Agent wolfi images for CI pipelines ([PRs](https://buildkite.com/elastic/integrations) and [daily](https://buildkite.com/elastic/integrations-schedule-daily/) jobs) except for [weekly](https://buildkite.com/elastic/integrations-schedule-weekly/) job.
Weekly pipeline:
https://github.com/elastic/integrations/blob/d5f72523ef4d33b3cef93ce35697cd28acc310e3/.buildkite/pipeline.schedule-weekly.yml#L26
[Integrations serverless job](https://buildkite.com/elastic/integrations-serverless) would run also these wolfi docker images, but currently system tests are not executed in those builds:
https://github.com/elastic/integrations/blob/d5f72523ef4d33b3cef93ce35697cd28acc310e3/.buildkite/scripts/common.sh#L806-L827
-

[CI] Enable wolfi images in CI except weekly builds

---

.buildkite/scripts/common.sh
dev/codeowners/codeowners.go
dev/codeowners/codeowners_test.go
dev/testsreporter/packageerror.go
dev/testsreporter/packageerror_test.go
dev/testsreporter/testsreporter.go

Refactor in testsreporter and codeowner tools to remove PackageOwnersCustomCodeowners function. By default, testsreporter it will use `.github/CODEOWNERS` file.
Currently, that function was just used in testsreporter.

Refactor testsreporter tool

---

magefile.go

Call directly to the method instead of using `Deps`. I don't think we need to call it as a dependency.

[CI] Fix call to testsreporter check

---

packages/f5_bigip/changelog.yml
packages/f5_bigip/data_stream/log/_dev/test/pipeline/test-pipeline-bigip-asm.log-expected.json
packages/f5_bigip/data_stream/log/elasticsearch/ingest_pipeline/pipeline_bigipasm.yml
packages/f5_bigip/manifest.yml

Fix ASM script processor when `event.original` is absent.
There are cases when logstash is involved, the `event.original` is missing 
even when `preserve_original_event` is enabled. This leads to one of the ASM 
script processor to fail. This script processor doesn't have null-check on 
`event.original` field which leads to the error.
This PR adds a null-check on `event.original` field to prevent this error.
**(Note for reviewers: Change best viewed with `Hide whitespace`)**

f5_bigip: Fix ASM script processor when `event.original` is absent.

---

packages/proofpoint_on_demand/changelog.yml
packages/proofpoint_on_demand/data_stream/audit/fields/fields.yml
packages/proofpoint_on_demand/docs/README.md
packages/proofpoint_on_demand/manifest.yml

Same change as https://github.com/elastic/integrations/pull/11016 that I forgot to apply to this package.
Adapt definitions of subfields of nested objects so they are actually installed by Fleet. New mappings are otherwise equivalent.
These mappings were correctly defined as expected by the spec, but Fleet was only installing empty nested objects. To workaround that, subfields can be moved to have their own definitions.
Issue in Fleet is fixed in https://github.com/elastic/kibana/pull/191730, but we can apply this workaround for older versions of the stack.

[proofpoint_on_demand] Adapt definitions of nested subfields

---

packages/bitdefender/changelog.yml
packages/bitdefender/data_stream/push_notifications/_dev/test/pipeline/test-push-notification-jsonrpc.json-expected.json
packages/bitdefender/data_stream/push_notifications/_dev/test/pipeline/test-push-notification.json-expected.json
packages/bitdefender/data_stream/push_notifications/elasticsearch/ingest_pipeline/default.yml
packages/bitdefender/manifest.yml

The .filePaths, .fileSizes and .remediationActions fields are correlated arrays, so ensure that empty actions are not removed from the array to maintain their cardinality relationships.
-

bitdefender: ensure remediation actions are correlated with their file paths

---

packages/apache/changelog.yml
packages/apache/data_stream/access/agent/stream/log.yml.hbs
packages/apache/data_stream/access/manifest.yml
packages/apache/manifest.yml

Please label as enhancement
Currently, there is no option for ignoring events older than X. This can be problematic, if there are hundreds of gigabytes of historical logfiles, that cannot be deleted, but shall not be ingested in Elastic.'
In more detail: We have apache as an internal core reverse-proxy and save the access logs on a fileshare, where elastic agent should ingest them. However some production environments have an uncompressed volume size of up to 227 GB, which currently should not all be ingested into Elastic, as there might be other retention periods as we currently have on our fileshare.
Therefore this option should prevent the ingestion of those old files, and should be configurable the same way, as it is already possible in the custom log integration.

Provide support of configuring ignore_older events in apache access-logs

---

packages/carbon_black_cloud/changelog.yml
packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
packages/carbon_black_cloud/data_stream/asset_vulnerability_summary/agent/stream/cel.yml.hbs
packages/carbon_black_cloud/data_stream/audit/agent/stream/cel.yml.hbs
packages/carbon_black_cloud/manifest.yml

```
[carbon_black_cloud] Return full state in CEL program results
Returning state with relevant field overridden resolves the problem of
losing `state.api_key` for later evaluations.
```

[carbon_black_cloud] Return full state in CEL program results

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/manifest.yml

Regarding #10577, while the field missing is indeed an issue, the pipeline should still not error. This adds functionality the other pipelines already implement to the ones missing them, to check if json.id.time exists before running the date processor. 
Alternatively, if json.id.time is missing, just drop the entire event as malformed.
- Relates #10577 
n/a

[google_workspace] handle json.id.time missing

---

packages/ti_crowdstrike/changelog.yml
packages/ti_crowdstrike/data_stream/intel/agent/stream/cel.yml.hbs
packages/ti_crowdstrike/data_stream/ioc/agent/stream/cel.yml.hbs
packages/ti_crowdstrike/manifest.yml

```
[ti_crowdstrike] Fix intel pagination bug caused by cursor formatting
Integer numbers of 1 million or more should be cast to int before
they're cast to string so that they are not formatted with an exponent.
The second example below shows how the timestamp used in the intel
filter condition was being misformatted:
mito -data <(echo '{"n": 1725646291}') <(echo 'state.n')
mito -data <(echo '{"n": 1725646291}') <(echo 'string(state.n)')
mito -data <(echo '{"n": 1725646291}') <(echo 'string(int(state.n))')
```

[ti_crowdstrike] Fix intel pagination bug due to cursor formatting

---

packages/entityanalytics_entra_id/changelog.yml
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/system/test-default-config.yml
packages/entityanalytics_entra_id/data_stream/entity/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_entra_id/data_stream/entity/manifest.yml
packages/entityanalytics_entra_id/manifest.yml

- Depends elastic/beats#40487
- Closes #10498

entityanalytics_entra_id: add support for request trace logging

---

packages/citrix_adc/changelog.yml
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-sslvpn-message.log
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-sslvpn-message.log-expected.json
packages/citrix_adc/data_stream/log/elasticsearch/ingest_pipeline/native.yml
packages/citrix_adc/manifest.yml

[citrix_adc] Improve handling of SSLVPN Message
Handle the following log 
```
<135> 09/09/2024:14:13:39 PRODSY3VPX01 0-PPE-0 : default SSLVPN Message 30461998 0 : "[Remote ip = 109.117.241.115:5019] {ns_handle_free_resources:13910} freeing sta resource for pcb:{src-ip:port=109.117.241.115:5019} <-> {dst-ip:port=75.60.204.46:443} pcbdevno=0xa14452, user_domain=(, ns_aaa->csg_flags=0x400"
```
This king of format, namely ```SSLVPN Message``` doesn't seem to be documented:
https://developer-docs.netscaler.com/en-us/netscaler-syslog-message-reference/current-release.html
but that's what we got from one of the users
The message substring looks like a freetext (debug?) message that we are not attempting to parse in this case.
The message is still preserved in ```citrix.extended.message``` field. …

[citrix_adc] Improve handling of SSLVPN Message

---

packages/azure_functions/_dev/build/docs/README.md
packages/azure_functions/docs/README.md

This PR adds a new section on the different hosting plans for Azure Functions metrics.
Closes [#123](https://github.com/elastic/integrations/issues/9010)

[DOCS] Add new section on Azure Functions hosting plans

---

packages/claroty_ctd/changelog.yml
packages/claroty_ctd/data_stream/event/agent/stream/tcp.yml.hbs
packages/claroty_ctd/data_stream/event/agent/stream/udp.yml.hbs
packages/claroty_ctd/manifest.yml

See title.
Fix is only for v8.16 (other versions are unaffected) and depends on elastic/beats#40751 — tested by injection.
- Fixes #11034
- Fixes #11035

claroty_ctd: fix replacement configuration

---

packages/cyberarkpas/changelog.yml
packages/cyberarkpas/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/cyberarkpas/manifest.yml

Rather than allocating a char[] to iterate over, just iterate over the bytes of the string.
- Closes #8307

cyberarkpas: improve efficiency of event.duration calculation

---

packages/entityanalytics_okta/_dev/deploy/docker/files/config.yml
packages/entityanalytics_okta/changelog.yml
packages/entityanalytics_okta/data_stream/user/_dev/test/pipeline/test-user.json
packages/entityanalytics_okta/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_okta/data_stream/user/fields/fields.yml
packages/entityanalytics_okta/docs/README.md
packages/entityanalytics_okta/manifest.yml

entityanalytics_okta: map group fields and add test infrastructure

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/pipeline/test-asset-host-detection.log-expected.json
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
packages/qualys_vmdr/data_stream/knowledge_base/sample_event.json
packages/qualys_vmdr/data_stream/user_activity/sample_event.json
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

…ection.vulnerability.qds_factors`
In this version `5.1.0`, the following changes have been made:
- Set `vulnerability.score.base` field based on the item *CVSS* item under field `qualys_vmdr.asset_host_detection.vulnerability.qds_factors`
- Set `vulnerability.classification` field to *CVSS*
- Set `vulnerability.severity` field based on `vulnerability.score.base`
- Set `vulnerability.scanner.vendor` field to *Qualys*
- Set `vulnerability.score.version` field based on the item *CVSS_vector* item under field `qualys_vmdr.asset_host_detection.vulnerability.qds_factors`
-

Set vulnerability ECS field based on Qualys data

---

.buildkite/scripts/build_packages.sh
.buildkite/scripts/find_oldest_supported_version.py

Fix script in charge of retrieving the oldest supported version of the stack to use for `elastic-package stack up -v -d --version <version>` command.
Without the fix there were packages that the stack version assigned was `8.x-SNAPSHOT`, but the script should return the version in the manifest since it is older than the ones available in the artifacts-api response:
Example:
``` 
Manifest ^8.13.0 -> script 8.13.0 	[keycloak]
Manifest ^8.13.0 -> script 8.13.0 	[httpjson]
Manifest ^8.13.0 -> script 8.13.0 	[vectra_detect]
Manifest ^8.3.0 -> script 8.x-SNAPSHOT 	[fortinet_fortimail]
Manifest ^8.8.0 -> script 8.x-SNAPSHOT 	[juniper_junos]
Manifest ^8.7.1 -> script 8.x-SNAPSHOT 	[hid_bravura_monitor]
Manifest ^8.13.0 -> script 8.13.0 	[keycloak]
Manifest ^8.13.0 -> script 8.13.0 	[httpjson] …
```

[CI] Fix script that retrieves oldest supported version

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/agent/stream/azure.yml.hbs
packages/cloud_asset_inventory/data_stream/asset_inventory/agent/stream/gcp.yml.hbs
packages/cloud_asset_inventory/manifest.yml

This PR re-introduces Azure and GCP options for Asset Inventory for Kibana versions matching `^8.16.0`.
Follow-up to https://github.com/elastic/integrations/pull/11091

[Cloud Security][Asset Inventory] Restore Azure and GCP streams for ^8.16

---

.github/workflows/updatecli/updatecli.d/bump-latest-snapshot-version.yml

Update `updatecli` configuration to use the new URL to retrieve the 8.x SNAPSHOT builds for the daily and weekly pipeline definitions.
- Relates https://github.com/elastic/elastic-package/pull/2103
- Depends on https://github.com/elastic/integrations/pull/11126

[CI] Update updatecli configuration for 8.x SNAPSHOT

---

.buildkite/scripts/build_packages.sh
.buildkite/scripts/common.sh
.buildkite/scripts/find_oldest_supported_version.py

Remove dependencies that are already defined in go.mod when calling with_mage in buildkite scripts.
-

[CI] [backport-security_detection_engine-8.12] Remove mage install deps

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/data_stream/result/fields/osquery.yml
packages/osquery_manager/manifest.yml

Upgrade osquery to 5.13.1
The mapping is generated from osquery 5.13.1 schema
- Relates https://github.com/elastic/beats/pull/40849

[osquery_manager] Upgrade osquery to 5.13.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.17.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2d9aba4ad853be73acd30a6f154a6e766d047908
None
None

[Security Rules] Update security rules package to v8.13.17

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/74d7e2422ee7357c13015144fcab67391c5fb329
None
None

[Security Rules] Update security rules package to v8.14.11

---

packages/cloud_asset_inventory/manifest.yml

Add template URL variables to all streams. The URLs will be used by Kibana the same way they are used in CSPM - to redirect user straight to cloud provider's deployment page.
Related to https://github.com/elastic/security-team/issues/10320

[Cloud Security][Asset Inventory] Add template variables to all input streams

---

packages/fortinet_fortiproxy/changelog.yml
packages/fortinet_fortiproxy/manifest.yml
packages/watchguard_firebox/changelog.yml
packages/watchguard_firebox/manifest.yml

- Release fortinet_fortiproxy and watchguard_firebox as GA
- Relates #10985
- Relates #11005

GA Deployment and Devices integrations

---

packages/stormshield/changelog.yml
packages/stormshield/data_stream/log/_dev/test/pipeline/test-firewall.log-expected.json
packages/stormshield/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/stormshield/data_stream/log/fields/ecs.yml
packages/stormshield/data_stream/log/sample_event.json
packages/stormshield/docs/README.md
packages/stormshield/manifest.yml

- Use stormshield.time for `@timestamp`
- Use stormshield.starttime for event.start
- Move stormshield.msg to message
- Release integration as GA
```
cd packages/stormshield
```
- Relates #10985
- Relates #11005

[stormshield] Fix timestamp fields, move stormshield.msg to message

---

packages/carbon_black_cloud/_dev/build/docs/README.md
packages/carbon_black_cloud/changelog.yml
packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
packages/carbon_black_cloud/docs/README.md
packages/carbon_black_cloud/manifest.yml

carbon_black_cloud: ensure alert search range is a valid temporal ordering

---

packages/cisco_aironet/changelog.yml
packages/cisco_aironet/data_stream/log/fields/ecs.yml
packages/cisco_aironet/docs/README.md
packages/cisco_aironet/manifest.yml

Add ECS mapping for the `destination.port` field (`long` type).
Users reported mapping exceptions due to `destination.port` string values causing field mapping as `keyword` instead of `long`. See the related issue.
Elasticsearch maps a field as a `keyword` if it has a string value. This happens even on stack versions 8.13+ because ecs@mappings does not perform type coercion.
By adding the `destination.port` field to the file `fields/ecs.yml`, we ensure Elasticsearch uses the expected ECS field mapping as `long` even when the value is a string. 
IMPORTANT: To fully resolve the issue, the input/integration owner should update it to emit the right value type to leverage ecs@mappings.
- Relates https://github.com/elastic/integrations/issues/10848

cisco_aironet: add ECS mapping for destination.port

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
packages/kubernetes/manifest.yml

- WHAT: Use filestream fingerprint mode by default for container_logs datastream
- WHY:  Avoid logs duplication
-

[Kubernetes] Use filestream fingerprint mode by default for container_logs datastream

---

packages/vsphere/changelog.yml
packages/vsphere/data_stream/network/fields/fields.yml

- Bug
Events are dropped because of network.name is not dimensioned.

[vSphere][network] fix issue with TSDB network name

---

packages/pfsense/changelog.yml
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-snort.log
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-snort.log-expected.json
packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/snort.yml
packages/pfsense/data_stream/log/fields/fields.yml
packages/pfsense/docs/README.md
packages/pfsense/manifest.yml

Add SNORT log processing
Didn't have any data samples in the original issue https://github.com/elastic/integrations/issues/10558, so had to look around and invent a couple.
It was not clear how to map some of the snort fields to ECS, mapped what was obvious and have put the rest under ```"snort"``` field similar to how it was done for ```"squid"``` logs.
- Closes https://github.com/elastic/integrations/issues/10558

[pfsense] Add SNORT log processing

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/o365/manifest.yml
packages/sentinel_one_cloud_funnel/changelog.yml
packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-dns.yml
packages/sentinel_one_cloud_funnel/manifest.yml
packages/sysmon_linux/changelog.yml
packages/sysmon_linux/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/sysmon_linux/manifest.yml
packages/system/changelog.yml
packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
packages/system/manifest.yml
packages/windows/changelog.yml
packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml
packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
packages/windows/manifest.yml

Make sure that the prefix of the IP address is ::ffff in all cases.
- Ref #10801

o365,sentinel_one_cloud_funnel,sysmon_linux,system,windows: tighten ipv4 extraction

---

.buildkite/scripts/find_oldest_supported_version.py

Add support in `find_oldest_supported_version.py` script to return the version as is when that version does not exist, but exist a next patch (newer) version.
Currently, `8.13.0` version is not part of the `versions`  reported in the artifacts-api response. But that Elastic stack version exists.
Before:
```
Manifest ^8.13.0 -> script 8.x-SNAPSHOT 	[keycloak]
Manifest ^8.13.0 -> script 8.x-SNAPSHOT 	[httpjson]
Manifest ^8.13.0 -> script 8.x-SNAPSHOT 	[vectra_detect]
Manifest ^8.3.0 -> script 8.3.0 	[fortinet_fortimail]
```
After:
```
Manifest ^8.13.0 -> script 8.13.0 	[keycloak]
Manifest ^8.13.0 -> script 8.13.0 	[httpjson]
Manifest ^8.13.0 -> script 8.13.0 	[vectra_detect]
Manifest ^8.3.0 -> script 8.3.0 	[fortinet_fortimail]
```
<details>
<summary>Current example of …

[CI] Update find oldest supported script

---

packages/carbon_black_cloud/changelog.yml
packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
packages/carbon_black_cloud/manifest.yml

When using the cursor value, the start expression in the range macro is a string since state.cursor.last_backend_update_timestamp is a string. This results in a comparison of range.start (string) with range.end (timestamp) which is not a valid type match for the \< operator. So we end up with a "no such overload". If the value is optional.none, we use delayed (timestamp) which is the correct type. Ensure that the expression is always a timestamp by doing a conversion on the resulting value, noting that a timestamp(timestamp(x)) is valid if timestamp(x) is.
-

carbon_black_cloud: fix timestamp type when using cursor value

---

packages/forgerock/_dev/deploy/docker/files/config.yml
packages/forgerock/changelog.yml
packages/forgerock/data_stream/am_access/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/am_access/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/am_activity/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/am_activity/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/am_authentication/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/am_authentication/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/am_config/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/am_core/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/idm_access/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/idm_access/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/idm_activity/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/idm_activity/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/idm_authentication/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/idm_authentication/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/idm_config/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/idm_config/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/idm_core/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/idm_core/agent/stream/httpjson.yml.hbs
packages/forgerock/data_stream/idm_sync/_dev/test/system/test-default-config.yml
packages/forgerock/data_stream/idm_sync/agent/stream/httpjson.yml.hbs
packages/forgerock/manifest.yml

```
The Forgerock API requires that the time range query satisfy three rules[1]. We
were not satisfying the last rule, that the end of the range must not be more
than 24 hours after the start of the range.
The API does not require that the end of the range must not be in the future, so
change the end time template to always render as the start of the range plus 24
hours.
The current tests do not correctly set the pagination token in some cases, and
in all cases the stream mock does not restrict queries that do not contain a
token from re-initiating a pagination cycle. Fix both of these and apply event
count assertions.
[1]https://backstage.forgerock.com/docs/idcloud/latest/tenants/audit-debug-logs.html#get-log-results-for-a-time-period
```
- Fixes #11220

forgerock: fix handling of query time ranges

---

packages/azure_metrics/_dev/build/docs/README.md
packages/azure_metrics/changelog.yml
packages/azure_metrics/docs/README.md
packages/azure_metrics/manifest.yml

This PR adds a section to the [Azure Resource Metrics](https://docs.elastic.co/integrations/azure_metrics) page to distinguish generic vs specialized integrations.
Fixes https://github.com/elastic/integration-docs/issues/376

[Azure docs] Clarify generic vs specialized integrations

---

packages/vsphere/changelog.yml
packages/vsphere/manifest.yml

- Enhancement
- Update package version.
- Move to integrations/packages/vsphere) directory.
- Run the following command to run tests. elastic-package test
- https://github.com/elastic/obs-integration-team/issues/6

[vSphere] Release new integration version.

---

packages/carbon_black_cloud/changelog.yml
packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
packages/carbon_black_cloud/manifest.yml

```
[carbon_black_cloud] Fix alert_v7 CEL pagination logic
When using the CEL input for the `alert_v7` data stream, data would
load very slowly for two reason:
- The page size defaulted to 20 results.
- The `want_more` flag was incorrectly set to false.
The response body has the fields `num_found` and `num_available`.
The `num_found` field gives the total number of results matching the query.
The `num_available` filed is equal to `min(num_found, 10000)`.
Now `want_more` is true if `num_found` is less than the page size, so it
will keep fetching more until less than a full page of results are found.
The page size is increased from 20 (the default) to 100.
```
I tested this manually.
When no results are found, the `num_found` field is returned with the value `0`, so the pagination condition …

[carbon_black_cloud] Fix alert_v7 CEL pagination logic

---

.github/CODEOWNERS
packages/elastic_connectors/manifest.yml

As part of the GitHub teams renaming initiative, it's required to rename the @elastic/ingestion-team to @elastic/search-extract-and-transform.
This PR is dedicated to renaming @elastic/ingestion-team to @elastic/search-extract-and-transform

Rename the ingestion-team

---

packages/checkpoint/_dev/build/docs/README.md
packages/checkpoint/changelog.yml
packages/checkpoint/docs/README.md
packages/checkpoint/manifest.yml

- Documentation update to remove EOL OS version R80.X from the list of supported versions.
- #10977

[checkpoint] Drop support for EOL OS version R80.X

---

packages/cloud_security_posture/manifest.yml

this PR makes `cloud_security_posture` available on ESS `9.0.0` deployments
- related https://github.com/elastic/package-registry/issues/1226

[Cloud Security][Cloud Security Posture] Update kibana condition

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

https://github.com/elastic/integrations/pull/11252 updated the kibana condition to include `^9.0.0` but did not add a changelog entry or bump the package version. this is what this PR does.

[Cloud Security][Cloud Security Posture] Bump package

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.23.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/08028185e8d6b3eb0a30b714c57dcf32686b8c68
None
None

[Security Rules] Update security rules package to v8.12.23

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.18.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/1bff37a47915ef67d733543eb35a0770caef49e9
None
None

[Security Rules] Update security rules package to v8.13.18

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/82609b828b63f6807d80af062b2fdb42fec0100b
None
None

[Security Rules] Update security rules package to v8.14.12

---

packages/tychon/changelog.yml
packages/tychon/manifest.yml

Add the security capability to the tychon package, this package fails to start in deployments without security plugins:
```
Error: can't install the package: could not zip-install package; API status code = 400; response body = {"statusCode":400,"error":"Bad Request","message":"Encountered 17 errors creating saved objects: [{\"type\":\"security-rule\",\"id\":\"0c5a9660-eaa9-11ee-a30d-e7740197132d\",\"error\":{\"type\":\"unsupported_type\"}},{\"type\":\"security-rule\",\"id\":\"10359860-1139-11ee-af86-538da1394f27\",\"error\":{\"type\":\"unsupported_type\"}},{\"type\":\"security-rule\",\"id\":\"2140f083-6e39-4df4-ba41-aa1f41cb81b8\",\"error\":{\"type\":\"unsupported_type\"}}...
```
Thanks @mrodm for reporting!

Add the security capability to the tychon package

---

packages/elastic_connectors/agent/input/github.yml.hbs
packages/elastic_connectors/agent/input/google_drive.yml.hbs
packages/elastic_connectors/changelog.yml
packages/elastic_connectors/manifest.yml

Update connector package definition to pass `connector_name` as input variable for the package logic. 
- Since agentless package is not public yet, ping @jedrazb for steps

[Elastic Connectors] Add index name as input var

---

packages/aws/changelog.yml
packages/aws/manifest.yml

We have "2.25.0" version released and the next prerelease version should be at least `2.26.0-preview01` instead of `2.25.0-preview01`. It's not correct to have a prerelease of a version already released.

Fix aws release version

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

Add missing `resource.timeout` to CEL input.
Although the parameter `resource_timeout` is defined in `manifest.yml`, 
it is missing from the input file. This PR adds `resource.timeout` to input.

o365: Add missing `resource.timeout` to CEL input.

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.24.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e6c968f2a9c31f9934c260d7fa7f9bf602160834
None
None

[Security Rules] Update security rules package to v8.12.24

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/7750e57bc76bd54885e1d1f950f347e0d8d1cfe6
None
None

[Security Rules] Update security rules package to v8.15.7

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8a1e0d96dcfe3993461b8169d6d85598a109ea69
None
None

[Security Rules] Update security rules package to v8.14.13

---

packages/aws/data_stream/firewall_logs/_dev/test/system/test-default-config.yml

A possible fix for flaky system test. 
This PR increases wait time for data retrieval.
- Relates: https://github.com/elastic/integrations/issues/11088

aws.firewall_logs: flaky-test: Increase wait time for data.

---

packages/wiz/changelog.yml
packages/wiz/elasticsearch/transform/latest_cdr_misconfigurations/transform.yml
packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
packages/wiz/manifest.yml

Increase retention policy to 90 days on Wiz transforms to cater for how Wiz evaluates environments for posture. In contrast to native CSP integration Wiz doesn't do regular full re-evaluation of customer environments, that's why short retention period mean customers having only a small slice of their posture. The change will go together with documentation on how to get more complete view for the posture using longer initial interval setting value
Build and install integration, ingest some data from Wiz, check that latest index contains documents without 90d period
- Relates https://github.com/elastic/security-team/issues/10683

[Cloud Security] increase transfom retention_policy to 90 days for Wiz

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_ad/data_stream/user/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_ad/manifest.yml
packages/entityanalytics_entra_id/changelog.yml
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-device.json-expected.json
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-users.json-expected.json
packages/entityanalytics_entra_id/data_stream/entity/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_entra_id/manifest.yml
packages/entityanalytics_okta/changelog.yml
packages/entityanalytics_okta/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_okta/data_stream/user/sample_event.json
packages/entityanalytics_okta/docs/README.md
packages/entityanalytics_okta/manifest.yml

The event.action field is an implementation detail that has an unfortunate name that could mislead users; the values held for entities do not relate to security details, but only to internal accounting. So remove them.
-

entityanalytics_{ad,entra_id,okta}: don't include input-private details to index

---

packages/auditd_manager/_dev/build/docs/README.md
packages/auditd_manager/changelog.yml
packages/auditd_manager/data_stream/auditd/agent/stream/auditd.yml.hbs
packages/auditd_manager/data_stream/auditd/manifest.yml
packages/auditd_manager/docs/README.md
packages/auditd_manager/manifest.yml

This PR reverts the Session Data option introduced on [this](https://github.com/elastic/integrations/pull/11336) PR.
The revert is needed because the `1.8.0` version relies on the `escape_multiline_string` helper that was introduced in Kibana in [this](https://github.com/elastic/kibana/pull/195159) PR. 
It fixes the error below when attempting to save the Auditd Manager integration version `1.8.0` in Serverless environments that don't contain the [Kibana](https://github.com/elastic/kibana/pull/195159) changes:
Reasoning:
1.8.0 manifest was set to be enabled Starting on Kibana 8.16+, but serverless release cadences follow a different cadence and it's on version 9.0.0 already, therefore  [this Kibana PR](https://github.com/elastic/integrations/pull/11336) must be deployed on serverless in …

[AuditdManager] Reverting Session Data option

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.25.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/072a8c99de78c504c4f87aea5d5fc5786f688696
None
None

[Security Rules] Update security rules package to v8.12.25

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/0591fe53a661f68afa05b5a68812c10b26d5e400
None
None

[Security Rules] Update security rules package to v8.15.8

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/163281c3a8c63267938f279e39be5a0aa7d44b13
None
None

[Security Rules] Update security rules package to v8.14.14

---

packages/cisco_duo/_dev/deploy/docker/files/config.yml
packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/auth/_dev/test/system/test-default-config.yml
packages/cisco_duo/data_stream/auth/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

```
We cannot guarantee the shape of body.message and body.message_detail, so just
include the known type resp.Body which should be short in the case of a
non-200 response.
The next_offset value is documented to be an array of two elements which must
be used to construct the parameter by concatenation with a separating comma[1].
[1]https://duo.com/docs/adminapi#authentication-logs
```
- Fixes #11405

cisco_duo: include error response body when non-200 and fix next_offset handling

---

packages/kubernetes_otel/changelog.yml
packages/kubernetes_otel/manifest.yml

Change `format_spec` in the `kubernetes_otel` package to 3.3.0 as support for content packages is added to `3.3.0`. 
Related to https://github.com/elastic/package-spec/pull/818

Change format_spec in the kubernetes_otel package to 3.3.0

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/admin/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/auth/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/auth/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/offline_enrollment/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/summary/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/telephony/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/telephony_v2/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

```
[cisco_duo] Set request rate limits
The Duo Admin API has rate limiting. It doesn't return rate limit
headers, but it does enforce limits with HTTP 429 responses.
For some endpoints, the API documentation specifies "a rate limit of 50
calls per minute". This as also been observed on the authentication
logs endpoint.
This changes sets a limit of 0.5 calls/second or 30 calls per minute
for all data streams and inputs.
HTTP 429 responses continue to be treated as errors.
API documentation: https://duo.com/docs/adminapi
```
I considered returning `{ "events": [], "want_more": false }` when a 429 response is received, however, with the new settings we expect to never exceed the limit, and if the limit is repeatedly exceeded, treating it as an error will help with troubleshooting.

[cisco_duo] Set request rate limits

---

packages/kubernetes_otel/changelog.yml
packages/kubernetes_otel/kibana/dashboard/kubernetes_otel-cluster-overview.json
packages/kubernetes_otel/manifest.yml

WHAT: Removing the events from overview dashboard
WHY: https://github.com/elastic/opentelemetry-dev/issues/469
This version includes some resizing of visualisations in ordeto make UX more friendly to smaller display analysis

Remove events from Otel Kubernetes General Dashboard

---

packages/cisco_duo/_dev/deploy/docker/files/config.yml
packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/auth/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

```
[cisco_duo] Fix auth CEL cursor handling
In the auth CEL program, the error `type conversion error from 'string'
to 'int'` seems to have been happening because of
`cursor.last_published` being set to a value of the form
`1532951895000,af0ba235-0b33-23c8-bc23-a31aa0231de8`, which can't be
parsed as an int.
Now `cursor.last_published` is replaced with `cursor.last_timestamp_ms`,
which is taken from the last result, and so will be available if the
last page of sequence has results but no value in
`response.metadata.next_offset`.
Also, the date is no longer shared across requests, the request
building is simplified, and redundant overrides of state are removed.
Related documentation: https://duo.com/docs/adminapi#authentication-logs
```
It's not obvious how `cursor.last_published` would …

[cisco_duo] Fix auth CEL cursor handling

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/admin/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/auth/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/auth/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/offline_enrollment/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/summary/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/telephony/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/telephony_v2/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

```
[cisco_duo] Make rate limit configurable
```
Also moves `show_user: false` variables to the end of the list in the manifest.
- Relates #11405

[cisco_duo] Make the rate limit configurable

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/_dev/test/pipeline/test-data-duplicated-querytime-events.json
packages/o365/data_stream/audit/_dev/test/pipeline/test-data-duplicated-querytime-events.json-expected.json
packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/o365/manifest.yml

For some unknown reason we couldn't find out, some events from O365 introduces a malformed JSON object by adding a duplicated `QueryTime` field. The pattern this issue follows is:
- It only affects events with `RecordType == 64`
- The undesired `QueryTime` field doesn't follow ISO8601 format.
So the pipeline fails with:
```
"error": {
"message": [
"Duplicate field 'QueryTime'\n at [Source: (String)\"{\"Version\":\"3.0\",\"VendorName\":\"Microsoft\"...\"[truncated 11497 chars]; line: 1, column: 5099]"
]
}
```
To fix the error it was added a `gsub` processor that attempts to find the undesired `QueryTime` field and removed from the whole `Data` object. In addition, to prevent other similar issues, added a `on_failure` case when decoding the `Data` field which generally contains unknown …

o365: Fix the handling of duplicated field QueryTime

---

packages/symantec_endpoint/changelog.yml
packages/symantec_endpoint/data_stream/log/fields/ecs.yml
packages/symantec_endpoint/docs/README.md
packages/symantec_endpoint/manifest.yml

The event.duration field does not get mapped as a long, even when there is a convert processor in place, potentially resulting in a mapping conflict. So add back a field definition for the field.
- For #10848
- Ref #11104

symantec_endpoint: ensure that event.duration is mapped as a long

---

packages/cisco_ios/changelog.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ios/manifest.yml

- Add support for ISO 8601 timestamps
```
```
- Closes #11495

[cisco_ios] Add support for ISO 8601 timestamps

---

packages/auditd_manager/_dev/build/docs/README.md
packages/auditd_manager/changelog.yml
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-default.expected
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-default.yml
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer-with-audit-rules-and-processors.expected
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer-with-audit-rules-and-processors.yml
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer-with-audit-rules.expected
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer-with-audit-rules.yml
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer-with-processors.expected
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer-with-processors.yml
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer.expected
packages/auditd_manager/data_stream/auditd/_dev/test/policy/test-session-viewer.yml
packages/auditd_manager/data_stream/auditd/agent/stream/auditd.yml.hbs
packages/auditd_manager/data_stream/auditd/manifest.yml
packages/auditd_manager/docs/README.md
packages/auditd_manager/manifest.yml

- Updating Auditd Manager manifest to include Session Data option starting from Kibana version 8.16.0.
- Updated logic in the `hbs` file to append Session Data Audit Rules and Session Data Processors when Session Data is selected.
- Updated documentation to include both manual and Toggle Switch options
To test these changes, go to Kibana -> Integrations -> Create new integration -> upload it as a .zip; and upload the following package:
[auditd_manager-1.18.2.zip](https://github.com/user-attachments/files/17498523/auditd_manager-1.18.2.zip)
- Closes https://github.com/elastic/security-team/issues/10830
Session Data Switcher
Docs
Policy Tests Included

[Auditd Manager] Add Session Data option

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.21.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/0eb316bf1c4e3c58fc6657d24a842627cdb2a8e7
None
None

[Security Rules] Update security rules package to v8.13.21

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.26.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b061ee3ee842614eb84be3f05639335fca10ac17
None
None

[Security Rules] Update security rules package to v8.12.26

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/fc4283e93ad7d90a2854ce05bb82e56b4cae692e
None
None

[Security Rules] Update security rules package to v8.15.9

---

packages/1password/data_stream/audit_events/_dev/test/system/test-default-config.yml
packages/1password/data_stream/audit_events/sample_event.json
packages/1password/data_stream/item_usages/_dev/test/system/test-default-config.yml
packages/1password/data_stream/item_usages/sample_event.json
packages/1password/data_stream/signin_attempts/_dev/test/system/test-default-config.yml
packages/1password/data_stream/signin_attempts/sample_event.json
packages/1password/docs/README.md

```
The system tests for 1password place the preserve_original_event
configuration option into the the top-level vars instead of the
per data_stream vars where the variable is declared. The sample
events generated by the system tests did not contain the
'event.original' field as a result.
```

1password - fix system test preserve_original_event

---

packages/wiz/_dev/build/docs/README.md
packages/wiz/changelog.yml
packages/wiz/docs/README.md
packages/wiz/manifest.yml

Update readme to mention the fourth support data stream, Cloud Configuration Finding
- Relates https://github.com/elastic/integrations/issues/11520

Add Cloud Configuration Finding to the list of data streams in README

---

packages/jamf_protect/changelog.yml
packages/jamf_protect/data_stream/alerts/sample_event.json
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/pipeline_event_authentication.yml
packages/jamf_protect/data_stream/telemetry/sample_event.json
packages/jamf_protect/data_stream/telemetry_legacy/sample_event.json
packages/jamf_protect/data_stream/web_threat_events/sample_event.json
packages/jamf_protect/data_stream/web_traffic_events/sample_event.json
packages/jamf_protect/docs/README.md
packages/jamf_protect/manifest.yml

Type of change:
- bigfix
- Minor bug fix to the itemType for `jamf_protect.telemetry.authentication_auto_unlock_type` on the `pipeline_event_authentication.yaml`, the integer values were wrong.
- integer values are not exposed in developer documentation, only in xCode header files. https://developer.apple.com/documentation/endpointsecurity/es_auto_unlock_type_t
```
typedef enum {
/// Unlock the machine using Apple Watch.
ES_AUTO_UNLOCK_MACHINE_UNLOCK = 1,
/// Approve an authorization prompt using Apple Watch.
ES_AUTO_UNLOCK_AUTH_PROMPT = 2
} es_auto_unlock_type_t;
```
`elastic-package test system`
```
2024/10/29 16:45:41  INFO Write container logs to file: /Users/thijs.xhaflaire/Documents/GitHub/Elastic/integrations/build/container-logs/elastic-agent-1730216741120038000.log
--- Test …
```

[Jamf Protect] Minor changes to the pipeline_event_authentication

---

packages/ibmmq/_dev/build/docs/README.md
packages/ibmmq/changelog.yml
packages/ibmmq/docs/README.md
packages/ibmmq/manifest.yml

This PR updates the Compatibility section for IBM MQ integration package with the supported official container images.
Closes https://github.com/elastic/integration-docs/issues/559

[IBM MQ integration package] Update the compatibility section

---

.buildkite/pipeline.schedule-daily.yml
.github/workflows/updatecli/updatecli.d/bump-latest-8x-snapshot-version.yml

Fix updatecli automation to update also label with the Elastic stack version accordingly.
Changed that would be performed by updatecli
```diff
--- .buildkite/pipeline.schedule-daily.yml
+++ .buildkite/pipeline.schedule-daily.yml
@@ -38,7 +38,7 @@
- step: "check"
allow_failure: false
-  - label: "Check integrations local stacks - Stack Version v8.16 - LogsDB"
+  - label: "Check integrations local stacks - Stack Version v8.17 - LogsDB"
trigger: "integrations"
build:
env:
```

[CI] Update configuration to update LogsDB step label in daily job

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/data_stream/result/fields/ecs.yml
packages/osquery_manager/manifest.yml

Add mappings for ECS email fields
This addresses one of the issues with email subfields mapping specifically `email.attachments` ECS field was not specified in the package before, resulting with invalid auto generated object mapping instead of the nested field. 
Adding all of the ECS email fields mappings with this change.

[osquery_manager] Add mappings for ECS email fields

---

packages/fortinet_fortimail/changelog.yml
packages/fortinet_fortimail/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/fortinet_fortimail/manifest.yml
packages/fortinet_fortiproxy/changelog.yml
packages/fortinet_fortiproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/fortinet_fortiproxy/manifest.yml

- Change rename to set processor when setting event.timezone
- In certain situations, an add_locale processor may have run on the agent and this will set event.timezone.
```
cd packages/fortinet_fortimail
cd packages/fortinet_fortiproxy
```

Tolerate existing event.timezone in fortimail and fortiproxy

---

packages/aws/changelog.yml
packages/aws/data_stream/securityhub_findings/_dev/test/pipeline/test-securityhub-findings.log-expected.json
packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
packages/aws/data_stream/securityhub_findings/fields/ecs.yml
packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/ecs.yml
packages/aws/manifest.yml

Add `cloud.provider`, `event.kind`, and `observer.vendor` fields to 
`_source` as needed by CDR workflows.
The commit [here](https://github.com/elastic/integrations/commit/0e4409161a73e99763b266042288416edace0599#diff-c17e1251c36fc92221e2d3db57cc560bd80a4cf5d345fd18c6b646af6a458866L39) removed the fields from `_source`. But the fields are required to be 
present in `_source` for Cloud Detection and Response (CDR) workflows. This PR reverts 
the changes made in that commit and re-adds the fields into the ingest pipeline.
`cd packages/aws && elastic-package stack down && elastic-package build && elastic-package stack up --version=8.16.0-SNAPSHOT -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v --data-streams=securityhub_findings`
```
--- Test …
```

aws.securityhub_findings: Add fields to `_source` as needed by CDR workflows.

---

packages/elasticsearch/changelog.yml
packages/elasticsearch/data_stream/ingest_pipeline/fields/package-fields.yml
packages/elasticsearch/manifest.yml

Bug
Adds `elasticsearch.node.name` as a TSDS dimension to prevent document collisions.
Install assets for the Elasticsearch integration and validate that the `metrics-elasticsearch.ingest_pipeline@package` component template properly sets `elasticsearch.node.name` as `"time_series_dimension": true`
- Closes #11522

[Elasticsearch][Ingest Pipeline] Add elasticsearch.node.name as TSDS dimension

---

packages/cel/agent/input/input.yml.hbs
packages/cel/changelog.yml
packages/cel/manifest.yml

Adds `xsd` configuration option to input.

cel: Add `xsd` configuration option to input.

---

packages/salesforce/_dev/build/docs/README.md
packages/salesforce/changelog.yml
packages/salesforce/docs/README.md
packages/salesforce/manifest.yml

It seems when SF instance demands a security token, it should be added to the password field.

packages/salesforce: Update docs to reflect the use of optional security token

---

packages/wiz/changelog.yml
packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml
packages/wiz/manifest.yml

`observer.vendor` and `cloud.provider` ECS mappings missing in the cdr vulnerability latest transform destination index
- relates https://github.com/elastic/security-team/issues/11034

[Cloud Security] add missing ECS mappings to wiz cdr_latest_vulnerabilities destination index

---

packages/apache/changelog.yml
packages/apache/manifest.yml
packages/nginx/changelog.yml
packages/nginx/manifest.yml
packages/system/changelog.yml
packages/system/manifest.yml
packages/windows/_dev/build/docs/README.md
packages/windows/changelog.yml
packages/windows/docs/README.md
packages/windows/manifest.yml
packages/zeek/changelog.yml
packages/zeek/manifest.yml

- Deprecated the experimental third-party API (Splunk) import option in apache, nginx, system, windows, and zeek packages.
- Closes #11502

Deprecate experimental third-party API import option

---

packages/apache_tomcat/changelog.yml
packages/apache_tomcat/data_stream/access/_dev/test/pipeline/test-access.log
packages/apache_tomcat/data_stream/access/_dev/test/pipeline/test-access.log-expected.json
packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
packages/apache_tomcat/manifest.yml

Fix 400 bad request in localhost_access.*.log causing dissect failure on pipeline.
This change seeks to resolve defect #11514, where the dissect will fail in the event that a 400 bad request occurs by modify the ingest pipeline for Apache Tomcat localhost access logs. 
The pipeline currently does not cater for a null (-) %r, First line of the request (method and request URI) see [Tomcat 9 - Access Logging](https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Access_Logging).
To resolve this, the %r will be split out as a whole and dissected again in the event it's not null (-).
- Cloned existing pipeline "logs-apache_tomcat.access.1.5.1" within ECE deployment and modified to add in dissects and tested using the following records: 
Input Docs:
``` json
[
{
"_index": "index",
"_id": …
```

[Bug] Fix 400 bad request in localhost_access.*.log causing dissect failure on pipeline.

---

packages/microsoft_exchange_online_message_trace/changelog.yml
packages/microsoft_exchange_online_message_trace/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_exchange_online_message_trace/data_stream/log/sample_event.json
packages/microsoft_exchange_online_message_trace/docs/README.md
packages/microsoft_exchange_online_message_trace/manifest.yml

Updated to set the event.category to 'email' and type to 'info' the only supported type for this category according to https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html#ecs-event-category-email
- Enhancement
- WHAT: Currently the ingest pipeline does not set the `event.category` or `event.type` fields.
- WHY:  By having these fields set, mainly `event.category` users can easily use this with the timeline EQL.
NA

Updated ingest pipeline default.yml to set event category and type

---

packages/ti_misp/changelog.yml
packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs
packages/ti_misp/data_stream/threat/manifest.yml
packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
packages/ti_misp/data_stream/threat_attributes/manifest.yml
packages/ti_misp/manifest.yml

Adding the possibility to set the request trace limit for the TI MISP integration.
The nature of API responses that require nested splits to decode events may lead to high resource utilization in the agent, which cannot be avoided by the filters that MISP currently provides. Setting a request trace limit may help in the processing of the responses to avoid the input being overwhelmed.

ti_misp: add request rate limit

---

packages/azure/_dev/build/docs/README.md
packages/azure/changelog.yml
packages/azure/docs/README.md
packages/azure/manifest.yml

Fix an error and contradiction about how the `azure-eventhub` input uses the storage account to create containers to store the event hub checkpoint information.
The error was in this sentence:
> The Elastic Agent can use one Storage account **container** for all integrations.
It should have been:
> The Elastic Agent can use one Storage account for all integrations.
- ~~[ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~
- ~~[ ] I have verified that any added dashboard complies with Kibana's [Dashboard good …

[azure] Fix error and improve clarity in Storage Account docs

---

packages/claroty_ctd/changelog.yml
packages/claroty_ctd/data_stream/asset/agent/stream/cel.yml.hbs
packages/claroty_ctd/data_stream/baseline/agent/stream/cel.yml.hbs
packages/claroty_ctd/manifest.yml

Type of change
- Bugfix
- Fixed batch size issue in data collection for asset and baseline data-streams.
- Install the elastic package locally.
- Start the elastic stack using the elastic package.
- Move to integrations/packages/claroty_ctd directory.
```
2024/11/11 10:27:21  INFO New version is available - v0.106.0. Download from: https://github.com/elastic/elastic-package/releases/tag/v0.106.0
Run asset tests for the package
2024/11/11 10:27:21  INFO License text found in "/root/github/integrations/LICENSE.txt" will be included in package
--- Test results for package: claroty_ctd - START ---
╭─────────────┬─────────────┬───────────┬───────────────────────────────────────────── …
```

[claroty_ctd] Fixed batch size issue in data collection for asset and baseline data-streams.

---

packages/corelight/changelog.yml
packages/corelight/kibana/dashboard/corelight-45197477-c13f-4e52-a5dd-fb4f53564963.json
packages/corelight/manifest.yml

Type of change
- Enhancement
- In the Corelight ingest pipeline repository, the `inferences` field has been updated to `ssh.inferences`. Accordingly, the Secure Channel Insight dashboard queries have been modified to use `ssh.inferences`.
- Move to integrations/packages/corelight directory.

[corelight] Update inferences field to ssh.inferences for ssh log type

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.22.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/79075ecdf5d0ba220fd4203d7c57bcabccaf5e72
None
None

[Security Rules] Update security rules package to v8.13.22

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/56c0d5c595ccf4571edf7ab679619f9bcef95093
None
None

[Security Rules] Update security rules package to v8.15.10

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/5bb2a17f7082c1ecfcd12f0902bc54f6880147ae
None
None

[Security Rules] Update security rules package to v8.16.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.16.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d57a0f991a9a768da2f99f61a7295088daee7d86
None
None

[Security Rules] Update security rules package to v8.14.16

---

packages/microsoft_sqlserver/_dev/build/docs/README.md
packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/docs/README.md
packages/microsoft_sqlserver/manifest.yml

Improve documentation to elaborate more on permissions. This PR also includes some general improvements to the documentation.
- https://github.com/elastic/integrations/issues/11483

packages/microsoft_sqlserver: Improve documentation

---

packages/aws_logs/changelog.yml
packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs
packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
packages/aws_logs/data_stream/generic/manifest.yml
packages/aws_logs/manifest.yml

Remove ingest pipeline option in config for custom aws logs integration. This option does not work, whatever is put in as the value for this config parameter, was being ignored. The way to change ingest pipeline is to choose `Add custom pipeline`:
- Closes https://github.com/elastic/integrations/issues/10729

[Custom AWS logs] Remove ingest pipeline option

---

packages/proxysg/changelog.yml
packages/proxysg/data_stream/log/manifest.yml
packages/proxysg/manifest.yml

In ProxySG integration, add new log format config options to all inputs. Previously, the new formats were added to only one input.  These config values need to exist on all inputs, so all can be configured to all supported log formats.

Add log format option to all input configs

---

packages/eset_protect/changelog.yml
packages/eset_protect/data_stream/detection/agent/stream/cel.yml.hbs
packages/eset_protect/data_stream/device_task/agent/stream/cel.yml.hbs
packages/eset_protect/manifest.yml

```
eset_protect: add HTTP header identifying the integration
The ESET Protect API will be requiring an HTTP header, "3rd-integration", to
identify integrations. Documentation for the header is not currently
available, but will be at the ESET Elastic integration documentation page[1]
in the future.
[1]https://help.eset.com/eset_connect/en-US/elastic.html
```
We will see changes in our monitoring after release
No issue
-

eset_protect: add HTTP header identifying the integration

---

packages/tenable_sc/_dev/build/docs/README.md
packages/tenable_sc/changelog.yml
packages/tenable_sc/data_stream/asset/agent/stream/httpjson.yml.hbs
packages/tenable_sc/data_stream/plugin/agent/stream/httpjson.yml.hbs
packages/tenable_sc/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
packages/tenable_sc/docs/README.md
packages/tenable_sc/manifest.yml

```
It appears that the API has become more strict with the user-agent
string format that is acceptable. Using the format that was previously
in place, including the filebeat component of the string, results in a
403 unauthorized, so conform exactly to the format described in the
developer documentation.
ref:https://developer.tenable.com/docs/user-agent-header
```
> [!NOTE]
> Tested locally :white_check_mark: 
1. Install the new version of the integration (`git fetch git@github.com:efd6/integrations.git 11510-tenable_sc && git checkout FETCH_HEAD && cd packages/tenable_sc && elastic-package build`)
2. Run an elastic-package instance.
3. Go through the kibana integration install process and add a policy with your credentials.
4. Check for document ingest.
- Closes #11510

tenable_sc: update tested versions note and user agent string

---

packages/prisma_cloud/changelog.yml
packages/prisma_cloud/kibana/tags.yml
packages/prisma_cloud/manifest.yml
packages/wiz/changelog.yml
packages/wiz/kibana/tags.yml
packages/wiz/manifest.yml

Adds tags.yml to all security integrations so that dashboards and saved searches are tagged with "Security Solution", and will be shown in the Security Solution UI.
Related integrations with "Security solution" tag:
- Added
- Pre-existent
Follow these [guidelines](https://docs.elastic.dev/security-solution/cloud-security/qa/test-integration-package#build-and-test-with-the-local-elasticsearch-and-kibana) to install `elastic-package`, build the new packages and integrates them with your local ES & Kibana
- Closes https://github.com/elastic/kibana/issues/195968
- Relates to https://github.com/elastic/integrations/pull/7789 (here we're basically mimicking that change-set)
I've got no Wiz-related data locally, but I do have it for Prisma Cloud and their tags config is the same: …

Add "Security Solution" tags to security-related CDR integrations

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Add new template URL for cloudformation creates the cloud connectors remote role. 
Add a new bool variable indicating that cloud connectors are used in the integration. Cloudbeat should parse this boolean. 
- Closes https://github.com/elastic/security-team/issues/11071

CSPM: add cloud connectors support

---

packages/universal_profiling_agent/agent/input/input.yml.hbs
packages/universal_profiling_agent/changelog.yml
packages/universal_profiling_agent/manifest.yml

Add project ID as optional configuration option.

Universal Profiling Agent: add project_id

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/telephony_v2/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

For Activity and Telephony data streams, the timestamp of the last event published is stored in the cursor state as a string with the format `2024-05-23T03:06:24.755940+00:00`, leading to the following error when populating `mintime`:
```
{"log.level":"debug","@timestamp":"2024-11-18T17:02:20.338Z","message":"response state","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"log.logger":"input.cel","log.origin":{"file.line":254,"file.name":"cel/input.go","function":"github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1"},"input_url":"https://api-<>.duosecurity.com","service.name":"filebeat","id":"cel-cisco_duo.activity-<>","input_source":"https://api-<>.duosecurity.com","cel":{"ecs.version":"1 …
```

cisco_duo: fix the parsing of last_published timestamp

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_ad/data_stream/user/manifest.yml
packages/entityanalytics_ad/manifest.yml

DEPENDS STACK v8.16.0
See title.
- Closes #10952

entityanalytics_ad: expose attribute selection configuration

---

packages/httpjson/_dev/build/docs/README.md
packages/httpjson/changelog.yml
packages/httpjson/docs/README.md
packages/httpjson/manifest.yml

This PR fixes a broken link on the [Custom API](https://www.elastic.co/docs/current/integrations/httpjson) doc page pointing to [Common Expression Language input](https://www.elastic.co/docs/current/cel/overview).
Relates to https://github.com/elastic/integration-docs/pull/579

Fix broken link in Custom API using Common Expression Language

---

packages/servicenow/_dev/build/docs/README.md
packages/servicenow/changelog.yml
packages/servicenow/data_stream/event/_dev/test/pipeline/test-common-config.yml
packages/servicenow/data_stream/event/agent/stream/aws-s3.yml.hbs
packages/servicenow/data_stream/event/agent/stream/cel.yml.hbs
packages/servicenow/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/servicenow/data_stream/event/manifest.yml
packages/servicenow/data_stream/event/sample_event.json
packages/servicenow/docs/README.md
packages/servicenow/kibana/dashboard/servicenow-e6093b0d-38a6-4b05-8354-4bbaef28b667.json
packages/servicenow/manifest.yml

Type of change
- Enhancement
- Add support for the timestamp_field input from the user to store inside cursor for data retrieval after intervals and also map with the `@timestamp` field.
- Provide support for ingesting Parquet files through AWS S3 or SQS.
- Add product version in the Readme.
- Remove `logs` keyword from the description on configuration page.
- Install the elastic package locally.
- Start the elastic stack using the elastic package.
- Move to integrations/packages/servicenow directory.
```
2024/11/20 15:23:50  INFO New version is available - v0.107.1. Download from: https://github.com/elastic/elastic-package/releases/tag/v0.107.1
Run asset tests for the package …
```

[servicenow] Add product version and remove `logs` from configuration page description.

---

packages/ti_misp/changelog.yml
packages/ti_misp/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/ti_misp/data_stream/threat_attributes/elasticsearch/ingest_pipeline/default.yml
packages/ti_misp/manifest.yml

Adding a fingerprint processor for the `threat_attributes` data stream to avoid ingesting the same indicators every time a request to the API is made.
Updated the fingerprint for the `threat` data stream, by including created/updated timestamps, so subsequent updates of the indicators are also ingested.

ti_misp: update the use of fingerprint processors

---

packages/cisco_ise/changelog.yml
packages/cisco_ise/data_stream/log/_dev/test/pipeline/test-pipeline-passed-authentications.log-expected.json
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_passed_authentications.yml
packages/cisco_ise/data_stream/log/fields/fields.yml
packages/cisco_ise/docs/README.md
packages/cisco_ise/manifest.yml

[cisco_ise] Revert mapping change for cisco_av_pair that was introduced with 1.24.1
https://github.com/elastic/integrations/pull/11619/files#diff-ce8c42e24fb4e94c7fb135eed466345a68c36cb91a247069fb9ea88312f97bbbL228
The mapping change in 1.24.1 causes the error, when the user tries to use to update to this version of integration
```
mapper_exception Root causes: mapper_exception the (enabled) parameter can't be upgraded for the object mapping [cisco_ise.log.cisco_av_pair].
```
Similar issue with Okta integration that happened earlier was mentioned here 
https://support.elastic.dev/knowledge/view/1a2f83e7
and the kibana ticket
https://github.com/elastic/kibana/issues/193044
The discussed and accepted solution is:
1. Revert the mapping change with this PR (next patch release)
2. Follow up …

[cisco_ise] Revert mapping change for cisco_av_pair that was introduced with 1.24.1

---

packages/aws/_dev/build/docs/README.md
packages/aws/_dev/build/docs/inspector.md
packages/aws/changelog.yml
packages/aws/docs/README.md
packages/aws/docs/inspector.md
packages/aws/manifest.yml

`inspector2:ListFindings` is a required AWS permission for IAM users in order to avoid this error when enabling the Inspector data stream:
```
{\"message\":\"User: arn:aws:iam::123456789:user/service/elastic is not authorized to perform: inspector2:ListFindings on resource: arn:aws:inspector2:eu-west-1: 123456789:/findings/list\"}"
```
See https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoninspector2.html.
It also clarifies that `Role ARN`, which is a global setting for the AWS integration, is not supported for the Inspector data stream as it make requests to the Inspector API through HTTPJSON, while `Role ARN` is a setting for AWS-based inputs.

aws_inspector: add note about AWS Permissions and Role ARN support

---

packages/jamf_pro/_dev/build/docs/README.md
packages/jamf_pro/changelog.yml
packages/jamf_pro/docs/README.md
packages/jamf_pro/manifest.yml

The current instructions state that the Jamf webhook should be configured with a JSON object withe the auth header name in "Authorization" and the auth token in "Token". According to Jamf, this is not correct. The headers are apparently constructed from the object such that the key is the header name and the value is the header value. Reflect this in the instructions.
- Fixes #11759

jamf_pro: fix instructions for Header Authentication configuration

---

packages/prometheus/_dev/build/docs/README.md
packages/prometheus/changelog.yml
packages/prometheus/docs/README.md
packages/prometheus/manifest.yml

Replaces occurrences of `Metricbeat` with `Elastic Agent` on the [Prometheus](https://www.elastic.co/docs/current/integrations/prometheus) integration page. 
Closes  https://github.com/elastic/integrations/issues/11490

Replace Metricbeat with Elastic Agent

---

packages/mysql/_dev/build/docs/README.md
packages/mysql/changelog.yml
packages/mysql/docs/README.md
packages/mysql/manifest.yml

Update README to clarify the supported setup information for `replica_status` data stream.
- Closes #11826

[O11y][MySQL] Update README to clarify the supported setup information for `replica_status` data stream

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/ecs.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

**Change Log:**
- Added logs, documentation and parsing for
- Hardware Health Monitor events
- Hardware Switch controller sync events
- HTTPS Server events
- IP source lockdown events
- IP tunnel events
- IP-SLA events
- IPv6 Router Advertisement events

Support the first 30-40 event types for the Aruba integration

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.23.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/39e9c2fcbda397c36fbae049ee107a4f21036077
None
None

[Security Rules] Update security rules package to v8.13.23

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8287dfd58fff028a12583a69476db7c36fff8473
None
None

[Security Rules] Update security rules package to v8.15.11

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3c3ecdf31617daaf06766b5420d4f684806304db
None
None

[Security Rules] Update security rules package to v8.16.2

---

packages/barracuda/_dev/build/docs/README.md
packages/barracuda/changelog.yml
packages/barracuda/docs/README.md
packages/barracuda/manifest.yml
packages/websocket/_dev/build/docs/README.md
packages/websocket/changelog.yml
packages/websocket/docs/README.md
packages/websocket/manifest.yml

As Filebeat is frozen at 8.15, this PR fixes the following broken links by replacing `current` with `8.15`:
- https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-websocket.html
- https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-barracuda.html
Relates https://github.com/elastic/integration-docs/issues/586

Fix broken links for Barracuda and Websocket integrations

---

packages/microsoft_sqlserver/_dev/build/docs/README.md
packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/docs/README.md
packages/microsoft_sqlserver/manifest.yml

This PR fixes a broken link to the SQL module example.
Relates https://github.com/elastic/integration-docs/issues/586

Fix broken link for Microsoft SQL Server Integration

---

packages/barracuda/_dev/build/docs/README.md
packages/barracuda/changelog.yml
packages/barracuda/docs/README.md
packages/barracuda/manifest.yml

This PR  replaces `8.15` with `8.13` for the link https://www.elastic.co/guide/en/beats/filebeat/8.13/filebeat-module-barracuda.html

Fix broken link for the Barracuda integration

---

packages/qualys_vmdr/_dev/build/docs/README.md
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

After the split of vulnerability per host in https://github.com/elastic/integrations/pull/9293 in `asset_host_detection` data-stream, 
there are several duplicate processors handling same thing. 
This PR removes these duplicate processors.
Other changes:
- Document required user role permissions to each API.
- Remove stale `kibana.version` requirement from `README`
After removing the duplicate processors, the pipeline tests should run successfully in `asset_host_detection`.
`cd packages/qualys_vmdr && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v --data-streams=asset_host_detection`
```
--- Test results for package: qualys_vmdr - START ---
╭─────────────┬──────────────────────┬───────────┬──────────────────────────────────────────────────────────┬ …
```

qualys_vmdr: Cleanup duplicate processors and update documentation

---

packages/zookeeper/changelog.yml
packages/zookeeper/data_stream/mntr/fields/fields.yml
packages/zookeeper/docs/README.md
packages/zookeeper/manifest.yml

Run zookeeper locally
```
docker run -it -d -p 2181:2181 -p 2888:2888 -p 3888:3888 -e ZOO_4LW_COMMANDS_WHITELIST=srvr,mntr,cons,conf zookeeper
```
Add Zookeeper integration in local Kibana
Follow instructions of adding an agent
(to make it work locally I added following lines into my `/etc/hosts` file
```
127.0.0.1       fleet-server
127.0.0.1       elasticsearch
```
For generating some extra metrics I created a new key in zookeeper
```
docker exec -it <ZOOKEEPER_CONTAINER_ID> bash
./bin/zkCli.sh
create /test test-data
get /test
quit
exit
```
Check Kibana Discover page to make sure `zookeeper.mntr.hostname` field is not showing up
- Closes #11600

remove hostname from zookeeper mntr data stream

---

packages/servicenow/_dev/build/docs/README.md
packages/servicenow/changelog.yml
packages/servicenow/data_stream/event/_dev/test/pipeline/test-common-config.yml
packages/servicenow/data_stream/event/agent/stream/aws-s3.yml.hbs
packages/servicenow/data_stream/event/agent/stream/cel.yml.hbs
packages/servicenow/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/servicenow/data_stream/event/manifest.yml
packages/servicenow/data_stream/event/sample_event.json
packages/servicenow/docs/README.md
packages/servicenow/manifest.yml

Type of change
- Enhancement
Users can now set their time zone offset using either of two formats: a canonical ID (e.g., "Europe/Amsterdam") or an HH:mm offset (e.g., "-05:00").
-

[servicenow] Replace dropdown with textbox for timezone offset parameter

---

packages/abnormal_security/_dev/build/docs/README.md
packages/abnormal_security/changelog.yml
packages/abnormal_security/docs/README.md
packages/abnormal_security/manifest.yml

This PR:
- fixes a broken link to https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html
- adjusts heading levels
- edits the text where needed
Relates https://github.com/elastic/integration-docs/issues/586

Fix broken link for the Abnormal Security integration

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Github Tracking Issue:
https://github.com/elastic/integrations/issues/11880 and https://github.com/elastic/integrations/issues/11906
Change Log:
Added parsing logic, doc, pipeline tests for:
- IRDP events
- L3 Encap capacity events
- L3 Resource Manager events
- LACP events
- LAG Events
- Layer 3 Interface Events
- LED Events
- LLDP Events
- Loop Protection Events
- Loopback Events
- MAC Address mode configuration events
- MAC Learning events
- MACsec events
- Management events
- MDNS events
- MGMD events
- Mirroring events
- Module events
- MSDP events
- Multicast Traffic Manager events
Test Cases:
- reviewed each log message added was processed properly within the pipeline tests

Support the first 40-60 event types for the Aruba integration

---

packages/citrix_adc/changelog.yml
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-native-config-time.json
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-native-config-time.json-config.yml
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-native-config-time.json-expected.json
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-native-local-time.json
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-native-local-time.json-config.yml
packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-native-local-time.json-expected.json
packages/citrix_adc/data_stream/log/agent/stream/stream.yml.hbs
packages/citrix_adc/data_stream/log/agent/stream/tcp.yml.hbs
packages/citrix_adc/data_stream/log/agent/stream/udp.yml.hbs
packages/citrix_adc/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/citrix_adc/data_stream/log/manifest.yml
packages/citrix_adc/manifest.yml

- Reworked how time zones are applied to ensure time zones values are applied in the proper order.
- The order is: from log, from config, from add_locale, and fallback to UTC.
- If tz_offset is null/empty string, the `add_locale` processor is not run.
- Add test cases
```
cd packages/citrix_adc
```

[citrix_adc] Ensure time zone setting is applied properly

---

packages/nginx_ingress_controller_otel/docs/README.md

[nginx_ingress_controller_otel] geoip processor available in contrib collector

docs: geoip processor available in contrib collector

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Change Log:
- added doc, pipeline tests and `default.yml` logic to parse the log lines
- moved fields to alphabetical order (len and limit)
Note: for parsing log events [2006, 2008, 2018], there were variations between recorded logs and the documentation
noted as a comment in the parsing logic

#11921-1 Multiple spanning tree protocol events (20xx)

---

packages/checkpoint_email/changelog.yml
packages/checkpoint_email/data_stream/event/agent/stream/cel.yml.hbs
packages/checkpoint_email/data_stream/event/manifest.yml
packages/checkpoint_email/manifest.yml
packages/okta/changelog.yml
packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
packages/okta/manifest.yml
packages/wiz/changelog.yml
packages/wiz/data_stream/audit/agent/stream/cel.yml.hbs
packages/wiz/data_stream/audit/manifest.yml
packages/wiz/data_stream/cloud_configuration_finding/agent/stream/cel.yml.hbs
packages/wiz/data_stream/cloud_configuration_finding/manifest.yml
packages/wiz/data_stream/issue/agent/stream/cel.yml.hbs
packages/wiz/data_stream/issue/manifest.yml
packages/wiz/data_stream/vulnerability/agent/stream/cel.yml.hbs
packages/wiz/data_stream/vulnerability/manifest.yml
packages/wiz/manifest.yml

Filebeat v8.15.x added the ability to delete request traces on the agent's host[1]. This change adds support for this feature to integrations with kibana.version at or above v8.15.x.
[1]elastic/beats#39969 and elastic/beats#40004
-

checkpoint_email,okta,wiz: add support for request trace deletion

---

packages/prometheus/changelog.yml
packages/prometheus/data_stream/collector/manifest.yml
packages/prometheus/data_stream/remote_write/manifest.yml
packages/prometheus/manifest.yml

Upgrade to package format_version v3. Tested using elastic-package (pipeline, static, etc.) and also linting and building. Also did basic testing by scraping data from Prometheus Server itself and populating the dashboard. Works as expected. For testing, I used 8.16.1 cluster.
https://github.com/elastic/integrations/issues/8028
Dashboards screenshots after using collector to scrape metrics from Prometheus Server itself.

packages/prometheus: Upgrade to package format_version v3

---

.github/CODEOWNERS
packages/azure/_dev/build/docs/events.md
packages/azure/changelog.yml
packages/azure/data_stream/events/agent/stream/stream.yml.hbs
packages/azure/data_stream/events/elasticsearch/ingest_pipeline/default.yml
packages/azure/data_stream/events/fields/base-fields.yml
packages/azure/data_stream/events/fields/fields.yml
packages/azure/data_stream/events/fields/package-fields.yml
packages/azure/data_stream/events/manifest.yml
packages/azure/data_stream/events/routing_rules.yml
packages/azure/docs/events.md
packages/azure/manifest.yml

Switch the integration package from the one-input-per-data-stream model to the one-input model.
One input per data stream model:
One input model:
In the one-input model, there is only one azure-eventhub input running and sending events to the `events` data stream. In the `events` data stream, the ingest pipeline performs these tasks:
- discover and set the `event.dataset` field using the `category` field in the event.
- use the `event.dataset` field to reroute the event to the target data stream.
The discover process uses the following logic:
- if the event doesn't have a category, it sets `event.dataset` to `azure.eventhub` (the generic integration)
- if the event does have a category, it sets `event.dataset` to `azure.platformlogs` (it's probably an Azure log)
- if the event category is …

[azure logs] add routing integration to use only one azure-eventhub input

---

packages/kibana/changelog.yml
packages/kibana/data_stream/audit/fields/ecs.yml
packages/kibana/docs/README.md
packages/kibana/manifest.yml

```
The kibana.audit data stream was missing a mapping for the span.id field.
Fixes #11658
Fixes #11130
Fixes #10691
Fixes #10514
Fixes #9839
```
- Fixes #11658
- Fixes #11130
- Fixes #10691
- Fixes #10514
- Fixes #9839

kibana - define span.id field

---

.buildkite/scripts/find_oldest_supported_version.py

Update find_oldest_supported_version.py as in main branch to get the latest fixes to get the latest supported version of the stack.
- Before
```
$ python3 .buildkite/scripts/find_oldest_supported_version.py --manifest-path packages/security_detection_engine/manifest.yml 
8.x-SNAPSHOT
```
- After
```
$ python3 .buildkite/scripts/find_oldest_supported_version.py --manifest-path packages/security_detection_engine/manifest.yml 
8.14.0
```
- Relates https://github.com/elastic/integrations/pull/11265
- Relates https://github.com/elastic/integrations/pull/11227

 [CI] Update find_oldest_supported_version script

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.18.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c0b531026a629d3d412b0938ef269b37cb931f31
None
None

[Security Rules] Update security rules package to v8.14.18

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3169b1d8d7b7c44ebeece36f2c462ea1b76b99cc
None
None

[Security Rules] Update security rules package to v8.15.12

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/44aa52d03f0124be8d209188d82ab3e8661ebb96
None
None

[Security Rules] Update security rules package to v8.16.3

---

packages/cloudflare_logpush/_dev/build/docs/README.md
packages/cloudflare_logpush/changelog.yml
packages/cloudflare_logpush/data_stream/access_request/manifest.yml
packages/cloudflare_logpush/data_stream/audit/manifest.yml
packages/cloudflare_logpush/data_stream/casb/manifest.yml
packages/cloudflare_logpush/data_stream/device_posture/manifest.yml
packages/cloudflare_logpush/data_stream/dns/manifest.yml
packages/cloudflare_logpush/data_stream/dns_firewall/manifest.yml
packages/cloudflare_logpush/data_stream/firewall_event/manifest.yml
packages/cloudflare_logpush/data_stream/gateway_dns/manifest.yml
packages/cloudflare_logpush/data_stream/gateway_http/manifest.yml
packages/cloudflare_logpush/data_stream/gateway_network/manifest.yml
packages/cloudflare_logpush/data_stream/http_request/manifest.yml
packages/cloudflare_logpush/data_stream/magic_ids/manifest.yml
packages/cloudflare_logpush/data_stream/nel_report/manifest.yml
packages/cloudflare_logpush/data_stream/network_analytics/manifest.yml
packages/cloudflare_logpush/data_stream/network_session/manifest.yml
packages/cloudflare_logpush/data_stream/sinkhole_http/manifest.yml
packages/cloudflare_logpush/data_stream/spectrum_event/manifest.yml
packages/cloudflare_logpush/data_stream/workers_trace/manifest.yml
packages/cloudflare_logpush/docs/README.md
packages/cloudflare_logpush/manifest.yml

- Change the UI setting name from `Cloudflare R2 Bucket Name` to `S3-Compatible Bucket Name`.
- Generalise the setting's description.
- Also update README to generalise the option.
Ref: https://github.com/elastic/integrations/issues/10733
> [!NOTE]
> Only changes the UI for the user. The respective config option names are untouched to avoid breaking change.
- Closes https://github.com/elastic/integrations/issues/10733

cloudflare_logpush: Generically rename non-AWS S3-compatible bucket options.

---

packages/juniper_srx/changelog.yml
packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-system.log-expected.json
packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/system.yml
packages/juniper_srx/manifest.yml

The purpose of this code change is to make failed SSH login attempts to Juniper equipment visible in Elastic Security.
To this end, we populate the following fields on a failed SSH login attempt in the system logging pipeline.
(if SSH login failed)
- event.outcome: failure
- event.category: authentication (append)
(no conditions)
- observer.name -> host.name (copy)
- `elastic-package test` in the package directory.
- Closes #11834
- Closes #11835

[Juniper SRX] Populate event fields for system log

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Changed the agentless identification tags for CSPM integration.
When saving the CSPM integration using an agentless agent, the request should include the following labels
```
org: security
division: engineering
team: cloud-security-posture
```
- Closes https://github.com/elastic/security-team/issues/11401

[Cloud Security] Changed CSPM agentless identification tags

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Ticket:
Support the first 70-80 event types for the Aruba integration
https://github.com/elastic/integrations/issues/12065
Change Log:
Added Port events (60x)
Added Port access roles events (930x)
Policies events (1010x)
Test Cases:
validate that the pipeline test pass
validated that the expected file parses the proper fields for the different message type

#12065 - 3/4/5 Added Port access role, Policies and Port events

---

packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/agent/stream/input.yml.hbs
packages/qualys_vmdr/manifest.yml

Qualys can send empty XML response body with 200 success status. 
Handle this case as valid.
Run system tests for `asset_host_detection`:
`eval "$(elastic-package stack shellinit)" && elastic-package test system --generate  -v --defer-cleanup 30m --data-streams=asset_host_detection`
```
--- Test results for package: qualys_vmdr - START ---
╭─────────────┬──────────────────────┬───────────┬───────────┬────────┬───────────────╮
│ PACKAGE     │ DATA STREAM          │ TEST TYPE │ TEST NAME │ RESULT │  TIME ELAPSED │
├─────────────┼──────────────────────┼───────────┼───────────┼────────┼───────────────┤
│ qualys_vmdr │ asset_host_detection │ system    │ default   │ PASS   │ 38.544323042s │
╰─────────────┴──────────────────────┴───────────┴───────────┴────────┴───────────────╯
--- Test results …
```

qualys_vmdr: Handle empty XML responses in Qualys asset_host_detection.

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Ticket:
Support the first 70-80 event types for the Aruba integration
https://github.com/elastic/integrations/issues/12065
Change Log:
- PORT_ACCESS events (1050x)
- Port security events (940x)
- Port Statistics events (660x)
Test Cases:
validate that the pipeline test pass
validated that the expected file parses the proper fields for the different message type

#12065-6/7 PORT_ACCESS, Port Security and Port Statistics Event additions

---

packages/azure_application_insights/_dev/build/docs/README.md
packages/azure_application_insights/docs/README.md
packages/azure_billing/_dev/build/docs/README.md
packages/azure_billing/docs/README.md
packages/azure_functions/_dev/build/docs/README.md
packages/azure_functions/docs/README.md
packages/azure_metrics/_dev/build/docs/README.md
packages/azure_metrics/docs/README.md
packages/citrix_adc/_dev/build/docs/README.md
packages/citrix_adc/docs/README.md
packages/citrix_waf/_dev/build/docs/README.md
packages/citrix_waf/docs/README.md
packages/jolokia_input/docs/README.md
packages/nats/_dev/build/docs/README.md
packages/nats/docs/README.md
packages/oracle_weblogic/_dev/build/docs/README.md
packages/oracle_weblogic/docs/README.md

This PR fixes the following broken links:
/packages/azure_application_insights @elastic/obs-infraobs-integrations
https://dev.applicationinsights.io/documentation/Authorization/API-key-and-App-ID
=> https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/overview
azure_billing, azure_functions, azure_metrics @elastic/obs-infraobs-integrations
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/elastic.elasticsearch?tab=Overview
=> https://azuremarketplace.microsoft.com/en/marketplace/apps/elastic.ec-azure-pp?tab=overview
/packages/citrix_adc @elastic/obs-infraobs-integrations
/packages/citrix_waf @elastic/sec-deployment-and-devices
https://support.citrix.com/article/CTX211543
=> https://support.citrix.com/s/article/CTX138973-how-to-send-application-firewall-messages-to-a-s …

Fix broken links in Observability integrations packages

---

packages/salesforce/changelog.yml
packages/salesforce/data_stream/apex/agent/stream/salesforce.yml.hbs
packages/salesforce/manifest.yml

Remove indentation from processors to avoid syntax error when adding new processors. This changed is required so that when processors are added from the UI they are at the same level (indentation) as the already added processors i.e., making it syntactically correct when formatted. Only `apex` is affected, for other datasets, it is in expected form.
Tested by adding `- add_fields: { fields: { my_id: "12345" } }` from the UI in processors.

packages/salesforce: Fix processor syntax issue when adding new ones

---

packages/mysql/_dev/build/docs/README.md
packages/mysql/changelog.yml
packages/mysql/data_stream/error/sample_event.json
packages/mysql/data_stream/replica_status/elasticsearch/ingest_pipeline/default.yml
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-10-1-21.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-10-2-12.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-10-3-13.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-explain.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-5-7-22.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-darwin-brew-5-7-10.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-debian-5-7-17.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-debian-5-7-19.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-ubuntu-5-5-53.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-ubuntu-8-0-15.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-percona-ubuntu-5-7-19-innodb.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-percona-ubuntu-5-7-19.log-expected.json
packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-percona-ubuntu-8-0-15.log-expected.json
packages/mysql/data_stream/slowlog/elasticsearch/ingest_pipeline/default.json
packages/mysql/data_stream/slowlog/sample_event.json
packages/mysql/docs/README.md
packages/mysql/manifest.yml

Fix optional chaining in the replica_status data stream pipeline
- Closes #11847

[O11y][MySQL] Fix optional chaining in the replica_status data stream pipeline

---

.buildkite/pipeline.yml
packages/apache/data_stream/access/_dev/test/pipeline/test-common-config.yml
packages/auth0/data_stream/logs/_dev/test/pipeline/test-common-config.yml
packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-common-config.yml
packages/barracuda/data_stream/waf/_dev/test/pipeline/test-access.log-config.yml
packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-common-config.yml
packages/forcepoint_web/data_stream/logs/_dev/test/pipeline/test-common-config.yml
packages/forgerock/data_stream/am_access/_dev/test/pipeline/test-common-config.yml
packages/fortinet_fortiproxy/data_stream/log/_dev/test/pipeline/test-common-config.yml
packages/gcp/data_stream/audit/_dev/test/pipeline/test-common-config.yml
packages/github/data_stream/audit/_dev/test/pipeline/test-common-config.yml
packages/iis/data_stream/access/_dev/test/pipeline/test-common-config.yml
packages/imperva_cloud_waf/data_stream/event/_dev/test/pipeline/test-common-config.yml
packages/modsecurity/data_stream/auditlog/_dev/test/pipeline/test-common-config.yml
packages/netskope/data_stream/events/_dev/test/pipeline/test-common-config.yml
packages/nginx/data_stream/access/_dev/test/pipeline/test-common-config.yml
packages/nginx_ingress_controller/data_stream/access/_dev/test/pipeline/test-ingest-raw.log-config.yml
packages/o365/data_stream/audit/_dev/test/pipeline/test-common-config.yml
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.log-config.yml
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-no-flattened-events.log-config.yml
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-yes-flattened-events.log-config.yml
packages/proofpoint_tap/data_stream/clicks_permitted/_dev/test/pipeline/test-common-config.yml
packages/slack/data_stream/audit/_dev/test/pipeline/test-common-config.yml
packages/sophos/data_stream/xg/_dev/test/pipeline/test-common-config.yml
packages/suricata/data_stream/eve/_dev/test/pipeline/test-common-config.yml
packages/trend_micro_vision_one/data_stream/detection/_dev/test/pipeline/test-common-config.yml

Include a new dynamic field for `user_agent.version` in order to accept versions with a trailing dot.
Related issue: https://github.com/elastic/elasticsearch/issues/116950
This regex needs to accept values like these ones (examples from apache and iis package):
- 15.0.a2
- 50.0.
- 50.0
- 7.79.1
- 54.0.2840.98
- 2016
Builds failing:
- 8.18.0-SNAPSHOT https://buildkite.com/elastic/integrations/builds/19186
- 9.0.0-SNAPSHOT https://buildkite.com/elastic/integrations/builds/19187
- Relates https://github.com/elastic/elasticsearch/issues/116950
- Closes https://github.com/elastic/integrations/issues/12036

Include `user_agent.version` in dynamic_fields (pipeline tests)

---

packages/ti_custom/_dev/build/docs/README.md
packages/ti_custom/changelog.yml
packages/ti_custom/docs/README.md
packages/ti_custom/manifest.yml

See title.
- Related to https://github.com/elastic/enhancements/issues/22961

ti_custom: Add docs about retrieving ISAC feeds

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Ticket:
Support the first 70-80 event types for the Aruba integration
https://github.com/elastic/integrations/issues/12065
Change Log:
- Power over Ethernet events (79xx)
Test Cases:
- validate that the pipeline test pass
- validated that the expected file parses the proper fields for the different message type

#12065-10 Adding Power over Ethernet events

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Parent Ticket:
https://github.com/elastic/integrations/issues/12118
Adding
- Rapid per VLAN Spanning Tree Protocol events (500x)
- Quality of Service events (570x) 
- Note: added generated logs, parsing logic and added post-process for aruba.rpvst.old_mac

#12118-3/4 Rapid per VLAN Spanning Tree Protocol and QoS events

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/event/manifest.yml
packages/m365_defender/manifest.yml

Change property connection_string to be a secret like in the other integrations like https://github.com/elastic/integrations/blob/main/packages/azure/manifest.yml

[M365 Defender] change connection_string to secret

---

packages/cloud_defend/changelog.yml
packages/cloud_defend/docs/README.md
packages/cloud_defend/manifest.yml

This PR fixes the following broken links by removing the specified id (after the #) and defaulting to the top of the page https://www.elastic.co/guide/en/ecs/current/ecs-process.html.
- https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-os-full
- https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-os-kernel
- https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-os-name
- https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-os-platform
- https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-os-type
- https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-os-version
- https://www.elastic.co/guide/en/ecs/current/ecs-process.html#field-process-group-id
- …

Fix broken links in Cloud Defend integration package

---

packages/ti_rapid7_threat_command/_dev/build/docs/README.md
packages/ti_rapid7_threat_command/changelog.yml
packages/ti_rapid7_threat_command/docs/README.md
packages/ti_rapid7_threat_command/manifest.yml

This PR updates the following AsciiDoc redirect https://www.elastic.co/guide/en/kibana/current/create-connector-api.html#_prerequisites_16 to point to the new page https://www.elastic.co/guide/en/kibana/current/action-types.html

Update link in the Rapid7 Threat Command Integration

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/access_transparency/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/context_aware_access/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/device/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/gcp/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/group_enterprise/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/rules/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/token/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/manifest.yml
packages/jamf_protect/changelog.yml
packages/jamf_protect/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/jamf_protect/data_stream/telemetry/elasticsearch/ingest_pipeline/default.yml
packages/jamf_protect/data_stream/web_threat_events/elasticsearch/ingest_pipeline/default.yml
packages/jamf_protect/data_stream/web_traffic_events/elasticsearch/ingest_pipeline/default.yml
packages/jamf_protect/manifest.yml
packages/ti_mandiant_advantage/changelog.yml
packages/ti_mandiant_advantage/data_stream/threat_intelligence/elasticsearch/ingest_pipeline/default.yml
packages/ti_mandiant_advantage/manifest.yml

This manually replays the changes in #12046.
- For #12067

google_workspace,jamf_protect,ti_mandiant: add "preserve_original_event" tag to documents with event.kind set to "pipeline_error"

---

packages/okta/changelog.yml
packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
packages/okta/data_stream/system/sample_event.json
packages/okta/docs/README.md
packages/okta/manifest.yml

okta: do not remove event.original in main ingest

---

packages/nginx_ingress_controller/_dev/build/docs/README.md
packages/nginx_ingress_controller/docs/README.md

This PR fixes the following broken link:
/packages/nginx_ingress_controller @elastic/obs-cloudnative-monitoring
https://github.com/kubernetes/ingress-nginx/blob/nginx-0.30.0/docs/user-guide/nginx-configuration/log-format.md
=>https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/log-format.md
Relates to https://github.com/elastic/integration-docs/issues/585

Fix broken links in the nginx_ingress_controller package

---

packages/azure_frontdoor/changelog.yml
packages/azure_frontdoor/data_stream/access/manifest.yml
packages/azure_frontdoor/data_stream/waf/agent/stream/azure-eventhub.yml.hbs
packages/azure_frontdoor/data_stream/waf/manifest.yml
packages/azure_frontdoor/manifest.yml

```
[azure_frontdoor] Add `storage_account_container` variables
Added to the manifests of both data streams.
Already used by the input config for the `access` data stream.
Usage added in the input config for the `waf` data stream.
```

[azure_frontdoor] Add `storage_account_container` variables

---

packages/qnap_nas/_dev/build/docs/README.md
packages/qnap_nas/docs/README.md
packages/sophos/_dev/build/docs/README.md
packages/sophos/docs/README.md
packages/suricata/_dev/build/docs/README.md
packages/suricata/docs/README.md

This PR fixes the following broken links:
/packages/qnap_nas @elastic/sec-deployment-and-devices
https://docs.qnap.com/nas-outdated/4.1/SMB/en/index.html?system_logs.htm
=> https://www.qnap.com/en/
/packages/sophos @elastic/sec-deployment-and-devices
https://community.sophos.com/kb/en-us/123184
=> https://support.sophos.com/support/s/?language=en_US#t=AllTab&sort=relevancy
/packages/suricata @elastic/sec-deployment-and-devices
https://suricata-ids.org/
=> https://suricata.io/
Relates to https://github.com/elastic/integration-docs/issues/585

Fix broken links in the security packages

---

packages/aws_logs/changelog.yml
packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
packages/aws_logs/manifest.yml

Resolve https://github.com/elastic/integrations/issues/12099
Fix duplicated keys in agent template, that was crashing the Fleet UI 
Tested after the fix and it work as expected:

Fix aws logs duplicated keys in agent template

---

packages/docker/changelog.yml
packages/docker/data_stream/network/fields/fields.yml
packages/docker/docs/README.md
packages/docker/manifest.yml

- WHAT: Add docker.network in and out fields definitions 
- WHY: These fields were added in beats docker module
-  PR in beats https://github.com/elastic/beats/pull/40968

Add new docker network in and out group fields

---

packages/authentik/changelog.yml
packages/authentik/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/authentik/manifest.yml
packages/proofpoint_on_demand/changelog.yml
packages/proofpoint_on_demand/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_on_demand/manifest.yml
packages/system/changelog.yml
packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml
packages/system/manifest.yml
packages/watchguard_firebox/changelog.yml
packages/watchguard_firebox/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/watchguard_firebox/manifest.yml
packages/windows/changelog.yml
packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
packages/windows/manifest.yml
packages/zscaler_zia/changelog.yml
packages/zscaler_zia/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/zscaler_zia/manifest.yml

Defensively copy list parameters in 'Set ECS categorization fields' scripts. See https://github.com/elastic/elasticsearch/issues/91977.

Fix handling of lists in 'Set ECS categorization fields' scripts

---

packages/arista_ngfw/changelog.yml
packages/arista_ngfw/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/arista_ngfw/manifest.yml

- Bug
A recent update to Arista NG Firewall changed the Syslog message format slightly. Where there used to be two spaces preceding the message body, the new format only includes a single space. The updated Grok pattern accounts for both the old, double-spaced format and the new single-spaced format.
Modified the `default` ingest pipeline with the proposed Grok pattern change, and the messages are now parsing again properly. 
- Closes #12175

[Arista NG Firewall] Correct Grok pattern due to change in Syslog message format.

---

packages/journald/changelog.yml
packages/journald/docs/README.md
packages/journald/fields/ecs.yml
packages/journald/manifest.yml

This commit adds the missing ECS mappings for `source.ip` and `host.ip`. Since these fields were not mapped, they defaulted to keyword in logs from journald, causing conflicts in the data view.
Maybe there is a faster way, but what I did is the following:
- Deploy a 8.12.1 cloud stack
- Enroll an agent
- Install the journald integration in the agent policy
- In Discover, visualize the `host.ip` field, it shows as conflict (keyword, ip)
- Package the integration and deploy to the existing cluster: `elastic-package install --zip ./integrations/build/packages/journald-1.1.1.zip -v`
- Update the integration in the agent policy
- In the new index after the rollover, confirm that mappings are correct (host.ip and source.ip are shown as `ip`)
- Delete the old conflicting index
- Check new data …

journald: add missing source.ip and host.ip ECS fields

---

packages/log/changelog.yml
packages/log/docs/README.md
packages/log/manifest.yml

This PR updates the Custom Log integration readme file. The original goal was to explain how users can use wildcard patterns to match multiple files (as outlined in https://github.com/elastic/platform-docs-team/issues/560). However, after making that update, I decide to update the entire file.
~- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices)~
Give it a quick read 😄 
- Closes …

Update Custom Logs Package Readme

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12185
SSH server events (520x)
SNMP events (71xx)
SSH client events (900x)
Smartlink events (1130x)
Note: this is against the 10.15 OS version, the links have been changed to reflect the new OS version

#12185-1/2/3/4 4 new event types for Aruba (SSH Server/Client, Smartlink and SNMP)

---

packages/problemchild/changelog.yml
packages/problemchild/elasticsearch/ingest_pipeline/problem_child_ingest_pipeline.yml
packages/problemchild/manifest.yml

The painless script `if` block serving as the entry point into the problem child inference pipeline has a bug in its logic checking for the appropriate host operating system. It separates its checks for various sub-fields of `host.os` and it's actual accessing of those fields from the `ctx` object, potentially leading to errors trying to access keys that don't exist.
For example, if a document contains `host.os.family` but doesn't contain `host.os.type`, this painless script will raise an error instead of simply failing.
-

Problem child ingest pipeline bug

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12118
- sFlow events (10xx)
- Self Test events (450x)
- REST events (46xx)
Note: this is based on OS 10.15 message types different than 10.07. Will allow the rest of the already mapped fields in another PR

#12118 8/9/10 Added 3 new events types (sFlow, Self Test and REST)

---

packages/azure/changelog.yml
packages/azure/data_stream/graphactivitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
packages/azure/data_stream/graphactivitylogs/elasticsearch/ingest_pipeline/default.yml
packages/azure/manifest.yml

- Bug
Fixed an issue where event.duration values were not properly being converted by implicit assignment due to differing on the basis of source and target datatypes. Added a convert processor to make this work properly and also fixed a naming related buf.
Some url extensions got removed because previously the parsing was incorrectly done, extensions should only occur after a '.', but the version number '.' was being incorrectly used. This is likely due to recent internal updates and not related to this change but regenerating the tests rectified this.
-

[azure][graphactivitylogs] - Fixed a bug related to event.duration value mapping

---

packages/jamf_pro/changelog.yml
packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
packages/jamf_pro/data_stream/inventory/manifest.yml
packages/jamf_pro/manifest.yml

```
[jamf_pro] Inventory pagination fix
* Always include the General section of inventory data.
* Update the cursor whenever there is new data.
* Assume there isn't another page if the current page isn't full.
* Correct the name of the `enable_section_content_caching` variable.
* Adjust the `page_size` variable description to correct the maximum.
* Simplify code to set the inventory filter parameter.
This has been manually tested against the live API.
```
I ran this against the live endpoint and checked a couple of pagination sequences. Here's some partial data from the logs (not the full results objects), that shows the cursor updates and sequence continuation/end are done correctly:
<details>
<summary>Expand for the partial request log data</summary>
```json
// first sequence
{ …
```

[jamf_pro] Inventory pagination fix

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8a1590e36e9bd52cfd130121e6746cdac51eebfd
None
None

[Security Rules] Update security rules package to v8.16.4

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8e24f3644c515cb1d16dd787bea0a241cfb54b0e
None
None

[Security Rules] Update security rules package to v8.15.13

---

packages/trend_micro_vision_one/changelog.yml
packages/trend_micro_vision_one/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/trend_micro_vision_one/data_stream/audit/manifest.yml
packages/trend_micro_vision_one/data_stream/detection/agent/stream/httpjson.yml.hbs
packages/trend_micro_vision_one/data_stream/detection/manifest.yml
packages/trend_micro_vision_one/manifest.yml

- Enhancement
Made page size for audit and detection data streams configurable and set more modest default page size values to avoid 
buffer overflow/ heap errors.
-

[trend_micro_vision_one] - Added configurable page size option for the detection and audit data streams

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/audit_logs/fields/fields.yml
packages/kubernetes/docs/audit-logs.md
packages/kubernetes/manifest.yml

- Enhancement
Added the data type for the 'audit-violation' field as type TEXT in the Kubernetes Audit logs ingest mapping. This will allow users  to search for and do alerts on this field. In Kubernetes, this field is generated in the audit logs when a user tries to deploy a deployment/pod into a namespace that has security restrictions applied to it. Alerts for this sort of violation are important.
Kubernetes documentation regarding the audit logs annotation `pod-security.kubernetes.io/audit-violations`: https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/#pod-security-kubernetes-io-audit-violations
- [] I have added an entry to my package's `changelog.yml` file.
- [>=8.16.0 ] I have verified that Kibana version constraints are current according to …

Kubernetes Audit log update - added datatype for annotations.pod-security_kubernetes_io/audit-violation

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12248
Virtual Switching Extension (70xx)
Virtual Switching Framework (VSF) events (99xx)
Added docs, mac address transform, parsing and generated logs 
Note: Against 10.15 OS

#12248-1/2 added two event types (Virtual Switching Extension and Virtual Switching Framework)

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12248
VLAN Interface events (160X)
VLAN events (21xx)
VRRP events (370x)
VRF Manager events (540x)
VRF events (640x)
Added logs, parsing and docs against OS 10.15

#12248-3/4/5/6/7 Adding 5 new event types (VLAN Interface, VLAN, VRRP, VRF Mgr and VRF)

---

.buildkite/pipeline.yml

Update the threshold that limits the creation of issues in daily jobs up to 30.
Environment variable that overwrites the value is defined here: https://github.com/elastic/integrations/blob/5468ed672708099ed7aabfbc95ccee36820dc091/magefile.go#L174

Update threshold that limits the creation of issues in daily jobs

---

packages/sentinel_one_cloud_funnel/changelog.yml
packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-network-action.log-expected.json
packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-network-action.yml
packages/sentinel_one_cloud_funnel/manifest.yml

Fixes the previous condition which resulted in `event.action` not being populated.
`elastic-package.exe test pipeline -v`

Fix missing `event.action` in S1 Network Events

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12248
VSX Sync events (760x)
VXLAN events (81xx)
VXLAN agent events (1250x)
Zero-touch provisioning events (87xx)
logs, parsing and docs against OS 10.15

#12248 8/9/10/11 Adding last 4 event types (VSX, VXLAN (and agent) and Zero Touch)

---

.github/ISSUE_TEMPLATE/integration_bug.yml
packages/fortinet_forticlient/changelog.yml
packages/fortinet_forticlient/manifest.yml

It seems that fortinet_forticlient missed the initial pass of deprecating rsa2elk packages, so deprecating now. Package will NOT be removed for the foreseeable future, but it will not be available in stack 9.0 or later. A rewrite of the package will be necessary for 9.0 support.
- Package is implemented using rsa2elk parsers, which are no longer maintained.

[fortinet_forticlient] Deprecate package

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- Updated AAA events, two additional events to support 10.15
- add new Accounting events: docs, parsing and fields
- Updated link for ACLs events
- added new Alarm events: docs, parsing and fields
- added new ARC events: docs, parsing and fields
- updated redact logic as it was interfering with the new AAA events 2306/2307 event ids

#12249-1 Driving to 10.15 OS support for all events including missed events from previous iteration of implementation (part 1)

---

packages/cisco_ftd/changelog.yml
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ftd/manifest.yml

- Events with ID 101001 through 105052 were not explicitly handled by the pipeline, which means the reason text from the event would be discarded.
- Added a script processor to save off the message to event.reason for these events.
```
cd packages/cisco_ftd
```

[cisco_ftd] Ensure event message is saved to event.reason for IDs 101001 through 105052

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-reprocess.json
packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-reprocess.json-expected.json
packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/panw_cortex_xdr/data_stream/incidents/_dev/test/pipeline/test-reprocess.json
packages/panw_cortex_xdr/data_stream/incidents/_dev/test/pipeline/test-reprocess.json-expected.json
packages/panw_cortex_xdr/data_stream/incidents/elasticsearch/ingest_pipeline/default.yml
packages/panw_cortex_xdr/manifest.yml

```
[panw_cortex_xdr] Allow reprocessing of events with `event.original` (#)
For both data streams, if the `event.original` field is populated,
discard the `message` and other fields that will be regenerated by the
pipeline.
This allows reprocessing of events (if they contain `event.original`),
and it allows the processing of events received from Logstash with the
`ecs_compatibility` mode[1] enabled (which populates `event.original`).
Pipeline tests are added to confirm correction function.
[1]: https://www.elastic.co/guide/en/logstash/current/ecs-ls.html
```

[panw_cortex_xdr] Allow reprocessing of events with `event.original`

---

packages/jamf_pro/_dev/deploy/docker/files/config.yml
packages/jamf_pro/changelog.yml
packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
packages/jamf_pro/manifest.yml

```
[jamf_pro] Inventory date formatting for filter
Ensure that `reportDate` values with less than 3 digits of a fractional
second will be padded with zeros to 3 digits before they are used in
the `filter` parameter.
Avoids HTTP 400 responses saying:
> Date [2025-01-08T10:50:26.6Z] does not match any of supported formats:
> yyyy-MM-ddTHH:mm:ss.SSSZ, yyyy-MM-ddTHH:mm:ss.SSZ,
> yyyy-MM-ddTHH:mm:ssZ, yyyy-MM-dd*, yyyy-MM-dd, yyyy-MM*, yyyy*
Also improves the CEL error handling by returning a single event
outside of an array (which will be logged).
This has been manually tested against the live API.
```
The system test has been updated to demonstrate the new functionality.
- Relates #12021

[jamf_pro] Inventory date formatting for filter

---

packages/goflow2/changelog.yml
packages/goflow2/data_stream/sflow/_dev/test/system/test-filestream-config.yml
packages/goflow2/data_stream/sflow/agent/stream/filestream.yml.hbs
packages/goflow2/data_stream/sflow/manifest.yml
packages/goflow2/manifest.yml
packages/imperva/changelog.yml
packages/imperva/data_stream/securesphere/_dev/test/system/test-logfile-config.yml
packages/imperva/data_stream/securesphere/agent/stream/filestream.yml.hbs
packages/imperva/data_stream/securesphere/manifest.yml
packages/imperva/manifest.yml
packages/proxysg/changelog.yml
packages/proxysg/data_stream/log/_dev/test/system/test-logfile-config.yml
packages/proxysg/data_stream/log/agent/stream/stream.yml.hbs
packages/proxysg/data_stream/log/manifest.yml
packages/proxysg/manifest.yml
packages/syslog_router/changelog.yml
packages/syslog_router/data_stream/log/_dev/test/system/test-filestream-config.yml
packages/syslog_router/manifest.yml

- Disabled filestream fingerprint (defaults to enabled in 9.0) in goflow2, imperva, proxysg, and syslog_router system tests
- Exposed filestream options configuration for goflow2, imperva, and proxysg in order to disable fingerprint in the system tests
```
cd packages/<pkg>
```
Note: I have run each package's system test against the latest 9.0.0-SNAPSHOT and all tests passed.
```
--- Test results for package: goflow2 - START ---
╭─────────┬─────────────┬───────────┬────────────┬────────┬────────────────╮
│ PACKAGE │ DATA STREAM │ TEST TYPE │ TEST NAME  │ RESULT │   TIME ELAPSED │ …
```

Ensure filestream fingerprint is disabled in system tests

---

packages/azure_openai/_dev/build/docs/README.md
packages/azure_openai/changelog.yml
packages/azure_openai/docs/README.md
packages/azure_openai/manifest.yml

This PR proposes some editing suggestions.
Closes https://github.com/elastic/integration-docs/issues/626
CC @daniela-elastic

Edit Azure Open AI page

---

packages/cisco_secure_email_gateway/changelog.yml
packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/pipeline_consolidated_event.yml
packages/cisco_secure_email_gateway/manifest.yml

- Fixed incorrect field name in a remove processor, which was in an on_failure processor
- Closes #12377

[cisco_secure_email_gateway] Fix field name in remove processor

---

packages/zscaler_zia/changelog.yml
packages/zscaler_zia/data_stream/firewall/_dev/test/pipeline/test-firewall-http-endpoint.log-expected.json
packages/zscaler_zia/data_stream/firewall/_dev/test/pipeline/test-firewall.log-expected.json
packages/zscaler_zia/data_stream/firewall/_dev/test/pipeline/test-unicode.json-expected.json
packages/zscaler_zia/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
packages/zscaler_zia/manifest.yml

Users may have private IPs inside `source.ip` which prevents `geo` fields from getting populated. 
This PR:
- Uses `source.nat.ip` as an alternate for populating `geo` fields if not already populated by `source.ip`.
- Removes processor explicitly populating `geo.country_name` as it is added by `geoip` processor.
`cd packages/zscaler_zia && elastic-package build && elastic-package stack up --version=8.13.0 -d -v  && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v`
```
--- Test results for package: zscaler_zia - START ---
╭─────────────┬─────────────┬───────────┬────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE     │ DATA STREAM │ TEST TYPE │ TEST NAME                                                  │ …
```

zscaler_zia: Use `source.nat.ip` as an alternate for geo IPs in `firewall` and `web` logs.

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/ecs.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated CoPP Events (15xx) doc link
- updated DHCP Server events (19xx) doc link
- updated Credential Manager events (65xx) doc link
- updated Config Management events (68xx) doc link
- updated CPU_RX Events (75xx) doc link
- updated Certificate management events (77xx) doc link and added throttle parsing
- updated DHCPv4 Snooping events (82xx) doc link, added new messages 8217-8226
- updated DHCPv6 snooping events (83xx) dock link, added new messages 8314-8323
- updated Discovery and Capability Exchange (DCBx) events (92xx) doc link, refactored fields
- updated Connectivity Fault Management (CFM) events (1160x) doc link, refactored fields
- updated Container Manager Events (118xx) doc link, added messages 11804-11811
- added Device …

#12249-3 Driving to 10.15 OS (part 3)

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

I'm adding `external_id` input var field for the `cloudbeat/cis_aws` input. We will use Role ARN and External ID fields  
to establish trust with Elastic.
Related ticket: [Add Cloud Connector Support for Agentless CSPM AWS Integration](https://github.com/elastic/security-team/issues/11078)

[Cloud Security] add external id field

---

packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_defender_endpoint/manifest.yml

There can be events without a description, which leads the if condition to fail with:
cannot access method/field [length] from a null def reference

[Defender Endpoint] fix null ref for description description

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/alert/agent/stream/httpjson.yml.hbs
packages/m365_defender/manifest.yml

M365 Defender: Make token endpoint configurable for Alert data stream

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/pod/fields/fields.yml
packages/kubernetes/docs/kubelet.md
packages/kubernetes/manifest.yml

Fix kubernetes.pod.cpu.usage.nanocores unit of measure
Currently, the field kubernetes.pod.cpu.usage.nanocores uses bytes as its unit of measurement. In contrast, other similar fields, such as kubernetes.container.cpu.usage.nanocores, do not specify a unit of measurement.
Start collecting data with the K8S integration (the `kubernetes.pod` dataset is enough):
1. Upload the integration v 1.70.1
2. Perform a rollover
3. Verify that the mapping of the field does not contain the unit of measure
```
GET .ds-metrics-kubernetes.pod-default*/_mapping/kubernetes.pod.cpu.usage.nanocores
```
- Similar to: https://github.com/elastic/integrations/pull/9780

[Kubernetes][Bug-Fix] Fix kubernetes.pod.cpu.usage.nanocores unit of measure

---

packages/akamai/changelog.yml
packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
packages/akamai/manifest.yml

```
Fix the document _id calculation to allow events with the same requestId
to be indexed.
The httpMessage.requestId field in Akamai SIEM events is not unique to all
events based on observations of the data. It was observed that a given request
ID could have multiple records. Among three records with the same requestId,
one variant had httpMessage.bytes=0 and another had a different
httpMessage.responseHeaders with "Server: Akamai Image Server...".
I prefixed the document _id value with the timestamp based on recommendations
from the "Efficient Duplicate Prevention for Event-Based Data in Elasticsearch"
blog post.
References
- https://www.elastic.co/blog/efficient-duplicate-prevention-for-event-based-data-in-elasticsearch.
- https://github.com/akamai/akamai-apis/blob/b106ff167cb582efdaf4a …
```

akamai - fingerprint event.original instead of requestId

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/58d233a1965c848d955733e222d42512a590d893
None
None

[Security Rules] Update security rules package to v8.15.14

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a03522d3c115319b2828de41e430b6bb48eb32a8
None
None

[Security Rules] Update security rules package to v8.16.5

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/caf2d9e94aaace6a907b1b792165aeb4da64147b
None
None

[Security Rules] Update security rules package to v8.17.3

---

packages/gcp_vertexai/changelog.yml
packages/gcp_vertexai/data_stream/metrics/agent/stream/stream.yml.hbs
packages/gcp_vertexai/data_stream/metrics/manifest.yml
packages/gcp_vertexai/manifest.yml

This PR removes the zone filter and fixes the regions filter default value.
-

[GCP VertexAI] Remove zone filter and fix regions

---

packages/proofpoint_on_demand/changelog.yml
packages/proofpoint_on_demand/data_stream/audit/agent/stream/websocket.yml.hbs
packages/proofpoint_on_demand/data_stream/mail/agent/stream/websocket.yml.hbs
packages/proofpoint_on_demand/data_stream/message/agent/stream/websocket.yml.hbs
packages/proofpoint_on_demand/manifest.yml

- Enhancement
Added new advanced config options for blanket & infinite retries while updating default retry values.
-

[proofpoint_on_demand] - Added new advanced config options for blanket & infinite retries and updated default retry values

---

packages/lmd/changelog.yml
packages/lmd/elasticsearch/transform/pivot_transform/transform.yml
packages/lmd/manifest.yml

This PR fixes a bug in the `transform.yml` file that caused the transform to be unavailable. The issue was in the `runtime_mappings` script, which incorrectly assumed `host.ip` was always a list and assigned the second IP as `destination.ip`. The updated script now checks the size of `host.ip` and assigns the value accordingly.
The PR was tested with `elastic-package` and the transform is working as expected now:

[LMD] Bugfix in the LMD transform runtime script

---

packages/logstash/_dev/build/docs/README.md
packages/logstash/changelog.yml
packages/logstash/data_stream/node_cel/manifest.yml
packages/logstash/docs/README.md
packages/logstash/manifest.yml

Documentation
Updated documentation to remove technical preview label on Agent based monitoring
-->

Removed technical preview language

---

packages/elastic_connectors/agent/input/amazon_s3.yml.hbs
packages/elastic_connectors/agent/input/azure_blob_storage.yml.hbs
packages/elastic_connectors/agent/input/box.yml.hbs
packages/elastic_connectors/agent/input/confluence.yml.hbs
packages/elastic_connectors/agent/input/dropbox.yml.hbs
packages/elastic_connectors/agent/input/github.yml.hbs
packages/elastic_connectors/agent/input/gmail.yml.hbs
packages/elastic_connectors/agent/input/google_cloud_storage.yml.hbs
packages/elastic_connectors/agent/input/google_drive.yml.hbs
packages/elastic_connectors/agent/input/jira.yml.hbs
packages/elastic_connectors/agent/input/microsoft_sql.yml.hbs
packages/elastic_connectors/agent/input/mongodb.yml.hbs
packages/elastic_connectors/agent/input/mysql.yml.hbs
packages/elastic_connectors/agent/input/network_drive.yml.hbs
packages/elastic_connectors/agent/input/notion.yml.hbs
packages/elastic_connectors/agent/input/onedrive.yml.hbs
packages/elastic_connectors/agent/input/oracle.yml.hbs
packages/elastic_connectors/agent/input/outlook.yml.hbs
packages/elastic_connectors/agent/input/postgresql.yml.hbs
packages/elastic_connectors/agent/input/salesforce.yml.hbs
packages/elastic_connectors/agent/input/servicenow.yml.hbs
packages/elastic_connectors/agent/input/sharepoint_online.yml.hbs
packages/elastic_connectors/agent/input/sharepoint_server.yml.hbs
packages/elastic_connectors/agent/input/slack.yml.hbs
packages/elastic_connectors/agent/input/teams.yml.hbs
packages/elastic_connectors/agent/input/zoom.yml.hbs
packages/elastic_connectors/changelog.yml
packages/elastic_connectors/manifest.yml

This PR adds the escape_string helper to the connector_name field under elastic_connectors to ensure that the field is escaped correctly.
1. Create an agentless cloud deployment with image override for connectors, see these instructions on uploading the built package to Kibana: https://github.com/elastic/search-team/issues/8918#issuecomment-2554307174
2. Create an integration for Github from Integrations page entering a name into it that will not be a valid string in yaml, if not escaped - for example [Elastic-managed] github connector qlnF
3. Agentless connector should be deployed successfully
(To reproduce this error on an existing 9.0 agentless cloud deployment with image override for connectors, simply perform the above steps and watch the connector fail to deploy - see the Related …

Adding escape_string helper to ensure connector_name field is escaped properly

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated link to Loopback events (90x)
- updated MGMD events (26xx), added events 2625-2627
- update Module events (32xx), added 3241-3246
- updated Management events (430x)
- Mac Learn events were deprecated, moved to MAC address management events (480x)
- updated Mirroring events (670x)
- updated MAC Address mode configuration events (1100x), added event 11004
- updated MACsec events (1120x), added event 11205-11214
- added new event MPLS events (1330x)

#12249-6 Driving to OS 10.15 part 6

---

packages/fleet_server/changelog.yml
packages/fleet_server/manifest.yml

Add support for 9.0 in fleet_server package.
- Required by https://github.com/elastic/kibana/pull/208169.

[fleet_server] Support 9.0 stack

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml
packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

required_vars validation rules for CSPM integration and default agentless deployments.
Add required_vars validation rules for CSPM integration for conditionally required fields.
Defaulting CSPM and Asset Inventory to agentless deployments.
- Relates https://github.com/elastic/package-spec/pull/855
- Relates https://github.com/elastic/security-team/issues/10623
- Relates https://github.com/elastic/security-team/issues/10623

[Cloud Security] add required_vars validation rules and default CSPM and Asset Inventory to agentless deployment

---

packages/microsoft_exchange_online_message_trace/changelog.yml
packages/microsoft_exchange_online_message_trace/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_exchange_online_message_trace/data_stream/log/sample_event.json
packages/microsoft_exchange_online_message_trace/docs/README.md
packages/microsoft_exchange_online_message_trace/manifest.yml

```
[microsoft_exchange_online_message_trace] Remove event.start/end
Don't set `event.start` and `event.end` to `StartDate` and `EndDate`,
because those are query parameters, not properties of the event itself.
Also, extend the description of the `additional_look_back` setting to
note that up to 24h may be necessary (according to the API
documentation[1]).
[1]: https://learn.microsoft.com/en-us/previous-versions/office/developer/o365-enterprise-developers/jj984335%28v%3doffice.15%29
```
Elsewhere I suggested standard solutions for pagination when there is:
1. a delay between data creation and data availability, and/or
2. an unstable a period after initial creation of the data.
<details>
</details>
I suggested switching from the look-back strategy (introduced in …

[microsoft_exchange_online_message_trace] Remove event.start/end

---

packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/pipeline/test-common-config.yml
packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/system/test-default-config.yml
packages/qualys_vmdr/data_stream/asset_host_detection/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/asset_host_detection/manifest.yml
packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

```
Add show_igs API parameter as a UI option. Also optionally add fingerprint processor.
By default, Qualys API only includes detection records with 
`Confirmed` and `Potential` vulnerabilities. With show_igs option users 
can enable Qualys API to fetch detections of type `Info` as well.
Optionally adding fingerprint processor on event.original field so that 
any existing vulnerabilities in the current backing index will not be duplicated.
I prefixed the document _id value with the timestamp based on recommendations
from the "Efficient Duplicate Prevention for Event-Based Data in Elasticsearch"
blog post.
References
- https://qualysguard.qg2.apps.qualys.com/qwebhelp/fo_portal/api_doc/assets/index.htm#t=host_lists%2Fhost_detection.htm
- …
```

qualys_vmdr: Add "show_igs" and fingerprint processor UI options

---

packages/tenable_io/changelog.yml
packages/tenable_io/manifest.yml
packages/tenable_sc/changelog.yml
packages/tenable_sc/manifest.yml

The Tenable Vulnerability Management and Security Center integrations are not being presented when a user selects the Vulnerability Management category within the Security section of integrations, it is a very simple fix adding the below to the categories section:
`  - vulnerability_management`
This would help new users find this integration easier when browsing via categories

Missing vulnerability management category

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/chrome/agent/stream/cel.yml.hbs
packages/google_workspace/manifest.yml

The default limit in the Filebeat input is 1MiB which is too small for some responses, resulting in loss of visibility in debugging issues in the integration, so increase to 5MiB.

google_workspace.chrome: Increase CEL resource.tracer.maxsize limit

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/manifest.yml

```
[imperva_cloud_waf] Tolerate no separator in log files
Make the CEL program tolerate log files that don't contain a
header/events separator (`|==|`).
The existing CEL program can fail with the error:
failed evaluation: failed eval: ERROR: <input>:19:35: index out of
bounds: 1 | ).as(v, v.next < size(v.worklist) ? |.................
.................^
With this change, it will not fail, but no events will be returned.
```
The observed error is for the index `1`. The use of `v.worklist[v.next]` will never cause that, because those uses are all surrounded by the condition `v.next < size(v.worklist)`, so it must be the access following `split("|==|")`.
[Log file structure documentation](https://docs.imperva.com/bundle/cloud-application-security/page/more/log-file-structure.htm).
Here's a …

[imperva_cloud_waf] Tolerate no separator in log files

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/telephony_v2/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

```
[cisco_duo] Avoid obsolete cursor data in activity, telephony_v2
In an earlier version of the CEL code for `activity`[1] and
`telephony_v2`[2], `cursor.last_published` was set to a UNIX timestamp
value. This was changed to use RFC3339 formatted times in later
PRs[3][4] (with the corresponding read-time parsing added in [5]).
Users who didn't create a new policy may have the current parsing logic
fail when it encounters an old UNIX timestamp value in
`cursor.last_published`.
This PR addresses that issue by renaming `cursor.last_published` to 
`cursor.last_response_ts`. That effectively clears the cursor so that
obsolete values will not be seen.
[1]: https://github.com/elastic/integrations/blob/2ea993/packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs#L111-L114
[2]: …
```

[cisco_duo] Avoid obsolete cursor data in activity, telephony_v2

---

packages/apache/changelog.yml
packages/apache/manifest.yml

Prepare apache package for 9.0.
The apache package is used in Kibana test suites and we need to have it before enabling constraints in https://github.com/elastic/kibana/pull/208169.

[apache] Support stack 9.0

---

packages/azure_billing/_dev/build/docs/README.md
packages/azure_billing/changelog.yml
packages/azure_billing/docs/README.md
packages/azure_billing/manifest.yml

This PR brings the subscription id from the either of the three billing scope. As the subscription id is default which is also used to establish API connection.
- Verify the README for scope changes.

[Azure Billing] Fix billing subscription scope in doc

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/archive_search_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/audit_events/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/dlp_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/message_release_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/threat_intel_malware_customer/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/threat_intel_malware_grid/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/ttp_ap_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/ttp_ip_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/ttp_url_logs/agent/stream/cel.yml.hbs
packages/mimecast/manifest.yml

```
[mimecast] Fix cursor time formatting and selection
In the `audit_events` data stream, the `state.cursor.last` value was
handled as a time type, but when cursor data is reloaded from the file
the value will be a string. The change matches the behavior in other
data streams: explicitly format the time as a string when storing it,
and handle it as a string when reading it.
The logic for selecting a time for the cursor was to take the max of
returned times and `now`. This will usually use the time `now` as the
new starting point, instead of the time of last data. The fix is to only
use `now` if there is no returned data, and otherwise use the latest
returned time.
```

[mimecast] Fix cursor time formatting and selection

---

packages/panw/changelog.yml
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-audit-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-authentication-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-config-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-correlated-events-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-decryption-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-globalprotect-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-gtp-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-hipmatch-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-ip-tag-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-sctp-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-system-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-time-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-tunnel-inspection-sample.log-expected.json
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-userid-sample.log-expected.json
packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
packages/panw/manifest.yml

- Breaking change
During the parse of the PANW log messages, the original `message` field is parsed by a `grok` filter and generates a new partial `message` field.
This partial `message` field will then be parsed by the auxiliary ingest pipelines, but after the parse is completed, the field is not removed and is part of the final document.
Since ths `message` fields is the majority of the original source message, this can represent an increase of almost 50% in storage requirements for the PANW data stream.
This PR aims to remove this field.
- Closes #12511

[PANW] Remove leftover message field after parse

---

docs/ci_pipelines.md

Update docs about CI pipelines to include the new special comment that can be posted in Pull Requests to trigger builds to test packages with an specific Elastic stack version.
- Relates https://github.com/elastic/integrations/pull/12536
- Relates https://github.com/elastic/integrations/pull/12516
Examples of the GitHub check status:
- Pending status:
- Finished (success) status:

[CI][docs] Update docs with new special comment for PRs

---

packages/jamf_pro/changelog.yml
packages/jamf_pro/data_stream/inventory/_dev/test/pipeline/test-inventory.json
packages/jamf_pro/data_stream/inventory/_dev/test/pipeline/test-inventory.json-expected.json
packages/jamf_pro/data_stream/inventory/fields/fields-general.yml
packages/jamf_pro/docs/README.md
packages/jamf_pro/manifest.yml

```
[jamf_pro] Fix mapping of `jamf_pro.inventory.general.enrollment_method`
Trying to map an object as a keyword resulted in events be dropped with
messages like:
Cannot index event '...' (status=400): {
"type": "document_parsing_exception",
"reason": "[1:8701] failed to parse field [jamf_pro.inventory.general.enrollment_method] of type [keyword] in document with id '...'. Preview of field's value: '...'",
"caused_by": {
"type": "illegal_argument_exception",
"reason": "Expected text at 1:8624 but found START_OBJECT"
}
}, dropping event!
The correct structure is in the API documentation[1]. The incoming field
is named `general.enrollmentMethod`.
[1]: https://developer.jamf.com/jamf-pro/v11.4.0/reference/get_v1-computers-inventory
```
- Closes #12021

[jamf_pro] Fix mapping of `jamf_pro.inventory.general.enrollment_method`

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/audit_events/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/cloud_integrated_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/siem_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/threat_intel_malware_customer/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/threat_intel_malware_grid/agent/stream/cel.yml.hbs
packages/mimecast/manifest.yml

We see situations where the CEL program is rendered in double quoted strings in the pre-config.yml in diagnostic bundles, making it difficult to read. The cause of this has now been identified as the presence of trailing whitespace on lines[1]. So remove those.
[1]https://github.com/go-yaml/yaml/issues/1041#issuecomment-2579279218
-

mimecast: fix rendering of CEL programs in config files

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/fields/fields.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

```
[o365] Static fields for use by security rules
Our security rules[1] use fields in `o365.audit.*`, some of which are
dynamic fields. When the `total_fields` limit is reached, additional
dynamic fields will be ignored, which can interfere with execution of
the rules.
This change adds static field definitions as necessary to never ignore
fields used by the security rules.
[1]: https://github.com/elastic/integrations/tree/main/packages/security_detection_engine/kibana/security_rule
```

[o365] Static fields for use by security rules

---

packages/apache_tomcat/changelog.yml
packages/apache_tomcat/data_stream/access/_dev/test/pipeline/test-access.log
packages/apache_tomcat/data_stream/access/_dev/test/pipeline/test-access.log-expected.json
packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
packages/apache_tomcat/manifest.yml

made the `HTTP version` inside the tomcat log optional.
~~- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) ~~
- Closes https://github.com/elastic/integrations/issues/10450

Apache Tomcat made the HTTP in the log optional

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/event/_dev/test/pipeline/test-email.log-expected.json
packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_email.yml
packages/m365_defender/manifest.yml

```
m365_defender: fix message ID handling
The current data flow for the fields changed here is NetworkMessageId[1] →
m365_defender.event.network.message_id → email.message_id and
InternetMessageId[1] → m365_defender.event.internet_message_id → email.local_id,
but the definition of email.message_id is that it represents the RFC5322
Message-ID[2], corresponding to the Defender InternetMessageId value, and
email.local_id[3] is the non-persistent identifier, reasonably corresponding to
the Defender NetworkMessageId value.
Also add m365_defender.event.internet_message_id to final remove processor.
[1]https://learn.microsoft.com/en-us/defender-xdr/advanced-hunting-emailevents-table#:~:text=NetworkMessageId,sending%20email%20system
[2]https://www.elastic.co/guide/en/ecs/current/ecs-email.html#fi …
```

m365_defender: fix message ID handling

---

packages/ti_custom/changelog.yml
packages/ti_custom/data_stream/indicator/fields/beats.yml
packages/ti_custom/docs/README.md
packages/ti_custom/elasticsearch/transform/latest_ioc/fields/beats.yml
packages/ti_custom/manifest.yml
packages/tychon/data_stream/cmrs/_dev/deploy/docker/sample_logs/test-base.ndjson
packages/tychon/data_stream/cmrs/_dev/test/system/test-default-config.yml

Fix system tests for 9.0.0 in Tychon and Custom TI packages.
Added mapping for `log.file.fingerprint` in Custom TI integration.
The filestream input has changed file identity determination from native to
fingerprint, and the default fingerprint minimum file size is 1kiB, so make
all test inputs at least this big in Tychon integration.
Same approach as taken in https://github.com/elastic/integrations/pull/12510.
Run system tests as follows:
```
elastic-package stack down && elastic-package stack up -v -d --version=9.0.0-SNAPSHOT && eval "$(elastic-package stack shellinit)"
```
Then in each of the affected package directories:
```
```
- Closes https://github.com/elastic/integrations/issues/12327
- Closes https://github.com/elastic/integrations/issues/12326

tychon, ti_custom: fix system tests for 9.0

---

packages/apm/changelog.yml
packages/apm/manifest.yml

`sampling.tail.storage_limit` is 0 by default in 9.0. See https://github.com/elastic/apm-server/pull/15467 .
As UI validation requires unit (e.g. GB), set apm integration default storage limit to `0GB` which carries the same meaning.
-

apm: change tail_sampling_storage_limit config default to 0GB

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/data_stream/apm_server_metrics/fields/beat-fields.yml
packages/elastic_agent/manifest.yml

[elastic_agent] Add missing apm-server tail sampling monitoring metrics mappings
Tail-based sampling monitoring metrics were missed in the bugfix in #10414 
- Part of https://github.com/elastic/apm-server/issues/14247

[elastic_agent] Add missing apm-server tail sampling monitoring metrics mappings

---

packages/kubernetes/_dev/build/docs/README.md
packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
packages/kubernetes/data_stream/container_logs/manifest.yml
packages/kubernetes/docs/README.md
packages/kubernetes/manifest.yml

This commit updates the Kubernetes Container Logs documentation to better explain that an input is always generated for every container.
It also fixes a broken link.
```
cd packages/kubernetes
elastic-package stack up -v -d
```
Navigate to https://localhost:5601/app/integrations/detail/kubernetes-1.70.2/overview
Check the new entry under "container-logs"
Add the integration, go to Collect Kubernetes container logs -> Advanced options -> Kubernetes container log path and check the new documentation for this field.
~~## Related issues~~

Update Kubernetes container logs documentation

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/agent/stream/stream.yml.hbs
packages/cisco_asa/data_stream/log/agent/stream/tcp.yml.hbs
packages/cisco_asa/data_stream/log/agent/stream/udp.yml.hbs
packages/cisco_asa/manifest.yml

- Fixed missing tz_map reference in agent files
- Tested manually with logfile, tcp, and udp inputs and verified that tz_map is being applied correctly.
```json
{
"agent": {
"name": "agent1",
"id": "00907d09-2b61-40d4-8cfc-89ee66f7dd6c",
"ephemeral_id": "29c1b216-477a-44e3-ae55-3e2cb9e7fa47",
"type": "filebeat",
"version": "8.17.0"
},
"elastic_agent": {
"id": "00907d09-2b61-40d4-8cfc-89ee66f7dd6c",
"version": "8.17.0",
"snapshot": false
},
"input": {
"type": "tcp"
},
"@timestamp": "2025-01-14T08:00:46.000-06:00",
"data_stream": {
"namespace": "default",
"type": "logs",
"dataset": "cisco_asa.log"
},
"host": {
"hostname": "hosst.domain.com"
},
"event": {
"severity": 4,
"reason": "IPv4 Address <10.1.1.1> IPv6 address <::> assigned to session",
"original": "Jan 14 08:00:46 hosst.domain.com : …
```

[cisco_asa] Fix issue with linking time zone mapping to agent config

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.21.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/1159867d72eae6e320889399d627423773e27989
None
None

[Security Rules] Update security rules package to v8.14.21

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/514965cdc0bbd0eb9134108cd84cb6bf7d95eff8
None
None

[Security Rules] Update security rules package to v8.16.6

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/306a7bf5560c9467430db40e1cd4d25ca52d7751
None
None

[Security Rules] Update security rules package to v8.15.15

---

packages/system/changelog.yml
packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
packages/system/manifest.yml

- Bugfix
- Fix dashboard query in [Metrics System] Host overview
- Closes #11528

[O11y][System] Fix dashboard query in `[Metrics System] Host overview`

---

.github/CODEOWNERS

This PR changes the code ownership of the `logstash` integration package from the @elastic/stack-monitoring team to the @elastic/logstash team.
The main reason behind this proposed change is that the Logstash team completely owns this package and since they are actively developing and maintaining it, it makes sense to cede code ownership on that folder and allow them to move faster.

Changed ownership of logstash package to logstash team

---

packages/logstash/manifest.yml

Update `logstash` owner in the package manifest to be the same defined in `.github/CODEOWNERS` file.
This difference between `.github/CODEOWNERS` and the package manifest is causing errors in builds triggered from PRs. Example: https://buildkite.com/elastic/integrations/builds/21798
- https://github.com/elastic/integrations/pull/12625

Update logstash owner in manifest

---

.buildkite/pull-requests.json

Buildkite builds should be triggered if `.github/CODEOWNERS` file is modified.
To avoid updating the owner without updating the corresponding package manifest or similar errors.
Relates https://github.com/elastic/integrations/pull/12625
Buildkite builds failing: https://buildkite.com/elastic/integrations/builds/21798

[ci] Remove .github folder from skip_ci_on_only_changed

---

packages/gigamon/changelog.yml
packages/gigamon/kibana/dashboard/gigamon-032aab7b-87b2-444c-8c86-956d092598fb.json
packages/gigamon/kibana/dashboard/gigamon-855a64dc-1a72-403f-932b-a5b848378f7e.json
packages/gigamon/kibana/dashboard/gigamon-8d02ca6f-9333-4cab-8b8a-a141e9fccdcf.json
packages/gigamon/kibana/dashboard/gigamon-e733c64e-6ea9-4dd6-a8ca-3914274598f3.json
packages/gigamon/manifest.yml

- Bug
Updated the Expired TLS Certificate Details widget in AppInsights dashboards to use real-time data instead of a hardcoded date. The title was also changed from "Internal SSL Certificates Expiration Date" to "Expired TLS Certificate Details" in NPM Dashboards. Removed the Connection Reset widget and rebuilt the SMB Conversation widget in the NPM Dashboard.
Before change
After Change

Fixed Queries in Gigamon Dashboards

---

.github/workflows/block-paths.yml

Github actions are not executed on events caused by creating pull requests from Github actions, to avoid infinite recursion. In our case this blocks PRs automated with actions.
Try to trigger the block paths workflow after checking the suites.

Try to trigger workflow to block paths on PRs created by github actions

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.16.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a6ee1de6de7d0d92973917ea99e27f990c608579
None
None

[Security Rules] Update security rules package to v8.15.16

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8c67391c3889ba04c35ca826e94637ce70c60dbd
None
None

[Security Rules] Update security rules package to v8.17.5

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.22.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ca734ac522567ce11791666e14e7866a282d5ab7
None
None

[Security Rules] Update security rules package to v8.14.22

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a254f5ca907cc5b1d8c3f5122f57f0eb18a5b7f3
None
None

[Security Rules] Update security rules package to v8.16.7

---

packages/cel/agent/input/input.yml.hbs
packages/cel/changelog.yml
packages/cel/manifest.yml

```
Add a user configurable 'condition' variable to allow users to control when 
the input should run. An example use case would be to apply Kubernetes 
autodiscovery conditions.
See https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html
Closes #12521
```

packages/cel - add 'condition' variable

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/chrome/agent/stream/cel.yml.hbs
packages/google_workspace/manifest.yml

```
In chrome events, next_page_token is stored at the root-level 
of state. As it is enclosed in state.with(), this leads to 
next_page_token getting carried into subsequent 
interval requests. 
This change moves next_page_token inside cursor, thus 
removing from root-level. Also simplifies the pageToken query 
parameter calculation.
```
**Tested using mito:**
1. Token at root-level (this carries token to next request.):
```
mito -data <(echo '{"token": "TOKEN1"}') <(echo '
state.with(
{
?"token": (1 > 2) ? optional.of("TOKEN2") : optional.none()
}
)
')
```
Returns:
```
{
"token": "TOKEN1"
}
```
2. Token at next-level (this omits token from next request):
```
mito -data <(echo '{"next": {"token": "TOKEN1"}}') <(echo '
state.with({
"next": {
?"token": (1 > 2) ? optional.of("TOKEN2") : …
```

google_workspace: Omit pageToken from interval requests in chrome events

---

.github/workflows/block-paths.yml

Update check-blocked paths GitHub Action workflow to add a mechanism to trigger this workflow in pull requests created by other GitHub Actions.
Example: https://github.com/elastic/integrations/pull/12684
Follows: #12668 
Related docs:
- `github` context: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
- `pull_request` payload: https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request
- `issue_comment` payload: https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment

[CI] Try to trigger workflow to block paths on PRs created by github actions and comments

---

.github/workflows/block-paths.yml

Keep just the `pull_request` event for block-paths github workflow.
In case, this GitHub action is not triggered because the PR has been created by another Github Action workflow, that PR can be closed and re-opened in order to trigger the corresponding GitHub action workflow.
Related [docs](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow):
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. 
Follows #12668
Follows #12688

[CI] Remove issue_comment event in block-paths workflow

---

packages/awsfirehose/changelog.yml
packages/awsfirehose/manifest.yml

- Enhancement
WHAT: Enabling support for AWS Firehose integrations for 9.0 version
WHY: Is needed in order to enable above integrations in version 9.0.0
1. Clone Pr
2. elastic-package build with v0.109.1
3. elastic-package stack up -d -v --version=9.0.0-SNAPSHOT to install a local ES
- Relates #https://github.com/elastic/integrations/issues/12529

AWS Firehose for 9.0.0 enablement

---

packages/elasticsearch/changelog.yml
packages/elasticsearch/manifest.yml
packages/kibana/changelog.yml
packages/kibana/manifest.yml

Updated ssl node descriptions in manifest.yml for integrations owned by stack-monitoring. This commit updates descriptions to the ssl node to be uniform with other integrations that are being updated.
Updated ssl node descriptions in manifest.yml for integrations owned by stack-monitoring. This commit updates descriptions to the ssl node to be uniform
- Closes #12711
- Relates #11792
Originally, we update the descriptions on all the files. This created some issues with so many teams needing to validate the files. This is currently a partial update with files that are owned by sec-deployment-and-devices,
One is owned by bs-infraobs-integrations. As such the only verification would be to check that was what updates is uniform. Note that the metrics type datastream points to a metricbeat …

Updated description on ssl node in manifest.yml to be uniform and link to online documentation for integrations owned by stack-monitoring

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/apiserver/manifest.yml
packages/kubernetes/data_stream/container/manifest.yml
packages/kubernetes/data_stream/node/manifest.yml
packages/kubernetes/data_stream/pod/manifest.yml
packages/kubernetes/data_stream/state_container/manifest.yml
packages/kubernetes/data_stream/state_cronjob/manifest.yml
packages/kubernetes/data_stream/state_daemonset/manifest.yml
packages/kubernetes/data_stream/state_deployment/manifest.yml
packages/kubernetes/data_stream/state_job/manifest.yml
packages/kubernetes/data_stream/state_namespace/manifest.yml
packages/kubernetes/data_stream/state_node/manifest.yml
packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
packages/kubernetes/data_stream/state_pod/manifest.yml
packages/kubernetes/data_stream/state_replicaset/manifest.yml
packages/kubernetes/data_stream/state_resourcequota/manifest.yml
packages/kubernetes/data_stream/state_service/manifest.yml
packages/kubernetes/data_stream/state_statefulset/manifest.yml
packages/kubernetes/data_stream/state_storageclass/manifest.yml
packages/kubernetes/data_stream/system/manifest.yml
packages/kubernetes/data_stream/volume/manifest.yml
packages/kubernetes/manifest.yml

Added description to ssl.certificate_authorities and ssl.verification_mode, including links to documentation. Integrations owned by obs-cloudnative-monitoring
Added description to ssl.certificate_authorities and ssl.verification_mode, including links to documentation. Integrations owned by obs-cloudnative-monitoring
Originally, we updatesd the descriptions on all the files in integrations. This created some issues with so many teams needing to validate the files. This is currently a partial update with files that are owned by obs-cloudnative-monitoring.
git diff main | grep description: | grep + | sort -u
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this …

Added description on ssl.* nodes in data_streams owned by obs-cloudnative-monitoring

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/audit_events/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/audit_events/sample_event.json
packages/mimecast/docs/README.md
packages/mimecast/manifest.yml

See title
> [!NOTE]
> To reviewers:
> - Issue is described in detail in a similar fix: https://github.com/elastic/integrations/pull/12666
> - Also see test 1 below to know how pagetoken (in current version) is wrongly getting carried into next request and how PR fixes it.
1. Final `response state` from system tests in current vs updated (PR):
- Current:
```json
{
...
"cursor": {
"last": "2025-02-13T15:32:15Z"
},
"events": [],
"last_page": {
"data": [
{
"endDateTime": "2025-02-13T15:32:13Z",
"startDateTime": "2025-02-12T15:32:13Z"
}
],
"next": "lasttoken"
},
...
}
``` 
- Updated (PR):
```json
{
...
"cursor": {
"last": "2025-02-13T15:17:25Z"
},
"events": [],
"last_page": {},
...
}
``` 
2. System tests should pass.
```
2025/02/13 21:02:15 DEBUG found 0 hits in …
```

mimecast.audit_events: Prevent pageToken from incorrectly reappearing in interval requests

---

packages/checkpoint_harmony_endpoint/changelog.yml
packages/checkpoint_harmony_endpoint/data_stream/forensics/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/manifest.yml

```
Improves error reporting for API requests in 
`checkpoint_harmony_endpoint.forensics` data-stream
```
> [!NOTE]
> Better reviewable when `Hide-Whitespace` is selected.

checkpoint_harmony_endpoint.forensics: Improve error reporting for API requests

---

packages/microsoft_exchange_server/changelog.yml
packages/microsoft_exchange_server/data_stream/httpproxy/fields/fields.yml
packages/microsoft_exchange_server/data_stream/imap4_pop3/fields/fields.yml
packages/microsoft_exchange_server/data_stream/messagetracking/fields/fields.yml
packages/microsoft_exchange_server/data_stream/smtp/fields/fields.yml
packages/microsoft_exchange_server/manifest.yml

Change log.offset mapping to long as its exported by filebeat:
https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-log.html

[Exchange Server] Fix log.offset mapping type

---

packages/ess_billing/changelog.yml
packages/ess_billing/manifest.yml

Updates description field on ssl node in manifest.yml. Description is consistent with other integrations. This issue tracks change to integration owned by customer-architects
Originally, we update the descriptions on all the files. This created some issues with so many teams needing to validate the files. This is currently a partial update with files that are owned by customer-architects.
git diff main | grep description: | grep + | sort -u
- Closes #12699
- Relates #11792

Updated description on ssl node to include links to online documentation for integrations owned by customer-architects

---

packages/envoyproxy/changelog.yml
packages/envoyproxy/data_stream/log/fields/beats.yml
packages/envoyproxy/data_stream/log/sample_event.json
packages/envoyproxy/docs/README.md
packages/envoyproxy/manifest.yml

- Enhancement
- OBS package for 9.0.0 enablement activities of O11y `envoyproxy` integration.
- Fix `envoyproxy` fingerprint issue
1. update manifest.yml, package minor version upgrade and kibana dependency addition ` || ^9.0.0`.
2. build package
3. run package tests
4. install integration from kibana
5. check for any issues
Pass: Successfully Passed
Pending: Either permission issue or agent will stuck on 0 hits
Failed: Failed because of beats and integration changes are not in sync
Not Available: Tests are not available
No. | Packages | build & check | pipeline | system | asset | static
-- | -- | -- | -- | -- | -- | --
1 | envoyproxy | Pass | Pass | Pass | Pass | Pass
- Relates https://github.com/elastic/obs-integration-team/issues/148
- Closes …

Enablement & Sanity test run for evoyproxy OBS integration package for 9.0.0

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.17.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/53057087aec60821ed2fd1c35d1a8241548b96a7
None
None

[Security Rules] Update security rules package to v8.15.17

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/9ff53cce2aa30263b1f243e36f0c324a56508d41
None
None

[Security Rules] Update security rules package to v8.16.8

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/manifest.yml

Upgrade Osquery Manager for Kibana 9.0.0

Osquery Manager - add support for Kibana 9.0.0

---

packages/logstash/changelog.yml
packages/logstash/manifest.yml

Updates description field on ssl node in manifest.yml. Description is consistent with other integrations. This issue tracks change to integration owned by logstash
Visual check of committed files
- Closes #12707
- Relates #11792

Updated description on ssl node in manifest.yml owned by logstash to be uniform with other integrations

---

packages/zscaler_zia/changelog.yml
packages/zscaler_zia/manifest.yml

Updated minor version and Kibana constraints to support 9.0.0.
- Install latest elastic-package (currently v0.109.1)
- Run a local 9.0.0 stack with `elastic-package stack up -d -v --version=9.0.0-SNAPSHOT`
- Run tests in affected packages with `elastic-package test`
- Install the integration manually and check everything works as expected

zscaler_zia: update kibana constraint to support 9.0.0

---

packages/filestream/changelog.yml
packages/filestream/manifest.yml

Update Kibana constraint and add a new changelog entry to make filestream integration available on 9.0

Make filestream available in 9.X

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/kibana/dashboard/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824.json
packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
packages/elastic_agent/manifest.yml

Previous PR auto-merged while addressing feedback
https://github.com/elastic/integrations/pull/12793

[Elastic Agent] Extra Elastic Agent metric dashboard fixes

---

packages/snyk/changelog.yml
packages/snyk/data_stream/audit_logs/_dev/test/pipeline/test-snyk-audit.json-expected.json
packages/snyk/data_stream/audit_logs/elasticsearch/ingest_pipeline/default.yml
packages/snyk/manifest.yml

snyk: prevent empty-keyed fields in snyk.audit_logs.content.notSupported

---

packages/jamf_pro/changelog.yml
packages/jamf_pro/data_stream/inventory/_dev/test/pipeline/test-inventory.json
packages/jamf_pro/data_stream/inventory/_dev/test/pipeline/test-inventory.json-expected.json
packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
packages/jamf_pro/manifest.yml

```
jamf_pro: normalize jamf_pro.inventory.operating_system.version and os.version to three-part versions
Depending on the source of the Jamf data, we may receive two-part (e.g.
15.1) or three-part (e.g. 15.1.0) versions for versions where the last
part is zero. This leads to multiplication of the numbers of
semantically identical versions in search results and dashboards. So
normalise all OS versions to the three-part form, unless there are other
syntax components (this should never happen).
```
> [!NOTE]
> The dashboard uses `jamf_pro.inventory.operating_system.version`, so this why we need to change both.
- Closes #12799

jamf_pro: normalize jamf_pro.inventory.operating_system.version and os.version to three-part versions

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_asa/manifest.yml

- Add gsub processor to trim extra quotes from beginning and end of user.name field.
```
```
- Closes #12576

[cisco_asa] Trim quotes from user.name

---

packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/manifest.yml

This change is needed as currently on Kibana (main/9.0.0) the MS Defender integration doesn't show.
related checks for integration package versions https://github.com/elastic/kibana/pull/208169
- https://github.com/elastic/integrations/pull/12821

MS Defender for Endpoint - add support for Kibana `9.0.0`

---

.buildkite/pipeline.schedule-daily.yml
.github/workflows/updatecli/updatecli.d/bump-latest-7x-version.yml

Set 7.17.28 for the corresponding CI step in daily jobs.
Example of Github Action run updating this step:
https://github.com/elastic/integrations/actions/runs/13542068394/job/37845169395?pr=12899

[CI] Set daily jobs to run 7.17.28 instead of snapshot

---

.buildkite/pipeline.yml
.buildkite/scripts/common.sh
.buildkite/scripts/test_one_package.sh

Skip errors in `elastic_connectors` for now.
https://buildkite.com/elastic/integrations/builds/22711#01953abf-f486-41be-a9db-18ecf5d383ae
Error: 
```
Error: can't install the package: could not zip-install package; API status code = 403; response body = {"statusCode":403,"error":"Forbidden","message":"elastic_connectors installation is not authorized"}
```
As reference: https://github.com/elastic/kibana/pull/211419
Example of a Buildkite build skipping error:
https://buildkite.com/elastic/integrations/builds/22753#019541cc-d460-4651-80fc-db6fcf7a0999/585-608

[elastic_connectors][ci] Skip install error elastic connectors

---

packages/openai/_dev/build/docs/README.md
packages/openai/changelog.yml
packages/openai/data_stream/audio_speeches/manifest.yml
packages/openai/data_stream/audio_transcriptions/manifest.yml
packages/openai/data_stream/code_interpreter_sessions/manifest.yml
packages/openai/data_stream/completions/manifest.yml
packages/openai/data_stream/embeddings/manifest.yml
packages/openai/data_stream/images/manifest.yml
packages/openai/data_stream/moderations/manifest.yml
packages/openai/data_stream/vector_stores/manifest.yml
packages/openai/docs/README.md
packages/openai/manifest.yml

Reduce data granularity by changing the default bucket width of 1d to 1m (1 day to 1 minute). Have also updated the documentation to clearly mention the collection behaviour, storage implications, how granularity affects, etc.

packages/openai: Change default bucket_width and improve documentation and field descriptions

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/imperva_cloud_waf/manifest.yml

```
imperva_waf: improve config robustness and error reporting
* prevent missing trailing slash from causing collection failure
* avoid misleading errors resulting from collection failure
```
> [!NOTE]
> The CEL input is not tested in system testing. So extra caution is required in review.
-

imperva_waf: improve config robustness and error reporting

---

packages/http_endpoint/changelog.yml
packages/http_endpoint/manifest.yml

```
http_endpoint: improve HMAC config documentation
The documentation did not indicate the types of HMAC headers that are
accepted by the integration. Base64 header support (raw and std encoding)
was added to the input in v8.15, so in order to not mislead users, the
kibana version is bumped to that.
```
- Depends #12943

http_endpoint: improve HMAC config documentation

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/archive_search_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/dlp_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/message_release_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/ttp_ap_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/ttp_ip_logs/agent/stream/cel.yml.hbs
packages/mimecast/data_stream/ttp_url_logs/agent/stream/cel.yml.hbs
packages/mimecast/manifest.yml

```
last_page is stored at the root-level of state. As it is enclosed 
in state.with(), this leads to last_page.next incorrectly getting 
carried into subsequent interval requests whenever last_page 
evaluates to optional.none().
This change removes last_page assignment to optional.none(), 
thus removing last_page.next it from interval requests. 
```
> [!NOTE]
> This fix is similar to audit events in #12770.

mimecast: Prevent pageToken from incorrectly reappearing in interval requests in multiple datastreams

---

.github/CODEOWNERS

Update ownership for O365 Metrics integration
Currently some of the data streams are owned by the @elastic/security-service-integrations because they were created by one of the team members.
All the data streams that the security team owns:
- /packages/o365_metrics/data_stream/groups_activity_group_detail
- /packages/o365_metrics/data_stream/onedrive_usage_account_detail 
- /packages/o365_metrics/data_stream/teams_user_activity_user_detail
- /packages/o365_metrics/data_stream/viva_engage_groups_activity_group_detail
Based on the integration name and scope and looking at the sample logs:
https://github.com/elastic/integrations/blob/main/packages/o365_metrics/data_stream/groups_activity_group_detail/sample_event.json
https://github.com/elastic/integrations/blob/main/packages/o365_metrics/dat …

[o365_metrics]Update ownership for O365 Metrics integration

---

packages/aws_mq/_dev/build/docs/README.md
packages/aws_mq/changelog.yml
packages/aws_mq/data_stream/rabbitmq_metrics/agent/stream/stream.yml.hbs
packages/aws_mq/data_stream/rabbitmq_metrics/elasticsearch/ingest_pipeline/default.yml
packages/aws_mq/data_stream/rabbitmq_metrics/fields/base-fields.yml
packages/aws_mq/data_stream/rabbitmq_metrics/fields/ecs.yml
packages/aws_mq/data_stream/rabbitmq_metrics/fields/fields.yml
packages/aws_mq/data_stream/rabbitmq_metrics/manifest.yml
packages/aws_mq/data_stream/rabbitmq_metrics/sample_event.json
packages/aws_mq/docs/README.md
packages/aws_mq/manifest.yml

- Enhancement
- Add support for RabbitMQ metrics.
- Add minor documentation updates.
- `elastic-package build`
- `elastic-package stack up -v -d --services package-registry`

[AmazonMQ] Add RabbitMQ metrics dataset

---

packages/cisco_aironet/changelog.yml
packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log
packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log-expected.json
packages/cisco_aironet/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_aironet/data_stream/log/fields/aironet-fields.yml
packages/cisco_aironet/docs/README.md
packages/cisco_aironet/manifest.yml

Properly parse CLIENT_ORCH_LOG-6-CLIENT_ADDED_TO_RUN_STATE messages in cisco_aironet. The pipeline will now parse out all values from this message type: user name, SSID, and client MAC.
The client MAC will also be reformatted to follow the standard format specified in ECS.
---
The format of this message was found here: https://bst.cisco.com/quickview/bug/CSCwj11043

[cisco_aironet] Properly parse CLIENT_ORCH_LOG-6-CLIENT_ADDED_TO_RUN_STATE messages

---

packages/cockroachdb/changelog.yml
packages/cockroachdb/data_stream/status/manifest.yml
packages/cockroachdb/manifest.yml
packages/etcd/changelog.yml
packages/etcd/manifest.yml
packages/jolokia_input/changelog.yml
packages/jolokia_input/manifest.yml
packages/prometheus/changelog.yml
packages/prometheus/data_stream/collector/manifest.yml
packages/prometheus/data_stream/remote_write/manifest.yml
packages/prometheus/manifest.yml
packages/prometheus_input/changelog.yml
packages/prometheus_input/manifest.yml
packages/websphere_application_server/changelog.yml
packages/websphere_application_server/manifest.yml

Update ssl option descriptions package in manifest.yml remaining packages
git diff main | grep description: | grep + | sort -u
- Closes #12993
- Relates #12992. #11792

Update ssl option descriptions package in manifest.yml remaining packages obs infraobs integrations

---

packages/checkpoint_harmony_endpoint/changelog.yml
packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/antimalware/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/forensics/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatextraction/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/urlfiltering/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/zerophishing/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/manifest.yml

```
Changes in the error handling:
- When receiving a 503 Service Unavailable response, the sequence is restarted gratefully, cleaning the task ID and page token and waiting for the next interval.
- When receiving a 404 Not Found, the task ID is requested again for the same timeframe.
```
> [!TIP]
> Review commit by commit for a better understanding. The first one just propagates improvements from https://github.com/elastic/integrations/pull/12795 and https://github.com/elastic/integrations/pull/12158 to the rest of the data streams, while the second contains the new changes.
> [!NOTE]
> All data streams have identical `cel.yml.hbs` files.

checkpoint_harmony_endpoint: improve handling of 404 and 503 errors

---

.buildkite/pipeline.serverless.yml

Latest daily CI builds have failed due to a timeout. Currently, this timeout is set to 4 hours. This PR increases that timeout up to 6 hours.
https://buildkite.com/elastic/integrations-serverless/builds?branch=main
Example:
https://buildkite.com/elastic/integrations-serverless/builds/1004#01956916-4d67-4104-bab7-fcae6791f78e

[CI] Update timeout for serverless pipeline

---

catalog-info.yaml

Update team permissions related to Pull Request pipeline in `catalog-info.yaml`.
Teams added in this PR are the ones found in `.github/CODEOWNERS` file. These are the teams:
```
@elastic/cloud-security-posture
@elastic/customer-architects
@elastic/ecosystem
@elastic/elastic-agent
@elastic/elastic-agent-data-plane
@elastic/fleet
@elastic/logstash
@elastic/ml-ui
@elastic/obs-ds-hosted-services
@elastic/obs-ds-intake-services
@elastic/obs-infraobs-integrations
@elastic/obs-ux-management-team
@elastic/profiling
@elastic/protections
@elastic/search-extract-and-transform
@elastic/sec-applied-ml
@elastic/sec-deployment-and-devices
@elastic/sec-linux-platform
@elastic/security-asset-management
@elastic/security-service-integrations
@elastic/sec-windows-platform
@elastic/stack-monitoring
```

[CI] Update teams permissions in pull request pipeline

---

packages/azure/_dev/build/docs/events.md
packages/azure/changelog.yml
packages/azure/data_stream/events/agent/stream/stream.yml.hbs
packages/azure/data_stream/events/manifest.yml
packages/azure/docs/events.md
packages/azure/manifest.yml

The PR adds the new `processor_version` configuration option (an related ones) to enable the azure-eventhub processor v2 in the Azure Logs integration v2 preview.
- We increase the min stack version to 8.15.1.
- processor v2 is only available to for integration v2 preview (no integration v1 support)
- Add `storage_account_connection_string` config option (required for processor v2); the policy template builds a default value using the `storage_account_key` but also offers an override option.
The processor v2 uses the modern Event Hub SDK.
In this PR, I am adding the processor v2 settings to the advanced section of the integration v2 only (`events` data stream).
The goal is to enable only processor v2 for the data stream that can avoid contention among event hub partition consumers. …

[azure logs] enable event hub processor v2

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Removed the validation requiring a project ID for CSPM GCP integration when the account type is `organization`
Start Kibana
1. Load CSPM integration with the preview mode on (cloud_security_posture-1.13.0-preview05)
2. Select GCP
3. Select Organization account
4. Select Agentless
5. Enter the Organization ID
6. Enter the JSON Blob
7. Save button should be enabled
closes https://github.com/elastic/security-team/issues/12087
https://github.com/user-attachments/assets/8c0f99b3-c65b-47c0-8f35-673e36ac245d

[Cloud Security] Fix GCP Organization Agentless validation

---

packages/azure_logs/_dev/build/docs/README.md
packages/azure_logs/agent/input/input.yml.hbs
packages/azure_logs/changelog.yml
packages/azure_logs/docs/README.md
packages/azure_logs/manifest.yml

Enable the azure-eventhub processor v2 in the Custom Azure Logs integration.
Changes:
- Add `processor_version` config option to optionally enable the processor v2 (defaults to v1).
- Add the processor v2 related config options:
- `processor_update_interval`
- `processor_start_position`
- `migrate_checkpoint`
- `partition_receive_timeout`
- `partition_receive_count`
- Increase the min stack version to 8.15.1.
The processor v2 uses the modern Event Hub SDK. Microsoft fully supports the modern SDK, is more modular and flexible, uses fewer resources, and makes it possible to enhance the processor in upcoming releases.

[azure_logs] Enable azure-eventhub processor v2

---

packages/logstash/changelog.yml
packages/logstash/manifest.yml

Updates the Logstash package to make it available in Kibana 9.0
-

Add Kibana 9.0 support.

---

packages/cisco_ise/changelog.yml
packages/cisco_ise/manifest.yml
packages/zeek/changelog.yml
packages/zeek/manifest.yml

Update SSL node description in manifest.yml file for packages owned by sec-deployment-and-devices
diff main | grep description: | grep + | sort -u
- Closes #12995
- Relates #12992, #11792

Update SSL node description in manifest.yml file for packages owned by sec-deployment-and-devices

---

packages/ess_billing/changelog.yml
packages/ess_billing/data_stream/billing/agent/stream/cel.yml.hbs
packages/ess_billing/data_stream/billing/manifest.yml
packages/ess_billing/manifest.yml

In the previous implementation of the integration, the billing data was pulled with an offset starting when the integration is first run. This had the side effect of aligning days to whatever current time it was at installation.
IE instead of pulling from 00:00 to 23:59, it could be from 11:00 to 10:59 for instance.
This fixes this behavior, while also changing the lookbehind behavior: it used to be a count of hours, whereas it is now a count of days.

Aligned data pulls to calendar days

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/fdr/manifest.yml
packages/crowdstrike/manifest.yml

```
Crowdstrike FDR data stream can collect more than 1000 fields
and the data stream explicitly defines more than 500 fields.
In such cases, the total_fields.limit is automatically updated to 
10000[1] from the default 1000. 
Having such dynamic resizing could be detrimental when some of 
these explicitly mapped fields are later removed and the limit goes 
back to 1000. If it goes back to 1000, then it could end up not 
indexing all fields, even the ECS fields.
This PR sets the field limit to 2000 to facilitate 
indexing of all fields, especially ECS.
Ref: 
- [1] https://www.elastic.co/guide/en/integrations-developer/current/general-guidelines.html#_field_limits
```
Current (1.54.0) version:
`GET .ds-logs-crowdstrike.fdr-default-2025.03.11-000001/_settings`
```json
{ …
```

crowdstrike.fdr: Increase field limits in FDR data-streams to avoid unindexed ECS fields

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/manifest.yml

```
imperva_cloud_waf: add slash between url base and log file in second stage
When the CEL input was made more robust to user configuration, this was
forgottend. Add it now.
```
-

imperva_cloud_waf: add slash between url base and log file in second stage

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/660aca68c6a0cbf4adff9124f193bb2c88eeb01e
None
None

[Security Rules] Update security rules package to v8.16.9

---

.buildkite/scripts/common.sh

Remove dependencies that are already defined in `go.mod` when calling `with_mage` in buildkite scripts.
Applied same change as #11143 
Relates #13077

[CI] Remove deps from with_mage

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/1adca4ebc13cfcae11d7b103bc1b5972a9da2d18
None
None

[Security Rules] Update security rules package to v8.17.7

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.24.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cb220eb8553a9e419ac573c5225bf2276f4f812a
None
None

[Security Rules] Update security rules package to v8.14.24

---

packages/sentinel_one/_dev/build/docs/README.md
packages/sentinel_one/changelog.yml
packages/sentinel_one/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
packages/sentinel_one/data_stream/agent/elasticsearch/ingest_pipeline/default.yml
packages/sentinel_one/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
packages/sentinel_one/data_stream/group/elasticsearch/ingest_pipeline/default.yml
packages/sentinel_one/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/sentinel_one/docs/README.md
packages/sentinel_one/manifest.yml
packages/zscaler_zia/_dev/build/docs/README.md
packages/zscaler_zia/changelog.yml
packages/zscaler_zia/docs/README.md
packages/zscaler_zia/manifest.yml

Parent Ticket:
https://github.com/elastic/integrations/issues/11810
- Updated the documentation based upon agreed upon language to highlight that the integration now supports Agentless deployment for both sentinel one and zscaler
- Upgraded the `format_version` to latest, 3.2.3
- Updated Kibana version constraints to ^8.18 || ^9.0.0
1. Setup an api token within Sentinel One
2. Fill in the Console URL and API token within the Sentinel One configuration
3. Validated that data gets ingested into ES
4. Validated that the agentless index gets created and populated with the right values
5. Validate that the agent logs do not show any errors after a period of time in operation
Note: I set the start interval was 165d to get as much initial data as possible

Enable zscaler and sentinel one for agentless

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_ad/data_stream/user/elasticsearch/ingest_pipeline/entity.yml
packages/entityanalytics_ad/data_stream/user/fields/fields.yml
packages/entityanalytics_ad/docs/README.md
packages/entityanalytics_ad/manifest.yml

```
entityanalytics_ad: do not rename msDS-* fields
Apparently there are 322 msDS-* fields, so we either enumerate them in
the look-up table or hope that camelCase to snake_case is not lossy for
any of them if we want to do renames. Rather than doing that, accept
that we cannot rename any of them and revert this single case to retain
a consistent naming convention for them.
```
> [!NOTE]
> Strictly breaking, but we are before v1.
-

entityanalytics_ad: do not rename msDS-* fields

---

packages/beat/changelog.yml
packages/beat/manifest.yml
packages/elasticsearch/changelog.yml
packages/elasticsearch/elasticsearch/transform/index_pivot/transform.yml
packages/elasticsearch/manifest.yml
packages/kibana/changelog.yml
packages/kibana/manifest.yml

Add constraint for 9.0.0 for Stack Monitoring integrations
cc @jamiehynds

[Stack Monitoring] Add compatibility with 9.x

---

packages/ess_billing/changelog.yml
packages/ess_billing/data_stream/billing/agent/stream/cel.yml.hbs
packages/ess_billing/manifest.yml

The org ID can sometimes be interpreted in scientific notation, which causes issues in the ESS billing dashboard. This fixes it by changing the type of org_id back to a string, directly from the Elastic Agent collection.

Fix org ID scientific notation

---

packages/o365_metrics/changelog.yml
packages/o365_metrics/data_stream/active_users_services_user_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/groups_activity_group_detail/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/mailbox_usage_detail/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/mailbox_usage_quota_status/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/onedrive_usage_account_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/onedrive_usage_account_detail/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/onedrive_usage_file_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/onedrive_usage_storage/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/outlook_activity/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/outlook_app_usage_version_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/service_health/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/sharepoint_site_usage_detail/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/sharepoint_site_usage_storage/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/subscriptions/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/teams_call_quality/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/teams_device_usage_user_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/teams_user_activity_user_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/teams_user_activity_user_detail/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/viva_engage_device_usage_user_counts/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/viva_engage_groups_activity_group_detail/agent/stream/cel.yml.hbs
packages/o365_metrics/manifest.yml

- Enhancement
Add support for configuring resource parameters, such as rate_limit, retry, and others.
-

[O365_metrics] Add support for configuring resource parameters.

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/manifest.yml
packages/o365/changelog.yml
packages/o365/manifest.yml
packages/ti_anomali/changelog.yml
packages/ti_anomali/manifest.yml

Update Kibana version constraints to support 9.0.0 for Anomali, Cisco Duo, and o365 integrations.
After some discussions at https://github.com/elastic/integrations/issues/11775, it has been decided that these packages will keep their deprecated data streams or inputs.
- Install latest elastic-package (currently v0.109.1)
- Run a local 9.0.0 stack with elastic-package stack up -d -v --version=9.0.0-SNAPSHOT
- Run tests in affected packages with elastic-package test
- Install the integration manually and check everything works as expected
- Relates https://github.com/elastic/integrations/issues/11775

cisco_duo, anomali, o365: update Kibana constraint to support 9.0.0

---

packages/auditd_manager/changelog.yml
packages/auditd_manager/manifest.yml

Updates the constraint to support the 9.0 stack.

update `audit_manager` Kibana constraint integration to support to 9.0

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/manifest.yml

```
imperva_cloud_waf: step over non-UTF-8 data work items
It is possible for users to incorrectly configure their Imperva Cloud
WAF logging to send compressed data (this is the default). This results
in a CEL evaluation failure since we depend on the data being string
CEF. When the non-UTF-8 data is converted to a string, CEL refuses to
peform the conversion by design. When a user has done this, it appears
that logs in the compressed form persist, so the agent is unable to move
past the integration-invalid data. This change tries to perform the
conversion, falling back to an error message being sent to the index
when it is not possible. This helps identify cases where the
configuration is incorrect, and allows the collection to step over the
bodies that are not consumable.
Unfortunately …
```

imperva_cloud_waf: step over non-UTF-8 data work items

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/manifest.yml

See title.
Since the input is not tested, the behaviour change here can be checked with the two CEL programs below, good.cel (new code) and bad.cel (original code) that reflect the defective code region in the agent configuration with minor modifications to allow it to run without an endpoint.
```
$ mito bad.cel 
failed program instantiation: failed compilation: ERROR: <input>:5:71: found no matching overload for '_?_:_' applied to '(bool, list(map(string, string)), list(map(string, map(string, string))))'
|  "events": try(string(body), "error").as(body, type(body) == type("") ?
| ......................................................................^
$ mito good.cel
[
{
"events": [
{
"error": {
"message": "invalid UTF-8 in bytes, cannot convert to string: check imperva waf logging is …
```

imperva_cloud_waf: work around type mismatch

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/pipeline/test-asset-host-detection.log-expected.json
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/manifest.yml

```
Fix `event.category` for asset vulnerabilities.
Currently in `asset_host_detection` data-stream, the 
`event.category` is incorrectly mapped to `host`.
This causes issue with Elastic CDR workflows as the data 
corresponds to host vulnerabilities. 
Update `event.category` to `vulnerability` to fix it.
```
Pipeline tests pass for `asset_host_detection`.
```
--- Test results for package: qualys_vmdr - START ---
╭─────────────┬──────────────────────┬───────────┬──────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE     │ DATA STREAM          │ TEST TYPE │ TEST NAME                                                │ RESULT │ TIME ELAPSED │
├─────────────┼──────────────────────┼───────────┼──────────────────────────────────────────────────────────┼─────── …
```

qualys_vmdr: Fix `event.category` for asset vulnerabilities.

---

packages/elasticsearch/changelog.yml
packages/elasticsearch/elasticsearch/transform/index_pivot/transform.yml
packages/elasticsearch/manifest.yml

Negative values were cut from the calculation of the delta between the start and end values of the metrics. This was causing the ingest volume to be inflated.
Values can be negative when a merge, or document deletion occurs.
This deletes the `Math.max(0, XX)` in the transform job bucket scripts where relevant (ie where the metrics aren't ever-increasing gauges that are reset upon node restart or shard migration)

Fixed transform job definition that was inflating ingest volume

---

packages/universal_profiling_agent/changelog.yml
packages/universal_profiling_agent/manifest.yml
packages/universal_profiling_collector/changelog.yml
packages/universal_profiling_collector/manifest.yml
packages/universal_profiling_symbolizer/changelog.yml
packages/universal_profiling_symbolizer/manifest.yml

Universal Profiling: Add Kibana constraint to support 9.0.0

Universal Profiling: Add Kibana constraint to support 9.0.0

---

packages/checkpoint_harmony_endpoint/changelog.yml
packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/antimalware/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/forensics/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatextraction/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/urlfiltering/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/zerophishing/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/manifest.yml

Fixing a CEL condition that made the `endTime` query parameter being null when `state.cursor.next_endTime` is also null, leading to the following error:
```
{"success":false,"error":{"status":400,"name":"Bad Request","details":["endTime should not be empty"]}}
```
> [!NOTE]
> All data streams have identical `cel.yml.hbs` files.

checkpoint_harmony_endpoint: fix assignment of endTime query parameter

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/_dev/test/pipeline/test-event.json
packages/imperva_cloud_waf/data_stream/event/_dev/test/pipeline/test-event.json-expected.json
packages/imperva_cloud_waf/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/imperva_cloud_waf/data_stream/event/sample_event.json
packages/imperva_cloud_waf/docs/README.md
packages/imperva_cloud_waf/manifest.yml

```
It is possible that cef.extensions.xff can contain ',' separated 
IPs. Handle such cases and convert the field as array by default.
```
Passes pipeline tests (with comma-separated `xff`)
```
--- Test results for package: imperva_cloud_waf - START ---
╭───────────────────┬─────────────┬───────────┬────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE           │ DATA STREAM │ TEST TYPE │ TEST NAME                                  │ RESULT │ TIME ELAPSED │
├───────────────────┼─────────────┼───────────┼────────────────────────────────────────────┼────────┼──────────────┤
│ imperva_cloud_waf │ event       │ pipeline  │ (ingest pipeline warnings test-event.json) │ PASS   │ 376.180458ms │
│ imperva_cloud_waf │ event       │ pipeline  │ test-event.json …
```

imperva_cloud_waf: Handle multiple IPs in `cef.extensions.xff`

---

packages/ti_threatconnect/changelog.yml
packages/ti_threatconnect/elasticsearch/ingest_pipeline/tactics_compatibility.yml
packages/ti_threatconnect/elasticsearch/transform/latest/transform.yml
packages/ti_threatconnect/manifest.yml

```
[ti_threatconnect] Add a compatibility pipeline to the transform
See `packages/ti_threatconnect/elasticsearch/ingest_pipeline/tactics_compatibility.yml`
for an explanation of this change.
This has been manually tested against a live server.
```
I tested by ingesting data that included tactics using package version 1.8.0, then updated to 1.9.2 and checked that the transform did not encounter any mapping conflicts and the rebuilt destination index had the correct data.
Here's an example from the old destination index (note the field `threat_connect.indicator.tags.data.tactics.data`):
And the same document in the rebuilt destination index (note the field `threat_connect.indicator.tags.data.tactics`):

[ti_threatconnect] Add a compatibility pipeline to the transform

---

packages/rubrik/changelog.yml
packages/rubrik/data_stream/drives/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/filesets/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/global_cluster_performance/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/managed_volumes/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/monitoring_jobs/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/mssql_databases/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/node_statistics/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/physical_hosts/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/sla_domains/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/tasks/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/unmanaged_objects/agent/stream/cel.yml.hbs
packages/rubrik/data_stream/virtual_machines/agent/stream/cel.yml.hbs
packages/rubrik/manifest.yml

I added support of for proxy settings in rubriks integration. A client needed it.

Update: Add support for proxy in CEL for rubrik integration

---

packages/apache/changelog.yml
packages/apache/manifest.yml

9.x support in the apache package was unexpectedly removed in 1.28.0, after https://github.com/elastic/integrations/pull/12503/files#diff-c1bfeefb3a7a71c324e3d6ee4ea6ed2b3cb6fd640e040b146c03582c3216cf37R14.
Recover support for 9.0 in this package.
- Reverts part of https://github.com/elastic/integrations/pull/12503.
- Recovers https://github.com/elastic/integrations/pull/12504.

Recover support for 9.0 in apache package

---

packages/wiz/changelog.yml
packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml
packages/wiz/manifest.yml

Update event.id field in latest cdr vulnerabilities to use ECS mapping

[Cloud Security][Wiz] add vulnerability event.id to use ecs mapping

---

packages/jamf_pro/changelog.yml
packages/jamf_pro/data_stream/inventory/_dev/test/pipeline/test-inventory.json
packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
packages/jamf_pro/data_stream/inventory/manifest.yml
packages/jamf_pro/manifest.yml

- Bug
**WHAT:** Fixed empty string issue for date query param in filter for Jamf Pro inventory data stream.
**WHY:** Recently there was a commit changing how the filter works detailed [here](https://github.com/harnish-elastic/integrations/commit/c730ea0f0ddbaa955e2a7189043617827fa880b5#diff-0ffc4d4d6aab9bfef1f294ac1e04c5560811b7c9ad54baba832b9d369b989476R40). The issue is that this change does not take into account the fact that due to the [previously existing cursor logic](https://github.com/harnish-elastic/integrations/commit/c730ea0f0ddbaa955e2a7189043617827fa880b5#diff-0ffc4d4d6aab9bfef1f294ac1e04c5560811b7c9ad54baba832b9d369b989476L73), there could be scenarios where the `cursor.last_report_date` is an **empty string**. 
Sending the date in the filter as an empty string causes the …

[Jamf_Pro] - Fix empty string issue for date query param in filter for Jamf Pro inventory data stream

---

packages/ti_threatconnect/changelog.yml
packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_threatconnect/elasticsearch/transform/latest/transform.yml
packages/ti_threatconnect/manifest.yml

```
ti_threatconnect: fix handling of missing cursor.last_timestamp
It is possible to get into a state where the program expects there to be
a last_timestamp in the cursor but none exists due to previous data
being present but empty. Fix this by falling back to the look-back time
if the last_timestamp is missing.
Also reorganise the code to make the logic less opaque.
```
-

ti_threatconnect: fix handling of missing cursor.last_timestamp

---

packages/checkpoint_harmony_endpoint/changelog.yml
packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/antimalware/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/forensics/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatextraction/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/urlfiltering/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/zerophishing/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/manifest.yml

```
The two changes included are:
- The handling of the 404 error when hitting the retrieve endpoint (that happens when the integration already received a valid task ID and page token, in this case, both parameters are cleaned and a new task ID is requested again for the same timeframe.
- In the generic error handling, also clean task ID and page token to avoid entering in a loop making requests with stale parameters.
```
> [!NOTE]
> All data streams have identical `cel.yml.hbs` files.

checkpoint_harmony_endpoint: improve handling of API errors

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_alert.yml
packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
packages/m365_defender/manifest.yml
packages/sentinel_one_cloud_funnel/changelog.yml
packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/sentinel_one_cloud_funnel/manifest.yml

```
m365_defender,sentinel_one_cloud_funnel: improve command line split script performance
Investigation in the crowdstrike fdr data stream has shown that this
processor can be significantly improved in terms of performance by
reducing string allocation while tokenising the command line. This
change replays the changes in that data stream in m365_defender and
sentinel_one_cloud_funnel.
ref: #13325
```
- Ref: #13325

m365_defender,sentinel_one_cloud_funnel: improve command line split script performance

---

docs/extend/add-data-stream.md
docs/extend/developer-tsds-guidelines.md
docs/extend/edit-ingest-pipeline.md
docs/extend/quick-start.md
docs/extend/what-is-an-integration.md

Related to https://github.com/elastic/docs-content/pull/914
Related to https://github.com/elastic/elasticsearch/pull/125663
Removes reliance on temporary redirects in the docs-content and elasticsearch repos.

[docs] Remove reliance on temporary redirects

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_ad/data_stream/user/elasticsearch/ingest_pipeline/entity.yml
packages/entityanalytics_ad/data_stream/user/fields/fields.yml
packages/entityanalytics_ad/docs/README.md
packages/entityanalytics_ad/manifest.yml

```
entityanalytics_ad: enrich the user object with AD security-related settings.
```
Adds boolean fields for account settings that are relevant to identify misconfigurations and security risks.
`elastic-package test pipeline -v`
Part of https://github.com/elastic/ia-trade-team/issues/537

[AD Entity Analytics] User Object Enrichments

---

packages/auth0/_dev/deploy/docker/files/config-logs.yml
packages/auth0/changelog.yml
packages/auth0/data_stream/logs/_dev/test/system/test-auth0-cel-config.yml
packages/auth0/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
packages/auth0/data_stream/logs/sample_event.json
packages/auth0/docs/README.md
packages/auth0/manifest.yml

- Bug
```
Under some circumstances when using the CEL input, the response can
be sent un-encoded,  since the CEL input sends it as a raw json to the
ingest pipeline to maintain compatibility, this can cause the date
processor to break when parsing the  fields
"auth0.logs.data.details.initiatedAt" and "auth0.logs.data.details.completedAt" as dates are interpreted
in  scientific notation, eg: "1.743012420759E12". This PR adds two
conversion scripts that fixes it by converting this  string notation to a
proper numeric value understood by the date processor.
```
-

[Auth0] - Fixed an existing date parsing issue for `auth0.logs` data stream

---

docs/tips_for_building_integrations.md

Update link to tips building integrations documentation.
This link is also used as part of the GitHub Pull Request template:
https://github.com/elastic/integrations/blob/b0dbc03952c9c55dae129b2eb7bf8401f8ad6c7a/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L32

Update link for tips building integrations documentation

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/manifest.yml

```
crowdstrike: improve ingest pipeline performance
This improves the performance of the null cleaning script in the pipeline's
postamble, and the command line arg splitter in the body of the pipeline.
The empty field change reduces the number of allocations for iterators by
half and improves the readability of the code.
│  old.bench  │           new.bench           │
│   sec/op    │    sec/op     vs base         │
remove-nulls   4.000µ ± 0%   2.000µ ± 50%  -50.00% (n=100)
The command line splitting script was consuming a significant proportion
of the pipeline's total CPU use. The original code was based on Go code
used in libbeat, on the assumption that the allocation and GC behaviour
would be similar between the two languages; this is not the case. While
slicing strings in Go is …
```

crowdstrike: improve ingest pipeline performance

---

packages/entityanalytics_entra_id/changelog.yml
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-common-config.yml
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-device.json-expected.json
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-users.json-expected.json
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/system/test-default-config.yml
packages/entityanalytics_entra_id/data_stream/entity/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_entra_id/data_stream/entity/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_entra_id/data_stream/entity/manifest.yml
packages/entityanalytics_entra_id/data_stream/entity/sample_event.json
packages/entityanalytics_entra_id/docs/README.md
packages/entityanalytics_entra_id/manifest.yml

```
Currently the integration doesn't have a way to preserve event.original.
Following a similar approach to #12206, this PR adds an option to 
preserve event.original.
```
Pipeline and system tests pass and populates `event.original` field.
```
--- Test results for package: entityanalytics_entra_id - START ---
╭──────────────────────────┬─────────────┬───────────┬─────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE                  │ DATA STREAM │ TEST TYPE │ TEST NAME                                   │ RESULT │ TIME ELAPSED │
├──────────────────────────┼─────────────┼───────────┼─────────────────────────────────────────────┼────────┼──────────────┤
│ entityanalytics_entra_id │ entity      │ pipeline  │ (ingest pipeline warnings test-device.json) │ PASS   │ …
```

entityanalytics_entra_id: Add "event.original" field when "preserve_original_event" is set.

---

packages/ti_crowdstrike/_dev/build/docs/README.md
packages/ti_crowdstrike/changelog.yml
packages/ti_crowdstrike/docs/README.md
packages/ti_crowdstrike/manifest.yml

The Scope for ti_crowdstrike IOC needs also have 'ioc-management:read' otherwise it results in 403  (access denied, authorization failed)
cel-ti_crowdstrike.ioc component state degraded, with 
```
error: 'single event error object returned by evaluation: {"error":{"code":"403","id":"403 Forbidden","message":"GET:{\n \"meta\": {\n  \"query_time\": 2.08e-7,\n  \"powered_by\": \"crowdstrike-api-gateway\",\n  \"trace_id\": \"8ad80abe-39e3-4b77-abb2-aefe3fc4037c\"\n },\n \"errors\": [\n  {\n   \"code\": 403,\n   \"message\": \"access denied, authorization failed\"\n  }\n ]\n}"}}'
```
For example from agent (debug) logs
```
{"log.level":"debug","@timestamp":"2025-03-21T13:10:57.138Z","message":"response state","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default" …
```

[doc] ti_crowdstrike doc update to setup on IOC scope to add ioc-management:read

---

packages/crowdstrike/changelog.yml

```
Updates changelog in main from backport fix #13397
This is inline with the guidelines for backporting[1].
Ref:
- [1] https://www.elastic.co/guide/en/integrations-developer/current/developer-workflow-support-old-package.html
```
- Relates https://github.com/elastic/integrations/pull/13397

crowdstrike.fdr: add backport's changelog entry

---

packages/awsfirehose/changelog.yml
packages/awsfirehose/data_stream/metrics/_dev/test/pipeline/test-mq-metrics.json
packages/awsfirehose/data_stream/metrics/_dev/test/pipeline/test-mq-metrics.json-expected.json
packages/awsfirehose/data_stream/metrics/routing_rules.yml
packages/awsfirehose/manifest.yml

- Enhancement
Add firehose routing rules for metrics from AWS/AmazonMQ namespaces. Select aws_mq.activemq_metrics and  aws_mq.rabbitmq_metrics datasets respectively for ActiveMQ and RabbitMQ metrics
- elastic-package build && elastic-package stack up -v -d --services package-registry
Not applicable

[AmazonMQ] Add firehose routing rules for ActiveMQ and RabbitMQ metrics

---

packages/aws/changelog.yml
packages/aws/data_stream/cloudwatch_logs/manifest.yml
packages/aws/manifest.yml

- Breaking change
- WHAT: We change the default value of the cloudwatch_lods data_stream.dataset to aws.cloudwatch_logs
- WHY:  This needs to match the package name cloudwatch_logs in order the preinstalled ingest mappings/templates for the given datastream to apply
- Clone dir
- cd packages/integrations/kubernetes
- elastic-package stack up -d -vvv --version=9.0.0-SNAPSHOT
- Create an elastic-agent policy
- Add kubernetes integration. The version 2.45.0 should be available 
- Closes #https://github.com/elastic/integrations/issues/12640
This is how the discalimer is displayed:
The default ingest template is displayed below:
So we changed the datastream.dataset to `aws.cloudwatch_logs`
Successful processing of cloudwatch events:
Important: We enable …

updating disclaimer for aws_cloudwatch logs

---

.github/CODEOWNERS

New packages may not be assigned to any team, so they can pass unnoticed.
Assign a default owner for the `/packages` directory, who should triage new packages and assign to the team actually maintaining the package.

Set a default owner for new packages

---

packages/ti_anomali/_dev/deploy/docker/files/intelligence-api-config.yml
packages/ti_anomali/changelog.yml
packages/ti_anomali/data_stream/intelligence/_dev/test/system/test-default-config.yml
packages/ti_anomali/data_stream/intelligence/agent/stream/cel.yml.hbs
packages/ti_anomali/data_stream/intelligence/manifest.yml
packages/ti_anomali/data_stream/intelligence/sample_event.json
packages/ti_anomali/docs/README.md
packages/ti_anomali/manifest.yml

Without initial polling interval, users fetch indicators from years ago
as seen in their Anomali Threatstream.
Adding configurable `initial_interval` option (with default 90 days) 
will help users adjust how far back to fetch indicators from.
Added `initial_interval` option to system tests config. System tests should pass.
```
--- Test results for package: ti_anomali - START ---
╭────────────┬──────────────┬───────────┬───────────┬────────┬───────────────╮
│ PACKAGE    │ DATA STREAM  │ TEST TYPE │ TEST NAME │ RESULT │  TIME ELAPSED │
├────────────┼──────────────┼───────────┼───────────┼────────┼───────────────┤
│ ti_anomali │ intelligence │ system    │ default   │ PASS   │ 37.072411042s │
╰────────────┴──────────────┴───────────┴───────────┴────────┴───────────────╯
--- Test results for …
```

ti_anomali: Add `initial_interval` parameter to API ingestion.

---

packages/elasticsearch/changelog.yml
packages/elasticsearch/elasticsearch/transform/index_pivot/manifest.yml
packages/elasticsearch/elasticsearch/transform/index_pivot/transform.yml
packages/elasticsearch/manifest.yml

Direct `_source` mode control is deprecated  - removed the setting for the transform destination index in the Elasticsearch integration
Closes https://github.com/elastic/integrations/issues/12847

Removed deprecated _source.mode in transform index

---

packages/okta/changelog.yml
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.log-expected.json
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-no-flattened-events.log-expected.json
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-yes-flattened-events.log-expected.json
packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
packages/okta/data_stream/system/sample_event.json
packages/okta/docs/README.md
packages/okta/manifest.yml

```
okta: retain full email address as user.name
The entityanalytics_okta integration retains the full email address
rather than only the username part of the address. This breaks being
able to correlate individual entities with events, in addition to
potentially allowing collision between non-identitical users in events.
So simplify the code and just keep the whole thing.
```
-

okta: retain full email address as user.name

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/fields/entity.yml
packages/cloud_asset_inventory/manifest.yml

`entity.name` was mistakenly mapped as `text` and not `keyword` impacting entity store aggregations

[Asset Discovery] Change entity.name from text to keyword

---

packages/proofpoint_on_demand/changelog.yml
packages/proofpoint_on_demand/data_stream/message/fields/fields.yml
packages/proofpoint_on_demand/manifest.yml

Applying `subobjects: false` to the `message.msg_parts.metadata` field in the messages data stream.
This object in source documents can look like:
```
"metadata": {
"mxtype": "Documentation",
"mxtype.localized": "Documentation",
...
}
```
Leading to the error when ingesting it:
```
(status=400): {"type":"illegal_argument_exception","reason":"can't merge a non object mapping [proofpoint_on_demand.message.msg_parts.metadata.mxtype] with an object mapping"}, dropping event!"
```
Setting `subobjects: false` so fields can be stored avoiding the nesting and the conflict.

proofpoint_on_demand: set subobjects false to msg_parts.metadata field

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cbeafe0838bee9a9a2583090d45970d27591fc0a
None
None

[Security Rules] Update security rules package to v8.17.8

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/deefc8830c03eabf12a307eaaa844a20f53f8947
None
None

[Security Rules] Update security rules package to v8.18.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/52d834fd8088c795c0ec738525c9b294f5f3d341
None
None

[Security Rules] Update security rules package to v8.16.10

---

packages/auth0/changelog.yml
packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-failure.json
packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-failure.json-expected.json
packages/auth0/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
packages/auth0/manifest.yml

This PR fixes `event.type` and `event.category` for the following failed authentication event actions:
- hundred-failed-logins-ip-address-blocked
- ten-failed-logins-ip-address-blocked
we've removed the `indicator` event.type and `threat` event.category for the above mentioned event.
**Note:** The newly added test logs are not live data but generated from the existing logs as per the requirement.
- Move to integrations/packages/m365_defender directory.
- Closes #13262

[Auth0] Fix `event.type` and `event.category` for failed authentication events

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
packages/elastic_agent/manifest.yml

This PR removes the `agent.name` filter with the hardcoded value `9ca5ae305860` from the Agent Metrics dashboard.  Currently, with this filter present, no metrics are displayed:
- Follow up to #12855

[Elastic Agent] Remove hardcoded `agent.name` filter from Agent Metrics dashboard

---

packages/azure/changelog.yml
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-managed-identity-sample.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-managed-identity.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-non-interactive-user-sample.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-non-interactive-user-signin.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-non-interactive-user.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-service-principal-signinlogs-sample.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-service-principal.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-sample.log-expected.json
packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
packages/azure/data_stream/signinlogs/fields/fields.yml
packages/azure/docs/adlogs.md
packages/azure/manifest.yml

- Bug
Add a new field `region_name` to map the location.state data to this field. Initially this was mapped to `country_name` which is not appropriate.
Added script to drop the null/empty values in the document and updated with more descriptive on_failure error message.
Install the integration and verify the signin logs captures the state in region_name field instead of country_name.

Fix Sign-in logs location.state field to region field

---

docs/ci_pipelines.md

Update CI pipelines document with the latest changes about the Elastic subscription and new steps in daily CI jobs.
Documentation about `STACK_VERSION` behavior requires #13491

[CI][Docs] Update ci docs basic subscription

---

go.mod
go.sum

Attempts to fix https://github.com/elastic/elastic-package/issues/2537, by downgrading github.com/creack/pty to the same version used in `elastic-package` repository, where the issue doesn't happen.

Downgrade github.com/creack/pty

---

packages/cloud_asset_inventory/data_stream/asset_inventory/agent/stream/aws.yml.hbs
packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

- Add cloud_connector value to credential type 
- Add require vars for Cloud Connector Credential Type
- Change External ID to password type

[Cloud Security Posture] UpdateCloud connector integration input

---

.github/CODEOWNERS

In https://github.com/elastic/integrations/pull/13391 we set a default owner for new packages, so a review is automatically requested and new packages don't pass unnoticed.
During the weeks we have had this system in place, we have noticed that most of the time someone from an integrations team has to do the review, and then the ecosystem still needs to approve.
To make this process more agile, we have created a new @elastic/integrations-triaging team where we could add representatives of the different integration teams.
This team is composed by now by some members of the ecosystem area plus @kcreddy from the security integrations team.

Change ecosystem to integrations-triaging as default owner

---

.github/CODEOWNERS
packages/osquery_manager/manifest.yml

Change the code owner of the Osquery integration to `security-defend-workflows`
Just verify the team name is right I guess?
No code changes.
None
None

[EDR Workflows] change the codeowner of osquery to security-defend-workflows

---

packages/cisco_meraki_metrics/changelog.yml
packages/cisco_meraki_metrics/data_stream/device_health/_dev/test/pipeline/test-pipeline-device-health.json-expected.json
packages/cisco_meraki_metrics/data_stream/device_health/elasticsearch/ingest_pipeline/default.yml
packages/cisco_meraki_metrics/manifest.yml

scale values in device channel utilization so they display correctly as percentages

[cisco_meraki_metrics] scale values in device channel utilization so they display correctly as percentages

---

packages/checkpoint_harmony_endpoint/changelog.yml
packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/antimalware/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/forensics/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/threatextraction/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/urlfiltering/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/data_stream/zerophishing/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/manifest.yml

Fix a typo that avoids reading properly the last timestamp from received data, as the incoming JSON body contains an array called `records` instead of `results`.
> [!NOTE]
> All data streams have identical `cel.yml.hbs` files.

checkpoint_harmony_endpoint: fix typo when calculating next start time

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Azure has deprecated username and password login. We noticed that we don't use it, but have references to it. This is a clean up only PR
Relates to https://github.com/elastic/cloudbeat/issues/3232

[CSPM] Remove unused azure credentials

---

packages/teleport/changelog.yml
packages/teleport/data_stream/audit/_dev/test/pipeline/test-common-config.yml
packages/teleport/data_stream/audit/_dev/test/pipeline/test-teleport-all-events.log-expected.json
packages/teleport/data_stream/audit/_dev/test/pipeline/test-teleport-generated.log-expected.json
packages/teleport/data_stream/audit/_dev/test/system/test-filestream-config.yml
packages/teleport/data_stream/audit/agent/stream/filestream.yml.hbs
packages/teleport/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/teleport/data_stream/audit/elasticsearch/ingest_pipeline/event-groups.yml
packages/teleport/data_stream/audit/manifest.yml
packages/teleport/data_stream/audit/sample_event.json
packages/teleport/docs/README.md
packages/teleport/manifest.yml

```
teleport: allow the user to decide which values should be set in
cloud.* fields.
This PR adds a UI configurator that allows the user to select
which of the two sources (or both) to use to populate the cloud fields. It
also tags the document with an indicator of which sources were available. 
```
- Closes #12918

[Teleport] Add support for configuring which cloud metadata to use

---

packages/log/agent/input/input.yml.hbs
packages/log/changelog.yml
packages/log/manifest.yml

The log input is disabled by default starting with the 9.0 stack version.
This additional parameter allows using the `log` integration despite that.
I've tested it locally by building the package and running the 9.0.0 stack with `elastic-package`. An enrolled agent was able to ingest logs using this integration.
https://www.elastic.co/docs/extend/integrations/testing-validation
- Relates https://github.com/elastic/integrations/pull/12503

Allow deprecated mode for the `log` integration

---

docs/docset.yml
docs/extend/add-mapping.md
docs/extend/package-spec.md
docs/extend/pipeline-testing.md
docs/extend/quick-start.md
docs/extend/testing-validation.md
docs/extend/what-is-an-integration.md

Fixes various syntax and rendering errors that might include:
* Fixing broken images
* Hardcoding book-level substitution values
* Fixing incorrectly closed blocks (admonitions, tab sets, code blocks, dropdowns etc.)
* Fixing poorly migrated complex tables
* Fixing poorly migrated lists
* Fixing poorly migrated tab sets
* Removing inline text formatting from directive titles where they won't be rendered (for example, inline `code` formatting in dropdown titles)
* Specifying if a version is trying to communicate if a feature was added, deprecated, or coming (for example, during migration `deprecated:[8.15.0]` became `[8.15.0]`, which doesn't give any information about _what_ happened in 8.15.0)
* Fixing nested dropdowns / definition lists
* Fixing poorly migrated footnotes
* Updating …

[docs] Fix various syntax and rendering errors

---

packages/filestream/_dev/build/docs/README.md
packages/filestream/changelog.yml
packages/filestream/docs/README.md
packages/filestream/manifest.yml

So, it's consistent with the previous `Custom Logs` package it's to replace.

Rename `Custom Filestream Logs` -> `Custom Logs (Filestream)`

---

packages/osquery/changelog.yml
packages/osquery/data_stream/result/elasticsearch/ingest_pipeline/default.yml
packages/osquery/manifest.yml

- Changed the set processor for event.type so it sets the value as an array to ensure compliance with ECS.
```
cd packages/osquery
```
- Closes #13600

[osquery] Ensure event.type is an array

---

packages/filestream/_dev/build/docs/README.md
packages/filestream/changelog.yml
packages/filestream/docs/README.md
packages/filestream/manifest.yml
packages/log/changelog.yml
packages/log/docs/README.md
packages/log/manifest.yml

It better reflects its current state.

Rename the log package from Legacy to Deprecated

---

packages/servicenow/changelog.yml
packages/servicenow/data_stream/event/_dev/test/system/test-default-config.yml
packages/servicenow/data_stream/event/agent/stream/cel.yml.hbs
packages/servicenow/data_stream/event/manifest.yml
packages/servicenow/data_stream/event/sample_event.json
packages/servicenow/docs/README.md
packages/servicenow/manifest.yml

```
Introduce an optional parameter to append additional query conditions
for advanced filtering needs. It is advised to avoid using timestamp
fields in the appended query to prevent potential issues with pagination and
cursor logic.
```
- Move to integrations/packages/servicenow directory.
- Closes #13413

[Servicenow] Add support to append `sysparm query` in CEL input

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.9 
Generated from commit  https://github.com/elastic/detection-rules/tree/46e4d04e5f1c96841c5d71e0f2cc61ffe1d9608c
None
None

[Security Rules] Update security rules package to v8.17.9

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.2
Generated from commit  https://github.com/elastic/detection-rules/tree/571e5248d93901bfcd340747754e082471a091ad
None
None

[Security Rules] Update security rules package to v8.18.2

---

packages/lmd/changelog.yml
packages/lmd/kibana/ml_module/lmd-ml.json
packages/lmd/manifest.yml

Remove time_of_day detector from ML module
Removed `time_of_day` detector from the ML module of LMD. The ML job `lmd_unusual_time_weekday_rdp_session_start` originally used two detectors: time_of_day and time_of_week. However, since these detectors rely on [different time formats](https://github.com/elastic/kibana/blob/19d2776b18247e1acf732da5a21c30a77fd20fa6/x-pack/platform/plugins/shared/ml/public/application/formatters/format_value.ts#L68), they cannot be combined in a single ML job. As a result, the time_of_day detector has been removed.
Tested locally using `elastic-package`
-

[LMD] Remove time_of_day detector from ML module

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

bump posture package major version to indicate a breaking change in Cloudbeat's next version which includes populating the event.outcome field with the same value from result.evaluation
- related https://github.com/elastic/cloudbeat/pull/3179
- closes https://github.com/elastic/security-team/issues/10639

[Cloud Security] bump posture package

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml
packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Add `required_vars` to Cloud Asset Inventory to complement https://github.com/elastic/kibana/pull/219001
- Relates to https://github.com/elastic/security-team/issues/12532

[Cloud Asset Inventory] Add `required_vars`

---

packages/elastic_connectors/manifest.yml

This PR adding the missing field `template_path` to `policy_templates` in [manifest.yml](https://github.com/elastic/integrations/blob/037cda7c46f84ca7c1d8055105f5d7fab59fda50/packages/elastic_connectors/manifest.yml#L163-L177) file for google_cloud_storage connector.
Due to the missing field the provisioning of the infrastructure for Elastic managed agentless connector was broken:

[Bug]Fixed missing template_path for google_cloud_storage elastic connector

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_ad/data_stream/user/elasticsearch/ingest_pipeline/entity.yml
packages/entityanalytics_ad/manifest.yml

entityanalytics_ad: map user group details to ecs fields

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/docs/README.md
packages/cloud_asset_inventory/kibana/index_pattern/cloud_asset_inventory-2773feaf-50bb-43f8-9fa9-8f9a5f85e566.json
packages/cloud_asset_inventory/manifest.yml

Fixes the Asset Inventory data view name.

[Cloud Security] Fix Cloud Asset Inventory dataview name

---

packages/atlassian_confluence/changelog.yml
packages/atlassian_confluence/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/atlassian_confluence/manifest.yml
packages/atlassian_jira/changelog.yml
packages/atlassian_jira/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/atlassian_jira/manifest.yml

```
atlassian_jira and atlassian_confluence: fix time parsing in cursor logic.
After reviewing the live request tracer, it was observed that the timestamps from Atlassian Jira Cloud include a
timezone offset (+0000), which was not being parsed correctly. To fix this, the expected timestamp layout
was added in parseDate.
Additionally, the expected timestamp layouts were added in formatDate for both Atlassian Jira and Atlassian Confluence
to ensure the full timestamp is captured accurately.
Tested the changes using mock server and the data available in the test folder.
```
Move to integrations/packages/atlassian_jira directory. …

[Atlassian JIRA and Atlassian Confluence] Fix Time Parsing in Cursor Logic

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d428fbd8c9ef5fe8d7467d16f2d966897d8f9aaa
None
None

[Security Rules] Update security rules package to v8.16.13

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/46baa3009df4dfb1f378b6af065636ee38fbdd5f
None
None

[Security Rules] Update security rules package to v8.17.11

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/07ef3aafc20b4805d8fd0d33dbfbf57f9d7b56dc
None
None

[Security Rules] Update security rules package to v8.18.4

---

dev/citools/kibana.go
dev/citools/kibana_test.go
dev/citools/logsdb.go
dev/citools/logsdb_test.go
dev/citools/packagemanifest.go
dev/citools/subscription.go
dev/citools/subscription_test.go
dev/testsreporter/_static/summary.tmpl
dev/testsreporter/builderror.go
dev/testsreporter/dataerror.go
dev/testsreporter/errorlinks.go
dev/testsreporter/format_test.go
dev/testsreporter/packageerror.go
dev/testsreporter/packageerror_test.go
dev/testsreporter/reporter.go
dev/testsreporter/reporter_test.go
dev/testsreporter/testsreporter.go
go.mod
magefile.go

Add the scripts used by `mage` in CI pipelines.
- Relates #13377 
- Relates #13473
- Relates #13491

[CI] Add missing mage scripts ci

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Remove Cloud Security Posture GCP project and organization Id from form validation.

[Cloud Security] Backport cloud security posture 1.13: remove GCP project and org Id from validation 

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
o365: ensure empty responses do not lead to invalid request ranges
It is possible for a content type to haev a content_created_at value
that is very close to the current time (less than 1s in the past). In
this case, the API timestamp range may end up with a time range that is
invalid for the API, with the startTime after the endTime. This change
ensures that in the case that the endTime has been clamped to now, the
startTime is clamped to 1s before now.
Also replace uses of the ternary operator with min and max function
calls where appropriate.
```
-

o365: ensure empty responses do not lead to invalid request ranges

---

.buildkite/scripts/common.sh

Remove the usage of the `-q` parameter when used as part of pipe with `git` commands.
It could report failure due to SIGPIPE errors. As it was, this code
```
if git diff --name-only "${commit_merge}" "${to}" | grep -q -E "^packages/${package}/" ; then
echo "[${package}] PR is affected: found package files"
return 0
fi
```
was returning failure (141 error code) even there were matching files with the given regex.
Related https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q
Buildkite build with tests:
- https://buildkite.com/elastic/integrations/builds/25683#0196ac79-4deb-448d-8609-c34b9a8a44d6
```bash
git fetch upstream pull/13810/head:pr-13810
(set -o pipefail ; git diff --name-only c08c07e2cd3268914d9c504d0a51273f33f63f4a befe8ead69811789c40cba2e907abf6d0bcd6046  | …
```

[CI] Do not use -q parameter together with git commands in pipe

---

packages/falco/changelog.yml
packages/falco/data_stream/alerts/_dev/test/pipeline/test-falco.log-expected.json
packages/falco/data_stream/alerts/_dev/test/pipeline/test-nopreserve.log-expected.json
packages/falco/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/falco/data_stream/alerts/fields/fields.yml
packages/falco/data_stream/alerts/sample_event.json
packages/falco/docs/README.md
packages/falco/manifest.yml

```
falco: fix conflicting field definitions for falco output fields and correct field types.
Resolved issues where scalar fields in the alerts data stream had children fieldscausing mapping conflicts.  
Specifically fixed the types for the following fields:
- `falco.output_fields.evt.time`
- `falco.output_fields.proc.ppid`
- `falco.output_fields.proc.sid`
- `falco.output_fields.proc.vpgid`
- `falco.output_fields.syslog.facility`
- `falco.output_fields.syslog.severity`
Updated field mappings to ensure consistent types and avoid hierarchy/type conflicts in the schema.
This change has been tested on the data available in the test folder.
```
Move to integrations/packages/falco …

[Falco] Fix Conflicting Field Types

---

.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/pipeline.serverless.yml
.buildkite/scripts/common.sh
.buildkite/scripts/trigger_integrations_in_parallel.sh

- Use GCP OIDC to copy the logs to the private storage.
- Use gcloud instead of gsutil (so it honours the Env variables)
- Tear-down is now managed by the BK plugin itself.
See the ci build
Relates to https://github.com/elastic/elastic-package/pull/2569

buildkite: use GCP OIDC

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml
packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Remove GCP project and organization required validation from Cloud Security Posture and Cloud Asset Discovery 
- relates https://github.com/elastic/kibana/pull/219001
- relates https://github.com/elastic/kibana/issues/220232

[Cloud Security] Asset Inventory and CSPM - remove GCP project and org id from validation

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/alert/manifest.yml
packages/crowdstrike/manifest.yml

The CrowdStrike alert integrations uses 2 API endpoints from CrowdStrike:
/alerts/queries/alerts/v2 → to get the composite IDs of all open alerts → limit of 10,000 (see https://www.falconpy.io/Service-Collections/Alerts.html#getqueriesalertsv2) as It's currently also defined as the default value for the batch size in the description.
The returned composite_ids of the first API call are then sent with a post again:
/alerts/entities/alerts/v2 → to get the alert details → limit of 1,000 (see https://www.falconpy.io/Service-Collections/Alerts.html#postentitiesalertsv2) 
which causes the integration to get an HTTP 413 request too large error if there are more than 1000 composite IDs returned from the first API which returns up to 10,000 IDs due to the limit.
As we already implemented a …

[Crowdstrike Alert] adjust batch size to API limit

---

packages/azure/_dev/build/docs/events.md
packages/azure/docs/events.md

Add a table with all the supported log categories and the destination dataset. It also highlights that the integration indexes the unsupported log categories using the `azure.platformlogs` dataset.
```sh
cd azure/packages
elastic-package build && elastic-package stack up -d -v --version 8.17.0  
```

[azure logs] Document Azure logs categories routing rules

---

packages/cloudflare_logpush/changelog.yml
packages/cloudflare_logpush/data_stream/http_request/_dev/test/pipeline/test-pipeline-http-request.log-expected.json
packages/cloudflare_logpush/data_stream/http_request/elasticsearch/ingest_pipeline/default.yml
packages/cloudflare_logpush/data_stream/http_request/fields/fields.yml
packages/cloudflare_logpush/data_stream/http_request/sample_event.json
packages/cloudflare_logpush/docs/README.md
packages/cloudflare_logpush/manifest.yml

```
cloudflare_logpush: map cloudflare_logpush.http_request.client.ssl.cipher to tls.cipher
Map cloudflare_logpush.http_request.client.ssl.cipher to the tls.cipher in order
to pick up its search behavior without risking potential breaking behavior.
```
Move to integrations/packages/cloudflare_logpush directory.
- Closes #13596

[Cloudflare Logpush] map cloudflare_logpush.http_request.client.ssl.cipher to tls.cipher

---

packages/ti_anomali/changelog.yml
packages/ti_anomali/data_stream/intelligence/manifest.yml
packages/ti_anomali/manifest.yml

```
ti_anomali: Add support for proxy URL and SSL configuration parameters in
intelligence data stream 
```
- Move to integrations/packages/ti_anomali directory.
- Related https://github.com/elastic/enhancements/issues/24137

[ti_anomali] Add support for proxy URL and SSL configuration parameters

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/fields/fields.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

Fix a mapping conflict in Elasticsearch when ingesting documents with the `Parameters` or `ModifiedProperties` fields. These fields may sometimes be strings or arrays of strings instead of objects, which conflicts with the existing mapping that defines them as objects. Once a document with an object-type field is ingested, Elasticsearch will reject subsequent documents where the same field is of a different type.
```
(status=400): {\"type\":\"document_parsing_exception\",\"reason\":\"[1:600] object mapping for [o365audit.Parameters] tried to parse field [Parameters] as object, but found a concrete value\"}, dropping event!
```
```
(status=400): {\"type\":\"document_parsing_exception\",\"reason\":\"[1:2] object mapping for [o365audit.ModifiedProperties] tried to parse field [null] as …
```

o365: Set subobjects false to conflict fields

---

.mergify.yml

Help with the backports automation using `mergify`:
- assign PR owner
- notify stalled PRs
-

mergify: support auto-assign backports and report stalled backports

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/02c6d5ee92ade002e6b606f6f91ab08c22f42d01
None
None

[Security Rules] Update security rules package to v8.16.14

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6f8eaa245181db990f0bb5df56cc5ca9729dbe89
None
None

[Security Rules] Update security rules package to v8.17.12

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d03efac787658b1ca84e4af42d5103f1352fdfb8
None
None

[Security Rules] Update security rules package to v9.0.5

---

packages/ti_custom/changelog.yml
packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_custom/data_stream/indicator/manifest.yml
packages/ti_custom/manifest.yml

```
ti_custom: add user-configurable HTTP Client Timeout parameter
This will give users the option to increase the resource.timeout parameter for CEL.
```
- Move to integrations/packages/ti_custom directory.

[ti_custom] Add user-configurable HTTP Client Timeout parameter

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/firewall_match.yml
packages/crowdstrike/manifest.yml

```
[crowdstrike] Correct network.direction mapping
In the falcon data stream, correct the mapping of `ConnectionDirection`
to `network.direction` to match the documentation.
Previously, the `ConnectionDirection` field was being incorrectly mapped
according to the values used for `TrafficDirection`.
```
Here's the meaning of the field values for `ConnectionDirection`, and `TrafficDirection`, from the documentation:

[crowdstrike] Correct network.direction mapping

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml

Cloud Asset Inventory:  fixed cloud formation URL

[Cloud Security] Cloud Asset Inventory:  fixed cloud formation URL

---

packages/cisco_secure_endpoint/changelog.yml
packages/cisco_secure_endpoint/data_stream/event/agent/stream/httpjson.yml.hbs
packages/cisco_secure_endpoint/manifest.yml

cisco_secure_endpoint: squelch errors from pagination ends

---

packages/github/changelog.yml
packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/github/data_stream/code_scanning/agent/stream/httpjson.yml.hbs
packages/github/data_stream/dependabot/agent/stream/httpjson.yml.hbs
packages/github/data_stream/issues/agent/stream/httpjson.yml.hbs
packages/github/data_stream/secret_scanning/agent/stream/httpjson.yml.hbs
packages/github/manifest.yml

github: squelch errors from pagination ends

---

packages/forgerock/changelog.yml
packages/forgerock/data_stream/am_access/elasticsearch/ingest_pipeline/default.yml
packages/forgerock/data_stream/am_access/fields/forgerock-fields.yml
packages/forgerock/data_stream/idm_access/elasticsearch/ingest_pipeline/default.yml
packages/forgerock/data_stream/idm_access/fields/forgerock-fields.yml
packages/forgerock/docs/README.md
packages/forgerock/manifest.yml

```
[forgerock] Map `forgerock.response.elapsedTime` as a long not a date (#)
The field represents a duration, not a point in time.
```

[forgerock] Map `forgerock.response.elapsedTime` as a long not a date

---

packages/sublime_security/_dev/build/docs/README.md
packages/sublime_security/changelog.yml
packages/sublime_security/docs/README.md
packages/sublime_security/manifest.yml

- Enabled agentless deployment for sublime security
- Upgraded the `format_version` to latest, 3.2.3
- Updated  Kibana version constraints to ^8.18 || ^9.0.0
1. Setup Sublime Security testing environment and get the api key from the dashboard
2. Setup agentless to use the api key and the correct endpoint (this was different than the default)
- Validate that data flows into elastic search
- Validated that metrics with regards to cpu and memory are OK from agent analyzer
- Validated that there are no pipeline error by searching for `event.kind`

Adding agentless deployment to the sublime security integration

---

packages/cribl/_dev/build/docs/README.md
packages/cribl/changelog.yml
packages/cribl/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml
packages/cribl/data_stream/metrics/fields/base-fields.yml
packages/cribl/data_stream/metrics/manifest.yml
packages/cribl/docs/README.md
packages/cribl/manifest.yml

```
cribl: reroute to metrics datastreams
Updated the documentation to specify separate index templates for logs and metrics
and added a dedicated metrics pipeline, ensuring correct handling of metric events.
```
- Closes #10700
- Relates #12480

[Cribl] Fix handling of metric event type

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_audit.yml
packages/infoblox_nios/manifest.yml

```
infoblox_nios: handle the parsing of ipv6 address
The convert processor failed to parse IPv6 addresses with octal
encoding. So a script processor has been added to parse the
octal-encoded IPv6 address before applying the convert processor.
```
- Move to integrations/packages/infoblox_nios directory.
- Closes #13782

[Infoblox NIOS] Handle the parsing of IPv6 address

---

packages/aws/_dev/build/docs/firewall.md
packages/aws/changelog.yml
packages/aws/docs/firewall.md
packages/aws/manifest.yml

```
aws.firewall: Document ingested log types of AWS Network Firewall.
The current documentation for AWS Network Firewall 
integration doesn't mention different log types ingested. 
This leads to users being unsure if the integration is 
capable to ingest all log types. This PR updates README 
documenting all different log types ingested by 
AWS Network Firewall.
```

aws.firewall: Document ingested log types of AWS Network Firewall

---

.github/workflows/updatecli/updatecli.d/bump-latest-8x-snapshot-version.yml

This PR updates the URL used to check about 8.x snapshots.
The previous URL was not updated since a few weeks ago.
Updating this URL keeps in the same result, as it is reporting patches versions for the  same 8.19.x version minor.

[CI] Update configuration updatecli for 8.x snapshot

---

.buildkite/scripts/backport_branch.sh

Add `dev/coverage` folder as another folder to sync in backport script.
Example of buildkite build failing:
https://buildkite.com/elastic/integrations-backport/builds/169#0196fd79-9677-43df-8892-0b7859d80f13
Tested in this buildkite build: https://buildkite.com/elastic/integrations-backport/builds/174

[CI] Add dev/coverage into backport script

---

packages/apm/agent/input/template.yml.hbs
packages/apm/changelog.yml
packages/apm/manifest.yml

apm: Add policy variable `tail_discard_on_write_failure` to configure `apm-server.sampling.tail.discard_on_write_failure`.
- Version constraints will be updated to much the below PR for the apm til config
1. Validated the  config using `elastic-packge` to install the packaged.  Used the Kibana UI to add the APM Integration. Verified the agent policy contained the correct config
2. Installed elastic agent locally. Validated the computed-config.yaml and validated the apm-server behavior when `discard_on_write_failure` was enabled and disabled 
- Part of https://github.com/elastic/apm-server/issues/15330
- Related to https://github.com/elastic/apm-server/issues/13525
- computed-config.yaml:
```yaml
sampling:
tail:
discard_on_write_failure: true
enabled: true
interval: 1m
policies:
- …
```

apm: Add config for tail-based sampling discard on write

---

packages/jamf_pro/changelog.yml
packages/jamf_pro/data_stream/events/fields/base-fields.yml
packages/jamf_pro/data_stream/events/sample_event.json
packages/jamf_pro/data_stream/inventory/fields/base-fields.yml
packages/jamf_pro/data_stream/inventory/sample_event.json
packages/jamf_pro/docs/README.md
packages/jamf_pro/manifest.yml

```
[jamf_pro] Add event.module definition for the events data stream
This matches what was already present in the inventory data stream.
Also updates the sample_event.json files. The constant_keyword fields
aren't currently included by elastic-package.
```

[jamf_pro] Add event.module definition for the events data stream

---

packages/box_events/changelog.yml
packages/box_events/data_stream/events/_dev/test/pipeline/test-anomalous-download.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-copy.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-create.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-download.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-invite.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-malicious-content.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-preview.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-rename.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-suspicious-locations.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-suspicious-sessions.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-trash.log-expected.json
packages/box_events/data_stream/events/_dev/test/pipeline/test-upload.log-expected.json
packages/box_events/data_stream/events/elasticsearch/ingest_pipeline/default.yml
packages/box_events/manifest.yml

```
box_events: improve the ecs field mappings for `user.*` fields
This PR is based on the earlier PR [1] that addressed improvements to the user.* field mappings.
In this update, some of the existing mappings have been revised and several new ones have been added.
[1] https://github.com/elastic/integrations/pull/12944
```
Move to integrations/packages/box_events directory.
- Closes #12971

[Box Events] Update and expand ECS `user.*` field mappings

---

packages/apm/agent/input/template.yml.hbs
packages/apm/changelog.yml
packages/apm/manifest.yml

Backport 2 PRs from 9.1 to 8.19:
- TBS ttl config https://github.com/elastic/integrations/pull/13348
- TBS discard_write_on_failure config https://github.com/elastic/integrations/pull/13950
This is a backport PR.
main changelog PR: https://github.com/elastic/integrations/pull/14031

apm: Backport TBS ttl and discard_on_write_failure to 8.19

---

packages/keycloak/changelog.yml
packages/keycloak/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/events.yml
packages/keycloak/data_stream/log/sample_event.json
packages/keycloak/docs/README.md
packages/keycloak/manifest.yml

```
keycloak: parse event.outcome field
This PR sets the ecs field `event.outcome` based on the value of `keycloak.login.type`.
```
- Move to integrations/packages/keyclock directory.

[KeyClock] Set the ECS field `event.outcome` based on the value of `keycloak.login.type`

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/o365/manifest.yml

As `organization` field may be a string instead of an object, the following error can appear when accessing its subfields being a string value.
```
Processor 'conditional' with tag '' failed with message 'dynamic getter [java.lang.String, id] not found'
```
Added a type check before accessing its subfields to avoid the above error.

o365: validate field type in pipeline before accessing subfields

---

packages/prisma_cloud/_dev/build/docs/README.md
packages/prisma_cloud/_dev/deploy/docker/files/config.yml
packages/prisma_cloud/changelog.yml
packages/prisma_cloud/data_stream/incident_audit/_dev/test/system/test-cel-config.yml
packages/prisma_cloud/data_stream/incident_audit/agent/stream/cel.yml.hbs
packages/prisma_cloud/data_stream/incident_audit/manifest.yml
packages/prisma_cloud/data_stream/incident_audit/sample_event.json
packages/prisma_cloud/docs/README.md
packages/prisma_cloud/manifest.yml

```
prisma_cloud: add support for REST API input to the incident audit data stream.
Previously, REST API input was not supported in the Incident Audit data stream. 
This update adds support for REST API input using CEL.
The API specifications were sourced from the Prisma Cloud API for Incident Audit[1], and the
changes were validated against a mock server.
[1] https://pan.dev/prisma-cloud/api/cwpp/get-audits-incidents/
```
Move to integrations/packages/prisma_cloud directory.
- Enhancement repo - 24540

[prisma_cloud] Add support for REST API Input to the Incident Audit data stream

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/fields/entity.yml
packages/cloud_asset_inventory/manifest.yml

Move `Attributes` (previously dynamic mapped object) to `entity.raw` flattened field
-  Related https://github.com/elastic/security-team/issues/12548

Move Attributes to a flattened entity.raw

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/agent/stream/cel.yml.hbs
packages/panw_cortex_xdr/data_stream/alerts/agent/stream/httpjson.yml.hbs
packages/panw_cortex_xdr/data_stream/incidents/agent/stream/httpjson.yml.hbs
packages/panw_cortex_xdr/manifest.yml

```
[panw_cortex_xdr] Improve rate limit configuration
- Remove HTTPJSON `request.rate_limit.*` configuration, since the API
does not return `X-Rate-Limit-*` headers.
- Add CEL `resource.rate_limit` configuration to set a fixed limit of 4
requests per second, which is just under half of the total limit.
The relevant API documentation[1] says:
> There is a limit of 10 API requests per second for each tenant. This
> includes all endpoints. Sending more than 10 requests per second can
> result in the following error: "Too many requests."
[1]: https://docs-cortex.paloaltonetworks.com/r/Cortex-XDR-REST-API/Get-Started-with-Cortex-XDR-APIs
```

[panw_cortex_xdr] Improve rate limit configuration

---

packages/logstash/changelog.yml
packages/logstash/data_stream/log/manifest.yml
packages/logstash/data_stream/slowlog/manifest.yml
packages/logstash/manifest.yml

Change default log files name in log and slow logs datastream to align with Logstash defaults.
- Updating to new version will not have conflict 
- System test `elastic-package test system`
- Spin up elastic-package on local and find the LS integration, as shown in the following pic:
- Closes #13015 
```
╭─me ~/Dev/elastic/integrations/packages/logstash  ‹upstream-main*› 
╰─➤  elastic-package test system                   
2025/05/31 10:21:44  INFO New version is available - v0.111.0. Download from: https://github.com/elastic/elastic-package/releases/tag/v0.111.0
Run system tests for the package
2025/05/31 10:21:44  INFO License text found in "/Users/mashhur/Dev/elastic/integrations/LICENSE.txt" will be included in package
2025/05/31 10:22:01  INFO Using service variant: …
```

[Logstash] Change default log files name in log and slow logs datastream

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/84b1016d8a22cfcd71b3bb17895f4424120fb45f
None
None

[Security Rules] Update security rules package to v8.16.15

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dbb83a6dd6c7107d2a24918b4cbdecbd8ebbb54a
None
None

[Security Rules] Update security rules package to v8.17.13

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/9d38a2970f3c241d689d1c6001966f73960c14a2
None
None

[Security Rules] Update security rules package to v9.0.6

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/fields/entity.yml
packages/cloud_asset_inventory/manifest.yml

Add `entity.source` ([ECS field](https://github.com/elastic/ecs/blob/main/rfcs/text/0049/entity.yml#L30))
- Related to https://github.com/elastic/security-team/issues/12550
- Complimentary of https://github.com/elastic/cloudbeat/pull/3317

[Asset Discovery] Add `entity.source` to asset discovery

---

packages/azure_metrics/_dev/build/docs/README.md
packages/azure_metrics/changelog.yml
packages/azure_metrics/data_stream/compute_vm/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/compute_vm_scaleset/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/container_instance/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/container_registry/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/container_service/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/database_account/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/monitor/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/storage_account/agent/stream/stream.yml.hbs
packages/azure_metrics/docs/README.md
packages/azure_metrics/manifest.yml

Follow-up of [beats PR](https://github.com/elastic/beats/pull/41790)
- WHAT: Adds `enable_batch_api` configuration parameter in azure resource metrics. 
- WHY:  Helps mitigating scalability problems
It can be easily tested by installing Azure Resource Metrics. Enable the `enable_batch_api` advanced setting.
Then the metrics will be collected from the azure batch api.
- Closes https://github.com/elastic/beats/issues/38624

Add enable_batch_api option in azure resource metrics

---

packages/beyondinsight_password_safe/changelog.yml
packages/beyondinsight_password_safe/data_stream/useraudit/_dev/test/pipeline/test-useraudits.json-expected.json
packages/beyondinsight_password_safe/data_stream/useraudit/elasticsearch/ingest_pipeline/default.yml
packages/beyondinsight_password_safe/data_stream/useraudit/sample_event.json
packages/beyondinsight_password_safe/docs/README.md
packages/beyondinsight_password_safe/manifest.yml

Modified the processing of user name fields including email addresses to align with the rest of the integrations. Changes applied include the following:
- When the user name is an email, this field is dissected into `<user.name>@<user.domain>`.
- Also the `user.email` field is populated with the full email address.
- Append `user.name` and `user.email` to `related.user`.
- Relates https://github.com/elastic/enhancements/issues/24531

beyondinsight_password_safe: standardize user name processing

---

packages/azure_metrics/_dev/build/docs/README.md
packages/azure_metrics/changelog.yml
packages/azure_metrics/data_stream/compute_vm/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/compute_vm_scaleset/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/container_instance/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/container_registry/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/container_service/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/database_account/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/monitor/agent/stream/stream.yml.hbs
packages/azure_metrics/data_stream/storage_account/agent/stream/stream.yml.hbs
packages/azure_metrics/docs/README.md
packages/azure_metrics/manifest.yml

Add the Latency config option to Azure Monitor integrations.
Latency is the time it takes for the Azure service to publish the metric values to Azure Monitor. The integration uses the latency value to compensate for the delay in metric value publishing.
Default value is 0. Typical values are 30s or 1m.
We expect the latency to help integrations with a few services that report metrics with delay.
- Relates https://github.com/elastic/beats/pull/44366

[azure metrics] Add latency config option

---

packages/okta/changelog.yml
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.log-expected.json
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-no-flattened-events.log-expected.json
packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-yes-flattened-events.log-expected.json
packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
packages/okta/data_stream/system/sample_event.json
packages/okta/docs/README.md
packages/okta/manifest.yml

```
According to ECS documentation about user fields usage[1]:
- When a system uses an email address as the main identifier, populate
both user.id and user.email with it.
This change copies the `user.name` field into the `user.email` field to align
with all other integrations where the main user identifier is an email address,
including Entity Analytics Okta.
This should help to who wants to correlate email addresses between integrations.
In this case, the user email is not dissected into `user.name@user.domail` as
for the Okta ecosystem, the user part of the email doesn't make sense by itself. 
[1] https://www.elastic.co/docs/reference/ecs/ecs-user-usage#ecs-user-identifiers
```
- Relates https://github.com/elastic/enhancements/issues/24531

Okta: populate user.email when user name is an email address

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_ad/data_stream/user/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_ad/data_stream/user/elasticsearch/ingest_pipeline/entity.yml
packages/entityanalytics_ad/data_stream/user/manifest.yml
packages/entityanalytics_ad/manifest.yml

```
[entityanalytics_ad] Remove members from group information by default
The `entityanalytics_ad.groups.member` field can be very large if the
user is a member of a large group.
We want information about groups a user belongs, but we don't need a
list of every other member of the group, so this field is no longer
populated by default.
Alongside the existing advanced option to request specific group
attributes, there is a new advanced option (off by default) to preserve
the member list.
```
- Closes #12520

[entityanalytics_ad] Remove members from group information by default

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

```
qualys_vmdr: prevent sending requests with an empty 
ids parameter to the Knowledge Base API in the 
asset host detection datastream.
This change adds a check to ensure the request to the
Knowledge Base API is only made when HOST_QID_LIST 
contains at least one ID. Previously, the integration was 
sending requests without checking if the IDs were empty, 
which resulted in an API error.
```
System Tests:
```
--- Test results for package: qualys_vmdr - START ---
╭─────────────┬──────────────────────┬───────────┬───────────┬────────┬─────────────────╮
│ PACKAGE     │ DATA STREAM          │ TEST TYPE │ TEST NAME │ RESULT │    TIME ELAPSED │
├─────────────┼──────────────────────┼───────────┼───────────┼────────┼─────────────────┤
│ qualys_vmdr │ asset_host_detection │ system    │ ahd-kb …
```

qualys_vmdr: prevent sending empty IDs in the knowledge base API request

---

packages/filestream/_dev/build/docs/README.md
packages/filestream/changelog.yml
packages/filestream/data_stream/generic/manifest.yml
packages/filestream/docs/README.md
packages/filestream/manifest.yml

This commit adds a message at the beginning of the Custom Logs (Filestream) integration warning that only files >= 1024 bytes in size will be ingested and pointing to the documentation to change this behaviour.
Build the package
Deploy the package
Look at the documentation
~~## Related issues~~

[filestream] add warning about only ingesting files >= 1024 bytes

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/falcon/agent/stream/streaming.yml.hbs
packages/crowdstrike/manifest.yml

```
crowdstrike: add support for multi-resource streams
elastic/beats#44548 added support for multi-resource stream. This
updates the CEL program that processes the events provided by the stream
so that it is able to handle the new cursor structure. It is able to
distinguish old agents from the new multi-resource aware agents by the
presence of the feed field in state.
When the agent is upgraded from the old state form to the new form, it is
expected that the integration will recollect the existing data since the
cursors are not compatible with each other.
```
- Fixes #13953
- Relates elastic/beats#44548

crowdstrike: add support for multi-resource streams

---

packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
packages/sentinel_one_cloud_funnel/changelog.yml
packages/sentinel_one_cloud_funnel/data_stream/event/agent/stream/abs.yml.hbs
packages/sentinel_one_cloud_funnel/data_stream/event/manifest.yml
packages/sentinel_one_cloud_funnel/docs/README.md
packages/sentinel_one_cloud_funnel/manifest.yml

```
sentinel_one_cloud_funnel: add support for azure blob storage input.
Previously, azure blob storage input was not supported in the sentinel_one_cloud_funnel event data stream. 
This update adds support for azure blob storage input.
Testing has been performed using log samples available in the test folder, which were accessed via an
azure blob storage container to validate the input functionality.
```
Move to integrations/packages/sentinel_one_cloud_funnel directory.
- Closes https://github.com/elastic/integrations/issues/13945

[sentinel_one_cloud_funnel] Add Support for Azure Blob Storage Input

---

packages/cisco_ios/changelog.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-config.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-expected.json
packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ios/manifest.yml

Cisco IOS logs can have time zone formats up to 7 characters long. This adds matching support for 7-character time zones in the ingest pipeline.
Cisco IOS logs can have time zone formats up to 7 characters long.
This adds matching support for 7-character time zones in the ingest
pipeline.

[cisco_ios] Add support for longer time zone formats

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.16.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/69e91b9ec4c9c96375a3577f7250440987e7625f
None
None

[Security Rules] Update security rules package to v8.16.16

---

packages/abnormal_security/changelog.yml
packages/abnormal_security/data_stream/ai_security_mailbox_not_analyzed/agent/stream/cel.yml.hbs
packages/abnormal_security/data_stream/ai_security_mailbox_not_analyzed/manifest.yml
packages/abnormal_security/manifest.yml

```
abnormal_security: allow configuration of a grace period for ai_security_mailbox_not_analyzed
The "Not Analyzed" data source may have a delayed availability for
messages, with advice from Abnormal Security being that 95% of messages
are ready by 60s, but that a 5-10 minute delay would likely be sufficient
to account for most messages transitioning from "Not Analyzed" to
successfully scanned. Given this range of expectations, provide a
mechanism for the user to tune the agent's response. The default
behaviour is to retain no grace period, the current behaviour.
```
- Fixes #14219

abnormal_security: allow configuration of a grace period for ai_security_mailbox_not_analyzed

---

packages/pad/changelog.yml
packages/pad/kibana/ml_module/pad-ml.json
packages/pad/manifest.yml

- Update ML jobs description and groups for Privileged Access Detection package.
- Updated `changelog.yml` and `manifest.yml`.
- Modified `pad-ml.json`: added group tags to the ML jobs to reflect their respective domains (e.g., Linux, Windows, Okta). Also updated the description for the job `pad_linux_high_median_process_command_line_entropy_by_user`.
-

[pad] Update ML jobs description and groups for Privileged Access Detection

---

packages/ti_eclecticiq/changelog.yml
packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/fields/ecs.yml
packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/transform.yml
packages/ti_eclecticiq/manifest.yml
packages/ti_opencti/changelog.yml
packages/ti_opencti/elasticsearch/transform/latest_ioc/fields/ecs.yml
packages/ti_opencti/elasticsearch/transform/latest_ioc/transform.yml
packages/ti_opencti/manifest.yml
packages/ti_threatconnect/changelog.yml
packages/ti_threatconnect/elasticsearch/transform/latest/fields/ecs.yml
packages/ti_threatconnect/elasticsearch/transform/latest/transform.yml
packages/ti_threatconnect/manifest.yml

```
error.message is undefined in some Threat Intel integrations.
If the field is undefined, the default keyword mapping is applied.
This causes issues when searching on data and also impacts 
custom rules. 
Update error.message field mapping as per ECS inside 
Threat Intel destination indices. The change impacts following 
integrations:
- ti_eclectiqiq
- ti_opencti
- ti_threatconnect
Since the mapping needs to be applied to destination indices, 
the index version suffix is also incremented along with upgrading 
transform's fleet version, only when the transform is updated.
```

{ti_eclectiqiq,ti_opencti,ti_threatconnect}: Update error.message field mapping as per ECS inside Threat Intel destination indices.

---

packages/github/changelog.yml
packages/github/data_stream/security_advisories/manifest.yml
packages/github/manifest.yml
packages/miniflux/changelog.yml
packages/miniflux/data_stream/feed_entry/manifest.yml
packages/miniflux/manifest.yml

Fix minor spelling mistakes

---

packages/box_events/_dev/deploy/docker/files/config.yml
packages/box_events/changelog.yml
packages/box_events/data_stream/events/_dev/test/system/test-httpjson-config.yml
packages/box_events/data_stream/events/agent/stream/httpjson.yml.hbs
packages/box_events/manifest.yml

```
box_events: fix handling of large cursor offsets
When a cursor stream offset is large — at least 1e6, the template renders
the value in e-notation. This is a consequence of the cursor being stored
as JSON and so being contaminated by JS number semantics. Another
threshold exists at 0x1p53 (4.5e15) where we lose exact integer
representation. We do see values as large as 3.0e16, so we are beyond
this value and cannot rely on numeric value representation at all.
This is exacerbated by the fact that the input converts from string to
integer values via float64.
To resolve this, explicitly convert the offset to an integer when
rendering the value into the parameter, and accept that we may either
recollect or miss documents from the API.
```
-

box_events: fix handling of large cursor offsets

---

packages/cisco_ios/changelog.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-kiwi.log
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-kiwi.log-expected.json
packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ios/manifest.yml

- Add support for Kiwi format logs. The Kiwi header is removed and the remaining log is parsed like a normal Cisco IOS log.
The Kiwi Syslog server alters the original Cisco IOS log by inserting a `Original Address=IP` at the beginning of the log, along with an RFC 5424 header.
```
```
- Closes #14293

[cisco_ios] Add support for Kiwi format logs

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/_dev/test/pipeline/test-common-config.yml
packages/o365/data_stream/audit/_dev/test/pipeline/test-numbery-json-events.json
packages/o365/data_stream/audit/_dev/test/pipeline/test-numbery-json-events.json-expected.json
packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/o365/manifest.yml

```
o365: fix handling of file size values
O365 audit file size data may include decimal points and sizes may be
represented with e-notation. These break the convert processor. To work
around this, in the case of strings, non-digit characters were removed
to allow parsing, but this was incorrect since it would add, e.g.
significant zeros. Fix this all by using painless to conditionally
convert/parse the values of the size field and render them in long.
It appears that Microsoft will sometimes send IDs as numeric values so
be more careful when assessing for email-like IDs. Incidentally, also
take more care when checking for port delimiters in IP values.
```
-

o365: fix handling of file size values and numeric IDs

---

packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/data_stream/log/agent/stream/httpjson.yml.hbs
packages/microsoft_defender_endpoint/data_stream/log/manifest.yml
packages/microsoft_defender_endpoint/data_stream/log/sample_event.json
packages/microsoft_defender_endpoint/docs/README.md
packages/microsoft_defender_endpoint/manifest.yml

```
microsoft_defender_endpoint: add configurable initial interval to the log data stream.
Previously, the initial interval was hardcoded to "5m" and not exposed
in the configuration options in log data stream. This update adds it as
a configurable option, with a default value of "5m". It allows users to
define how far back they want to pull data from the API.
```
Move to integrations/packages/microsoft_defender_endpoint directory.
- Closes https://github.com/elastic/integrations/issues/12912

[microsoft_defender_endpoint] Add Initial Interval in Config Options

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/811d66daba417ea98a723e67d08ca5dea0eaf905
None
None

[Security Rules] Update security rules package to v9.0.8

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.1.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/f92147e93669ea6a313d3810207f0c7f5d15298a
None
None

[Security Rules] Update security rules package to v9.1.1

---

packages/cyberark_epm/changelog.yml
packages/cyberark_epm/data_stream/admin_audit/agent/stream/cel.yml.hbs
packages/cyberark_epm/data_stream/aggregated_event/agent/stream/cel.yml.hbs
packages/cyberark_epm/data_stream/policyaudit_aggregated_event/agent/stream/cel.yml.hbs
packages/cyberark_epm/data_stream/policyaudit_raw_event/agent/stream/cel.yml.hbs
packages/cyberark_epm/data_stream/raw_event/agent/stream/cel.yml.hbs
packages/cyberark_epm/manifest.yml

Enhanced error handling in the CEL program to prevent "'no such key: version'" errors by ensuring proper propagation of the state data configuration during failures. This was accomplished by wrapping the programs with `state.with()`.
- 
_Reproducing the problem before the fix by injecting HTTP 500 responses with p=0.8_
After go-retryablehttp exhausts its retries, the failure response is returned to the CEL problem. This results in the next iteration failing due to the missing `state.version`.

fix(cyberark_epm): propagate state variables on error

---

packages/ti_threatconnect/_dev/build/docs/README.md
packages/ti_threatconnect/changelog.yml
packages/ti_threatconnect/docs/README.md
packages/ti_threatconnect/elasticsearch/transform/latest/transform.yml
packages/ti_threatconnect/manifest.yml

```
[ti_threatconnect] Remove outdated version information
The README included out of date advice about the required Kibana and
Elastic Stack version number.
```

[ti_threatconnect] Remove outdated version information

---

packages/ti_custom/_dev/deploy/docker/files/config.yml
packages/ti_custom/changelog.yml
packages/ti_custom/data_stream/indicator/_dev/test/system/test-taxii-token-config.yml
packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_custom/data_stream/indicator/manifest.yml
packages/ti_custom/manifest.yml

ti_custom: add support for alternative token auth types

---

.buildkite/scripts/common.sh

Skip test all packages if files under `.github/workflows/` are updated, deleted or modified.
That folder is already skipped to trigger builds in Pull Requests:
https://github.com/elastic/integrations/blob/da0a9342630eb151a8b734818de0c37d853b67e4/.buildkite/pull-requests.json#L17
Example:
This build https://buildkite.com/elastic/integrations/builds/28159#0197e5e4-3986-41ba-8873-6edeef50ca87 was triggered due to this file was modified but all packages were tested:
`.github/workflows/bump-elastic-stack-version.yml` 
```
$ git diff --name-only 951d4f041634a32de5e513a4d5eeff4073b03e22..7c48a2a906 
.github/workflows/bump-elastic-stack-version.yml
```
This has been tested locally by simulating the files obtained by `git diff` command:
```shell
$ echo -e …
```

[CI] Update regex of files/folders to skip test packages

---

packages/system/changelog.yml
packages/system/kibana/dashboard/system-Metrics-system-overview.json
packages/system/manifest.yml

For "CPU Usage" panels in `[Metrics System] Overview` and `[Metrics System] Host Overview`  the `system.cpu.total.norm.pct` metrics is used. However, in the `[Metrics System] Overview` dashboard, in the panel with "Host", "CPU Usage", "Memory Usage" (see screenshots) the `system.process.cpu.total.norm.pct` metric is used which is `0.00%` most of the time. This PR sets it to `system.cpu.total.norm.pct`.
See title.
With the changes from this PR the CPU Usage is now the same, see screenshot of `[Metrics System] Overview` and `[Metrics System] Host Overview` (highlighted by red rounded rectangles):

[system] fix CPU Usage on [Metrics System] Overview "hosts" tab

---

packages/cloudflare_logpush/changelog.yml
packages/cloudflare_logpush/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/cloudflare_logpush/manifest.yml

```
[cloudflare_logpush] Fix audit data stream null handling
Fix misuse of the Elvis operator that was causing the error:
Cannot invoke "Object.getClass()" because "value" is null
Also add a tag to every processor in the audit data stream and include include
it in the on_failure message. Fix some indentation.
```

[cloudflare_logpush] Fix audit data stream null handling

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/data_stream/audit/manifest.yml
packages/o365/manifest.yml

```
[o365] Stricter enforcement of maximum age limits
In order to avoid requesting data more than 7 days old:
- When calculating the start of the allowed time range, use `now()` (a
function that returns the current time) rather than `now` (which is
the time the current CEL evaluation began), as the latter will become
too old if a singe CEL evaluation runs for more than a few minutes.
- Make the `167h55m`  limit used throughout the CEL expression
configurable, in the advanced settings, so that it can be shortened if
necessary.
This integration's CEL expression is one that may run for a long time.
For each of a list of content types it will register a subscription,
list data and fetch data, and this has been observed to take many
minutes.
```

[o365] Stricter enforcement of maximum age limits

---

packages/aws_logs/_dev/build/docs/README.md
packages/aws_logs/changelog.yml
packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs
packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
packages/aws_logs/data_stream/generic/manifest.yml
packages/aws_logs/docs/README.md
packages/aws_logs/manifest.yml

For some reason the fix was not applied for `aws_logs` package while doing the bulk fix for the `number_of_workers` in the PR: https://github.com/elastic/integrations/pull/13350
See title.
- Closes https://github.com/elastic/integrations/issues/14403
- Relates https://github.com/elastic/integrations/pull/13350
- Relates https://github.com/elastic/integrations/pull/13346

[aws_logs] fix number_of_workers to be always passed in hbs template

---

packages/ti_custom/changelog.yml
packages/ti_custom/kibana/dashboard/ti_custom-e336dd7a-d5cb-4b7f-a6cd-85c45d0bd1ac.json
packages/ti_custom/manifest.yml

Added filter to the Custom Threat Intelligence dashboard so only indicators from destination index (latest transform) are shown, avoiding to display duplicated indicators.

Custom TI: add filter for transform's destination index in dashboard

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
[o365] No delays until up-to-date
Instead of fetching history continuously until reaching the current day
then waiting the interval time between requests, keep fetching until
within one batch length of the current time.
With the default settings, waiting 3 minutes between requests for one
hour batches would significantly extend the time required to get
up-to-date. For example, it's 45 minutes of waiting to cover 15 hours.
It's particularly disruptive to the user experience if there is no
historical data and new data has such a delay.
```

[o365] No delays until up-to-date

---

packages/security_ai_prompts/changelog.yml
packages/security_ai_prompts/manifest.yml

Moves Security AI Prompts package out of prerelease, version `1.0.0`

[Security AI Prompts] First major release

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/vulnerability/agent/stream/cel.yml.hbs
packages/m365_defender/manifest.yml

Enhanced error handling in the CEL program to prevent "no such key: product_batch_size'" errors by ensuring proper propagation of the state data configuration during failures. This was accomplished by wrapping the objects returned from errors with state.with()

fix(m365_defender): propagate state variables on error

---

packages/cisco_ftd/changelog.yml
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-endpoint-profile.log-expected.json
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-config.yml
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-expected.json
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log-expected.json
packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ftd/manifest.yml

- Ensure Ingress and Egress zone values are set to proper ECS fields
- This will also allow the network.direction logic to work as intended
```
cd packages/cisco_ftd
```
Note: in order for network.direction to be set properly, the integration needs to be configured with `internal_zones` and `external_zones` that match zone names that are seen in the log.
- Closes #14749

[cisco_ftd] Ensure observer zone fields are set

---

packages/fireeye/changelog.yml
packages/fireeye/data_stream/nx/_dev/test/pipeline/test-nx.log-expected.json
packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/default.yml
packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/renaming-raws.yml
packages/fireeye/data_stream/nx/fields/fields.yml
packages/fireeye/data_stream/nx/sample_event.json
packages/fireeye/docs/README.md
packages/fireeye/manifest.yml

```
fireeye: add missing ECS fields
This PR has added the missing ECS fields like event, file, IP related fields, etc.
```
- Move to integrations/packages/fireeye directory.
- Closes #13756

[FireEye] Add missing ECS fields

---

.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml

Update [Buildkite junit-annotate plugin](https://github.com/buildkite-plugins/junit-annotate-buildkite-plugin) up to version 2.7.0
Set `run-in-docker: false` to use the ruby from the agent.

[CI] Update junit buildkite plugin

---

packages/netskope/changelog.yml
packages/netskope/data_stream/events_v2/_dev/test/pipeline/test-events.log-expected.json
packages/netskope/data_stream/events_v2/elasticsearch/ingest_pipeline/default.yml
packages/netskope/manifest.yml

```
netskope: fix ingest pipeline processors for the wrongly mapped fields
```
- Move to integrations/packages/netskope directory.
- Relates #14527

[Netskope Events v2] Fix typos in ingest pipeline

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/f5b8848253803b23941f32c4a4ba58973b5569be
None
None

[Security Rules] Update security rules package to v8.18.10

---

packages/aws/_dev/build/docs/cloudwatch.md
packages/aws/docs/cloudwatch.md

This PR:
- Adds detailed instructions on how to opt into specific metrics
- Improves link formatting
- Slightly reorganizes the **Advanced options** subsections
Relates to https://github.com/elastic/integration-docs/issues/813

[DOCS] Add instructions to collect AWS CloudWatch specific metrics

---

packages/system_otel/changelog.yml
packages/system_otel/manifest.yml

Added `discovery.datasets` field to enable auto-install of content package when data is ingested with dataset `hostmetricsreceiver`.
- Relates https://github.com/elastic/package-spec/issues/919

Add discovery datasets field to system_otel

---

packages/wiz/changelog.yml
packages/wiz/data_stream/vulnerability/agent/stream/cel.yml.hbs
packages/wiz/data_stream/vulnerability/manifest.yml
packages/wiz/manifest.yml

```
wiz: add filters to retrieve all types of vulnerabilities in the vulnerability dataset
This change introduces filters to the vulnerability dataset, allowing
retrieval of all types of vulnerabilities. It enhances the dataset's
flexibility by ensuring comprehensive coverage across different
vulnerability categories.
```
- Move to integrations/packages/wiz directory.
- Closes https://github.com/elastic/integrations/issues/14437

[wiz] Add Filters to Retrieve all Types of Vulnerabilities

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a30e86eadfe8962ef6acae6a9e42aa35cd5b35c5
None
None

[Security Rules] Update security rules package to v9.0.11

---

packages/o365/_dev/deploy/docker/config.yml
packages/o365/changelog.yml
packages/o365/data_stream/audit/_dev/test/system/test-cel-bad-creds-config.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
[o365] Surface credential or subscription errors in Fleet status
Instead of ignoring errors and returning successes, if there are any
errors while creating/checking subscriptions, return an error showing
the problem, wait the interval time, and repeat everything next time.
This is intended to avoid silencing errors such as AF10001 "The
permission set () sent in the request does not include the expected
permission.".
```
The `changelog.yml` entry assumes https://github.com/elastic/integrations/pull/14730 will be merged first.
In the system test `data_stream/audit/_dev/test/system/test-cel-bad-creds-config.yml`, comment out the skip, run it with `--defer-cleanup 10m` and inspect the error document produced.
- Related https://github.com/elastic/elastic-package/issues/2800

[o365] Surface credential or subscription errors in Fleet status

---

packages/sql_input/changelog.yml

According to the procedure https://www.elastic.co/docs/extend/integrations/developer-workflow-support-old-package, adding a version 0.6.1 to the changelog introduced in the following PR: https://github.com/elastic/integrations/pull/14815
- Requires https://github.com/elastic/integrations/pull/14815

[sql_input] add v0.6.1 to changelog (backported)

---

.buildkite/scripts/common.sh
dev/testsreporter/_static/summary.tmpl
dev/testsreporter/format_test.go

Fix the description written in the issues created by the daily CI builds in case of Serverless builds.
It was set `Stack version: Same as in Pull Request builds` but this is not true for builds testing packages with a Serverless project.
- Relates https://github.com/elastic/integrations/issues/14873

[CI] Fix description written for failed tests in Serverless

---

packages/o365/_dev/deploy/docker/config.yml
packages/o365/_dev/deploy/docker/docker-compose.yml
packages/o365/changelog.yml
packages/o365/data_stream/audit/_dev/test/system/test-grant-type-refresh-token-config.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/data_stream/audit/manifest.yml
packages/o365/manifest.yml

Added configurable `oauth_endpoint_params` for greater flexibility.  An
example use case is to allow overriding the default grant_type to
support using providing a static refresh_token.
> [!NOTE]  
> The above configuration treats the `refresh_token` as static configuration. If the server returns a new `refresh_token` it a response the oauth client will not use it.
-----
Request tracer log showing the oauth request.
```json
{
"log.level": "debug",
"@timestamp": "2025-08-13T18:42:20.704Z",
"message": "HTTP request",
"transaction.id": "JLSRFNTSCTDHG-1",
"url.original": "http://svc-o365-cel:8080/test-grant-type-refresh-token-client-id/oauth2/v2.0/token",
"url.scheme": "http",
"url.path": "/test-grant-type-refresh-token-client-id/oauth2/v2.0/token",
"url.domain": "svc-o365-cel",
"url.port": …
```

feat(o365): add support for configurable oauth2 endpoint params

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
o365: reduce code complexity, repeated work and garbage generation
This is the first step in making the integration safer to use in a
memory-constrained setting. The current code does the full set of
requests for each element of a set of subscription results, causing a
heavy memory load. The intention is to make use of work lists to reduce
the individual evaluation memory load when the CEL program is running.
The existing code is relatively over-complex, so this reduces that
complexity, while replacing heavily allocating operations with lighter
calls, and omitting completely calls that are not required, and so
eliding the allocation that those calls fruitlessly make.
Rather than making this change a commit in a pull request to convert to
work lists, this optimised version is made a …
```

o365: reduce code complexity, repeated work and garbage generation

---

packages/aws/changelog.yml
packages/aws/data_stream/config/_dev/deploy/docker/files/config.yml
packages/aws/data_stream/config/agent/stream/cel.yml.hbs
packages/aws/data_stream/config/elasticsearch/ingest_pipeline/default.yml
packages/aws/manifest.yml

```
fix(aws.config): handle empty DescribeConfigRules responses
This change addresses issues discovered during testing of the AWS Config
integration CEL program. The program was failing to handle empty ConfigRules
responses properly, which could occur when AWS Config has no rules configured
in a region. The failures resulted in 'index out of bounds: 0' errors.
The fix ensures that empty ConfigRules lists are handled gracefully without
causing program failures.
The error.message values now accurately reflect the URL path and include the
specific AWS Config API call being made (DescribeConfigRules vs
GetComplianceDetailsByConfigRule).
State management has been improved to consistently preserve the URL value
across all execution paths, preventing debug warnings about missing state
values. …
```

fix(aws.config): handle empty DescribeConfigRules responses

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/120da01c8d7380634797e7dc6319eb3ef4c8d827
None
None

[Security Rules] Update security rules package to v8.18.12

---

packages/beyondinsight_password_safe/changelog.yml
packages/beyondinsight_password_safe/data_stream/managedaccount/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/managedsystem/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/session/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/manifest.yml

```
fix(beyondinsight_password_safe): remove cookies on auth failure
When authentication fails with 401, remove the explicit 'cookies: null' assignment
and use an empty cursor object instead. This allows the orValue() fallback logic
to work properly by checking for key existence rather than null values.
Otherwise the cookie value would never be refreshed, leading to persistent auth
failures.
Fixes: #14985
```
[beyondinsight_password_safe-0.5.1.zip](https://github.com/user-attachments/files/21868782/beyondinsight_password_safe-0.5.1.zip)
- Fixes: #14985

fix(beyondinsight_password_safe): remove cookies on auth failure

---

packages/windows/changelog.yml
packages/windows/data_stream/windows_defender/elasticsearch/ingest_pipeline/default.yml
packages/windows/manifest.yml

Only try to extract extension when there is a dot in the file name in defender data stream.

[windows] Only try to extract extension when there is a dot in the file name in defender data stream.

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/manifest.yml

```
crowdstrike: Implemented a conditional JSON parsing workaround for `ResourceAttributes` to
handle cases where custom rules convert the object into a JSON string, ensuring consistent
ingestion of documents.
```
- Move to integrations/packages/crowdstrike directory.

[crowdstrike] Added a conditional JSON parsing workaround for ResourceAttributes

---

packages/symantec_endpoint_security/changelog.yml
packages/symantec_endpoint_security/data_stream/incident/agent/stream/cel.yml.hbs
packages/symantec_endpoint_security/manifest.yml

```
[symantec_endpoint_security] Fix loss of state in error case
Failure to propagate the state in the error case was causing failures
such as:
failed eval: ERROR: :21:50: no such key: limit
Fixed by wrapping in `state.with(...)`. Also ran celfmt.
```
Review the diff with whitespace changes off to avoid noise from the `celfmt` reformatting.

[symantec_endpoint_security] Fix loss of state in error case

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.19.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/0a1af011524bdc7c6d16d7cdb1cec2454291d6df
None
None

[Security Rules] Update security rules package to v8.19.6

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/555120131f0b4767b400bd6432801ecce0b9596c
None
None

[Security Rules] Update security rules package to v8.18.13

---

packages/ti_opencti/changelog.yml
packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-x509-certificate.json
packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-x509-certificate.json-expected.json
packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
packages/ti_opencti/manifest.yml

```
In current pipeline, the empty strings inside raw data 
can create several malformed fields which are indexed 
into transform source indices due to the default setting: 
"index.mapping.ignore_malformed: true".
Since this setting is "false" inside transform's destination 
indices, the transform fails during index operation.
This PR adds script processor to remove null and 
empty strings inside raw data and not ingest them into 
the source indices avoiding malformed data at source.
PR[1] has the fix for setting the default 
"index.mapping.ignore_malformed: true"
inside transform's destination indices as well.
[1]: https://github.com/elastic/kibana/pull/232439
```
Added sample data with empty strings.
Run pipeline tests:
**Current Behaviour:**
```
--- Test results for package: ti_opencti …
```

ti_opencti: Add script processor to drop all nulls / empty strings.

---

.buildkite/pull-requests.json

Avoid triggering Buildkite builds if the only file updated is `CODE_OF_CONDUCT.md` in a given pull request.
- Follows #15072

[CI] Add exception for CODE_OF_CONDUCT.md file

---

packages/dga/changelog.yml
packages/dga/docs/README.md
packages/dga/manifest.yml

Corrects a typo in the readme pointing to the wrong datastream
- ~[ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices)~
Tested with elastic-package

[DGA] Correct Readme typo

---

packages/azure/_dev/build/docs/events.md
packages/azure/changelog.yml
packages/azure/docs/events.md
packages/azure/manifest.yml

Add a FAQ section to the Azure Logs integration v2 preview to clarify the integration functionality and future plans.
We've been getting similar questions from multiple users, so this FAQ should help address common concerns and provide clarity for everyone.

docs: add FAQ section for Azure Logs integration v2 preview

---

packages/amazon_security_lake/changelog.yml
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-findings.log-expected.json
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-iam.log-expected.json
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-resources-data.log
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-resources-data.log-expected.json
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-unmapped.log
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-unmapped.log-expected.json
packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/pipeline_resources_data_json.yml
packages/amazon_security_lake/manifest.yml

```
[amazon_security_lake] Parse JSON in `ocsf.resources.data`, `ocsf.unmapped`
In case these fields are JSON strings rather than objects, parse them so
that they can be indexed as flattened.
```
- Relates #14323

[amazon_security_lake] Parse JSON in `ocsf.resources.data`, `ocsf.unmapped`

---

packages/snyk/changelog.yml
packages/snyk/data_stream/audit_logs/agent/stream/cel.yml.hbs
packages/snyk/data_stream/issues/agent/stream/cel.yml.hbs
packages/snyk/data_stream/issues/elasticsearch/ingest_pipeline/default.yml
packages/snyk/data_stream/issues/manifest.yml
packages/snyk/manifest.yml

```
snyk: fix parameter handling and allow issue update ingestion
The previous implementation of the issues data stream did not correctly
handle request parameters; type and scan_item.id are not multiple value
parameters[1], and effective_severity_level and status use a comma
separated element syntax[2]. scan_item.id and scan_item.type are
corequisites[2] so this is documented in the configuration UI to avoid
confusion.
The previous design of the data stream intentionally only collected the
first seen occurrence of an issue, this behaviour has been changed so
that all updates are collected.
The stack version is updated to allow for deletion of old request trace logs.
[1]https://docs.snyk.io/snyk-api/reference/issues#get-orgs-org_id-issues
[2]experimentally determined
```
> [!NOTE]
> …

snyk: fix parameter handling and allow issue update ingestion

---

packages/o365/_dev/deploy/docker/config.yml
packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
o365: tolerate changed API next page URI behaviour
The API now returns the next page URI with the parameters lowercased.
This is not documented[1], so retain support for the document behaviour.
[1]https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference
```
-

o365: tolerate changed API next page URI behaviour

---

packages/wiz/changelog.yml
packages/wiz/data_stream/defend/_dev/test/pipeline/test-defend.json-expected.json
packages/wiz/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability.log-expected.json
packages/wiz/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
packages/wiz/data_stream/vulnerability/fields/fields.yml
packages/wiz/data_stream/vulnerability/sample_event.json
packages/wiz/docs/README.md
packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml
packages/wiz/manifest.yml

This PR sets the vulnerability.title field by constructing a title using prefix and the vulnerability.id field if available. This is an alignment to other 3p integrations which already set this field during the ingest phase.
1. build package with elastic-package build
2. set all necessary env variables to install the integration in your ess/serverless env
3. run elastic-package install
4. go to findings -> vulnerabilities tab - findings should appear with vulnerability.title field set.
https://github.com/elastic/security-team/issues/12863

[Cloud Security] update wiz ingest pipeline to set vulnerability.title field

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/data_stream/status_change_logs/elasticsearch/ilm/default_policy.json
packages/elastic_agent/data_stream/status_change_logs/lifecycle.yml
packages/elastic_agent/data_stream/status_change_logs/manifest.yml
packages/elastic_agent/manifest.yml

Resolves: https://github.com/elastic/ingest-dev/issues/5692
This adds a 90 day data retention limit for the `elastic_agent.status_change` data stream. 
Prior to this change, this data stream did not have a retention limit set. Kibana has a task that writes to this `elastic_agent.status_change` every minute only if there is a change in status. 
The primary use case for this data is for setting up alert rule monitoring of elastic agents. 90 days would allow users to analyze trends with status changes that may occur with an agent over the span of weeks or months. This also aligns with similar retention of our per 1m metric default policies for APM: https://www.elastic.co/docs/solutions/observability/apm/index-lifecycle-management.
- Closes: https://github.com/elastic/ingest-dev/issues/5692

Add data retention for elastic agent status_change_logs data stream

---

packages/auth0/_dev/deploy/docker/docker-compose.yml
packages/bbot/_dev/deploy/docker/docker-compose.yml
packages/beelzebub/_dev/deploy/docker/docker-compose.yml
packages/bitdefender/_dev/deploy/docker/docker-compose.yml
packages/carbonblack_edr/_dev/deploy/docker/docker-compose.yml
packages/cisco_meraki/_dev/deploy/docker/docker-compose.yml
packages/cloudflare_logpush/_dev/deploy/docker/docker-compose.yml
packages/f5_bigip/_dev/deploy/docker/docker-compose.yml
packages/gigamon/_dev/deploy/docker/docker-compose.yml
packages/http_endpoint/_dev/deploy/docker/docker-compose.yml
packages/jamf_compliance_reporter/_dev/deploy/docker/docker-compose.yml
packages/jamf_pro/_dev/deploy/docker/docker-compose.yml
packages/jamf_protect/_dev/deploy/docker/docker-compose.yml
packages/opencanary/_dev/deploy/docker/docker-compose.yml
packages/ping_one/_dev/deploy/docker/docker-compose.yml
packages/sysdig/_dev/deploy/docker/docker-compose.yml
packages/tanium/_dev/deploy/docker/docker-compose.yml
packages/ti_anomali/_dev/deploy/docker/docker-compose.yml
packages/wiz/_dev/deploy/docker/docker-compose.yml
packages/zoom/_dev/deploy/docker/docker-compose.yml
packages/zscaler_zia/_dev/deploy/docker/docker-compose.yml

```
fix: disable webhook probe for http_endpoint inputs
The elastic/stream webhook output probes the endpoint with HEAD requests
to see if it is ready. This triggers the input to become unhealthy
because the request does not validate. This change disables the HEAD
probe. It's not really needed because elastic-package sends a SIGHUP
after the integration is running to trigger the webhook callbacks to
begin.
This fixes the following error:
> (HEALTHY->DEGRADED): request did not validate: only POST requests are allowed"
I considered changing it to STREAM_WEBHOOK_PROBE=POST, but that fails with a different
validation:
> (HEALTHY->DEGRADED): request did not validate: wrong Content-Type header, expecting application/json"
Related: #14022
```
- Relates #14022
- …

fix(system tests): disable webhook probe for http_endpoint inputs

---

.buildkite/pipeline.yml
.buildkite/scripts/check_sources.sh
.buildkite/scripts/common.sh
go.mod
go.sum
magefile.go
tools.go

Ensure that test dependencies used in CI will not fail due to a mismatch of required Golang versions.
Related failure seen in backport branches:
```
Setting up the Go environment...
GVM v0.5.2 (platform linux arch amd64
go version go1.23.4 linux/amd64
/root/.gvm/versions/go1.23.4.linux.amd64/bin/go
go: downloading github.com/magefile/mage v1.15.0
go: downloading github.com/jstemmer/go-junit-report v1.0.0
go: downloading gotest.tools/gotestsum v1.13.0
go: downloading gotest.tools v2.2.0+incompatible
go: gotest.tools/gotestsum@latest: gotest.tools/gotestsum@v1.13.0 requires go >= 1.24.0 (running go 1.23.4; GOTOOLCHAIN=local)
🚨 Error: The command exited with status 1
```
Examples of builds failing:
- https://buildkite.com/elastic/integrations/builds/31461#01995328-df87-4570-93eb-e7da7bdbe102 …

[CI] Move test dependencies to tools.go

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml
packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Add the cloud_connector_id field to the CSPM and Cloud Asset Inventory packages for Azure cloud connectors.
- relates https://github.com/elastic/security-team/issues/12603

[Cloud Security] Add elastic connector id to azure

---

packages/auth0/_dev/deploy/docker/docker-compose.yml

Follow up to #15355 where I missed a version update. STREAM_WEBHOOK_PROBE is only honored on >= 0.19.0 so this change is needed to fix the "only POST requests are allowed" DEGRADED agent status.
- Relates #15355
- https://buildkite.com/elastic/integrations/builds/31509

fix(auth0): use elastic/stream v0.20.0

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.19.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/077688d082a3314bd53cd225518fc9ccb2a2e926
None
None

[Security Rules] Update security rules package to v8.19.7

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/633354674318a34014305d257e3626f70378a994
None
None

[Security Rules] Update security rules package to v9.0.14

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
o365: fix handling of error conditions when requesting work continuation
CEL type(o.f) == T does not work the same way as painless o.f instanceof T
if f is not in o. It is necessary to check for existence first.
In this case, this can be done either by directly checking for the existence
of events in state, or because of an invariant in the program, by the absence
of error in state. The latter is chosen for clarity and to ensure that the
invariant is kept.
```
-

o365: fix handling of error conditions when requesting work continuation

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/alert/agent/stream/httpjson.yml.hbs
packages/m365_defender/data_stream/incident/agent/stream/httpjson.yml.hbs
packages/m365_defender/data_stream/vulnerability/agent/stream/cel.yml.hbs
packages/m365_defender/manifest.yml

```
m365_defender: ensure $skip parameter is correctly formatted
The values used to populate this parameter can be greater than the
cutover to e-notation for doubles, so convert to int before converting
to string.
```
-

m365_defender: ensure $skip parameter is correctly formatted

---

packages/tenable_sc/_dev/build/docs/README.md
packages/tenable_sc/changelog.yml
packages/tenable_sc/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
packages/tenable_sc/data_stream/plugin/elasticsearch/ingest_pipeline/default.yml
packages/tenable_sc/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
packages/tenable_sc/docs/README.md
packages/tenable_sc/manifest.yml

```
tenable_sc: add agentless deployment
```
- Install the elastic package locally.
- Start the elastic stack using the elastic package.
- Move to integrations/packages/tenable_sc directory.
- Closes #15330
**Note**: These changes are not tested on serverless project.

[Tenable SC] Add agentless deployment

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
o365: fix error propagation within cel program
The logic for handling error propagation from failed subscriptions
requests was incorrect. The downstream logic was expecting to find the
error in the root of state, but the subscription request block was
leaving it in the work object.
Later error handling was incorrectly leaving any error state in the root
of state, when it should have been placed under events.
In the case that a subscription has failed, there may not be an entry in
the last_for list for the subscription, resulting in a look-up failure
during assessment for completion of the hour-window steps.
Finally, the postamble logic was brittle to failed requests, assuming
that the todo_type and todo_content list would be present, which is not
necessarily the case when a …
```

o365: fix error propagation within cel program

---

packages/syslog_router/changelog.yml
packages/syslog_router/data_stream/log/manifest.yml
packages/syslog_router/manifest.yml

Add support for Cisco IOS messages. Matches on the Cisco Emblem header in the log, and by default matches after Cisco ASA and FTD to avoid ambiguity.
1. Install assets for Cisco ASA, Cisco FTD, and Cisco IOS
2. Configure the Syslog Router integration (no changes necessary to routing configs).
3. Send Cisco ASA, FTD, and IOS logs to agent running integration
4. Verify that logs have landed in the correct data streams
I manually verified that logs were routed to the correct data streams.
- Closes #15337

[syslog_router] Support Cisco IOS

---

packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/data_stream/vulnerability/agent/stream/cel.yml.hbs
packages/microsoft_defender_endpoint/manifest.yml

```
microsoft_defender_endpoint: ensure $skip parameter is correctly formatted
The values used to populate this parameter can be greater than the
cutover to e-notation for doubles, so convert to int before converting
to string.
Fix is similar to #15392 as it the same API and CEL program.
```

microsoft_defender_endpoint: ensure $skip parameter is correctly formatted

---

packages/panw/_dev/build/docs/README.md
packages/panw/changelog.yml
packages/panw/docs/README.md
packages/panw/manifest.yml

This PR fixes a broken link on the https://www.elastic.co/docs/reference/integrations/panw page.
Fixes https://github.com/elastic/docs-content/issues/3232

[PANW] Fix broken link

---

packages/haproxy/_dev/build/docs/README.md
packages/haproxy/changelog.yml
packages/haproxy/docs/README.md
packages/haproxy/manifest.yml

This PR:
- adds missing information about metricsets that can be collected from HAProxy
- suggests some edits
Closes https://github.com/elastic/docs-content/issues/3204.

Add missing information on the HAProxy Integration documentation

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/498015de5e2141dea492bb550768e93a82fe0533
None
None

[Security Rules] Update security rules package to v8.18.15

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/1d1ba597059efc8fd5fdbfceb95cb143f855f394
None
None

[Security Rules] Update security rules package to v9.0.15
