elastic/integrations

- packages/aws/_dev/build/docs/rds.md
> Update RDS - First draft of AWS integration edits

- packages/aws/_dev/build/docs/lambda.md
> Update Lambda - first draft of AWS integration edits

- packages/pfsense/changelog.yml
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-opensense.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-bsd.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-dhcp.log
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-dhcp.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-haproxy.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-ipsec.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-openvpn.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-squid.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-syslog.log-expected.json
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-unbound.log-expected.json
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/dhcp.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/firewall.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/haproxy.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/ipsec.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/openvpn.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/php-fpm.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/squid.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/unbound.yml
- packages/pfsense/data_stream/log/fields/ecs.yml
- packages/pfsense/data_stream/log/fields/fields.yml
- packages/pfsense/docs/README.md
- packages/pfsense/manifest.yml
> [PFsense] Enhance PFsense Integration with DHCPv6 support

- packages/ti_threatq/_dev/build/build.yml
- packages/ti_threatq/changelog.yml
- packages/ti_threatq/data_stream/threat/_dev/test/pipeline/test-threatq-sample-ndjson.log-expected.json
- packages/ti_threatq/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/ti_threatq/data_stream/threat/sample_event.json
- packages/ti_threatq/docs/README.md
- packages/ti_threatq/manifest.yml
Update ti_threatq to ECS 8.4.0
Closes #3889
> [ti_threatq] Update ECS to 8.4.0

- packages/system/changelog.yml
- packages/system/data_stream/security/_dev/test/pipeline/test-4674.json
- packages/system/data_stream/security/_dev/test/pipeline/test-4674.json-expected.json
- packages/system/data_stream/security/_dev/test/pipeline/test-security-windows2016-4738-account-changed.json-expected.json
- packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml
- packages/system/data_stream/security/fields/winlog.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
This fixes cases where NewUacValue and UserAccountControl are set to the
blank value ("-") in 4738 and 4742, and cases in 4674 where there is
more than one access mask value.
- Fixes #3898
> system/security: fix handling of events 4674, 4738 and 4742

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/fields.yml
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
This adds handling of authentication fields for Cisco ASA AAA message types.
- Updates elastic/beats#32257
- Closes #3852
> cisco_asa: add handling of AAA operations

- LICENSE.txt
Change license text from Elastic License v1 to Elastic License v2, that is the current text used by most if not all Elastic products.
Elastic License v1 is [not currently supported by the package spec](https://github.com/elastic/package-spec/blob/cf00245987ddfa9a9688e37294d23c3c268f5cc4/versions/1/integration/manifest.spec.yml#L147).
- Relates https://github.com/elastic/package-spec/issues/298.
> Change text from Elastic License v1 to Elastic License v2

- packages/awsfargate/_dev/build/docs/README.md
- packages/awsfargate/changelog.yml
- packages/awsfargate/docs/README.md
- packages/awsfargate/manifest.yml
This change adds more details about running the agent as a sidecar container to deploy the integration in an ECS cluster.
Feedback from the support team proved that the current version of the docs is inadequate to explain how and why to deploy the Elastic Agent as a sidecar container in the task definition.
> [AWS Fargate] Clarify how to run the agent as sidecar container

- packages/jamf_compliance_reporter/_dev/build/docs/README.md
- packages/jamf_compliance_reporter/changelog.yml
- packages/jamf_compliance_reporter/docs/README.md
- packages/jamf_compliance_reporter/manifest.yml
Updates the Jamf Compliance Reporter integration docs to align with the documentation guidelines established in https://github.com/elastic/integrations/pull/3433.  
- https://github.com/elastic/integrations/pull/3433.
> [docs] Update Jamf docs to align with docs guidelines

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/log/fields/ecs.yml
- packages/cisco_meraki/docs/README.md
- packages/cisco_meraki/manifest.yml
Fix `client.geo.location` mapping from object to geo_point.
- Closes #3938
> [Cisco Meraki] Fix client.geo.location mapping

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/kibana/csp_rule_template/dc91f4c4-4f0e-59ba-a0e1-96e996736787.json
- packages/cloud_security_posture/manifest.yml
Fixes https://github.com/elastic/cloudbeat/issues/227
Fix a typo in a CSP rule id
-
> Remove comma from rule id

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/manifest.yml
Upgrade osquery fields to match osquery 5.4.0 schema changes
- Closes https://github.com/elastic/security-team/issues/4191
> Osquery_manager: Upgrade osquery fields to match osquery 5.4.0 schema changes

- packages/sentinel_one/_dev/build/build.yml
- packages/sentinel_one/changelog.yml
- packages/sentinel_one/data_stream/activity/_dev/test/pipeline/test-pipeline-activity.log-expected.json
- packages/sentinel_one/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/activity/sample_event.json
- packages/sentinel_one/data_stream/agent/_dev/test/pipeline/test-pipeline-agent.log-expected.json
- packages/sentinel_one/data_stream/agent/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/agent/sample_event.json
- packages/sentinel_one/data_stream/alert/_dev/test/pipeline/test-pipeline-alert.log-expected.json
- packages/sentinel_one/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/alert/sample_event.json
- packages/sentinel_one/data_stream/group/_dev/test/pipeline/test-pipeline-group.log-expected.json
- packages/sentinel_one/data_stream/group/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/group/sample_event.json
- packages/sentinel_one/data_stream/threat/_dev/test/pipeline/test-pipeline-threat.log-expected.json
- packages/sentinel_one/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/threat/sample_event.json
- packages/sentinel_one/docs/README.md
- packages/sentinel_one/manifest.yml
Update sentinel_one to ECS 8.4.0
Closes #3887
> [sentinel_one] Update ECS to 8.4.0

- packages/ti_anomali/_dev/build/build.yml
- packages/ti_anomali/changelog.yml
- packages/ti_anomali/data_stream/limo/_dev/test/pipeline/test-anomali-limo-ndjson.log-expected.json
- packages/ti_anomali/data_stream/limo/elasticsearch/ingest_pipeline/default.yml
- packages/ti_anomali/data_stream/limo/sample_event.json
- packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json-expected.json
- packages/ti_anomali/data_stream/threatstream/elasticsearch/ingest_pipeline/default.yml
- packages/ti_anomali/data_stream/threatstream/sample_event.json
- packages/ti_anomali/docs/README.md
- packages/ti_anomali/manifest.yml
- Update ti_anomali to ECS 8.4.0
Closes #3888
> [ti_anomali] Update ECS to 8.4.0

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
Fixes grok handling of a variety of non-canonical log formats.
- Fixes #3942
> cisco_asa: relax some grok rules for divergent logs

- packages/pfsense/changelog.yml
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/dhcp.yml
- packages/pfsense/manifest.yml
Fix redundant Grok Pattern that causes "warning" messages in Elasticsearch logs.
- Closes #3955
> [PFsense] Fix Redundant Grok pattern

- packages/couchbase/changelog.yml
- packages/couchbase/data_stream/bucket/_dev/test/system/test-default-config.yml
- packages/couchbase/data_stream/bucket/manifest.yml
- packages/couchbase/manifest.yml
- Enhancement
Change `host` parameter from data stream specific manifest  to integration specific manifest.
For Couchbase, there can be multiple data streams for which we currently have a `host` inside the manifest (data stream specific), but it seems easier in terms of user experience to have the `host` field inside the main manifest (integration specific). Hence, the end-user won't have to enter the same host multiple times for multiple data streams.
- Move to integrations/packages/couchbase directory.
> [Couchbase] Update manifest file for bucket data stream

- packages/apache_spark/changelog.yml
- packages/apache_spark/data_stream/executor/fields/fields.yml
- packages/apache_spark/docs/README.md
- packages/apache_spark/manifest.yml
- Bug
This PR contains a minor cleanup for Apache Spark integration. It removes the 3 fields which were present in **fields.yml** but not in **stream.yml.hbs**, and hence were not getting collected. The fields were not supposed to be collected as a part of the integration as per the PRD (https://github.com/elastic/integrations/issues/493), as all of them are histogram metrics (Reference: https://spark.apache.org/docs/3.2.0/monitoring.html). The changes which are made do not affect the existing functionality of the integration at all and are just a cleanup to the integration.
> Spark provides the following types of metrics - Gauge, Counter, Histogram, Meter, Timer. The most common types of metrics used in Spark instrumentation are gauges and counters. Hence, we will support only Gauge and …
> [apache_spark] Update integration package to remove unnecessary fields

- packages/gcp/changelog.yml
- packages/gcp/data_stream/loadbalancing_metrics/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/loadbalancing_metrics/fields/base-fields.yml
- packages/gcp/data_stream/loadbalancing_metrics/manifest.yml
- packages/gcp/data_stream/loadbalancing_metrics/sample_event.json
- packages/gcp/docs/loadbalancing.md
This PR adds some fixes for issues that slipped through the review of the `loadbalancing_metrics` datastream:
- fix `credentials_json` escaping
- set period default to 60s
- fix event.dataset
-
> Fixes to `loadbalancing_metrics` datastream

- packages/windows/changelog.yml
- packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
- packages/windows/manifest.yml
Adds `field` to translate_sid processor in powershell operational datastream.  Without the required `field` events can not be processed
- Closes #3988
> [windows] add field to translate_sid processor in powershell operational

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
- https://github.com/elastic/integrations/pull/3964
-
> KSPM integration version bump

- packages/proofpoint_tap/_dev/build/docs/README.md
- packages/proofpoint_tap/changelog.yml
- packages/proofpoint_tap/docs/README.md
- packages/proofpoint_tap/manifest.yml
This adds a note to explain the semantics of `{source,destination}.ip` for the click datasets. The meaning of these fields in this context have caused confusion for some users.
> proofpoint_tap: clarify use of {source,destination}.ip

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
- Bug
This PR adjusts the monitor ids to account for custom ids from project monitors.
This PR also ads `playwright_options`. Playwright options were added to monitor management to account for project monitors, but since it's not available as an option in the UI, it was never added to the synthetics integration config. This caused playwright_options config to be missing for project monitors with private locations.
> synthetics - adjust configuration to account for project monitor ids

- packages/fortinet/_dev/build/docs/README.md
- packages/fortinet/changelog.yml
- packages/fortinet/docs/README.md
- packages/fortinet/manifest.yml
- packages/fortinet_forticlient/changelog.yml
- packages/fortinet_forticlient/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
- packages/fortinet_forticlient/data_stream/log/agent/stream/log.yml.hbs
- packages/fortinet_forticlient/data_stream/log/agent/stream/tcp.yml.hbs
- packages/fortinet_forticlient/data_stream/log/agent/stream/udp.yml.hbs
- packages/fortinet_forticlient/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/fortinet_forticlient/manifest.yml
- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/manifest.yml
- packages/fortinet_fortimail/changelog.yml
- packages/fortinet_fortimail/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
- packages/fortinet_fortimail/data_stream/log/agent/stream/log.yml.hbs
- packages/fortinet_fortimail/data_stream/log/agent/stream/tcp.yml.hbs
- packages/fortinet_fortimail/data_stream/log/agent/stream/udp.yml.hbs
- packages/fortinet_fortimail/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/fortinet_fortimail/manifest.yml
- packages/fortinet_fortimanager/changelog.yml
- packages/fortinet_fortimanager/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
- packages/fortinet_fortimanager/data_stream/log/agent/stream/log.yml.hbs
- packages/fortinet_fortimanager/data_stream/log/agent/stream/tcp.yml.hbs
- packages/fortinet_fortimanager/data_stream/log/agent/stream/udp.yml.hbs
- packages/fortinet_fortimanager/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/fortinet_fortimanager/manifest.yml
- Deprecate original Fortinet integration
- Swap the logfile legacy input for the filestream input
-
> [Fortinet] Deprecate original integration & change logfile to filestream

- packages/gcp/changelog.yml
Fix the PR links in changelog added with PR https://github.com/elastic/integrations/pull/3986
> Fix links for gcp 2.5.0 changelog

- docs/developer_workflow_design_build_test_integration.md
CI builds fail if the [elastic contributor agreement](https://www.elastic.co/contributor-agreement) isn't on file for a github user. However, I didn't see that info anywhere prior to trying to submit my first integration so my initial CI build failed due to it. 
This PR adds that language to the dev docs about building a new integration, specifically in the **Open a PR** section.
- See #3839 for a PR that failed due to no contributor agreement on file at time PR was submitted.
> [docs] Add contributor agreement prereq to dev docs

- packages/tenable_sc/_dev/build/docs/README.md
- packages/tenable_sc/changelog.yml
- packages/tenable_sc/data_stream/asset/agent/stream/httpjson.yml.hbs
- packages/tenable_sc/data_stream/asset/sample_event.json
- packages/tenable_sc/data_stream/plugin/agent/stream/httpjson.yml.hbs
- packages/tenable_sc/data_stream/plugin/sample_event.json
- packages/tenable_sc/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
- packages/tenable_sc/data_stream/vulnerability/sample_event.json
- packages/tenable_sc/docs/README.md
- packages/tenable_sc/manifest.yml
Type of change
- Bug
This PR fixes the bug related to indefinite pagination by adding explicit pagination termination conditions. In the Filebeat version, 8.2.0 pagination termination was not happening. Refer to the attached issue for more information.
- Closes https://github.com/elastic/integrations/issues/3931
> [tenable_sc] Fix an indefinite pagination bug by adding explicit pagination termination conditions.

- packages/problemchild/changelog.yml
- packages/problemchild/kibana/ml_module/problemchild-ml.json
- packages/problemchild/manifest.yml
While testing changes made in [this](https://github.com/elastic/integrations/pull/3777) PR in the snapshot environment, we found that the ML jobs module for the LotL Attack Detection package does not show up if no malicious events were seen by the ingest pipeline. This is not expected behavior. This PR fixes that.
- Build the latest ProblemChild package from this branch
- Stand up a cluster using elastic-package
- Add the LotL Attack Detection integration
- Create a test index with the default index pipeline as the ProblemChild ingest pipeline and mappings for the problemchild prediction and blocklist fields
- Ingest a dummy Windows process event document in the test index which is known to produce a prediction of 0 from the ProblemChild supervised model
- Create a data view for the test …
> Fixes the ML jobs query for the LotL Attack Detection Package

- .ci/Jenkinsfile
String-based syntax for parameters of `triggerRemoteJob` doesn't work on latest Jenkins LTS. Migrate to the new map-based syntax.
Issue found in https://github.com/elastic/elastic-package/pull/928, solution evaluated in https://github.com/elastic/elastic-package/pull/929.
> Stop using legacy syntax for parameters on triggerRemoteJob

- packages/elastic_agent/_dev/build/build.yml
- packages/elastic_agent/changelog.yml
- packages/elastic_agent/manifest.yml
Adds ECS dependency in order to fix ECS fields resolution in the package.
Addressed https://github.com/elastic/integrations/issues/3926
- Closes https://github.com/elastic/integrations/issues/3926
Before the fix, the ECS field in the package is not resolved:
After the fix, the ECS field in the package is resolved:
> Elastic Agent: Fix ECS fields resolution

- packages/journald/_dev/build/build.yml
- packages/journald/_dev/build/docs/README.md
- packages/journald/changelog.yml
- packages/journald/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/journald/data_stream/log/fields/ecs.yml
- packages/journald/data_stream/log/sample_event.json
- packages/journald/docs/README.md
- packages/journald/manifest.yml
Update kibana.constraint to allow 8.1.0+. 8.1.0 is required because https://github.com/elastic/beats/pull/30032
is needed due to a breaking change that was introduced in 8.0.0.
Rename message_id to ECS event.code. This field was added in 8.0. From [man systemd.journal-fields](https://www.man7.org/linux/man-pages/man7/systemd.journal-fields.7.html)
>   MESSAGE_ID=
>            A 128-bit message identifier ID for recognizing certain
>            message types, if this is desirable. ...
> [journald] Add 8.x support

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/firewall_logs/_dev/test/pipeline/test-firewall.log-expected.json
- packages/aws/data_stream/firewall_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/route53_resolver_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/s3access/_dev/test/pipeline/test-s3-server-access.log-expected.json
- packages/aws/data_stream/s3access/elasticsearch/ingest_pipeline/default.yml
- packages/aws/manifest.yml
The AWS-S3 input sets the `cloud.region` field to the region the S3 bucket is located. This is not always the same as the region the event originated per https://discuss.elastic.co/t/filebeat-aws-cloudtrail-processor-parses-incorrect-aws-region-from-logs/312150.  The current ingest pipelines only use a rename processor which doesn't work if the field already exists.  This changes the processor a set to override from the input. Also adds additional parsing for datastreams that don't already have `cloud.region` set.
-
> [AWS] Update AWS cloud.region parsing

- packages/activemq/changelog.yml
- packages/activemq/data_stream/log/fields/fields.yml
- packages/activemq/docs/README.md
- packages/activemq/manifest.yml
- Bug
This PR contains a minor cleanup for ActiveMQ integration. It removes the 2 fields which were present in **fields.yml** . These two fields are `activemq.log.log_stack_trace` and `activemq.log.message` which are regrouped in `error.stack_trace` and `message` fields. Since these fields are replaced they are no longer required in fields.yml. 
As we know that release tag got deprecated but recently got added by [ellis-elastic](https://github.com/ellis-elastic) in this [PR](https://github.com/elastic/integrations/pull/3535/files) , so removed that tag as a part of this bugfix PR
The changes which are made do not affect the existing functionality of the integration at all and are just a cleanup to the integration.
- Start …
> [activemq] Update integration package to remove unnecessary fields

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/data_stream/query/manifest.yml
- packages/prometheus/manifest.yml
For cases when prometheus is running not on kubernetes, prometheus integration does not work:
- defined default value for bearer_token cause those errors:
``` 
{"log.level":"error","@timestamp":"2022-08-18T09:02:02.484Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat_monitoring stderr: \"panic: close of closed channel\\n\\ngoroutine 2015 [running]:\\ngithub.com/elastic/beats/v7/metricbeat/beater.(*Metricbeat).Stop(0xc0009d44d0)\\n\\t/go/src/github.com/elastic/beats/metricbeat/beater/metricbeat.go:276 +0x28\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\t/go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:461 …
```
> [Prometheus] Disable leader election; Remove default value for bearer token

- packages/system/changelog.yml
- packages/system/data_stream/security/_dev/test/pipeline/test-4738.json
- packages/system/data_stream/security/_dev/test/pipeline/test-4738.json-expected.json
- packages/system/data_stream/security/_dev/test/pipeline/test-4742.json
- packages/system/data_stream/security/_dev/test/pipeline/test-4742.json-expected.json
- packages/system/manifest.yml
This adds test cases for events 4738 and 4742, missed in the original bugfix.
- Updates #3898
> system/security: add test cases for events 4738 and 4742

- packages/hashicorp_vault/_dev/build/docs/README.md
- packages/hashicorp_vault/_dev/deploy/docker/docker-compose.yml
- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/hashicorp_vault/data_stream/audit/fields/ecs.yml
- packages/hashicorp_vault/data_stream/audit/fields/fields.yml
- packages/hashicorp_vault/data_stream/audit/sample_event.json
- packages/hashicorp_vault/docs/README.md
- packages/hashicorp_vault/manifest.yml
Update tests to use Hashicorp Vault 1.11.2.
Update mappings for Vault 1.11 audit data schema.
- Closes #4035
1.11 event with new fields.
```
{
"agent": {
"name": "docker-fleet-agent",
"id": "03109bfa-7015-46bd-9433-3879357210cd",
"type": "filebeat",
"ephemeral_id": "c6777a07-0ee5-4efc-b9d5-efe38e545ab5",
"version": "8.3.2"
},
"hashicorp_vault": {
"audit": {
"request": {
"client_token": "hmac-sha256:9670f60ae136c9fb5ec99472291977aa9c61ad4d49829cf4dffabc21d5a05483",
"path": "auth/token/lookup-self",
"namespace": {
"id": "root"
},
"remote_port": 46026,
"id": "6a2dae54-47cc-80ab-43d5-aaa60bc95745",
"mount_type": "token",
"remote_address": "172.30.0.4",
"client_token_accessor": "hmac-sha256:dd2e0395c657ad5a10dfd832e841b0f1d91e0e95911fa58d6ee7fe7e622912c5",
"operation": "read", …
```
> [hashicorp_vault] Test with Vault 1.11.2

- packages/system/changelog.yml
- packages/system/data_stream/security/fields/ecs.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
Fix missing mappings for `error.code` and `error.message`.
- Closes #4071
> [System] Fix missing field mappings

- packages/spring_boot/changelog.yml
- packages/spring_boot/data_stream/audit_events/_dev/test/pipeline/test-auditevent-metrics.log-expected.json
- packages/spring_boot/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
- packages/spring_boot/data_stream/audit_events/fields/fields.yml
- packages/spring_boot/data_stream/audit_events/sample_event.json
- packages/spring_boot/data_stream/gc/sample_event.json
- packages/spring_boot/data_stream/http_trace/_dev/test/pipeline/test-httptrace-metrics.log-expected.json
- packages/spring_boot/data_stream/http_trace/elasticsearch/ingest_pipeline/default.yml
- packages/spring_boot/data_stream/http_trace/fields/fields.yml
- packages/spring_boot/data_stream/http_trace/sample_event.json
- packages/spring_boot/data_stream/memory/elasticsearch/ingest_pipeline/default.yml
- packages/spring_boot/data_stream/memory/fields/fields.yml
- packages/spring_boot/data_stream/memory/sample_event.json
- packages/spring_boot/data_stream/threading/sample_event.json
- packages/spring_boot/docs/README.md
- packages/spring_boot/kibana/lens/spring_boot-0f481600-ca11-11ec-b4b1-b57f75afa7dd.json
- packages/spring_boot/kibana/lens/spring_boot-12228630-ca11-11ec-b4b1-b57f75afa7dd.json
- packages/spring_boot/kibana/lens/spring_boot-4a05b120-c9ea-11ec-b4b1-b57f75afa7dd.json
- packages/spring_boot/kibana/lens/spring_boot-a41702e0-c7f1-11ec-986a-f1e84447fd00.json
- packages/spring_boot/kibana/lens/spring_boot-e9033ff0-c9e9-11ec-b4b1-b57f75afa7dd.json
- packages/spring_boot/manifest.yml
- Bug
This PR is of the Spring Boot integration to update the field name in `audit_events` data stream dashboard and some nits in fields descriptions. Along with the fixes, it also enhances the integration by following some of the best practices of integration development.
- Move to integrations/packages/spring_boot directory.
> [Spring Boot] Update the field in `audit_events` data stream dashboard

- packages/traefik/changelog.yml
- packages/traefik/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/traefik/manifest.yml
Fix a `if` condition on the community_id processor on one of the ingest pipeline of the Traefik integration.
`cd packages/traefik && elastic-package test pipeline -v `
> fix condition on community_id processor

- packages/aws/changelog.yml
- packages/aws/kibana/dashboard/aws-e6776b10-1534-11ea-841c-01bf20a6c8ba.json
- packages/aws/manifest.yml
Fixes Billing Dashboard.  Replaced incorrect field with proper one.
- Closes #4082
> [AWS] Fix Billing Dashboard

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_job/fields/base-fields.yml
- packages/kubernetes/data_stream/state_job/fields/fields.yml
- packages/kubernetes/manifest.yml
remove overlapping fields in state_job data_stream, that causes some inconsistency (like mentioned [here](https://github.com/elastic/integrations/pull/4081#issuecomment-1228695490))
-
> [kubernetes] remove overlapping field in state_job data_stream

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/agent/stream/tcp.yml.hbs
- packages/panw/data_stream/panos/agent/stream/udp.yml.hbs
- packages/panw/manifest.yml
For panw changes whitespace so when templates are expanded the policy can be compiled.  Previously adding a processor broke compiling the policy.
1. `elastic-package stack up -d`
2. Add `panw` integration to a policy
3. Add processors to TCP, UDP & file input types
4. Add integration
> [panw] bug fix for adding processors

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/manifest.yml
- revert index mapping configuration introduces in this PR - https://github.com/elastic/integrations/pull/3891 (reason - [issue](https://github.com/elastic/kibana/issues/129344) was fixed)
- add description to the http config options. Context: from https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html#_example_configuration_51:
prometheus module supports the options described in [Standard HTTP config options](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html#module-http-config-options)
- bump kibana version to 8.4, because mapping fix was added in 8.4
-
dynamic template:
Prometheus integration UI:
> [prometheus] revert index mapping changes

- packages/aws/changelog.yml
- packages/aws/manifest.yml
- packages/aws_logs/changelog.yml
- packages/aws_logs/manifest.yml
- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/manifest.yml
- packages/cisco_umbrella/manifest.yml
- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/manifest.yml
- packages/crowdstrike/manifest.yml
Bug
Apply an hotfix for https://github.com/elastic/beats/issues/32888 directly in the aws integration package.
Proper fix downstream will be addressed in https://github.com/elastic/beats/pull/32921
-
> set default endpoint in aws to empty string

- docs/generic_guidelines.md
These docs were in internal observability docs, but never migrated here.
> Add docs about dimensions

- packages/elasticsearch/data_stream/ccr/fields/ecs.yml
- packages/elasticsearch/data_stream/cluster_stats/fields/ecs.yml
- packages/elasticsearch/data_stream/enrich/fields/ecs.yml
- packages/elasticsearch/data_stream/index/fields/ecs.yml
- packages/elasticsearch/data_stream/index_recovery/fields/ecs.yml
- packages/elasticsearch/data_stream/index_summary/fields/ecs.yml
- packages/elasticsearch/data_stream/ml_job/fields/ecs.yml
- packages/elasticsearch/data_stream/node/fields/ecs.yml
- packages/elasticsearch/data_stream/node_stats/fields/ecs.yml
- packages/elasticsearch/data_stream/pending_tasks/fields/ecs.yml
- packages/elasticsearch/data_stream/shard/fields/ecs.yml
- packages/kibana/data_stream/cluster_actions/fields/ecs.yml
- packages/kibana/data_stream/cluster_rules/fields/ecs.yml
- packages/kibana/data_stream/node_actions/fields/ecs.yml
- packages/kibana/data_stream/node_rules/fields/ecs.yml
- packages/kibana/data_stream/stats/fields/ecs.yml
- packages/kibana/data_stream/status/fields/ecs.yml
- packages/kibana/docs/README.md
- packages/logstash/data_stream/node/fields/ecs.yml
- packages/logstash/data_stream/node_stats/fields/ecs.yml
Add mapping for the [error.message](https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-message) field. 
It will allow SM to filter erroneous documents for https://github.com/elastic/kibana/pull/140102 and https://github.com/elastic/integrations/issues/4011
> [Stack Monitoring] add error.message mapping

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container/fields/base-fields.yml
- packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
- packages/kubernetes/data_stream/pod/fields/base-fields.yml
- packages/kubernetes/data_stream/state_container/fields/base-fields.yml
- packages/kubernetes/data_stream/state_cronjob/fields/base-fields.yml
- packages/kubernetes/data_stream/state_daemonset/fields/base-fields.yml
- packages/kubernetes/data_stream/state_job/fields/base-fields.yml
- packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/base-fields.yml
- packages/kubernetes/data_stream/state_pod/fields/base-fields.yml
- packages/kubernetes/data_stream/state_replicaset/fields/base-fields.yml
- packages/kubernetes/data_stream/state_resourcequota/fields/base-fields.yml
- packages/kubernetes/data_stream/state_service/fields/base-fields.yml
- packages/kubernetes/data_stream/state_statefulset/fields/base-fields.yml
- packages/kubernetes/data_stream/volume/fields/base-fields.yml
- packages/kubernetes/manifest.yml
When working on another PR - https://github.com/elastic/integrations/pull/4095#discussion_r958218787, I've noticed that some dimension fields are missing - mainly for `namespace` field - at some point namespace related PR was reverted and all dimension fields were removed - https://github.com/elastic/integrations/pull/2209.
Also some fields had typos
-
> [kubernetes ] Add missing dimention fields

- packages/kafka/changelog.yml
- packages/kafka/data_stream/consumergroup/agent/stream/stream.yml.hbs
- packages/kafka/data_stream/consumergroup/manifest.yml
- packages/kafka/data_stream/partition/agent/stream/stream.yml.hbs
- packages/kafka/data_stream/partition/manifest.yml
- packages/kafka/manifest.yml
kafka integration will be passing down _**sasl.mechanism**_ for **consumergroup** & **partition** data_streams.
- Closes #3667
```
- id: kafka/metrics-kafka.partition-2b7de019-5e65-4fc2-a011-2e80100604bf
data_stream:
dataset: kafka.partition
type: metrics
metricsets:
- partition
period: 10s
hosts:
- 'localhost:9092'
username: u1
password: p1
sasl.mechanism: SCRAM-SHA-256
```
> Kafka sasl mechanism

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
This cleans up the grok pattern naming so that the name matches the target.
- Relates #3507
> cisco_asa,cisco_ftd: rename syslog priority grok pattern SYSLOGFACILITY=>SYSPRIORITY

- docs/documentation_guidelines.md
- links_table.yml
Updated documentation guidelines to include the information related to how the readme templates work. And information related to how to use links with url placeholder.
This PR adds the links definitions file into the root of the working repository (`links_table.yml`). This file is going to be used while rendering README files when it is used the new placeholder `{{ url <key> <link> }}` notation introduced in https://github.com/elastic/elastic-package/pull/938
In following PRs, packages will be updated to use this new placeholder in their docs.
- Relates https://github.com/elastic/integrations/issues/4067
- Requires https://github.com/elastic/elastic-package/issues/948
> Added new file for links definitions

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/stream.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Add additional AWS auth options (https://github.com/elastic/security-team/issues/4495)
Related https://github.com/elastic/security-team/issues/4495
> feat: add aws additional auth options

- .ci/Jenkinsfile
This PR modifies the Jenkinsfile to run the publishing step also for `backport-*` branches.
> CI: enable backport branches

- .ci/jobs/integrations.yml
Tidy up what branches from the upstream can be built in the CI. 
People contribute through their forked repositories, or origin Pull Requests, hence there is no need to build all the branches for this project but the ones following certain nomenclature `feature-.*` or `backport-.*` (see https://github.com/elastic/integrations/pull/4182)
> jjbb: exclude branches which are not main or feature/backport in the upstream

- packages/cloudflare/changelog.yml
- packages/cloudflare/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/cloudflare/manifest.yml
- Change lookup of key for array length from 'response' to 'result'
- Closes #4195
> [cloudflare] Fix lookup of invalid key for pagination

- packages/okta/changelog.yml
- packages/okta/manifest.yml
This fixes the configuration requirements for the okta api_key.
- Fixes #4105
> okta: mark api_key config field as required

- packages/cisco_ise/changelog.yml
- packages/cisco_ise/data_stream/log/_dev/test/pipeline/test-pipeline-tacacs-accounting.log-expected.json
- packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_tacacs_accounting.yml
- packages/cisco_ise/data_stream/log/fields/fields.yml
- packages/cisco_ise/data_stream/log/sample_event.json
- packages/cisco_ise/docs/README.md
- packages/cisco_ise/manifest.yml
In most documented cases cisco_ise.log.avpair.task_id appears to be a decimal
numeric value. However, in the wild hex, numerical and UUID values appear to
exist so map as a keyword.
- Closes #4075
> cisco_ise: map cisco_ise.log.avpair.task_id as keyword

- packages/atlassian_confluence/_dev/build/docs/README.md
- packages/atlassian_confluence/changelog.yml
- packages/atlassian_confluence/data_stream/audit/manifest.yml
- packages/atlassian_confluence/docs/README.md
- packages/atlassian_confluence/manifest.yml
- packages/atlassian_jira/_dev/build/docs/README.md
- packages/atlassian_jira/changelog.yml
- packages/atlassian_jira/data_stream/audit/manifest.yml
- packages/atlassian_jira/docs/README.md
- packages/atlassian_jira/manifest.yml
> atlassian_{confluence,jira}: clarify API authentication

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
This relaxes the parsing of 113005 messages that do not conform to the documented format but appear in the wild.
- Fixes #4185
> cisco_asa: fix handling of non-canonical 113005 messages

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/fields/ecs.yml
- packages/cloud_security_posture/data_stream/findings/fields/fields.yml
- packages/cloud_security_posture/manifest.yml
Update the mapping CSP uses based on https://github.com/elastic/cloudbeat/pull/346
-
> Update CSP mapping fields

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/audit_logs/fields/fields.yml
- packages/kubernetes/docs/audit-logs.md
- packages/kubernetes/manifest.yml
Add audit logs fields to the mapping. More details why it was not possible to introduce it before - https://github.com/elastic/integrations/issues/3664#issuecomment-1227202756
- Closes https://github.com/elastic/integrations/issues/3664
> Add kubernetes.audit.annotations.authorization_k8s_io/* fields

- .ci/Jenkinsfile
ignore issues with kind delete cluster, example: https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-4203/3/pipeline/
```
ERROR: failed to delete cluster "kind": failed to delete nodes: command "docker rm -f -v kind-control-plane" failed with error: exit status 1
```
similar to https://github.com/elastic/elastic-package/pull/967
-
> Ignore issues with kind delete cluster

- .ci/schedule-daily.groovy
Bump from 8.3.0-SNAPSHOT to 8.5.0-SNAPSHOT for daily test jobs.
This affects https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations-daily/.
> [ci] Use Elastic Stack 8.5.0-SNAPSHOT in daily jobs

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/agent/stream/log.yml.hbs
- packages/infoblox_nios/data_stream/log/agent/stream/tcp.yml.hbs
- packages/infoblox_nios/data_stream/log/agent/stream/udp.yml.hbs
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox_nios/data_stream/log/manifest.yml
- packages/infoblox_nios/manifest.yml
This adds the ability to configure the timezone for event ingestion.
- Closes #4184
> infoblox_nios: allow configuration of timezone

- .ci/Jenkinsfile
- dev/benchreport/benchmark.go
- dev/benchreport/report.go
- dev/benchreport/result.go
- magefile.go
Adds a mage target that will compare two given benchmark results folders.
The source folder will be compared against a target folder, and for any benchmark result in source it will generate a report, showing the variation between the two.
Example report:
Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`admin` | 0 | 2906.13 | 2906.13 (100%) | :+1:
`drive` | 0 | 4882.81 | 4882.81 (100%) | :+1:
`groups` | 0 | 5232.86 | 5232.86 (100%) | :+1:
`login` | 0 | 4972.65 | 4972.65 (100%) | :+1:
`saml` | 0 | 6377.55 | 6377.55 (100%) | :+1:
`user_accounts` | 0 | 12626.26 | 12626.26 (100%) | :+1:
Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`forwarded` | 5854.8 | 3148.61 …
> [ci] Add mage command to compare bench reports

- packages/activemq/changelog.yml
- packages/activemq/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
- packages/activemq/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/data_stream/audit/fields/ecs.yml
- packages/activemq/data_stream/audit/sample_event.json
- packages/activemq/data_stream/broker/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/data_stream/broker/fields/ecs.yml
- packages/activemq/data_stream/broker/sample_event.json
- packages/activemq/data_stream/log/_dev/test/pipeline/test-activemq.log-expected.json
- packages/activemq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/data_stream/log/fields/ecs.yml
- packages/activemq/data_stream/log/sample_event.json
- packages/activemq/data_stream/queue/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/data_stream/queue/fields/ecs.yml
- packages/activemq/data_stream/queue/sample_event.json
- packages/activemq/data_stream/topic/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/data_stream/topic/fields/ecs.yml
- packages/activemq/data_stream/topic/sample_event.json
- packages/activemq/docs/README.md
- packages/activemq/manifest.yml
- Enhancement
This pull request is raised to add some ECS fields to ActiveMQ package which could be useful for user experience. Following changes are made to enhance package.
- Added event.category
- Added event.kind
- Added event.type
- Updated ecs.yml with all the fields
- Updated version to 0.4.3 in manifest.yml
- Move to integrations/packages/activemq directory.
> [activemq] Add ECS fields

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
This fixes the handling of message type 302020 which was being incorrectly characterised as a termination event rather than a start event.
- Updates #4199
> cisco_{asa,ftd}: fix handling of 302020 messages

- packages/gcp/changelog.yml
- packages/gcp/data_stream/firestore/agent/stream/stream.yml.hbs
- packages/gcp/manifest.yml
Convert GCP Firestore metricset from lightweight
- Closes #3722
> [GCP] Convert GCP Firestore metricset from lightweight

- packages/gcp/changelog.yml
- packages/gcp/data_stream/gke/agent/stream/stream.yml.hbs
- packages/gcp/manifest.yml
Convert GCP GKE metricset from lightweight
- Relates #490
- Requires #2301
- Requires #3798
> [GCP] Convert GCP GKE metricset from lightweight

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/_dev/test/system/test-logfile-config.yml
- packages/infoblox_nios/data_stream/log/manifest.yml
- packages/infoblox_nios/manifest.yml
This fixes a duplication of the log file input path in the configuration page for `infoblox_nios`. It also harmonises the input title for the file input with the two others. See screenshots below.
Before this change:
After this change:
> infoblox_nios: fix configuration page

- packages/mattermost/_dev/build/docs/README.md
- packages/mattermost/changelog.yml
- packages/mattermost/docs/README.md
- packages/mattermost/manifest.yml
Add link to product documentation for Mattermost.
- Supersedes #3001
> [Mattermost] Add product docs link

- packages/vsphere/_dev/build/build.yml
- packages/vsphere/_dev/deploy/docker/docker-compose.yml
- packages/vsphere/_dev/deploy/docker/sample_logs/syslog.log
- packages/vsphere/changelog.yml
- packages/vsphere/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log
- packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log-expected.json
- packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/manifest.yml
-  Updates grok pattern to make domain field optional
- Updates to ECS 8.4
- Closes #4109
> [Vsphere] Fix optional domain in grok pattern

- packages/gcp/changelog.yml
- packages/gcp/data_stream/pubsub/agent/stream/stream.yml.hbs
- packages/gcp/manifest.yml
Remove lightweight module in gcp.pubsub data stream
- Closes #4263
> [GCP] Remove lightweight module in gcp.pubsub data stream

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-events.log-expected.json
- packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/events.yml
- packages/cisco_meraki/manifest.yml
- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet.log-expected.json
- packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/fortinet_fortigate/manifest.yml
This fixes issues in ECS compliance in the cisco_meraki and fortinet_fortigate packages.
- For #4284
> cisco_meraki,fortinet_fortigate: fix ECS issues

- packages/system/changelog.yml
- packages/system/data_stream/syslog/agent/stream/log.yml.hbs
- packages/system/manifest.yml
This removes a duplicated `processors` line in the syslog datastream.
> Fix duplicated processor in syslog

- packages/azure_billing/_dev/build/docs/README.md
- packages/azure_billing/changelog.yml
- packages/azure_billing/data_stream/billing/manifest.yml
- packages/azure_billing/docs/README.md
- packages/azure_billing/manifest.yml
Update the integration UX and documentation to enhance:
- How to create and configure the required App Registration.
- How to use the scopes (subscription, department, and billing account).
- Closes #3279
> Azure Billing Metrics UX and docs update

- packages/carbon_black_cloud/changelog.yml
- packages/carbon_black_cloud/data_stream/alert/sample_event.json
- packages/carbon_black_cloud/data_stream/asset_vulnerability_summary/sample_event.json
- packages/carbon_black_cloud/data_stream/audit/sample_event.json
- packages/carbon_black_cloud/data_stream/endpoint_event/_dev/test/pipeline/test-endpoint-event.log-expected.json
- packages/carbon_black_cloud/data_stream/endpoint_event/elasticsearch/ingest_pipeline/default.yml
- packages/carbon_black_cloud/data_stream/watchlist_hit/_dev/test/pipeline/test-watchlist-hit.log-expected.json
- packages/carbon_black_cloud/data_stream/watchlist_hit/elasticsearch/ingest_pipeline/default.yml
- packages/carbon_black_cloud/docs/README.md
- packages/carbon_black_cloud/manifest.yml
- packages/sentinel_one/changelog.yml
- packages/sentinel_one/data_stream/activity/_dev/test/pipeline/test-pipeline-activity.log-expected.json
- packages/sentinel_one/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/activity/sample_event.json
- packages/sentinel_one/data_stream/agent/sample_event.json
- packages/sentinel_one/data_stream/alert/sample_event.json
- packages/sentinel_one/data_stream/group/sample_event.json
- packages/sentinel_one/data_stream/threat/sample_event.json
- packages/sentinel_one/docs/README.md
- packages/sentinel_one/manifest.yml
There has been a change in behaviour in the set iteration order between v8.3.3 and v8.4.1, so sort the array to ensure a stable order for testing.
In carbon_black the multiple argument appends with allow_duplicates=false also leads to a change in array ordering. The cause for this is less clear, but sort the array to work around the issue.
This ensures that arrays which showed unstable ordering between v8.3.3 and v8.4.1 are consistently ordered explicitly.
-
> carbon_black_cloud,sentinel_one: ensure consistent ordering of arrays

- packages/ti_cif3/changelog.yml
- packages/ti_cif3/manifest.yml
Tag Collective Intelligence Framework v3 integration with `threat_intel` category so it appears under Threat Intelligence category
> add threa_intel category to ti_cif3 integrations

- packages/kibana/changelog.yml
- packages/kibana/img/logo_kibana.svg
Replaces the kibana package logo with the one from https://brand.elastic.co/302f66895/p/41ff52-solution-logos/b/14d954/i/11013297
It's a little complicated. See https://github.com/elastic/integrations/pull/4175 for instructions.
Closes https://github.com/elastic/integrations/issues/4297
> Update kibana logo

- packages/aws/changelog.yml
- packages/aws/data_stream/billing/agent/stream/stream.yml.hbs
- packages/aws/manifest.yml
Fix billing datastream agent template.
- Closes #4307
> [AWS] Fix billing datastream agent template.

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/container_logs/manifest.yml
- packages/kubernetes/manifest.yml
Add `condition` configuration option to container logs data stream
- Closes #4306
> [Kubernetes] Add `condition` configuration option to container logs data stream

- packages/gcp/changelog.yml
- packages/gcp/data_stream/gke/agent/stream/stream.yml.hbs
- packages/gcp/manifest.yml
Fixes `kubernetes.io` service prefix indentation.
-
> [GCP] Fix kubernetes.io service prefix indendation

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
- packages/cloud_security_posture/manifest.yml
> Remove unconfigurable default fields from hbs files

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Cloud Security Posture integration is now GA.
___ 
- Closes: https://github.com/elastic/security-team/issues/5108
> moving cloud security posture to GA

- packages/infoblox_bloxone_ddi/_dev/build/docs/README.md
- packages/infoblox_bloxone_ddi/changelog.yml
- packages/infoblox_bloxone_ddi/docs/README.md
- packages/infoblox_bloxone_ddi/manifest.yml
Related: https://github.com/elastic/integrations/pull/4295
Escapes the left angle bracket (`<`) used in the new Infoblox BloxOne DDI doc. 
The [Integration docs](https://docs.elastic.co/integrations) use MDX (not plain Markdown). From the [MDX documentation](https://mdxjs.com/docs/what-is-mdx/#markdown):
>Unescaped left angle bracket / less than (`<`) and left curly brace (`{`) have to be escaped: `\<` or `\{` (or use expressions: `{'<'}`, `{'{'}`)
I used `\<` because it also renders correctly in plain Markdown (see **Screenshots** below).
Note: This PR also removes the "Overview" heading, which will be added when the file is processed from a Markdown file to an MDX file. Though including the "Overview" heading here doesn't break the build, it does result in two "Overview" headings on the …
> [docs] Escape left angle bracket (`<`)

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
Adds project fields to lightweight project monitors via processors.
1. Pull down this PR
2. `cd packages/synthetics`
3. `elastic-package clean`
4. `elastic-package build`
5. `elastic-package stack up --version 8.5.0-SNAPSHOT -v`
6. Navigate to Uptime. Create a private location with the elastic-package agent policy
7. In your terminal, run `npx @elastic/synthetics init` to init a new synthetics testing directory, or update an existing testing directory to by updating `synthetics.config.ts` to use `https://localhost:5601` and update private locations to include your new private location. 
8. In your `journeys` directory within your synthetics tests, add the following lightweight monitors in a `heartbeat.yml` file
```
heartbeat.monitors:
- type: icmp
id: stuff
name: Cloudflare DNS
hosts: …
```
> [Synthetics] project fields for lightweight monitors

- packages/azure/_dev/build/docs/README.md
- packages/azure/changelog.yml
- packages/azure/docs/README.md
- packages/azure/manifest.yml
Remove the 'Overview' heading at the doc beginning.
I just learned that https://docs.elastic.co/integrations/azure automatically adds one on its own, so we should omit it in the source code to avoid duplicates.
> [Azure Logs] Remove extra overview heading

- packages/gcp/changelog.yml
- packages/gcp/data_stream/dns/_dev/test/pipeline/test-dns.log-expected.json
- packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/dns/sample_event.json
- packages/gcp/docs/README.md
- packages/gcp/docs/dns.md
- packages/gcp/manifest.yml
This converts `dns.answers.ttl` to long during document parsing to conform to ECS spec for this field.
- Closes #4361
> gcp: fix type of dns.answers.ttl

- packages/netflow/changelog.yml
Amend 2.2.5 changelog entry with correct link.
> [netflow] Amend 2.2.5 changelog entry with correct link

- packages/microsoft_dhcp/_dev/build/docs/README.md
- packages/microsoft_dhcp/changelog.yml
- packages/microsoft_dhcp/docs/README.md
- packages/microsoft_dhcp/manifest.yml
- Bug
This fixes an issue in the documentation and does not impact the integration itself.
The hyperlink is broken and displays incorrectly here on GitHub and in Kibana. Also, the last parenthesis ")" is not properly parsed either so the link doesn't work at all in Kibana, (you will get a 404 not found).
> [microsoft_dhcp] Fix broken hyperlink in docs

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudfront_logs/agent/stream/aws-s3.yml.hbs
- packages/aws/manifest.yml
This PR is to fix adding processors for `cloudfront` logs in AWS package. With the change, we can see `processors` in agent policy is in the right format now:
```
inputs:
- id: aws-s3-cloudfront-096288f1-4c9d-4f1b-a6b1-7e73ecc7a849
name: aws-1
revision: 1
type: aws-s3
meta:
package:
name: aws
version: 1.24.3
data_stream:
streams:
- id: aws-s3-aws.cloudfront_logs-096288f1-4c9d-4f1b-a6b1-7e73ecc7a849
data_stream:
dataset: aws.cloudfront_logs
type: logs
queue_url: 'https://sqs.us-east-1.amazonaws.com/123/test'
max_number_of_messages: 5
access_key_id: a
secret_access_key: b
session_token: c
tags:
- forwarded
- aws-cloudfront
publisher_pipeline.disable_host: true
processors:
- drop_event:
when:
regexp:
message: ^#.*
- drop_event:
when:
not:
regexp: …
```
> Fix adding processors in cloudfront logs

- packages/gcp/changelog.yml
- packages/gcp/data_stream/redis/fields/agent.yml
- packages/gcp/docs/redis.md
- packages/gcp/manifest.yml
- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/fields/agent.yml
- packages/google_workspace/data_stream/drive/fields/agent.yml
- packages/google_workspace/data_stream/groups/fields/agent.yml
- packages/google_workspace/data_stream/login/fields/agent.yml
- packages/google_workspace/data_stream/saml/fields/agent.yml
- packages/google_workspace/data_stream/user_accounts/fields/agent.yml
- packages/google_workspace/manifest.yml
This fixes field definition duplications in gcp and google_workspace.
- gcp is a regression
- google_workspace was not discovered in previous rounds of deduplication which depend on `elastic-package check` and are stochastic.
- For #4338
- Updates #4398
> gcp,google_workspace: remove duplicate fields

- packages/azure/changelog.yml
- packages/azure_billing/_dev/build/docs/README.md
- packages/azure_billing/changelog.yml
- packages/azure_billing/docs/README.md
- packages/azure_billing/manifest.yml
Remove the 'Overview' heading at the doc beginning.
TIL that https://docs.elastic.co/integrations/azure automatically adds one on its own, so we should omit it in the source code to avoid duplicates.
- Relates #4382 4382
> [Azure Billing Metrics] Remove extra overview heading

- packages/system/changelog.yml
- packages/system/data_stream/syslog/agent/stream/log.yml.hbs
- packages/system/manifest.yml
Similar to https://github.com/elastic/integrations/pull/4395, this PR is to fix adding processors for `syslog` in system package.
> [system] fix adding additional processors in syslog data stream

- packages/system/changelog.yml
- packages/system/data_stream/auth/manifest.yml
- packages/system/manifest.yml
Remove incorrect tag
- Closes #4188
> [System] Remove incorrect tag

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/metrics/agent/stream/stream.yml.hbs
- packages/mongodb/manifest.yml
- Bug
Updated the username and password variable in the template file for metrics data stream.
- Clone the PR.
- Run the elastic-package stack up command.
- Add the mongoDb integration.
- In Integration UI provide all host related details.
- Enrol the elastic agent.
- MongoDB Metrics should be flowing to the Elastic-search.
- Closes #4345
> [MongoDB]Adding username and password to handlebar file

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
- packages/network_traffic/changelog.yml
- packages/network_traffic/manifest.yml
As part of https://github.com/elastic/kibana/issues/141823, we want to have featured integrations for certain categories. The network_traffic and cloud_security_posture integrations will be featured in the security category so they need the security category in the manifest.
> Add "security" category to featured security integrations

- packages/akamai/changelog.yml
- packages/akamai/data_stream/siem/fields/ecs.yml
- packages/akamai/manifest.yml
- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/fields/agent.yml
- packages/auditd/data_stream/log/fields/fields.yml
- packages/auditd/data_stream/log/fields/package-fields.yml
- packages/auditd/docs/README.md
- packages/auditd/manifest.yml
- packages/barracuda/changelog.yml
- packages/barracuda/data_stream/spamfirewall/fields/base-fields.yml
- packages/barracuda/data_stream/waf/fields/base-fields.yml
- packages/barracuda/manifest.yml
- packages/bluecoat/changelog.yml
- packages/bluecoat/data_stream/director/fields/base-fields.yml
- packages/bluecoat/manifest.yml
- packages/box_events/changelog.yml
- packages/box_events/data_stream/events/fields/fields.yml
- packages/box_events/manifest.yml
- packages/carbon_black_cloud/changelog.yml
- packages/carbon_black_cloud/data_stream/alert/fields/agent.yml
- packages/carbon_black_cloud/data_stream/asset_vulnerability_summary/fields/agent.yml
- packages/carbon_black_cloud/data_stream/endpoint_event/fields/agent.yml
- packages/carbon_black_cloud/data_stream/watchlist_hit/fields/agent.yml
- packages/carbon_black_cloud/docs/README.md
- packages/carbon_black_cloud/manifest.yml
- packages/cef/changelog.yml
- packages/cef/data_stream/log/fields/fields.yml
- packages/cef/manifest.yml
- packages/lastpass/changelog.yml
This removes duplicated field definitions in a some of the SEI packages identified in #4398.
- Updates #4398
> akamai,auditd,barracuda,bluecoat,box_events,carbon_black_cloud,cef: remove duplicated fields

- packages/f5/changelog.yml
- packages/f5/data_stream/bigipafm/fields/base-fields.yml
- packages/f5/data_stream/bigipapm/fields/base-fields.yml
- packages/f5/manifest.yml
- packages/fim/changelog.yml
- packages/fim/data_stream/event/fields/agent.yml
- packages/fim/manifest.yml
- packages/fireeye/changelog.yml
- packages/fireeye/data_stream/nx/fields/agent.yml
- packages/fireeye/data_stream/nx/fields/ecs.yml
- packages/fireeye/manifest.yml
- packages/fortinet_forticlient/changelog.yml
- packages/fortinet_forticlient/data_stream/log/fields/agent.yml
- packages/fortinet_forticlient/data_stream/log/fields/base-fields.yml
- packages/fortinet_forticlient/manifest.yml
- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/data_stream/log/fields/agent.yml
- packages/fortinet_fortigate/manifest.yml
- packages/fortinet_fortimail/data_stream/log/fields/agent.yml
- packages/fortinet_fortimail/data_stream/log/fields/base-fields.yml
- packages/fortinet_fortimanager/changelog.yml
- packages/fortinet_fortimanager/data_stream/log/fields/agent.yml
- packages/fortinet_fortimanager/data_stream/log/fields/base-fields.yml
- packages/fortinet_fortimanager/manifest.yml
This removes duplicated fields from f5 and the fortinet packages as part of #4398.
- Updates #4398
> f5,fim,fireeye,fortinet_*: remove duplicate fields

- packages/aws/changelog.yml
- packages/aws/data_stream/dynamodb/agent/stream/stream.yml.hbs
- packages/aws/data_stream/dynamodb/sample_event.json
- packages/aws/docs/dynamodb.md
- packages/aws/manifest.yml
Use the base cloudwatch metricset for dynamodb, instead of the lightweight module metricsset. Lightweight modules are deprecated in beats; the integration should use the cloudwatch metricset.
> [aws] Use the base cloudwatch metricset for dynamodb, instead of the lightweight module metricsset

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log-expected.json
- packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/flows.yml
- packages/cisco_meraki/manifest.yml
Simplify the handling of the line by using grok from the outset, reducing the number of machines needing to be instantiated and increasing the flexibility of the inputs that can be parsed.
- Closes #4335
> cisco_meraki: improve handling of flows events

- packages/okta/changelog.yml
- packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/okta/manifest.yml
Mark URL as required parameter
- Closes #4413
> [Okta] Make URL config option a required parameter

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log-expected.json
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/data_stream/log/fields/ecs.yml
- packages/cisco_ftd/data_stream/log/fields/fields.yml
- packages/cisco_ftd/data_stream/log/sample_event.json
- packages/cisco_ftd/docs/README.md
- packages/cisco_ftd/manifest.yml
This brings the cisco_asa and cisco_ftd ingest pipelines more into agreement though parts dealing with ECS categorisation remain distinct.
The changes in cisco_asa do not affect test outcomes and are for the most part cosmetic to reduce diff noise in future changes. It does add the malware event kind classification that exists in cisco_ftd.
The changes in cisco_ftd fix incorrect handling of:
- network.inner/cisco.ftd.tunnel_type fields
- 305012 events.
And add the network.community_id field to events.
- Close #2116
> cisco_{asa,ftd}: harmonise pipelines

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/docs/README.md
- packages/cloud_security_posture/manifest.yml
this PR removed the internal links in the readme of the CSP integration that doesn't work when viewing the integration in kibana
> getting rid of internal links

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/manifest.yml
- packages/kibana/changelog.yml
- packages/kibana/manifest.yml
- packages/logstash/changelog.yml
- packages/logstash/manifest.yml
Remove release field, add preview1 identifier
This is based on recommendations in https://github.com/elastic/kibana/issues/122973 and https://github.com/elastic/package-spec/issues/225
```
#!/usr/bin/env bash
set -euxo pipefail
(cd packages/elasticsearch && elastic-package build)
(cd packages/kibana && elastic-package build)
(cd packages/logstash && elastic-package build)
elastic-package stack up -v -d --version 8.6.0-SNAPSHOT
```
- Verify that elasticsearch, kibana & logstash packages are not immediately visible in integrations search
- Click the "available as an Elastic Agent integration" from a logs/metrics package to see the latest version
Note that the label will show "Beta" until https://github.com/elastic/kibana/issues/122973 is addressed.
Closes …
> [Stack Monitoring] Remove release field, add preview1 identifier

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/manifest.yml
Upgrades osquery mappings to match osquery 5.5.1 schema
> Osquery_manager: Upgrade osquery mappings to match osquery 5.5.1 schema

- packages/iis/changelog.yml
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-8.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-72.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis10-access.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-ipv6zone.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-x-forward-for-extended.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-x-forward-for.log-expected.json
- packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/iis/manifest.yml
- Bug
This PR updates the field name in the ingest pipeline processor. Which will ingest the event.duration field to Elasticsearch. 
Run pipeline tests
Verify the event.duration field is captured in the Expected json file.
Run the integration and verify the data is getting ingested into Elasticsearch.
- Closes #4475
> IIS - Update ingest pipeline to process event.duration

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/manifest.yml
Fingerprints the whole event object in addition to the ID one. Some items from the API return multiple events, which share the same id object. This causes that only the first one would get stored and the rest would be dropped because of the duplicated id.
> [google_workspace] Change fingerprint processor to avoid skipping events.

- packages/elastic_agent/data_stream/elastic_agent_logs/fields/ecs.yml
Adds the `agent.*` filed to the Elastic Agent ECS mapping. The mappings are taken from [filebeat](https://github.com/elastic/beats/blob/6a669aac5d95a42b7d6bfaf13d14c79b7fc94361/libbeat/ecs/agent.go#L26).
Install the Elastic Agent integration and verify the fileds `agent.*` in the `logs-*` index are indexed.
- Closes #4191
> Add agent.* fields to Elastic Agent ecs mapping

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/docs/README.md
- packages/cloud_security_posture/manifest.yml
This PR fixes a documentation build error for docs.elastic.co. All code blocks must be formatted in markdown code blocks.
* For https://github.com/elastic/wordlake/pull/50.
> docs: fix doc build error

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/common.yml
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/data_stream/browser_network/manifest.yml
- packages/synthetics/data_stream/browser_screenshot/manifest.yml
- packages/synthetics/data_stream/http/fields/common.yml
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/fields/common.yml
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/fields/common.yml
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
This fixes the type of this numeric field to correctly be a long, thus matching heartbeat.
> [Synthetics] Change state.duration_ms to long from date

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-decryption-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-gtp-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-hipmatch-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-ip-tag-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-sctp-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-system-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-tunnel-inspection-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-userid-sample.log-expected.json
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/authentication.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/config.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/correlated_event.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/decryption.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/threat.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/traffic.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/tunnel_inspection.yml
- packages/panw/data_stream/panos/sample_event.json
- packages/panw/docs/README.md
- packages/panw/manifest.yml
This makes `event.outcome` dependent on event actions and results where appropriate. In some cases `event.outcome` is left empty as the original event does not have a success/failure state.
- Closes #4495
> panw: fix handling of event.outcome

- packages/cisco_duo/changelog.yml
- packages/cisco_duo/data_stream/admin/_dev/test/pipeline/test-empty.log
- packages/cisco_duo/data_stream/admin/_dev/test/pipeline/test-empty.log-expected.json
- packages/cisco_duo/data_stream/admin/agent/stream/httpjson.yml.hbs
- packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/auth/_dev/test/pipeline/test-empty.log
- packages/cisco_duo/data_stream/auth/_dev/test/pipeline/test-empty.log-expected.json
- packages/cisco_duo/data_stream/auth/agent/stream/httpjson.yml.hbs
- packages/cisco_duo/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/offline_enrollment/_dev/test/pipeline/test-empty.log
- packages/cisco_duo/data_stream/offline_enrollment/_dev/test/pipeline/test-empty.log-expected.json
- packages/cisco_duo/data_stream/offline_enrollment/agent/stream/httpjson.yml.hbs
- packages/cisco_duo/data_stream/offline_enrollment/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/summary/_dev/test/pipeline/test-summary.log-expected.json
- packages/cisco_duo/data_stream/telephony/_dev/test/pipeline/test-empty.log
- packages/cisco_duo/data_stream/telephony/_dev/test/pipeline/test-empty.log-expected.json
- packages/cisco_duo/data_stream/telephony/agent/stream/httpjson.yml.hbs
- packages/cisco_duo/data_stream/telephony/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/manifest.yml
This works around the behaviour of the httpjson input that results in a root object being sent to ingest when a split would result in zero children.
**Note** Looking further into the httpjson behaviour the `ignore_empty_value` option on the split processor (not originally intended to handle this) does do the right thing in this case. However is is not testable either in the integration test framework because we cannot test for zero events, nor in the httpjson package input tests for the same reason.
- Closes #4502
> cisco_duo: drop messages that hold no events

- packages/tcp/changelog.yml
- packages/tcp/data_stream/generic/agent/stream/tcp.yml.hbs
- packages/tcp/manifest.yml
- packages/udp/changelog.yml
- packages/udp/data_stream/generic/agent/stream/udp.yml.hbs
- packages/udp/manifest.yml
Fixes the indentation of the syslog processor in the agent handlebars file.
- Closes #4525
> [tcp/udp] Fix indentation of syslog processor in agent handlebars file

- packages/prometheus/_dev/build/docs/README.md
- packages/prometheus/changelog.yml
- packages/prometheus/docs/README.md
- packages/prometheus/manifest.yml
Small documentation updates. Removing x-pack references and updating default values of variables
> Fixing x-pack referneces and updating default values of variables

- packages/microsoft_sqlserver/_dev/build/docs/README.md
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/performance/agent/stream/stream.yml.hbs
- packages/microsoft_sqlserver/data_stream/transaction_log/agent/stream/stream.yml.hbs
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
- Enhancement
Connection is established with and without port number and also with the Instance Name.
> Default Instance - `username:password@host`, `username:password@host:port` 
> Named Instance - `username:password@host:port`, `username:password@host/InstanceName`
- Enable mssql integrations
- Connect to mssql named instance to collect data. (Test by instance name and by port number)
- Connect to mssql default instance using default connection string and by port number.
> [microsoft_sqlserver] Establish Named instance connection by Instance Name

- packages/ti_cif3/changelog.yml
- packages/ti_cif3/data_stream/feed/fields/ecs.yml
- packages/ti_cif3/docs/README.md
- packages/ti_cif3/manifest.yml
- packages/ti_recordedfuture/changelog.yml
- packages/ti_recordedfuture/data_stream/threat/fields/ecs.yml
- packages/ti_recordedfuture/docs/README.md
- packages/ti_recordedfuture/manifest.yml
This uses the ECS definition of `threat.indicator.geo.location` to ensure that it is mapped as `geo_point`.
- Closes #4542
> ti_{cif3,recordedfuture}: map threat.indicator.geo.location as geo_point

- packages/log/changelog.yml
- packages/log/data_stream/log/agent/stream/stream.yml.hbs
- packages/log/data_stream/log/manifest.yml
- packages/log/manifest.yml
Closes https://github.com/elastic/integrations/issues/3432
This adds a field for custom tags and processors in the `logs` integration.
- [] I have verified that all data streams collect metrics or logs.
> Add custom processors and logs to log integration

- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/agent/stream/winlog.yml.hbs
- packages/winlog/data_stream/winlog/manifest.yml
- packages/winlog/manifest.yml
This adds the capacity for users to configure the providers list [available in Winlogbeat](https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-winlogbeat-options.html#_event_logs_provider).
- Closes #4547
> winlog: allow users to configure providers list

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/log/agent/stream/log.yml.hbs
- packages/microsoft_sqlserver/data_stream/log/manifest.yml
- packages/microsoft_sqlserver/manifest.yml
This adds an advanced configuration option to allow users to specify the text encoding to be used.
- Closes #4538
> micsosoft_sqlserver: allow text encoding configuration

- packages/aws/changelog.yml
- packages/aws/data_stream/waf/agent/stream/aws-s3.yml.hbs
- packages/aws/manifest.yml
Remove duplicate `content_type` from aws.waf.
Fixes #4587
- Fixes #4587
- Caused by: https://github.com/elastic/integrations/pull/4532
> [aws] Remove duplicate content_type from aws.waf

- .ci/Jenkinsfile
Removes the required steps of publishing into Package Storage V1. Specifically, publishing into snapshot stage with the command  `elastic-package publish`.
Packages will be just published into Package Storage V2.
To be merged after the switch to storage V2 is completed.
> Remove publish steps of packages into Package Storage v1

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/agent/stream/stream.yml.hbs
- packages/cisco_asa/data_stream/log/agent/stream/tcp.yml.hbs
- packages/cisco_asa/data_stream/log/agent/stream/udp.yml.hbs
- packages/cisco_asa/data_stream/log/manifest.yml
- packages/cisco_asa/manifest.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/agent/stream/stream.yml.hbs
- packages/cisco_ftd/data_stream/log/agent/stream/tcp.yml.hbs
- packages/cisco_ftd/data_stream/log/agent/stream/udp.yml.hbs
- packages/cisco_ftd/data_stream/log/manifest.yml
- packages/cisco_ftd/manifest.yml
This adds user configuration for internal and external zones. The logic for configured internal and external zones was already present but not used, for example [here](https://github.com/elastic/integrations/blob/f754dbe2c945613720c5895708b00bf48159227e/packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L1837-L1900) for FTD.
The format and logic of the config options is taken from the Checkpoint integration.
> cisco_{asa,ftd}: add configuration for internal and external zones

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/admin/manifest.yml
- packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/drive/manifest.yml
- packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/groups/manifest.yml
- packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/login/manifest.yml
- packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/saml/manifest.yml
- packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/user_accounts/manifest.yml
- packages/google_workspace/manifest.yml
- Uses last event date as cursor instead of current time  for better error recovery on agent crashes
- Supports all formats for last_event.id.time that are also supported as part of the pipelines
- Adds conditional to avoid showing errors on last page
- Fixes pagination logic by avoiding page == 0 conditions
> [google_workspace] Fix cursor value and pagination

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/apiserver/manifest.yml
- packages/kubernetes/data_stream/audit_logs/manifest.yml
- packages/kubernetes/data_stream/container/manifest.yml
- packages/kubernetes/data_stream/container_logs/manifest.yml
- packages/kubernetes/data_stream/controllermanager/manifest.yml
- packages/kubernetes/kibana/dashboard/kubernetes-f4dc26db-1b53-4ea2-a78b-1bfab8ea267c.json
- packages/kubernetes/manifest.yml
Fixes a typo in cluster overview ootb kubernetes dashboard.
Kubenretes---> Kubernetes
Integration---> integration
> Fix kubernetes typo in cluster overview dash

- packages/apache_spark/_dev/build/docs/README.md
- packages/apache_spark/changelog.yml
- packages/apache_spark/docs/README.md
- packages/apache_spark/manifest.yml
- Enhancement
Update README to explicitly add details for the end user to know that the Apache Spark integration uses Jolokia metricbeat module and hence, Jolokia needs to be set up as a third party dependency. Based on the documentation [link](https://spark.apache.org/docs/3.2.0/monitoring.html#component-instance--master), it can collect the metrics only when Spark is running standalone as master/worker.
- Move to integrations/packages/apache_spark directory.
- Relates #4523
> [apache_spark] Improvise README to explicitly call out the need for Spark to run standalone

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/manifest.yml
Updates kibana constraint to ^8.6 for 1.5.1
> Osquery_manager: Update kibana constraint to ^8.6 for 1.5.1

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/fields/agent.yml
- packages/netflow/data_stream/log/fields/ecs.yml
- packages/netflow/manifest.yml
- packages/netscout/changelog.yml
- packages/netscout/data_stream/sightline/fields/base-fields.yml
- packages/netscout/data_stream/sightline/fields/ecs.yml
- packages/netscout/manifest.yml
- packages/netskope/changelog.yml
- packages/netskope/data_stream/alerts/fields/agent.yml
- packages/netskope/data_stream/alerts/fields/ecs.yml
- packages/netskope/data_stream/events/fields/agent.yml
- packages/netskope/data_stream/events/fields/ecs.yml
- packages/netskope/docs/README.md
- packages/netskope/manifest.yml
- packages/o365/changelog.yml
- packages/o365/data_stream/audit/fields/agent.yml
- packages/o365/data_stream/audit/fields/ecs.yml
- packages/o365/manifest.yml
- packages/okta/changelog.yml
- packages/okta/data_stream/system/fields/agent.yml
- packages/okta/data_stream/system/fields/ecs.yml
- packages/okta/manifest.yml
This removes duplicate field definitions.
- For #4398
> netflow,netscout,netskope,o365,okta: remove duplicate fields

- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_container/manifest.yml
- packages/kubernetes/data_stream/state_cronjob/manifest.yml
- packages/kubernetes/data_stream/state_daemonset/manifest.yml
- packages/kubernetes/data_stream/state_deployment/manifest.yml
- packages/kubernetes/data_stream/state_job/manifest.yml
- packages/kubernetes/data_stream/state_node/manifest.yml
- packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
- packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
- packages/kubernetes/data_stream/state_pod/manifest.yml
- packages/kubernetes/data_stream/state_replicaset/manifest.yml
- packages/kubernetes/data_stream/state_resourcequota/manifest.yml
- packages/kubernetes/data_stream/state_service/manifest.yml
- packages/kubernetes/data_stream/state_statefulset/manifest.yml
- packages/kubernetes/data_stream/state_storageclass/manifest.yml
- packages/kubernetes/docs/README.md
- packages/kubernetes/manifest.yml
Enhancement
Enables Kube state metrics by default
Upgrade to 1.27.2 version and check if kube-state metrics is enabled by default
- Closes https://github.com/elastic/integrations/issues/4548
Logs:
Filebeat and Metricbeat started successfully:
```json
{"log.level":"info","@timestamp":"2022-11-15T09:54:20.257Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-11-15T09:54:21.170Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-11-15T09:54:21Z - message: Application: metricbeat--8.5.0[1a9c4b03-c1ba-458e-9557-8abef159c34f]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"} …
```
> Enabling kube-state metrics

- packages/microsoft_sqlserver/_dev/build/docs/README.md
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/performance/agent/stream/stream.yml.hbs
- packages/microsoft_sqlserver/data_stream/performance/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_sqlserver/data_stream/performance/fields/fields.yml
- packages/microsoft_sqlserver/data_stream/performance/manifest.yml
- packages/microsoft_sqlserver/data_stream/performance/sample_event.json
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
- Enhancement
This PR adds support for list of dynamic counter names.
Add Microsoft Sql Server integration, Enable performance metrics, give dynamic counter input and see the metrics for that counter in Kibana
- Closes #4432
> Support list of dynamic counter name.

- packages/logstash/changelog.yml
- packages/logstash/data_stream/node_stats/fields/fields.yml
- packages/logstash/data_stream/node_stats/fields/package-fields.yml
- packages/logstash/manifest.yml
Regression in mappings were introduced [in previous change](https://github.com/elastic/integrations/pull/4443)
- cluster_uuid was removed
- nested properties were updated to use an unsupported syntax - see relevant issue https://github.com/elastic/kibana/issues/138596
- build logstash package `elastic-package build`
- start a stack `elastic-package stack up -v -d --version 8.5.0-SNAPSHOT`
- start logstash service `elastic-package service up -v`
- install elasticsearch and logstash packages
- logstash appears in standalone and elasticsearch cluster
> [logstash] fix mappings

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
this is a [quick wins](https://docs.google.com/spreadsheets/d/1Bs-_nQkmab1be_6HYZi6B4gA1VSTAcWXYaPYMtmcwJ4/edit#gid=0) task
we want users to be able to search for KSPM and get our integration.
fleet UI looks at [these](https://github.com/elastic/kibana/blob/768d5b8b8c2465a2ee1d1f94c1b84ace168309b3/x-pack/plugins/fleet/public/applications/integrations/hooks/use_local_search.tsx#L14) fields (`title`, `name`)
so we update the title to include KSPM in it.
> add KSPM to integration name

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
- packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/manifest.yml
Add run_from property field as mentioned in https://github.com/elastic/kibana/issues/140564
> [Synthetics] Add run_from property

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-3d4d9290-bcb1-11ec-b64f-7dd6e8e82013.json
- packages/kubernetes/manifest.yml
Fix the title of the Pod memory usage panel to properly indicate how the "pct" is calculated.
Before:
After:
> Fix pod memory usage panel title

- packages/istio/manifest.yml
Revert release of Istio integration from GA back to Beta
- Relates #4253
> revert istio release from ga to beta

- .ci/Jenkinsfile
Running tests for all integrations after any merge launches dozens of jobs. If multiple branches
are merged in a short period of time, this can overload CI.
> Enable selective testing of integrations on main and backport branches

- .ci/Jenkinsfile
Follow up of https://github.com/elastic/integrations/pull/4683, current code generates empty diffs for a linear history, as is the case for main branch.
> Fix order of commits when checking if integration has changed in main branch

- packages/gcp/changelog.yml
- packages/gcp/data_stream/compute/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/compute/manifest.yml
- packages/gcp/data_stream/dataproc/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/dataproc/manifest.yml
- packages/gcp/data_stream/firestore/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/firestore/manifest.yml
- packages/gcp/data_stream/gke/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/gke/manifest.yml
- packages/gcp/data_stream/loadbalancing_metrics/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/loadbalancing_metrics/manifest.yml
- packages/gcp/data_stream/redis/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/redis/manifest.yml
- packages/gcp/data_stream/storage/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/storage/manifest.yml
- packages/gcp/manifest.yml
Add `regions` parameter to data streams.
It also updates Kibana min version to 8.5.0, as Metricbeat 8.5.0 is required for the underlying feature: https://github.com/elastic/beats/pull/32964
`regions` setting should be added to these data streams:
-
> [GCP] support multiple regions when gathering metrics

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-b945b7b0-bcb1-11ec-b64f-7dd6e8e82013.json
- packages/kubernetes/manifest.yml
Fixes https://github.com/elastic/integrations/issues/4537.
The issue exists for all k8s cluster that are not created with `kubeadm`. This means all cloud provider are affected. 
Since the information of `Control Plane` column is not crucial we can completely remove it since it makes the whole panel to brake in many cases.
> Fix broken k8s Nodes dashboard for CSPs

- .ci/Jenkinsfile
- .ci/schedule-daily.groovy
Add parameter to allow checking all the integrations independently of the latest commits. This will be used mainly to run the schedule-daily job.
> Add parameter to force checking all integrations

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
- packages/kubernetes/manifest.yml
Puts back the condition setting in `stream.yml.hbs` file of `container_logs` data_stream  added by https://github.com/elastic/integrations/commit/336cdfcbd08728a1a0ab1f3d946e9b7170c18a08  and which was removed accidentally when re-basing for https://github.com/elastic/integrations/pull/4363/files#diff-0357f29b430528695df420c2917a9cb06b6ade346ee0b1d71603e50befa1dcc2L7.
> Move back removed condition setting for container_logs

- packages/cisco_secure_endpoint/changelog.yml
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp-empty.log
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp-empty.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_secure_endpoint/manifest.yml
If there are no events for the 24 hour interval, the Cisco API endpoint returns an empty data array, and the ingest pipeline processor returns processor failures because of this.
Its better to drop the empty event rather than storing ingest failures.
> [Cisco_Secure_Endpoint] Add drop processor for empty events

- packages/atlassian_bitbucket/changelog.yml
- packages/atlassian_bitbucket/data_stream/audit/_dev/test/pipeline/test-audit-api-empty.log
- packages/atlassian_bitbucket/data_stream/audit/_dev/test/pipeline/test-audit-api-empty.log-expected.json
- packages/atlassian_bitbucket/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/atlassian_bitbucket/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/atlassian_bitbucket/manifest.yml
- packages/atlassian_confluence/changelog.yml
- packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-api-empty.log
- packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-api-empty.log-expected.json
- packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-cloud-empty.log
- packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-cloud-empty.log-config.yml
- packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-cloud-empty.log-expected.json
- packages/atlassian_confluence/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/atlassian_confluence/data_stream/audit/elasticsearch/ingest_pipeline/cloud.yml
- packages/atlassian_confluence/data_stream/audit/elasticsearch/ingest_pipeline/self-hosted.yml
- packages/atlassian_confluence/manifest.yml
- packages/atlassian_jira/changelog.yml
- packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-empty.log
- packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-empty.log-expected.json
- packages/atlassian_jira/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/atlassian_jira/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/atlassian_jira/manifest.yml
This drops messages that have a zero-length event list for the atlassian packages.
- Closes #4712
> atlassian_{bitbucket,confluence,jira}: fix handling of zero-length event lists

- packages/juniper_junos/changelog.yml
- packages/juniper_junos/data_stream/log/fields/agent.yml
- packages/juniper_junos/data_stream/log/fields/ecs.yml
- packages/juniper_junos/manifest.yml
- packages/juniper_netscreen/changelog.yml
- packages/juniper_netscreen/data_stream/log/fields/agent.yml
- packages/juniper_netscreen/data_stream/log/fields/ecs.yml
- packages/juniper_netscreen/manifest.yml
- packages/juniper_srx/changelog.yml
- packages/juniper_srx/data_stream/log/fields/ecs.yml
- packages/juniper_srx/manifest.yml
- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/log/fields/ecs.yml
- packages/m365_defender/manifest.yml
- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/fields/ecs.yml
- packages/microsoft_defender_endpoint/data_stream/log/fields/fields.yml
- packages/microsoft_defender_endpoint/manifest.yml
- packages/mimecast/changelog.yml
- packages/mimecast/data_stream/siem_logs/fields/ecs.yml
- packages/mimecast/data_stream/ttp_ap_logs/fields/ecs.yml
- packages/mimecast/data_stream/ttp_ip_logs/fields/ecs.yml
- packages/mimecast/data_stream/ttp_url_logs/fields/ecs.yml
- packages/mimecast/manifest.yml
- packages/modsecurity/changelog.yml
- packages/modsecurity/data_stream/auditlog/fields/agent.yml
- packages/modsecurity/manifest.yml
This removes duplicate field definitions from juniper_junos, juniper_netscreen, juniper_srx, m365_defender, microsoft_defender_endpoint, mimecast and modsecurity.
- For #4398
> juniper_*,m365_defender,microsoft_defender_endpoint,mimecast,modsecurity: remove duplicate fields

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
Fix the parse of flattened `process` fields in the default Falcon ingest pipeline.
- Closes #4707
> fix flattened process fields in default ingest pipeline

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
- packages/suricata/manifest.yml
Fixes #4723. Adds a defensive copy of the lists that we use from the params map, very much in the style of what was done previously in #3492.
- Closes #4723
- Relates elastic/elasticsearch#91977
> [suricata] Defensive copy of parameter lists

- packages/akamai/_dev/build/docs/README.md
- packages/akamai/changelog.yml
- packages/akamai/data_stream/siem/agent/stream/gcs.yml.hbs
- packages/akamai/data_stream/siem/manifest.yml
- packages/akamai/docs/README.md
- packages/akamai/manifest.yml
- Enhancement
Adds support for GCS input to the Akamai package.
- Closes #4291
> Add GCS input to Akamai

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
- packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/manifest.yml
fixes https://github.com/elastic/integrations/issues/4735
Type of change
- Bug
In https://github.com/elastic/integrations/pull/4673, the run_from fields were introduced to the synthetics integration. While these fields are meant to specify to heartbeat which location a monitor is run from, these fields currently interfere with the existing location name logic, causing the location name to become missing.
The solution is to add `run_from.geo.name` to ensure that the `observer.geo.name` properly is indexed correctly.
1. Check out this PR
2. Navigate to `packages/synthetics`
3. Run `elastic-package clean` then `elastic-package build`
4. In the same directory, run `elastic-package stack up --version 8.5.0-SNAPSHOT -v`
5. Navigate to `https://localhost:5601` and log in.
6. Navigate to Uptime …
> [Synthetics] add run_from.geo.name field

- packages/httpjson/changelog.yml
- packages/httpjson/manifest.yml
Minor clean-up to the docs page. Probably not worth a version bump; will be picked up with the next significant change.
> httpjson: remove leftover single quote

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-b945b7b0-bcb1-11ec-b64f-7dd6e8e82013.json
- packages/kubernetes/manifest.yml
Fix the function to calculate pod memory usage.
Since, the total memory node used in the function was  `kubernetes.node.memory.allocatable.bytes`, every memory used by system daemons was not being considered. Changing it to `kubernetes.node.memory.capacity.bytes` fix problems like the one mentioned in elastic/integrations#4577.
Before:
After:
> [Metrics Kubernetes] Nodes: Fix memory usage by node

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
In the following PR we are introducing CSPM policy template with AWS
For fully testing it, you should test with the following kibana changes: https://github.com/elastic/kibana/pull/146842
-
> [Cloud Posture] Introducing cspm

- packages/log/changelog.yml
Looks like I had a copy-and-paste issue when I opened https://github.com/elastic/integrations/pull/4568
This just changes the `changelog.yml` entry so it points at the correct PR, which is apparently used to generate docs.
> Fix PR URL in changelog

- packages/azure_application_insights/changelog.yml
- packages/azure_application_insights/data_stream/app_state/fields/fields.yml
- packages/azure_application_insights/docs/README.md
- packages/azure_application_insights/docs/app_state.md
- packages/azure_application_insights/manifest.yml
Fix a misspelling in the field name `azure.app_state.browser_timings_receive_[d]uration` that was causing an error during Lens editing.
- Closes #4753
> Azure App Insights: fix misspelled field name in app_state data stream

- packages/aws/_dev/build/docs/kinesis.md
- packages/aws/changelog.yml
- packages/aws/data_stream/kinesis/manifest.yml
- packages/aws/docs/kinesis.md
- packages/aws/manifest.yml
This PR is to adjust Kinesis integration documentation to specify that this integration is to collect metrics for Kinesis Data Streams from CloudWatch.
- Relates https://github.com/elastic/integrations/issues/4757
> [AWS] Change Kinesis integration documentation to Kinesis Data Stream

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
- packages/panw/manifest.yml
- Add a foreach processor to handle appending host.ip values to related.ip when it is an array. The if statement on this new processor verifies that host.ip is an instance of List. Changed the if statement on the related append processor to check if host.ip is an instance of String.
- Add pipeline tests
```
cd packages/panw && elastic-package test
```
- Relates elastic/sdh-beats#2818
> [panw] Fix handling of related.ip when host.ip is an array

- .ci/Jenkinsfile
- packages/elastic_package_registry/docs/README.md
This PR checks whether or not there is an error when building a package before publishing it to package storage. If there is any error, that package will be skipped (i.e. outdated README).
It has been added `elastic-package check` command. This command fails if the package has any error. Other packages with no errors will still be published.
Example:
- Forced this scenario by checking just two packages, and of them has an outdated README  `packages/elastic_package/registry/docs/README.md`
- Outcome: Package with the outdated README has not been built.
- Output: https://fleet-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/branches/PR-4812/runs/7/nodes/154/log/?start=0
> Add check command before building and publishing packages

- packages/okta/changelog.yml
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/manifest.yml
This ensures that already-set event.original documents can still be ingested.
- Closes #4782
> okta: handle already set event.original more robustly

- .ci/Jenkinsfile
This PR adds a method to obtain the kibana version condition independently on how it is defined in the YAML manifest file.
Example of the version value retrieved when manifest YAML is flattened ([link](https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-4838/5/consoleText)):
- that `null` was to check there was no error when accessing elements that are not in the map.
```
[2022-12-15T13:20:37.537Z] [Pipeline] readYaml
[2022-12-15T13:20:37.572Z] [Pipeline] echo
[2022-12-15T13:20:37.572Z] Manifest flattened version: ^7.16.0 || ^8.0.0 - null
[2022-12-15T13:20:37.586Z] [Pipeline] sh
[2022-12-15T13:20:37.615Z] + egrep -v ^(packages/|.github/CODEOWNERS)
[2022-12-15T13:20:37.615Z] + git merge-base origin/main 0e378fe25e932ec6d8234218cc902fa4e36d1f4d
[2022-12-15T13:20:37.615Z] …
```
> Check kibana version prepare stack

- packages/aws_logs/changelog.yml
- packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs
- packages/aws_logs/data_stream/generic/manifest.yml
- packages/aws_logs/manifest.yml
This PR is to add `latency` config parameter into aws-cloudwatch input. During testing, I found we are also missing the `number_of_workers` parameter too.
Here is what the agent policy looks like after installing the integration with specifying `latency`:
```
inputs:
- id: aws-cloudwatch-aws_logs-bcb0ad28-0671-41af-bc9a-9657b6d40f3e
name: aws_logs-1
revision: 1
type: aws-cloudwatch
meta:
package:
name: aws_logs
version: 0.3.2
data_stream:
streams:
- id: aws-cloudwatch-aws_logs.generic-bcb0ad28-0671-41af-bc9a-9657b6d40f3e
data_stream:
dataset: aws_logs.generic
log_group_arn: >-
arn:aws:logs:eu-west-1:123456789:log-group:/aws/lambda/apm-test-api-gateway-v1:*
start_position: beginning
scan_frequency: 1m
api_sleep: 200ms
latency: 30m
access_key_id: a …
```
> [Custom AWS Logs] Add latency config parameter into aws-cloudwatch input

- packages/lastpass/changelog.yml
- packages/lastpass/data_stream/detailed_shared_folder/elasticsearch/ingest_pipeline/default.yml
- packages/lastpass/data_stream/detailed_shared_folder/sample_event.json
- packages/lastpass/data_stream/event_report/_dev/test/pipeline/test-event-report.log
- packages/lastpass/data_stream/event_report/_dev/test/pipeline/test-event-report.log-expected.json
- packages/lastpass/data_stream/event_report/elasticsearch/ingest_pipeline/default.yml
- packages/lastpass/data_stream/event_report/sample_event.json
- packages/lastpass/data_stream/user/elasticsearch/ingest_pipeline/default.yml
- packages/lastpass/data_stream/user/sample_event.json
- packages/lastpass/docs/README.md
- packages/lastpass/kibana/dashboard/lastpass-45d2e670-244b-11ed-80ca-25e921dc7ac2.json
- packages/lastpass/manifest.yml
Type of change
- Enhancement
- Due to changes in the LastPass API response, few conditions in the event report pipeline is updated.
- Add support for category `Failed login` event.
- Add support for `event.outcome` field.
- Move to integrations/packages/lastpass directory.
- Closes #4839
- Closes #4771
- Closes #4776
> [Enhancement] [LastPass] Add support for `event.outcome` field and new type of `event.action`

- packages/ti_otx/changelog.yml
- packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-empty-ndjson.log
- packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-empty-ndjson.log-expected.json
- packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-sample-ndjson.log
- packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-sample-ndjson.log-expected.json
- packages/ti_otx/data_stream/threat/agent/stream/httpjson.yml.hbs
- packages/ti_otx/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/ti_otx/data_stream/threat/sample_event.json
- packages/ti_otx/docs/README.md
- packages/ti_otx/manifest.yml
When OTX returns a count of 0, we should drop the empty documents
> [TI OTX] Adding drop for empty documents

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/kibana/index_pattern/cloud_security_posture-303eea10-c475-11ec-af18-c5b9b437dbbe.json
- packages/cloud_security_posture/kibana/index_pattern/cloud_security_posture-9129a080-7f48-11ec-8249-431333f83c5f.json
- packages/cloud_security_posture/manifest.yml
In https://github.com/elastic/integrations/pull/4804 we used lower version the the latest in order to indicate the change is for previous stack version. It seems wrong way (new pr to snapshot EPR wasn't created) - this PR only promote the version to be higher than before.
> [Cloud Posture] support spaces 8.6.0 - fix

- packages/microsoft_sqlserver/_dev/build/docs/README.md
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/agent/stream/stream.yml.hbs
- packages/microsoft_sqlserver/data_stream/transaction_log/manifest.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/sample_event.json
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
- Enhancement
The MSSQL Integration currently loads "transaction_log metrics" from system dbs.
This PR has updated the integration to load "transaction_log metrics" from the user dbs by providing the list of databases for which the metrics is to be collected.
Also, this PR fixes the bug in the query for fetching metrics from sys.dm_db_log_space_usage.
Add the microsoft_sql_server integration, add server config, enable transaction_log metrics and verify the data.
Also, for the metrics from sys.dm_db_log_space_usage table, specify the list of databases.
- Relates #4108 
- Closes #4690
> Support user databases for transaction log

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/mongodb/data_stream/log/sample_event.json
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
This PR address the SDH on mongodb log data stream 
- Clone the PR.
- Run the elastic-package stack up command.
- Add the mongoDb integration.
- In Integration UI provide the mongod.log path and enable the preserve original event.
- Enrol the elastic agent.
- Closes #4836
> [MongoDB] Added remove processors in ingest pipeline for log datastream

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Today CSPM 1.1.1 version referring for package that support 8.6.0  and 1.1.2 supports 8.7.0. 
This PR update the current version (support 8.7.0) to 1.2.0 in order to use the minor digit to distinguish between the two.
> [Cloud Posture] update minor version for indicating 8.7.0

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/elastic_agent_logs/fields/fields.yml
- packages/elastic_agent/manifest.yml
Adds new mapping fields to the elastic_agent logs data stream for the individualized `component` fields to allow for searching and filtering for logs on a particular agent component.
Future follow ups will add new visualizations for things like top unhealthy input and output messages, top unhealthy input types, unhealthy output types etc.
I'm keeping this compatible with older Kibana versions as it will not break older stacks and allows us to continue to ship new dashboards and fixes to older stack versions.
- Related to https://github.com/elastic/elastic-agent/issues/1954
Logs can be filtered by things like the individual component that produced them:
> Add mappings for components in elastic_agent logs

- packages/aws_logs/changelog.yml
- packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
- packages/aws_logs/data_stream/generic/manifest.yml
- packages/aws_logs/manifest.yml
Because of the `unless` statements in the AWS config template, it is not possible to set worker count when using `non_aws_bucket_name`.
Worker count is a required field, so this will fail.
I also added a default value just in case people forget about the setting.
> [AWS_Logs] Add support for worker count in non_aws_bucket settings

- packages/auditd_manager/changelog.yml
- packages/auditd_manager/data_stream/auditd/agent/stream/auditd.yml.hbs
- packages/auditd_manager/data_stream/auditd/manifest.yml
- packages/auditd_manager/manifest.yml
Adds the `audit_rule_files` option.
> [auditd_manager] Add audit rule files option to auditd_manager

- packages/istio/changelog.yml
- packages/istio/data_stream/istiod_metrics/_dev/test/system/test-default-config.yml
- packages/istio/data_stream/istiod_metrics/agent/stream/stream.yml.hbs
- packages/istio/data_stream/istiod_metrics/manifest.yml
- packages/istio/manifest.yml
Remove need for autodiscovery to monitor Istiod service.
1. Setup Istio by following the steps at https://github.com/elastic/integrations/pull/3632
2. create a data view for the index pattern `metrics-istio.istiod*`
3. Switch to Discover and select the data view created at step 2
4. Check the field `error.message` is empty for all metric events. 
5. Add a filter `istio.istiod.metrics.pilot_inbound_updates.counter: exists` to view a sample of the dataset for one of the metrics used in the `[Metrics Istio] Overview` dashboard
6. Check the dashboard `[Metrics Istio] Overview` has no errors and some actual data.
- Relates #4678
> Remove need for autodiscovery to monitor Istiod service.

- packages/vsphere/changelog.yml
- packages/vsphere/data_stream/host/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/manifest.yml
- Bug
- Closes https://github.com/elastic/integrations/issues/4927
> Change cpu and memory calculation in vsphere

- packages/okta/changelog.yml
- packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/data_stream/system/fields/fields.yml
- packages/okta/data_stream/system/sample_event.json
- packages/okta/docs/README.md
- packages/okta/manifest.yml
Makes okta.debug_context.debug_data.risk_reasons visible to search.
- For elastic/beats#33677.
> okta: make okta.debug_context.debug_data.risk_reasons visible to search

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
- packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/auditd/data_stream/log/fields/fields.yml
- packages/auditd/docs/README.md
- packages/auditd/manifest.yml
Audit messages may contain spaces when the value is quoted, so let the kv processor know how to deal with this case.
- For elastic/beats#22587
> auditd: teach kv about quoted spaces

- packages/beat/changelog.yml
- packages/beat/data_stream/state/agent/stream/stream.yml.hbs
- packages/beat/data_stream/stats/agent/stream/stream.yml.hbs
- packages/beat/manifest.yml
Add `ssl` configuration options for elasticsearch integration module
- Applied changes locally, and used [elastic-package](https://github.com/elastic/elastic-package) to spawn up a complete stack locally.
- Made sure the new fields are visible in the UI as below:
- Checked that the policy has the new fields mapped properly
- Spawned an Elastic agent locally and checked the matribeat logs to make sure that it initially fails when connecting to ES and then succeeds to establish a connection to ES when ssl configuration are passed properly
- subtask of [#4666 ](https://github.com/elastic/integrations/issues/4666)
> [Beats] Added ssl config support to beats module

- packages/kibana/changelog.yml
- packages/kibana/data_stream/cluster_actions/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/cluster_rules/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/node_actions/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/node_rules/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/stats/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/status/agent/stream/stream.yml.hbs
- packages/kibana/manifest.yml
Add `ssl` configuration options for kibana integration module
- Applied changes locally, and used [elastic-package](https://github.com/elastic/elastic-package) to spawn up a complete stack locally.
- Made sure the new fields are visible in the UI as below:
- Checked that the policy has the new fields mapped properly
- Spawned an Elastic agent locally and checked the matribeat logs to make sure that it initially fails when connecting to ES and then succeeds to establish a connection to ES when ssl configuration are passed properly
- subtask of [#4666 ](https://github.com/elastic/integrations/issues/4666)
> [Kibana] Added ssl config support to kibana module

- packages/linux/changelog.yml
- packages/linux/data_stream/service/agent/stream/stream.yml.hbs
- packages/linux/manifest.yml
Fixes https://github.com/elastic/integrations/issues/4882
This properly formats the `state_filter` and `pattern_filter` fields.
> Fix filters in linux/services

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/manifest.yml
Adds a network fetcher to the agent config.
-
> Cloud Security - Add a network fetcher to the AWS CSPM config

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/manifest.yml
Support OPA decision log fields in the fleet UI log screen.
Resolves https://github.com/elastic/cloudbeat/issues/533
-
> Cloudbeat decision logs fields

- packages/salesforce/changelog.yml
- packages/salesforce/data_stream/login_rest/agent/stream/httpjson.yml.hbs
- packages/salesforce/data_stream/logout_rest/agent/stream/httpjson.yml.hbs
- packages/salesforce/manifest.yml
In the current Salesforce Integration, we don’t have pagination support for login-rest and logout-rest data streams. So if in any case, we have a response body with more than 2000 records, the next page is never called and the data will not be fetched.
Solution:
You can request the next batch of records using the provided URL with your instance and session information, and repeat until all records have been retrieved. These requests use `nextRecordsUrl` and don’t include any parameters. The final batch of records doesn’t have a `nextRecordsUrl` field and return `true` value for field `done`
- Relates #3940 
- Relates #4261
- Relates #4323
> [Salesforce] Add pagination support for login_rest and logout_rest data streams

- packages/prometheus/changelog.yml
- packages/prometheus/manifest.yml
remove duplicated "Integration" from the integration package name, that impact naming in documentation - https://docs.elastic.co/integrations/prometheus
-
> [Prometheus] remove Integration from the package name

- packages/docker/changelog.yml
- packages/docker/data_stream/container_logs/manifest.yml
- packages/docker/manifest.yml
This PR adds a new line to the conditions form of the Docker package, linking to the available keys.
> [Metrics][Docker] Add link to Docker available keys

- packages/lyve_cloud/changelog.yml
They lyve_cloud changelog entry points to the wrong PR. This PR updates the changelog to point to the correct PR.
> Fix lyve_cloud changelog

- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/agent/stream/httpjson.yml.hbs
- packages/microsoft_defender_endpoint/data_stream/log/manifest.yml
- packages/microsoft_defender_endpoint/manifest.yml
Some customers uses a different Oauth2 authentication flow, so I will keep the original Azure resource implementation while adding the optional support for Oauth2 scopes.
When a scope is defined, it will negate these two lines in httpjson:
```
auth.oauth2.provider: azure
auth.oauth2.azure.resource: {{azure_resource}}
```
The reason for this is the difference in Oauth2 flow, and the expected URL parameters and POST body format used. The earlier API versions was dependent on the concept of providing resources, and the provider parameter is simply used by the Golang Oauth2 library to provide certain Azure specific features.
Once the API changed, it now only requires Oauth2 scopes to provided instead of resources. We still want to support both for the people that are still using the old …
> [Microsoft_defender_endpoint] Add support for Oauth2 scopes

- docs/dashboard_guidelines.md
- docs/generic_guidelines.md
- move dashboard guidelines to separate file
- add guideline around visualisation by value
Updating guidelines to reflect the guideline to use visualisations by value is part of https://github.com/elastic/integrations/issues/3448.  
I went a step forward and also moved dashboard guidelines to a new file, to help discovery and clarity of content.
-
> Dashboard guidelines: use by value

- packages/dga/_dev/build/docs/README.md
- packages/dga/changelog.yml
- packages/dga/docs/README.md
- packages/dga/kibana/ml_module/dga-ml.json
- packages/dga/kibana/security_rule/170b35d4-d944-4264-a8ca-3118ae2e1534.json
- packages/dga/kibana/security_rule/64116bb2-0f2c-4cf6-9df4-9973452b4d4b.json
- packages/dga/kibana/security_rule/997ec71d-bddc-4513-b6f1-193f601fd420.json
- packages/dga/kibana/security_rule/a020dadb-3da2-4252-91e9-b0fc148823e2.json
- packages/dga/manifest.yml
- packages/problemchild/_dev/build/docs/README.md
- packages/problemchild/changelog.yml
- packages/problemchild/docs/README.md
- packages/problemchild/kibana/ml_module/problemchild-ml.json
- packages/problemchild/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
- packages/problemchild/kibana/security_rule/415d6863-7676-401f-aa8d-62f59a28e849.json
- packages/problemchild/kibana/security_rule/86d57ec4-ace5-4456-8145-02e6f0cdd71a.json
- packages/problemchild/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
- packages/problemchild/kibana/security_rule/9b98d945-2cce-45e5-aa84-4b021af0e153.json
- packages/problemchild/kibana/security_rule/a5cb4cd7-ba05-47e8-a815-f95c21719ded.json
- packages/problemchild/kibana/security_rule/ae7c2f69-0c51-4b02-ad54-d3d75023da8b.json
- packages/problemchild/kibana/security_rule/ff590871-371b-468f-8cd8-2876b54c53bd.json
- packages/problemchild/manifest.yml
* #4820
* In this PR, we are not shipping dashboards
-
> Quality of life updates to ProblemChild and DGA packages

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.3.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cb77d7b0af952de9178cf8476731efc3f5e58aa2
* https://github.com/elastic/ia-trade-team/issues/91
None
> [Security Rules] Update security rules package to v8.3.4

- docs/developer_workflow_design_build_test_integration.md
- docs/tips_for_building_integrations.md
Add information about package compatibility with stack/beats version
-
> Add a note regarding kibana.version

- docs/dashboard_guidelines.md
Add a new subsection in the "[Dashboards guidelines](https://github.com/elastic/integrations/blob/main/docs/dashboard_guidelines.md)" doc to include recommendation/best practices of using pre-filters in visualizations.
- Relates #4936
> Add a section about pre-filters in visualizations

- .github/CODEOWNERS
- packages/tomcat/manifest.yml
With the agreement of the service integrations team, they will take ownership of the Apache Tomcat package.
> [Tomcat] - change owner to obs service integrations team

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_cronjob/fields/base-fields.yml
- packages/kubernetes/data_stream/state_cronjob/sample_event.json
- packages/kubernetes/data_stream/state_daemonset/fields/base-fields.yml
- packages/kubernetes/data_stream/state_daemonset/sample_event.json
- packages/kubernetes/data_stream/state_deployment/fields/base-fields.yml
- packages/kubernetes/data_stream/state_deployment/sample_event.json
- packages/kubernetes/data_stream/state_job/fields/base-fields.yml
- packages/kubernetes/data_stream/state_job/sample_event.json
- packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/base-fields.yml
- packages/kubernetes/data_stream/state_persistentvolumeclaim/sample_event.json
- packages/kubernetes/data_stream/state_replicaset/fields/base-fields.yml
- packages/kubernetes/data_stream/state_replicaset/sample_event.json
- packages/kubernetes/data_stream/state_statefulset/fields/base-fields.yml
- packages/kubernetes/data_stream/state_statefulset/sample_event.json
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
In https://github.com/elastic/beats/pull/33763 namespace metadata was added to all namespaced resources
-
> Add missing namespace_uid and namespace_labels fields

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/fields/rule.yml
- packages/cloud_security_posture/manifest.yml
Adds a new `rule.benchmark.posture_type` field to the mapping.
> [Cloud Posture] Add posture_type field to mapping

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.4.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/545122a6eac0cc7dcef9dfb0073edb4fd1033370
* https://github.com/elastic/ia-trade-team/issues/91
None
> [Security Rules] Update security rules package to v8.4.2

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/o365/manifest.yml
- Added a fingerprint processor to prevent duplicate events from being ingested. It generates a hash based on the o365audit field.
- Closes #5046
> [O365] Add fingerprint processor to prevent ingestion of duplicate events

- .github/CODEOWNERS
- packages/microsoft_sqlserver/manifest.yml
- packages/oracle/manifest.yml
The obs-service-integrations team will take ownership of the oracle and microsoft_sqlserver packages.
> [oracle,microsoft_sqlserver] - change owner to obs-service-integrations

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/manifest.yml
Add cloudtrail fetcher to CIS AWS hbs file
-
> Cloud Security - Add cloudtrail fetcher to CIS AWS hbs file

- packages/kubernetes/_dev/deploy/k8s/cluster-role-binding.yaml
- packages/kubernetes/_dev/deploy/k8s/cluster-role.yaml
- packages/kubernetes/_dev/deploy/k8s/deployment.yaml
- packages/kubernetes/_dev/deploy/k8s/service-account.yaml
- packages/kubernetes/_dev/deploy/k8s/service.yaml
Updates kube state metrics to the latest version, as the current one `2.3.0` is no longer supported by any of the K8s version the integration supports.
-
> [Kubernetes] Update kube state metrics version

- packages/windows/changelog.yml
- packages/windows/data_stream/perfmon/agent/stream/stream.yml.hbs
- packages/windows/data_stream/perfmon/manifest.yml
- packages/windows/manifest.yml
Adds support for the custom processor definition in windows perfmon.
> [Windows] Added support for custom processors on perfmon

- packages/nginx_ingress_controller/changelog.yml
- packages/nginx_ingress_controller/data_stream/access/manifest.yml
- packages/nginx_ingress_controller/data_stream/error/manifest.yml
- packages/nginx_ingress_controller/manifest.yml
After 8.6.0, kubernetes pod labels used for condition matching are not dedoted. 
PR that introduced this is https://github.com/elastic/elastic-agent/pull/1398
So the `nginx_ingress_controller` integration needs to be updated with the correct defaults for conditions used to match the ingress-nginx pod.
1. Set up an elastic-stack of 8.6.0 version
2. Set up kubernetes cluster and  ingress-nginx following https://kind.sigs.k8s.io/docs/user/ingress/
3.  Install 1.7.0 versions of  nginx_ingress_controller package
4. Run agent with the correct policy
5. Check logs being collected
> [NGINX] After 8.6.0, kubernetes pod labels used for condition matching are not dedoted

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/fields/ecs.yml
- packages/cloud_security_posture/manifest.yml
Adds cloud fields to the cloud security posture event fields:
- `cloud.account.id`
- `cloud.account.name`
- `cloud.provider`
Related to https://github.com/elastic/cloudbeat/issues/586
> [Cloud Posture] Add cloud fields to mapping

- .github/ISSUE_TEMPLATE/integration-checklist.md
Adding link  to the documentation guidelines in the integration template in order to make folks more aware of this document.
> Update doc guidelines in integration release template

- packages/mysql/changelog.yml
- packages/mysql/data_stream/performance/elasticsearch/ingest_pipeline/default.yml
- packages/mysql/data_stream/performance/sample_event.json
- packages/mysql/manifest.yml
- Enhancement
This PR is updating ingest pipeline for the performance data stream of mysql,
so that processor exits quietly when the field mysql.performance.events_statements.last.seen does not exist.
Add the mysql integration and ingest document without last.seen field for performance data stream and it should not give any error.
- Closes [17542](https://github.com/elastic/enhancements/issues/17542)
> [mysql] Update ingest pipeline for performance datastream

- packages/iis/changelog.yml
- packages/iis/data_stream/application_pool/agent/stream/stream.yml.hbs
- packages/iis/manifest.yml
- Bug
Create multiple application pools in IIS Manager
Verify all the application pool metrics are getting captured.
Specify names in the application pool configuration and verify whether only those metrics are being captured.
- Closes #4445
> [IIS] Accept multiple application_pool name

- packages/rabbitmq/_dev/build/docs/README.md
- packages/rabbitmq/changelog.yml
- packages/rabbitmq/data_stream/log/_dev/test/pipeline/test-rabbitmq.log
- packages/rabbitmq/data_stream/log/_dev/test/pipeline/test-rabbitmq.log-expected.json
- packages/rabbitmq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/rabbitmq/docs/README.md
- packages/rabbitmq/manifest.yml
- Enhancement
This PR supports RabbitMQ  new timestamp format with nanosecond precision and timezone "2022-03-23 13:16:58.000369+03:00".
Previous timestamp format "2019-04-12 10:11:15.094".
New DATETIME pattern is replaced by TIMESTAMP_ISO8601.
- Relates #2905
> [RabbitMQ] Add support for new timestamp format

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepointfileop-events.json
- packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepointfileop-events.json-expected.json
- packages/o365/data_stream/audit/_dev/test/pipeline/test-sp-sharing-op-events.json-expected.json
- packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/o365/data_stream/audit/sample_event.json
- packages/o365/docs/README.md
- packages/o365/manifest.yml
Adds "SharePointSharingOperation" to event codes that have file, directory and URL details retained in ECS fields.
- Closes #5064
> o365: retain file, directory and URL details for SharePointSharingOperation

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-sysmon-operational-events.json-expected.json
- packages/windows/data_stream/perfmon/manifest.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/fields/winlog.yml
- packages/windows/data_stream/sysmon_operational/sample_event.json
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Adds the field ` winlog.event_data.TargetProcessGUID`  of type `keyword` to sysmon_operational. 
DATA example
<details>
```json
{
"is_partial" : false,
"is_running" : false,
"took" : 66,
"timed_out" : false,
"hits" : {
"total" : {
"value" : 1,
"relation" : "eq"
},
"sequences" : [
{
"join_keys" : [
"747f3d96-68a7-43f1-8cbe-e8d6dadd0358",
"{747f3d96-feac-6174-0000-0010fb029a00}",
"{747f3d96-feae-6174-0000-00106ad39a00}"
],
"events" : [
{
"_index" : ".ds-logs-windows.sysmon_operational-default-2021.10.23-000001",
"_id" : "7RECsXwBE6i8IeLQ59M9",
"_source" : {
"agent" : {
"hostname" : "MSEDGEWIN10",
"name" : "MSEDGEWIN10",
"id" : "b79edb1f-7b68-4a66-8a9e-c679030c1d8e",
"ephemeral_id" : "d085494b-52ea-4845-a4b1-46381c2243c7",
"type" : "filebeat",
"version" : "7.15.0"
},
"process" : {
"args" : [ …
```
> [Windows] Add additional fields to windows package system_operational integration

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/manifest.yml
Add `aws-monitoring` fetcher to aws hbs file
Related https://github.com/elastic/csp-security-policies/issues/148
> feat: add monitoring fetcher

- packages/system/changelog.yml
- packages/system/data_stream/cpu/fields/agent.yml
- packages/system/data_stream/load/fields/agent.yml
- packages/system/data_stream/memory/fields/agent.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
We are in the progress of starting to adopt TSDB. To enabled TSDB, dimension fields are required. In this PR, dimensions are added to the following dataset:
* system.cpu
* system.load
* system.memory
The dimensions that were selected are:
* agent.id
* container.id
* host.name
* cloud.instance.id
These 4 dimensions should set a good foundation for the dataset selected above. It should make it work well in host, cloud and container environments. Not all dimensions always have to exist. We still need to define a more generic set of dimensions for integrations.
The goal of this PR is to enable us testing TSDB on common dataset. It also allows Kibana developers to have dataset ready for testing.
As long as TSDB is not enabled and on older versions of the stack, this change will not have any …
> [System] Update cpu, load, memory dataset with dimensions

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_service/_dev/test/system/test-default-config.yml
- packages/kubernetes/manifest.yml
Add system testing for state service datastream.
Unlike the other `state_*` datastreams, the `_dev` folder needed for that test was missing.
> [Kubernetes] Add system testing for state service

- packages/lyve_cloud/changelog.yml
- packages/lyve_cloud/manifest.yml
The Lyve Cloud changelog was fixed in https://github.com/elastic/integrations/pull/4991. I didn't know that you also have to bump the version for changes to make it into EPR. The PR bumps the version to 1.0.1.
> Bump lyve_cloud version

- packages/fim/changelog.yml
- packages/fim/data_stream/event/agent/stream/file_integrity.yml.hbs
- packages/fim/manifest.yml
- Bug
Fixes for a SDH involving a duplicate key issue which prevented processors from being added in the config.
- Relates https://github.com/elastic/sdh-beats/issues/3018
> [fim] Fix for duplicate processor key

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
- packages/elastic_agent/kibana/lens/elastic_agent-27798780-0037-11ec-af6c-1740f74b2d73.json
- packages/elastic_agent/kibana/lens/elastic_agent-409f5d70-0037-11ec-af6c-1740f74b2d73.json
- packages/elastic_agent/kibana/lens/elastic_agent-58677820-0037-11ec-af6c-1740f74b2d73.json
- packages/elastic_agent/kibana/lens/elastic_agent-6e88c0a0-0037-11ec-af6c-1740f74b2d73.json
- packages/elastic_agent/kibana/visualization/elastic_agent-47d87552-8421-4cfc-bc5d-4a7205f5b007.json
- packages/elastic_agent/kibana/visualization/elastic_agent-69219f50-febc-11eb-9a5b-19cc90b68e55.json
- packages/elastic_agent/kibana/visualization/elastic_agent-819241d0-0037-11ec-af6c-1740f74b2d73.json
- packages/elastic_agent/kibana/visualization/elastic_agent-93a8a11d-b2da-4ef3-81dc-c7040560ffde.json
- packages/elastic_agent/kibana/visualization/elastic_agent-a11c250a-865f-4eb2-9441-882d229313be.json
- packages/elastic_agent/manifest.yml
Add data_stream.dataset=elastic_agent.elastic agent for agent visualizations in elastic agent metrics dashboard and data_stream.dataset=elastic_agent.* for beats visualizations.
Add filters to visualizations on elastic agent metrics dashboard.
Build the elastic agent extension and bring up the integration stack with 
`elastic-package build && elastic-package stack up -d -v` 
and go to [Elastic agent dashboard](https://localhost:5601/app/dashboards#/view/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395) 
Click edit and notice like all the panels have a filter icon on the top right corner
If we edit a graph we can see the filter applied on dataset (it's the same for all panels of this type)
Beat Lens visualization are slightly different, for example:
- Relates #4936
> Add filters to elastic agent visualizations

- packages/system/changelog.yml
- packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
- packages/system/kibana/dashboard/system-Metrics-system-overview.json
- packages/system/manifest.yml
Added `dataset` filters for system metrics dashboards
- Closes #4936
> System dashboards add filters

- packages/beat/data_stream/stats/fields/fields.yml
- packages/beat/docs/README.md
Adds recently created [APM server fields](https://github.com/elastic/apm-server/commit/2e58ae3ad343b6520a5aef047b50e2bc019ddab1#diff-20f700df6ec50fcbecb398cba4104ea382244cc68006978dcde3a107b5e12b7cR254) to the mappings
Closes [#5225](https://github.com/elastic/integrations/issues/5225)
> [beat] Add new apm_server fields

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/docs/README.md
- packages/cloud_security_posture/manifest.yml
This PR is adding a paragraph in our integration README, that the cloud security posture plugin support installation only using the `default` namespace.
Only readme changes.
This PR will be back-ported to our CSP integration on Kibana 8.6.
- Relates https://github.com/elastic/security-team/issues/5831
- https://github.com/elastic/integrations/pull/5211
> [Cloud Security] - Updating readme documentation with the supported namespace - backporting Kibana 8.5

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/docs/README.md
- packages/cloud_security_posture/manifest.yml
This PR is adding a paragraph in our integration README, that the cloud security posture plugin support installation only using the `default` namespace.
This PR will be back-ported to our CSP integration on Kibana 8.6. 
Only readme changes.
- Relates https://github.com/elastic/security-team/issues/5831
- https://github.com/elastic/integrations/pull/5209
> [Cloud Security] - Updating readme documentation with the supported namespace - backporting Kibana 8.6

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.4.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/718c39183f7c129abb911b0768d948d2b8784521
* https://github.com/elastic/ia-trade-team/issues/100
None
> [Security Rules] Update security rules package to v8.4.3

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d1a27608abc97fa517445ccc07ea05132cc00ade
* https://github.com/elastic/ia-trade-team/issues/100
None
> [Security Rules] Update security rules package to v8.5.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.1-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8e283cea844bfebbac9d63ad4d622148b7383e75
None
None
> [Security Rules] Update security rules package to v8.6.1-beta.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8e283cea844bfebbac9d63ad4d622148b7383e75
* https://github.com/elastic/ia-trade-team/issues/100
None
> [Security Rules] Update security rules package to v8.6.1

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
GCP and Azure inputs weren't mapped to any stream.
This caused the fleet to crash due to it being unable to find `stream.yml.hbs` that it assigns by default in such cases.
- Closes https://github.com/elastic/kibana/issues/151062
> Assign streams to inputs

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/kibana/security_rule/a198fbbd-9413-45ec-a269-47ae4ccf59ce.json
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.1-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/79f51c42c056f5ca88484b4af729596e248e22b4
None
None
> [Security Rules] Update security rules package to v8.7.1-beta.1

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Fixing the syntax of the manifest beta version
> Fixing beta version syntax

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/79f51c42c056f5ca88484b4af729596e248e22b4
* https://github.com/elastic/kibana/pull/151152
* https://github.com/elastic/ia-trade-team/issues/100
> [Security Rules] Update security rules package to v8.7.1

- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/fields/ecs.yml
- packages/winlog/docs/README.md
- packages/winlog/manifest.yml
- Bug
Account for any ingest pipelines that might throw some error messages or event codes.
> [winlog] Add a couple ECS fields for error checking/codes

- packages/azure/_dev/build/docs/application_gateway.md
- packages/azure/changelog.yml
- packages/azure/data_stream/application_gateway/agent/stream/azure-eventhub.yml.hbs
- packages/azure/data_stream/application_gateway/manifest.yml
- packages/azure/docs/application_gateway.md
- packages/azure/manifest.yml
Add the `storage_account_container`  to the application gateway integration as an advanced option in the data stream. 
This option is available to all other Azure Logs integration, and this one should have it too. I guess we added to others while the Application Gateway was still in development and missed syncing up.
We did this for other integrations with https://github.com/elastic/integrations/pull/3877
- Closes #5289
> [Azure Logs] Add `storage_account_container` to application gateway integration

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/rules/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/manifest.yml
Fixes the order of `processes` in ingest-pipeline. The `fingerprint` process had colliding documents because `rename` process ran first and changed the value of `json.events.name` which potentially could create same fingerprint for documents with different name but other matching fields.
Found this bug as part of system testing in https://github.com/elastic/security-team/issues/5869
- Build elastic-package locally - `make build`
- Navigate to `google_workspace` package
- Add `assert: hit_count : 22` to `admin` data_stream's System test [config](https://github.com/elastic/integrations/blob/main/packages/google_workspace/data_stream/admin/_dev/test/system/test-default-config.yml)
- The system test fails without this PR as the number of documents ingested are less than expected , reason …
> [Google Workspace ] Fix order of processes in ingest pipeline

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Due to `multiple` values being `false`, the fleet did not generate unique `ids` for the inputs.
- Relates https://github.com/elastic/cloudbeat/issues/755
> Fixing multiple for input streams

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/rules/_dev/test/pipeline/test-rules.log-expected.json
- packages/google_workspace/data_stream/rules/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/rules/sample_event.json
- packages/google_workspace/docs/README.md
- packages/google_workspace/manifest.yml
Type of change
- Bug
- Fix `@timestamp` field value by mapping `google_workspace.id.time` in the Google Workspace Rules data stream.
- Move to integrations/packages/google_workspace directory.
- Closes #5301
> [Google Workspace] Fix timestamp value in Rules data stream

- packages/cisco_secure_email_gateway/changelog.yml
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-amp.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-anti-spam.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-consolidated-event.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-content-scanner.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-error.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-gui-log.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-status.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-system.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/_dev/test/pipeline/test-common-text-mail.log-expected.json
- packages/cisco_secure_email_gateway/data_stream/log/agent/stream/stream.yml.hbs
- packages/cisco_secure_email_gateway/data_stream/log/agent/stream/tcp.yml.hbs
- packages/cisco_secure_email_gateway/data_stream/log/agent/stream/udp.yml.hbs
- packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_secure_email_gateway/data_stream/log/manifest.yml
- packages/cisco_secure_email_gateway/data_stream/log/sample_event.json
- packages/cisco_secure_email_gateway/docs/README.md
- packages/cisco_secure_email_gateway/manifest.yml
Allow user configuration of timezones via config dash or locale.
- Updates #5094
> cisco_secure_email_gateway: allow configuration of time zones

- packages/checkpoint/changelog.yml
- packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/checkpoint/manifest.yml
Errors are made more informative and provide tags to allow programmatic repair.
- Closes #5108
> checkpoint: enhance processor error reporting

- packages/microsoft_exchange_online_message_trace/changelog.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/httpjson.yml.hbs
- packages/microsoft_exchange_online_message_trace/data_stream/log/fields/ecs.yml
- packages/microsoft_exchange_online_message_trace/docs/README.md
- packages/microsoft_exchange_online_message_trace/manifest.yml
Enhancement & Bug
Two changes were made:
1. Added missing `event.start` and `event.created` ECS mappings
2. Added the ability to configure the `request.timeout` field
I made this a single PR and only bumped by patch as both of these things are relatively small changes. I can split into 2 different PRs if desired.
1. Spin up stack install old version of package
2. Update to new version of package
3. Observe that the missing field mappings are now present in the component template
4. Observe that you can now configure the request.timeout value. Confirm that the default value is 60s and that it is set when adding the integration to a policy. Confirm that changing the timeout value also changes it in the policy.
- Closes #5291
> MS Exchange - Add missing ECS mappings & ability to configure request timeout

- packages/system/changelog.yml
- packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
- packages/system/manifest.yml
Removes a redundant regular expression quantifier in the auth message grok processor.
- Closes #5294
> system/auth: remove redundant regular expression quantifier

- packages/azure_frontdoor/changelog.yml
- packages/azure_frontdoor/data_stream/access/agent/stream/azure-eventhub.yml.hbs
- packages/azure_frontdoor/data_stream/waf/agent/stream/azure-eventhub.yml.hbs
- packages/azure_frontdoor/manifest.yml
Changed the default storage container names for both streams to avoid collisions with the Azure Firewall Logs integration
The change can be seen by adding the integration and inspecting the corresponding agent policy (looking for `storage_account_container` under `inputs`).
> Change default storage container name to avoid collision

- packages/azure/changelog.yml
- packages/azure/data_stream/firewall_logs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/manifest.yml
Add additional checks for event.original already existing into Azure firewall logs integration ingest pipeline
> Add additional checks for event.original already existing into Azure firewall logs integration ingest pipeline

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/manifest.yml
Enhancement
In the Prometheus Collector, switch from `condition` being a toggle for Leader Election only, to a text field.
I'm not sure what the policy for this type of change is, but when upgrading existing Integrations via this change, it will blank out an existing leader election condition, if one was previously set:
<details>
<summary>Integration Before Upgrade</summary>
```yaml
inputs:
- id: prometheus/metrics-prometheus-eb767fbc-1e20-47da-b85d-973f5b4195f2
name: prometheus-1
revision: 1
type: prometheus/metrics
meta:
package:
name: prometheus
version: 1.2.0
data_stream:
package_policy_id: eb767fbc-1e20-47da-b85d-973f5b4195f2
streams:
- id: >-
prometheus/metrics-prometheus.collector-eb767fbc-1e20-47da-b85d-973f5b4195f2
data_stream:
dataset: …
```
> Enable setting condition on Prometheus Collector

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
- packages/cloud_security_posture/data_stream/findings/fields/cloudbeat.yml
- packages/cloud_security_posture/manifest.yml
fixes https://github.com/elastic/cloudbeat/issues/768, https://github.com/elastic/kibana/issues/150608
- Added `rule.benchmark.posture_type: kspm` when it's missing
- Added commit_time format support (requires a fix on kibana as well: https://github.com/elastic/kibana/pull/151871)
> [Cloud Security] Add backward compatibility for cloudbeat < 8.7

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/http/manifest.yml
- packages/network_traffic/manifest.yml
Fixes type of `real_ip_header` option for HTTP data stream.
The backing configuration expects a `string`, not a `bool`.
https://github.com/elastic/beats/blob/1f1868d6b1c98d9b9b995e6ffbb3772b8ee293b1/packetbeat/protos/http/config.go#L31
-
> network_traffic: fix type of real_ip_header option for HTTP data stream

- packages/system/changelog.yml
- packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/security/fields/winlog.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/fields/winlog.yml
- packages/winlog/docs/README.md
- packages/winlog/manifest.yml
- Bug
This sets the winlog.time_created field (currently keyword) to a date type. Even though that I have no data that has this field any longer (in Winlogbeat or Elastic Agent System or Custom Windows event log integrations), I see that it exists in the sample json files provided in the pipelines directory for testing, so instead of removing it, I am updating to a date as it should be.
> [system + winlog] Fix mapping for time_created to date

- packages/panw_cortex_xdr/changelog.yml
- packages/panw_cortex_xdr/data_stream/alerts/agent/stream/httpjson.yml.hbs
- packages/panw_cortex_xdr/data_stream/alerts/manifest.yml
- packages/panw_cortex_xdr/manifest.yml
This PR adds support for API tokens issued under the [_Advanced_ security level](https://medium.com/palo-alto-networks-developer-blog/custom-incidents-in-cortex-xdr-ef22a05ff753#2169).
```sh
$ cd integrations/packages/panw_cortex_xdr
$ elastic-package build
$ elastic-package stack up -d -v
$ eval "$(elastic-package stack shellinit)"
$ elastic-package test  -v
```
> [Cortex XDR] Add support for Advanced security level

- docs/generic_guidelines.md
Relates to https://github.com/elastic/integrations/issues/4124.
> Add some guidelines about the use of metrics metadata and dimensions

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/audit/agent/stream/log.yml.hbs
- packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/cluster_stats/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/deprecation/agent/stream/log.yml.hbs
- packages/elasticsearch/data_stream/enrich/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/gc/agent/stream/log.yml.hbs
- packages/elasticsearch/data_stream/index/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_recovery/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_summary/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/ml_job/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/node/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/node_stats/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/pending_tasks/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/server/agent/stream/log.yml.hbs
- packages/elasticsearch/data_stream/shard/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/slowlog/agent/stream/log.yml.hbs
- packages/elasticsearch/manifest.yml
Enhancement
1. Add the ability to set condition to both the Logs and Metrics sections
2. Add the ability to set leader election on the Metrics section
- `condition` is a top level of both inputs as I couldn't think of a reason where a user would want conditions to be different based on what is being collected within an input, and this greatly simplifies things for users.
- `leaderelection` was added to the metrics input, because if you want to use the `cluster` scope, you'd want only one Elastic Agent performing the collection
- `condition` and `leaderelection` are both under the advanced sections, as I'm not sure how many people would actually use this (I don't know how many users actually run Elasticsearch on Kubernetes)
<details>
<summary>Integration Policy Before Upgrade</summary> …
> [Elasticsearch] Add condition and leader election to Elasticsearch integration

- packages/azure/changelog.yml
- packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/eventhub/elasticsearch/ingest_pipeline/parsed-message.yml
- packages/azure/manifest.yml
Fix handling of the `event.original` in the last two Azure Logs that were missing it.
Some event forwarders (for example, Logstash) send both `message` and `event.original` fields, causing an error in the ingest pipeline.
With this change, the pipeline ensures there will only be the `event.original` field early in the pipeline.
Open the Dev Tools and send the following request to simulate the pipeline execution:
```
POST _ingest/pipeline/logs-azure.application_gateway-1.5.10/_simulate
{
"docs": [
{
"tags":
"_source": {
"event": {
"original": "{\"resourceId\":\"/SUBSCRIPTIONS/23103928-B2CF-472A-8CDB-0146E2849129/RESOURCEGROUPS/PEERINGTEST/PROVIDERS/MICROSOFT.NETWORK/APPLICATIONGATEWAYS/Application-Gateway-Name\",\"operationName\":\"ApplicationGatewayAccess\",\"timestamp\":\"2017-04-26T19:27 …
```
> [Azure Logs] Fix `event.original` handling on Application Gateway and the generic Event Hub integration

- packages/prometheus/_dev/build/docs/README.md
- packages/prometheus/docs/README.md
add documentation regarding the remote_write data_stream:
- create service when running agent in kubernetes
- add information regarding `write_relabel_configs` to align with https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-prometheus-remote_write.html
-
> [Prometheus ] Add remote_write documentation

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell_operational.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml
- packages/windows/data_stream/forwarded/fields/winlog.yml
- packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
- Bug
- Enhancement
Align with other Windows integrations and the winlog.time_created improper mapping and adjusting the error handling for said pipelines.
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.
- Relates #5350
> [windows] Fix mapping/pipelines for time_created

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/manifest.yml
Promotes the changes from 1.4.0-beta1 to GA, including support for Ingest Pipeline metrics added in https://github.com/elastic/integrations/pull/4597. This will bump the minimum required Kibana version to 8.7.0.
- Relates to https://github.com/elastic/integrations/pull/4597
Here's what it looks like when I have Logs & Metrics enabled on a 8.7 cluster in Cloud + an agent running the system integration to ingest data.
> Promote Elasticsearch 1.4.0 to GA

- packages/jumpcloud/_dev/build/docs/README.md
- packages/jumpcloud/changelog.yml
- packages/jumpcloud/docs/README.md
- packages/jumpcloud/manifest.yml
The Jumpcloud integration screenshot source is incorrect. This PR fixes it so that the screenshot will correctly render in Kibana and our documentation.
> Fix image source in Jumpcloud readme

- packages/tines/_dev/build/docs/README.md
- packages/tines/changelog.yml
- packages/tines/docs/README.md
- packages/tines/manifest.yml
The Tines integration screenshot sources are incorrect. This PR fixes them so the screenshots will correctly render in Kibana and our documentation.
> Fix image sources in Tines readme

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/fields/fields.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
- Enhancement
This PR adds the new o365.audit.ListBaseType that could be categorized as a long on a rollover or new index creation. Previously this was a keyword but could be mapped to a long which does not fit since the value could be either null, 1, 2, or some small integer.
> [o365] Update fields.yml with new ListBaseType field

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/http/agent/stream/http.yml.hbs
- packages/network_traffic/data_stream/http/manifest.yml
- packages/network_traffic/manifest.yml
Manifest.yml defined the send_headers UI option as the wrong type (bool not text), this PR fixes that.
> [network_traffic] Fix field type for send_headers from bool to text

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
- packages/cloud_security_posture/data_stream/vulnerabilities/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/manifest.yml
We've refactored the configuration schema
Just build and run with kibana, depends on https://github.com/elastic/kibana/pull/152215
-
> [Cloud Security] Refactor config type

- packages/tines/changelog.yml
- packages/tines/manifest.yml
Makes the email address configuration field optional; v13+ of self-hosted instances and all cloud instances do not require it and so it would be confusing. Do leave it though since there may be pre v13 users, but add a note with a link to the Tines auth documentation.
- Closes #5421
> tines: make email address optional and add note

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/database_account/agent/stream/stream.yml.hbs
- packages/azure_metrics/manifest.yml
Move the `CassandraConnectionClosures` metric name from the always-available list of metrics to the Cassandra-focused list of metrics.
Metric names that are not always available should be listed in a section marked with the [ignore_unsupported](https://www.elastic.co/guide/en/beats/metricbeat/8.6/metricbeat-metricset-azure-monitor.html) setting set to `true`.
The integration works if the subscription has at least one Cassandra cluster available but fails otherwise.
- Relates #5453
> [Azure Metrics] Fix CassandraConnectionClosures metric configuration

- packages/kibana/changelog.yml
- packages/kibana/data_stream/audit/agent/stream/log.yml.hbs
- packages/kibana/data_stream/cluster_actions/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/cluster_rules/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/log/agent/stream/log.yml.hbs
- packages/kibana/data_stream/node_actions/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/node_rules/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/stats/agent/stream/stream.yml.hbs
- packages/kibana/data_stream/status/agent/stream/stream.yml.hbs
- packages/kibana/manifest.yml
Enhancement
1. Add the ability to set the `condition` option to both Kibana Logs and Metrics inputs
- `condition` is a top level of both inputs as I couldn't think of a reason where a user would want conditions to be different based on what is being collected within an input, and this greatly simplifies things for users.
- The examples below have version numbers that don't directly match this PR, it was the only way I could get this integration to show up in Kibana for testing purposes.
<details>
<summary>Before Upgrade</summary>
```yaml
inputs:
- id: logfile-kibana-8db829a3-4ae0-4bad-8851-4b652c5c0bf0
name: kibana-1
revision: 1
type: logfile
meta:
package:
name: kibana
version: 2.3.0
data_stream:
package_policy_id: …
```
> [Kibana] Add `condition` configuration for Kibana logs and metrics

- packages/logstash/_dev/deploy/docker/docker-compose.yml
- packages/logstash/_dev/deploy/variants.yml
- packages/logstash/changelog.yml
- packages/logstash/data_stream/log/sample_event.json
- packages/logstash/data_stream/node/sample_event.json
- packages/logstash/data_stream/node_stats/fields/fields.yml
- packages/logstash/data_stream/node_stats/fields/package-fields.yml
- packages/logstash/data_stream/node_stats/manifest.yml
- packages/logstash/data_stream/node_stats/sample_event.json
- packages/logstash/data_stream/slowlog/sample_event.json
- packages/logstash/docs/README.md
- packages/logstash/manifest.yml
Noticed empty graphs when implementing https://github.com/elastic/kibana/pull/152575 caused by missing aliases.
This change adds the mappings and updates wording about the metrics input.
> [logstash] Add missing monitoring cpu aliases

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/manifest.yml
- packages/cisco_asa/manifest.yml
- Parses additional patterns for message ids: 113012, 113004, and 716039 as underlined in issue: https://github.com/elastic/integrations/issues/5443
- Removes `ignore_missing: true` and raises error when renaming `message` into `event.original` to avoid consuming empty messages.
- Closes https://github.com/elastic/integrations/issues/5443
> [Cisco ASA] Support additional patterns for 113012, 113004, and 716039 message ids

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/system/test-logfile-config.yml
- packages/cisco_asa/data_stream/log/_dev/test/system/test-tcp-config.yml
- packages/cisco_asa/data_stream/log/_dev/test/system/test-tls-config.yml
- packages/cisco_asa/data_stream/log/_dev/test/system/test-udp-config.yml
- packages/cisco_asa/data_stream/log/agent/stream/stream.yml.hbs
- packages/cisco_asa/data_stream/log/agent/stream/tcp.yml.hbs
- packages/cisco_asa/data_stream/log/agent/stream/udp.yml.hbs
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/fields.yml
- packages/cisco_asa/data_stream/log/manifest.yml
- packages/cisco_asa/data_stream/log/sample_event.json
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
Provides an option to allow the user to retain a searchable copy of the log message.
- Closes #5249
> cisco_asa: allow user to retain searchable log message

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/database_account/agent/stream/stream.yml.hbs
- packages/azure_metrics/manifest.yml
Move the `CassandraConnectionClosures` metric into a dedicated query section using the [supported dimension](https://learn.microsoft.com/en-us/azure/cosmos-db/monitor-reference#api-for-cassandra-metrics) `ClosureReason` instead of the unsupported `DatabaseName`.
We must remediate an error introduced in the [previous PR](https://github.com/elastic/integrations/pull/5447) when we put the `CassandraConnectionClosures` metric name together with other Cassandra-related metrics using the `DatabaseName` dimension. 
This can work under some circumstances — that's why we didn't spot the problem!
Unfortunately, this can cause an error since the `CassandraConnectionClosures` supports only the `ClosureReason` and `Region` dimensions.
- Relates #5453
> [Azure Monitor] Fix dimensions for CassandraConnectionClosures

- packages/1password/_dev/deploy/docker/config.yml
- packages/1password/changelog.yml
- packages/1password/data_stream/item_usages/_dev/test/system/test-default-config.yml
- packages/1password/data_stream/item_usages/agent/stream/httpjson.yml.hbs
- packages/1password/data_stream/signin_attempts/_dev/test/system/test-default-config.yml
- packages/1password/data_stream/signin_attempts/agent/stream/httpjson.yml.hbs
- packages/1password/manifest.yml
Exit the pagination loop when the response contains `has_more: false`.
Fixes #5471
- Closes #5471
After the fix for signin_attempts:
```
{"log.level":"debug","@timestamp":"2023-03-08T19:51:29.477Z","message":"HTTP request","transaction.id":"7D8G6EKMH551E-1","url.original":"http://elastic-package-service_1password_eventsapi_mock_1:8080/api/v1/signinattempts","url.scheme":"http","url.path":"/api/v1/signinattempts","url.domain":"elastic-package-service_1password_eventsapi_mock_1","url.port":"8080","url.query":"","http.request.method":"POST","user_agent.original":"Elastic-Filebeat/8.6.1 (linux; amd64; 14f2f8d585f8c380945feee789771bd782cd6b2d; 2023-01-24 13:28:02 +0000 UTC)","http.request.body.content":"{\"limit\":1000}","http.request.body.bytes":14,"http.request.mime_type":"application/json"," …
```
> [1password] Stop pagination on has_more=false

- packages/okta/changelog.yml
- packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/okta/data_stream/system/manifest.yml
- packages/okta/manifest.yml
Allows configuration of HTTP keep-alives. The default used departs from the current behaviour (disabled) to ensure the best experience for most cases by allowing connection reuse, but can be reverted to the old behaviour if needed.
It is an advanced configuation option since it's expected to not be needed in the vast majority of cases.
- Closes #4844
> okta: allow configuration of http keep-alives

- packages/cloud_defend/changelog.yml
- packages/cloud_defend/manifest.yml
Sets a new default yaml config for the integration. The new policy format looks like this:
```
file:
selectors:
- name: nginxBinMods
operation:
- createExecutable
- modifyExecutable
targetFilePath:
- /usr/bin/**
containerImageName:
- nginx
- name: excludeTestServers
containerImageTag:
- staging
- preprod
responses:
- match:
- nginxBinMods
exclude:
- excludeTestServers
actions:
- alert
process:
selectors:
- name: allProcesses
operation:
- fork
- exec
responses:
- match:
- allProcesses
actions:
- log
```
- improve package documentation (reflect new schema and new selector conditions and response actions)
- CI e2e testing with kind (once public artifact is available).
- Relates to https://github.com/elastic/kibana/pull/153126
https://user-images.githubusercontent.com/16198204/224398453-e41d8b …
> [D4C] updated schema yaml format

- packages/windows/changelog.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/fields/winlog.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Supports more Sysmon events introduced since v13.10. Following EventIDs are supported:
EventIDs: `8, 9, 19, 20, 27, 28, 255`
`elastic-package stack down && elastic-package build && elastic-package stack up --version=8.6.0 -d -v --services=elasticsearch && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate --data-streams sysmon_operational -v`
```
Run pipeline tests for the package
--- Test results for package: windows - START ---
╭─────────┬────────────────────┬───────────┬──────────────────┬────────┬──────────────╮
│ PACKAGE │ DATA STREAM        │ TEST TYPE │ TEST NAME        │ RESULT │ TIME ELAPSED │
├─────────┼────────────────────┼───────────┼──────────────────┼────────┼──────────────┤
│ windows │ sysmon_operational │ pipeline  │ test-events.json │ …
```
> [Windows] Support Sysmon New EventIDs - 8, 9, 19, 20, 27, 28, 255

- packages/zscaler_zia/changelog.yml
- packages/zscaler_zia/data_stream/web/_dev/test/pipeline/test-web-http-endpoint.log-expected.json
- packages/zscaler_zia/data_stream/web/_dev/test/pipeline/test-web.log-expected.json
- packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
- packages/zscaler_zia/data_stream/web/sample_event.json
- packages/zscaler_zia/docs/README.md
- packages/zscaler_zia/manifest.yml
Maps web login user details to ECS (`user.{name,domain}` and `related.user`).
-
> zscaler_zia: map web login user details to ECS

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
The following PR fixes the upgrade issue we experience when upgrading from 8.6 to 8.7
It appears `CSPM` inputs are being added to the agent policy, making it invalid.
turning these input streams to be disabled by default fixes the issue
- Install `1.1.3` version of the integration
- Wait for the auto-upgrade to kick in
- Explore the agent policy and check if any inputs of `cspm` appear, if so, the issue haven't been fixed.
<details>
<summary>Before</summary>
```yaml
id: d7280e80-c350-11ed-8d30-8d88b3254e9a
revision: 9
outputs:
default:
type: elasticsearch
hosts:
- 'http://localhost:9200'
output_permissions:
default:
_elastic_agent_monitoring:
indices:
- names:
- logs-elastic_agent.apm_server-default
privileges:
- auto_configure
- create_doc
- names:
- …
```
> (backport) [Cloud Security] Fix upgrade failure to 8.7.* from 8.6.*

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
Removes redundant GeoIP look-ups. These appear ~twice (the first instance is a subset of the second — this change removes the first).
https://github.com/elastic/integrations/blob/96e8c055db9886098ddd895ab2d9f3e50b27253c/packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml#L1463-L1505
https://github.com/elastic/integrations/blob/96e8c055db9886098ddd895ab2d9f3e50b27253c/packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml#L1979-L2025
- Relates https://github.com/elastic/integrations/pull/5168#issuecomment-1457237407
> crowdstrike: remove redundant GeoIP look-ups

- packages/pfsense/changelog.yml
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-squid.log
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-squid.log-expected.json
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/squid.yml
- packages/pfsense/manifest.yml
Handle CONNECT method and lines without destination ip.
`elastic-package stack down && elastic-package build && elastic-package stack up -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test`
- Fixes #4971
> [Bug][PfSense] Fix squid pipeline's GROK pattern

- .ci/schedule-daily.groovy
Update Elastic stack version in integrations daily job to use 8.7 SNAPSHOT version.
> Update Elastic stack version integrations daily

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
- packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/netflow/manifest.yml
Adds enrich network direction and type.
New test events are from the netflow9_e10s_4_7byte_pad.pcap and ipfix_test_procera_*52935.dat files in the netflow tests from elastic/beats@b6aa37560e130b97278b99fb32ae93a646bb4256 with adjustment for integration package testing.
- Closes #5452
> netflow: enrich network direction and type

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
- packages/crowdstrike/data_stream/fdr/manifest.yml
- packages/crowdstrike/manifest.yml
Adds support for `max_number_of_messages` parameter configuration in SQS mode when using AWS S3 input.
- Closes https://github.com/elastic/integrations/issues/5595
> [Crowdstrike] | Add support for concurrent messages in SQS mode

- packages/nats/_dev/deploy/docker/Dockerfile
- packages/stan/_dev/deploy/docker/Dockerfile
Fix build of service images for stan and nats, by pinning the versions used for the build.
Before this change, they fail with errors like the following one:
```
------                                                                                                  
> [elastic-package-service-nats build-env 3/4] RUN cd src && go get -d github.com/nats-io/nats.go/:    
#0 3.980 package crypto/ecdh: unrecognized import path "crypto/ecdh" (import path does not begin with hostname)
------
failed to solve: executor failed running [/bin/sh -c cd src && go get -d github.com/nats-io/nats.go/]: exit code: 1
Error: up command failed: can't set up the service deployer: could not boot up service using Docker Compose: running Docker Compose up command failed: exit status 17
exit status 1
```
From the …
> Fix build of service images for stan an nats

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/common.yml
- packages/synthetics/data_stream/http/fields/common.yml
- packages/synthetics/data_stream/icmp/fields/common.yml
- packages/synthetics/data_stream/tcp/fields/common.yml
- packages/synthetics/manifest.yml
Fix inconsistent mapping between state.id and state.ends.id, these should both be keyword since heartbeat sends strings.
> [Synthetics] Fix mapping for state.ends.id

- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/audit/manifest.yml
- packages/gcp/data_stream/dns/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/dns/manifest.yml
- packages/gcp/data_stream/firewall/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/firewall/manifest.yml
- packages/gcp/data_stream/loadbalancing_logs/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/loadbalancing_logs/manifest.yml
- packages/gcp/data_stream/vpcflow/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/vpcflow/manifest.yml
- packages/gcp/manifest.yml
Adds support for configuring `subscription_num_goroutines` and `subscription_max_outstanding_messages` parameters across all datastreams having GCP PubSub input.
- Closes https://github.com/elastic/integrations/issues/5629
> [GCP] Support additional input param in PubSub input for all datastreams

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/agent/stream/netflow.yml.hbs
- packages/netflow/data_stream/log/manifest.yml
- packages/netflow/manifest.yml
Allows user to specify internal networks.
- Closes #5620
> netflow: allow specification of internal networks

- packages/beat/changelog.yml
- packages/beat/data_stream/stats/fields/package-fields.yml
- packages/beat/docs/README.md
- packages/beat/manifest.yml
Add missing cgroup memory aliases from this change https://github.com/elastic/elasticsearch/pull/94400
Related https://github.com/elastic/kibana/issues/153123
> [beat] fix cgroup memory aliases

- packages/apache/changelog.yml
- packages/apache/kibana/visualization/apache-22057f20-3a12-11eb-8946-296aab7b13db.json
- packages/apache/kibana/visualization/apache-47820ce0-3a1d-11eb-8946-296aab7b13db.json
- packages/apache/kibana/visualization/apache-99666080-3a20-11eb-8946-296aab7b13db.json
- packages/apache/manifest.yml
Fixes the issue described at https://github.com/elastic/integrations/issues/5560
- Closes #5560
- https://github.com/elastic/kibana/pull/13872
EDIT: Corrected the 3rd item in the check list, which was wrongly marked as n/a.
> [Apache] Fix a bug that may blank three visualizations

- packages/azure/_dev/build/docs/README.md
- packages/azure/_dev/build/docs/activitylogs.md
- packages/azure/_dev/build/docs/adlogs.md
- packages/azure/_dev/build/docs/application_gateway.md
- packages/azure/_dev/build/docs/eventhub.md
- packages/azure/_dev/build/docs/firewall_logs.md
- packages/azure/_dev/build/docs/platformlogs.md
- packages/azure/_dev/build/docs/springcloudlogs.md
- packages/azure/changelog.yml
- packages/azure/data_stream/eventhub/manifest.yml
- packages/azure/docs/README.md
- packages/azure/docs/activitylogs.md
- packages/azure/docs/adlogs.md
- packages/azure/docs/application_gateway.md
- packages/azure/docs/eventhub.md
- packages/azure/docs/firewall_logs.md
- packages/azure/docs/platformlogs.md
- packages/azure/docs/springcloudlogs.md
- packages/azure/manifest.yml
- Extend the Azure Logs documentation on the Storage Account. We want to make sure users understand why it is needed and how to set it up to deploy this integration successfully.
-  Add a small new "Requirements and setup" section in each integration page that links to the general Azure Logs page, containing the requirements and detailed setup instructions.
We received some questions about the role of the Storage Account in the Azure Logs integration. At least one user—probably more—couldn't find the needed information on our public-facing documentation. 
Here are the questions:
```text
- Do we need to set up and Azure storage account for the integration to work?
- Is it enough with just having an event hub?
- Why is recommended setting up an storage account and how does it help?
- What …
```
> [Azure Logs] Clarify the Storage Account container role in the integration

- packages/checkpoint/_dev/build/docs/README.md
- packages/checkpoint/changelog.yml
- packages/checkpoint/docs/README.md
- packages/checkpoint/manifest.yml
Improves front page documentation to match guidelines.
- Closes #5113
> checkpoint: improve front page documentation

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/manifest.yml
- packages/netflow/manifest.yml
Adds a missing read buffer size configuration.
- Fixes #5682
> netflow: add missing read buffer size configuration

- packages/system/changelog.yml
- packages/system/kibana/dashboard/system-0d3f2380-fa78-11e6-ae9b-81e5311e8cab.json
- packages/system/kibana/dashboard/system-277876d0-fa2c-11e6-bbd3-29c986c96e5a.json
- packages/system/kibana/dashboard/system-5517a150-f9ce-11e6-8115-a7c18106d86a.json
- packages/system/kibana/dashboard/system-71f720f0-ff18-11e9-8405-516218e3d268.json
- packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
- packages/system/kibana/dashboard/system-Logs-syslog-dashboard.json
- packages/system/kibana/dashboard/system-Metrics-system-overview.json
- packages/system/kibana/dashboard/system-Windows-Dashboard.json
- packages/system/kibana/dashboard/system-bae11b00-9bfc-11ea-87e4-49f31ec44891.json
- packages/system/kibana/dashboard/system-bb858830-f412-11e9-8405-516218e3d268.json
- packages/system/kibana/dashboard/system-d401ef40-a7d5-11e9-a422-d144027429da.json
- packages/system/kibana/search/system-06b6b060-7a80-11ea-bc9a-0baf2ca323a3.json
- packages/system/kibana/search/system-324686c0-fefb-11e9-8405-516218e3d268.json
- packages/system/kibana/search/system-62439dc0-f9c9-11e6-a747-6121780e0414.json
- packages/system/kibana/search/system-6f4071a0-7a78-11ea-bc9a-0baf2ca323a3.json
- packages/system/kibana/search/system-757510b0-a87f-11e9-a422-d144027429da.json
- packages/system/kibana/search/system-7e178c80-fee1-11e9-8405-516218e3d268.json
- packages/system/kibana/search/system-8030c1b0-fa77-11e6-ae9b-81e5311e8cab.json
- packages/system/kibana/search/system-9066d5b0-fef2-11e9-8405-516218e3d268.json
- packages/system/kibana/search/system-Syslog-system-logs.json
- packages/system/kibana/search/system-b6f321e0-fa25-11e6-bbd3-29c986c96e5a.json
- packages/system/kibana/search/system-ce71c9a0-a25e-11e9-a422-d144027429da.json
- packages/system/kibana/search/system-eb0039f0-fa7f-11e6-a1df-a78bd7504d38.json
- packages/system/kibana/tag/system-fleet-managed-default.json
- packages/system/kibana/tag/system-fleet-pkg-system-default.json
- packages/system/manifest.yml
This does a general clean up of the Windows dashboards. Each commit is a distinct operation.
- For #5022
> system: clean up windows dashboards

- packages/tines/changelog.yml
- packages/tines/data_stream/audit_logs/_dev/test/pipeline/test-audit-logs.json
- packages/tines/data_stream/audit_logs/_dev/test/pipeline/test-audit-logs.json-expected.json
- packages/tines/data_stream/audit_logs/fields/fields.yml
- packages/tines/docs/README.md
- packages/tines/manifest.yml
Makes `tines.audit_log.inputs.inputs.{agents,diagramNotes,links}` object arrays flattened.
- Fixes #5497
> tines: make inputs object arrays flattened

- packages/dga/changelog.yml
- packages/dga/manifest.yml
- packages/problemchild/changelog.yml
- packages/problemchild/manifest.yml
Based on discussion in `#integrations` (Jan 13, 2023), the versions of the packages should be >=1.0.0 if the packages are tagged as GA.
Not linking the comment thread directly, as this is a public repo.
-
> Update DGA and ProblemChild version numbers for discoverability

- packages/redis/changelog.yml
- packages/redis/data_stream/info/fields/agent.yml
- packages/redis/data_stream/info/fields/ecs.yml
- packages/redis/data_stream/info/fields/fields.yml
- packages/redis/docs/README.md
- packages/redis/manifest.yml
Type of change
- Enhancement
Enable dimension fields for info datastream
https://github.com/elastic/integrations/issues/5698
-
> [Redis] [TSDB] Enable dimension fields for info datastream

- packages/tenable_io/changelog.yml
- packages/tenable_io/data_stream/asset/agent/stream/httpjson.yml.hbs
- packages/tenable_io/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
- packages/tenable_io/manifest.yml
- Bug
This adds response.save_first_response parameter to httpjson yml.hbs files to support the latest change in the httpjson input with regards to how the first_response object is saved/accessed.
- Relates [Fix first_response false positive error by making it a flag based object](https://github.com/elastic/beats/pull/34748/files)
> [integrations][tennable_io] - Updates package to corelate with latest httpjson change

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/ccr/fields/fields.yml
- packages/elasticsearch/docs/README.md
- packages/elasticsearch/manifest.yml
Related https://github.com/elastic/kibana/issues/153298
Add missing `read_exceptions` mappings to the `ccr` data stream
> [elasticsearch] add read exceptions mappings

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_node/fields/fields.yml
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
Add condition NetworkUnavailable to state node.
Follow up to https://github.com/elastic/beats/pull/34976.
> [Kubernetes] Add condition NetworkUnavailable to state node

- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
- packages/cisco_umbrella/manifest.yml
Fixes an indentation error that disables configuration of the integration in Kibana.
> [cisco_umbrella] Fix indentation

- packages/aws/_dev/build/docs/cloudwatch.md
- packages/aws/changelog.yml
- packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-cloudwatch.yml.hbs
- packages/aws/data_stream/cloudwatch_logs/manifest.yml
- packages/aws/docs/cloudwatch.md
- packages/aws/manifest.yml
If the logs collection starts at 10:00, then the input will gather logs in this time window:
- start: 09:59
- end: 10:00
Unfortunately, logs sometimes become available in CloudWatch with a delay; in these circumstances, the input of the CloudWatch logs could miss them.
For example, if a log event is:
- created: 09:59:30
- available 10:00:30
The input will miss that event with the default latency setting [^1]. 
However, the CloudWatch Logs input has a setting called `latency` that allows users to adjust the logs collection time window to cope with the AWS services' latency.
[^1]: The input will pick that log event up at the next restart if "start position" is set to "beginning".
Make the CloudWatch Logs input setting option `latency` available in the integration settings.
- Closes #5712
> [AWS] Add CloudWatch logs latency config option

- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
- packages/cisco_umbrella/manifest.yml
Reverts configuration for handling of multiline messages from Umbrella Auditlogs.
> [cisco_umbrella] Revert S3 multiline

- packages/microsoft_exchange_online_message_trace/_dev/build/docs/README.md
- packages/microsoft_exchange_online_message_trace/_dev/deploy/docker/files/config.yml
- packages/microsoft_exchange_online_message_trace/changelog.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/_dev/test/system/test-httpjson-config.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/httpjson.yml.hbs
- packages/microsoft_exchange_online_message_trace/docs/README.md
- packages/microsoft_exchange_online_message_trace/manifest.yml
- Enhancement
This deprecates the basic auth fields and adds support for OAuth2. This had to be done because Microsoft has 
completely ended support of basic auth in Message Trace APIs since 31st March 2023. This has been also mentioned
here: https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-time-s-up/ba-p/3695312
This change should also fix the SDH: https://github.com/elastic/sdh-beats/issues/3262
- Relates [Microsoft Exchange Online Message Trace integration Basic auth deprecated](https://github.com/elastic/sdh-beats/issues/3262)
> [integrations] [microsft message trace] - Deprecated basic auth and added support for Oauth2

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
Relates to https://github.com/elastic/kibana/issues/140864
- Enhancement
Adds missing heartbeat lightweight configs to the Synthetics integration
> [Synthetics] add additional lightweight heartbeat configs

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/flow/manifest.yml
- packages/network_traffic/manifest.yml
This fixes documentation that misdirects users to use "-1" as a sentinel. This value causes packetbeat to fail to configure.
See https://github.com/elastic/beats/blob/25acf60399e2c56f544f4f76cb76611a28847cdf/packetbeat/flows/flows.go#L49-L66 and https://play.golang.com/p/Z7Si8WEzDAL.
- For #5771
> network_traffic: fix documentation for flows period

- packages/network_traffic/_dev/build/docs/README.md
- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/manifest.yml
- packages/network_traffic/data_stream/cassandra/manifest.yml
- packages/network_traffic/data_stream/dhcpv4/manifest.yml
- packages/network_traffic/data_stream/dns/manifest.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-http-get-2k-file-config.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-icmp-2-pings-config.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-icmp4-ping-config.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-icmp6-ping-config.yml
- packages/network_traffic/data_stream/flow/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/flow/fields/ecs.yml
- packages/network_traffic/data_stream/flow/manifest.yml
- packages/network_traffic/data_stream/flow/sample_event.json
- packages/network_traffic/data_stream/http/manifest.yml
- packages/network_traffic/data_stream/icmp/manifest.yml
- packages/network_traffic/data_stream/memcached/manifest.yml
- packages/network_traffic/data_stream/mongodb/manifest.yml
- packages/network_traffic/data_stream/mysql/manifest.yml
- packages/network_traffic/data_stream/nfs/manifest.yml
- packages/network_traffic/data_stream/pgsql/manifest.yml
- packages/network_traffic/data_stream/redis/manifest.yml
- packages/network_traffic/data_stream/sip/manifest.yml
- packages/network_traffic/data_stream/thrift/manifest.yml
- packages/network_traffic/data_stream/tls/manifest.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/kibana/dashboard/network_traffic-flows.json
- packages/network_traffic/manifest.yml
Removes the beta tags from each of the integrations data streams.
- For #5771
> network_traffic: remove beta tags on data streams and add flow tests

- packages/github/_dev/build/docs/README.md
- packages/github/changelog.yml
- packages/github/docs/README.md
- packages/github/manifest.yml
`Issues` datastream is not in package's README. This PR adds `Issues` datastream into package README.
> [Github] Add issues datastream into package README

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-http-get-2k-file-config.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-icmp-2-pings-config.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-icmp4-ping-config.yml
- packages/network_traffic/data_stream/flow/_dev/test/system/test-icmp6-ping-config.yml
- packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
- packages/network_traffic/manifest.yml
This fixes the passing of the flows period and timeout parameters which previously were passed to agent in the wrong location always resulting in the agent using the default values specified by packetbeat, 10s and 30s.
To confirm this is working correctly, before running the tests with `elastic-package`, set the agent logging level to "debug". Run the system tests and when they have completed, step into the agent's terminal and collect diagnostics with `./elastic-agent diagnostics`. Examine the log file for the log line describing packetbeat's understanding of the parameters, e.g. (note the `period=-1s`):
```
$ jq 'select(.message | startswith("new flows worker")).message' < elastic-agent-diagnostics-2023-04-06T04-52-21Z-00/logs/elastic-agent-20230406.ndjson
"new flows worker. timeout=5s, …
```
> network_traffic: fix passing of period and timeout parameters to agent

- packages/aws/_dev/build/docs/README.md
- packages/aws/changelog.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
Add two missing permissions to the AWS integration docs. 
* `logs:DescribeLogGroups`
* `logs:FilterLogEvents`
The AWS CloudWatch logs input requires these permissions to fetch logs from the CloudWatch API.
The additional permissions come from the [AWS CloudWatch input docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-cloudwatch.html) for Filebeat.
- Relates #5019
> [AWS] Add missing permissions required by the CloudWatch logs integration

- packages/aws/_dev/build/docs/README.md
- packages/aws/changelog.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
Add two missing permissions to the AWS integration docs. 
* `ce:GetCostAndUsage`
* `organizations:ListAccounts`
The source list comes from the [Metricbeat docs](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-billing.html):
- Relates #5019
> [AWS] Add missing permissions in the AWS Billing integration documentation

- packages/akamai/changelog.yml
- packages/akamai/data_stream/siem/_dev/test/system/test-default-config.yml
- packages/akamai/data_stream/siem/agent/stream/httpjson.yml.hbs
- packages/akamai/data_stream/siem/manifest.yml
- packages/akamai/manifest.yml
Add an advanced option to enable http request trace logging for debugging purposes.
1. elastic-package build
2. elastic-package install
3. Use Kibana to add the integration to an Agent policy and toggle on the tracer feature.
4. Verify request/response logs are in `/usr/share/elastic-agent/state/data/run/httpjson-default/http-request-trace-httpjson*.ndjson`.
> [Akamai] Add toggle to enable request tracing

- packages/akamai/_dev/deploy/docker/files/config.yml
- packages/akamai/changelog.yml
- packages/akamai/data_stream/siem/_dev/test/system/test-default-config.yml
- packages/akamai/data_stream/siem/agent/stream/httpjson.yml.hbs
- packages/akamai/manifest.yml
The Akamai SIEM API returns an 'offset' value that encodes the storage time of the last returned event. Use offset as the cursor value when making API requests.
This assumes that the API response always includes an offset. And that the response has total == 0 when there is no more data available.
The version is marked as beta because it has not been tested against the real Akamai service.
Relates: #5826
- Relates #5826
This is a beta release. So users will need to select the version explicitly to test it.
These are the raw request / responses from testing with the mock API.
```
GET /siem/v1/configs/aaaa?from=1680879244 HTTP/1.1
Host: elastic-package-service_akamai_1:8080
User-Agent: Elastic-Filebeat/8.7.0 (linux; amd64; a8dbc6c06381f4fe33a5dc23906d63c04c9e2444; 2023-03-23 00:44:06 +0000 …
```
> [Akamai] Use 'offset' value as cursor

- packages/redis/changelog.yml
- packages/redis/data_stream/info/fields/fields.yml
- packages/redis/docs/README.md
- packages/redis/manifest.yml
> [Redis] Added metric_type mapping for datastream - info

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.4.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/82c92efcbb15f1a03fd304a76f6a90cf10c3ef48
None
None
> [Security Rules] Update security rules package to v8.4.4

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/34665130fdc64ed300ba21297aba79c0d01a91b8
None
None
> [Security Rules] Update security rules package to v8.5.2

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.2-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e8aa73919356c76a331cf6010fe25d5e3bee9ddd
None
None
> [Security Rules] Update security rules package to v8.6.2-beta.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e8aa73919356c76a331cf6010fe25d5e3bee9ddd
None
None
> [Security Rules] Update security rules package to v8.6.2

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/kibana/security_rule/a198fbbd-9413-45ec-a269-47ae4ccf59ce.json
- packages/security_detection_engine/kibana/security_rule/ff4599cb-409f-4910-a239-52e4e6f532ff.json
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.2-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/51222a85eb6899c73b40147fb8496ea3dffaf0b1
None
None
> [Security Rules] Update security rules package to v8.7.2-beta.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/51222a85eb6899c73b40147fb8496ea3dffaf0b1
None
None
> [Security Rules] Update security rules package to v8.7.2

- packages/system/_dev/build/docs/README.md
- packages/system/changelog.yml
- packages/system/data_stream/application/manifest.yml
- packages/system/data_stream/security/manifest.yml
- packages/system/data_stream/system/manifest.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
- packages/windows/_dev/build/docs/README.md
- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/manifest.yml
- packages/windows/data_stream/powershell/manifest.yml
- packages/windows/data_stream/powershell_operational/manifest.yml
- packages/windows/data_stream/sysmon_operational/manifest.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
- packages/winlog/_dev/build/docs/README.md
- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/fields/agent.yml
- packages/winlog/data_stream/winlog/manifest.yml
- packages/winlog/docs/README.md
- packages/winlog/manifest.yml
- Add documentation around case where the event ID clause limit is lower than what is claimed by current docs.
- Add additional documentation for workaround when event ID clause limit is exceeded.
- Formatting and cleanup per elastic-package
- Closes #5835
> [System/Windows/Winlog] Document 21 Event ID clause limit under certain situations

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/vulnerabilities/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/manifest.yml
Configures the cycle time for vulnerability management.
Removed the region, because we suppose to query it at runtime.
- Closes https://github.com/elastic/cloudbeat/issues/852
> Adding vulnerability management period and removing region

- packages/websphere_application_server/changelog.yml
- packages/websphere_application_server/manifest.yml
- Enhancement
Bump up the package version and release Session Manager, Servlet, Threadpool lens migration work
- https://github.com/elastic/integrations/issues/5575
- https://github.com/elastic/integrations/issues/5221
> [O11y][WebSphere Application Server] Release Session Manager, Servlet, Threadpool lens migration work

- packages/cloud_security_posture/manifest.yml
This PR updates the CloudFormation template format for the Vuln Mgmt policy. The format was now updated to support the full CloudFormation create stack URL, plus these additional parameters to be replaced by Kibana:
- `FLEET_ENROLLMENT_TOKEN`
- `FLEET_URL`
- `KIBANA_VERSION`
> [Cloud Security Posture] Update CloudFormation template format

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/fields/fields.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
An unknown field of o365.audit.FileSizeBytes was found in my logs when trying to reindex some conflict field indices into a new index.
Sadly, M$ does not appear to have these fields documented in their schema here: https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema
Furthermoore, it is much to difficult to get a raw event so I don't have a sample. Perhaps someone else out there can share a o365 Audit document from the SharePointFileOperation in event.code.
- Enhancement
Add new FileSizeBytes field to make sure it is properly mapped.
> [o365] New field detected: FileSizeBytes

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/access_transparency/sample_event.json
- packages/google_workspace/data_stream/admin/sample_event.json
- packages/google_workspace/data_stream/alert/sample_event.json
- packages/google_workspace/data_stream/context_aware_access/sample_event.json
- packages/google_workspace/data_stream/device/sample_event.json
- packages/google_workspace/data_stream/drive/sample_event.json
- packages/google_workspace/data_stream/gcp/sample_event.json
- packages/google_workspace/data_stream/group_enterprise/sample_event.json
- packages/google_workspace/data_stream/groups/sample_event.json
- packages/google_workspace/data_stream/login/sample_event.json
- packages/google_workspace/data_stream/rules/sample_event.json
- packages/google_workspace/data_stream/saml/sample_event.json
- packages/google_workspace/data_stream/token/_dev/test/pipeline/test-token.log-expected.json
- packages/google_workspace/data_stream/token/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/token/sample_event.json
- packages/google_workspace/data_stream/user_accounts/sample_event.json
- packages/google_workspace/docs/README.md
- packages/google_workspace/manifest.yml
- Enhancement
- Set event categorization for Token data stream.
- Move to integrations/packages/google_workspace directory.
- Relates https://github.com/elastic/integrations/issues/4722
> [google_workspace] Set event categorization for Token data stream.

- packages/cloud_defend/changelog.yml
- packages/cloud_defend/data_stream/alerts/fields/fields.yml
- packages/cloud_defend/data_stream/file/fields/fields.yml
- packages/cloud_defend/data_stream/process/fields/fields.yml
- packages/cloud_defend/docs/README.md
- packages/cloud_defend/manifest.yml
Changes the type for orchestrator.resource.label and orchestrator.resource.annotation to type keyword. "flattened" type has too many limitations for our use cases. Also added (BETA) to the integration description in the manifest.
- Relates https://github.com/elastic/ecs/pull/2181
> [D4C] change resource.label and resource.annotation to keyword type

- packages/mimecast/changelog.yml
- packages/mimecast/data_stream/audit_events/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/audit_events/manifest.yml
- packages/mimecast/data_stream/dlp_logs/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/dlp_logs/manifest.yml
- packages/mimecast/data_stream/siem_logs/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/siem_logs/manifest.yml
- packages/mimecast/data_stream/threat_intel_malware_customer/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/threat_intel_malware_customer/manifest.yml
- packages/mimecast/data_stream/threat_intel_malware_grid/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/threat_intel_malware_grid/manifest.yml
- packages/mimecast/data_stream/ttp_ap_logs/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/ttp_ap_logs/manifest.yml
- packages/mimecast/data_stream/ttp_ip_logs/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/ttp_ip_logs/manifest.yml
- packages/mimecast/data_stream/ttp_url_logs/agent/stream/httpjson.yml.hbs
- packages/mimecast/data_stream/ttp_url_logs/manifest.yml
- packages/mimecast/manifest.yml
This adds an option to enable the request tracer for each of the Mimecast data streams to enable debugging. It also bump kibana constraint to 8.5.0 which is when the request tracer feature was introduced to Agent.
- For #5053
> mimecast: add option to enable http request trace logging for debugging

- packages/pulse_connect_secure/changelog.yml
- packages/pulse_connect_secure/data_stream/log/agent/stream/tcp.yml.hbs
- packages/pulse_connect_secure/data_stream/log/manifest.yml
- packages/pulse_connect_secure/manifest.yml
This add a TCP options configuration field that allows users to pass parameters to the TCP input. This is important to allow setting framing options.
- Closes #5861
> pulse_connect_secure: allow user-defined TCP options

- packages/cloudflare/changelog.yml
- packages/cloudflare/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
- packages/cloudflare/manifest.yml
Previously keys containing double quotes would cause YAML parsing error, so use the handlebars escape_string helper. This is available from v8.3.3 and v8.4.0, so constrain kibana version to ^v8.4.0.
- For #3388
> cloudflare: safe escape authentication keys

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/agent/stream/amqp.yml.hbs
- packages/network_traffic/data_stream/cassandra/agent/stream/cassandra.yml.hbs
- packages/network_traffic/data_stream/dhcpv4/agent/stream/dhcpv4.yml.hbs
- packages/network_traffic/data_stream/dns/agent/stream/dns.yml.hbs
- packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
- packages/network_traffic/data_stream/http/agent/stream/http.yml.hbs
- packages/network_traffic/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/network_traffic/data_stream/memcached/agent/stream/memcached.yml.hbs
- packages/network_traffic/data_stream/mongodb/agent/stream/mongodb.yml.hbs
- packages/network_traffic/data_stream/mysql/agent/stream/mysql.yml.hbs
- packages/network_traffic/data_stream/nfs/agent/stream/nfs.yml.hbs
- packages/network_traffic/data_stream/pgsql/agent/stream/pgsql.yml.hbs
- packages/network_traffic/data_stream/redis/agent/stream/redis.yml.hbs
- packages/network_traffic/data_stream/sip/agent/stream/sip.yml.hbs
- packages/network_traffic/data_stream/thrift/agent/stream/thrift.yml.hbs
- packages/network_traffic/data_stream/tls/agent/stream/tls.yml.hbs
- packages/network_traffic/manifest.yml
This feature was added to v8.7, but hooks from the integration were not made available.
- Relates elastic/beats#34428
- https://discuss.elastic.co/t/block-installation-of-bundled-npcap-via-network-packet-capture-integration/329748
> network_traffic: allow integration users to specify npcap.never_install

- CONTRIBUTING.md
Add top level link to Docs Guidelines docs.
Super basic tweak to add the Docs Guidelines link to the Contributing page.
> [DOCS] Update CONTRIBUTING.md with Docs Guidelines link

- packages/cloudflare_logpush/changelog.yml
- packages/cloudflare_logpush/data_stream/firewall_event/_dev/test/pipeline/test-pipeline-firewall-event.log-expected.json
- packages/cloudflare_logpush/data_stream/firewall_event/elasticsearch/ingest_pipeline/default.yml
- packages/cloudflare_logpush/data_stream/firewall_event/fields/ecs.yml
- packages/cloudflare_logpush/data_stream/firewall_event/sample_event.json
- packages/cloudflare_logpush/data_stream/http_request/_dev/test/pipeline/test-pipeline-http-request.log-expected.json
- packages/cloudflare_logpush/data_stream/http_request/elasticsearch/ingest_pipeline/default.yml
- packages/cloudflare_logpush/data_stream/http_request/sample_event.json
- packages/cloudflare_logpush/docs/README.md
- packages/cloudflare_logpush/manifest.yml
Previously the url fields were being populated by the referrer URL parts in the http_request datastream and the request fields were incompletely filled in the firewall_events datastream.
The use of the uri_parts processor to populate the url fields is a little troubling in the http_request datastream as the field used, ClientRequestURI, is not a URL and is arguably not even a URI without the context of the other ClientRequest* fields.
- Fixes #5849
> cloudflare_logpush: fix mapping of url fields

- packages/influxdb/changelog.yml
- packages/influxdb/data_stream/advstatus/fields/fields.yml
- packages/influxdb/docs/README.md
- packages/influxdb/manifest.yml
Type of change
- Bug
Add additional dimension field to advstatus datastream under influxDB
- Closes #5919
> [InfluxDB] Add  additional dimension field for advstatus datastream

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
sets `period` to `24h` on the `aws.yml` config
- Closes https://github.com/elastic/cloudbeat/issues/752
> [Cloud Security] Set default CSPM period

- packages/fleet_server/agent/input/agent.yml.hbs
- packages/fleet_server/changelog.yml
- packages/fleet_server/manifest.yml
Remove the host and port field from the Fleet server integration as it seems those values are only configurable during Fleet server installation.
Related to [154674](https://github.com/elastic/kibana/pull/154674)
cc @jen-huang @michel-laterman 
Should we restrict that package to newest version of Kibana (8.7?)
I tested manually:
* that a fleet server is available when not providing any port or host
* that you can customize fleet server port with `--fleet-server-port`
> [Fleet] Remove host and port for Fleet Server

- packages/kafka/changelog.yml
- packages/kafka/data_stream/broker/fields/fields.yml
- packages/kafka/docs/README.md
- packages/kafka/manifest.yml
Type of change
- Enhancement
Added metric_type mapping for broker datastream
- Relates #5905
> [Kafka] [TSDB] Added metric_type mapping for broker datastream

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/fields/ecs.yml
- packages/cloud_security_posture/data_stream/findings/fields/fields.yml
- packages/cloud_security_posture/manifest.yml
Add `orchestrator.cluster.id` to the index mapping
See https://github.com/elastic/cloudbeat/pull/847
> [Cloud Security] Add orchestrator.cluster.id to the index mapping

- .ci/Jenkinsfile
- .ci/schedule-daily.groovy
As an optimization add a parameter to skip the package publishing step.
This avoids any interaction with the remote publishing Jenkins pipeline
so it can avoid errors not related to testing.
There is no need to attempt publishing for jobs that only are concerned
with testing (e.g. daily tests agains 7.17 and 8.x).
This PR began as just a test to try to understand why CI jobs are failing. 
I am concerned that daily CI testing is not running for all packages against the latest 8.7 snapshot. There is a [job](https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations-daily/) that is running daily, but I suspect it’s not doing any real testing. It mostly fails on publishing and never gets to the point of running package or system tests.
- Test-only type of jobs should never be doing any …
> [ci] - Test skipping publishing step for daily 7.17 and 8.x test jobs

- packages/cel/_dev/build/build.yml
- packages/cel/changelog.yml
- packages/cel/manifest.yml
- packages/jolokia_input/_dev/build/build.yml
- packages/jolokia_input/changelog.yml
- packages/jolokia_input/manifest.yml
Add the build manifest where the ECS reference is set.
Go to the package folder definition and run `elastic-package build -v`:
```
~/Coding/work/integrations/packages/jolokia_input
$ elastic-package build -v 
2023/04/20 10:20:39 DEBUG Enable verbose logging
2023/04/20 10:20:39 DEBUG Distribution built without a version tag, can't determine release chronology. Please consider using official releases at https://github.com/elastic/elastic-package/releases
Build the package
2023/04/20 10:20:39 DEBUG Use build directory: /home/mariorodriguez/Coding/work/integrations/build
2023/04/20 10:20:39 DEBUG Build directory: /home/mariorodriguez/Coding/work/integrations/build/packages/jolokia/0.0.5
2023/04/20 10:20:39 DEBUG Clear target directory (path: …
```
> Added build manifest setting ECS reference

- packages/mysql_enterprise/changelog.yml
- packages/mysql_enterprise/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/mysql_enterprise/manifest.yml
MySQL send its audit logs as parts of an infinitely long JSON array and so separates each line of the logs with a comma. We don't know that we are in an array since the first line of the log may not have been sent to us, so remove the trailing comma to treat each element of the partial array object as an object in a JSON stream.
- Fixes #5941
> mysql_enterprise: fix handling of streaming data sent as partial array object

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-sysmon-operational-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/sample_event.json
- packages/windows/docs/README.md
- packages/windows/manifest.yml
This updates the tests expectations to match the bahaviour of ES ingest processors.
- Fixes #5958
> windows: update tests expectations to match processor behaviour

- .github/CODEOWNERS
- packages/universal_profiling_symbolizer/changelog.yml
- packages/universal_profiling_symbolizer/docs/README.md
- packages/universal_profiling_symbolizer/img/profiler-logo-color-48px.svg
- packages/universal_profiling_symbolizer/manifest.yml
Add a package for Universal Profiling Symbolizer
> Universal Profiling: add package for symbolizer

- .ci/schedule-daily.groovy
Fix definition of the schedule-daily job.
Follow up of https://github.com/elastic/integrations/pull/5884
Example of job failing: 
https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations-daily/detail/integrations-daily/229/pipeline
```
[2023-04-24T03:04:23.996Z] WorkflowScript: 34: expecting ']', found 'booleanParam' @ line 34, column 17.
[2023-04-24T03:04:23.996Z]                    booleanParam(name: 'skip_publishing', value: true),
[2023-04-24T03:04:23.996Z]                    ^
[2023-04-24T03:04:23.996Z] 
[2023-04-24T03:04:23.996Z] 1 error
```
> Fix schedule daily job

- packages/windows/changelog.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
Adds `event.category` and `event.type` to Sysmon Operational pipeline which were missed when new EventIDs were incorporated in https://github.com/elastic/integrations/issues/4038
- Closes https://github.com/elastic/integrations/issues/5976
> [Windows] Add event.category and event.type to Sysmon Operational 

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/data_stream/browser_network/manifest.yml
- packages/synthetics/data_stream/browser_screenshot/manifest.yml
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
- Enhancement
Change synthetics integration from `beta` to `ga`.
- Relates [#123](https://github.com/elastic/synthetics-dev/issues/180)
> [Synthetics] Release Synthetics Integration as GA.

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/ingest_pipeline/agent/stream/stream.yml.hbs
- packages/elasticsearch/manifest.yml
Add `ssl` support to elasticsearch ingest_pipeline data stream
NA
NA
-
> Add ssl support to elasticsearch ingest pipeline datastream

- packages/ti_recordedfuture/changelog.yml
- packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-domain-default.log-expected.json
- packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-hash-default.log-expected.json
- packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-httpjson.log-expected.json
- packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-ip-default.log-expected.json
- packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-url-default.log-expected.json
- packages/ti_recordedfuture/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/ti_recordedfuture/data_stream/threat/sample_event.json
- packages/ti_recordedfuture/docs/README.md
- packages/ti_recordedfuture/manifest.yml
This extracts provider names from the evidence details fields in order to populate `threat.indicator.provider`.
- Fixes #5960
> ti_recordedfuture: scrape provider details from evidence fields

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
- packages/network_traffic/data_stream/flow/manifest.yml
- packages/network_traffic/manifest.yml
Allows users to specify processors to run on packetbeat data in flows datastream.
- Closes #5969
> network_traffic: allow user-defined processors on flows

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/collstats/fields/agent.yml
- packages/mongodb/data_stream/collstats/fields/base-fields.yml
- packages/mongodb/data_stream/collstats/fields/fields.yml
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
- Enhancement
This PR updates dimension fields for collStats datastream of mongoldb to support TSDB enablement.
- Relates #5281
> Added dimensions fields to mongodb collStats datastream to enable TSDB.

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs
- packages/ti_misp/data_stream/threat/manifest.yml
- packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
- packages/ti_misp/data_stream/threat_attributes/manifest.yml
- packages/ti_misp/manifest.yml
Adds an advanced option to enable http request trace logging for debugging purposes and bumps kibana constraint to 8.5.0 which is when the request tracer feature was introduced to Agent.
- For #5956
> ti_misp: add toggle to enable request tracing

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.4.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/036bc88c8ab9303e34f926b38537c2baec678939
None
> [Security Rules] Update security rules package to v8.4.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/7c68af76e65dd66af2a10e54d5110adf47ed09ac
None
> [Security Rules] Update security rules package to v8.5.3

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6fa181fa084b44f65e02e0579a9336a17e4ffe4e
None
> [Security Rules] Update security rules package to v8.6.3

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/86abb79b77549bbb566e3bd5e5405a91ad2363b9
None
> [Security Rules] Update security rules package to v8.7.3

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/003b8c4aba5b215c519c981ead1ac7bff72c266a
None
> [Security Rules] Update security rules package to v8.8.1

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
The meaning of `ElasticAgentVersion` parameter has changed as part of the new cloudformation template.
The template used to expect a value in the form of `elastic-agent-KIBANA_VERSION-linux-arm64`, and as of the new template it only expects `KIBANA_VERSION`.
-
> [Vulnerability Management] Update CloudFormation template ElasticAgentVersion

- packages/okta/changelog.yml
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/manifest.yml
Removes a pair of redundant renames incorrectly introduced in #6010.
-
> okta: remove redundant rename processors

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/vulnerabilities/fields/ecs.yml
- packages/cloud_security_posture/data_stream/vulnerabilities/fields/fields.yml
- packages/cloud_security_posture/data_stream/vulnerabilities/fields/vulnerability.yml
- packages/cloud_security_posture/manifest.yml
Update CNVM index mapping
Run together with https://github.com/elastic/cloudbeat/pull/912
- Relates https://github.com/elastic/cloudbeat/issues/897
- Relates https://github.com/elastic/cloudbeat/pull/912
> Update index mapping for CNVM findings

- packages/apache/changelog.yml
- packages/apache/data_stream/status/fields/agent.yml
- packages/apache/data_stream/status/fields/ecs.yml
- packages/apache/docs/README.md
- packages/apache/manifest.yml
Type of change
- Enhancement
Added metric_type mapping for partition datastream
- Relates #6075
> [Apache] [TSDB] Added dimension fields for status datastream

- kind-config.yaml
- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container/fields/base-fields.yml
- packages/kubernetes/manifest.yml
The dimensions set for the container data stream are not enough, since a pod can have multiple containers. In that case, without setting the container name (unique per pod) as dimension, there would be no way to distinguish between documents from different containers in the same pod.
Relates to https://github.com/elastic/integrations/issues/4618.
> [Kubernetes][Container] Add container name as dimension

- packages/akamai/_dev/deploy/docker/files/config.yml
- packages/akamai/changelog.yml
- packages/akamai/data_stream/siem/agent/stream/httpjson.yml.hbs
- packages/akamai/data_stream/siem/manifest.yml
- packages/akamai/manifest.yml
- Bug
This adds the 'to' query params to the time based requests and removes it when we transition over to the offset based requests. Even though the 'to' query param is marked as optional by the Akamai siem docs as discussed [here](https://github.com/elastic/sdh-beats/issues/3282#issuecomment-1536156561) , the requests were failing without it.
**NOTE:** **This is a beta release. So users will need to select the version explicitly to test it.**
- Relates #5826
- Supersedes #5827
> [Akamai] Added the 'to' query params to the time based request

- packages/tomcat/_dev/build/docs/README.md
- packages/tomcat/changelog.yml
- packages/tomcat/docs/README.md
- packages/tomcat/manifest.yml
- Deprecation
- Rename `Tomcat` integration to `Tomcat NetWitness Logs`.
- Add deprecation note in README.md.
- Move to integrations/packages/tomcat) directory.
- Run the following command to run tests. elastic-package test
- Relates #5200
> [Tomcat] Deprecate Tomcat package

- packages/tomcat/_dev/build/docs/README.md
- packages/tomcat/changelog.yml
- packages/tomcat/docs/README.md
- packages/tomcat/manifest.yml
- Deprecation
- Add link of new `apache_tomcat` package in README.md.
- Move to integrations/packages/tomcat) directory.
- Run the following command to run tests. elastic-package test
- Relates #5200
> [Tomcat] Update README.md

- packages/nginx/changelog.yml
- packages/nginx/data_stream/stubstatus/fields/agent.yml
- packages/nginx/manifest.yml
- Bug
Modify the dimension field mapping to support public cloud deployment
> [Nginx] Modify the dimension field mapping to support public cloud deployment

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/cassandra/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/dhcpv4/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/http/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/icmp/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/memcached/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/mongodb/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/mysql/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/nfs/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/pgsql/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/redis/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/sip/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/thrift/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/tls/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/manifest.yml
Versions of packetbeat that add the offending fields are no longer supported by the integration, so this removes the script that cleans them from the document.
-
> network_traffic: remove redundant field cleanup scripts

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
As we saw that a few regions don't support the `a1` instance family we are changing to a more recent instance family `c6g`.
- Related: https://github.com/elastic/cloudbeat/issues/954
> [Vulnerability Management] Update CloudFormation template to deploy c6g instance family

- packages/couchdb/changelog.yml
- packages/couchdb/data_stream/server/fields/ecs.yml
- packages/couchdb/docs/README.md
- packages/couchdb/manifest.yml
- Bug
Modify the dimension field mapping to support public cloud deployment
> [CouchDB] Modify the dimension field mapping to support public cloud deployment

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Since `preview10` wasn't recognize by kibana as the latest version of csp `1.3.0`  we want  to try `preview91` instead.
-
> [Vulnerability Management] Bump integration version preview91

- packages/elastic_package_registry/changelog.yml
- packages/elastic_package_registry/data_stream/metrics/fields/fields.yml
- packages/elastic_package_registry/docs/README.md
- packages/elastic_package_registry/manifest.yml
- packages/gcp/changelog.yml
- packages/gcp/data_stream/redis/fields/fields.yml
- packages/gcp/docs/README.md
- packages/gcp/docs/redis.md
- packages/gcp/manifest.yml
Fix `metric_type` declarations for GCP and Elastic Package Registry integrations. These integrations had `gauge` metrics declared for non-numeric fields like booleans and dates, which resulted in Elasticsearch errors when enabling TSDB or generating time series metrics in mappings.
> [Fleet] Fix metric types for GCP + elastic package registry integrations

- packages/system/changelog.yml
- packages/system/data_stream/application/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/security/_dev/test/system/test-default-config.yml
- packages/system/data_stream/security/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/system/manifest.yml
- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/system/test-default-config.yml
- packages/windows/data_stream/forwarded/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell/_dev/test/system/test-default-config.yml
- packages/windows/data_stream/powershell/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell_operational/_dev/test/system/test-default-config.yml
- packages/windows/data_stream/powershell_operational/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/sysmon_operational/_dev/test/system/test-default-config.yml
- packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
- packages/windows/manifest.yml
This PR enables request tracer on integrations with `httpjson` input. 
Sets the minimum Kibana version to `8.7.1`
Enables the request tracer in system tests.
- https://github.com/elastic/integrations/pull/5641
> Enable Request tracer on System and Windows integrations

- packages/cloud_defend/changelog.yml
- packages/cloud_defend/docs/README.md
- packages/cloud_defend/manifest.yml
Removes documentation for an unimplemented selector condition.
> [D4C] cloud_defend. Removed kubernetesPodId. Update docs.

- packages/trellix_epo_cloud/changelog.yml
- packages/trellix_epo_cloud/data_stream/device/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/data_stream/event/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/data_stream/group/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/manifest.yml
During debug logging complete state is logged. Currently this will include the `api_key` field. So let the redactor know to mask this.
Example log lines:
Relevant text is `"api_key\":\"*\"`
before call to CEL:
```
{"log.level":"debug","@timestamp":"2023-05-12T01:24:30.674Z","message":"request state","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"service.name":"filebeat","id":"cel-trellix_epo_cloud.device-3ea71031-938c-4944-b2e6-bd49efbff32e","input_url":"http://elastic-package-service_trellix_epo_cloud_1:8090","cel":{"ecs.version":"1.6.0","state":"{\"api_key\":\"*\",\"batch_size\":1000,\"url\":\"http://elastic-package-service_trellix_epo_cloud_1:8090\",\"want_more\":false}"},"log.logger":"input.cel","log. …
```
> trellix_epo_cloud: ensure API keys are not logged

- packages/aws_logs/changelog.yml
- packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
- packages/aws_logs/data_stream/generic/manifest.yml
- packages/aws_logs/manifest.yml
This PR is to add multiline support for custom AWS logs integration. Here is what the policy looks like after the multiline parser is added:
```
streams:
- id: aws-s3-aws_logs.generic-4cc5036f-5f6b-4040-8e4c-ca2720f1481e
data_stream:
dataset: aws_logs.generic
bucket_arn: test_arn
number_of_workers: 1
bucket_list_interval: 120s
max_bytes: 10MiB
max_number_of_messages: 5
sqs.max_receive_count: 5
sqs.wait_time: 20s
file_selectors: null
access_key_id: aa
secret_access_key: bb
tags:
- forwarded
publisher_pipeline.disable_host: true
parsers:
- multiline:
pattern: ^<Event
negate: true
match: after
```
Step1: create a s3 bucket and upload a file with multiline log sample. For example what I'm using is:
```
kaiyansheng ~/Documents  $ cat test_multiline.log 
<Event><Data>
A
B
C</Data></Event> …
```
> [Custom AWS Logs] Add multiline support for aws-s3 input

- packages/aws/changelog.yml
- packages/aws/data_stream/s3access/_dev/test/pipeline/test-s3-server-access.log-expected.json
- packages/aws/data_stream/s3access/elasticsearch/ingest_pipeline/default.yml
- packages/aws/manifest.yml
Fix a small typo in a field name.
> [AWS] Fix typo in field name causing erroneous timestamp detection on s3access

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
- packages/kubernetes/kibana/dashboard/kubernetes-f5ab5510-9c94-11e9-94fd-c91206cd5249.json
- packages/kubernetes/manifest.yml
Backport the fix https://github.com/elastic/integrations/pull/6221 to the 1.39 version as was suggested in https://github.com/elastic/integrations/pull/6221#discussion_r1195115705
steps used to create this backport PR:
```
git branch backport-kubernetes-1.39 a02e91e0a7a63d4b94f421f770c7c9b68acdc98f
git cherry-pick 2e7c914d3cfc86020f9e6c6432e183448bbae5f3
<fix conflicts>
git cherry-pick --continue
git push -u origin backport-kubernetes-1.39             
<create remote branch - did it manually from the a02e91e0a7a63d4b94f421f770c7c9b68acdc98f commit>
open a PR against elastic/backport-kubernetes-1.39 
```
-
Proxy visualisation after this commit:
scheduler:
> [Kubernetes][Dashboards] Fix missing sort field on proxy and scheduler dashboards

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/88188bdb486e6dbf8c771f2bf3c36ca5cba152c2
* https://github.com/elastic/ia-trade-team/issues/122
None
> [Security Rules] Update security rules package to v8.5.4

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/67c31074e94e0cb3e0a0ba10a0f38b8a0cea067f
* https://github.com/elastic/ia-trade-team/issues/122
None
> [Security Rules] Update security rules package to v8.6.4

- packages/windows/changelog.yml
- packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell_operational/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/powershell_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
Due to recursive descent, the previous patterns resulted in significant fruitless work, surpassing the regular expression cost limit. This short-circuits the search to improve efficiency.
- Fixes #6030
> windows: improve regular expression search efficiency to allow parsing large events

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cbda991e210933a02da116f944b48225c33f6dde
* https://github.com/elastic/ia-trade-team/issues/122
None
> [Security Rules] Update security rules package to v8.8.2

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
- packages/infoblox_nios/manifest.yml
Fixes the way we split dns messages to take into account quoted values of the split character.
> [infoblox_nios] Fix dns.answers processing

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/index_recovery/_dev/test/system/test-default-config.yml
- packages/elasticsearch/data_stream/index_recovery/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_summary/agent/stream/stream.yml.hbs
- packages/elasticsearch/manifest.yml
This PR fixes a bug caused by the fact that the `active.only` flag was not being forwarded to the index_recovery data stream configuration.
- Pull this branch
- run `elastic-package stack up`
- ` cd packages/elasticsearch && elastic-package service up`
- Toggle the "Fech active index only" flag
- When on, there shouldn't be any docs with `stage: DONE` in `metrics-elasticsearch.stack_monitoring.index_recovery-*` index
- When off there will be docs with `stage: DONE`
closes [#5466](https://github.com/elastic/integrations/issues/5466)
> [Elasticsearch] Forward active.only config to datastream config

- packages/ded/changelog.yml
- packages/ded/manifest.yml
- packages/dga/changelog.yml
- packages/dga/manifest.yml
- packages/lmd/changelog.yml
- packages/lmd/manifest.yml
- packages/problemchild/changelog.yml
- packages/problemchild/manifest.yml
With the new subcategory, make the UEBA packages more visible. Mockup visual:
* https://github.com/elastic/package-spec/issues/499
Update advanced_analytics_ueba category for 4 packages.
* Update version and changelog files
* Update the manifest file
-
> Update advanced_analytics_ueba category for 4 packages

- packages/nginx_ingress_controller/changelog.yml
- packages/nginx_ingress_controller/data_stream/access/fields/fields.yml
- packages/nginx_ingress_controller/docs/README.md
- packages/nginx_ingress_controller/manifest.yml
Change the mapping type of the field nginx_ingress_controller.access.upstream.name to fix an error on the overview dashboard of the integration `nginx_ingress_controller`. 
This error was preventing the `top upstreams` panel to correctly display any value
1. Setup a dev environment with elastic stack, fleet and kubernetes integration installe
2. install ingress-nginx helm chart from https://kubernetes.github.io/ingress-nginx
3. Add a demo application with the following manifests
deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name:  demo
labels:
app:  demo
spec:
selector:
matchLabels:
app: demo
replicas: 1
strategy:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 25%
type: RollingUpdate
template:
metadata:
labels:
app:  demo
spec:
containers:
- name: …
```
> Fix dashboard issue with integration nginx_ingress_controller

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-3912d9a0-bcb2-11ec-b64f-7dd6e8e82013.json
- packages/kubernetes/manifest.yml
When TSDB is disabled, there is a visualization that appears like this:
However, when enabling TSDB, the visualization stops working since "it is not possible to filter by `kubernetes.volume.fs.used.pct: *`". This PR fixes that so the visualization works the same in both modes.
> [Kubernetes][Dashboard] Update volume dashboard

- packages/nginx/changelog.yml
- packages/nginx/manifest.yml
- Bug
Add beta flag to NGINX 
- Relates https://github.com/elastic/obs-infraobs-team/issues/1043
> Add beta flag to nginx

- packages/prometheus_input/changelog.yml
- packages/prometheus_input/docs/README.md
- packages/prometheus_input/manifest.yml
- Bug
This PR fixes broken url's in prometheus input package readme. 
- Closes https://github.com/elastic/integrations/issues/6324
> Update urls in prometheues input package readme

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/audit/fields/agent.yml
- packages/microsoft_sqlserver/data_stream/audit/fields/ecs.yml
- packages/microsoft_sqlserver/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_sqlserver/data_stream/log/fields/agent.yml
- packages/microsoft_sqlserver/data_stream/log/fields/ecs.yml
- packages/microsoft_sqlserver/data_stream/performance/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_sqlserver/data_stream/performance/fields/agent.yml
- packages/microsoft_sqlserver/data_stream/performance/fields/ecs.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/fields/agent.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/fields/ecs.yml
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
It adds the following changes:
**Audit data stream**
- Add the requested field definitions. The ones that match ECS are included in `ecs.yml`. Otherwise, they have been added at `agent.yml` along with missing fields for `cloud` and `container`.
- Although `host.os.name` is defined in ECS, it has been included in `agent.yml` to avoid a conflict in the type of the `text` multi_field (`text` vs `match_only_text`) with the Log data stream.
**Log data stream**
- `host` ECS fields defined at `agent.yml` have been moved to `ecs.yml` for consistency.
**Performance data stream**
- Added missing `cloud` and `container` fields in agent.yml.
- Added `host` fields in ecs.yml for consistency.
**Transaction logs data stream**
- Added missing `cloud` and `container` fields in agent.yml.
- Added `host` …
> Add missing field definitions for the SQLServer integration

- packages/cloud_security_posture/changelog.yml
Changing the development version to 1.3.0
> [Cloud Posture] remove preview from 1.3.0 after release

- packages/sophos_central/changelog.yml
- packages/sophos_central/data_stream/alert/_dev/test/pipeline/test-pipeline-activity.log-expected.json
- packages/sophos_central/data_stream/alert/_dev/test/pipeline/test-user-formats.log-expected.json
- packages/sophos_central/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
- packages/sophos_central/data_stream/alert/sample_event.json
- packages/sophos_central/data_stream/event/sample_event.json
- packages/sophos_central/docs/README.md
- packages/sophos_central/manifest.yml
- Switch formats from epoch_* to UNIX*
- Switch one instance of UNIX to UNIX_MS (sophos_central.alert.data.threat_id.date), as incoming value was expressed in milliseconds
- Update package-spec version to 2.7.0
- Regen test expected files
```
```
> [sophos_central] Fix timestamp parsing and update package-spec version to 2.7.0

- packages/hid_bravura_monitor/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/hid_bravura_monitor/data_stream/winlog/elasticsearch/ingest_pipeline/default.yml
Remove trailing spaces. And use a block sequence instead of a flow sequence for remove processor. This was causing some issues when round-tripping the YAML while doing some programmatic edits to the integration.
> [hid_bravura_monitor] - Format ingest pipeline YAML

- packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
All (indented) characters are considered to be content, including white space characters. This causes the source in the YAML to match the source in the ingest processor.
https://yaml.org/spec/1.2.2/#812-literal-style
- Works around: https://github.com/goccy/go-yaml/issues/374
> [fortinet_fortigate] use YAML literal for script source

- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
All (indented) characters are considered to be content, including white space characters. This causes the source in the YAML to match the source in the ingest processor.
https://yaml.org/spec/1.2.2/#812-literal-style
- Works around: https://github.com/goccy/go-yaml/issues/374
> [Infoblox NIOS] use YAML literal for script source

- packages/aws/changelog.yml
- packages/aws/data_stream/kinesis/fields/fields.yml
- packages/aws/kibana/dashboard/aws-fac28650-7349-11e9-816b-07687310a99a.json
- packages/aws/manifest.yml
- Bug
Update AWS Metric visualizations with correct field names.
<html>
<body>
Old Field | New Field
-- | --
aws.ec2.cpu.total.pct | host.cpu.usage
aws.elb.metrics.Latency | aws.elb.metrics.Latency.avg
aws.elb.metrics.UnHealthyHostCount | aws.elb.metrics.UnHealthyHostCount.max
aws.lambda.metrics.Invocations | aws.lambda.metrics.Invocations.avg
aws.ecs.metrics.CPUUtilization | aws.ecs.metrics.CPUUtilization.avg
aws.ecs.metrics.CPUReservation | aws.ecs.metrics.CPUReservation.avg
</body>
</html>
- https://github.com/elastic/integrations/issues/6338
- https://github.com/elastic/integrations/issues/6222
> [O11y][AWS] Fix Incorrect fields in AWS Metrics Overview dashboard 

- packages/docker/changelog.yml
- packages/docker/data_stream/diskio/fields/fields.yml
- packages/docker/docs/README.md
- packages/docker/manifest.yml
Add counter metric type to `docker.diskio.reads.ops`, since it is a cumulative value. All others metrics already have a type.
> [Docker][Diskio] Add metric type

- packages/microsoft_sqlserver/_dev/build/docs/README.md
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
Add missing required information to the docs for Microsoft SQL Server integration.
This detail was already documented for the [Metricbeat MSSQL Module docs ](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-mssql.html#_permissionaccess_required_for_tables) and I've taken this detail directly from there.
- Closes https://github.com/elastic/integrations/issues/5397
> [DOCS] Update Microsoft SQL Server integration docs with required permissions to the database

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/810082937068da8791e9e9cd18a0629f0230b621
None
None
> [Security Rules] Update security rules package to v8.5.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/7e66b301db4657aadd6e53a4bd030b38d6102f38
* https://github.com/elastic/ia-trade-team/issues/130
None
> [Security Rules] Update security rules package to v8.6.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/9d2131357e843e17bea5cd5e7773c093ee0d6173
* https://github.com/elastic/ia-trade-team/issues/130
None
> [Security Rules] Update security rules package to v8.7.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/56cc01f4daf2a374e2f8303f9e40e8b4a4d42b57
* https://github.com/elastic/ia-trade-team/issues/130
None
> [Security Rules] Update security rules package to v8.8.3

- packages/mysql/_dev/deploy/docker/Dockerfile
- packages/mysql/_dev/deploy/docker/docker-compose.yml
- packages/mysql/_dev/deploy/docker/entrypoint.sh
- packages/mysql/_dev/deploy/variants.yml
- packages/mysql/changelog.yml
- packages/mysql/data_stream/performance/_dev/test/system/test-default-config.yml
- packages/mysql/data_stream/performance/sample_event.json
- packages/mysql/manifest.yml
- Enhancement
- This PR updates system test cases for the MySQL package.
- System tests are done in the supported versions mentioned in the `variants.yml` due to this [issue](https://github.com/elastic/beats/issues/25069).
Conversation for the same:- [Link](https://github.com/elastic/integrations/issues/4372#issuecomment-1567776226)
- Updated `sample_event.json` for the performance data stream.
- Move to integrations/packages/mysql directory.
- Run the following command to run the system tests. elastic-package test system
- Closes #4372
> [O11y][MySQL] Update system test cases

- packages/nagios_xi/changelog.yml
- packages/nagios_xi/data_stream/host/fields/fields.yml
- packages/nagios_xi/data_stream/service/fields/fields.yml
- packages/nagios_xi/docs/README.md
- packages/nagios_xi/manifest.yml
- Bug
- Update field description for host and service data streams fields.yml
- Update README.md with descriptions.
- Relates #6318
> [O11y] [Nagios XI] Update field description for host and service data stream

- packages/couchbase/changelog.yml
- packages/couchbase/manifest.yml
- Bug
Making the Sync gateway parameter optional, so user won't be forced to configure the Sync gateway host parameter if they are not using it.
- Relates #6248
> [O11y] [Couchbase] Make sync-gateway host optional

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/events/_dev/test/pipeline/test-mx-events.json-expected.json
- packages/cisco_meraki/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_meraki/data_stream/events/sample_event.json
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-airmarshal-events.log-expected.json
- packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/airmarshal.yml
- packages/cisco_meraki/data_stream/log/fields/ecs.yml
- packages/cisco_meraki/data_stream/log/sample_event.json
- packages/cisco_meraki/docs/README.md
- packages/cisco_meraki/manifest.yml
Updates package-spec version to 2.7.0
- Normalized `observer.mac` to array.
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=8.8 -format-version=2.7.0 packages/cisco_meraki
```
```
cd packages/cisco_meraki
```
> [cisco_meraki] - Update to package-spec 2.7.0

- packages/mongodb/_dev/deploy/docker/docker-compose.yml
- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/log/manifest.yml
- packages/mongodb/kibana/search/mongodb-bfc96a60-0a80-11e8-bffe-ff7d4f68cf94.json
- packages/mongodb/manifest.yml
- Bug
This PR updates the default path for mongoldb logs and also fix the dashboard to filter logs data specific to mongodb.log dataset.
- Closes #6114
> Fix mongodb logs overview dashboard and default logs path

- packages/zoom/changelog.yml
- packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
- packages/zoom/data_stream/webhook/manifest.yml
- packages/zoom/manifest.yml
This is an improvement of #6288 adding the following:
- Instead of hardcoding the CRC provider option for the Zoom integration, now it is exposed to users the option to enable it when configuring the integration.
- The reason of this change, is because a new option has been added called `crc.secret` at https://github.com/elastic/beats/pull/35604. This forces the user to add this secret token manually when setting up the integration.
- A new parameter `secret_header` has been added since now, Zoom allows verifying events with a custom header instead of using `Authorization` as a hardcoded one.
- Depends on https://github.com/elastic/beats/pull/35604
> Add CRC options when configuring Zoom integration

- packages/activemq/changelog.yml
- packages/activemq/data_stream/queue/fields/ecs.yml
- packages/activemq/data_stream/queue/fields/fields.yml
- packages/activemq/docs/README.md
- packages/activemq/manifest.yml
- Enhancement
Added TSDB dimensions for queue datastream of ActiveMQ package
> ActiveMQ Added dimension fields for queue datastream

- packages/checkpoint/_dev/build/docs/README.md
- packages/checkpoint/changelog.yml
- packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/checkpoint/docs/README.md
- packages/checkpoint/manifest.yml
Because Checkpoint reuse loguids, it is possible for two logged events to be given the same fingerprint. So use the segment_time as well in the fingerprint args. Also document that if collisions are important, the user should enable semi-unified logging on the device's dashboard.
- Fixes #6355
> checkpoint: avoid data loss from loguid collisions

- packages/ti_misp/_dev/deploy/docker/files/config.yml
- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
- packages/ti_misp/manifest.yml
The threat_attributes data stream was not breaking out of its pagination loop when an empty response was returned.
Fixes #6510
> [ti_misp] Fix threat_attributes pagination loop

- packages/symantec_endpoint/changelog.yml
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-policy-rfc3164-sep14-3ru7.log
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-policy-rfc3164-sep14-3ru7.log-expected.json
- packages/symantec_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/symantec_endpoint/data_stream/log/manifest.yml
- packages/symantec_endpoint/manifest.yml
Use the configured time zone offset when interpreting all times. Previously only the syslog header and log export header were interpreted using the time zone offset and other times within the event were treated as if the were UTC. Based on new information we now assume that all times are relative to the time zone offset.
Fixes #6499
> [symantec_endpoint] Parse all times relative to configured TZ offset

- packages/azure/changelog.yml
- packages/azure/kibana/dashboard/azure-1adf52d0-f50f-11eb-a831-732d3e9bbd43.json
- packages/azure/kibana/dashboard/azure-5ad41d90-f50e-11eb-a831-732d3e9bbd43.json
- packages/azure/manifest.yml
Migrating dashboard "Azure Spring Cloud System Logs" to Lens
Note: I have observed some issues with area plots, "Top 10 values" and "Hide zero values" options not taking effect in the latest stack versions, I am currently investigating why, seems like an issue on the visualization side so far. 
Screenshot before migration:
Screenshot after migration:
> Migrate  dashboard "Azure Spring Cloud System Logs" to Lens

- packages/aws/_dev/build/docs/README.md
- packages/aws/changelog.yml
- packages/aws/data_stream/apigateway_metrics/agent/stream/stream.yml.hbs
- packages/aws/data_stream/apigateway_metrics/manifest.yml
- packages/aws/data_stream/natgateway/manifest.yml
- packages/aws/data_stream/redshift/agent/stream/stream.yml.hbs
- packages/aws/data_stream/redshift/manifest.yml
- packages/aws/data_stream/transitgateway/manifest.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
Add `include_linked_accounts` into redshift and apigateway data streams.
> [aws] Add tags_filter and include_linked_accounts in missing metric data streams

- packages/http_endpoint/changelog.yml
- packages/http_endpoint/data_stream/generic/agent/stream/http.yml.hbs
- packages/http_endpoint/data_stream/generic/manifest.yml
- packages/http_endpoint/manifest.yml
Previously the value was being rendered directly without iteration, so we had a comma-separated list instead of a YAML sequence.
Also fix some copy-paste errors.
Computed config now:
```
- data_stream:
id: http_endpoint-http_endpoint-c69b6080-0996-11ee-9698-67a83ee16ff8
meta:
package:
name: http_endpoint
version: 1.9.1
name: http_endpoint-1
package_policy_id: c69b6080-0996-11ee-9698-67a83ee16ff8
policy:
revision: 7
revision: 1
streams:
- data_stream:
dataset: http_endpoint.generic
id: http_endpoint-http_endpoint.generic-c69b6080-0996-11ee-9698-67a83ee16ff8
include_headers:
- user-agent
- x-real-ip
listen_address: localhost
listen_port: 8080
publisher_pipeline.disable_host: true
ssl:
certificate: /etc/pki/client/cert.pem
enabled: false
key: /etc/pki/client/cert.key
tags: …
```
> http_endpoint: fix handling of include header config

- packages/windows/changelog.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
This allows DNS query responses to have no data as can be seen for example with SRV responses.
Test event provided in elastic/beats#35207.
- For #elastic/beats#35207
> windows: allow DNS query responses to have no data

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/data_stream/query/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/query/manifest.yml
- packages/prometheus/data_stream/remote_write/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/remote_write/manifest.yml
- packages/prometheus/manifest.yml
Adds processors settings to prometheus integration
> Add processors to prometheus

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c49b1fb2c72172dbd6724c66b7a31450d948912b
* https://github.com/elastic/ia-trade-team/issues/131
None
> [Security Rules] Update security rules package to v8.5.6

- packages/fleet_server/agent/input/agent.yml.hbs
- packages/fleet_server/changelog.yml
- packages/fleet_server/manifest.yml
Resolve https://github.com/elastic/fleet-server/issues/2689 
Fix fleet server integration to avoid `server:null` in template and allow to configure APM
I tried the following integration config and got APM working:
> [Fleet] Fix fleet server integration to avoid server:null in template

- packages/aws/_dev/build/docs/README.md
- packages/aws/changelog.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
This PR is to fix image link in AWS readme file: https://github.com/elastic/integrations/blob/db7028b3383c325063a473e45d45b51ddf628f73/packages/aws/docs/README.md#debug
> [aws] fix image link in README

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6352d52bc0ef568ca1753a8df66d0adb175b38a6
* https://github.com/elastic/ia-trade-team/issues/131
None
> [Security Rules] Update security rules package to v8.7.6

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/541cf2b529bcc98504ece2d35fa1982c02698557
* https://github.com/elastic/ia-trade-team/issues/131
None
> [Security Rules] Update security rules package to v8.8.4

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/log/fields/fields.yml
- packages/microsoft_sqlserver/data_stream/log/manifest.yml
- packages/microsoft_sqlserver/data_stream/performance/fields/fields.yml
- packages/microsoft_sqlserver/data_stream/performance/manifest.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/manifest.yml
- packages/microsoft_sqlserver/manifest.yml
- Enhancement
Migrates the integration data streams from BETA to GA
- performance
- transaction_log
- error_log
- Install the integration
- Run system and pipeline tests
- Verify the data loading in Kibana
- Verify the BETA flags are removed from the datastreams
- Closes #6056
> [Microsoft SQL Server] Migrate Microsoft SQL Server to GA

- packages/memcached/changelog.yml
- packages/memcached/manifest.yml
- Enhancement
Migrates the integration from BETA to GA
The testing guidelines and execution results are captured in this [issue](#6055)
- Closes #6055
> [MemCached] Migrate to GA

- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet.log-expected.json
- packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/event.yml
- packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/utm.yml
- packages/fortinet_fortigate/data_stream/log/fields/ecs.yml
- packages/fortinet_fortigate/data_stream/log/fields/fields.yml
- packages/fortinet_fortigate/data_stream/log/sample_event.json
- packages/fortinet_fortigate/docs/README.md
- packages/fortinet_fortigate/manifest.yml
This updates the fortinet_fortigate integration package to package-spec 2.7.0.
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=8.8 -format-version=2.7.0 packages/fortinet_fortigate
```
```
cd packages/fortinet_fortigate
```
> [fortinet_fortigate] - Update package-spec to 2.7.0

- packages/darktrace/changelog.yml
- packages/darktrace/data_stream/ai_analyst_alert/_dev/test/pipeline/test-ai-analyst-alert.log-expected.json
- packages/darktrace/data_stream/ai_analyst_alert/elasticsearch/ingest_pipeline/default.yml
- packages/darktrace/data_stream/ai_analyst_alert/sample_event.json
- packages/darktrace/data_stream/model_breach_alert/_dev/test/pipeline/test-model-breach-alert.log-expected.json
- packages/darktrace/data_stream/model_breach_alert/elasticsearch/ingest_pipeline/default.yml
- packages/darktrace/data_stream/model_breach_alert/sample_event.json
- packages/darktrace/data_stream/system_status_alert/_dev/test/pipeline/test-system-status-alert.log-expected.json
- packages/darktrace/data_stream/system_status_alert/elasticsearch/ingest_pipeline/default.yml
- packages/darktrace/data_stream/system_status_alert/sample_event.json
- packages/darktrace/docs/README.md
- packages/darktrace/manifest.yml
This updates the darktrace integration to package-spec 2.7.0.
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=8.8 -format-version=2.7.0 packages/darktrace
```
```
cd packages/darktrace
```
> [darktrace] - Update to package-spec 2.7.0

- packages/iptables/_dev/deploy/docker/Dockerfile
- packages/iptables/changelog.yml
- packages/iptables/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/iptables/manifest.yml
Modify iptables to correctly set `event.kind` for pipeline errors and ensure `error.message` is an array.
Change testing docker image to provide a journald that is compatible with beats.
- For #6582
- Fixes #6547
> iptables: ensure event.kind is correctly set for pipeline errors

- catalog-info.yaml
- packages/aws/changelog.yml
- packages/aws/kibana/dashboard/aws-98f85120-0ea4-11ee-9c37-e55025c0278a.json
- packages/aws/kibana/dashboard/aws-a4482820-03aa-11ee-84d4-7f15bab18041.json
- packages/aws/manifest.yml
- packages/ti_rapid7_threat_command/elasticsearch/ingest_pipeline/ti_rapid7_threat_command-cve-rule-transform-pipeline.yml
- packages/ti_rapid7_threat_command/elasticsearch/ingest_pipeline/ti_rapid7_threat_command-ioc-rule-transform-pipeline.yml
- packages/ti_rapid7_threat_command/elasticsearch/ingest_pipeline/ti_rapid7_threat_command-unique-ioc-transform-pipeline.yml
Modify ti_rapid7_threat_command integration to correctly set `event.kind` for pipeline errors and ensure `error.message` is an array.
* For #6582
> [ti_rapid7_threat_command] Ensure event.kind is correctly set for pipeline errors

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_alert.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_app_and_identity.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_email.yml
- packages/m365_defender/manifest.yml
- packages/mattermost/changelog.yml
- packages/mattermost/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/mattermost/manifest.yml
- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_defender_endpoint/manifest.yml
- packages/microsoft_dhcp/changelog.yml
- packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcp.yml
- packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcpv6.yml
- packages/microsoft_dhcp/manifest.yml
- packages/microsoft_exchange_online_message_trace/changelog.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_exchange_online_message_trace/manifest.yml
- packages/mysql_enterprise/changelog.yml
- packages/mysql_enterprise/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/mysql_enterprise/manifest.yml
Modify m365_defender, mattermost, microsoft_defender_endpoint, microsoft_dhcp, microsoft_exchange_online_message_trace and mysql_enterprise to correctly set `event.kind` for pipeline errors and ensure `error.message` is an array.
modsecurity is omitted as there is a pending PR to fix ingest in that package.
- For #6582
> m*: ensure event.kind is correctly set for pipeline errors

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
Adds a comment to the cloud security config file that the fetchers section is kept for BC, once we do not support a cloudbeat version < 8.10, this section can be removed.
- https://github.com/elastic/cloudbeat/pull/1033
> [Cloud security] Add a BC comment to config files

- packages/modsecurity/changelog.yml
- packages/modsecurity/data_stream/auditlog/_dev/test/pipeline/test-apache-audit.log-expected.json
- packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
- packages/modsecurity/manifest.yml
Apache provides these as an array of strings, but a flattened must be an object or array of objects. So promote the strings to an object with the string in the "value" field.
- Fixes #6579
> modsecurity: fix handling of apache audit.details field

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs
- packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
- packages/ti_misp/manifest.yml
For a given sequence of page requests, the later requests should use the same timestamp parameter as the initial page in the sequence.
This is achieved by setting a query string parameter in the initial request that will be ignored by MISP, and using that to set the correct timestamp in the `response.pagination` transforms. This is a workaround for the fact that [`reponse.pagination` transforms](https://www.elastic.co/guide/en/beats/filebeat/8.8/filebeat-input-httpjson.html#response-pagination) aren't provided direct access to the last request, but can access the URL via the last response.
When fetching data from MISP, we start at an earlier point (120 hours by default, 10 mins in testing) and page forward from that point. As items are received, item timstamps are recorded in [`httpjson` …
> [ti_misp] Keep the same timestamp for later pages

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/memcached/_dev/test/pipeline/test-common-config.yml
- packages/network_traffic/data_stream/memcached/_dev/test/pipeline/test-stats-responses.json
- packages/network_traffic/data_stream/memcached/_dev/test/pipeline/test-stats-responses.json-expected.json
- packages/network_traffic/data_stream/memcached/_dev/test/system/test-memcached-bin-tcp-stats-config.yml
- packages/network_traffic/data_stream/memcached/_dev/test/system/test-memcached-text-tcp-stats-config.yml
- packages/network_traffic/data_stream/memcached/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/memcached/fields/protocol.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
Fixes the Network Packet Capture integration to not drop events with memcached `STATS` response data, by using a flattened field to hold the stats data in a single object.
The Network Packet Capture integration currently fails to index events with memcached `STATS` response data,
as described in issue https://github.com/elastic/integrations/issues/6230.
The stats data in the event is an array of objects with `name` and `value` keys:
```
{
"memcache": {
"response": {
"stats": [
{
"name": "pid",
"value": "1"
},
{
"name": "uptime",
"value": "183329"
},
...
], ...
}, ...
}, ...
}
```
Many stat names are listed in the [memcached documentation](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L1229) (93 general-purpose statistics, and over 100 others). However, actual …
> [network_traffic] Fix to index events with memcached stats responses

- packages/sophos/changelog.yml
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-anti-spam.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-anti-virus-ftp.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-anti-virus-smtp.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-anti-virus-web.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-atp-firewall.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-authentication.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-content-filtering-http.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-content-filtering-web-content-policy.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-firewall.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-idp.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-sandstorm.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-systemhealth.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-18-5-wireless.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-xg-cfilter-new.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-xg-event-new.log-expected.json
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-xg-firewall-new.log-expected.json
- packages/sophos/data_stream/xg/agent/stream/log.yml.hbs
- packages/sophos/data_stream/xg/agent/stream/tcp.yml.hbs
- packages/sophos/data_stream/xg/agent/stream/udp.yml.hbs
- packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
- packages/sophos/data_stream/xg/fields/fields.yml
- packages/sophos/data_stream/xg/manifest.yml
- packages/sophos/docs/README.md
- packages/sophos/manifest.yml
Ensure fields that have been defined as date are parseable as date. Also add timezone configuration and progressively determine timezone from logs, config, locale.
- Fixes #6546
> sophos: fix handling of date parsing

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Adds the `aws.account_type` enum option which can take the `single_account` and `organization_account` values.
- Relates https://github.com/elastic/cloudbeat/issues/1037
- Relates https://github.com/elastic/cloudbeat/pull/1072
> [Cloud Security] [AWS Orgs] Add config option

- packages/statsd_input/agent/input/input.yml.hbs
- packages/statsd_input/changelog.yml
- packages/statsd_input/manifest.yml
- Bug
While debugging why the client is not able to send data to the statsd_input's spawned server, I found that the configuration used is incorrect making the server listen on a default IP which is not always correct unless someone uses the standalone elastic-agent. Also, accepting multiple hosts for a server doesn't make sense and that's why also only one host is considered in metricbeat module side of beats. Also, the IP shouldn't have `http://` prefix and it should be without it.
Found this when trying to send data using a statsd client from a different container which is part of the same network as of elastic-agent's container. Also made a toy UDP server to check if it receiving the packets in the same container but metricbeat was not receiving them.  When checking with tcpdump, I …
> statsd_input: Fix config to take `host` instead of `hosts`

- packages/docker/changelog.yml
- packages/docker/data_stream/container/manifest.yml
- packages/docker/data_stream/cpu/manifest.yml
- packages/docker/data_stream/diskio/manifest.yml
- packages/docker/data_stream/healthcheck/manifest.yml
- packages/docker/data_stream/image/manifest.yml
- packages/docker/data_stream/info/manifest.yml
- packages/docker/data_stream/memory/manifest.yml
- packages/docker/data_stream/network/fields/fields.yml
- packages/docker/data_stream/network/manifest.yml
- packages/docker/manifest.yml
Enable TSDB by default in all metrics data streams, except for events.
Relates to https://github.com/elastic/integrations/issues/6393
> [Docker] Enable TSDB by default

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.5.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6c207df3867c64c78f75a77617ea02fed1c7f16c
None
> [Security Rules] Update security rules package to v8.5.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/5f9e269636ffce2b7035f7775264c71585a08833
None
> [Security Rules] Update security rules package to v8.6.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b2227164b77bfce27170cc24dcb513965156eebd
* https://github.com/elastic/kibana/pull/160680#issuecomment-1610244767
> [Security Rules] Update security rules package to v8.7.7

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat_attributes/elasticsearch/ingest_pipeline/default.yml
- packages/ti_misp/manifest.yml
This PR fix the fingerprint processor on the MISP Attributes Ingest Pipeline, it was making a reference to a field that does not exist in the document.
- Closes #6686
> [ti_misp] fix the fingerprint processor for the attributes pipeline.

- packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-ubuntu-8-0-15.log
- packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-ubuntu-8-0-15.log-expected.json
- packages/mysql/data_stream/slowlog/elasticsearch/ingest_pipeline/default.json
- Bug
Changes deduplicate the list and only keep the unique elements. After this, if only 1 element remains, then it's added to the result as a single element (a string) and if not, the list is kept in the result with unique elements. This handling is done to manage the new behaviour of the grok processor in 8.7.x+. Read the related issue for more details.
- Closes #6016
> mysql: Add script processor to fix grok behaviour of ES 8.7.x+

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/edacb4b82c10c91076fba7372f8b4027c41bde3b
* https://github.com/elastic/kibana/pull/160680#issuecomment-1610429642
> [Security Rules] Update security rules package to v8.8.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/77e5b274d86c1ee66e7ea85c73bcbf938cbaebc6
* https://github.com/elastic/ia-trade-team/issues/135
None
> [Security Rules] Update security rules package to v8.9.1

- packages/haproxy/changelog.yml
- packages/haproxy/data_stream/log/_dev/test/pipeline/test-default.log-config.yml
- packages/haproxy/data_stream/log/_dev/test/pipeline/test-default.log-expected.json
- packages/haproxy/data_stream/log/agent/stream/log.yml.hbs
- packages/haproxy/data_stream/log/agent/stream/syslog.yml.hbs
- packages/haproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/haproxy/data_stream/log/manifest.yml
- packages/haproxy/manifest.yml
HAproxy mostly does not log with a timezone by default, and we hardcode add_local after any custom processors, so its not possible to override the local timezone.
The PR adds the common timezone offset which we use in other integration + changes the order of add_locale to be before custom processors.
> [HAProxy] Add timezone offset support

- packages/haproxy/changelog.yml
- packages/haproxy/data_stream/log/manifest.yml
- packages/haproxy/manifest.yml
Followup on the older PR https://github.com/elastic/integrations/pull/6767, the UTC default is unecessary and should have been removed.
> [HAProxy] Remove uncessary Timezone default in manifest

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/ecs.yml
- packages/osquery_manager/manifest.yml
Fixed the ```elf.sections``` mapping to make it ```nested```.
Before this change:
```
"elf": {
"properties": {
"creation_date": {
"type": "date"
},
"header": {
"properties": {
"entrypoint": {
"type": "long"
}
}
},
"sections": {
"properties": {
"chi2": {
"type": "long"
},
"entropy": {
"type": "long"
},
"physical_size": {
"type": "long"
},
"virtual_address": {
"type": "long"
},
"virtual_size": {
"type": "long"
}
}
}
}
}  
```
After the change (note the ```"type": "nested",```:
```
{
"elf": {
"properties": {
"creation_date": {
"type": "date"
},
"header": {
"properties": {
"entrypoint": {
"type": "long"
}
}
},
"sections": {
"type": "nested",
"properties": {
"chi2": {
"type": "long"
},
"entropy": {
"type": "long"
},
"physical_size": {
"type": "long"
},
"virtual_address": {
"type": "long"
}, …
```
> Fix elf.sections mapping to nested

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Update the CloudFormation template version to increase EC2 root volume disk to 32 Gb.
- Resolves: https://github.com/elastic/cloudbeat/issues/1098
> [CNVM] CloudFormation template increase disk size

- packages/sophos/changelog.yml
- packages/sophos/data_stream/xg/agent/stream/log.yml.hbs
- packages/sophos/manifest.yml
Fixes indentation in the log config yml/hbs.
- Fixes #6690
> sophos: fix log config indentation

- packages/iis/changelog.yml
- packages/iis/kibana/dashboard/iis-4b975820-85a1-11ea-91bc-ab084c7ec0e7.json
- packages/iis/kibana/dashboard/iis-ebc23240-8572-11ea-91bc-ab084c7ec0e7.json
- packages/iis/manifest.yml
- Bug
This PR updates the aggregator function from average to max for few counter fields of IIS visualisations.
- Relates #6267
> [IIS] update visualisation for counter fields

- packages/aws/changelog.yml
- packages/aws/data_stream/billing/manifest.yml
- packages/aws/data_stream/dynamodb/manifest.yml
- packages/aws/data_stream/ebs/manifest.yml
- packages/aws/data_stream/ecs_metrics/manifest.yml
- packages/aws/data_stream/elb_metrics/manifest.yml
- packages/aws/data_stream/firewall_metrics/manifest.yml
- packages/aws/data_stream/kinesis/manifest.yml
- packages/aws/data_stream/lambda/manifest.yml
- packages/aws/data_stream/natgateway/manifest.yml
- packages/aws/data_stream/rds/manifest.yml
- packages/aws/data_stream/redshift/manifest.yml
- packages/aws/data_stream/s3_storage_lens/manifest.yml
- packages/aws/data_stream/sns/manifest.yml
- packages/aws/data_stream/sqs/manifest.yml
- packages/aws/data_stream/transitgateway/manifest.yml
- packages/aws/data_stream/vpn/manifest.yml
- packages/aws/manifest.yml
Enable time series data streams for the metrics datasets:
- Billing
- DynamoDB
- EBS
- ECS
- ELB
- Firewall
- Kinesis
- Lambda
- NAT gateway
- RDS
- Redshift
- S3 Storage Lens
- SNS
- SQS
- Transit Gateway
- VPN.
> [AWS] Enable TSDB for some metric datasets - Part 1

- .ci/Jenkinsfile
This PR adds the needed environment variables to remove docker-compose logs (pull and up subcommands), so they are available for the next elastic-package version.
- Tested with the changes from https://github.com/elastic/elastic-package/pull/1330 in this CI job with just a few packages: https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-6742/2/pipeline
Run in one of the packages in this repository with the variables defined. For instance
```bash
export ELASTIC_PACKAGE_COMPOSE_DISABLE_ANSI=true
export ELASTIC_PACKAGE_COMPOSE_DISABLE_PULL_PROGRESS_INFORMATION=true
elastic-package stack up -v -d
elastic-package stack test -v
elastic-package stack down
```
- Relates https://github.com/elastic/elastic-package/pull/1330 , …
> Add env. vars to manage docker output in CI jobs

- packages/1password/changelog.yml
- packages/1password/kibana/dashboard/1password-audit-events-full-dashboard.json
- packages/1password/kibana/dashboard/1password-item-usages-full-dashboard.json
- packages/1password/kibana/dashboard/1password-signin-attempts-full-dashboard.json
- packages/1password/kibana/search/1password-audit-events.json
- packages/1password/kibana/search/1password-item-usages.json
- packages/1password/kibana/search/1password-signin-attempts.json
- packages/1password/manifest.yml
> 1password: convert to lens

- packages/ti_util/changelog.yml
- packages/ti_util/kibana/dashboard/ti_util-9eff2529-fff5-4064-b825-fa089f260bfa.json
- packages/ti_util/manifest.yml
This PR updates two panels in the ti_util dashboard per updates in 8.x described [here](https://www.elastic.co/guide/en/security/8.0/whats-new.html#index-updates-8.0).
1.  Switch index from `.siem-signals-<space-id>` to `.alerts-security.alerts-<space-id>` 
2. Switch filter field from `signal.rule.name` to `kibana.alert.rule.name`
> TI Util package fix incorrect index in dashboard

- packages/bluecoat/changelog.yml
- packages/bluecoat/manifest.yml
- packages/juniper_junos/changelog.yml
- packages/juniper_junos/manifest.yml
- packages/juniper_netscreen/changelog.yml
- packages/juniper_netscreen/manifest.yml
Deprecates bluecoat, juniper_junos and juniper_netscreen.
- Closes #6789
- Closes #6790
- Closes #6791
> bluecoat,juniper_junos,juniper_netscreen: deprecate packages

- packages/vsphere/_dev/build/build.yml
- packages/vsphere/changelog.yml
- packages/vsphere/data_stream/datastore/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/data_stream/datastore/manifest.yml
- packages/vsphere/data_stream/datastore/sample_event.json
- packages/vsphere/data_stream/host/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/data_stream/host/manifest.yml
- packages/vsphere/data_stream/host/sample_event.json
- packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log-expected.json
- packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/data_stream/log/sample_event.json
- packages/vsphere/data_stream/virtualmachine/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/data_stream/virtualmachine/manifest.yml
- packages/vsphere/data_stream/virtualmachine/sample_event.json
- packages/vsphere/docs/README.md
- packages/vsphere/manifest.yml
- Enhancement
This PR enables TSDB for Vsphere.
- Relates #6152
> [VSphere] Tsdb enabled release

- packages/airflow/changelog.yml
- packages/airflow/data_stream/statsd/fields/fields.yml
- packages/airflow/docs/README.md
- packages/airflow/manifest.yml
- Enhancement
This PR adds metric_type mapping for the fields of statsD datastream.
- Closes #6729
> [Airflow] Add metrictype mapping for the fields of statsd datastream.

- packages/mysql/changelog.yml
- packages/mysql/kibana/visualization/mysql-493e8460-630d-11ea-a83e-25b8612d00cc.json
- packages/mysql/manifest.yml
- Bug
The dashboard uses avg function on field having metric_type value `counter`. This is not a supported feature. The PR updates to use the max() function instead.
Dashboard testing
-
> [MySql] Fix to correct the aggregate function used in dashboard

- packages/activemq/changelog.yml
- packages/activemq/data_stream/log/manifest.yml
- packages/activemq/manifest.yml
Revert back changes from issue https://github.com/elastic/kibana/pull/157897. 
Removing the following configs from the activemq package manifest
```
elasticsearch.dynamic_dataset: true
elasticsearch.dynamic_namespace: true
```
We would like to revert these permissions in favour of creating a separate input package to reroute traffic from Activemq. 
The idea is that we would like to have datastream-based integrations to monitor a specific application, while we should have input packages instead to reroute "mixed" traffic (from different sources) from that application.
The datastream `log` is actually looking at the activemq application logs, not at the traffic from activemq. This is why it doesn't make sense to allow rerouting for this package. Those logs should be in a fixed location …
> Activemq package: revert back change to dynamic_dataset/namespace

- packages/aws_logs/changelog.yml
- packages/aws_logs/data_stream/generic/manifest.yml
- packages/aws_logs/manifest.yml
Add permissions to write to logs-*-*. Same changes as in this issue https://github.com/elastic/kibana/pull/157897. 
```
elasticsearch:
dynamic_dataset: true
dynamic_namespace: true
```
Similar change was applied to aws package and then reverted at https://github.com/elastic/integrations/pull/6806. That was the wrong package to modify.
This package aws_log is instead the right one, since it should reroute the traffic from AWS logs in cloudwatch
- Relates https://github.com/elastic/kibana/pull/157897
> aws_logs package: allow reroute to logs-*-*

- README.md
Fox broken hyperlink for redirecting to Package Specification that is found further down on the README.md.
> [docs] Fix broken link to Package Specification section

- .ci/schedule-daily.groovy
As a minor improvement into the visibility of failures in the daily integration job, attempt to enable Slack notifications.
From digging into the [pipeline library](https://github.com/elastic/apm-pipeline-library/blob/main/vars/notifyBuildResult.groovy#L34), the current config is missing `slackComment: true` when notifying on the build status.
Relates to #6071.
> [ci] Enable Slack notifications on daily job status

- packages/awsfargate/changelog.yml
- packages/awsfargate/data_stream/task_stats/fields/fields.yml
- packages/awsfargate/docs/README.md
- packages/awsfargate/manifest.yml
Add metric type to fields.
Please check:
- `core.*.ticks` - counter?
- `memory.commit.total` - Counter?
- `memory.commit.peak` - Counter?
- `*.wait_time`, `*.service_time` and `*.queued` - is it correct that they are all counters?
- `*.private_working_set.total` - Is it a gauge? Seems like a current value that goes up and down.
**_Important_**: If `awsfargate.task_stats.diskio.read.bytes` and `awsfargate.task_stats.diskio.write.bytes` are in fact counters, then the dashboard will break since they are using the unsupported aggregation `average`.
Relates to https://github.com/elastic/integrations/issues/6732.
> [AWS Fargate] Add metric type to fields

- packages/kafka_log/changelog.yml
- packages/kafka_log/data_stream/generic/manifest.yml
- packages/kafka_log/manifest.yml
Add permissions to write to logs-*-*. Same changes as in this issue https://github.com/elastic/kibana/pull/157897. 
```
elasticsearch:
dynamic_dataset: true
dynamic_namespace: true
```
Similar change was applied to kafka package and then reverted at https://github.com/elastic/integrations/pull/6803. That was the wrong package to modify.
This package kafka_log is instead the right one, since it should reroute the traffic from Kafka
- Relates https://github.com/elastic/kibana/pull/157897
> Kafka_log package: allow reroute to logs-*-*

- packages/kafka/changelog.yml
- packages/kafka/data_stream/log/manifest.yml
- packages/kafka/manifest.yml
Revert back changes from issue https://github.com/elastic/kibana/pull/157897. 
Removing the following configs from the system package manifest
```
elasticsearch.dynamic_dataset: true
elasticsearch.dynamic_namespace: true
```
This change is reverted as for monitoring Kafka is not needed. The logs that are collected by the datastream kafka.log are written by the Kafka service and must go to a specific dataset for the integration to work.
There is a kafka_log package that reads topics from Kafka. This is the scenario where routing is needed to sort the data into different data streams.
The change of adding the permissions was made with the assumption this is the kafka_log package, but it isn't so it must be reverted.
The change only affects users using Fleet and will change back the API …
> Kafka package: revert back change to dynamic_dataset/namespace

- packages/sonicwall_firewall/_dev/build/build.yml
- packages/sonicwall_firewall/changelog.yml
- packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-drizzthacker.log-expected.json
- packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-general.log-expected.json
- packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-nat.log-expected.json
- packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-sonicos70-aws.log-expected.json
- packages/sonicwall_firewall/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/sonicwall_firewall/data_stream/log/sample_event.json
- packages/sonicwall_firewall/docs/README.md
- packages/sonicwall_firewall/manifest.yml
- Updates the package-spec version to `2.9.0`
- Ensure `observer.ip` is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=8.8 -format-version=2.9.0 packages/sonicwall_firewall
```
> [sonicwall_firewall] - update package-spec to 2.9.0

- packages/hid_bravura_monitor/changelog.yml
- packages/hid_bravura_monitor/data_stream/winlog/fields/ecs.yml
- packages/hid_bravura_monitor/docs/README.md
- packages/hid_bravura_monitor/manifest.yml
The `winlog` input can produce error.code under some conditions so make sure their is a mapping present for the field that is aligned to ECS.
Relates #6766
> [hid_bravura_monitor.winlog] Add ECS error.code mapping

- packages/netskope/changelog.yml
- packages/netskope/data_stream/events/fields/fields.yml
- packages/netskope/docs/README.md
- packages/netskope/manifest.yml
Removes `netskope.events.region` and `netskope.events.region.id`. These fields are not used and cause a mapping conflict.
- Closes #6705
> netskope: remove netskope.events.region and netskope.events.region.id

- packages/cel/_dev/test/system/test-basic-auth-config.yml
- packages/cel/_dev/test/system/test-get-config.yml
- packages/cel/_dev/test/system/test-oauth-config.yml
- packages/cel/_dev/test/system/test-oauth-scope-config.yml
- packages/cel/agent/input/input.yml.hbs
- packages/cel/changelog.yml
- packages/cel/manifest.yml
This exposes the redact.fields and redact.delete options of the CEL input configuration. The redact.delete option is always sent to ensure that the CEL input will receive a redact config object as this is planned to be made a required configuration option there.
-
> cel: make debug log field redactions available

- packages/windows/changelog.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
Adds a test case for sysmon 15.0/event 29.
- Closes #6748
> windows: add support for sysmon 15.0/event 29

- packages/azure/changelog.yml
- packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
- packages/azure/manifest.yml
This is the same fix as in #5361, but for the `url.path` field.
Open the dev tools and run the following query to simulate a request:
```
POST _ingest/pipeline/logs-azure.application_gateway-1.5.25/_simulate
{
"docs": [
{
"_source": {
"json": {
"properties": {
"requestUri": "https://example.com"
}
},
"url": {
"path": "https://elastic.co"
}
}
}
]
}
```
-
> [azure] Ensure url.path cannot be duplicated

- packages/windows/changelog.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/sample_event.json
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Sets `event.action` to the event's sysmon name.
Event details from https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon.
- For https://github.com/elastic/integrations/pull/6761#discussion_r1256488180
> windows: set event.action to the event's sysmon name

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/tls/fields/protocol.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
> network_traffic: fix mapping for tls.detailed.{client,server}_certificate_chain

- packages/aws/changelog.yml
- packages/aws/data_stream/usage/manifest.yml
- packages/aws/manifest.yml
Enable TSDB for AWS Usage by default.
> [AWS Usage] Enable TSDB by default

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/index/manifest.yml
- packages/elasticsearch/data_stream/index_recovery/manifest.yml
- packages/elasticsearch/data_stream/index_summary/manifest.yml
- packages/elasticsearch/data_stream/ingest_pipeline/manifest.yml
- packages/elasticsearch/data_stream/ml_job/manifest.yml
- packages/elasticsearch/data_stream/node/manifest.yml
- packages/elasticsearch/data_stream/node_stats/manifest.yml
- packages/elasticsearch/manifest.yml
Enable TSDB by default. Please refer to https://github.com/elastic/integrations/issues/6618 for more information.
Relates to https://github.com/elastic/integrations/issues/6618.
> [Elasticsearch] Enable TSDB by default

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat_attributes/elasticsearch/ingest_pipeline/default.yml
- packages/ti_misp/manifest.yml
Retains the `misp.attribute.value` when the `misp.attribute.type` is "email-subject".
This cannot be tested because the current pipeline sets `threat.indicator.type` to "email-message" for emails and this is not a valid value for this field according to the ECS definition.
- Fixes #6598
> ti_misp: retain email subjects in misp.attribute

- packages/fortinet_fortimanager/changelog.yml
- packages/fortinet_fortimanager/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/sentinel_one_cloud_funnel/changelog.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-common-config.yml
Elasticsearch 8.9 includes a fix to correctly handle epoch_millis formatted timestamps in the date ingest pipeline processor. This causes pipeline checks to fails in integrations where the timestamp now parsed accurately. So temporarily relax the test constraints on date fields while version skew exists.
- Fixes #6850
> fortigate_fortimanager,sentinel_one_cloud_funnel: relax date tests

- packages/auth0/changelog.yml
- packages/auth0/kibana/dashboard/auth0-29fb7200-4062-11ec-b18d-ef6bf98b26bf.json
- packages/auth0/kibana/search/auth0-629b19e0-4061-11ec-b18d-ef6bf98b26bf.json
- packages/auth0/manifest.yml
> auth0: convert visualisations to lens

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-f4dc26db-1b53-4ea2-a78b-1bfab8ea267c.json
- packages/kubernetes/manifest.yml
- Bug
Updates the index pattern as per discussion here: https://github.com/elastic/integrations/pull/6603#issuecomment-1630781078
- Relates https://github.com/elastic/integrations/pull/6603
> Updating index pattern to match ccs scenario

- packages/google_workspace/changelog.yml
- packages/google_workspace/kibana/dashboard/google_workspace-3be0b490-3430-11ed-9f31-c9178ccae8cd.json
- packages/google_workspace/kibana/dashboard/google_workspace-f8210e80-3b28-11ed-8bdd-f5c5df6c1370.json
- packages/google_workspace/kibana/search/google_workspace-1cac9ed0-3b2f-11ed-8bdd-f5c5df6c1370.json
- packages/google_workspace/kibana/search/google_workspace-2c40f770-3b24-11ed-8bdd-f5c5df6c1370.json
- packages/google_workspace/manifest.yml
- Updated the visualizations of Google Workspace dashboards to Lens
- The screenshots were not updated since the integration already contains 7 screenshots and converted visualisations don't appear in them
- Part of #6787
**Before**
**After**
> [Google Workspace] Convert visualisations to Lens

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/19e44a28e47fb3998ac2b4fabb09f6958207f7bf
* https://github.com/elastic/ia-trade-team/issues/136
None
> [Security Rules] Update security rules package to v8.7.9

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/5e7ae6254ff0cd0d196f7d2e21ef171322ff5b81
None
None
> [Security Rules] Update security rules package to v8.8.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.2-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cd50e36aa71d397a2da96aadc78678cd66abe18e
* https://github.com/elastic/ia-trade-team/issues/136
None
> [Security Rules] Update security rules package to v8.9.2-beta.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/24790232c9cae358b27c0f07705d60eb5e6c4568
* https://github.com/elastic/ia-trade-team/issues/136
None
> [Security Rules] Update security rules package to v8.9.2

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/data_stream/log/sample_event.json
- packages/cisco_ios/docs/README.md
- packages/cisco_ios/manifest.yml
Fix grok to allow string fman_fp_image to be optionally included.
Added tests.
- Relates #6919
- Relates #6680
> [cisco_ios] Fix grok to be aware of fman_fp_image

- packages/aws/changelog.yml
- packages/aws/data_stream/apigateway_metrics/fields/ecs.yml
- packages/aws/data_stream/apigateway_metrics/fields/fields.yml
- packages/aws/docs/apigateway.md
- packages/aws/manifest.yml
Set the dimension fields for API Gateway data stream.
The dimension fields are:
- ECS fields (decision for these fields is [here](https://github.com/elastic/integrations/issues/5193#issuecomment-1536090359)):
- agent.id
- cloud.account.id
- cloud.region
- Other fields:
- aws.dimensions.ApiId
- aws.dimensions.ApiName
- aws.dimensions.Method
- aws.dimensions.Resource
- aws.dimensions.Route
- aws.dimensions.Stage
Passed the [tests](https://github.com/elastic/TSDB-migration-test-kit) with 2 elastic agents running at the same time.
> [AWS][API Gateway] Set dimension fields

- packages/sql_input/agent/input/input.yml.hbs
- packages/sql_input/changelog.yml
- packages/sql_input/docs/README.md
- packages/sql_input/manifest.yml
- Enhancement
This PR adds the merge_results feature to SQL Input Package. 
- Closes https://github.com/elastic/integrations/issues/6896
Two queries for MYSQL 
Metrics of both queries merged in single event
> sql_input: Add `merge_results` feature to SQL Input package

- packages/sentinel_one/changelog.yml
- packages/sentinel_one/kibana/dashboard/sentinel_one-0dd17490-bbb8-11ec-82b7-8fcb232e9538.json
- packages/sentinel_one/manifest.yml
- Updated the visualisations of the Threat dashboard to Lens
- Part of #6787
Two visualisation changed that don't affect screenshots:
**Before**
**After**
> [Sentinel One] Convert visualisations to Lens

- packages/ti_util/changelog.yml
- packages/ti_util/kibana/dashboard/ti_util-9eff2529-fff5-4064-b825-fa089f260bfa.json
- packages/ti_util/manifest.yml
This updates the filter for two lens visualizations on the dashboard to use the current rule names.
In 8.8 we deprecated the existing rules in favor of [new, more specific names](https://www.elastic.co/guide/en/security/current/prebuilt-rule-8-8-6-prebuilt-rules-8-8-6-summary.html). This change was then backported to 8.5. So, this PR updates those names and sets the min version to 8.5
For more context, see https://elastic.slack.com/archives/C02TNUE3P6F/p1688126475454089
-
> updating rule names to match current

- packages/aws/changelog.yml
- packages/aws/data_stream/emr_metrics/fields/ecs.yml
- packages/aws/data_stream/emr_metrics/fields/fields.yml
- packages/aws/docs/emr.md
- packages/aws/manifest.yml
The data stream already had the metric type defined for the metric fields. However, they were not according to TSDB baselines and they had the same problem as described in https://github.com/elastic/integrations/pull/6952: 
> 
> All metric fields are calculated through an aggregation (sum or avg). However, this is only for a given timestamp. On the next timestamp, new values will be used on the final aggregation and so on.
> 
> Because of this, the value for some field, 4XXError.sum for example, does not relate to the next 4XXError.sum field. The values are not cumulative over the different timestamps, and that is a requirement for a counter field.
> 
> All metric fields are gauge in this data stream.
The ECS dimension fields chosen in …
> [AWS][EMR] Update metric type and set dimensions fields

- packages/memcached/changelog.yml
- packages/memcached/data_stream/stats/fields/ecs.yml
- packages/memcached/docs/README.md
- packages/memcached/kibana/dashboard/memcached-a36fa0b0-eccf-11ec-b66b-6bfdc9ecc703.json
- packages/memcached/manifest.yml
- Enhancement
Add dimension fields for stats datastream
https://github.com/elastic/integrations/issues/6925
> [memcached] Add dimension fields to stats datastream

- docs/developer_workflow_design_build_test_integration.md
This PR updates the docs related to release a batch of Pull Request under the same version.
Rendered version of the doc [here](https://github.com/mrodm/integrations/blob/update_docs_next_version_group/docs/developer_workflow_design_build_test_integration.md)
> Update docs about grouping PRs in next version

- packages/aws/changelog.yml
- packages/aws/data_stream/apigateway_metrics/manifest.yml
- packages/aws/data_stream/emr_metrics/manifest.yml
- packages/aws/manifest.yml
Enable TSDB by default for API Gateway and EMR data streams
> [AWS] Enable TSDB by default for API Gateway and EMR data streams

- packages/system/changelog.yml
- packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-expected.json
- packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log-expected.json
- packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log-expected.json
- packages/system/data_stream/auth/_dev/test/pipeline/test-timestamp.log-expected.json
- packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
- packages/system/manifest.yml
Enriches event fields for pam session and auth messages and for process-related auth messages.
- Closes #6550
> system: improve event.{action,category,outcome} enrichment for auth datastream

- packages/awsfargate/changelog.yml
- packages/awsfargate/data_stream/task_stats/manifest.yml
- packages/awsfargate/manifest.yml
Enable TSDB by default.
Relates to https://github.com/elastic/integrations/issues/6732.
> [AWS Fargate] Enable TSDB by default

- packages/trellix_epo_cloud/changelog.yml
- packages/trellix_epo_cloud/data_stream/event/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/manifest.yml
The `now` global is currently static for the life of the filebeat CEL input meaning that it may be potentially many hours in the past. Fix this by using the dynamic `now()` function which is evaluated at the time of the sub-expression's evaluation.
See elastic/beats#36107 for details.
In this case the work-around is not really any different to using the `now` global once elastic/beats#36107 is merged and released, but this should be reverted as after that as in the general case, the `now()` function should be avoided unless needed.
- Relates https://github.com/elastic/integrations/pull/6621#discussion_r1266898025
- Relates elastic/beats#36107
> trellix_epo_cloud: work around static CEL now global behaviour

- packages/gcp/changelog.yml
- packages/gcp/manifest.yml
Just a small nit to make the manifest owner the same as azure/aws, while both teams are owners in the CODEOWNERS file already.
> [GCP] change ownership in manifest

- packages/istio/changelog.yml
- packages/istio/kibana/dashboard/istio-f0f863b0-5941-11ed-bfb8-bbfe5b338339.json
- packages/istio/manifest.yml
Update "Pilot xds expired" visualization to use last value instead of average.
"Pilot xds expired" visualization uses a counter metric, `istio.istiod.metrics.pilot_xds_expired_nonce.counter`. Currently, that metric is being used with an unsupported aggregation, `average`. Since we want to migrate this integration to TSDB we have to fix that. The solution is to use `last_value` and break the visualization by the label (see screenshot section).
Relates to https://github.com/elastic/integrations/issues/6567.
Currently the visualization looks like this:
With the change in this PR, it will look like this:
> [Istio] Update "Pilot xds expired" visualization

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Direct the user to different cloud formation templates instead of a single template with params
- Closes https://github.com/elastic/cloudbeat/issues/1122
- Relates https://github.com/elastic/cloudbeat/pull/1125
> [cloud_security_posture] Seperate cloud formation templates for CSPM and CNVM

- packages/cloud_security_posture/changelog.yml
Remove the preview tags from the 1.4.x integration's version before the 8.9 release.
> [Cloud Security Posture] Remove preview tag before the 8.9 release

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/collstats/manifest.yml
- packages/mongodb/data_stream/dbstats/manifest.yml
- packages/mongodb/data_stream/metrics/manifest.yml
- packages/mongodb/data_stream/replstatus/manifest.yml
- packages/mongodb/data_stream/status/manifest.yml
- packages/mongodb/manifest.yml
- Enhancement
This PR enables TSDB for MongoDB module.
- Relates #6152
> [MongoDB] Enable TSDB

- packages/jamf_compliance_reporter/changelog.yml
- packages/jamf_compliance_reporter/data_stream/log/sample_event.json
- packages/jamf_compliance_reporter/docs/README.md
- packages/jamf_compliance_reporter/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/jamf_compliance_reporter
```
> [jamf_compliance_reporter] - update package spec to 2.9.0

- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/data_stream/audit/fields/fields.yml
- packages/hashicorp_vault/data_stream/audit/sample_event.json
- packages/hashicorp_vault/data_stream/log/sample_event.json
- packages/hashicorp_vault/data_stream/metrics/sample_event.json
- packages/hashicorp_vault/docs/README.md
- packages/hashicorp_vault/manifest.yml
Updates package spec to 2.9.0
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/hashicorp_vault
```
> [hashicorp_vault] - update package spec to 2.9.0

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log-expected.json
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox_nios/data_stream/log/sample_event.json
- packages/infoblox_nios/docs/README.md
- packages/infoblox_nios/manifest.yml
- Ensure host.ip is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/infoblox_nios
```
> [infoblox_nios] - update package spec to 2.9.0

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
When the AWS organization option is selected in the CSPM installation option, a different file needs to be used. This PR adds a variable in the template so that the correct file can be chosen according to the aws account type installation option.
- Depends on https://github.com/elastic/cloudbeat/pull/1152
- Related to https://github.com/elastic/cloudbeat/issues/982
> [Cloud Security Posture] Add account type in CloudFormation url

- packages/keycloak/changelog.yml
- packages/keycloak/data_stream/log/sample_event.json
- packages/keycloak/docs/README.md
- packages/keycloak/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/keycloak
```
> [keycloak] - update package-spec to 2.9.0

- packages/lastpass/changelog.yml
- packages/lastpass/data_stream/detailed_shared_folder/sample_event.json
- packages/lastpass/data_stream/event_report/sample_event.json
- packages/lastpass/data_stream/user/sample_event.json
- packages/lastpass/docs/README.md
- packages/lastpass/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/lastpass
```
> [lastpass] - update pkg-spec to 2.9.0

- packages/akamai/changelog.yml
- packages/akamai/data_stream/siem/agent/stream/httpjson.yml.hbs
- packages/akamai/data_stream/siem/manifest.yml
- packages/akamai/manifest.yml
Adds an event limit parameter to the HTTPJSON stream.
-
> akamai: add event limit parameter to HTTPJSON stream

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Add the required permission to the CNVM CloudFormation template so that the elastic-agent could run `aws.DescribeVolumes`.
- Resolves: https://github.com/elastic/cloudbeat/issues/1118
> [cloud_security_posture] CNVM CloudFormation template: DescribeVolumes

- packages/m365_defender/manifest.yml
- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/_dev/test/pipeline/test-defenderatp.log-expected.json
- packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_defender_endpoint/data_stream/log/sample_event.json
- packages/microsoft_defender_endpoint/docs/README.md
- packages/microsoft_defender_endpoint/manifest.yml
- Ensure that threat.technique.name is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/microsoft_defender_endpoint
```
> [microsoft_defender_endpoint] - update package-spec to 2.9.0

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/elastic_agent_logs/fields/fields.yml
- packages/elastic_agent/data_stream/fleet_server_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/fleet_server_logs/fields/fields.yml
- packages/elastic_agent/manifest.yml
Add missing mappings for fleet-server logs.
New attributes appear in the log stream:
- ~~I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~
- Closes #5680
> Add additional mappings for fleet-server logs

- packages/aws_logs/data_stream/generic/_dev/deploy/tf/env.yml
- packages/aws_logs/data_stream/generic/_dev/deploy/tf/main.tf
- packages/aws_logs/data_stream/generic/_dev/deploy/tf/variables.tf
- packages/aws_logs/data_stream/generic/_dev/test/system/test-default-config.yml
Add `system tests` for `awss3` input in `aws_logs` integration
Adds system test by using `terraform service deployer` and using the `SQS queue_url` generated in `terraform outputs`.
Created test after the implementation of https://github.com/elastic/elastic-package/pull/1272
- Setup AWS credentials and add `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the env vars.
- Navigate to `packages/aws_logs`
- Spin up elastic stack using …
> [aws_logs] Add system tests for awss3 input

- packages/microsoft_exchange_online_message_trace/changelog.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
- packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/sample_event.json
- packages/microsoft_exchange_online_message_trace/docs/README.md
- packages/microsoft_exchange_online_message_trace/manifest.yml
- Ensure email.from.address is an array
- Ensure email.to.address is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/microsoft_exchange_online_message_trace
```
> [microsoft_exchange_online_message_trace] - update package-spec to 2.9.0

- packages/f5_bigip/_dev/deploy/docker/docker-compose.yml
- packages/f5_bigip/changelog.yml
- packages/f5_bigip/data_stream/log/_dev/test/system/test-filestream-config.yml
- packages/f5_bigip/data_stream/log/_dev/test/system/test-logfile-config.yml
- packages/f5_bigip/data_stream/log/agent/stream/log.yml.hbs
- packages/f5_bigip/data_stream/log/fields/ecs.yml
- packages/f5_bigip/data_stream/log/manifest.yml
- packages/f5_bigip/docs/README.md
- packages/f5_bigip/manifest.yml
Add log file input to integration.
- Closes #6269
> f5_bigip: add support for log file input

- .github/CODEOWNERS
Makes code ownership more fine grained in the system package.
The manifest and changelog are co-owned by both teams and the two primarily security focused data streams are assigned to security external integrations. Rather than enumerating all data streams, assign to observability by default and carve out security data streams.
- For #7023
> CODEOWNERS: split ownership of system between observability and security

- packages/haproxy/changelog.yml
- packages/haproxy/data_stream/info/fields/fields.yml
- packages/haproxy/docs/README.md
- packages/haproxy/manifest.yml
Type of Change
- Enhancement
Add `metric_type` mapping to info datastream of HA Proxy
- relates #7138
> [HA Proxy] Add metric_type mapping to info datastream

- packages/netskope/changelog.yml
- packages/netskope/data_stream/alerts/fields/fields.yml
- packages/netskope/data_stream/alerts/sample_event.json
- packages/netskope/data_stream/events/_dev/test/pipeline/test-events.log-expected.json
- packages/netskope/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/netskope/data_stream/events/sample_event.json
- packages/netskope/docs/README.md
- packages/netskope/manifest.yml
- Ensure that user.roles is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/netskope
```
> [netskope] - update package-spec to 2.9.0

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/fields/fields.yml
- packages/o365/data_stream/audit/sample_event.json
- packages/o365/docs/README.md
- packages/o365/manifest.yml
- Ensure that user.roles is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/o365
```
> [o365] - update package-spec to 2.9.0

- .github/CODEOWNERS
Makes code ownership more fine grained in the windows package.
The package as a whole is co-owned by both teams and the primarily security focused data streams are assigned to security external integrations.
- For #7023
> CODEOWNERS: split ownership of windows between data plane and security

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/kibana/csp_rule_template/05480064-f899-53e8-b8ad-34172b09b400.json
- packages/cloud_security_posture/kibana/csp_rule_template/2f7d9d2a-ec1f-545a-8258-ea62bbffad7f.json
- packages/cloud_security_posture/kibana/csp_rule_template/33a612ed-8dee-554d-9dd7-857bfc31a33a.json
- packages/cloud_security_posture/kibana/csp_rule_template/677bdabb-ee3f-58a6-82f6-d40ccc4efe13.json
- packages/cloud_security_posture/kibana/csp_rule_template/8daf3f8a-8cb0-58f4-955a-ce2dd2a11f75.json
- packages/cloud_security_posture/kibana/csp_rule_template/933268ec-44e8-5fba-9ed7-535804521cc7.json
- packages/cloud_security_posture/kibana/csp_rule_template/b56e76ca-b976-5b96-ab3f-359e5b51ddf2.json
- packages/cloud_security_posture/kibana/csp_rule_template/b8f1182a-1b3e-5b08-8482-f74949163e97.json
- packages/cloud_security_posture/kibana/csp_rule_template/c13f49ab-845e-5a89-a05e-6a7c7b23f628.json
- packages/cloud_security_posture/kibana/csp_rule_template/d3d725bd-652f-573e-97f5-adfd002fab8e.json
- packages/cloud_security_posture/kibana/csp_rule_template/eed3e284-5030-56db-b749-01d7120dc577.json
- packages/cloud_security_posture/kibana/csp_rule_template/f00c266c-0e28-5c49-b2b0-cd97603341ec.json
- packages/cloud_security_posture/kibana/csp_rule_template/fb4368ab-cdee-5188-814c-a8197411ba22.json
- packages/cloud_security_posture/manifest.yml
Adds rule templates for [current](https://github.com/elastic/csp-security-policies/blob/main/RULES.md#gcp-cis-benchmark) rules
- Closes https://github.com/elastic/security-team/issues/7181
> [Cloud Security] Add GCP rule templates

- packages/ti_anomali/changelog.yml
- packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json-expected.json
- packages/ti_anomali/data_stream/threatstream/elasticsearch/ingest_pipeline/default.yml
- packages/ti_anomali/data_stream/threatstream/manifest.yml
- packages/ti_anomali/data_stream/threatstream/sample_event.json
- packages/ti_anomali/docs/README.md
- packages/ti_anomali/elasticsearch/transform/latest_ioc/transform.yml
- packages/ti_anomali/manifest.yml
- Existing sort order for latest transform is `event.ingested`. Since this is not precise to the millisecond level, whenever  events comes with both deleted and added for same indicator (within a second), the last activity is not preserved and the indicator is simply deleted. 
- This PR changes the sort order and the sync fields to `@timestamp` which has millisecond resolution, and thus preserves the correct order of events to store in the destination indices.
- Relates https://github.com/elastic/integrations/issues/7012
> [TI_Anomali] Fix transform sort order field

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
- packages/cloud_security_posture/manifest.yml
Adds backwards compatibility for the cluster_id field for agents pre 8.8.0
- Relates https://github.com/elastic/kibana/issues/155463
> [Cloud Security] Injest now copies cluster_id -> orchestrator.cluster.id if null (due to pre 8.8.0 agents)

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
Instead of adding individual fields to processors, we will generate those as yaml in kibana !!
Relevant kibana PR https://github.com/elastic/kibana/pull/162812 !!
> [Synthetics] Move processors to kibana

- packages/fortinet_fortimail/changelog.yml
- packages/fortinet_fortimail/data_stream/log/_dev/test/pipeline/test-system.log
- packages/fortinet_fortimail/data_stream/log/_dev/test/pipeline/test-system.log-expected.json
- packages/fortinet_fortimail/data_stream/log/elasticsearch/ingest_pipeline/pipeline_system.yml
- packages/fortinet_fortimail/manifest.yml
Parse out affected host IP when block rules are added or removed.
- Closes #7180
> fortigate_fortimail: handle block rule addition and removal

- packages/istio/changelog.yml
- packages/istio/data_stream/istiod_metrics/manifest.yml
- packages/istio/data_stream/proxy_metrics/manifest.yml
- packages/istio/manifest.yml
Enable TSDB by default for all metrics data streams.
Relates to https://github.com/elastic/integrations/issues/6567.
> [Istio] Enable TSDB by default

- packages/memcached/changelog.yml
- packages/memcached/data_stream/stats/manifest.yml
- packages/memcached/manifest.yml
- Enhancement
This PR enables TSDB by default for the `memcached` package.
- Closes #6925
> Memcached TSDB Enablement

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-events.json
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-events.json-expected.json
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-operational-events.json
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-operational-events.json-expected.json
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell_operational.yml
- packages/windows/manifest.yml
The details regexp pattern for the powershell data stream was improved in #6154 to reduce backtracking costs that caused regexp costs to exceed the set runtime limits. The same pattern on other data streams was not updated. This change brings them up to date with the change.
- For #7174
> windows: harmonise powershell details regexp patterns

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
It fixes the parsing of a 113005 Cisco ASA message as follows:
```
Jul  1 09:27:13 216.160.83.56 : %ASA-6-113005: AAA user authentication Rejected : reason = AAA failure : server = 81.2.69.142 : user = 123 : user IP = 89.160.20.112
```
The `grok` processor failed because of an unexpected space after `AAA user authentication Rejected`. This can potentially happen with every field so now the pattern expects that every value can be followed by spaces.
> [Cisco ASA] Fix the handling of spaces in 113005 messages

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.6.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b313e6dd455de89421c194aca28d18d19ba190cc
* https://github.com/elastic/ia-trade-team/issues/144
None
> [Security Rules] Update security rules package to v8.6.10

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3ea78d194e0bdfbcea853ae4178c809690957274
* https://github.com/elastic/ia-trade-team/issues/144
None
> [Security Rules] Update security rules package to v8.8.8

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/648a36605872a75558590ef5e09c4d95cebd1a6c
None
None
> [Security Rules] Update security rules package to v8.9.3

- packages/tenable_sc/changelog.yml
- packages/tenable_sc/data_stream/asset/agent/stream/httpjson.yml.hbs
- packages/tenable_sc/data_stream/asset/sample_event.json
- packages/tenable_sc/data_stream/plugin/agent/stream/httpjson.yml.hbs
- packages/tenable_sc/data_stream/plugin/sample_event.json
- packages/tenable_sc/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability.log-expected.json
- packages/tenable_sc/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
- packages/tenable_sc/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/tenable_sc/data_stream/vulnerability/fields/fields.yml
- packages/tenable_sc/data_stream/vulnerability/sample_event.json
- packages/tenable_sc/docs/README.md
- packages/tenable_sc/manifest.yml
Retains a calculated vulnerability age in days from the first and last seen dates.
- Closes #7198
> tenable_sc: add tenable_sc.vulnerability.age field

- packages/universal_profiling_agent/changelog.yml
- packages/universal_profiling_agent/manifest.yml
Promote Agent integration for GA
> Universal Profiling: Promote Agent integration for GA

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
1. Make the project_id param optional as the user will not provide it in the CN deployment mode.
Will be required by the UI component in the manual setup.
2. Add a new input var for storing the Cloudshell URL that will be used to redirect the client.
- Closes: https://github.com/elastic/integrations/issues/7233
- Related: https://github.com/elastic/cloudbeat/issues/1121
> [Cloud Security] Add a CloudShell url param

- packages/system/changelog.yml
- packages/system/data_stream/security/_dev/test/pipeline/test-security-windows2012-4779.json
- packages/system/data_stream/security/_dev/test/pipeline/test-security-windows2012-4779.json-expected.json
- packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml
- packages/system/manifest.yml
It fixes a constraint error with the `source.ip` and `related.ip` fields when populated from `winlog.event_data.ClientAddress` that may contain invalid IP values, in particular `LOCAL` and `Unknown`, leading to this error:
```
[0] unexpected pipeline error: ['LOCAL' is not an IP string literal.]
```
This has been already fixed in Winlogbeat at https://github.com/elastic/beats/pull/34295 but doesn't affect the winlog input and this ingest pipeline.
Added pipeline tests to validate that `ClientAddress` is handled properly.
> [System] Validate ClientAddress IP for Windows Security events

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/container_service/agent/stream/stream.yml.hbs
- packages/azure_metrics/manifest.yml
Add missing dimensions to the `kube_pod_status_phase` and `kube_pod_status_ready` metrics
- Closes https://github.com/elastic/integrations/issues/7161
> [Azure][container_service] Add missing azure dimensions to the kube_pod_status_phase and kube_pod_status_ready metrics

- packages/statsd_input/docs/README.md
- Bug
Improves the documentation for statsd_input package.
> statsd_input: Improve documentation

- packages/okta/changelog.yml
- packages/okta/data_stream/system/fields/fields.yml
- packages/okta/data_stream/system/sample_event.json
- packages/okta/docs/README.md
- packages/okta/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/okta
```
> [okta] - Update package-spec to 2.9.0

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-config-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-decryption-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-globalprotect-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/decryption.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
- packages/panw/data_stream/panos/sample_event.json
- packages/panw/docs/README.md
- packages/panw/manifest.yml
- Ensure host.ip is an array
- Ensure x509.subject.common_name and x509.issuer.common_name are arrays
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/panw
```
> [panw] - update package-spec to 2.9.0

- packages/panw_cortex_xdr/changelog.yml
- packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr-bioc.log-expected.json
- packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
- packages/panw_cortex_xdr/data_stream/alerts/sample_event.json
- packages/panw_cortex_xdr/docs/README.md
- packages/panw_cortex_xdr/manifest.yml
- Ensure registry.data.strings is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/panw_cortex_xdr
```
> [panw_cortex_xdr] - update package-spec to 2.9.0

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/apm_server_metrics/manifest.yml
- packages/elastic_agent/data_stream/auditbeat_metrics/manifest.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/manifest.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/manifest.yml
- packages/elastic_agent/data_stream/filebeat_input_metrics/manifest.yml
- packages/elastic_agent/data_stream/filebeat_metrics/manifest.yml
- packages/elastic_agent/data_stream/fleet_server_metrics/manifest.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/manifest.yml
- packages/elastic_agent/data_stream/metricbeat_metrics/manifest.yml
- packages/elastic_agent/data_stream/osquerybeat_metrics/manifest.yml
- packages/elastic_agent/data_stream/packetbeat_metrics/manifest.yml
- packages/elastic_agent/manifest.yml
Enable TSDB by default for all metrics data streams, except for:
- Endpoint security metrics: it never receives any data.
- Filebeat input metrics: the migration is failing with
```
Error: error running package asset tests: could not complete test run: can't install the package: can't install the package: could not install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"invalid_index_template_exception\n\tRoot causes:\n\t\tinvalid_index_template_exception: index_template [metrics-elastic_agent.filebeat_input] invalid, cause [Validation Failed: 1: [index.mode=time_series] requires a non-empty [index.routing_path];]"}
```
However, `agent.id` is set as dimension and it is always present for all documents. I cannot find the reason …
> [Elastic Agent] Enable TSDB by default

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Use a newer CloudFormation templates to tag the elastic-agent once it's up.
- Fixes: https://github.com/elastic/cloudbeat/issues/1132
> [cloud_security_posture] Update CloudFormation template to tag agents

- packages/pulse_connect_secure/changelog.yml
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-admin.log-expected.json
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-syslog.log-expected.json
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-system.log-expected.json
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log-expected.json
- packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/pulse_connect_secure/data_stream/log/sample_event.json
- packages/pulse_connect_secure/docs/README.md
- packages/pulse_connect_secure/manifest.yml
- Ensure that observer.ip is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/pulse_connect_secure
```
> [pulse_connect_secure] - update package-spec to 2.9.0

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/tls.yml
- packages/suricata/data_stream/eve/sample_event.json
- packages/suricata/docs/README.md
- packages/suricata/manifest.yml
- Ensure x509 subject and issuer fields are arrays
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/suricata
```
> [suricata] - update package-spec to 2.9.0

- packages/tenable_sc/changelog.yml
- packages/tenable_sc/data_stream/asset/sample_event.json
- packages/tenable_sc/data_stream/plugin/sample_event.json
- packages/tenable_sc/data_stream/vulnerability/sample_event.json
- packages/tenable_sc/docs/README.md
- packages/tenable_sc/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/tenable_sc
```
> [tenable_sc] - update package-spec to 2.9.0

- packages/ti_cif3/changelog.yml
- packages/ti_cif3/data_stream/feed/_dev/test/pipeline/test-cif3-no-preserve-ndjson.log-expected.json
- packages/ti_cif3/data_stream/feed/_dev/test/pipeline/test-cif3-sample-ndjson.log-expected.json
- packages/ti_cif3/data_stream/feed/elasticsearch/ingest_pipeline/default.yml
- packages/ti_cif3/data_stream/feed/fields/ecs.yml
- packages/ti_cif3/data_stream/feed/sample_event.json
- packages/ti_cif3/docs/README.md
- packages/ti_cif3/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/ti_cif3
```
> [ti_cif3] - update package-spec to 2.9.0

- packages/ti_abusech/changelog.yml
- packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
- packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/data_stream/malware/sample_event.json
- packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
- packages/ti_abusech/data_stream/malwarebazaar/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
- packages/ti_abusech/data_stream/threatfox/_dev/test/pipeline/test-threatfox-ndjson.log-expected.json
- packages/ti_abusech/data_stream/threatfox/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/data_stream/threatfox/sample_event.json
- packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
- packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/data_stream/url/sample_event.json
- packages/ti_abusech/manifest.yml
- Ensure event.type and event.category are arrays
- Ensure threat.software.alias is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/ti_abusech
```
> [ti_abusech] - update package-spec to 2.9.0

- packages/okta/changelog.yml
- packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.log-expected.json
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/data_stream/system/fields/fields.yml
- packages/okta/data_stream/system/sample_event.json
- packages/okta/docs/README.md
- packages/okta/manifest.yml
Sets the value of the field `okta.debug_context.debug_data.dt_hash`.
- Closes #7329
> [Okta] Add field for okta.debug_context.debug_data.dt_hash

- packages/spring_boot/changelog.yml
- packages/spring_boot/data_stream/audit_events/agent/stream/stream.yml.hbs
- packages/spring_boot/data_stream/http_trace/agent/stream/stream.yml.hbs
- packages/spring_boot/manifest.yml
> spring_boot: add support for http request trace logging

- packages/kubernetes/data_stream/pod/fields/fields.yml
- packages/kubernetes/data_stream/state_node/sample_event.json
- packages/kubernetes/data_stream/state_persistentvolume/sample_event.json
- packages/kubernetes/data_stream/state_pod/fields/fields.yml
- packages/kubernetes/data_stream/state_resourcequota/sample_event.json
- packages/kubernetes/data_stream/state_storageclass/sample_event.json
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
Upgrade the integration package-spec format_version from `1.0.0` to `2.9.0` and addresses all the reported by elastic-package.
Here're the adjustments needed due to the new validations introduced with the newer package-spec versions:
- Remove the deprecated attributes `license` and `release` from the manifest.yml
- Remove duplicated `pod.ip` definitions
- Update datasets in `sample_event.json` files
We need this upgrade in preparation for the introduction of the [routing rules](https://github.com/elastic/integrations/pull/7118) that require a more recent versions of the package-spec.
- Stack: 8.9.0
- Integration: 1.43.1
- elastic-package: v0.84.0
```shell
$ git diff
diff --git a/packages/kubernetes/manifest.yml b/packages/kubernetes/manifest.yml
index 45ddd5c33..15343b610 100644
--- …
```
> [Kubernetes] Bump package-spec format_version to 2.9.0

- .github/CODEOWNERS
Makes code ownership more fine grained in the system package.
The manifest and changelog are co-owned by both teams and the two primarily security focused data streams are assigned to security external integrations. Rather than enumerating all data streams, assign to cloud monitoring by default and carve out security data streams.
- For #7023
> CODEOWNERS: split ownership of aws between observability and security

- .github/CODEOWNERS
Makes code ownership more fine grained in the system package.
The manifest and changelog are co-owned by both teams and the two primarily security focused data streams are assigned to security external integrations. Rather than enumerating all data streams, assign data streams to cloud monitoring by default and carve out security data streams.
- For #7023
> CODEOWNERS: split ownership of gcp between cloud monitoring and security

- .ci/Jenkinsfile
- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/docs/README.md
Add support for Kubernetes latest version 1.27.
https://github.com/elastic/observability-dev/issues/2531
> [Kubernetes/Kind] Update k8s and kind version

- packages/couchbase/changelog.yml
- packages/couchbase/data_stream/node/agent/stream/stream.yml.hbs
- packages/couchbase/data_stream/node/manifest.yml
- packages/couchbase/manifest.yml
> couchbase: add support for http request trace logging

- packages/hadoop/changelog.yml
- packages/hadoop/data_stream/application/agent/stream/stream.yml.hbs
- packages/hadoop/data_stream/application/manifest.yml
- packages/hadoop/manifest.yml
> hadoop: add support for http request trace logging

- packages/ti_maltiverse/changelog.yml
- packages/ti_maltiverse/data_stream/indicator/agent/stream/stream.yml.hbs
- packages/ti_maltiverse/data_stream/indicator/manifest.yml
- packages/ti_maltiverse/manifest.yml
> ti_maltiverse: add support for http request trace logging

- packages/bitdefender/changelog.yml
- packages/bitdefender/data_stream/push_configuration/agent/stream/httpjson.yml.hbs
- packages/bitdefender/data_stream/push_statistics/agent/stream/httpjson.yml.hbs
- packages/bitdefender/manifest.yml
> bitdefender: add support for http request trace logging

- packages/bitwarden/changelog.yml
- packages/bitwarden/data_stream/collection/agent/stream/httpjson.yml.hbs
- packages/bitwarden/data_stream/event/agent/stream/httpjson.yml.hbs
- packages/bitwarden/data_stream/group/agent/stream/httpjson.yml.hbs
- packages/bitwarden/data_stream/policy/agent/stream/httpjson.yml.hbs
- packages/bitwarden/manifest.yml
> bitwarden: add support for http request trace logging

- packages/trellix_epo_cloud/changelog.yml
- packages/trellix_epo_cloud/data_stream/device/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/data_stream/device/manifest.yml
- packages/trellix_epo_cloud/data_stream/event/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/data_stream/event/manifest.yml
- packages/trellix_epo_cloud/data_stream/group/agent/stream/input.yml.hbs
- packages/trellix_epo_cloud/data_stream/group/manifest.yml
- packages/trellix_epo_cloud/manifest.yml
Adds support for CEL input-based HTTP request trace logging.
- For #7228
> trellix_epo_cloud: add support for http request trace logging

- packages/cel/agent/input/input.yml.hbs
- packages/cel/changelog.yml
- packages/cel/manifest.yml
Write HTTP request trace logs unders logs/cel/ rather than logs/httpjson/
-
> cel: fix location of http request trace log destination
