- dev/import-beats/docs.go
- dev/import-beats/fields.go
- dev/import-beats/packages.go
This PR modifies the import-beats script for visit potential `fields.epr.yml` files.
If there are some ECS fields referred, the script can import them to fields.
Sample fields.epr.yml for aws:
```
- name: cloud.account.name
type: alias
path: cloud.account.name
- name: cloud.account.id
type: alias
path: cloud.account.id
- name: cloud.provider
type: alias
path: cloud.provider
- name: cloud.region
type: alias
path: cloud.region
```
> Check potential fields.epr.yml for modules

- magefile.go
Changes:
* remove "public" folder contents instead of entire "public" which can be mounted (and then could break the EPR container)
> Fix cleaning volume with packages

- dev/import-beats-resources/system/docs/README.md
Issue: https://github.com/elastic/package-registry/issues/447
Pushing everything at once will cause a huge mess and make all PRs non-reviewable. I will solve this issue in small steps.
First one: add missing system resources
> Add missing system resources

- testing/environments/snapshot.yml
This PR fixes the issue with changed path to the `/registry` installation in the Docker image.
> Fix: packages path

- dev/import-beats-resources/kafka/docs/README.md
Add docs template for Kafka integration.
> Add Kafka docs template to resources

- packages/mysql/dataset/slowlog/fields/fields.yml
- packages/mysql/kibana/search/Logs-MySQL-Slow-log-ecs.json
- packages/mysql/kibana/search/Logs-MySQL-error-log-ecs.json
- packages/mysql/manifest.yml
- packages/nginx/dataset/access/fields/fields.yml
- packages/nginx/dataset/error/fields/fields.yml
- packages/nginx/dataset/ingress_controller/fields/fields.yml
- packages/nginx/manifest.yml
- packages/redis/dataset/info/fields/fields.yml
- packages/redis/dataset/log/fields/fields.yml
- packages/redis/dataset/slowlog/fields/fields.yml
- packages/redis/dataset/slowlog/manifest.yml
- packages/redis/kibana/search/73613570-4791-11e7-be88-2ddb32f3df97-ecs.json
- packages/redis/manifest.yml
Changes:
* this PR removes references to `fileset`, which apparently is a leftover skipped by the migration.
* added missing `event.created` fields which are used by these dashboards.
* redis: use `127.0.0.1` instead of `localhost`
* mysql: add `event.duration` field
* redis: add `service.address` and `service.duration` fields
Issues:
https://github.com/elastic/kibana/issues/68064
> Fix issues with dashboards

- go.mod
- go.sum
- packages/log/dataset/log/fields/base-fields.yml
- vendor/modules.txt
This PR bumps up the dependency on package-registry to only validate presence of base fields.
Also adding a missing file (`log` integration).
> Update dependency to only validate fields

- magefile.go
This PR fixes `magefile.go` to not ignore errors coming from `go mod`.
> Fix: handle mod error

- dev/import-beats/datasets.go
- dev/import-beats/fields_base_fields.go
Issue: https://github.com/elastic/package-registry/issues/465#issuecomment-633831298
import-beats: create `base-fields.yml` files for each dataset
Testing:
I used `haproxy` integration for development, but didn't pull it in for clarity.
```
$ PACKAGES=haproxy mage ImportBeats
$ find packages/haproxy | grep base-fields
packages/haproxy/dataset/info/fields/base-fields.yml
packages/haproxy/dataset/stat/fields/base-fields.yml
packages/haproxy/dataset/log/fields/base-fields.yml
$ cat packages/haproxy/dataset/info/fields/base-fields.yml
- name: stream.type
type: constant_keyword
description: Stream type.
- name: stream.dataset
type: constant_keyword
description: Stream dataset.
- name: stream.namespace
type: constant_keyword
description: Stream namespace.
- name: '@timestamp'
type: date …
```
> import-beats: create base fields

- dev/update-package-storage/git.go
- dev/update-package-storage/main.go
- dev/update-package-storage/packages.go
Issue: https://github.com/elastic/integrations/issues/45
This PR modifies `mage UpdatePackageStorage` to create branches with updates if only the version is bumped up.
Testing:
I created this PR https://github.com/elastic/package-storage/pull/50 , because the version of `aws` integration has been bumped up.
> Release integration only on version bump

- packages/kafka/kibana/search/All Kafka logs-ecs.json
Kafka logs dashboard is not displaying any data, it seems to be using incorrect fields for filtering. Use `stream.dataset` instead of `fileset.name`.
> Filter by stream.dataset in kafka logs dashboard

- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/kafka/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/redis/manifest.yml
This PR bumps up versions of multiple integrations to release all changes related to a massive fields rename (from `stream.*` to `dataset.*`).
> Update packages to release stream-to-dataset renaming

- dev/update-package-storage/git.go
This caused the update script to fail on my dev box. The `cherrypick_pr` script that we use in elastic/beats gets the username by inspecting the path of the branch we use to push, instead of `user.name`. This makes the behavior in line with `cherrypick_pr`.
> change getUsername so we get the upstream user

- packages/aws/dataset/cloudtrail/fields/package-fields.yml
- packages/aws/dataset/cloudwatch_logs/fields/package-fields.yml
- packages/aws/dataset/ec2_logs/fields/package-fields.yml
- packages/aws/dataset/elb_logs/fields/package-fields.yml
- packages/aws/dataset/s3access/fields/package-fields.yml
- packages/aws/dataset/vpcflow/fields/package-fields.yml
With removing the empty package-fields.yml files, Kibana Discover is able to display json fields correctly:
> Remove empty package-fields.yml from aws package

- config.yml
- go.mod
- go.sum
- magefile.go
- packages/mysql/manifest.yml
- testing/environments/package-registry.config.yml
- testing/environments/snapshot.yml
- vendor/github.com/elastic/package-registry/devmode/devmode.go
- vendor/github.com/elastic/package-registry/util/package.go
- vendor/github.com/elastic/package-registry/util/packages.go
- vendor/modules.txt
This PR uses freshly introduced `package_paths` configuration option to prevent from pulling packages from the package-storage.
> Use custom package_paths in EPR

- dev/import-beats/datasets.go
We should not only check the length of the `moduleFields` but also the actual `Fields` to identify empty `package-fields.yml` file.
closes: https://github.com/elastic/integrations/issues/101
> Adjust import-beats script to avoid empty package-fields.yml files 

- .ci/Jenkinsfile
- .ci/integrations/Dockerfile
The path fro the packages changed on https://github.com/elastic/integrations/pull/104 before I merge, this PR fix the issue.
> fix: the distribution copy and mount path

- packages/mongodb/dataset/log/manifest.yml
- packages/nginx/dataset/access/manifest.yml
- packages/nginx/dataset/error/manifest.yml
- packages/nginx/dataset/ingress_controller/manifest.yml
- packages/redis/dataset/log/manifest.yml
- packages/system/dataset/auth/manifest.yml
- packages/system/dataset/syslog/manifest.yml
This PR remove os.* vars from integrations.
- Closes https://github.com/elastic/integrations/issues/108
> Remove os.* vars from integrations

- dev/update-package-storage/git.go
- dev/update-package-storage/main.go
As part of https://github.com/elastic/package-storage/issues/86 the way packages are released is changed. The release process will be snapshot -> staging -> production. This PR now first switches over to directly open PR's against production to move away from master. This allows us to update the deployment of epr.elastic.co to point to production branch instead and start to cleanup / remove the master branch.
The second step will be to adjust the script that it directly pushed to snapshot and we then have a release script to promote packages from snapshot to staging to production.
Before this is merged, I will update all the packages a last time from master to production and will not accept PR's against master anymore for packages.
> Update target branch of release script

- packages/apache/manifest.yml
- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/kafka/manifest.yml
- packages/kubernetes/manifest.yml
- packages/log/manifest.yml
- packages/mongodb/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/postgresql/manifest.yml
- packages/rabbitmq/manifest.yml
- packages/redis/manifest.yml
- packages/system/manifest.yml
- packages/windows/manifest.yml
Removes outdated `categories` from packages. This is because these categories are no longer supported by the package registry (see https://github.com/elastic/package-registry/pull/534). With these outdated categories in place one can no longer load the packages in this repo into a package registry built off `master`. 
Longer term, authors of packages would need to redefine categories for their respective packages, picking from the [list _du jour_](https://github.com/elastic/package-registry/blob/e93e801a6dfbfa6f83c8b69f6e9405603151f937/util/package.go#L27-L51) (see #135).
> Remove outdated categories

- dev/import-beats/conditions.go
- dev/import-beats/packages.go
- go.mod
- go.sum
- packages/apache/manifest.yml
- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/kafka/manifest.yml
- packages/kubernetes/manifest.yml
- packages/mongodb/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/postgresql/manifest.yml
- packages/rabbitmq/manifest.yml
- packages/redis/manifest.yml
- packages/system/manifest.yml
- packages/windows/manifest.yml
- vendor/github.com/elastic/package-registry/util/dataset.go
- vendor/github.com/elastic/package-registry/util/package.go
- vendor/modules.txt
Kibana stopped working due to https://github.com/elastic/kibana/issues/70572. Probably it's an issue with missing contraints.
> Use constraints instead of requirements

- CONTRIBUTING.md
- dev/import-beats/packages.go
- packages/apache/manifest.yml
- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/kafka/manifest.yml
- packages/kubernetes/manifest.yml
- packages/log/manifest.yml
- packages/mongodb/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/postgresql/manifest.yml
- packages/rabbitmq/manifest.yml
- packages/redis/manifest.yml
- packages/system/manifest.yml
- packages/windows/manifest.yml
This PR assigns owner teams to packages. It also updates the import-beats script to assign a common team alias.
- https://github.com/elastic/integrations/issues/103
> Assign owners to packages

- .ci/integrations/Dockerfile
- testing/environments/kubernetes/snapshot.yml
- testing/environments/snapshot.yml
Builds in the integrations repo should not change over time. Also development in the registry should not directly affect the integrations repo. To have things more reproducible, this changes the docker container which is run for the registry to a specific revision. It is the same revision which is uesd for the golang dependencies. If possible, these two should stay in sync in the future.
> Attach the registry image to a specific version

- dev/update-package-storage/github.go
As all the packages are now in the production branch and not master anymore in package-storage, I assume this one should serve as a base.
> Make production branch as base branch

- packages/nginx/dataset/access/test/test-access-events.json
- packages/nginx/dataset/access/test/test-access-expected.json
This PR defines sample pipeline test cases for `nginx.access`. I'm sure that expected results are invalid, but committing them to compare with real data later on.
Files are inline with the proposal for the unified tool for packages and are easy to use with Simulate Pipeline API https://www.elastic.co/guide/en/elasticsearch/reference/master/simulate-pipeline-api.html
~~- [ ] I have reviewed [tips for building integrations]~~(https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
> Define pipeline test cases for nginx.access

- packages/base/docs/README.md
- packages/base/elasticsearch/component_template/events-mappings.json
- packages/base/elasticsearch/component_template/events-settings.json
- packages/base/elasticsearch/component_template/logs-mappings.json
- packages/base/elasticsearch/component_template/logs-settings.json
- packages/base/elasticsearch/component_template/metrics-mappings.json
- packages/base/elasticsearch/component_template/metrics-settings.json
- packages/base/elasticsearch/ilm_policy/events-default.json
- packages/base/elasticsearch/ilm_policy/logs-default.json
- packages/base/elasticsearch/ilm_policy/metrics-default.json
- packages/base/elasticsearch/index_template/events.json
- packages/base/elasticsearch/index_template/logs.json
- packages/base/elasticsearch/index_template/metrics.json
- packages/base/manifest.yml
This adds the base package for versioning to the integrations repository. This package is maintained by the ingest-management team but integrations is a good place for this package at the moment until we have found a new home.
As Elasticsearch ships the basic assets, this currently does not need to be released. As soon as we have brought all the assets in line with Elasticsearch and added improvements, we need to start releasing it.
> Add base package to integrations repository

- packages/nginx/kibana/search/Filebeat-Nginx-module-ecs.json
Fixes incorrect installation and errors removing kibana search assets: `Filebeat-Nginx-module-ecs.json` and `Logs-Nginx-integration-ecs.json` have the same id `Logs-Nginx-integration-ecs`.
> fix nginx search asset id

- CONTRIBUTING.md
- dev/import-beats/conditions.go
- packages/apache/manifest.yml
- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/iis/manifest.yml
- packages/kafka/manifest.yml
- packages/kubernetes/manifest.yml
- packages/mongodb/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/postgresql/manifest.yml
- packages/prometheus/manifest.yml
- packages/rabbitmq/manifest.yml
- packages/redis/manifest.yml
- packages/system/manifest.yml
- packages/windows/manifest.yml
- packages/zookeeper/manifest.yml
Changes all occurences of `^7.9.0` to `>=7.9.0` so that the packages also appear in Kibana `master` which sends `kibana.version=8.0.0` to the registry.
- Closes https://github.com/elastic/integrations/issues/172
- Is needed by https://github.com/elastic/kibana/pull/71443
> Use minimum kibana version

- packages/apache/manifest.yml
- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/iis/manifest.yml
- packages/kafka/manifest.yml
- packages/kubernetes/manifest.yml
- packages/log/manifest.yml
- packages/mongodb/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/postgresql/manifest.yml
- packages/prometheus/manifest.yml
- packages/rabbitmq/manifest.yml
- packages/redis/manifest.yml
- packages/system/manifest.yml
- packages/windows/manifest.yml
- packages/zookeeper/manifest.yml
This PR marks all integrations packages (except `system`) as `experimental`. It also bumps up minor versions of all packages that were updated.
> Mark packages as experimental + bump minor versions

- packages/kubernetes/kibana/visualization/44f12b40-2bf4-11e7-859b-f78b612cde28-ecs.json
- packages/kubernetes/manifest.yml
Updates based on https://github.com/elastic/beats/pull/19675.
Closes https://github.com/elastic/integrations/issues/179.
> Fix nanocore sum for non default intervals on Kubernetes Overview Dashboard

- dev/import-beats-resources/nginx/docs/README.md
- packages/nginx/docs/README.md
This PR fixes a markdown link typo in the nginx package description.
> Fix markdown link to Nginx home page

- packages/mongodb/dataset/collstats/fields/base-fields.yml
- packages/mongodb/dataset/collstats/manifest.yml
- packages/mongodb/dataset/dbstats/fields/base-fields.yml
- packages/mongodb/dataset/dbstats/manifest.yml
- packages/mongodb/dataset/log/manifest.yml
- packages/mongodb/dataset/metrics/fields/base-fields.yml
- packages/mongodb/dataset/metrics/manifest.yml
- packages/mongodb/dataset/replstatus/fields/base-fields.yml
- packages/mongodb/dataset/replstatus/manifest.yml
- packages/mongodb/dataset/status/fields/base-fields.yml
- packages/mongodb/dataset/status/manifest.yml
- packages/mongodb/docs/README.md
- packages/mongodb/kibana/search/MongoDB-search-ecs.json
- packages/mongodb/kibana/search/bfc96a60-0a80-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/search/e49fe000-0a7e-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/visualization/0fef5710-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Read-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Write-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-Engine-ampersand-Version-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-WiredTiger-Cache-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-asserts-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-hosts-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-memory-stats-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-operation-counters-ecs.json
- packages/mongodb/manifest.yml
1. Fix `service.address` field to keyword
2. Add better description for metrics dataset
3. Change release to experimental for individual datasets under mongodb package
4. Add namespace default in kibana
> Fix mongodb package service.address field and metrics description

- packages/mongodb/manifest.yml
Add all optional config parameters for mongodb metrics collection.
> Add optional config parameters for mongodb metrics collection

- packages/mongodb/kibana/dashboard/mongodb-Metrics-MongoDB-ecs.json
- packages/mongodb/kibana/dashboard/mongodb-abcf35b0-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/search/MongoDB-search-ecs.json
- packages/mongodb/kibana/search/bfc96a60-0a80-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/search/e49fe000-0a7e-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/visualization/0fef5710-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Read-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Write-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-Engine-ampersand-Version-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-WiredTiger-Cache-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-asserts-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-hosts-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-memory-stats-ecs.json
- packages/mongodb/kibana/visualization/MongoDB-operation-counters-ecs.json
This PR is to remove redundant `[Metrics MongoDB] ECS` from visualization titles and dashboard titles.
Before:
After:
> Remove redundant [Metrics MongoDB] ECS from visualization titles

- packages/kubernetes/dataset/scheduler/manifest.yml
- packages/kubernetes/dataset/state_container/manifest.yml
- packages/kubernetes/dataset/state_cronjob/manifest.yml
- packages/kubernetes/dataset/state_deployment/manifest.yml
- packages/kubernetes/dataset/state_node/manifest.yml
- packages/kubernetes/dataset/state_persistentvolume/manifest.yml
- packages/kubernetes/dataset/state_persistentvolumeclaim/manifest.yml
- packages/kubernetes/dataset/state_pod/manifest.yml
- packages/kubernetes/dataset/state_replicaset/manifest.yml
- packages/kubernetes/dataset/state_resourcequota/manifest.yml
- packages/kubernetes/dataset/state_service/manifest.yml
- packages/kubernetes/dataset/state_statefulset/manifest.yml
- packages/kubernetes/dataset/state_storageclass/manifest.yml
- packages/kubernetes/manifest.yml
Adds period options for datasets that was missing.
> Add period options for state_* and scheduler datasets

- testing/environments/agent.yml
- testing/environments/snapshot.yml
Currently for development the 8.0.0-SNAPSHOT builds are used but the packages that we develop are shipped for 7.9. It is possible that a feature in 8.0 does not exist in 7.9 but we use it in a package. Because of this I think it makes more sense to develop against the version we plan to ship the packages to. This also ties into https://github.com/elastic/package-storage/issues/163
A follow up discussion should happen on what happens after 7.9 is released. Should we develop against 7.9 or 7.10.0-SNAPSHOT?
> Change snapshot testing version to 7.9.0-SNAPSHOT

- CONTRIBUTING.md
- dev/import-beats/conditions.go
- packages/apache/manifest.yml
- packages/aws/manifest.yml
- packages/cisco/manifest.yml
- packages/haproxy/manifest.yml
- packages/iis/manifest.yml
- packages/kafka/manifest.yml
- packages/kubernetes/manifest.yml
- packages/mongodb/manifest.yml
- packages/mysql/manifest.yml
- packages/netflow/manifest.yml
- packages/nginx/manifest.yml
- packages/postgresql/manifest.yml
- packages/prometheus/manifest.yml
- packages/rabbitmq/manifest.yml
- packages/redis/manifest.yml
- packages/system/manifest.yml
- packages/windows/manifest.yml
- packages/zookeeper/manifest.yml
This updates the Kibana version on all packages to `^7.9.0` instead of `>=7.9.0`. The problem with `>=7.9.0` is that these packages will potentially also show up in 8.0 without necessarily being compatible as we don't know today what will break in 8.0. It also causes a problem if a package is removed for 8.0. Lets assume the last package we release has `>=7.9.0 <8.0.0` inside. Even though the latest package will not show up, older packages will.
I assume it was changed do `>=7.9.0` to solve an issue with the 8.0.0-SNAPSHOT testing. On the Kibana side this will be solved by https://github.com/elastic/kibana/pull/73415 and on the storage side there is a discussion on what Kibana version to use for testing which should also solve this: https://github.com/elastic/package-storage/issues/163
> Update Kibana version to ^7.9.0

- dev/import-beats/streams_config_parser.go
Fixes an out-of-bounds array access when extracting input type from a Filebeat module.
This is a minor bug, probably something is not formatted as expected in one of the filesets:
```
panic: runtime error: slice bounds out of range [:8] with capacity 0
goroutine 1 [running]:
main.extractInputTypeFromTextNode(0xc00029c960, 0x0, 0x0, 0x203000)
/Users/adrian/go/src/github.com/elastic/integrations/dev/import-beats/streams_config_parser.go:79 +0x183
main.inputTypesForNode(0x1596c40, 0xc00029c960, 0x0, 0x0, 0x0)
/Users/adrian/go/src/github.com/elastic/integrations/dev/import-beats/streams_config_parser.go:44 +0x354
main.inputTypesForListNode(0xc00029c930, 0xc0003c3500, 0x1, 0x1)
/Users/adrian/go/src/github.com/elastic/integrations/dev/import-beats/streams_config_parser.go:88 +0xaf …
```
> Fix a crash during module conversion

- packages/prometheus/dataset/collector/fields/fields.yml
- packages/prometheus/dataset/query/fields/fields.yml
- packages/prometheus/dataset/remote_write/fields/fields.yml
- packages/prometheus/manifest.yml
Adds missing field mappings for Prometheus package.
Closes https://github.com/elastic/integrations/issues/258
> Add object field types in prometheus package

- packages/system/dataset/socket/manifest.yml
This PR fixes variable type for duration-like option (should be text instead of duration).
-
> Fix: use text type instead of integer (earlier: duration)

- testing/environments/snapshot.yml
The 7.9 registry was branched off and all future development is currently happening for 7.10. So the testing environment should be updated accordingly.
> Update test environment to 7.10.0

- packages/zeek/dataset/kerberos/elasticsearch/ingest_pipeline/default.yml
- packages/zeek/manifest.yml
Fixes loading of zeek kerberos pipeline.
- "---" is required at beginning of yaml docs
- bumped version of zeek to 0.1.1
> Fix zeek kerberos pipeline

- packages/nginx/data_stream/access/_dev/test/pipeline/test-access-raw.log-expected.json
Update the expected documents for tests to include the new `country_name` field under `geo`.
- Relates https://github.com/elastic/elasticsearch/pull/62915
> Update NGINX package golden files for pipeline tests

- packages/checkpoint/manifest.yml
- packages/cisco/manifest.yml
- packages/crowdstrike/manifest.yml
- packages/fortinet/manifest.yml
- packages/juniper/manifest.yml
- packages/microsoft/manifest.yml
- packages/o365/manifest.yml
- packages/okta/manifest.yml
- packages/panw/manifest.yml
- packages/suricata/manifest.yml
- packages/zeek/manifest.yml
- packages/zoom/manifest.yml
The name of the security ingest team was changed to external integrations. This updates the github team same to @elastic/security-external-integrations within manifests.
> Update GH team name to security-external-integrations

- packages/aws/data_stream/ec2_metrics/fields/fields.yml
- packages/aws/docs/README.md
- packages/system/data_stream/cpu/fields/fields.yml
- packages/system/data_stream/diskio/fields/fields.yml
- packages/system/data_stream/network/fields/fields.yml
- packages/system/docs/README.md
For 7.10, we introduced some common fields in Beats for host inventory schema.
- Relates https://github.com/elastic/beats/issues/19757
> Add common host inventory fields into aws and system package

- packages/aws/data_stream/cloudtrail/agent/stream/s3.yml.hbs
- packages/aws/data_stream/cloudtrail/manifest.yml
- packages/aws/data_stream/cloudwatch_logs/agent/stream/s3.yml.hbs
- packages/aws/data_stream/cloudwatch_logs/manifest.yml
- packages/aws/data_stream/ec2_logs/agent/stream/s3.yml.hbs
- packages/aws/data_stream/ec2_logs/manifest.yml
- packages/aws/data_stream/elb_logs/agent/stream/s3.yml.hbs
- packages/aws/data_stream/elb_logs/manifest.yml
- packages/aws/data_stream/s3access/agent/stream/s3.yml.hbs
- packages/aws/data_stream/s3access/manifest.yml
- packages/aws/data_stream/vpcflow/agent/stream/s3.yml.hbs
- packages/aws/data_stream/vpcflow/manifest.yml
This PR is to add `fips_enabled` config option into the integration as a part of https://github.com/elastic/beats/issues/21286.
> Add fips_enabled config parameter to log data streams

- testing/environments/kibana.config.yml
This PR renames `ingest_manager` to `fleet` due to latest breaking changes pushed to Kibana.
-
> Rename ingest_manager to fleet

- packages/aws/data_stream/billing/manifest.yml
- packages/aws/data_stream/cloudwatch_metrics/manifest.yml
- packages/aws/data_stream/dynamodb/manifest.yml
- packages/aws/data_stream/ebs/manifest.yml
- packages/aws/data_stream/ec2_metrics/manifest.yml
- packages/aws/data_stream/elb_metrics/manifest.yml
- packages/aws/data_stream/lambda/manifest.yml
- packages/aws/data_stream/natgateway/manifest.yml
- packages/aws/data_stream/rds/manifest.yml
- packages/aws/data_stream/s3_daily_storage/manifest.yml
- packages/aws/data_stream/s3_request/manifest.yml
- packages/aws/data_stream/sns/manifest.yml
- packages/aws/data_stream/sqs/manifest.yml
- packages/aws/data_stream/transitgateway/manifest.yml
- packages/aws/data_stream/usage/manifest.yml
- packages/aws/data_stream/vpn/manifest.yml
- packages/aws/manifest.yml
This PR is to add latency config into aws metrics data stream after merging https://github.com/elastic/beats/pull/20875.
> Add latency config into aws metrics data stream

- packages/system/data_stream/auth/fields/ecs.yml
- packages/system/data_stream/syslog/fields/ecs.yml
- packages/system/manifest.yml
Add missing field definitions for the ECS host fields to the log data streams of the system package.
- Fixes #291
> Add ECS host fields to system package log data streams

- dev/import-beats/kibana.go
- dev/import-beats/packages.go
This PR fixes the migration script is to prepend modules names to Kibana dashboards.
Additionally:
- I fixed issue with undefined `event` function in templates (not used in initial migration).
- https://github.com/elastic/integrations/issues/318
> Fix import-beats: prepend module names to Kibana dashboards

- packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/forwarded/fields/ecs.yml
- packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell/fields/ecs.yml
- packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell_operational/fields/ecs.yml
- packages/windows/data_stream/security/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/security/fields/ecs.yml
- packages/windows/data_stream/security/fields/winlog.yml
- packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/sysmon_operational/fields/ecs.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Changes
- Bump ecs.version to 1.6.0.
- Add missing mappings for
- event.outcome (just missing, no impact)
- host.ip (bug since it must be mapped to IP)
- log.level (bug since this is used by dashboards)
- event.code (bug since it maps to integer otherwise)
- winlog.event_data.OldTargetUserName (used in dashboard)
- winlog.event_data.NewTargetUserName (used in dashboard)
- Fixes #329
> Windows event log data stream fixes

- packages/o365/data_stream/audit/agent/stream/log.yml.hbs
- packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
- packages/o365/manifest.yml
- set ecs.version to 1.6.0
- bump package version
> Bump o365 ecs version to 1.6.0

- packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/okta/data_stream/system/agent/stream/log.yml.hbs
- packages/okta/manifest.yml
- set ecs.version to 1.6.0
- bump package version
> Bump okta ecs version to 1.6.0

- go.mod
- go.sum
This PR updates dependency on the elastic-package to verify Kibana dashboard names.
- https://github.com/elastic/integrations/issues/318
> Update dependency on elastic-package

- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
- packages/suricata/data_stream/eve/fields/ecs.yml
- packages/suricata/docs/README.md
- packages/suricata/manifest.yml
Change file.x509 mappings to tls.server.x509 to be in sync with the module
> [filebeat][suricata] Change file.x509 mappings to tls.server.x509

- packages/checkpoint/data_stream/firewall/agent/stream/udp.yml.hbs
- packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/checkpoint/data_stream/firewall/fields/base-fields.yml
- packages/checkpoint/data_stream/firewall/fields/ecs.yml
- packages/checkpoint/data_stream/firewall/manifest.yml
- packages/checkpoint/docs/README.md
- packages/checkpoint/manifest.yml
Sync the change from https://github.com/elastic/beats/pull/21854 to use the UDP input instead of syslog input
to allow for RFC 5424 syslog parsing.
> Update CheckPoint package with RFC 5424 parsing fix

- dev/import-beats/kibana.go
- dev/import-beats/kibana_test.go
- go.mod
This PR updates all Kibana asset IDs, and their references from other assets, during migration according to these rules:
It also updates any asset titles, labels, etc. during migration according this rule:
- Resolves #344 
- Resolves #339
> Update Kibana asset IDs and titles during migration

- dev/update-package-storage/packages.go
This PR fixes the issue with removing children resources. The build job failed because the parent directory wasn't available, but the job tried to remove its children.
See: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations/detail/master/212/pipeline
-
> Fix: don't remove children if parent is not available

- .ci/Jenkinsfile
it changes when to run the Update Package Storage stage, not it only runs on the master branch
> ci: Update Package Storage only on master branch

- packages/o365/_dev/build/docs/README.md
- packages/o365/data_stream/audit/agent/stream/log.yml.hbs
- packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
- packages/o365/data_stream/audit/manifest.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
This updates the `o365` package to `0.2.5`. Some configuration was broken, preventing it to work against o365 API.
- Re-writes and reorganizes the vars configurations.
- Split the tenant ID/name list in two separate vars (can't get YAML working).
- Fix broken agent stream.
- Made log (file) input disabled by default.
- Add docs explaining how to configure.
Ask me for an o365 account for testing.
> Fix Office 365 package configuration

- .ci/Jenkinsfile
- .gitignore
- CONTRIBUTING.md
- dev/update-package-storage/README.md
- magefile.go
This PR strips mage targets from the Magefile. Since that moment packages can be built using the `elastic-package` tool.
- Resolves https://github.com/elastic/integrations/issues/407
> Strip mage targets from Magefile

- .github/ISSUE_TEMPLATE/package-checklist.md
Removing action item. It should has been removed as part of #342 (see https://github.com/elastic/integrations/pull/342#discussion_r514119497)
> Remove unneeded action item

- packages/aws/kibana/map/aws-0edf0640-3e7e-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/search/aws-5e5a3c90-bac0-11e9-9f70-1f7bda85a5eb.json
- packages/aws/kibana/search/aws-c1aee600-4487-11ea-ad63-791a5dc86f10.json
- packages/aws/kibana/visualization/aws-219c1850-3e82-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-73970bc0-3e86-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-75853f20-4484-11ea-ad63-791a5dc86f10.json
- packages/aws/kibana/visualization/aws-76af8140-3e84-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-b6a308f0-3e82-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-bad8c910-4485-11ea-ad63-791a5dc86f10.json
- packages/aws/kibana/visualization/aws-bd37d720-3e84-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-ceb7c030-3e86-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-d8b1e830-3e82-11ea-bb0a-69c3ca1d410f.json
- packages/aws/kibana/visualization/aws-e50c51e0-3e7f-11ea-bb0a-69c3ca1d410f.json
This PR is to fix `elb` and `vpcflow` dashboards by changing `fileset.name` to `data_stream.dataset`.
- Closes https://github.com/elastic/integrations/issues/431
> [aws package] change fileset.name to data_stream.dataset

- packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log
- packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log-expected.json
- packages/aws/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
- packages/aws/manifest.yml
This PR is to move https://github.com/elastic/beats/pull/22721 over into aws package.
> Drop fields in aws vpcflow data stream when value equals to "-"

- packages/crowdstrike/_dev/deploy/docker/Dockerfile
- packages/crowdstrike/_dev/deploy/docker/docker-compose.yml
- packages/crowdstrike/_dev/deploy/docker/falcon-audit-events.log
- packages/crowdstrike/_dev/deploy/docker/falcon-events.log
- packages/crowdstrike/_dev/deploy/docker/falcon-sample.log
- packages/crowdstrike/data_stream/falcon/_dev/test/system/config.yml
- packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
- packages/crowdstrike/data_stream/falcon/fields/fields.yml
- packages/crowdstrike/docs/README.md
Add a system test for CrowdStrike Falcon and fix the issues it detected.
These were the errors initially detected.
crowdstrike/falcon :
[0] field "crowdstrike.event.PatternDispositionFlags.Detect" is undefined
[1] field "crowdstrike.event.PatternDispositionFlags.InddetMask" is undefined
[2] field "crowdstrike.event.PatternDispositionFlags.Indicator" is undefined
[3] field "crowdstrike.event.PatternDispositionFlags.KillParent" is undefined
[4] field "crowdstrike.event.PatternDispositionFlags.KillProcess" is undefined
[5] field "crowdstrike.event.PatternDispositionFlags.KillSubProcess" is undefined
[6] field "crowdstrike.event.PatternDispositionFlags.OperationBlocked" is undefined
[7] field "crowdstrike.event.PatternDispositionFlags.PolicyDisabled" is undefined
[8] field …
> Add system test for CrowdStrike Falcon

- packages/nginx_ingress_controller/kibana/dashboard/nginx_ingress_controller-0b3dba40-f341-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/dashboard/nginx_ingress_controller-dfbc0840-f340-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-1aa782a0-f345-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-78738850-f342-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-Access-Browsers.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-Access-Map.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-Access-OSes.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-a3bf1ce0-f347-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-afd506b0-f348-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-ba138ab0-f344-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-c37e2770-f341-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-ee250270-f344-11ea-a3fd-1b45ec532bb3.json
- packages/nginx_ingress_controller/kibana/visualization/nginx_ingress_controller-f137cb40-f345-11ea-a3fd-1b45ec532bb3.json
This PR adjusts (corrects) Kibana versions after export to fix the issue spotted in https://github.com/elastic/package-storage/pull/704 .
- https://github.com/elastic/package-storage/pull/704
> Nginx ingress contoller: fix wrong Kibana version

- packages/aws/data_stream/cloudtrail/fields/ecs.yml
- packages/aws/docs/README.md
Add `event.ingested` into `ecs.yml` for aws.cloudtrail data stream.
- Closes https://github.com/elastic/integrations/issues/473
> Add event.ingested into ecs.yml for aws.cloudtrail

- packages/aws/data_stream/billing/agent/stream/stream.yml.hbs
- packages/aws/data_stream/cloudwatch_metrics/agent/stream/stream.yml.hbs
- packages/aws/data_stream/dynamodb/agent/stream/stream.yml.hbs
- packages/aws/data_stream/ebs/agent/stream/stream.yml.hbs
- packages/aws/data_stream/ec2_metrics/agent/stream/stream.yml.hbs
- packages/aws/data_stream/elb_metrics/agent/stream/stream.yml.hbs
- packages/aws/data_stream/lambda/agent/stream/stream.yml.hbs
- packages/aws/data_stream/natgateway/agent/stream/stream.yml.hbs
- packages/aws/data_stream/rds/agent/stream/stream.yml.hbs
- packages/aws/data_stream/s3_daily_storage/agent/stream/stream.yml.hbs
- packages/aws/data_stream/s3_request/agent/stream/stream.yml.hbs
- packages/aws/data_stream/sns/agent/stream/stream.yml.hbs
- packages/aws/data_stream/sqs/agent/stream/stream.yml.hbs
- packages/aws/data_stream/transitgateway/agent/stream/stream.yml.hbs
- packages/aws/data_stream/usage/agent/stream/stream.yml.hbs
- packages/aws/data_stream/vpn/agent/stream/stream.yml.hbs
- packages/aws/manifest.yml
This PR fixes passing credentials into aws package for metrics data streams. The bug is caused by mismatching variable names between `stream.yml.hbs` for elastic-agent template and `manifest.yml` for defining and passing credentials. 
- Closes #https://github.com/elastic/integrations/issues/465
```
id: 02716e40-4141-11eb-aecf-c93b3fa306f0
revision: 8
outputs:
default:
type: elasticsearch
hosts:
- 'http://elasticsearch:9200'
agent:
monitoring:
enabled: true
logs: true
metrics: true
inputs:
- id: ae0f6522-7da1-4ea5-bcd3-7d661d62a448
name: aws-1
revision: 1
type: aws/metrics
meta:
package:
name: aws
version: 0.3.15
data_stream:
streams:
- id: aws/metrics-aws.dynamodb-ae0f6522-7da1-4ea5-bcd3-7d661d62a448
data_stream:
dataset: …
```
> Fix credentials for metrics data streams in aws package

- packages/nginx_ingress_controller/data_stream/error/elasticsearch/ingest_pipeline/default.yml
- packages/nginx_ingress_controller/manifest.yml
This PR fixes issue spotted in the Nginx Ingress Controller's pipeline tests (non-idempotent test runs).
The CI will verify it.
- https://github.com/elastic/integrations/issues/491
> nginx_ingress_controller: use event.created in the ingest pipeline

- packages/system/data_stream/load/agent/stream/stream.yml.hbs
- packages/system/manifest.yml
No idea how I missed this in testing, but the `load` metricset should only be skipped on Windows, as opposed to just running on Linux.
> Fix conditional in load dataset

- packages/aws/data_stream/ec2_metrics/fields/agent.yml
- packages/aws/data_stream/ec2_metrics/fields/fields.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
- packages/system/data_stream/cpu/fields/agent.yml
- packages/system/data_stream/diskio/fields/agent.yml
- packages/system/data_stream/network/fields/agent.yml
- packages/system/data_stream/process/fields/agent.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
This PR is to add common [host inventory schema fields](https://github.com/elastic/beats/issues/19757) and [process inventory schema fields](https://github.com/elastic/beats/issues/22216) into integration packages.
> add host inventory schema fields and process fields

- packages/system/manifest.yml
https://github.com/elastic/integrations/pull/499 suppose to bump the system package version but didn't. This PR is to add that :)
> update system package version to 0.10.6 for new process/host fields

- packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-expected.json
- packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
- packages/fortinet/data_stream/firewall/agent/stream/tcp.yml.hbs
- packages/fortinet/data_stream/firewall/agent/stream/udp.yml.hbs
- packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/event.yml
- packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/utm.yml
- packages/fortinet/data_stream/firewall/fields/agent.yml
- packages/fortinet/data_stream/firewall/fields/beats.yml
- packages/fortinet/data_stream/firewall/fields/ecs.yml
- packages/fortinet/data_stream/firewall/manifest.yml
- packages/fortinet/docs/README.md
- packages/fortinet/manifest.yml
This updates the fortinet package's firewall data_stream to use ECS 1.7, including the network direction changes recently introduced in beats.
~~[ ] I have verified that all datasets collect metrics or logs.~~
> Update fortinet/firewall integration to ECS 1.7

- packages/nats/_dev/deploy/docker/docker-compose.yml
- packages/nats/data_stream/route/_dev/test/system/test-default-config.yml
- packages/nats/data_stream/routes/_dev/test/system/test-default-config.yml
This PR fixes the flakiness reported at https://github.com/elastic/integrations/issues/520 after the changes happened at https://github.com/elastic/elastic-package/pull/209 and more specifically the one at https://github.com/elastic/elastic-package/blob/master/internal/testrunner/runners/system/servicedeployer/compose.go#L64.
`route` and `routes` data_streams require a clustered nats so as to find the required metrics, in this we need to make sure that a clustered nats is running (2 services) instead of a single nats service.
> Ensure all composed services are up for nats cluster testing

- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/docs/README.md
- packages/kubernetes/manifest.yml
This PR fixes a leftover TODO in the docs of kubernetes package so as to point to the current agent manifests for k8s.
> Add agent manifest as refrence in k8s package

- .ci/Jenkinsfile
- go.mod
- go.sum
This PR enables docker logging for containers running in the CI.
Artifacts collected here: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-535/4/artifacts
- https://github.com/elastic/integrations/issues/380
> CI: Collect Elastic stack logs

- packages/stan/kibana/visualization/stan-0e412fe0-4371-11ea-b0c6-cb14c0977bd1.json
- packages/stan/kibana/visualization/stan-46a07ac0-436d-11ea-b0c6-cb14c0977bd1.json
- packages/stan/manifest.yml
Follow up of https://github.com/elastic/integrations/pull/532 to add missing datastream filters to kibana visualisations.
Part of https://github.com/elastic/integrations/issues/363/
> Add missing datastream filters

- packages/apache/data_stream/access/fields/ecs.yml
- packages/apache/data_stream/error/fields/ecs.yml
- packages/apache/docs/README.md
- packages/apache/manifest.yml
I think these event ECS fields are missing for apache package. This PR is to add them into the `ecs.yml` files.
> Add event fields into ecs.yml for apache

- packages/suricata/data_stream/eve/fields/agent.yml
- packages/suricata/data_stream/eve/fields/fields-epr.yml
- packages/suricata/docs/README.md
- packages/suricata/manifest.yml
This updates the suricata package to use wildcard fields that were introduced in ECS 1.7.0 experimental and are already used in beats. The package itself was synced with the latest pipeline changes in https://github.com/elastic/integrations/pull/457 but the keyword fields that got changed to wildcards still needed to be updated.
> Update suricata integration with wildcard fields

- packages/linux/_dev/build/docs/README.md
- packages/linux/data_stream/entropy/manifest.yml
- packages/linux/data_stream/network_summary/manifest.yml
- packages/linux/data_stream/raid/manifest.yml
- packages/linux/data_stream/service/manifest.yml
- packages/linux/data_stream/socket/manifest.yml
- packages/linux/data_stream/users/manifest.yml
- packages/linux/docs/README.md
- packages/linux/manifest.yml
- This fixes a handful of documentation issues in the linux module relating to config labels and the readme.
- https://github.com/elastic/integrations/issues/546
- https://github.com/elastic/integrations/issues/547
- https://github.com/elastic/integrations/issues/548
> Fix linux documentation and config names

- packages/fleet_server/elasticsearch/index_template/.fleet-actions.json
- packages/fleet_server/manifest.yml
Rename action input_id to input_type. Instead of integration input id that is generated every time by kibana, rely on more stable integration input type.
This integration was not released and still under development, should be safe to break.
- Relates to Fleet Server change https://github.com/elastic/fleet-server/pull/73
> Rename action input_id to input_type

- packages/aws/data_stream/billing/fields/ecs.yml
- packages/aws/data_stream/cloudwatch_metrics/fields/ecs.yml
- packages/aws/data_stream/dynamodb/fields/ecs.yml
- packages/aws/data_stream/ebs/fields/ecs.yml
- packages/aws/data_stream/ec2_metrics/fields/ecs.yml
- packages/aws/data_stream/ec2_metrics/fields/fields.yml
- packages/aws/data_stream/elb_metrics/fields/ecs.yml
- packages/aws/data_stream/lambda/fields/ecs.yml
- packages/aws/data_stream/natgateway/fields/ecs.yml
- packages/aws/data_stream/rds/fields/ecs.yml
- packages/aws/data_stream/s3_daily_storage/fields/ecs.yml
- packages/aws/data_stream/s3_request/fields/ecs.yml
- packages/aws/data_stream/sns/fields/ecs.yml
- packages/aws/data_stream/sqs/fields/ecs.yml
- packages/aws/data_stream/transitgateway/fields/ecs.yml
- packages/aws/data_stream/usage/fields/ecs.yml
- packages/aws/data_stream/vpn/fields/ecs.yml
- packages/aws/docs/README.md
This PR is to fix missing field definitions in AWS package.
> Add missing field definitions into AWS data streams

- packages/osquery_elastic_managed/data_stream/osquery/manifest.yml
- packages/osquery_elastic_managed/docs/README.md
- packages/osquery_elastic_managed/manifest.yml
I noticed the naming inconsistencies with the official product https://osquery.io/
Fixed em.
> Fix Osquery naming, to make consistent with the official product naming

- packages/linux/data_stream/conntrack/manifest.yml
- packages/linux/data_stream/entropy/manifest.yml
- packages/linux/data_stream/ksm/manifest.yml
- packages/linux/data_stream/network_summary/manifest.yml
- packages/linux/data_stream/pageinfo/manifest.yml
- packages/linux/data_stream/raid/manifest.yml
- packages/linux/data_stream/service/manifest.yml
- packages/linux/data_stream/socket/manifest.yml
- packages/linux/data_stream/users/manifest.yml
- packages/linux/manifest.yml
Addresses https://github.com/elastic/integrations/issues/548 and cleans up some of the config values in the Linux integration.
- Pull down and build
- Start up the elastic stack
- Go into the Linux integration, make sure the config fields in the Integration say `Linux host...`.
> Clean up linux config value names

- packages/fleet_server/elasticsearch/index_template/.fleet-actions-results.json
- packages/fleet_server/manifest.yml
This change flattens the .fleet-actions-results schema moving to the action top level the additional properties ```started_at```, ```completed_at```, ```action_data```
> Update .fleet-actions-results mapping

- packages/linux/_dev/build/docs/README.md
- packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
- packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
- packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
- packages/linux/docs/README.md
- packages/linux/manifest.yml
- packages/system/_dev/build/docs/README.md
- packages/system/data_stream/process/agent/stream/stream.yml.hbs
- packages/system/data_stream/process_summary/agent/stream/stream.yml.hbs
- packages/system/data_stream/socket_summary/agent/stream/stream.yml.hbs
- packages/system/docs/README.md
- packages/system/manifest.yml
This PR adds `system.hostfs` options for `system` and `linux` package. This setting was introduced in https://github.com/elastic/beats/pull/23831 in oder to resolve https://github.com/elastic/beats/issues/22915.
0. Update properly the stack manifest file so as to mount the proper directories inside the docker container:
```
- "0.0.0.0:5601:5601"
kibana_is_ready:
image: tianon/true
depends_on:
kibana:
condition: service_healthy
package-registry:
build:
context: .
dockerfile: Dockerfile.package-registry
healthcheck:
test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
retries: 300
interval: 1s
ports:
- "0.0.0.0:8080:8080"
package-registry_is_ready:
image: tianon/true
depends_on:
package-registry:
condition: service_healthy
elastic-agent:
image: …
```
> Add system.hostfs setting

- go.mod
- go.sum
Updates the dependency on `elastic-package` to bring in https://github.com/elastic/elastic-package/pull/247.
- Will benefit https://github.com/elastic/integrations/pull/674
> Updates the dependency on elastic-package

- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/data_stream/apiserver/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/controllermanager/manifest.yml
- packages/kubernetes/data_stream/scheduler/manifest.yml
- packages/kubernetes/data_stream/state_container/manifest.yml
- packages/kubernetes/data_stream/state_cronjob/manifest.yml
- packages/kubernetes/data_stream/state_daemonset/manifest.yml
- packages/kubernetes/data_stream/state_deployment/manifest.yml
- packages/kubernetes/data_stream/state_node/manifest.yml
- packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
- packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
- packages/kubernetes/data_stream/state_pod/manifest.yml
- packages/kubernetes/data_stream/state_replicaset/manifest.yml
- packages/kubernetes/data_stream/state_resourcequota/manifest.yml
- packages/kubernetes/data_stream/state_service/manifest.yml
- packages/kubernetes/data_stream/state_statefulset/manifest.yml
- packages/kubernetes/data_stream/state_storageclass/manifest.yml
- packages/kubernetes/docs/README.md
- packages/kubernetes/manifest.yml
This PR is the final part of https://github.com/elastic/integrations/issues/511. Based on the specs defined at [migration assessment](https://github.com/elastic/obs-dc-team/blob/master/migration/packages/kubernetes.md), only specific datastreams should be 
enabled by default. This PR makes the appropriate changes so as to enable by default only the datastreams that were defined as default in the [migration assessment](https://github.com/elastic/obs-dc-team/blob/master/migration/packages/kubernetes.md).
Also setting the kibana version to `kibana.version: ">=7.11.0"`.
Note: Manual test of Dashboards performed using data shipped from [Elastic-Agent-Standalone](https://github.com/elastic/beats/pull/23679)
> Enable only default datastreams of k8s package

- packages/linux/data_stream/conntrack/agent/stream/stream.yml.hbs
- packages/linux/data_stream/iostat/agent/stream/stream.yml.hbs
- packages/linux/data_stream/ksm/agent/stream/stream.yml.hbs
- packages/linux/data_stream/memory/agent/stream/stream.yml.hbs
- packages/linux/data_stream/pageinfo/agent/stream/stream.yml.hbs
- packages/linux/manifest.yml
- packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/perfmon/agent/stream/stream.yml.hbs
- packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/service/agent/stream/stream.yml.hbs
- packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
- packages/windows/manifest.yml
This PR adds conditional guards to the windows and Linux modules to prevent them from running on non-compatible OSes. I'm still testing this on non-linux OSes.
- pull down PR, build and setup kibana with the integration
- Create a policy with the `system`, `linux` and `windows` integrations
- Apply the policy to an agent
- Make sure the agent is showing a healthy status, and that non-compatible data streams aren't trying to run on the agent.
- https://github.com/elastic/beats/issues/23996
> Add guards to OS-specific data streams

- packages/fleet_server/manifest.yml
Change default bind port from 8000 to 8220 for Fleet Server integration configuration.
Follow up on: https://github.com/elastic/fleet-server/pull/92#pullrequestreview-591730588
> [Fleet Server] Change default bind port from 8000 to 8220

- packages/linux/changelog.yml
- packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
- packages/linux/data_stream/network_summary/agent/stream/stream.yml.hbs
- packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
- packages/linux/data_stream/service/agent/stream/stream.yml.hbs
- packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
- packages/linux/data_stream/users/agent/stream/stream.yml.hbs
- packages/linux/manifest.yml
- packages/windows/changelog.yml
- packages/windows/data_stream/security/agent/stream/winlog.yml.hbs
- packages/windows/manifest.yml
Fixes https://github.com/elastic/beats/issues/23996
I keep on forgetting this isn't metricbeat, and more metricsets are enabled now. We'll need OS guards across most things that aren't broadly cross-compatible. 
- Pull down, build with `elastic-package`
- run on MacOS or windows, enabled `linux` package and make sure there's no errors and the agent is healthy.
- https://github.com/elastic/beats/issues/23996
> Add additional guards for Linux/Windows

- packages/azure/changelog.yml
- packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
- packages/azure/data_stream/activitylogs/agent/stream/azure-eventhub.yml.hbs
- packages/azure/data_stream/activitylogs/agent/stream/log.yml.hbs
- packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/activitylogs/fields/ecs.yml
- packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
- packages/azure/data_stream/auditlogs/agent/stream/azure-eventhub.yml.hbs
- packages/azure/data_stream/auditlogs/agent/stream/log.yml.hbs
- packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-remote-raw.log-expected.json
- packages/azure/data_stream/platformlogs/agent/stream/azure-eventhub.yml.hbs
- packages/azure/data_stream/platformlogs/agent/stream/log.yml.hbs
- packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
- packages/azure/data_stream/signinlogs/agent/stream/azure-eventhub.yml.hbs
- packages/azure/data_stream/signinlogs/agent/stream/log.yml.hbs
- packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/signinlogs/fields/ecs.yml
- packages/azure/docs/README.md
- packages/azure/manifest.yml
Syncs azure package with latest changes made in beats
> Sync azure package with beats

- packages/microsoft/changelog.yml
- packages/microsoft/data_stream/defender_atp/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft/manifest.yml
Drops any present `cloud` field to be able to set it with event provided values.
Related failures: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/107/tests
> Drop cloud field in Defender ATP to set it with provided values

- packages/kubernetes/_dev/deploy/docker/docker-compose.yml
This PR defines healthchecks for the Docker service used by the Kubernetes integration. The lack of healthchecks caused problems for the master branch (HTTP 502 errors).
> Define healthchecks for Kubernetes integration

- go.mod
- go.sum
This PR updates the elastic-package to temporarily switch the Agent's image to hardcoded stable one.
~- [ ] I have reviewed [tips for building integrations]~(https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- https://github.com/elastic/beats/issues/24198
> Temporarily use hardcoded agent image reference

- go.mod
- go.sum
- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_node/fields/fields.yml
- packages/kubernetes/docs/README.md
- packages/kubernetes/manifest.yml
This PR updates the dependency on elastic-package to use the 7.13.0-SNAPSHOT stack.
~- [ ] I have reviewed [tips for building integrations]~(https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
CI will verify it.
> Bump up the stack to 7.13

- packages/checkpoint/changelog.yml
- packages/checkpoint/manifest.yml
- packages/crowdstrike/changelog.yml
- packages/crowdstrike/manifest.yml
- packages/kubernetes/changelog.yml
- packages/kubernetes/manifest.yml
- packages/nats/changelog.yml
- packages/nats/manifest.yml
- packages/o365/changelog.yml
- packages/o365/manifest.yml
- packages/okta/changelog.yml
- packages/okta/manifest.yml
- packages/panw/changelog.yml
- packages/panw/manifest.yml
- packages/prometheus/changelog.yml
- packages/prometheus/manifest.yml
- packages/stan/changelog.yml
- packages/stan/manifest.yml
- packages/suricata/changelog.yml
- packages/suricata/manifest.yml
Packages must contain kibana.version: '^7.12.0' and NOT '>7.12.0', for example.
Otherwise these packages will automatically be compatible with 8.0 which we are not sure yet.
> Use kibana.version ^ instead of >=

- packages/aws/data_stream/ec2_metrics/_dev/deploy/tf/main.tf
This PR modifies TF definition for AWS EC2 metrics system test to correctly select the instance type. Otherwise the TF runner fails like https://github.com/elastic/elastic-package/pull/265 .
> Fix: correctly filter AWS instance type

- .ci/Jenkinsfile
To avoid two or more stages fight for a node on gobld we introduce a small sleep before the node provisioning enough to reduce the concurrence of request. Also, we fixed the node typo to Ubuntu-20 to avoid using old version of Ubuntu
> ci: spread the agent provision to avoid conflicts

- .ci/Jenkinsfile
- go.mod
- go.sum
This PR temporarily switches to the stable revision of Elastic Agent until https://github.com/elastic/beats/issues/24310 is fixed.
The PR also disables compatibility checks with older stack versions (as the tool doesn't support them currently, due to the mentioned issue).
- https://github.com/elastic/beats/issues/24310
> Temporary switch to stable image of Elastic Agent

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/fields/package-fields.yml
- packages/netflow/docs/README.md
- packages/netflow/manifest.yml
Updates the vendor fields as a result of https://github.com/elastic/beats/pull/23773.
- Relates https://github.com/elastic/beats/pull/23773
> Update fields for Netflow module

- .ci/Jenkinsfile
- go.mod
- go.sum
This PR updates dependency on the elastic-package to use the latest 7.13.0-SNAPSHOT images (confirmed to be stable).
- https://github.com/elastic/beats/issues/24310
> Update elastic-package to use 7.13.0-SNAPSHOT

- .ci/Jenkinsfile
This PR modifies the CI check `isPrAffected`, so that it ignores modifications pushed to master branch and focuses only on the current branch.
- Fixes: https://github.com/elastic/integrations/issues/764
> Fix: git diff ignores "their" commits

- .ci/Jenkinsfile
Mitigate the failures due to aborted build by ensuring the Workers are one shoot based and there is a sleep to have a smooth ram up when requesting several workers at the same time.
> [CI] enable one shoot workers

- .ci/jobs/defaults.yml
Use the default value for periodic-folder-trigger = `none`
> periodic-folder-trigger (str): How often to scan for new branches or pull/change requests. Valid values: 1m, 2m, 5m, 10m, 15m, 20m, 25m, 30m, 1h, 2h, 4h, 8h, 12h, 1d, 2d, 1w, 2w, 4w. (default none)
[docs](https://docs.openstack.org/infra/jenkins-job-builder/project_workflow_multibranch.html)
Reduce the build load in the `beats-ci` for this particular scan, we don't build PRs when there is change in their target branch to reduce the number of resources in the cloud.
For instance, last night the trigger happened and triggered the build for all the PRs, as a consequence there were a big long queue
> [jjbb] remove periodic-folder-trigger

- packages/fleet_server/changelog.yml
- packages/fleet_server/manifest.yml
This is that gray area of both:
- Feature work
- Bug
came out of discussion in https://github.com/elastic/integrations/issues/787
It sets the manifest to be ^7.13 so we don't end up with accidental 7.12 usage and have to deal with SDH / upgrade bugs when folks go from 7.12 to 7.13 and DO want to use Fleet Server
~~- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~~
Anyone disagree or see that it would be a problem to better avoid this usage?  
after it is promoted / merged, make sure it does not appear for 7.12 BC / or shipped stacks
> prevent 7.12 Fleet-Server package usage to avoid future / upgrade bugs

- .ci/Jenkinsfile
Use the stash/unstash instead the `gitCheckout` in each parallel stage
Avoid issues with GitHub when it's down.
Avoid several entries for each gitcheckout in the jenkins ui
> [CI] use the stash/unstash approach

- dev/import-beats/changelog.go
- dev/import-beats/main.go
- dev/import-beats/packages.go
This PR enhances the `mage ImportBeats` script to generate a `changelog.yml` file for every imported package.
1. Import a package. Example:
```
PACKAGES=traefik mage ImportBeats
```
2.  Check that there is a `changelog.yml` file in the package's root folder with these contents:
```
- version: "<package version>"
changes:
- description: initial release
type: enhancement # can be one of: enhancement, bugfix, breaking-change
link: 
```
- Resolves partially #765
> Generate initial package changelog when importing from Beats modules

- packages/osquery/changelog.yml
- packages/osquery/docs/README.md
- packages/osquery/manifest.yml
> Update orignal osquery package description

- packages/linux/changelog.yml
- packages/linux/data_stream/iostat/manifest.yml
- packages/linux/data_stream/memory/manifest.yml
- packages/linux/data_stream/network_summary/manifest.yml
- packages/linux/manifest.yml
Right now, all the data streams in `linux` are disabled by default, which can be a tad confusing when a user clicks the slider to enable the data stream groups, and Kibana just enables all of the data streams, even when some streams like `raid` require a specific system config. This enables a few basic data streams, so uses get some data streams by default, and so they won't blindly enable the entire integration.
- Pull down, build, start stack
- Add the linux integration in the Kibana UI, make sure the data stream groups are on by default.
> Set a few data streams to enabled in the linux integration

- go.mod
- go.sum
@mtojek asked me to update the dependencies here once https://github.com/elastic/elastic-package/pull/303 was merged, so we can pull the updated version into CI, among other things. This was just `go get github.com/elastic/elastic-package@f187867` and `go mod tidy`.
> update dependencies for new elastic-package

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/docs/README.md
- packages/security_detection_engine/manifest.yml
Changed the title of the `security_detection_engine` package. Had some conversations with PM, it's looking like "Prebuilt Security Detection Rules" is the most logical title.
N/A
N/A
None
None
> Change the title of the security_detection_engine package

- packages/iptables/changelog.yml
- packages/iptables/data_stream/log/agent/stream/log.yml.hbs
- packages/iptables/data_stream/log/agent/stream/syslog.yml.hbs
- packages/iptables/manifest.yml
This PR updates the iptables package to use ecs 1.9.0.
> Update iptables to ecs 1.9.0

- packages/traefik/changelog.yml
- packages/traefik/data_stream/access/agent/stream/log.yml.hbs
- packages/traefik/manifest.yml
This PR updates the traefik package to use ecs 1.9.0.
> Update traefik to ecs 1.9.0

- packages/rabbitmq/changelog.yml
- packages/rabbitmq/data_stream/log/agent/stream/log.yml.hbs
- packages/rabbitmq/manifest.yml
This PR updates the rabbitmq package to use ecs 1.9.0.
> Update rabbitmq to ecs 1.9.0

- packages/infoblox/changelog.yml
- packages/infoblox/data_stream/nios/agent/stream/stream.yml.hbs
- packages/infoblox/data_stream/nios/agent/stream/tcp.yml.hbs
- packages/infoblox/data_stream/nios/agent/stream/udp.yml.hbs
- packages/infoblox/manifest.yml
This PR updates the infoblox package to use ecs 1.9.0.
> Update infoblox to ecs 1.9.0

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/log.yml.hbs
- packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
- packages/o365/manifest.yml
This PR updates the o365 package to use ecs 1.9.0.
> Update o365 to ecs 1.9.0

- packages/cyberark/changelog.yml
- packages/cyberark/data_stream/corepas/agent/stream/stream.yml.hbs
- packages/cyberark/data_stream/corepas/agent/stream/tcp.yml.hbs
- packages/cyberark/data_stream/corepas/agent/stream/udp.yml.hbs
- packages/cyberark/manifest.yml
This PR updates the cyberark package to use ecs 1.9.0.
> Update cyberark to ecs 1.9.0

- packages/f5/changelog.yml
- packages/f5/data_stream/bigipafm/agent/stream/stream.yml.hbs
- packages/f5/data_stream/bigipafm/agent/stream/tcp.yml.hbs
- packages/f5/data_stream/bigipafm/agent/stream/udp.yml.hbs
- packages/f5/data_stream/bigipapm/agent/stream/stream.yml.hbs
- packages/f5/data_stream/bigipapm/agent/stream/tcp.yml.hbs
- packages/f5/data_stream/bigipapm/agent/stream/udp.yml.hbs
- packages/f5/manifest.yml
This PR updates the f5 package to use ecs 1.9.0.
> Update f5 to ecs 1.9.0

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/admin/agent/stream/log.yml.hbs
- packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/drive/agent/stream/log.yml.hbs
- packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/groups/agent/stream/log.yml.hbs
- packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/login/agent/stream/log.yml.hbs
- packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/saml/agent/stream/log.yml.hbs
- packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/user_accounts/agent/stream/log.yml.hbs
- packages/google_workspace/manifest.yml
This PR updates the google_workspace package to use ecs 1.9.0.
> Update google_workspace to ecs 1.9.0

- packages/windows/_dev/build/docs/README.md
- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/forwarded/manifest.yml
- packages/windows/data_stream/powershell/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell/manifest.yml
- packages/windows/data_stream/powershell_operational/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell_operational/manifest.yml
- packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/sysmon_operational/manifest.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Relates to https://github.com/elastic/security-team/issues/884
Depends on https://github.com/elastic/integrations/pull/884
> Add splunk input for all windows data streams

- packages/winlog/_dev/build/docs/README.md
- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
- packages/winlog/data_stream/winlog/fields/winlog.yml
- packages/winlog/data_stream/winlog/manifest.yml
- packages/winlog/docs/README.md
- packages/winlog/manifest.yml
Adds Splunk input to winlog custom events package.
> Add Splunk httpjson input to winlog package

- go.mod
- go.sum
This PR updates the elastic-package to use stable Docker images (emergency fix).
> Emergency fix: Use stable Docker images

- packages/system/changelog.yml
- packages/system/data_stream/application/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/application/manifest.yml
- packages/system/data_stream/security/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/security/manifest.yml
- packages/system/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/system/manifest.yml
- packages/system/manifest.yml
Relates to elastic/security-team#884
Depends on https://github.com/elastic/integrations/pull/884
> Add Splunk input for application, security and system

- packages/okta/changelog.yml
- packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/okta/manifest.yml
Uses fail_on_template_error option for google_workspace and okta modules pagination.
In some cases, the expected value used to paginate might not be there, and we want this to interrupt the execution instead of doing a request with an unexpected empty value.
> Add fail_on_template_error in okta

- packages/okta/changelog.yml
- packages/okta/data_stream/system/fields/fields.yml
- packages/okta/manifest.yml
Syncs change made in https://github.com/elastic/beats/pull/24636
> Change okta.target to flattened for better search capabilities

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
- packages/google_workspace/manifest.yml
Uses fail_on_template_error option for google_workspace and okta modules pagination.
In some cases, the expected value used to paginate might not be there, and we want this to interrupt the execution instead of doing a request with an unexpected empty value.
> Add fail_on_template_error in google_workspace

- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/data_stream/result/fields/package-fields.yml
- packages/osquery_manager/data_stream/result/fields/primary-fields.yml
- packages/osquery_manager/manifest.yml
Explicit mapping for all osquery fields.
Following this recommendation for mapping
https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html
```
Consider mapping a numeric identifier as a keyword if:
You don’t plan to search for the identifier data using range queries.
Fast retrieval is important. term query searches on keyword fields are often faster than term searches on numeric fields.
If you’re unsure which to use, you can use a multi-field to map the data as both a keyword and a numeric data type.
```
The fields mapping is generated from the official osquery 4.7.0 schema. The numeric fields are mapped to keywords, the text fields had additional text multifield defined.
- Relates https://github.com/elastic/security-team/issues/935
osquery mapping:
collected osquery …
> Explicit mapping for all osquery fields

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
- Bug
Adjusts the type of the check.receive field in the tcp data_stream.
> adjust tcp data_stream check.receive type to text

- packages/apache/changelog.yml
- packages/apache/kibana/ml_module/apache-Logs-ml.json
- packages/apache/manifest.yml
Adds an ML module containing anomaly detection jobs for finding unusual activity in HTTP access logs to the Apache integration. Requires Kibana 7.13.0 or later.
These are the same five jobs that have previously been stored inside the ML Kibana plugin:
- Detect unusual visitor rates
- Detect unusual status code rates
- Detect unusual source IPs - high distinct count of URLs
- Detect unusual source IPs - high request rate
- Detect low request rates
Some minor edits have been made to the previous job configurations stored in the ML Kibana plugin:
- ID of the module is `apache_data_stream` compared to `apache_ecs` for the legacy module
- Module and datafeed queries use `data_stream.dataset: apache.access` compared to `event.dataset: apache.access` for the legacy module
- The ML module no …
> [ML] Adds ML jobs for access logs to Apache package

- packages/nginx/changelog.yml
- packages/nginx/kibana/ml_module/nginx-Logs-ml.json
- packages/nginx/manifest.yml
Adds an ML module containing anomaly detection jobs for finding unusual activity in HTTP access logs to the Nginx integration. Requires Kibana 7.13.0 or later.
These are the same five jobs that have previously been stored inside the ML Kibana plugin:
- Detect unusual visitor rates
- Detect unusual status code rates
- Detect unusual source IPs - high distinct count of URLs
- Detect unusual source IPs - high request rate
- Detect low request rates
Some minor edits have been made to the previous job configurations stored in the ML Kibana plugin:
- ID of the module is `ngix_data_stream` compared to `nginx_ecs` for the legacy module
- Module and datafeed queries use `data_stream.dataset: nginx.access` compared to `event.dataset: nginx.access` for the legacy module
- The ML module no longer …
> [ML] Adds ML jobs for access logs to Nginx package

- .ci/Jenkinsfile
This PR updates stack image reference due to the caching issue we faced - cached images are not compatible with each other.
> Fix: update stack image references

- go.mod
- go.sum
Updating elastic-package dep to include https://github.com/elastic/elastic-package/pull/332
> Upgrade elastic-package to use updated k8s service deployer

- packages/system/changelog.yml
- packages/system/data_stream/application/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/security/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/system/manifest.yml
Uses `decode_xml_wineventlog` processor instead of `decode_xml`
> Use decode_xml_wineventlog in system Splunk inputs

- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
- packages/winlog/manifest.yml
Uses `decode_xml_wineventlog` processor instead of `decode_xml`
> Use decode_xml_wineventlog in winlog Splunk inputs

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell_operational/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
- packages/windows/manifest.yml
Uses `decode_xml_wineventlog` processor instead of `decode_xml`
> Use decode_xml_wineventlog in windows Splunk inputs

- packages/suricata/manifest.yml
Changes minimum version of Kibana/ES to 7.13 to work with the newer processors introduced in 7.12 and 7.13 for suricata. This is an addition to the 0.6.0 package version, so no new changelog is added.
> [Suricata] Up the minimum version of kibana

- packages/zeek/manifest.yml
Sets the minimum version of ES/Kibana for zeek package to 7.13 for the `registered_domain` processor
> [Zeek] Change minimum version to 7.13

- docs/definitions.md
- docs/developer_workflow_design_build_test_integration.md
It describes the different type of `_dev` dirs that are supported when building and testing an integration package.
> docs: describe the purpose of the _dev dirs

- packages/fleet_server/agent/input/agent.yml.hbs
- packages/fleet_server/changelog.yml
- packages/fleet_server/manifest.yml
There are a few expert configurations available for fleet-server which should be tuned especially when scaling it. In the future, fleet-server should be able to potentially tune this automatically. For now we should allow expert users to configure these.
With this change, the policy UI looks as following:
> [fleet_server] Add yaml block for custom configurations

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/apiserver/manifest.yml
- packages/kubernetes/data_stream/container/manifest.yml
- packages/kubernetes/data_stream/node/manifest.yml
- packages/kubernetes/data_stream/pod/manifest.yml
- packages/kubernetes/data_stream/scheduler/manifest.yml
- packages/kubernetes/data_stream/system/manifest.yml
- packages/kubernetes/data_stream/volume/manifest.yml
- packages/kubernetes/manifest.yml
This PR fixes default values for k8s package and more specifically references to env variables which should be prefixed with `env.` so as to be properly evaluated by Agent.
> Fix k8s package's env references

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
- packages/synthetics/manifest.yml
Fixes #980 
Adjusts formatting of the `add_fields` processor.
Previously, the processor was formatted with incorrect yaml, this caused the nasty error described in #980 
1. Pull down this PR
2. Navigate to the `packages/synthetics` directory
3. Run `elastic-package build`
4. Run `elastic-package stack up -s 'package-registry'`
5. Update the registry url in kibana.dev.yml to `xpack.fleet.registryUrl: "http://localhost:8080"`
6. Pull down Kibana locally and run Kibana with `yarn start --no-base-path` and ES with `yarn es snapshot -E xpack.security.authc.api_key.enabled=true --license trial`
7. Navigate to fleet and add an agent
8. Navigate to the synthetics integration and configure a tcp and icmp monitor. Ensure the monitors are displayed in Uptime
> [Synthetics] fix add fields formatting

- packages/aws/_dev/build/docs/README.md
- packages/aws/changelog.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
This PR is to update the `role_arn` documentation to sync with https://github.com/elastic/beats/pull/25446 change made in libbeat for 7.13.
> Update documentation for using role_arn

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
- packages/auditd/data_stream/log/agent/stream/log.yml.hbs
- packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/auditd/data_stream/log/fields/base-fields.yml
- packages/auditd/data_stream/log/manifest.yml
- packages/auditd/docs/README.md
- packages/auditd/manifest.yml
Moves remaining edge processing to the ingest pipeline and make `event.original` optional
> [auditd] Move edge to ingest pipeline and make event.original optional

- packages/fleet_server/agent/input/agent.yml.hbs
- packages/fleet_server/changelog.yml
- packages/fleet_server/manifest.yml
The max_connection config was missing the limits prefix and was not working because of this.
> [fleet_server] Fix max_connection config issue

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-6-0.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-dns-4-1-4.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
- packages/suricata/data_stream/eve/agent/stream/log.yml.hbs
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
- packages/suricata/manifest.yml
Makes event.original optional
- Relates to #777
> [suricata] Make event.original optional

- packages/system/changelog.yml
- packages/system/data_stream/application/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/application/agent/stream/winlog.yml.hbs
- packages/system/data_stream/application/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/security/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/security/agent/stream/winlog.yml.hbs
- packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/system/data_stream/system/agent/stream/winlog.yml.hbs
- packages/system/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/system/manifest.yml
Makes event.original optional for application, security, and system data streams.
NOTE: In this case, `event.original` is already present from the winlog and httpjson inputs.
- Relates https://github.com/elastic/integrations/issues/777
> [system] Make event.original optional for application, security, and system ata streams

- packages/aws/changelog.yml
- packages/aws/manifest.yml
This PR is to set Kibana version to ^7.13.0 for aws package.
> set kibana version to ^7.13.0 for aws package

- packages/traefik/changelog.yml
- packages/traefik/manifest.yml
Updates the minimum version of Kibana required for the `traefik-0.1.2` package to `7.13.0`.
> Updating Kibana version condition to 7.13.0

- packages/fleet_server/changelog.yml
- packages/fleet_server/docs/README.md
- packages/fleet_server/manifest.yml
Adding a description to address https://github.com/elastic/integrations/issues/787
- Closes https://github.com/elastic/integrations/issues/787
> Update README.md for Fleet Server

- packages/cisco/changelog.yml
- packages/cisco/manifest.yml
Fixes the Cisco package being broken (not-installable).
It would cause the following error in Kibana when trying to configure it:
```
kbn-ui-shared-deps.js:382 TypeError: Root value is not flatten-able, received undefined
at getFlattenedObject (:9243/39457/bundles/plugin/fleet/fleet.chunk.0.js:3)
at countValidationErrors (:9243/39457/bundles/plugin/fleet/fleet.chunk.2.js:39)
at :9243/39457/bundles/plugin/fleet/fleet.chunk.2.js:39
[...]
```
Due to an input defined in the main manifest.yml that was not used by any data stream.
The package seem to have been broken for a long time.
- Closes https://github.com/elastic/kibana/issues/100340
> Fix broken Cisco package

- packages/synthetics/changelog.yml
- packages/synthetics/manifest.yml
This PR bumps the version to 0.1.0 for the 7.13.0 release.
> [Synthetics] bump version to 0.1.0 for 7.13.0 release

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-config.yml
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
- packages/netflow/data_stream/log/agent/stream/netflow.yml.hbs
- packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/netflow/manifest.yml
Moves ecs.version to the ingest pipeline and add pipeline tests.
- Relates #961
> [netflow] Add pipeline tests and move ecs.version to ingest pipeline

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/manifest.yml
Adds a fingerprint processor for the `json.id` object, and uses it as the document id to prevent duplicated events in case of re processing.
> [google_workspace] Use fingerprint of id object as document id

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-config.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
- packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
- packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
- packages/panw/manifest.yml
Makes event.original optional
- Relates #777
- Relates #961
> [panw] Make event.original optional

- packages/okta/_dev/build/docs/README.md
- packages/okta/changelog.yml
- packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-config.yml
- packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
- packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/okta/data_stream/system/agent/stream/log.yml.hbs
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/data_stream/system/manifest.yml
- packages/okta/data_stream/system/sample_event.json
- packages/okta/docs/README.md
- packages/okta/manifest.yml
Makes event.original optional in the same way as the rest of packages.
- Relates #777
- Relates #961
> [okta] Make event.original optional

- go.mod
- go.sum
This is just `go get github.com/elastic/elastic-package@master` and `go mod tidy`. We're updating the `elastic-package` dependency now that the enhancement for profiles has been merged.
> Update elastic-package dependency

- packages/apache/data_stream/status/_dev/test/system/test-default-config.yml
This PR temporarily skips the `apache/status` data stream's system test. This test should be un-skipped once https://github.com/elastic/beats/issues/26120 is resolved.
> Skip apache/status system test

- packages/docker/changelog.yml
- packages/docker/data_stream/cpu/fields/fields.yml
- packages/docker/docs/README.md
- packages/docker/manifest.yml
This PR fixes the Elasticsearch mapping data types for the following fields:
- `docker.cpu.core.*.norm.pct`
- `docker.cpu.core.*.pct`
- `docker.cpu.core.*.ticks`
- Fixes #1080
> Fixing data types of scalar fields

- packages/system/changelog.yml
- packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
- packages/system/manifest.yml
In 7.13.1 event.code was fixed on winlog input and changed from an int to a keyword. This change fixes the pipeline to support this change.
> [system] Fix security pipeline to support string event.code

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudtrail/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/cloudtrail/manifest.yml
- packages/aws/manifest.yml
Adds support for AWS CloudTrail Digest and AWS CloudTrail Insight Logs
~~- [ ] If I'm introducing a new feature, I have modified the Kibana
version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).~~
Setup CloudTrail with Insight logs.
- Closes #1022
> Add support for CloudTrail Digest and Insight Logs

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-config.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-config.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
- packages/auditd/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/auditd/data_stream/log/agent/stream/log.yml.hbs
- packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/auditd/data_stream/log/fields/ecs.yml
- packages/auditd/data_stream/log/manifest.yml
- packages/auditd/docs/README.md
- packages/auditd/manifest.yml
Updates package ECS version to 1.10.
Sync module changes to packages if any.
Adds Preserve Raw event functionality if not already exists.
Adds pipeline tests if missing.
- Relates #994
> [Auditd] updating auditd package to ECS 1.10

- packages/radware/changelog.yml
- packages/radware/data_stream/defensepro/agent/stream/stream.yml.hbs
- packages/radware/data_stream/defensepro/agent/stream/tcp.yml.hbs
- packages/radware/data_stream/defensepro/agent/stream/udp.yml.hbs
- packages/radware/data_stream/defensepro/elasticsearch/ingest_pipeline/default.yml
- packages/radware/data_stream/defensepro/manifest.yml
- packages/radware/manifest.yml
Updates package ECS version to 1.10.
Sync module changes to packages if any.
Adds Preserve Raw event functionality if not already exists.
Adds pipeline tests if missing.
Adds missing tags + moving tags to advanced settings.
Adds possibility to add custom processors.
- Relates #994
> [Radware] update radware ECS version and adding event.original options

- packages/apache/data_stream/status/_dev/test/system/test-default-config.yml
This reverts commit 867f6723c13f69bf981ad32baa77ac5d90349334.
- https://github.com/elastic/elastic-package/issues/374
> Revert "Skip apache/status system test (#1078)"

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/log/_dev/test/pipeline/test-mongodb-debian.log-expected.json
- packages/mongodb/data_stream/log/_dev/test/pipeline/test-mongodb-ubuntu-4-4-4.log-expected.json
- packages/mongodb/data_stream/log/elasticsearch/ingest_pipeline/pipeline-json.yml
- packages/mongodb/data_stream/log/fields/fields.yml
- packages/mongodb/docs/README.md
Store the structured attributes included in JSON logs, using the `flattened` type for that.
- JSON logs support added in #1138.
> Store structured attributes from MongoDB logs in JSON format

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Removed the pre-release qualifier, since this package is ready for production.
Just a version bump so it can be released to production.
Same steps as other versions, like #1144 
None
None
> [Security Rules] Release rules package 0.13.1

- packages/mongodb/_dev/build/build.yml
- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/collstats/fields/ecs.yml
- packages/mongodb/data_stream/collstats/fields/fields.yml
- packages/mongodb/data_stream/dbstats/fields/ecs.yml
- packages/mongodb/data_stream/log/fields/ecs.yml
- packages/mongodb/data_stream/metrics/fields/ecs.yml
- packages/mongodb/data_stream/replstatus/fields/ecs.yml
- packages/mongodb/data_stream/status/fields/ecs.yml
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
CI will verify if the integration works correctly.
- https://github.com/elastic/package-spec/issues/63
> MongoDB: Enable ECS dependency

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/fields/ecs.yml
- packages/windows/data_stream/powershell/fields/ecs.yml
- packages/windows/data_stream/powershell_operational/fields/ecs.yml
- packages/windows/data_stream/sysmon_operational/fields/ecs.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Uses wildcard field type for the relevant ECS fields.
> [windows] Use wildcard field type

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/fields/ecs.yml
- packages/suricata/docs/README.md
- packages/suricata/manifest.yml
Uses `wildcard` field type instead of `keyword` for relevant ECS fields.
> [suricata] Use wildcard type

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/fields/ecs.yml
- packages/netflow/docs/README.md
- packages/netflow/manifest.yml
Uses wildcard field type for the relevant ECS fields.
> [netflow] Use wildcard type

- packages/system/changelog.yml
- packages/system/data_stream/security/fields/ecs.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
Uses wildcard field type in the relevant ECS fields of the security stream
> [system] Use wildcard type for security stream

- .ci/Jenkinsfile
This PR adjusts graceful shutdown of Kind cluster while there is an error.
CI job (failing on purpose): https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-1202/1/pipeline/378
Kubernetes task boots the kind cluster, then fails, so the try-catch-finally blocks tears down the cluster first, then Elastic stack. Without this fix, the kind cluster wasn't stopped, so the `elastic-package stack down` failed with "active endpoints error".
- Fixes: https://github.com/elastic/elastic-package/issues/383
> Fix: adjust graceful shutdown of Kind cluster while there is an error

- packages/redis/changelog.yml
- packages/redis/data_stream/info/fields/base-fields.yml
- packages/redis/data_stream/key/fields/base-fields.yml
- packages/redis/data_stream/keyspace/fields/base-fields.yml
- packages/redis/data_stream/log/fields/base-fields.yml
- packages/redis/data_stream/slowlog/fields/base-fields.yml
- packages/redis/docs/README.md
- packages/redis/manifest.yml
> [Redis] set event.module and event.dataset

- packages/aws/changelog.yml
- packages/aws/data_stream/elb_logs/_dev/test/pipeline/test-alb.log-expected.json
- packages/aws/data_stream/elb_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/elb_logs/fields/ecs.yml
- packages/aws/docs/README.md
- packages/aws/manifest.yml
This PR is to sync changes made in https://github.com/elastic/beats/pull/26441 with AWS package.
> Update AWS ELB ingest pipeline

- go.mod
- go.sum
Update to https://github.com/elastic/elastic-package/commit/2278b9ec04a65488757fde3691126f0d551bb4c5. This adds validation that if a document contains a constant_keyword field that its value must match the declared `value` from the fields definition (if declared).
- Relates https://github.com/elastic/package-spec/pull/194
- Relates https://github.com/elastic/elastic-package/pull/386
> Update elastic-package version for constant_keyword value

- packages/nats/changelog.yml
- packages/nats/data_stream/connection/fields/base-fields.yml
- packages/nats/data_stream/connections/fields/base-fields.yml
- packages/nats/data_stream/log/fields/base-fields.yml
- packages/nats/data_stream/route/fields/base-fields.yml
- packages/nats/data_stream/routes/fields/base-fields.yml
- packages/nats/data_stream/stats/fields/base-fields.yml
- packages/nats/data_stream/subscriptions/fields/base-fields.yml
- packages/nats/docs/README.md
- packages/nats/manifest.yml
This PR adds event.module and event.dataset to the integration.
> [Nats] set event.module and event.dataset

- packages/nginx_ingress_controller/changelog.yml
- packages/nginx_ingress_controller/data_stream/access/fields/base-fields.yml
- packages/nginx_ingress_controller/data_stream/error/fields/base-fields.yml
- packages/nginx_ingress_controller/docs/README.md
- packages/nginx_ingress_controller/manifest.yml
> [Nginx Ingress Controller] Set event.module and event.dataset

- packages/apache/changelog.yml
- packages/apache/data_stream/access/fields/base-fields.yml
- packages/apache/data_stream/error/fields/base-fields.yml
- packages/apache/data_stream/status/fields/base-fields.yml
- packages/apache/docs/README.md
- packages/apache/manifest.yml
This PR adds event.module and event.dataset to the integration.
> [Apache] set event.module and event.dataset

- packages/cisco/changelog.yml
- packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/data_stream/asa/manifest.yml
- packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/data_stream/ftd/manifest.yml
- packages/cisco/manifest.yml
This removes the log level config option. I recommend configuring the device to
only send the log level you want (e.g. `logging trap <severity>`).
When these data streams were ported over from Beats they had a log_level
parameter, but that was never implemented for Fleet because it required a mutable
Ingest Node pipeline in order to inject the level into the pipeline.
- Closes #799
> Remove unimplemented "Log Level" parameter from Cisco ASA/FTD

- packages/linux/changelog.yml
- packages/linux/data_stream/conntrack/fields/base-fields.yml
- packages/linux/data_stream/entropy/fields/base-fields.yml
- packages/linux/data_stream/iostat/fields/base-fields.yml
- packages/linux/data_stream/ksm/fields/base-fields.yml
- packages/linux/data_stream/memory/fields/base-fields.yml
- packages/linux/data_stream/network_summary/fields/base-fields.yml
- packages/linux/data_stream/pageinfo/fields/base-fields.yml
- packages/linux/data_stream/raid/fields/base-fields.yml
- packages/linux/data_stream/service/fields/base-fields.yml
- packages/linux/data_stream/socket/fields/base-fields.yml
- packages/linux/data_stream/users/fields/base-fields.yml
- packages/linux/docs/README.md
- packages/linux/manifest.yml
> [Linux] set event.module and event.dataset

- packages/azure/changelog.yml
- packages/azure/data_stream/activitylogs/fields/base-fields.yml
- packages/azure/data_stream/auditlogs/fields/base-fields.yml
- packages/azure/data_stream/platformlogs/fields/base-fields.yml
- packages/azure/data_stream/signinlogs/fields/base-fields.yml
- packages/azure/docs/README.md
- packages/azure/manifest.yml
> [Azure] set event.module and event.dataset

- packages/stan/changelog.yml
- packages/stan/data_stream/channels/fields/base-fields.yml
- packages/stan/data_stream/log/fields/base-fields.yml
- packages/stan/data_stream/stats/fields/base-fields.yml
- packages/stan/data_stream/subscriptions/fields/base-fields.yml
- packages/stan/docs/README.md
- packages/stan/manifest.yml
> [STAN] set event.module and event.dataset

- packages/haproxy/changelog.yml
- packages/haproxy/data_stream/info/fields/base-fields.yml
- packages/haproxy/data_stream/log/fields/base-fields.yml
- packages/haproxy/data_stream/log/fields/ecs.yml
- packages/haproxy/data_stream/stat/fields/base-fields.yml
- packages/haproxy/docs/README.md
- packages/haproxy/manifest.yml
> [HAProxy] set event.module and event.dataset

- packages/docker/changelog.yml
- packages/docker/data_stream/container/fields/base-fields.yml
- packages/docker/data_stream/cpu/fields/base-fields.yml
- packages/docker/data_stream/diskio/fields/base-fields.yml
- packages/docker/data_stream/event/fields/base-fields.yml
- packages/docker/data_stream/event/sample_event.json
- packages/docker/data_stream/healthcheck/fields/base-fields.yml
- packages/docker/data_stream/image/fields/base-fields.yml
- packages/docker/data_stream/info/fields/base-fields.yml
- packages/docker/data_stream/memory/fields/base-fields.yml
- packages/docker/data_stream/network/fields/base-fields.yml
- packages/docker/docs/README.md
- packages/docker/manifest.yml
> [Docker] set event.module and event.dataset

- packages/zookeeper/changelog.yml
- packages/zookeeper/data_stream/connection/fields/base-fields.yml
- packages/zookeeper/data_stream/mntr/fields/base-fields.yml
- packages/zookeeper/data_stream/server/fields/base-fields.yml
- packages/zookeeper/docs/README.md
- packages/zookeeper/manifest.yml
This PR adds event.module and event.dataset to the integration.
> [zookeeper] set event.module and event.dataset

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/collstats/fields/base-fields.yml
- packages/mongodb/data_stream/dbstats/fields/base-fields.yml
- packages/mongodb/data_stream/log/fields/base-fields.yml
- packages/mongodb/data_stream/metrics/fields/base-fields.yml
- packages/mongodb/data_stream/replstatus/fields/base-fields.yml
- packages/mongodb/data_stream/status/fields/base-fields.yml
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
Add dataset and module fields to mongodb package
-
> Add dataset and module fields to mongodb package

- packages/zookeeper/changelog.yml
- packages/zookeeper/data_stream/connection/fields/base-fields.yml
- packages/zookeeper/data_stream/mntr/fields/base-fields.yml
- packages/zookeeper/data_stream/server/fields/base-fields.yml
- packages/zookeeper/docs/README.md
- packages/zookeeper/manifest.yml
This PR brings back `data_stream` fields removed in previous PR: https://github.com/elastic/integrations/pull/1248 .
Spotted in: https://github.com/elastic/package-storage/pull/1517
> Fix: add missing data_stream fields

- packages/rabbitmq/changelog.yml
- packages/rabbitmq/data_stream/node/sample_event.json
- packages/rabbitmq/docs/README.md
- packages/rabbitmq/manifest.yml
This PR fixes invalid sample event for `rabbitmq.node`.
> [RabbitMQ] Fix sample event for node

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/fields/base-fields.yml
- packages/prometheus/data_stream/query/fields/base-fields.yml
- packages/prometheus/data_stream/remote_write/fields/base-fields.yml
- packages/prometheus/docs/README.md
- packages/prometheus/manifest.yml
Add `event.module` and `event.dataset` to all data streams in prometheus package.
From changes discussed in https://github.com/elastic/security-team/issues/780
I didn't run `elastic-package test` as I'm still setting up all the required environment.
> [prometheus] add event.module and event.dataset

- go.mod
- go.sum
Updates elastic-package to support dropped events in pipeline tests (elastic/elastic-package#397).
- Required for https://github.com/elastic/integrations/pull/1145
- Change in elastic-package elastic/elastic-package#397
> Update elastic-package to support dropped events in pipeline tests

- packages/barracuda/changelog.yml
- packages/barracuda/data_stream/spamfirewall/fields/base-fields.yml
- packages/barracuda/data_stream/waf/fields/base-fields.yml
- packages/barracuda/manifest.yml
> [barracuda] Set event.module and event.dataset

- packages/osquery/changelog.yml
- packages/osquery/data_stream/result/fields/base-fields.yml
- packages/osquery/data_stream/result/fields/ecs.yml
- packages/osquery/docs/README.md
- packages/osquery/manifest.yml
> [osquery] Set event.module and event.dataset

- packages/squid/changelog.yml
- packages/squid/data_stream/log/fields/base-fields.yml
- packages/squid/manifest.yml
> [squid] Set event.module and event.dataset

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-expected.json
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/auth_activity_audit.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/detection_summary.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/firewall_match.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/incident_summary.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/remote_response_session_end.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/remote_response_session_start.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/user_activity_audit.yml
- packages/crowdstrike/data_stream/falcon/fields/base-fields.yml
- packages/crowdstrike/data_stream/falcon/fields/ecs.yml
- packages/crowdstrike/docs/README.md
- packages/crowdstrike/manifest.yml
> [crowdstrike] Set event.module and event.dataset

- go.mod
- go.sum
This PR reverts latest elastic-package update pushed to the master branch.
Apparently it caused problems for traefik and zeek integrations (system tests).
For reference: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/512/pipeline/332
> Revert "Update dependency on elastic-package (#1283)"

- packages/system/changelog.yml
- packages/system/manifest.yml
The system module will be GA for 7.14. This is the version bump.
> ga system module

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/apiserver/fields/fields.yml
- packages/kubernetes/data_stream/container/fields/fields.yml
- packages/kubernetes/data_stream/controllermanager/fields/fields.yml
- packages/kubernetes/data_stream/event/fields/fields.yml
- packages/kubernetes/data_stream/node/fields/fields.yml
- packages/kubernetes/data_stream/pod/fields/fields.yml
- packages/kubernetes/data_stream/proxy/fields/fields.yml
- packages/kubernetes/data_stream/scheduler/fields/fields.yml
- packages/kubernetes/data_stream/state_container/fields/fields.yml
- packages/kubernetes/data_stream/state_cronjob/fields/fields.yml
- packages/kubernetes/data_stream/state_daemonset/fields/fields.yml
- packages/kubernetes/data_stream/state_deployment/fields/fields.yml
- packages/kubernetes/data_stream/state_node/fields/fields.yml
- packages/kubernetes/data_stream/state_persistentvolume/fields/fields.yml
- packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/fields.yml
- packages/kubernetes/data_stream/state_replicaset/fields/fields.yml
- packages/kubernetes/data_stream/state_resourcequota/fields/fields.yml
- packages/kubernetes/data_stream/state_statefulset/fields/fields.yml
- packages/kubernetes/data_stream/system/fields/fields.yml
- packages/kubernetes/data_stream/volume/fields/fields.yml
- packages/kubernetes/docs/events.md
- packages/kubernetes/docs/kube-apiserver.md
- packages/kubernetes/docs/kube-controller-manager.md
- packages/kubernetes/docs/kube-proxy.md
- packages/kubernetes/docs/kube-scheduler.md
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/docs/kubelet.md
- packages/kubernetes/manifest.yml
This change updates `fields.yml` defintions to include units and metric type information so as to enhance meta information for each collected Kubernetes fields in accordance with https://github.com/elastic/elasticsearch/pull/61941/. More example [here](https://github.com/elastic/kibana/issues/82273).
- Closes https://github.com/elastic/integrations/issues/934
> Add _meta information to Kubernetes fields

- packages/okta/changelog.yml
- packages/okta/manifest.yml
> [okta] Add missing initial_interval option to the manifest

- packages/linux/changelog.yml
- packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
- packages/linux/data_stream/network_summary/agent/stream/stream.yml.hbs
- packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
- packages/linux/data_stream/service/agent/stream/stream.yml.hbs
- packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
- packages/linux/data_stream/users/agent/stream/stream.yml.hbs
- packages/linux/manifest.yml
This is a fix for https://github.com/elastic/integrations/issues/1296
So, because a handful of `linux` data streams are actually backed by the `system` module within metricbeat, they'll break the mapping, since they'll report `event.module` as `system` and not `linux`. This adds a processor to said data streams, so we can drop the event in ingest, and then the proper value is inserted in the mapping.
This is a (somewhat) temporary workaround, as eventually the metricsets will be migrated to `linux`.
- Pull down and build
- On a linux host, run the elastic stack, add the linux integration and enable the `entropy`, `network_summary`, `service`, `socket` and  `users` data streams. Note: `users` and `service` won't work if you're running the agent from inside a docker container
- Make sure …
> Add Processors to linux package

- packages/aws/changelog.yml
- packages/aws/manifest.yml
This PR changes AWS default credential option to access keys. When running on Docker, AWS credential file needs to be provided via volume mount and this is not shipped with elastic agent by default. Therefore, we should recommend users to use access key, secret access key and/or session token as default credential option.
> Change AWS default credential option to access keys

- packages/prometheus/_dev/build/docs/README.md
- packages/prometheus/changelog.yml
- packages/prometheus/docs/README.md
- packages/prometheus/manifest.yml
This PR replaces `$yml` code blocks with `yml`.
- Fixes: https://github.com/elastic/integrations/issues/1322
> Fix: replace dollar-yml tags with yml

- go.mod
- go.sum
This PR updates dependency on elastic-package to the release v0.9.3 (not anymore "master").
> Update elastic-package to v0.9.3

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/agent/stream/stream.yml.hbs
- packages/osquery_manager/manifest.yml
Adds ECS mapping settings support for each query/stream.
Bumps up version to 0.4.0 and minimum kibana version to 7.15.0
The integration settings update payload with ```ecs_mapping``` (using ```/api/fleet/package_policies``` kibana API) example:
```
{
"version": "WzE3MjUsM10=",
"name": "osquery_manager-1",
"description": "",
"namespace": "default",
"policy_id": "548a3940-df4e-11eb-8fdd-b98cebb63257",
"enabled": true,
"output_id": "",
"package": {
"name": "osquery_manager",
"title": "Osquery Manager",
"version": "0.4.0"
},
"inputs": [
{
"policy_template": "osquery_manager",
"type": "osquery",
"enabled": true,
"streams": [
{
"data_stream": {
"type": "logs",
"dataset": "osquery_manager.result"
},
"id": "osquery-osquery_manager.result-1b63ffff-c050-4bef-98d9-fc8507fd1406",
"vars": {
"query": { …
```
> Osquery manager: ECS mapping support

- packages/azure/changelog.yml
- packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/manifest.yml
- add pipeline changes removed during module integration sync, offending PR https://github.com/elastic/integrations/pull/722
- add pipeline changes removed during module integration sync
> Re-adding pipeline changes removed by mistake

- packages/aws/changelog.yml
- packages/aws/manifest.yml
This PR is to remove network and security categories at the package level for AWS and add them into each policy template.
- Closes https://github.com/elastic/integrations/issues/1342
> Change categories in AWS package

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/agent/stream/stream.yml.hbs
- packages/osquery_manager/manifest.yml
Changes the format of ECS mapping configuration for the queries:
1. The mapping keys are the ECS key path
2. The mapping value is an object that allows to define the static ```value``` or the ```field``` which is the name of the osquery result column. 
Current format example:
```
"ecs_mapping": {
"user.custom.shoeSize": {
"value": 45
},
"user.id": {
"field": "uid"
},
"user.name": {
"field": "username"
}
}
```
The fragment of the document showing and example of the ECS fields mapped:
> Osquery_manager: Update ECS mapping format based on the latest developers feedback

- packages/synthetics/changelog.yml
- packages/synthetics/manifest.yml
Fixes elastic/kibana#104662
- Enhancement
Adds the synthetics package to Elastic Stack filter option.
> [Synthetics] adjust category to categorize under elastic_stack

- packages/fortinet/changelog.yml
- packages/fortinet/manifest.yml
Changes experimental label to GA, as the package is already in v1+ and the original intent is for it to be GA.
> [fortinet] Remove experimental label from manifest

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/manifest.yml
- packages/fleet_server/changelog.yml
- packages/fleet_server/manifest.yml
Move the `elastic_agent` and `fleet-server` packages to GA, changing the version to 1.0.0
- Closes #1329
> Move elastic_agent and fleet_server to GA

- go.mod
- go.sum
This PR updates dependency on elastic-package to support Go 1.16.
> Use Go 1.16

- packages/zscaler/changelog.yml
- packages/zscaler/data_stream/zia/_dev/test/pipeline/test-generated.log-expected.json
- packages/zscaler/data_stream/zia/_dev/test/pipeline/test-zscaler.log-expected.json
- packages/zscaler/data_stream/zia/elasticsearch/ingest_pipeline/default.yml
- packages/zscaler/manifest.yml
> zscaler update to ECS 1.11.0

- packages/traefik/changelog.yml
- packages/traefik/data_stream/access/_dev/test/pipeline/test-format-common.log-expected.json
- packages/traefik/data_stream/access/_dev/test/pipeline/test-format-json.log-expected.json
- packages/traefik/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/traefik/manifest.yml
> traefik update to ECS 1.11.0

- packages/tomcat/changelog.yml
- packages/tomcat/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
- packages/tomcat/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/tomcat/manifest.yml
> tomcat update to ECS 1.11.0

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-6-0.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-dns-4-1-4.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-metadata.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
- packages/suricata/manifest.yml
> suricata update to ECS 1.11.0

- packages/squid/changelog.yml
- packages/squid/data_stream/log/_dev/test/pipeline/test-access1.log-expected.json
- packages/squid/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
- packages/squid/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/squid/manifest.yml
> squid update to ECS 1.11.0

- packages/santa/changelog.yml
- packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
- packages/santa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/santa/manifest.yml
> santa update to ECS 1.11.0

- packages/stan/changelog.yml
- packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
- packages/stan/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/stan/manifest.yml
> stan update to ECS 1.11.0

- packages/sophos/changelog.yml
- packages/sophos/data_stream/utm/_dev/test/pipeline/test-generated.log-expected.json
- packages/sophos/data_stream/utm/elasticsearch/ingest_pipeline/default.yml
- packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log-expected.json
- packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
- packages/sophos/manifest.yml
> sophos update to ECS 1.11.0

- packages/sonicwall/changelog.yml
- packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-general.log-expected.json
- packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-generated.log-expected.json
- packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/sonicwall/manifest.yml
> sonicwall update to ECS 1.11.0

- packages/radware/changelog.yml
- packages/radware/data_stream/defensepro/elasticsearch/ingest_pipeline/default.yml
- packages/radware/manifest.yml
> radware update to ECS 1.11.0

- packages/proofpoint/changelog.yml
- packages/proofpoint/data_stream/emailsecurity/_dev/test/pipeline/test-generated.log-expected.json
- packages/proofpoint/data_stream/emailsecurity/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint/manifest.yml
> proofpoint update to ECS 1.11.0

- packages/osquery/changelog.yml
- packages/osquery/data_stream/result/elasticsearch/ingest_pipeline/default.yml
- packages/osquery/manifest.yml
> osquery update to ECS 1.11.0

- packages/okta/changelog.yml
- packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/manifest.yml
> okta update to ECS 1.11.0

- packages/nginx/changelog.yml
- packages/nginx/data_stream/access/_dev/test/pipeline/test-access.log-expected.json
- packages/nginx/data_stream/access/_dev/test/pipeline/test-nginx.log-expected.json
- packages/nginx/data_stream/access/_dev/test/pipeline/test-test-with-host.log-expected.json
- packages/nginx/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/nginx/data_stream/error/_dev/test/pipeline/test-error-raw.log-expected.json
- packages/nginx/data_stream/error/elasticsearch/ingest_pipeline/default.yml
- packages/nginx/manifest.yml
> nginx update to ECS 1.11.0

- packages/netscout/changelog.yml
- packages/netscout/data_stream/sightline/_dev/test/pipeline/test-generated.log-expected.json
- packages/netscout/data_stream/sightline/elasticsearch/ingest_pipeline/default.yml
- packages/netscout/manifest.yml
> netscout update to ECS 1.11.0

- packages/rabbitmq/changelog.yml
- packages/rabbitmq/data_stream/log/_dev/test/pipeline/test-rabbitmq.log-expected.json
- packages/rabbitmq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/rabbitmq/manifest.yml
> rabbitmq update to ECS 1.11.0

- packages/redis/changelog.yml
- packages/redis/data_stream/log/_dev/test/pipeline/test-redis-5-0-3.log-expected.json
- packages/redis/data_stream/log/_dev/test/pipeline/test-redis-darwin-3-0-2.log-expected.json
- packages/redis/data_stream/log/_dev/test/pipeline/test-redis-windows-2-4-6.log-expected.json
- packages/redis/data_stream/log/_dev/test/pipeline/test-redis.log-expected.json
- packages/redis/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/redis/manifest.yml
> redis update to ECS 1.11.0

- packages/kafka/changelog.yml
- packages/kafka/data_stream/log/_dev/test/pipeline/test-controller-2-0-0.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-controller.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-server-2-0-0.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-server.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-1-1-0.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-2-0-0.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-2-2-2.log-expected.json
- packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change.log-expected.json
- packages/kafka/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/kafka/manifest.yml
> kafka update to ECS 1.11.0

- packages/infoblox/changelog.yml
- packages/infoblox/data_stream/nios/_dev/test/pipeline/test-generated.log-expected.json
- packages/infoblox/data_stream/nios/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox/manifest.yml
> infloblox update to ECS 1.11.0

- packages/imperva/changelog.yml
- packages/imperva/data_stream/securesphere/_dev/test/pipeline/test-generated.log-expected.json
- packages/imperva/data_stream/securesphere/elasticsearch/ingest_pipeline/default.yml
- packages/imperva/manifest.yml
> imperva update to ECS 1.11.0

- packages/iis/changelog.yml
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-72.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-ipv6zone.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-x-forward-for-extended.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/test-x-forward-for.log-expected.json
- packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error-72.log-expected.json
- packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error.log-expected.json
- packages/iis/data_stream/error/_dev/test/pipeline/test-ipv6-zone-id.log-expected.json
- packages/iis/data_stream/error/elasticsearch/ingest_pipeline/default.yml
- packages/iis/manifest.yml
> iis update to ECS 1.11.0

- packages/f5/changelog.yml
- packages/f5/data_stream/bigipafm/_dev/test/pipeline/test-generated.log-expected.json
- packages/f5/data_stream/bigipafm/elasticsearch/ingest_pipeline/default.yml
- packages/f5/data_stream/bigipapm/_dev/test/pipeline/test-generated.log-expected.json
- packages/f5/data_stream/bigipapm/elasticsearch/ingest_pipeline/default.yml
- packages/f5/manifest.yml
> f5 update to ECS 1.11.0

- packages/cylance/changelog.yml
- packages/cylance/data_stream/protect/_dev/test/pipeline/test-generated.log-expected.json
- packages/cylance/data_stream/protect/elasticsearch/ingest_pipeline/default.yml
- packages/cylance/manifest.yml
> cylance update to ECS 1.11.0

- packages/cyberark/changelog.yml
- packages/cyberark/data_stream/corepas/_dev/test/pipeline/test-generated.log-expected.json
- packages/cyberark/data_stream/corepas/elasticsearch/ingest_pipeline/default.yml
- packages/cyberark/manifest.yml
> cyberark update to ECS 1.11.0

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-expected.json
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
> crowdstrike update to ECS 1.11.0

- packages/checkpoint/changelog.yml
- packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
- packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
- packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/checkpoint/manifest.yml
> checkpoint update to ECS 1.11.0

- packages/postgresql/changelog.yml
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-10-default.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-10-min-duration-statement.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-4.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-autovacuum-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-connection-disconnection-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-duration-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-ipv6-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-multi-line-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-parse-bind-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-start-stop-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-tempfile-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-12-default.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-12-min-duration-statement.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-13-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-13-error-code-csv.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-debian-with-slowlog.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-multi-core.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-new-timestamp.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-query-steps-slowlog.log-expected.json
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-ubuntu-9-5.log-expected.json
- packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/postgresql/manifest.yml
> postgresql update to ECS 1.11.0

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
- packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/netflow/manifest.yml
> netflow update to ECS 1.11.0

- packages/bluecoat/changelog.yml
- packages/bluecoat/data_stream/director/_dev/test/pipeline/test-generated.log-expected.json
- packages/bluecoat/data_stream/director/elasticsearch/ingest_pipeline/default.yml
- packages/bluecoat/manifest.yml
> bluecoat update to ECS 1.11.0

- packages/barracuda/changelog.yml
- packages/barracuda/data_stream/spamfirewall/_dev/test/pipeline/test-generated.log-expected.json
- packages/barracuda/data_stream/spamfirewall/elasticsearch/ingest_pipeline/default.yml
- packages/barracuda/data_stream/waf/_dev/test/pipeline/test-generated.log-expected.json
- packages/barracuda/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
- packages/barracuda/manifest.yml
> barracuda update to ECS 1.11.0

- packages/microsoft/changelog.yml
- packages/microsoft/data_stream/defender_atp/_dev/test/pipeline/test-defenderatp.log-expected.json
- packages/microsoft/data_stream/defender_atp/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft/data_stream/dhcp/_dev/test/pipeline/test-generated.log-expected.json
- packages/microsoft/data_stream/dhcp/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft/manifest.yml
> microsoft update to ECS 1.11.0

- packages/haproxy/changelog.yml
- packages/haproxy/data_stream/log/_dev/test/pipeline/test-default.log-expected.json
- packages/haproxy/data_stream/log/_dev/test/pipeline/test-haproxy.log-expected.json
- packages/haproxy/data_stream/log/_dev/test/pipeline/test-httplog-no-headers.log-expected.json
- packages/haproxy/data_stream/log/_dev/test/pipeline/test-tcplog.log-expected.json
- packages/haproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/haproxy/manifest.yml
> haproxy update to ECS 1.11.0

- packages/nats/changelog.yml
- packages/nats/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
- packages/nats/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/nats/manifest.yml
> nats update to ECS 1.11.0

- packages/juniper/changelog.yml
- packages/juniper/data_stream/junos/_dev/test/pipeline/test-generated.log-expected.json
- packages/juniper/data_stream/junos/elasticsearch/ingest_pipeline/default.yml
- packages/juniper/data_stream/netscreen/_dev/test/pipeline/test-generated.log-expected.json
- packages/juniper/data_stream/netscreen/elasticsearch/ingest_pipeline/default.yml
- packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
- packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
- packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
- packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
- packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
- packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
- packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
- packages/juniper/manifest.yml
> juniper update to ECS 1.11.0

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-application.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-calendar.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chat.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chromeos.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-contacts.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-delegatedadmin.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-docs.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-domain.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-groups.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-licenses.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-mobile.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-org.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-security.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-sites.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-user.log-expected.json
- packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/drive/_dev/test/pipeline/test-drive.log-expected.json
- packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/groups/_dev/test/pipeline/test-groups.log-expected.json
- packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/login/_dev/test/pipeline/test-login.log-expected.json
- packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/saml/_dev/test/pipeline/test-saml.log-expected.json
- packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/user_accounts/_dev/test/pipeline/test-user-accounts.log-expected.json
- packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/manifest.yml
> google_workspace update to ECS 1.11.0

- packages/cef/changelog.yml
- packages/cef/data_stream/log/_dev/test/pipeline/test-cef.log-expected.json
- packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.log-expected.json
- packages/cef/data_stream/log/_dev/test/pipeline/test-fp-ngfw-smc.log-expected.json
- packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cef/manifest.yml
> cef update to ECS 1.11.0

- packages/azure/changelog.yml
- packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-edgecases.log-expected.json
- packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
- packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
- packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-kube.log-expected.json
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
- packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-remote-raw.log-expected.json
- packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
- packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
- packages/azure/manifest.yml
> azure update to ECS 1.11.0

- packages/cisco/changelog.yml
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
- packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
- packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
- packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
- packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/data_stream/meraki/_dev/test/pipeline/test-generated.log-expected.json
- packages/cisco/data_stream/meraki/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/data_stream/nexus/elasticsearch/ingest_pipeline/default.yml
- packages/cisco/manifest.yml
> cisco update to ECS 1.11.0

- .ci/Jenkinsfile
This PR orchestrates Jenkins to collect internal fleet-server logs.
> Workaround: collect internal fleet-server logs

- packages/azure/changelog.yml
- packages/azure/data_stream/activitylogs/fields/agent.yml
- packages/azure/data_stream/activitylogs/fields/ecs.yml
- packages/azure/data_stream/auditlogs/fields/agent.yml
- packages/azure/data_stream/auditlogs/fields/ecs.yml
- packages/azure/data_stream/platformlogs/fields/agent.yml
- packages/azure/data_stream/platformlogs/fields/ecs.yml
- packages/azure/data_stream/signinlogs/fields/agent.yml
- packages/azure/data_stream/signinlogs/fields/ecs.yml
- packages/azure/data_stream/springcloudlogs/fields/agent.yml
- packages/azure/data_stream/springcloudlogs/fields/ecs.yml
- packages/azure/docs/README.md
- packages/azure/docs/activitylogs.md
- packages/azure/docs/adlogs.md
- packages/azure/docs/platformlogs.md
- packages/azure/docs/springcloudlogs.md
- packages/azure/manifest.yml
This PR modifies field definitions for Azure integration to use ECS fields
> Azure integration: use ECS fields

- packages/zoom/_dev/build/build.yml
- packages/zoom/changelog.yml
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json-expected.json
- packages/zoom/data_stream/webhook/_dev/test/system/test-webhook-http-config.yml
- packages/zoom/data_stream/webhook/_dev/test/system/test-webhook-https-config.yml
- packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/default.yml
- packages/zoom/data_stream/webhook/fields/ecs.yml
- packages/zoom/data_stream/webhook/manifest.yml
- packages/zoom/docs/README.md
- packages/zoom/manifest.yml
- sets `ecs.version` to 1.11.0
- moves setting ecs.version to pipeline for all data sets
> zoom update to ECS 1.11.0

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container/fields/base-fields.yml
- packages/kubernetes/data_stream/pod/fields/base-fields.yml
- packages/kubernetes/docs/kubelet.md
- packages/kubernetes/manifest.yml
This PR adds missing `daemonset.name` field in pod and container data streams to tune according to elastic/beats#26808.
> Add missing daemonset.name field in pod and container data streams

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/agent.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/base-fields.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_logs/manifest.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/agent.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/base-fields.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/manifest.yml
- packages/elastic_agent/manifest.yml
The datastream for heartbeat logs and metrics were missing in the packages.
> [Elastic Agent] Add support for heartbeat logs, metrics

- packages/nginx_ingress_controller/_dev/build/build.yml
- packages/nginx_ingress_controller/changelog.yml
- packages/nginx_ingress_controller/data_stream/access/fields/agent.yml
- packages/nginx_ingress_controller/data_stream/access/fields/ecs.yml
- packages/nginx_ingress_controller/data_stream/error/fields/agent.yml
- packages/nginx_ingress_controller/data_stream/error/fields/ecs.yml
- packages/nginx_ingress_controller/docs/README.md
- packages/nginx_ingress_controller/manifest.yml
> nginx_ingress_controller generate ecs.yml

- packages/osquery/_dev/build/build.yml
- packages/osquery/changelog.yml
- packages/osquery/data_stream/result/fields/agent.yml
- packages/osquery/data_stream/result/fields/ecs.yml
- packages/osquery/docs/README.md
- packages/osquery/manifest.yml
> osquery generate ecs.yml

- packages/synthetics/changelog.yml
- packages/synthetics/manifest.yml
Fixes elastic/integrations#1534
This PR adjusts synthetics categorization to add web and monitoring.
> [Synthetics] update categorization to include web and monitoring

- packages/system/changelog.yml
- packages/system/kibana/dashboard/system-Windows-Dashboard.json
- packages/system/kibana/visualization/system-a3c3f350-9b6d-11ea-87e4-49f31ec44891.json
- packages/system/kibana/visualization/system-d770b040-9b35-11ea-87e4-49f31ec44891.json
- packages/system/manifest.yml
See: https://github.com/elastic/integrations/issues/1524
This fixes the dashboard IDs in the windows navigation visualizations. 
- Pull down a build
- Navigate to the windows Dashboard. Click through the links in the middle-right, make sure they all work.
- Closes #1524
> Fix windows dashboard links

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/proxy/manifest.yml
- packages/kubernetes/manifest.yml
Replaces the default host for proxy data stream in kubernetes package from `localhost:10249` to `${env.NODE_NAME}:10249`.
The proxy metrics can be fetched from the pod by using the k8s node name and proxy port as it is accessible from inside the pod.
This is a step towards getting rid of `hostNetwork:true` setting in agent deployment configuration.
https://github.com/elastic/beats/issues/25739
> Replace localhost with node_name env var to access k8s proxy

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
- packages/elastic_agent/manifest.yml
In https://github.com/elastic/integrations/pull/1547 I fixed a bug with the default filter on the agent dashboard
the package has been promoted to production before that fix so we need to publish a new version.
> [Fleet] Publish a new version of elastic agent package

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/ecs.yml
- packages/osquery_manager/manifest.yml
Updates host.ip field mapping from keyword to ip data type. Addresses https://discuss.elastic.co/t/osquery-manager-integration-mapping-ip-host-ip-as-keyword/283225
- Closes https://github.com/elastic/security-team/issues/1692
Before the change:
After the change:
> Osquery_manager: Update host.ip field mapping from keyword to ip data type

- packages/aws/data_stream/ec2_metrics/_dev/test/system/test-default-config.yml
This PR enables back system tests for EC2. I suspect that it might be related with machines limit for the AWS account (killed all old machines).
- https://github.com/elastic/integrations/issues/1566
> Enable system tests for AWS EC2

- .ci/Jenkinsfile
This PR modifies Jenkinsfile to skip "latest" directory for dumped logs. Currently it isn't true that it's always the latest stack.
> Skip "latest" directory for dumped logs

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudtrail/fields/ecs.yml
- packages/aws/docs/cloudtrail.md
- packages/aws/manifest.yml
This PR is to add `event.created` field for cloudtrail data stream in the AWS package. 
- Closes https://github.com/elastic/integrations/issues/1584
> Add event.created field for cloudtrail data stream

- packages/cisco/changelog.yml
- packages/cisco/manifest.yml
This simply marks the Cisco package deprecated in title and description, the users should switch to more product specific packages when possible:
https://github.com/elastic/integrations/pull/1582
https://github.com/elastic/integrations/pull/1583
https://github.com/elastic/integrations/pull/1586
https://github.com/elastic/integrations/pull/1587
https://github.com/elastic/integrations/pull/1588
- Relates #343
> [Cisco] Deprecate Cisco package in favor of product specific packages

- packages/aws/changelog.yml
- packages/aws/data_stream/billing/fields/fields.yml
- packages/aws/data_stream/billing/sample_event.json
- packages/aws/docs/billing.md
- packages/aws/manifest.yml
This PR is to fix the `aws.billing.EstimatedCharges` field name.
closes: https://github.com/elastic/integrations/issues/1592
> Fix aws.billing.EstimatedCharges field name

- packages/nginx/changelog.yml
- packages/nginx/data_stream/access/manifest.yml
- packages/nginx/data_stream/error/manifest.yml
- packages/nginx/data_stream/stubstatus/manifest.yml
- packages/nginx/manifest.yml
> Make Nginx GA

- packages/apache/changelog.yml
- packages/apache/data_stream/access/manifest.yml
- packages/apache/data_stream/error/manifest.yml
- packages/apache/data_stream/status/manifest.yml
- packages/apache/manifest.yml
Release Apache integration as GA
> Make Apache integration GA

- packages/nginx_ingress_controller/changelog.yml
- packages/nginx_ingress_controller/data_stream/access/manifest.yml
- packages/nginx_ingress_controller/data_stream/error/manifest.yml
- packages/nginx_ingress_controller/manifest.yml
Make Nginx Ingress Controller GA
> Make Nginx Ingress Controller GA

- packages/docker/changelog.yml
- packages/docker/data_stream/container/manifest.yml
- packages/docker/data_stream/cpu/manifest.yml
- packages/docker/data_stream/diskio/manifest.yml
- packages/docker/data_stream/event/manifest.yml
- packages/docker/data_stream/healthcheck/manifest.yml
- packages/docker/data_stream/image/manifest.yml
- packages/docker/data_stream/info/manifest.yml
- packages/docker/data_stream/memory/manifest.yml
- packages/docker/data_stream/network/manifest.yml
- packages/docker/manifest.yml
Release Docker as GA. No breaking changes were introduced. Minimum stack version required: ^7.14
- Relates https://github.com/elastic/integrations/issues/1438
> Release  Docker as GA

- packages/cisco_umbrella/changelog.yml
- packages/cloudflare/changelog.yml
Fixes the changelog entries for Cisco Umbrella and Cloudflare.  When Cisco Umbrella was merged, I accidently updated the Cloudflare changelog.
- Relates #1646
> Fix Cisco Umbrella & Cloudflare changelog

- packages/gcp/changelog.yml
- packages/gcp/manifest.yml
Move GCP integration to GA from experimental. This will be used in the upcoming Dataflow integration project.
-
> [Enhancement] Move GCP integration from experimental to GA

- packages/checkpoint/changelog.yml
- packages/checkpoint/data_stream/firewall/manifest.yml
- packages/checkpoint/manifest.yml
> GA checkpoint integration

- packages/cyberarkpas/changelog.yml
- packages/cyberarkpas/data_stream/audit/manifest.yml
- packages/cyberarkpas/manifest.yml
GA cyperarkpas integration
- version 2.0.0
- remove release from audit data_stream manifest
- kibana version to 7.16.0
> GA cyperarkpas integration

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/o365/manifest.yml
- Adds type assertion of Map when containsKey() is used
- Adds type assertion of List when accessing as array
`elastic-package test`
> 0365 Add type assertions to painless scripts

- packages/cef/changelog.yml
- packages/cef/data_stream/log/manifest.yml
- packages/cef/manifest.yml
GA CEF integration
- version number to 1.0.0
- release tag to ga
> GA CEF integration

- packages/winlog/_dev/build/build.yml
- packages/winlog/_dev/deploy/docker/docker-compose.yml
- packages/winlog/_dev/deploy/docker/http-mock-config.yml
- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/_dev/test/system/test-splunk-config.yml
- packages/winlog/data_stream/winlog/fields/beats.yml
- packages/winlog/data_stream/winlog/fields/ecs.yml
- packages/winlog/data_stream/winlog/fields/winlog.yml
- packages/winlog/data_stream/winlog/manifest.yml
- packages/winlog/docs/README.md
- packages/winlog/manifest.yml
GA winlog integration
- ecs external definitions
- add missing field definitions
- sync winlog.yml with system/security integration
- add system test for httpjson input
- change default datastream.dataset to winlog.winlog
``` bash
```
> GA winlog integration

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/manifest.yml
- packages/google_workspace/data_stream/drive/manifest.yml
- packages/google_workspace/data_stream/groups/manifest.yml
- packages/google_workspace/data_stream/login/manifest.yml
- packages/google_workspace/data_stream/saml/manifest.yml
- packages/google_workspace/data_stream/user_accounts/manifest.yml
- packages/google_workspace/manifest.yml
ga google_workspace integration
- remove release from data_stream manifests
> [google_workspace] ga google_workspace integration

- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/manifest.yml
ga hashicorp vault integration
- release to GA
> ga hashicorp vault integration

- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/manifest.yml
- packages/gcp/data_stream/firewall/manifest.yml
- packages/gcp/data_stream/vpcflow/manifest.yml
- packages/gcp/manifest.yml
GA gcp integrations
- remove release from data_stream manifests
> GA gcp integrations

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/manifest.yml
Update integration manifest to allow free-form osquery configuration, limit to one integration.
Example of the new configuration payload, specifically the ```streams``` array is empty and the osquery configuration is under ```config``` ```osquery``` ```value``` property on updating the configuration:
```
{
"name": "osquery_manager-1",
"description": "",
"policy_id": "dc5c1ad0-0b47-11ec-9743-91c25b5c7a9b",
"namespace": "default",
"inputs": [
{
"type": "osquery",
"enabled": true,
"streams": [],
"policy_template": "osquery_manager",
"config": {
"osquery": {
"value": {
"schedule": {
"macos_uptime": {
"query": "SELECT * FROM uptime",
"interval": 60
}
},
"options": {
"disable_tables": "users"
},
"packs": {
"internal_stuff": {
"queries": {
"users": {
"query": "SELECT * FROM users limit 5", …
```
> Osquery_manager: Update integration manifest to allow free-form osquery configuration, limit to one integration

- .ci/Jenkinsfile
This PR checks if it's fine to temporarily switch to Ubuntu 18 workerNode for Kubernetes integration, as in Ubuntu 20 there are issues with `kind`.
> Workaround: use Ubuntu 18 as worker node for Kubernetes

- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/manifest.yml
- packages/winlog/manifest.yml
The event ID value in the conditions should be a string.
> [winlog] Fix example processors config

- packages/network_traffic/_dev/build/docs/README.md
- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
- packages/network_traffic/data_stream/flow/manifest.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
Set the title of the integration to "Network Packet Capture".
Also add config options for `timeout` and `period` to the `flow` data stream.
> [network_traffic] Set title to Network Packet Capture

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/manifest.yml
- packages/crowdstrike/manifest.yml
GA crowdstrike integration
- remove release from falcon data_stream manifest
- kibana version to 7.16.0
> GA crowdstrike integration

- packages/cloudflare/changelog.yml
- packages/cloudflare/data_stream/logpull/manifest.yml
- packages/cloudflare/manifest.yml
GA Cloudflare integration
- version number to 1.0.0
- release tag to ga
> GA Cloudflare integration

- packages/aws/data_stream/ec2_metrics/_dev/test/system/test-default-config.yml
Skip flaky tests: https://github.com/elastic/integrations/issues/1761
> Flaky: skip system tests for EC2

- .ci/Jenkinsfile
This reverts commit aba53e6b70147d7c505d2c58bb9e43757e7b19a7 (https://github.com/elastic/integrations/pull/1754)
> Revert "Workaround: use Ubuntu 18 as worker node for Kubernetes (#1754)"

- packages/osquery/changelog.yml
- packages/osquery/data_stream/result/manifest.yml
- packages/osquery/manifest.yml
Updates the osquery package to GA:
- Updates version to 1.0.0.
- Marked as GA.
https://github.com/elastic/integrations/issues/1562
> osquery: GA package as version 1.0.0

- packages/zerofox/_dev/deploy/docker/docker-compose.yml
- packages/zerofox/_dev/deploy/docker/files/config.yml
- packages/zerofox/changelog.yml
- packages/zerofox/data_stream/alerts/_dev/test/system/test-default-config.yml
- packages/zerofox/data_stream/alerts/fields/beats.yml
- packages/zerofox/data_stream/alerts/manifest.yml
- packages/zerofox/docs/README.md
- packages/zerofox/manifest.yml
Updates the zerofox package to GA:
- Adds system tests.
- Fixes missing input.type field.
- Updates version to 1.0.0.
- Marked as GA.
https://github.com/elastic/integrations/issues/1562
> Zerofox: Release version 1.0.0 as GA

- packages/sophos/changelog.yml
- packages/sophos/data_stream/xg/fields/fields.yml
- packages/sophos/data_stream/xg/manifest.yml
- packages/sophos/manifest.yml
ga sophos xg
- remove release from xg data_stream
- utm is still experimental
``` bash
```
> ga sophos xg

- packages/juniper/changelog.yml
- packages/juniper/data_stream/srx/fields/fields.yml
- packages/juniper/data_stream/srx/manifest.yml
- packages/juniper/manifest.yml
ga juniper integration
- remove release from srx data_stream
- release experimental for junos & netscreen data_streams
- version 1.0.0
``` bash
```
> ga juniper integration

- packages/santa/changelog.yml
- packages/santa/data_stream/log/manifest.yml
- packages/santa/manifest.yml
ga santa integration
- remove release from data_stream
> [santa] ga santa integration

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
Prevents pipeline script error in windows integration
- prevent creating new HashMap with null
- improve error.message
``` bash
elastic-package test pipeline
```
- Relates #1789
> [windows] prevent pipeline script error

- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/changelog.yml
- packages/kubernetes/docs/README.md
- packages/kubernetes/manifest.yml
This PR resolves https://github.com/elastic/integrations/issues/1780.
In [Kubernetes integration Readme](https://github.com/elastic/integrations/blob/master/packages/kubernetes/_dev/build/docs/README.md) which is the text that appears in the k8s integration Fleet UI, an example manifest is mentioned pointing to a non-existing doc.
These lines are deprecated and are removed completely.
- Closes https://github.com/elastic/integrations/issues/1780
> Remove deprecated lines from kubernetes package readme

- .ci/schedule-daily.groovy
Current daily job doesn't wait for the finalization of the invoked job, so it is always green.
Propagate the result of the invoked job.
> Make daily job fail if the invoked job fails

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/synthetics.yml
- packages/synthetics/data_stream/browser_network/fields/synthetics.yml
- packages/synthetics/data_stream/browser_screenshot/fields/synthetics.yml
- packages/synthetics/manifest.yml
Fixes #1925
Relates to elastic/beats#28409
Type of change
- Enhancement
Updates the `browser`, `browser.network`, and `browser.screenshot` mappings to include keyword mapping, keeping in step with heartbeat.
> [Synthetics] update mappings

- packages/ti_abusech/changelog.yml
- packages/ti_abusech/manifest.yml
Bumping min version, it was supposed to be done with https://github.com/elastic/integrations/pull/2063 but seems to have not been included.
> [AbuseCH] Bump min version

- packages/apache/changelog.yml
- packages/apache/manifest.yml
> apache: changes for unified integration UI

- docs/developer_workflow_design_build_test_integration.md
Document that `elastic-package create package` and `elastic-package create data-stream`
can be used to bootstrap new packages and data streams respectively.
> Add 'elastic-package create' to developer workflow docs

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/proxy/_dev/test/system/test-default-config.yml
- packages/kubernetes/data_stream/proxy/manifest.yml
- packages/kubernetes/manifest.yml
This PR sets the default host for `proxy` data_stream of `kubernetes` integration to `localhost` instead of `env.NODE_NAME` in order to resolve https://github.com/elastic/integrations/issues/2029
-
> Set kube proxy default hosts to localhost

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
- packages/o365/data_stream/audit/manifest.yml
- packages/o365/manifest.yml
- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell_operational/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
- packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
- packages/windows/manifest.yml
Fixes the _processors_ configuration option for `windows` and `o365` packages.
Before this change, trying to add custom processors to any of their data streams resulted in the following error:
- ~~[ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).~~
> Fix processors configuration in windows and o365 packages

- packages/kibana/changelog.yml
- packages/kibana/data_stream/stats/manifest.yml
- packages/kibana/manifest.yml
This PR changes the tag of Kibana to experimental again
> Revert Kibana to experimental

- .ci/schedule-daily.groovy
* Adds a daily stage to run integration tests with 8.0 snapshots.
* 7.x branches don't exist anymore, use 7.16 snapshots instead for this major.
-
> Run daily jobs with 7.16 and 8.0 snapshots

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/ecs.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/docs/README.md
- packages/osquery_manager/manifest.yml
* Update manifest release tag from beta to ga
* Add host_users, host_groups, host_processes tables columns into package readme
* Remove previously explicitly mapped text/keywords fields. This relies on the dynamic keyword[1024] mapping
```
"dynamic_templates": [
{
"strings_as_keyword": {
"match_mapping_type": "string",
"mapping": {
"ignore_above": 1024,
"type": "keyword"
}
}
}
]
```
and helps to:
** Reduce the size of the mapping
** Eliminate the kibana warning 
```
kibana         | [2021-11-03T19:02:37.819+00:00][WARN ][plugins.fleet] large amount of default fields detected for index template logs-osquery_manager.result in package osquery_manager, applying the first 1024 fields
```
> Osquery_manager: Update to GA. Reduce the number of explicitly mapped text/keyword osquery fields.

- packages/cassandra/changelog.yml
- packages/cassandra/data_stream/log/manifest.yml
- packages/cassandra/data_stream/metrics/manifest.yml
- packages/cassandra/manifest.yml
> Make Cassandra GA

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/manifest.yml
Make it compatible with 7.16 and 8.x
> [elastic_agent] Update compatiblity to be compatible with 8.0.x

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/visualization/kubernetes-174a6ad0-30e0-11e7-8df8-6d3604a72912.json
- packages/kubernetes/kibana/visualization/kubernetes-da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3.json
- packages/kubernetes/kibana/visualization/kubernetes-e1018b90-2bfb-11e7-859b-f78b612cde28.json
- packages/kubernetes/manifest.yml
There are two visualizations on the `[Metrics Kubernetes] Overview dashboard` with 2 broken visualizations (`Desired Pods` and `Unavailable Pods`), reason for that: index pattern is overridden (they have "yes" checked),  but `series_Index_pattern`  is not specified:
(note that in the picture as an index_pattern was picked `logs-*`)
index pattern shouldn't be overridden.
- Closes https://github.com/elastic/beats/issues/28792
Add here screenshots presenting:
- Kibana UI forms presenting configuration options exposed by the integration:
local setup:
> Fix visualizations on the Kubernetes overview dashboard

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/fields/fields.yml
- packages/windows/data_stream/forwarded/manifest.yml
- packages/windows/data_stream/powershell/fields/fields.yml
- packages/windows/data_stream/powershell/manifest.yml
- packages/windows/data_stream/powershell_operational/fields/fields.yml
- packages/windows/data_stream/powershell_operational/manifest.yml
- packages/windows/manifest.yml
The change replaces the simple tokenizer with a custom tokenizer that splits on word boundaries that do not include hyphen.
- Fixes #1776.
> packages/windows/data_stream/powershell_operations: don't split tokens on hyphen

- packages/zeek/changelog.yml
PR https://github.com/elastic/integrations/pull/2110 introduced an unexpected and unwanted change to Zeek package changelog.
This commit reverts that change.
- Related  https://github.com/elastic/integrations/pull/2110
> zeek: fix changelog link

- packages/apache/changelog.yml
- packages/apache/manifest.yml
Release a version of the Apache package compatible with the 8 version of the stack.
- https://github.com/elastic/elastic-package/pull/571
> Release Apache for Kibana 8

- packages/stan/changelog.yml
- packages/stan/manifest.yml
> Release stan for v8.0.0

- packages/windows/changelog.yml
- packages/windows/manifest.yml
Release Windows for Kibana 8
The breaking changes should not affect current configuration 
- https://github.com/elastic/elastic-package/pull/571
> Release Windows for Kibana 8

- packages/iis/changelog.yml
- packages/iis/manifest.yml
Release IIS for Kibana 8
No breaking changes for 8.0
- https://github.com/elastic/elastic-package/pull/571
> Release IIS for Kibana 8

- packages/apache/changelog.yml
- packages/apache/kibana/ml_module/apache-Logs-ml.json
- packages/apache/manifest.yml
The query defined in the json configuration files of anomaly detection modules are run to determine if the module is match for data in the selected index. These queries run over the full time range of the index so can potentially take a long time to return, particularly if searching over documents which are not in the hot or warm data tiers. This PR adds an extra condition to the query to ignore data from the cold and frozen tiers.
https://github.com/elastic/kibana/issues/116696
> [ML] Fix Apache ML module manifest query to ignore frozen and cold tiers

- packages/nginx/changelog.yml
- packages/nginx/kibana/ml_module/nginx-Logs-ml.json
- packages/nginx/manifest.yml
The query defined in the json configuration files of anomaly detection modules are run to determine if the module is match for data in the selected index. These queries run over the full time range of the index so can potentially take a long time to return, particularly if searching over documents which are not in the hot or warm data tiers. This PR adds an extra condition to the query to ignore data from the cold and frozen tiers.
https://github.com/elastic/kibana/issues/116696
> [ML] Fix Nginx ML module manifest query to ignore frozen and cold tiers

- .github/PULL_REQUEST_TEMPLATE.md
Current checkbox seems to recommend release of new features only for
current or next versions of the stack, what seems to indicate the
preference of in-band releases, when current preference is out-of-band
releases.
Relax the recommendation in the checkbox, with a reference to existing
guidelines.
> Update checkbox in template for version constraint guidelines

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/manifest.yml
This PR adds the fields necessary for Heartbeat to throttle synthetic monitors. These fields are used by the UI in https://github.com/elastic/kibana/pull/118594.
For that, it builds upon the throttling options added in https://github.com/elastic/beats/issues/27952.
Please notice that after recent changes we now merge the download, upload, and latency fields into one, so that we can avoid too much conditional formatting on handlebars. That formatting is now done on the Kibana side instead.
**There are complete testing instructions in the Kibana PR https://github.com/elastic/kibana/pull/118594. Please follow those instructions using this build of the Synthetics integration.**
This PR is related to https://github.com/elastic/kibana/issues/114155.
> [Uptime] Add fields for browser throttling

- packages/kafka/changelog.yml
- packages/kafka/manifest.yml
This PR is to release the kafka package for Kibana 8.0.0.
> Release kafka package for kibana 8

- packages/rabbitmq/changelog.yml
- packages/rabbitmq/manifest.yml
This PR is to release the `rabbitmq` package for Kibana 8.0.0.
> Release rabbitmq package for Kibana 8

- packages/vsphere/changelog.yml
- packages/vsphere/manifest.yml
This PR is to release the `vsphere` package for Kibana 8.0.0.
> Release vsphere package for kibana 8

- packages/aws/_dev/build/docs/cloudtrail.md
- packages/aws/_dev/build/docs/cloudwatch.md
- packages/aws/_dev/build/docs/ec2.md
- packages/aws/_dev/build/docs/elb.md
- packages/aws/_dev/build/docs/s3.md
- packages/aws/_dev/build/docs/vpcflow.md
- packages/aws/changelog.yml
- packages/aws/data_stream/cloudtrail/sample_event.json
- packages/aws/data_stream/cloudwatch_logs/sample_event.json
- packages/aws/data_stream/ec2_logs/sample_event.json
- packages/aws/data_stream/elb_logs/sample_event.json
- packages/aws/data_stream/s3access/sample_event.json
- packages/aws/data_stream/vpcflow/sample_event.json
- packages/aws/data_stream/waf/sample_event.json
- packages/aws/docs/cloudtrail.md
- packages/aws/docs/cloudwatch.md
- packages/aws/docs/ec2.md
- packages/aws/docs/elb.md
- packages/aws/docs/s3.md
- packages/aws/docs/vpcflow.md
- packages/aws/docs/waf.md
- packages/aws/manifest.yml
Enhancement
Add missing sample events for AWS integration
-
> Add missing sample events

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudtrail/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/cloudtrail/manifest.yml
- packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/cloudwatch_logs/manifest.yml
- packages/aws/data_stream/ec2_logs/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/ec2_logs/manifest.yml
- packages/aws/data_stream/elb_logs/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/elb_logs/manifest.yml
- packages/aws/data_stream/s3access/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/s3access/manifest.yml
- packages/aws/data_stream/vpcflow/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/vpcflow/manifest.yml
- packages/aws/data_stream/waf/agent/stream/aws-s3.yml.hbs
- packages/aws/data_stream/waf/manifest.yml
- packages/aws/manifest.yml
Give users the ability to set max_number_of_messages for the aws-s3 input.
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-s3.html#_max_number_of_messages
- Closes #2298
> [aws] Add max_number_of_messages to AWS integration config

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/manifest.yml
Add 8.0.0 constraint to osquery_manager.
Fixes: https://github.com/elastic/security-team/issues/2439
- Closes https://github.com/elastic/security-team/issues/2439
> [osquery_manager] Add 8.0.0 constraint

- packages/ti_anomali/changelog.yml
- packages/ti_anomali/data_stream/limo/_dev/test/pipeline/test-anomali-limo-ndjson.log-expected.json
- packages/ti_anomali/data_stream/limo/fields/base-fields.yml
- packages/ti_anomali/data_stream/limo/sample_event.json
- packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json-expected.json
- packages/ti_anomali/data_stream/threatstream/fields/base-fields.yml
- packages/ti_anomali/data_stream/threatstream/sample_event.json
- packages/ti_anomali/docs/README.md
- packages/ti_anomali/manifest.yml
Fixing some minor typos when setting TI related ECS fields.
> [Anomali] Fixing typos in base-fields.yml

- .ci/Jenkinsfile
Resolves: https://github.com/elastic/integrations/issues/2144
This PR modifies the Jenkinsfile to fix daily jobs for stack 7.x. Tests have been failing since a long time now.
> Fix: don't include 8.x packages in stack 7.x jobs

- packages/httpjson/_dev/build/build.yml
- packages/httpjson/_dev/build/docs/README.md
- packages/httpjson/_dev/deploy/docker/docker-compose.yml
- packages/httpjson/_dev/deploy/docker/files/config.yml
- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/_dev/test/system/test-basicauth-config.yml
- packages/httpjson/data_stream/generic/_dev/test/system/test-oauth-config.yml
- packages/httpjson/data_stream/generic/_dev/test/system/test-pagination-config.yml
- packages/httpjson/data_stream/generic/_dev/test/system/test-transforms-config.yml
- packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
- packages/httpjson/data_stream/generic/fields/base-fields.yml
- packages/httpjson/data_stream/generic/fields/beats.yml
- packages/httpjson/data_stream/generic/fields/ecs.yml
- packages/httpjson/data_stream/generic/manifest.yml
- packages/httpjson/data_stream/generic/sample_event.json
- packages/httpjson/docs/README.md
- packages/httpjson/manifest.yml
This PR adds a package to utilize the httpjson input with custom integration, similar to winlog and log packages.
> [New Package] httpjson custom input

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/event/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/event/manifest.yml
- packages/kubernetes/manifest.yml
This PR adds `skip_older` setting introduced at https://github.com/elastic/beats/pull/29396.
> Add skip_older setting for event data_stream

- .ci/schedule-daily.groovy
This PR adjusts execution timeout for the daily job.
If we need 2h to finish single job, a we want 2 jobs, then we need to increase the total timeout :)
> CI: Increase execution timeout for daily job

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/audit/agent/stream/winlog.yml.hbs
- packages/microsoft_sqlserver/data_stream/audit/manifest.yml
- packages/microsoft_sqlserver/manifest.yml
- packages/system/changelog.yml
- packages/system/data_stream/application/agent/stream/winlog.yml.hbs
- packages/system/data_stream/application/manifest.yml
- packages/system/data_stream/security/agent/stream/winlog.yml.hbs
- packages/system/data_stream/security/manifest.yml
- packages/system/data_stream/system/agent/stream/winlog.yml.hbs
- packages/system/data_stream/system/manifest.yml
- packages/system/manifest.yml
- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/forwarded/manifest.yml
- packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell/manifest.yml
- packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell_operational/manifest.yml
- packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/sysmon_operational/manifest.yml
- packages/windows/manifest.yml
- packages/winlog/changelog.yml
- packages/winlog/data_stream/winlog/agent/stream/winlog.yml.hbs
- packages/winlog/data_stream/winlog/manifest.yml
- packages/winlog/manifest.yml
- Exposes the new `language` option for all integrations using the `winlog` input.
- Exposes `event_id` for all integrations that didn't let the user customize this option.
> Expose event_id, and language options to all winlog inputs

- packages/auditd/_dev/build/build.yml
- packages/cisco/_dev/build/build.yml
- packages/cisco_meraki/_dev/build/build.yml
- packages/cisco_nexus/_dev/build/build.yml
- packages/fortinet/_dev/build/build.yml
- packages/juniper/_dev/build/build.yml
- packages/juniper_junos/_dev/build/build.yml
- packages/juniper_netscreen/_dev/build/build.yml
- packages/juniper_srx/_dev/build/build.yml
- packages/linux/_dev/build/build.yml
- packages/microsoft/_dev/build/build.yml
- packages/netflow/_dev/build/build.yml
- packages/santa/_dev/build/build.yml
- packages/sonicwall/_dev/build/build.yml
- packages/sophos/_dev/build/build.yml
- packages/system/_dev/build/build.yml
- packages/tomcat/_dev/build/build.yml
This PR introduces a workaround for the [ECS issue](https://github.com/elastic/ecs/issues/1701), it impacted the master branch, caused trouble with successful builds.
As the ECS 1.12 was altered with a deprecation notice,  it was detected as a non-versioned change in README:
```diff
diff --git a/packages/auditd/docs/README.md b/packages/auditd/docs/README.md
index fc85d483c..a70e0cff8 100644
--- a/packages/auditd/docs/README.md
+++ b/packages/auditd/docs/README.md
@@ -229,7 +229,7 @@ An example event for `log` looks as following:
| process.exit_code | The exit code of the process, if this is a termination event. The field should be absent if there is no exit code for the event (e.g. process start). | long |
| process.name | Process name. Sometimes called program name or similar. | keyword …
```
> Workaround: skip ppid deprecation notice

- packages/auditd/_dev/build/build.yml
- packages/cisco/_dev/build/build.yml
- packages/cisco_meraki/_dev/build/build.yml
- packages/cisco_nexus/_dev/build/build.yml
- packages/fortinet/_dev/build/build.yml
- packages/juniper/_dev/build/build.yml
- packages/juniper_junos/_dev/build/build.yml
- packages/juniper_netscreen/_dev/build/build.yml
- packages/juniper_srx/_dev/build/build.yml
- packages/linux/_dev/build/build.yml
- packages/microsoft/_dev/build/build.yml
- packages/netflow/_dev/build/build.yml
- packages/santa/_dev/build/build.yml
- packages/sonicwall/_dev/build/build.yml
- packages/sophos/_dev/build/build.yml
- packages/system/_dev/build/build.yml
- packages/tomcat/_dev/build/build.yml
This PR reverts the workaround for ECS related changes (deprecation notice).
Related: https://github.com/elastic/integrations/pull/2364
> Revert "Workaround for ppid deprecation notice (#2364)"

- .ci/Jenkinsfile
This PR upgrades k8s version for the CI to a latest one (v1.23.0)
> Upgrade k8s version to v1.23.0

- packages/microsoft_dhcp/changelog.yml
- packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
- packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_dhcp/manifest.yml
This PR adds more MS DHCP action types and uses those codes to determine failure outcomes.
https://github.com/elastic/beats/issues/29221
> [microsoft_dhcp] Add more event.action and event.outcome values

- packages/cisco_umbrella/_dev/build/docs/README.md
- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log-config.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-config.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log-config.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log-config.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
- packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_umbrella/data_stream/log/fields/ecs.yml
- packages/cisco_umbrella/data_stream/log/fields/fields.yml
- packages/cisco_umbrella/data_stream/log/manifest.yml
- packages/cisco_umbrella/docs/README.md
- packages/cisco_umbrella/manifest.yml
Adds support for Non SQS type S3 buckets, including Cisco Managed S3 buckets.
Updates pipeline to support the newest proxy logs.
> [Cisco Umbrella] adding support for Cisco Managed S3 buckets and non SQS

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_job/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_job/manifest.yml
- packages/kubernetes/manifest.yml
align elastic-agent-standalone manifest and k8s package: https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L93-L101
- relates https://github.com/elastic/beats/issues/29565
> Add missing leaderelection condition to state_job data stream

- packages/cisco_ios/_dev/deploy/docker/sample_logs/cisco-ios.log
- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-config.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
- packages/cisco_ios/data_stream/log/agent/stream/stream.yml.hbs
- packages/cisco_ios/data_stream/log/agent/stream/udp.yml.hbs
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/data_stream/log/fields/ecs.yml
- packages/cisco_ios/data_stream/log/fields/fields.yml
- packages/cisco_ios/data_stream/log/manifest.yml
- packages/cisco_ios/docs/README.md
- packages/cisco_ios/manifest.yml
Improve Cisco IOS handling for syslog data. Previously the `@timestamp` value was not being set from the timestamp in log.
I tested with various time configurations. My preferred format is `service timestamps log datetime msec year show-timezone`.
Fixes #2474
- Closes  #2474
> [cisco_ios] Add syslog header and timestamp parsing

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/container/manifest.yml
- packages/kubernetes/data_stream/pod/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/pod/manifest.yml
- packages/kubernetes/data_stream/state_container/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_container/manifest.yml
- packages/kubernetes/data_stream/state_pod/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_pod/manifest.yml
- packages/kubernetes/manifest.yml
Add possibility to configure `add_recourse_metadata` for pod and container resources.
- Closes https://github.com/elastic/integrations/issues/2362
> Expose add_resource_metadata for container and pods resources

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/manifest.yml
The removal of explicit known osquery text/keyword mapping in the
https://github.com/elastic/integrations/pull/2123
cause the issue with incorrect mapping of some dynamic fields and breakage of osquery results storage.
Repro case:
1. Start 7.16.2 stack with osquery enabled
2. Execute live query ```select * from interface_details```, observe results
3. Execute live query ```select * from users```, observe results are not shown.
In osquerybeat log there are errors such as:
```
{"type":"mapper_parsing_exception","reason":"failed to parse field [osquery.type] of type [long] in document with id 'RLgaUH4BGTlwkgjnS5A2'. Preview of field's value: 'local'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"local\""}}, dropping event!
```
The reason for the error is the …
> Osquery_manager: Add back the explicit mapping for the known osquery text/keyword fields text/keyword fields

- packages/system/changelog.yml
- Fix incorrect PR number in changelog for 1.8.0.
- ~~[ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~~
- ~~[ ] I have added an entry to my package's `changelog.yml` file.~~
- ~~[ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~
> [system] Fix incorrect PR number in changelog

- packages/aws/_dev/build/docs/vpcflow.md
- packages/aws/changelog.yml
- packages/aws/docs/vpcflow.md
- packages/aws/manifest.yml
Adds descriptions of the supported vpcflow formats to the vpcflow readme
> [AWS/vpcflow] add description of supported vpcflow formats

- packages/ti_threatq/changelog.yml
- packages/ti_threatq/data_stream/threat/fields/base-fields.yml
- packages/ti_threatq/data_stream/threat/sample_event.json
- packages/ti_threatq/docs/README.md
- packages/ti_threatq/kibana/dashboard/ti_threatq-a05fd810-78f1-11ec-a97c-7db1518ab848.json
- packages/ti_threatq/kibana/dashboard/ti_threatq-ab289de0-78f1-11ec-a97c-7db1518ab848.json
- packages/ti_threatq/kibana/dashboard/ti_threatq-b45b0c40-78f1-11ec-a97c-7db1518ab848.json
- packages/ti_threatq/kibana/tag/ti_threatq-c0cca010-78f1-11ec-a97c-7db1518ab848.json
- packages/ti_threatq/manifest.yml
Adds threat.feed fields and dashboards to the ThreatQ integration
> [ThreatQ] Adding threat.feed ECS fields and dashboards

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
-Added a check to the forwarded/security conditional to ensure that only events with a provider of `Microsoft-Windows-Eventlog` or `Microsoft-Windows-Security-Auditing` are allowed through. Events not matching these providers will still be indexed, but won't receive additional enrichment that could lead to incorrect metadata being applied.
```
cd packages/windows && elastic-package test
```
- Relates elastic/beats#27288
> [windows] Add provider name check to forwarded/security conditional

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/ecs.yml
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/data_stream/browser_network/fields/ecs.yml
- packages/synthetics/data_stream/browser_network/fields/http.yml
- packages/synthetics/data_stream/browser_network/manifest.yml
- packages/synthetics/data_stream/browser_screenshot/manifest.yml
- packages/synthetics/data_stream/http/fields/ecs.yml
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/fields/ecs.yml
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/fields/ecs.yml
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
Adds index optimization settings to all Synthetics data streams
The following settings have been added Synthetics data streams:
* http
* icmp
* TCP
* browser
```
elasticsearch:
index_template:
mappings:
dynamic: false
settings:
index:
codec: best_compression
sort.field: 
- "url.full.keyword"
- "monitor.id"
```
* browser.screenshot
```
elasticsearch:
index_template:
mappings:
dynamic: false
settings:
index:
codec: best_compression
sort.field: 
- "monitor.id"
```
browser.network
```
elasticsearch:
index_template:
mappings:
dynamic: false
settings:
index:
codec: best_compression
sort.field: 
- "url.full.keyword"
- "http.request.url"
- "http.response.headers.etag"
- "monitor.id"
```
1. Navigate to `packages/synthetics`
2. Run `elastic-package stack clean`, then `elastic-package stack build` …
> [Synthetics] add index optimizations

- packages/windows/changelog.yml
- packages/windows/manifest.yml
This PR fixes the issue introduced in https://github.com/elastic/integrations/pull/2515 due to the not bumped package version.
> Fix windows: missing version bump

- .ci/Jenkinsfile
- .ci/jobs/integrations-daily.yml
- .ci/schedule-daily.groovy
- .github/ISSUE_TEMPLATE/integration-checklist.md
- .github/PULL_REQUEST_TEMPLATE.md
- .mergify.yml
- README.md
- docs/definitions.md
- docs/developer_workflow_design_build_test_integration.md
- docs/developer_workflow_fleet_ui.md
- docs/fine_tune_integration.md
- docs/import_from_beats.md
- docs/testing_and_validation.md
> Neutral naming for integrations

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_container/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_container/manifest.yml
- packages/kubernetes/data_stream/state_cronjob/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_cronjob/manifest.yml
- packages/kubernetes/data_stream/state_daemonset/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_daemonset/manifest.yml
- packages/kubernetes/data_stream/state_deployment/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_deployment/manifest.yml
- packages/kubernetes/data_stream/state_job/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_job/manifest.yml
- packages/kubernetes/data_stream/state_node/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_node/manifest.yml
- packages/kubernetes/data_stream/state_persistentvolume/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
- packages/kubernetes/data_stream/state_persistentvolumeclaim/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
- packages/kubernetes/data_stream/state_pod/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_pod/manifest.yml
- packages/kubernetes/data_stream/state_replicaset/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_replicaset/manifest.yml
- packages/kubernetes/data_stream/state_resourcequota/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_resourcequota/manifest.yml
- packages/kubernetes/data_stream/state_service/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_service/manifest.yml
- packages/kubernetes/data_stream/state_statefulset/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_statefulset/manifest.yml
- packages/kubernetes/data_stream/state_storageclass/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/state_storageclass/manifest.yml
- packages/kubernetes/manifest.yml
This PR adds `node` and `namespace` settings for state_* datastreams of k8s package. These settings are used for enriching the metrics with metadata retrieved from the API server.
Closes https://github.com/elastic/integrations/issues/2556
> Tune k8s package settings

- .ci/schedule-daily.groovy
This PR modifies `schedule-daily.groovy` to run daily system tests against 8.1-SNAPSHOT.
Motivation:
The `containerd` integration requires [8.1 stack](https://github.com/elastic/integrations/blob/main/packages/containerd/manifest.yml#L12) to be present and it isn't ignored by 8.0 stacks, failing the system test with 404 error. We can refactor [the logic](https://github.com/elastic/integrations/blob/main/.ci/Jenkinsfile#L149) to skip packages targeting 8.1 or we can use a newer snapshot.
I'm not in favor of adding an extra column to the testing matrix (now: 7.16 and 8.0), as this job is sequential and developers do not pay much attention to its status.
Let me know what you think.
> Schedule daily: test packages against 8.1

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/tls/fields/protocol.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
This brings the mapping for server_certificate_chain into agreement with the packetbeat [code](https://github.com/elastic/beats/blob/master/packetbeat/protos/tls/tls.go#L305-L310) and [mapping](https://github.com/elastic/beats/blob/master/packetbeat/protos/tls/_meta/fields.yml#L193-L195), fixing #2499.
`elastic-package test system --data-streams tls` in the network_traffic package.
- Closes #2499
N/A
> package/network_traffic/tls: fix mapping for tls.detailed.server_certificate_chain

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/pod/fields/base-fields.yml
- packages/kubernetes/data_stream/state_pod/fields/base-fields.yml
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/docs/kubelet.md
- packages/kubernetes/manifest.yml
Document fields added in https://github.com/elastic/beats/pull/28954 and https://github.com/elastic/beats/pull/29572 to fix https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/67/tests
> Add missing job.name and cronjob.name meta fields

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container/fields/base-fields.yml
- packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
- packages/kubernetes/docs/kubelet.md
- packages/kubernetes/manifest.yml
Follow-up of [https://github.com/elastic/integrations/pull/2608](https://github.com/elastic/integrations/pull/2608) to fix [https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/72/tests](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/72/tests).
> Add missing job and cronjob fields in container related metricsets

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/common.yml
- packages/synthetics/data_stream/browser_network/fields/common.yml
- packages/synthetics/data_stream/browser_screenshot/fields/common.yml
- packages/synthetics/data_stream/http/fields/common.yml
- packages/synthetics/data_stream/icmp/fields/common.yml
- packages/synthetics/data_stream/tcp/fields/common.yml
- packages/synthetics/manifest.yml
Relates to: https://github.com/elastic/uptime/issues/443
Adds run_once mappings to Synthetics
> Synthetics - add run_once fields

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/data_stream/query/manifest.yml
- packages/prometheus/data_stream/remote_write/manifest.yml
- packages/prometheus/manifest.yml
Disable `query` and `remote_write` datastreams from defaults. Leaving only `collector` datastream enabled by default.
> Improve Prometheus default datastream enablement

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_container/fields/base-fields.yml
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
This PR adds `job.name` and `cronjob.name` fields in state_container data stream.
Follow-up of [#2608](https://github.com/elastic/integrations/pull/2612) to fix https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/72/tests.
> Add job.name field in state_container

- packages/iptables/data_stream/log/_dev/test/system/test-journald-config.yml
- packages/journald/data_stream/log/_dev/test/system/test-journald-config.yml
This PR disables journald based system tests as there were panics observed: https://github.com/elastic/integrations/issues/2602
> Disable system tests exercising journald input

- packages/osquery/changelog.yml
- packages/osquery/manifest.yml
- packages/panw/changelog.yml
- packages/panw/manifest.yml
Major version bumped due to incorrect detection of breaking change. Fix package versions for -
- osquery
- panw
It's safe to fix the versions these updated versioned packages weren't promoted to staging/production.
> [osquery] [panw] Fix package versions

- .ci/schedule-daily.groovy
This PR fixes the daily schedule of CI jobs to use full semver to define Elastic stacks. I decided to enable parallel jobs as nobody notice it due to blocking bugs in 7.17.
Spotted here: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/89/pipeline
> CI fix: use full semver for Elastic stacks

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/manifest.yml
Adds standard HTTP options to Prometheus package.
Http options: [module-http-config-options](https://www.elastic.co/guide/en/beats/metricbeat/7.2/configuration-metricbeat.html#module-http-config-options)
Closes https://github.com/elastic/integrations/issues/496
> Add standard HTTP options to Prometheus package

- .ci/schedule-daily.groovy
This PR fixes the bad syntax in the daily schedule job (my bad).
Spotted in: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations-daily/detail/integrations-daily/156/pipeline/
> Fix daily schedule: bad groovy syntax

- packages/pulse_connect_secure/changelog.yml
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-admin.log-expected.json
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-syslog.log
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-syslog.log-expected.json
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-system.log-expected.json
- packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log-expected.json
- packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/pulse_connect_secure/data_stream/log/fields/ecs.yml
- packages/pulse_connect_secure/docs/README.md
- packages/pulse_connect_secure/manifest.yml
This adds support for syslog priority value parsing.
First commit is mechanical; this just runs the new version of elastic-package on to reduce diff noise in commit two.
`elastic-package test` in package/pulse_connect_secure
- Closes #2546.
N/A
> pulse_connect_secure: add syslog priority format parsing support

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/collstats/agent/stream/stream.yml.hbs
- packages/mongodb/data_stream/dbstats/agent/stream/stream.yml.hbs
- packages/mongodb/data_stream/replstatus/agent/stream/stream.yml.hbs
- packages/mongodb/data_stream/status/agent/stream/stream.yml.hbs
- packages/mongodb/manifest.yml
Authentication wasn't working in Mongodb because there was some missing pieces on the templating of the package.
This fix the auth errors for `3.x` and `4.x` but `5.x` doesn't work yet until the driver is updated.
> Fix templates to include username and password in Mongodb

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/manifest.yml
Fix `github.owner` attribute for the package. Change from `elastic/integrations` to `elastic/security-external-integrations`.
> [microsoft_sqlserver] fix owner

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/fields/agent.yml
- packages/network_traffic/data_stream/cassandra/fields/agent.yml
- packages/network_traffic/data_stream/dhcpv4/fields/agent.yml
- packages/network_traffic/data_stream/dns/fields/agent.yml
- packages/network_traffic/data_stream/flow/fields/agent.yml
- packages/network_traffic/data_stream/http/fields/agent.yml
- packages/network_traffic/data_stream/icmp/fields/agent.yml
- packages/network_traffic/data_stream/memcached/fields/agent.yml
- packages/network_traffic/data_stream/mongodb/fields/agent.yml
- packages/network_traffic/data_stream/mysql/fields/agent.yml
- packages/network_traffic/data_stream/nfs/fields/agent.yml
- packages/network_traffic/data_stream/pgsql/fields/agent.yml
- packages/network_traffic/data_stream/redis/fields/agent.yml
- packages/network_traffic/data_stream/sip/fields/agent.yml
- packages/network_traffic/data_stream/thrift/fields/agent.yml
- packages/network_traffic/data_stream/tls/fields/agent.yml
- packages/network_traffic/data_stream/tls/fields/protocol.yml
- packages/network_traffic/manifest.yml
This fixes a typo.
`elastic-package test` in network_traffic.
- Relates #2643
> network_traffic: fix typo

- packages/hashicorp_vault/_dev/build/docs/README.md
- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/docs/README.md
- packages/hashicorp_vault/manifest.yml
The Hashicorp Vault readme is breaking the [integration documentation](https://docs.elastic.co/en/integrations) update script. This PR fixes the error by moving indented code to markdown code blocks. This prevents the build from trying to render `<` and `{` characters.
Other PRs that I have opened with similar problems:
* https://github.com/elastic/integrations/pull/2654
* https://github.com/elastic/integrations/pull/2656
> Fix hashicorp documentation

- packages/hid_bravura_monitor/_dev/build/docs/README.md
- packages/hid_bravura_monitor/changelog.yml
- packages/hid_bravura_monitor/docs/README.md
- packages/hid_bravura_monitor/manifest.yml
The HID Bravura readme is currently breaking the [integration documentation](https://docs.elastic.co/en/integrations) update script. This PR fixes the docs by removing `{beatname_uc}`.
Other PRs that I have opened with similar problems:
* https://github.com/elastic/integrations/pull/2655
* https://github.com/elastic/integrations/pull/2656
> Fix hid_bravura documentation

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
- packages/crowdstrike/manifest.yml
When "Is FDR Queue" was enabled in the config then the S3 input was supposed
to parse the CrowdStrike FDR SQS notification format. But the config was checking
for `if fdr_queue` but the variable is named `is_fdr_queue`.
Fixes #2646
- Fixes #2646
> [crowdstrike] Fix issue with 'Is FDR Queue' option not taking effect

- packages/github/_dev/build/docs/README.md
- packages/github/_dev/deploy/docker/files/config.yml
- packages/github/changelog.yml
- packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/github/docs/README.md
- packages/github/manifest.yml
Fixes an bug with an invalid query parameter operator for the GitHub API.
- Closes #2622 
- Closes #2461
> [github] Fix Github query operator error

- packages/udp/changelog.yml
- packages/udp/data_stream/generic/manifest.yml
- packages/udp/manifest.yml
Fixing a typo in the manifest.yml of the UDP package for listen address
Closes #2668
> [UDP] Fixing typo in listen_address for package

- packages/ti_anomali/changelog.yml
- packages/ti_anomali/data_stream/limo/manifest.yml
- packages/ti_anomali/manifest.yml
Adding a missing UI option for first_interval to the limo datastream.
> [Anomali] adding initial interval to manifest

- packages/azure_metrics/_dev/build/docs/compute_vm.md
- packages/azure_metrics/_dev/build/docs/compute_vm_scaleset.md
- packages/azure_metrics/_dev/build/docs/container_instance.md
- packages/azure_metrics/_dev/build/docs/container_registry.md
- packages/azure_metrics/_dev/build/docs/container_service.md
- packages/azure_metrics/_dev/build/docs/database_account.md
- packages/azure_metrics/_dev/build/docs/storage_account.md
- packages/azure_metrics/changelog.yml
- packages/azure_metrics/docs/compute_vm.md
- packages/azure_metrics/docs/compute_vm_scaleset.md
- packages/azure_metrics/docs/container_instance.md
- packages/azure_metrics/docs/container_registry.md
- packages/azure_metrics/docs/container_service.md
- packages/azure_metrics/docs/database_account.md
- packages/azure_metrics/docs/storage_account.md
- packages/azure_metrics/manifest.yml
The Azure Metrics readmes are breaking the [integration documentation](https://docs.elastic.co/en/integrations) update script. This PR fixes the error by moving a string including `{` and `}` to a code snippet.
Other PRs that I have opened with similar problems:
* https://github.com/elastic/integrations/pull/2654
* https://github.com/elastic/integrations/pull/2655
> Fix azure_metrics docs

- packages/mimecast/changelog.yml
- packages/mimecast/data_stream/audit_events/fields/ecs.yml
- packages/mimecast/docs/README.md
- packages/mimecast/manifest.yml
This fixes a documentation bug.
- Relates #2643
> mimecast/auditevents: fix typo

- packages/logstash/changelog.yml
- packages/logstash/manifest.yml
This is required because for those who have installed it, upgrading to 8.0.0 stack can cause critical issues. There are no changes to the package itself beyond declaring that this package, as-is, is also compatible with ^8.0.0
> Makes experimental logstash package work for 8.0.0

- packages/fortinet/changelog.yml
- packages/fortinet/data_stream/clientendpoint/manifest.yml
- packages/fortinet/data_stream/firewall/manifest.yml
- packages/fortinet/data_stream/fortimail/manifest.yml
- packages/fortinet/data_stream/fortimanager/manifest.yml
- packages/fortinet/manifest.yml
Unify the descriptions of the Listen Address and Listen Port in manifests.
The variable names were not changed to avoid breaking the upgrade path for existing users.
- Relates #2627
> [fortinet] Clarify description of listen address/port

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container_logs/manifest.yml
- packages/kubernetes/manifest.yml
Adjust default ndjson parser configuration. Even though this configuration is commented out, I would add it to prevent `Error decoding JSON` errors in case there are both: json and not json logs in the k8s cluster.
- Relates https://github.com/elastic/beats/issues/6045
> Container logs: improve default ndjson parser configuration

- packages/docker/changelog.yml
Fix wrong link included in http://github.com/elastic/integrations/pull/2678.
> Fix url in docker changelog

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/tls/fields/protocol.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
This adds fields corresponding to changes in packetbeat in elastic/beats#30102.
- Relates elastic/beats#30102
> network_traffic/tls: capture tls random data and ocsp status

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
- packages/crowdstrike/data_stream/fdr/manifest.yml
- packages/crowdstrike/manifest.yml
The default value for `fdr_parsing_script` is a multline string. When the handlebar
template was evaluated this created invalid YAML. By changing the variable type to
'yaml' Kibana produces config that is valid. It looks like
sqs.notification_parsing_script.source: >-
function parse(n) { var m = JSON.parse(n); var evts = []; var files =
m.files; ...
I cannot find any documentation for the 'yaml' variable type so I hoping this is how it was
expected to be used.
- Closes #2646
Before:
After:
> [crowdstrike] Fix multi-line string handling for config variable

- packages/zscaler/changelog.yml
- packages/zscaler/docs/README.md
- packages/zscaler/manifest.yml
There are now Zscaler ZIA and Zscaler ZPA integrations that are specific Zscaler products.
This package is being marked as deprecated. The new integrations are not generated parsers
based on rsa2elk.
Relates #2459
- Relates #2459
> [zscaler] Mark package as deprecated

- packages/system/changelog.yml
- packages/system/data_stream/filesystem/agent/stream/stream.yml.hbs
- packages/system/data_stream/filesystem/manifest.yml
- packages/system/manifest.yml
The `filesystem.ignore_types` option was missing from the system integrations config. This adds it back in.
> Fix missing ignore in filesystem config

- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/_dev/test/system/test-pubsub-config.yml
- packages/gcp/data_stream/audit/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/dns/_dev/test/system/test-pubsub-config.yml
- packages/gcp/data_stream/dns/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/firewall/_dev/test/system/test-pubsub-config.yml
- packages/gcp/data_stream/firewall/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/vpcflow/_dev/test/system/test-pubsub-config.yml
- packages/gcp/data_stream/vpcflow/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/manifest.yml
This handlebar variable contains a string and is required to be
passed as a string to the Beat. It must be properly quoted because
it contains JSON which in YAML will be interpretted as an object.
In general all handlebar variables that are strings should be single-quoted.
Given the configuration input of
```yaml
vars:
credentials_json: '{\"fake\":\"creds\"}'
```
Fleet was producing a policy containing
```yaml
credentials_json:
\"fake\":\"creds\": null
```
and now will produce
```yaml
credentials_json: '{\"fake\":\"creds\"}'
```
> Add single quotes around the credentials_json var

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/manifest.yml
- packages/synthetics/data_stream/http/manifest.yml
- packages/synthetics/data_stream/icmp/manifest.yml
- packages/synthetics/data_stream/tcp/manifest.yml
- packages/synthetics/manifest.yml
This PR is part of the fix for elastic/kibana#125402.
It updates the default values for a monitor's `schedule` so that they're wrapped in double-quotes, not single-quotes.
Wrapping values in single-quotes causes `JSON.parse` to throw an error when parsing those values, and, therefore, causes an error in Kibana.
> ☝️  Please notice that this does not address why `input` values from the Kibana config are not passed to the integration. I'm not sure yet about whether that's a problem with the configuration itself or the piece of software responsible for setting those values.
> **UPDATE**: The problem with regards to the configuration values not propagating to the integration are now being tracked by the Fleet team at elastic/kibana#125730.
1. Add the following config to your Kibana config …
> [Uptime] fix default values for synthetic monitor schedules [closes elastic/kibana#125402]

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/common.yml
- packages/synthetics/data_stream/browser_network/fields/common.yml
- packages/synthetics/data_stream/browser_screenshot/fields/common.yml
- packages/synthetics/data_stream/http/fields/common.yml
- packages/synthetics/data_stream/icmp/fields/common.yml
- packages/synthetics/data_stream/tcp/fields/common.yml
- packages/synthetics/manifest.yml
Adds mapping for `service.name` to each Synthetics data stream, corresponding to the APM Service name
1. Check out this PR
2. Navigate to the `packages/synthetics` directory. Run `elastic-package clean`, then `elastic-package build`.
3. In that same directory, run `elastic-package stack up --version 8.2.0-SNAPSHOT -v`
4. One the stack is up, log in at `localhost:5601`. 
5. Navigate to the Synthetics Integration, create an HTTP, TCP, or browser monitor and add an APM service name. Make sure that you change the agent policy to `Elastic Agent (elastic-package)` before saving. 
6. Navigate to dev tools. Ensure that the synthetics document for that monitor has your specified APM service name listed under `service.name`.
> synthetics - add apm service name mapping

- packages/github/_dev/deploy/docker/files/config.yml
- packages/github/changelog.yml
- packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/github/manifest.yml
Construct dates as YYYY-MM-DDTHH:MM:SS+00:00 per
https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates.
Fixes #2731
> [github] Fix date format used in queries

- packages/docker/changelog.yml
- packages/docker/data_stream/diskio/fields/fields.yml
- packages/docker/data_stream/diskio/sample_event.json
- packages/docker/data_stream/network/fields/fields.yml
- packages/docker/data_stream/network/sample_event.json
- packages/docker/docs/README.md
- packages/docker/kibana/visualization/docker-Network-IO.json
- packages/docker/kibana/visualization/docker-containers.json
- packages/docker/manifest.yml
This PR tunes docker package accordingly to remove deprecated fields.
Related to https://github.com/elastic/beats/issues/30413 https://github.com/elastic/beats/pull/30500 https://github.com/elastic/beats/pull/27933
> Tune docker package according to Beat's fields deprecation

- packages/http_endpoint/_dev/build/docs/README.md
- packages/http_endpoint/changelog.yml
- packages/http_endpoint/docs/README.md
- packages/http_endpoint/manifest.yml
Updating the readme with recommendations from PR.
> [HTTP Endpoint] update README

- packages/mimecast/_dev/deploy/docker/files/config.yml
- packages/mimecast/changelog.yml
- packages/mimecast/data_stream/siem_logs/sample_event.json
- packages/mimecast/docs/README.md
- packages/mimecast/manifest.yml
Add content-disposition to test mock to properly create sample event from SIEM logs.
> [mimecast] Add content-disposition to test logs

- packages/sophos/changelog.yml
- packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/systemhealth.yml
- packages/sophos/manifest.yml
Copies the `systemhealth` ingest pipeline from the Beats module.
This pipeline was referenced in the main pipeline but not present in the package.
> sophos - Add missing `systemhealth` pipeline to xg datastream

- packages/nginx/_dev/build/docs/README.md
- packages/nginx/changelog.yml
- packages/nginx/docs/README.md
- packages/nginx/manifest.yml
Adds a table to the readme for the Nginx module, which lists the machine learning modules that are included in the integration. The names and descriptions for these jobs are found in https://github.com/elastic/integrations/blob/main/packages/nginx/kibana/ml_module/nginx-Logs-ml.json
- Relates #2640
> Add ML modules to Nginx readme

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
- packages/suricata/manifest.yml
This adds a few more network.protocols that had some missing mapping for ECS.
> [Suricata] adding more network protocols

- packages/cef/changelog.yml
- packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cef/manifest.yml
If the decode_cef Beat processor has errors then those errors are
lost if there is a pipeline error.
- Relates: https://github.com/elastic/integrations/issues/2676
> [cef] Append pipeline errors to error.message

- packages/kafka/changelog.yml
- packages/kafka/data_stream/broker/agent/stream/stream.yml.hbs
- packages/kafka/data_stream/consumergroup/agent/stream/stream.yml.hbs
- packages/kafka/data_stream/partition/agent/stream/stream.yml.hbs
- packages/kafka/manifest.yml
Pass the SSL configs entered in the UI down to agent config for the following metricsets: broker, consumergroup & partition.
Bumping the version to 1.2.2
Closes #2750
Redo of PR #2785, which will be closed.
Earlier SSL configs were not passed down to the metricset. Fixed it.
-
Tested the changes using elastic-package build and run. The new agent policy with ssl entered from the UI.
- id: kafka/metrics-kafka.partition-4fec773e-840d-470c-ae45-3bbcd1aff871
data_stream:
dataset: kafka.partition
type: metrics
metricsets:
- partition
period: 10s
hosts:
- 'localhost:9092'
ssl.certificate: cert1
ssl.certificate_authorities: auth1
ssl.key: key1
> Pass the SSL configs entered in the UI down to agent config

- packages/okta/changelog.yml
- packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
- packages/okta/manifest.yml
This increases the limit for the number of results returned in an API response from okta. This allows more responses to be obtained within the API rate limits.
- Closes #2776.
> okta: increase API response limit

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-application.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-calendar.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chat.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chromeos.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-contacts.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-delegatedadmin.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-docs.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-domain.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-groups.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-licenses.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-mobile.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-org.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-security.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-sites.log-expected.json
- packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-user.log-expected.json
- packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
- packages/google_workspace/manifest.yml
event.ingested is added by a Fleet final_pipeline so these additions were redundant.
> [google_workspace] Remove redundant event.ingested

- packages/cloudflare/changelog.yml
- packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
- packages/cloudflare/data_stream/logpull/manifest.yml
- packages/cloudflare/manifest.yml
Fix interval logic so interval can be as small as 1s instead of
2m.  This is necessary if there are large volumes of data.
``` bash
cd packages/cloudflare
elasstic-package clean && elastic-package check
elastic-package stack up -d
eval "$(elastic-package stack shellinit)"
```
- Closes #2705
> [cloudflare] bugfix interval

- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/_dev/test/system/test-transforms-config.yml
- packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
- packages/httpjson/data_stream/generic/manifest.yml
- packages/httpjson/data_stream/generic/sample_event.json
- packages/httpjson/manifest.yml
This removes oauth_custom and request_custom, and rather have separate UI fields for each option, to resolve issues with how config templates are converted in kibana.
> [HTTPJSON] fixing config fields in manifest.yml not working as intended

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/sample_event.json
- packages/network_traffic/data_stream/cassandra/sample_event.json
- packages/network_traffic/data_stream/dhcpv4/sample_event.json
- packages/network_traffic/data_stream/dns/sample_event.json
- packages/network_traffic/data_stream/http/sample_event.json
- packages/network_traffic/data_stream/icmp/sample_event.json
- packages/network_traffic/data_stream/memcached/sample_event.json
- packages/network_traffic/data_stream/mongodb/sample_event.json
- packages/network_traffic/data_stream/mysql/sample_event.json
- packages/network_traffic/data_stream/nfs/sample_event.json
- packages/network_traffic/data_stream/pgsql/sample_event.json
- packages/network_traffic/data_stream/redis/sample_event.json
- packages/network_traffic/data_stream/sip/sample_event.json
- packages/network_traffic/data_stream/thrift/sample_event.json
- packages/network_traffic/data_stream/tls/fields/protocol.yml
- packages/network_traffic/data_stream/tls/sample_event.json
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
This replays #2517 for client certificates, now fixing #2499.
- Closes #2499.
> package/network_traffic/tls: fix mapping for tls.detailed.client_certificate_chain

- .github/CODEOWNERS
This PR renames the `integrations-developer-experience` team to `ecosystem`.
> Rename the developer-experience team to ecosystem

- packages/aws/changelog.yml
- packages/aws/kibana/dashboard/aws-3367c170-921f-11e9-aa19-159bf182e06f.json
- packages/aws/manifest.yml
In https://github.com/elastic/kibana/issues/127664 the AWS package assets are not installed due to a missing reference in a dashboard.
While the Fleet team works on fixing the issue on their side, this PR fixes the AWS package to reference `metrics-` instead of `metricbeat-` as all other dashboar do.
Package is bumped to 1.13.1.
- https://github.com/elastic/kibana/issues/127664
> Aws 1.13.0 fix dashboard missing reference

- packages/aws/data_stream/ec2_metrics/_dev/deploy/tf/.terraform.lock.hcl
Add `.terraform.lock.hcl` to `aws` package.
- Closes #2661
> Add Terraform lock file to aws package

- .github/CODEOWNERS
- packages/modsecurity/changelog.yml
- packages/modsecurity/manifest.yml
Add support for ES 8.x and change to correct ownership of package
Closes #2832
> [Modsecurity] Set correct owner and include 8.0 versions

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/apm_server_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/apm_server_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/auditbeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/auditbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/elastic_agent_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/endpoint_security_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/endpoint_sercurity_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/filebeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/filebeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/fleet_server_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/fleet_server_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/metricbeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/metricbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/osquerybeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/osquerybeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/packetbeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/packetbeat_metrics/fields/ecs.yml
- packages/elastic_agent/manifest.yml
Fixes the missing `ecs.version` fields on the elastic_agent package.
1. Run `elastic-package build`
2. Run `elastic-package stack up`
3. Go to Discover and within the `logs-*` data view, type `ecs.version: "8.0.0"` into the filter bar
4. Verify that logs from elastic_agent are shown
- Closes https://github.com/elastic/kibana/issues/127000
> Add ecs.version to elastic_agent fields

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/docs/README.md
- packages/osquery_manager/manifest.yml
Upgrades mapping and readme to osquery 5.2.2
- Relates https://github.com/elastic/security-team/issues/3302
- Requires https://github.com/elastic/beats/pull/30874
> Upgrade to osquery 5.2.2

- packages/system/_dev/deploy/docker/docker-compose.yml
- packages/system/changelog.yml
- packages/system/data_stream/process/_dev/test/system/test-default-config.yml
- packages/system/data_stream/process/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/process/fields/ecs.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
Migrate data from Agent 7.x to ECS 8.0 format.
Agent 7.x produces process.ppid, but in order to comply with ECS 8.0
we want all data to use process.parent.pid.
The process data stream lacked any tests so I added a system test to
verify the pipeline works and validate the fields.yml. I found some
undocumented fields.
Relates #2363 #2512
- Relates #2363 
- Relates #2512
- 7.x source code producing the process.ppid - https://github.com/elastic/beats/blob/d420ccdaf201e32a524632b5da729522e50257ae/metricbeat/module/system/process/process.go#L124
> [system] Add pipeline to rename process.ppid in process data_stream

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log-expected.json
- packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
- Adds date parsing for the BiosReleaseDate field
``` sh
elastic-package clean
elastic-package check
elastic-package stack up -d
eval "$(elastic-package stack shellinit)"
```
> [crowdstrike] add date parsing for BiosReleaseDate field

- packages/aws/changelog.yml
- packages/aws/data_stream/waf/_dev/test/pipeline/test-waf.log-expected.json
- packages/aws/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
- packages/aws/manifest.yml
- fixes timestamp parsing in `waf` datastream by removing erroneous `'`
``` sh
elastic-package clean
elastic-package check
elastic-package stack up --daemon 
eval "$(elastic-package stack shellinit)"
elastic-package test pipeline -d waf
```
> [aws] fix timestamp parsing in waf data stream

- packages/gcp/_dev/build/docs/README.md
- packages/gcp/_dev/build/docs/audit.md
- packages/gcp/_dev/build/docs/dns.md
- packages/gcp/_dev/build/docs/firewall.md
- packages/gcp/_dev/build/docs/vpcflow.md
- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/manifest.yml
- packages/gcp/data_stream/dns/manifest.yml
- packages/gcp/data_stream/firewall/manifest.yml
- packages/gcp/data_stream/vpcflow/manifest.yml
- packages/gcp/docs/README.md
- packages/gcp/docs/audit.md
- packages/gcp/docs/dns.md
- packages/gcp/docs/firewall.md
- packages/gcp/docs/vpcflow.md
- packages/gcp/manifest.yml
Update README for the Google Cloud Platform (GCP) integration with new sections about how to configure authentication, integration settings, and how to start collecting logs creating a pub/sub topic, a subscription, and a sink.
The fields and events sample are included in both the README and the dedicated `.md` files, in preparation of making them visible on the main docs site https://docs.elastic.co/en/integrations/gcp.
Closes #2802
> GCP: improve integration docs

- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
- packages/httpjson/manifest.yml
Fixes a typo in the httpjson.yml.hbs template file
> [httpjson] Fixing typo in httpjson.yml.hbs

- .ci/schedule-daily.groovy
This PR modifies the daily schedule to test using 8.2.0-SNAPSHOT.
This [Jenkins pipeline](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/325/pipeline) discovered the inconsistency between the stack version used for testing and the requirement defined in the package.
> Use stack v8.2 for daily testing

- packages/cisco_secure_endpoint/changelog.yml
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp1.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp2.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp3.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp4.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp5.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp6.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp7.log-expected.json
- packages/cisco_secure_endpoint/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_secure_endpoint/data_stream/event/fields/ecs.yml
- packages/cisco_secure_endpoint/data_stream/event/sample_event.json
- packages/cisco_secure_endpoint/docs/README.md
- packages/cisco_secure_endpoint/manifest.yml
Will try to extract host.domain, user.domain and user.email if possible.
> Extract potential host.domain and user.domain in Cisco Secure Endpoint

- packages/fireeye/changelog.yml
- packages/fireeye/data_stream/nx/_dev/test/pipeline/test-nx.log-expected.json
- packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/default.yml
- packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/renaming-raws.yml
- packages/fireeye/data_stream/nx/fields/ecs.yml
- packages/fireeye/data_stream/nx/fields/fields.yml
- packages/fireeye/docs/README.md
- packages/fireeye/manifest.yml
Fix `dns.id` & `network.iana_number` field mappings.
- CLoses #2872
> [Fireeye] Fix field conflicts

- packages/ti_abusech/changelog.yml
- packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-common-config.yml
- packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
- packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-common-config.yml
- packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
- packages/ti_abusech/data_stream/malwarebazaar/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/data_stream/malwarebazaar/fields/ecs.yml
- packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
- packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-common-config.yml
- packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
- packages/ti_abusech/docs/README.md
- packages/ti_abusech/manifest.yml
Fix field mapping conflicts in `threat.indicator.file.x509.not_before/not_after`
- Closes #2871
> [TI AbuseCH] Fix field mappings

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/audit/_dev/test/pipeline/test-events.json-expected.json
- packages/microsoft_sqlserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_sqlserver/data_stream/audit/fields/winlog.yml
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
Fix field conflict for `winlog.record_id`
- Closes #2870
> [Microsoft SQL Server] Fix field conflict

- packages/checkpoint/changelog.yml
- packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
- packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
- packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-common-config.yml
- packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/checkpoint/data_stream/firewall/fields/fields.yml
- packages/checkpoint/docs/README.md
- packages/checkpoint/manifest.yml
Fix field mapping conflicts for `checkpoint.icmp_type`, `checkpoint.icmp_code` & `checkpoint.email_recipients_num`
- Closes #2873
> [Checkpoint] Fix multiple field conflicts

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/manifest.yml
- packages/network_traffic/data_stream/cassandra/manifest.yml
- packages/network_traffic/data_stream/dhcpv4/manifest.yml
- packages/network_traffic/data_stream/dns/manifest.yml
- packages/network_traffic/data_stream/flow/manifest.yml
- packages/network_traffic/data_stream/http/manifest.yml
- packages/network_traffic/data_stream/icmp/manifest.yml
- packages/network_traffic/data_stream/memcached/manifest.yml
- packages/network_traffic/data_stream/mongodb/manifest.yml
- packages/network_traffic/data_stream/mysql/manifest.yml
- packages/network_traffic/data_stream/nfs/manifest.yml
- packages/network_traffic/data_stream/pgsql/manifest.yml
- packages/network_traffic/data_stream/redis/manifest.yml
- packages/network_traffic/data_stream/sip/manifest.yml
- packages/network_traffic/data_stream/thrift/manifest.yml
- packages/network_traffic/data_stream/tls/manifest.yml
- packages/network_traffic/manifest.yml
Changes the release status to beta.
> network_traffic: change release stability to beta

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/index_recovery/fields/package-fields.yml
- packages/elasticsearch/manifest.yml
elasticsearch index_recovery data stream has version mapped as long in package-fields.yml and system auth data_stream has version mapped as keyword in fields.yml. This changes elasticsearch to use `keyword`.
- Closes #2885
> elasticsearch/index_recovery: fix version field mapping

- .github/CODEOWNERS
- packages/logstash/manifest.yml
We should also be the owner of the Logstash integration until ownership is moved to the Logstash teams.
> Update owner of Logstash

- packages/problemchild/_dev/build/docs/README.md
- packages/problemchild/changelog.yml
- packages/problemchild/docs/README.md
- packages/problemchild/manifest.yml
Fixes a small typo in the README of the ProblemChild package - changes Winglogbeat to Winlogbeat.
This package hasn't been published yet so there is no version update requirement.
Relates to https://github.com/elastic/integrations/pull/2115
> Fix typo in ML supervised model Problem child package

- packages/containerd/changelog.yml
- packages/containerd/data_stream/blkio/fields/ecs.yml
- packages/containerd/data_stream/cpu/fields/ecs.yml
- packages/containerd/data_stream/memory/fields/ecs.yml
- packages/containerd/docs/README.md
- packages/containerd/manifest.yml
Add new ECS container fields. 
Fields are:
1. container.cpu.usage
2. container.memory.usage
3. container.disk.read.bytes
4. container.disk.write.bytes
> Add new ecs fields to containerd integration

- .github/CODEOWNERS
- dev/codeowners/codeowners.go
- dev/codeowners/codeowners_test.go
- dev/codeowners/testdata/CODEOWNERS-invalid-override
- dev/codeowners/testdata/CODEOWNERS-no-owner
- dev/codeowners/testdata/CODEOWNERS-valid
This is creating noise in pull requests for new integrations.
CI check can be enough to ensure that each package has an entry in the
CODEOWNERS file.
> Remove default codeowners for new packages and code owners

- packages/zscaler_zia/_dev/build/docs/README.md
- packages/zscaler_zia/changelog.yml
- packages/zscaler_zia/docs/README.md
- packages/zscaler_zia/manifest.yml
The image in the README file was not visible on the GitHub page. This PR updates the image file reference in the README file.
- Move to integrations/packages/zscaler_zia directory.
> elastic-package build 
> elastic-package stack up -d -s package-registry
-
> Update image reference in Zscaler ZIA README.

- packages/auth0/_dev/build/docs/README.md
- packages/auth0/changelog.yml
- packages/auth0/docs/README.md
- packages/auth0/manifest.yml
Added link to Auth0 documentation
Type of change
- Enhancement
Added link to Auth0 documentation
-
> Update Auth0 Readme

- packages/microsoft_sqlserver/_dev/build/docs/README.md
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
Added links to Microsoft documentation
Type of change
- Enhancement
Added links to Microsoft documentation
-
> Update Microsoft SQL Server readme

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
- packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/auditd/data_stream/log/sample_event.json
- packages/auditd/docs/README.md
- packages/auditd/manifest.yml
The PR sets/fixes `event.outcome` value as per ECS specification.
`elastic-package test pipeline -v -g`
- Closes #3043
> [auditd]: set event.outcome value as per ECS specification

- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/agent/stream/httpjson.yml.hbs
- packages/microsoft_defender_endpoint/data_stream/log/manifest.yml
- packages/microsoft_defender_endpoint/manifest.yml
Certain Azure tenants requires a custom resource, like for example FED or government tenants, this PR adds support for overwriting the resource.
> [Microsoft Defender Endpoint] Add support for custom azure resource

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/threat.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/traffic.yml
- packages/panw/manifest.yml
This removes two invalid field values from event.category. The valid values were already set so no replacement is required.
- Closes #3049
> panw: remove invalid field values from pipeline

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
- packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/netflow/manifest.yml
This replaces an invalid field value. A parallel change is required in [x-pack/filebeat/input/netflow](https://github.com/elastic/beats/blob/ab3acb0d7bb3bff68a45000eac0a1beba87efe90/x-pack/filebeat/input/netflow/convert.go#L283) to bring that into line. This change is independent of that and will remain effective after that has been merged.
- Closes #3047
> netflow: replace invalid field value

- packages/atlassian_jira/_dev/build/docs/README.md
- packages/atlassian_jira/changelog.yml
- packages/atlassian_jira/docs/README.md
- packages/atlassian_jira/manifest.yml
Added link to Atlassian documentation
Type of change
- Enhancement
Added link to Atlassian documentation
-
> Update Atlassian Jira Readme

- packages/atlassian_confluence/_dev/build/docs/README.md
- packages/atlassian_confluence/changelog.yml
- packages/atlassian_confluence/docs/README.md
- packages/atlassian_confluence/manifest.yml
Added link to Atlassian documentation
Type of change
- Enhancement
Added link to Atlassian documentation
-
> Update Atlassian Confluence Readme

- packages/fireeye/changelog.yml
- packages/fireeye/data_stream/nx/_dev/test/pipeline/test-common-config.yml
- packages/fireeye/data_stream/nx/_dev/test/pipeline/test-nx.log-expected.json
- packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/default.yml
- packages/fireeye/manifest.yml
This moves invalid field values to conform with ECS.
- Closes #3053
> fireeye: move invalid field values

- packages/awsfargate/changelog.yml
- packages/awsfargate/manifest.yml
TL;DR  — I forgot to bump the package version in the last PR and this one fixes it.
Bump package version to 0.1.1 to release the last minor changes merged without a proper versioning.
- Relates #3109
> [awsfargate] bump package version

- .github/CODEOWNERS
- dev/codeowners/codeowners.go
- dev/codeowners/codeowners_test.go
- dev/codeowners/testdata/CODEOWNERS-invalid-override-wildcard
- dev/codeowners/testdata/CODEOWNERS-multiple-owners
- dev/codeowners/testdata/CODEOWNERS-valid
/packages/* only include the first level of files under /packages.
Removing the wildcard matches everything under /packages.
Fixes issue reproduced in https://github.com/elastic/integrations/pull/3131.
> Exclude ecosystem as owner of subdirectories of packages

- packages/google_workspace/changelog.yml
- packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
- packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
- packages/google_workspace/manifest.yml
Fixes the module config to prevent skipping events by using incorrect startDate values on pagination.
> [google_workspace} Fix pagination bug that skipped events when more than one page is present

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/kibana/search/cisco_asa-14fce5e0-498f-11e9-b8ce-ed898b5ef295.json
- packages/cisco_asa/kibana/search/cisco_asa-753406e0-4986-11e9-b8ce-ed898b5ef295.json
- packages/cisco_asa/kibana/search/cisco_asa-96c6ff60-4986-11e9-b8ce-ed898b5ef295.json
- packages/cisco_asa/kibana/visualization/cisco_asa-fd89b1e0-49a2-11e9-b8ce-ed898b5ef295.json
- packages/cisco_asa/manifest.yml
- stop using `cisco.asa.message_id` in visualization, field no longer populated.
- use data_stream to limit to cisco asa events.
- use event.code instead which has same info as `cisco.asa.message_id` did
- Closes #3142
> [cisco_asa] fix visualizations

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/docs/README.md
- packages/cloud_security_posture/manifest.yml
Update the integration readme to include deployment instructions for users who already have elastic-agent DaemonSet deployed and need to update it's volumes and mounts.
> Update cloud security posture README

- packages/cloudflare/changelog.yml
- packages/cloudflare/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
- packages/cloudflare/data_stream/logpull/_dev/test/pipeline/test-http-json.log-expected.json
- packages/cloudflare/data_stream/logpull/elasticsearch/ingest_pipeline/default.yml
- packages/cloudflare/docs/README.md
- packages/cloudflare/manifest.yml
adds teh fingerprint processor to deduplicate events for Cloudflare LogPull when using multiple agents.
-
> [Cloudflare] Add _id field to LogPull data_stream

- packages/zoom/changelog.yml
- packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
- packages/zoom/manifest.yml
Adds config to ignore content-type checks.
> [zoom] Fix content-type handling

- packages/gcp/_dev/build/docs/README.md
- packages/gcp/changelog.yml
- packages/gcp/docs/README.md
- packages/gcp/manifest.yml
Document the specific GCP privileges required by the Pub/Sub input.
> [gcp] Clarify service account privileges

- packages/cloudflare/_dev/build/docs/README.md
- packages/cloudflare/changelog.yml
- packages/cloudflare/docs/README.md
- packages/cloudflare/manifest.yml
Update Cloudflare documentation
Pipeline Tests
`elastic-package test pipeline`
System Tests
`elastic-package test system`
- Closes #3227
> [Cloudflare]: update documentation

- packages/aws/changelog.yml
- packages/aws/manifest.yml
This PR is to fix duplicate titles in AWS integration. When adding AWS integration, in the configure integration page, without this PR you will see multiple `Collect logs from S3` titles and multiple `Collect logs from CloudWatch` titles. They are meant for adding different integrations but accidentally were named to be all the same.
Before:
After:
> Fix duplicate titles in AWS integration

- packages/symantec_endpoint/changelog.yml
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-administrative.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-activity.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-behavior.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-packet.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-proactive-detection-sonar.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-risk.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-scan.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-security.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-system.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-traffic.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-policy.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-remove-mapped-fields.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc3164.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc5424.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-system.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-text-log-dump.log-expected.json
- packages/symantec_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/symantec_endpoint/manifest.yml
Changes values assigned to ECS field to conform to the spec.
- Closes #3050
> symantec_endpoint: use valid ECS values for fields

- packages/zeek/changelog.yml
- packages/zeek/data_stream/kerberos/_dev/test/pipeline/test-kerberos.log-expected.json
- packages/zeek/data_stream/kerberos/elasticsearch/ingest_pipeline/default.yml
- packages/zeek/manifest.yml
Changes values assigned to ECS field to conform to the spec.
- use "access" for event.type instead of "authentication"
- add "authentication" to event.category
- Closes #3052
> zeek/kerberos: use valid ECS values for fields

- packages/aws/changelog.yml
- packages/aws/manifest.yml
This PR changes `s3` integration tile's title and description to better explain what this integration does.
Also several services in AWS should be called Amazon XXX instead of AWS XXX. For example, S3, RDS, EC2 and etc.
- Closes https://github.com/elastic/integrations/issues/3237
> Improve s3 integration tile information

- packages/auditd/changelog.yml
- packages/auditd/kibana/dashboard/auditd-dfbb49f0-0a0f-11e7-8a62-2d05eaaac5cb.json
- packages/auditd/kibana/search/auditd-4ac0a370-0a11-11e7-8b04-eb22a5669f27.json
- packages/auditd/kibana/visualization/auditd-2bb0fa70-0a11-11e7-9e84-43da493ad0c7.json
- packages/auditd/kibana/visualization/auditd-5ebdbe50-0a0f-11e7-825f-6748cda7d858.json
- packages/auditd/kibana/visualization/auditd-6295bdd0-0a0e-11e7-825f-6748cda7d858.json
- packages/auditd/kibana/visualization/auditd-c5411910-0a87-11e7-8b04-eb22a5669f27.json
- packages/auditd/manifest.yml
Migrates the map visualisation to from tile_map to map object.
(This PR is partially to test the waters — if it's fine I'll take on the remaining SEI migrations)
- Relates #2617
> auditd: migrate tile_map to map object

- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
- packages/httpjson/data_stream/generic/manifest.yml
- packages/httpjson/manifest.yml
Adds missing option for the Google oauth2 config
> [httpjson] Adds missing  option for Google Oauth2

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/stream.yml.hbs
- packages/cloud_security_posture/manifest.yml
The information in `dataYaml` var (which is functionally the Rules Activation YAML) is sent to cloudbeat via the Agent policy, where it can be consumed for cloudbeat to know which rules to run.
Within the package directory,
```
elastic-package up
```
Create an Agent policy and view its full contents. Changes made to the `dataYaml` var will be reflected as data stream input in the Agent policy.
> Send dataYaml (Rules Activation YAML) to Agent

- packages/docker/changelog.yml
- packages/docker/data_stream/diskio/agent/stream/stream.yml.hbs
- packages/docker/data_stream/diskio/manifest.yml
- packages/docker/manifest.yml
This adds A `skip_major` option, in line with what's now supported in metricbeat itself.
> Add skip_major option to docker/diskio

- packages/aws/changelog.yml
- packages/aws/data_stream/dynamodb/fields/fields.yml
- packages/aws/data_stream/rds/fields/fields.yml
- packages/aws/data_stream/rds/sample_event.json
- packages/aws/data_stream/sns/fields/fields.yml
- packages/aws/docs/dynamodb.md
- packages/aws/docs/rds.md
- packages/aws/docs/sns.md
- packages/aws/manifest.yml
This PR is to fix the RDS dimension fields in fields.yml file. When collecting dimension information from CloudWatch, if there are more than one dimension key, these keys are separated into different dimensions with their own entries. For example: dimension `DBClusterIdentifier, Role` will separate into `aws.dimesnions.DBClusterIdentifier` and `aws.dimensions.Role`.
> Fix aws.dimensions.* for rds data stream

- packages/infoblox/changelog.yml
- packages/infoblox/docs/README.md
- packages/infoblox/manifest.yml
There is a new integration specific to Infoblox NIOS. This package is now deprecated.
Relates #3129 
- Relates #3129
> [infoblox] Mark package as deprecated

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/fields.yml
- packages/elastic_agent/manifest.yml
It changes some of the CPU metrics mappings for the Elsatic Agent. They were `date`, when should be `long`.
- Closes #3276
> 3276 metrics-elastic_agent mapping system.process.cpu.total.time.ms as a date

- packages/linux/changelog.yml
- packages/linux/data_stream/memory/fields/fields.yml
- packages/linux/manifest.yml
This is a fix for https://github.com/elastic/integrations/issues/3120. Just adding a few fields to the one memory datastream.
> Add swap to memory fields

- packages/cisco_ftd/_dev/deploy/docker/docker-compose.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/system/test-tcp-config.yml
- packages/cisco_ftd/data_stream/log/agent/stream/tcp.yml.hbs
- packages/cisco_ftd/data_stream/log/manifest.yml
- packages/cisco_ftd/manifest.yml
- Add TCP input, with TLS and custom options support
- Add system test for TCP input
```
cd packages/cisco_ftd && elastic-package test
```
- Relates #1878
> [cisco_ftd] Add TCP input with TLS support

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudwatch_logs/manifest.yml
- packages/aws/manifest.yml
This PR is to deprecate s3 input as an option in CloudWatch integration. Logs sent to CloudWatch can be ingested into elasticsearch directly via cloudwatch input. There is no need to send them to an S3 bucket and then to ealsticsearch.
Also this PR also enhanced the description for cloudwatch integration.
- Closes https://github.com/elastic/integrations/issues/3261
-
> Deprecate s3 input in cloudwatch integration

- packages/crowdstrike/changelog.yml
- packages/cyberark/changelog.yml
- packages/cyberarkpas/changelog.yml
- packages/docker/changelog.yml
- packages/elastic_agent/changelog.yml
- packages/nats/changelog.yml
- packages/nginx/changelog.yml
- packages/nginx_ingress_controller/changelog.yml
- packages/osquery_manager/changelog.yml
- packages/postgresql/changelog.yml
- packages/prometheus/changelog.yml
- packages/rabbitmq/changelog.yml
- packages/redis/changelog.yml
- packages/security_detection_engine/changelog.yml
- packages/snort/changelog.yml
- packages/stan/changelog.yml
- packages/synthetics/changelog.yml
- packages/traefik/changelog.yml
- packages/zookeeper/changelog.yml
- packages/zoom/changelog.yml
- packages/zscaler/changelog.yml
Fix links in changelogs, required for package-spec 1.8.0 (https://github.com/elastic/package-spec/pull/324).
> Fix links in changelogs

- packages/cisco_duo/changelog.yml
- packages/cisco_duo/data_stream/auth/_dev/test/pipeline/test-auth.log-expected.json
- packages/cisco_duo/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/manifest.yml
This fixes an invalid value in event.outcome for the auth data set.
- Closes #3328
> cisco_duo: fix invalid values for event.outcome

- packages/fireeye/changelog.yml
- packages/fireeye/data_stream/nx/sample_event.json
- packages/fireeye/docs/README.md
- packages/fireeye/manifest.yml
This fixes the invalid event.type value in the sample event that was missed in #3099.
- Closes #3053
> fireeye: fix invalid value in sample event

- packages/netflow/changelog.yml
- packages/netflow/data_stream/log/sample_event.json
- packages/netflow/manifest.yml
This fixes the event.category field in the sample event.
- Closes #3047
> netflow: fix sample event

- packages/aws/changelog.yml
- packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-extra-samples.log-expected.json
- packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log-expected.json
- packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-v5-all-fields.log-expected.json
- packages/aws/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/vpcflow/sample_event.json
- packages/aws/docs/vpcflow.md
- packages/aws/manifest.yml
This PR is to fix invalid values for ECS fields in AWS integration.
- Closes https://github.com/elastic/integrations/issues/3044
> [aws] Fix invalid values for ECS fields

- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
This removes invalid values from the event.outcome field. 
- Closes #3328
> cisco_ftd: remove invalid values from ECS fields

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/sip/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/sip/sample_event.json
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
This change removes an invalid value in the SIP data set.
- Relates #3329
> network_traffic: remove invalid value from event.category in SIP sample event

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/sample_event.json
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
This removes invalid values from the event.outcome field.
- Relates #3344
- Relates #3016
> cisco_asa: remove invalid values from ECS fields

- packages/network_traffic/changelog.yml
- packages/network_traffic/manifest.yml
It moves the network packet capture integration to release:ga.
-
> network_traffic: release as ga

- packages/okta/changelog.yml
- packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
- packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/okta/data_stream/system/fields/fields.yml
- packages/okta/manifest.yml
This change fills the already mapped `okta.request.ip-chain` array, but redefines the mapping as a flattened object array.
- Closes #3292
> okta: fill okta.request.ip_chain.* as a flattened object

- packages/panw/changelog.yml
- packages/panw/kibana/visualization/panw-135930b0-7570-11e9-976e-65a8f47cc4c1.json
- packages/panw/kibana/visualization/panw-d9cab170-756f-11e9-976e-65a8f47cc4c1.json
- packages/panw/manifest.yml
These were missed when the source and destination zone ingestion was
removed.
See https://github.com/elastic/integrations/commit/b6a86b2ff490a90468605df945cc1c7d6d7045af#diff-59b7510d3715bf1d6cc9619d4ae36134571ae31e2bb54c717b653287ac4cc288L59-L62 for details.
-
> panw: update mapping of zone fields in visualisations

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/log/_dev/test/pipeline/test-m365-defender-empty-ndjson.log-expected.json
- packages/m365_defender/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/data_stream/log/sample_event.json
- packages/m365_defender/docs/README.md
- packages/m365_defender/manifest.yml
Events with status type of "Redirect" is events created when an incident is updated, however without any information, alerts or ID's, so it bypasses duplication handling, this PR ensures those empty events are also dropped.
> [M365_Defender] Update duplication for redirect type events

- packages/iptables/changelog.yml
- packages/iptables/data_stream/log/sample_event.json
- packages/iptables/docs/README.md
- packages/iptables/manifest.yml
The sample event was not up to date with the pipeline.
> [iptables] Update sample_event.json

- packages/santa/changelog.yml
- packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
- packages/santa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/santa/data_stream/log/fields/ecs.yml
- packages/santa/data_stream/log/sample_event.json
- packages/santa/docs/README.md
- packages/santa/manifest.yml
This adds a `process.entity_id` from the agent.id, the process.pid and the process.pidversion (stored in santa.pidversion).
- Relates https://github.com/elastic/integrations/pull/3347#pullrequestreview-974633387 and https://github.com/elastic/integrations/pull/3347#pullrequestreview-975997434.
> santa: add process.entity_id constructed from agent.id, pid and pidversion

- packages/sonicwall/_dev/deploy/docker/docker-compose.yml
- packages/sonicwall/changelog.yml
- packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-common-config.yml
- packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-rsa2elk-output.json
- packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-rsa2elk-output.json-expected.json
- packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/sonicwall/manifest.yml
Format the `{source,destination}.mac` field as per ECS (h[ttps://www.elastic.co/guide/en/ecs/current/ecs-observer.html#field-observer-mac](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-mac)). 
> The notation format from RFC 7042 is suggested: Each octet (that is, 8-bit byte) is represented by two [uppercase] hexadecimal digits giving the value of the octet as an unsigned integer. Successive octets are separated by a hyphen.
> [sonicwall] Format {source,destination}.mac per ECS

- packages/cylance/_dev/deploy/docker/docker-compose.yml
- packages/cylance/changelog.yml
- packages/cylance/data_stream/protect/_dev/test/pipeline/test-common-config.yml
- packages/cylance/data_stream/protect/_dev/test/pipeline/test-rsa2elk-output.json
- packages/cylance/data_stream/protect/_dev/test/pipeline/test-rsa2elk-output.json-expected.json
- packages/cylance/data_stream/protect/_dev/test/system/test-udp-config.yml
- packages/cylance/data_stream/protect/elasticsearch/ingest_pipeline/default.yml
- packages/cylance/data_stream/protect/sample_event.json
- packages/cylance/manifest.yml
Format the `host.mac` field as per ECS (https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-mac).
> The notation format from RFC 7042 is suggested: Each octet (that is, 8-bit byte) is represented by two [uppercase] hexadecimal digits giving the value of the octet as an unsigned integer. Successive octets are separated by a hyphen.
The value also needed to be converted to an array.
> [cylance] Format host.mac per ECS

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/agent.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/base-fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/manifest.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/agent.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/base-fields.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/beat-fields.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/manifest.yml
- packages/elastic_agent/manifest.yml
Required configuration changes to avoid permission errors when Agent-managed filebeat tries to create the `logs-elastic_agent.cloudbeat-*` index on ES. 
Build the `elastic_agent` and `cloud_security_posture` packages, bring the stack up along with the [associated changes on Kibana](https://github.com/elastic/kibana/pull/132452). Running an Agent with the CIS integration added should show the option for cloudbeat logs on the logs page, as shown in the screenshot.
> Add configuration required for cloudbeat logs, metrics

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/cassandra/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/dhcpv4/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/http/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/icmp/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/memcached/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/mongodb/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/mysql/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/nfs/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/pgsql/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/redis/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/manifest.yml
This makes the integration ECS-compliant.
- Closes #3329
> network_traffic: remove invalid "network_traffic" terms from event.category

- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-auditlogs.log
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-auditlogs.log-config.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-auditlogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
- packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_umbrella/data_stream/log/fields/ecs.yml
- packages/cisco_umbrella/data_stream/log/fields/fields.yml
- packages/cisco_umbrella/docs/README.md
- packages/cisco_umbrella/manifest.yml
Add Audit Logs support
- Closes #2295
> [Cisco Umbrella] Add Audit Log support

- docs/developer_workflow_design_build_test_integration.md
Adds verbose/daemon to package-registry recycle command in dev docs.
Without this it's unclear if the job is hanging or just taking a long time to download layers for rebuild.
Rebuild grabs ~1GB of layers which takes 13 minutes on my connection.
- ~~I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~~
- ~~I have verified that all data streams collect metrics or logs.~~
- ~~I have added an entry to my package's `changelog.yml` file.~~
- ~~I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~
Read and follow …
> Add verbose/daemon to package-registry recycle command

- packages/fim/changelog.yml
- packages/fim/manifest.yml
Releases the auditbeat-based `fim` package as GA and makes it compatible with 8.2.0.
> fim: Make GA and compatible with 8.2.0

- .ci/jobs/integrations.yml
It was reported that PRs get triggered again if there was a change in their PR description.
The GitHub webhook event is sent and processed by jenkins, since Jenkins verifies the target branch has changed then it triggers a new build.
This is the configuration we apply by default as stated in https://github.com/elastic/apm-pipeline-library/blob/c13c74b24da047d29da2a628b7645fe55dda1da7/.ci/jobs/apm-test-pipeline-mbp.yml#L54-L57
> jjbb: ignore builds if the target branch has changed

- packages/fortinet/data_stream/fortimanager/_dev/test/pipeline/test-rsa2elk-output.json
- packages/fortinet/data_stream/fortimanager/_dev/test/pipeline/test-rsa2elk-output.json-expected.json
- packages/fortinet/data_stream/fortimanager/elasticsearch/ingest_pipeline/default.yml
Format the `{source,destination}.mac` field as per ECS (h[ttps://www.elastic.co/guide/en/ecs/current/ecs-observer.html#field-observer-mac](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-mac)). 
> The notation format from RFC 7042 is suggested: Each octet (that is, 8-bit byte) is represented by two [uppercase] hexadecimal digits giving the value of the octet as an unsigned integer. Successive octets are separated by a hyphen.
> [fortinet.forimanager] - Format {source,destination}.mac per ECS

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/thrift/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/thrift/sample_event.json
- packages/network_traffic/data_stream/tls/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/tls/sample_event.json
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
> network_traffic: fix invalid terms in tls and thrift data sets

- packages/postgresql/_dev/build/docs/README.md
- packages/postgresql/docs/README.md
- Enhancement
Readme does not hold the information about the minimum privileges a postgresSQL user must hold to fetch the metric from Elasticsearch.
> [doc] PostgreSQL module - minimum privileges required

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs
- packages/ti_misp/manifest.yml
> [MISP] Add fixes for MISP integration

- packages/microsoft_dhcp/changelog.yml
- packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-logv6.log-expected.json
- packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcpv6.yml
- packages/microsoft_dhcp/manifest.yml
Replaces unexpected value for `event.type` "stop" with "end".
- Fixes https://github.com/elastic/integrations/issues/3406
> [microsoft_dhcp] Fix value of event.type

- packages/carbon_black_cloud/changelog.yml
- packages/carbon_black_cloud/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
- packages/carbon_black_cloud/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/carbon_black_cloud/manifest.yml
Replaces `failed` with `failure` in `event.outcome`, according to ECS.
- Fixes #3407
> [carbon_black_cloud] Fix invalid value for event.outcome

- packages/windows/changelog.yml
- packages/windows/data_stream/powershell/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/powershell/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
This tightens constraints in the regular expression to prevent greedy consumption of the input and regexp complexity explosion.
- Closes #3494 
- Relates elastic/beats#31833
> windows/powershell: fix regexp constraints in event 800 parameter detail processing

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/cluster_stats/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/enrich/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_recovery/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_summary/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/ml_job/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/node/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/node_stats/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/pending_tasks/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/shard/agent/stream/stream.yml.hbs
- packages/elasticsearch/manifest.yml
Add `scope` configuration option for metricsets
- Closes #3255
> [elasticsearch] Add `scope` configuration option for metricsets

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
Prior to this change the data type (HashMap) was constructed on each script processor iteration. By using `params` the same map is reused, but care must be taken to ensure that the `params` data is not modified. That involves making copies of any mutable lists.
Based on local testing this changes the avg execution time of the categorize-events script processor the from 71,092 ns to 5,810 ns.
This was done from a containerized ES running on my local machine so don't read into the overall numbers. The relative difference in the categorize-events script is the important part.
Before:
After:
> [crowdstrike.fdr] Use 'params' for data table in script processors

- packages/cyberarkpas/changelog.yml
- packages/cyberarkpas/data_stream/audit/manifest.yml
- packages/cyberarkpas/manifest.yml
The definition for the paths variable was missing the `multi` flag, preventing it to be used when setting up the integration in the UI, as it would never be an array.
> cyberarkpas: Make paths a multi string var

- packages/azure_application_insights/_dev/build/docs/README.md
- packages/azure_application_insights/changelog.yml
- packages/azure_application_insights/docs/README.md
- packages/azure_application_insights/docs/app_state.md
- packages/azure_application_insights/manifest.yml
Added links to Microsoft documentation and corrected Markdown
Type of change
- Enhancement
Added links to Microsoft documentation and corrected Markdown
-
> Update azure_application_insights Readme

- packages/hid_bravura_monitor/_dev/build/docs/README.md
- packages/hid_bravura_monitor/changelog.yml
- packages/hid_bravura_monitor/docs/README.md
- packages/hid_bravura_monitor/manifest.yml
added links to documentation is and fixed existing links
Type of change
- Enhancement
added links to documentation is and fixed existing links
-
> update hid_bravura_monitor readme

- packages/google_workspace/_dev/build/docs/README.md
- packages/google_workspace/changelog.yml
- packages/google_workspace/docs/README.md
- packages/google_workspace/manifest.yml
added a link to Google documentation
Type of change
Enhancement
added a link to Google documentation
-
> update Google workspace readme

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Currently, we can only constrain an integration to a Kibana version.
Even though an old version of the elastic agent can run with newer versions of the Elastic stack it's still worth limiting the newer versions of the Integration to Kibana 8.4, which narrows down the possibility of running with the wrong cloudbeat version.
- Relates: https://github.com/elastic/package-spec/issues/165#issuecomment-1153753218
> CSP - Update kibana version constrain

- packages/iis/changelog.yml
- packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log-expected.json
- packages/iis/data_stream/access/_dev/test/pipeline/tst-iis10-access.log
- packages/iis/data_stream/access/_dev/test/pipeline/tst-iis10-access.log-expected.json
- packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/iis/manifest.yml
- Enhancement
IIS Beats module doesn't support the below type of IIS 10 log format:
2018-12-31 12:02:53 10.44.0.136 GET / - 443 - 10.50.6.188 Mozilla/4.0+(compatible;+MSIE+8.0;+Windows+NT+5.1;+Trident/4.0) - - 401 0 0 0
Gives the below error :
Provided Grok expressions do not match field value: [2021-06-10 23:26:57 10.44.0.136 GET / - 80 - 10.46.208.5 Mozilla/4.0+(compatible;+MSIE+8.0;+Windows+NT+5.1;+Trident/4.0) - itweb.acx.co 200 0 0 23]
`This PR adds support for a log format for IIS 10 logs.` 
A new grok pattern was added that supports parsing cookie in the IIS 10 log. 
Pipeline tests have been added for the new format of logs. 
Running elastic-package test pipeline should be good. 
- Closes https://github.com/elastic/beats/issues/31839
> iis_iis10_sdh: Accept IIS 10 Log Format

- packages/pfsense/changelog.yml
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-haproxy.log
- packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-haproxy.log-expected.json
- packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/haproxy.yml
- packages/pfsense/manifest.yml
Add support for parsing HTTP, TCP and Error logs for HAproxy running on PFsense.
- Resolves #3501
> [PFsense] Update PFsense HAProxy parsing

- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
- packages/httpjson/manifest.yml
Auth options were supedited to the existence of `oauth_id`, which made valid configs not rendered. Removing this will delegate the validation of the config to the input itself.
> [httpjson] Remove conditional rendering based on oauth_id of auth options

- packages/cisco_meraki/_dev/build/docs/README.md
- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/docs/README.md
- packages/cisco_meraki/manifest.yml
This PR fixes a `docs.elastic.co` documentation build error. Squiggly brackets must be escaped or in backticks.
* https://github.com/elastic/integrations/issues/3351.
> Fix doc build (Cisco Meraki)

- packages/azure_metrics/_dev/build/docs/monitor.md
- packages/azure_metrics/changelog.yml
- packages/azure_metrics/docs/monitor.md
- packages/azure_metrics/manifest.yml
This PR fixes a `docs.elastic.co` documentation build error. Squiggly brackets must be escaped or in backticks.
* https://github.com/elastic/integrations/issues/3351.
> Fix doc build (Azure Metrics)

- packages/akamai/_dev/build/docs/README.md
- packages/akamai/changelog.yml
- packages/akamai/docs/README.md
- packages/akamai/manifest.yml
improved the clarity of the English
- Enhancement
improved the clarity of the English
-
>  update readme for Akamai 

- packages/system/changelog.yml
- packages/system/data_stream/core/agent/stream/stream.yml.hbs
- packages/system/data_stream/core/manifest.yml
- packages/system/data_stream/cpu/agent/stream/stream.yml.hbs
- packages/system/data_stream/cpu/manifest.yml
- packages/system/data_stream/diskio/agent/stream/stream.yml.hbs
- packages/system/data_stream/diskio/manifest.yml
- packages/system/data_stream/filesystem/agent/stream/stream.yml.hbs
- packages/system/data_stream/filesystem/manifest.yml
- packages/system/data_stream/fsstat/agent/stream/stream.yml.hbs
- packages/system/data_stream/fsstat/manifest.yml
- packages/system/data_stream/load/agent/stream/stream.yml.hbs
- packages/system/data_stream/load/manifest.yml
- packages/system/data_stream/memory/agent/stream/stream.yml.hbs
- packages/system/data_stream/memory/manifest.yml
- packages/system/data_stream/network/agent/stream/stream.yml.hbs
- packages/system/data_stream/network/manifest.yml
- packages/system/data_stream/process/agent/stream/stream.yml.hbs
- packages/system/data_stream/process/manifest.yml
- packages/system/data_stream/process_summary/agent/stream/stream.yml.hbs
- packages/system/data_stream/process_summary/manifest.yml
- packages/system/data_stream/socket_summary/agent/stream/stream.yml.hbs
- packages/system/data_stream/socket_summary/manifest.yml
- packages/system/data_stream/syslog/agent/stream/log.yml.hbs
- packages/system/data_stream/syslog/manifest.yml
- packages/system/data_stream/uptime/agent/stream/stream.yml.hbs
- packages/system/data_stream/uptime/manifest.yml
- packages/system/manifest.yml
Fix for https://github.com/elastic/integrations/issues/2865
This adds a little drop-down config that adds `processors` and `tags` fields to all events in the system integration.
> Add processors and tags to all system data streams

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/container_instance/agent/stream/stream.yml.hbs
- packages/azure_metrics/data_stream/container_instance/elasticsearch/ingest_pipeline/default.yml
- packages/azure_metrics/manifest.yml
This PR is to move lightweight module configuration from Metricbeat into integrations.
* Closes #3592
> [Azure] Move container instance metrics from beats to integrations

- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
- packages/httpjson/data_stream/generic/manifest.yml
- packages/httpjson/manifest.yml
Exposes new option `oauth_google_jwt_json` added in 8.4.0
> [httpjson] Add  option to the manifest

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/container_service/agent/stream/stream.yml.hbs
- packages/azure_metrics/data_stream/container_service/elasticsearch/ingest_pipeline/default.yml
- packages/azure_metrics/manifest.yml
This PR is to move lightweight module configuration from Metricbeat into integrations.
Switch from "container_service" to "monitor" metricset, add the metrics configuration from beats, and add an ingest pipeline to set the expected field names (`azure.container_service.*` instead of `azure.metrics.*`).
- Closes #3595 3595
> Move container_service metrics from beats to integrations

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/fields.yml
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
This fixes handling of user parsing when there are SGT fields associated with the user and dissects the destination user from the domain in 302013 and 302015 events.
- Relates #elastic/beats#32009
> cisco_asa: fix handling of user parsing with sgt fields

- packages/httpjson/changelog.yml
- packages/httpjson/data_stream/generic/manifest.yml
- packages/httpjson/manifest.yml
Template breaks when yaml contents are all comments under some circumstances. The default examples were causing some issues because of that for some configurations.
> [httpjson] Remove defaults from manifest.

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/container_registry/agent/stream/stream.yml.hbs
- packages/azure_metrics/data_stream/container_registry/elasticsearch/ingest_pipeline/default.yml
- packages/azure_metrics/data_stream/container_registry/sample_event.json
- packages/azure_metrics/manifest.yml
This PR is to move lightweight module configuration from Metricbeat into integrations.
Switch from "container_registry" to "monitor" metricset, add the metrics configuration from beats, and add an ingest pipeline to set the expected field names (`azure. container_registry.*` instead of `azure.metrics.*`).
- Closes #3594
> [Azure Metrics] Move container_registry metrics from beats to integrations

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/data_stream/query/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/query/manifest.yml
- packages/prometheus/data_stream/remote_write/manifest.yml
- packages/prometheus/manifest.yml
…s; collector: add leader election, remove default value for ssl; query: add leader election
Those changes are the result of evaluation issue, for more details: https://github.com/elastic/integrations/issues/3489, https://github.com/elastic/integrations/issues/3487, https://github.com/elastic/integrations/issues/3488
remote_write datastream:
- hide some configuration settings
collectordatastream:
- add leader election
- remove default value for ssl
query datastream:
- add leader election
- Relates https://github.com/elastic/integrations/issues/3489, https://github.com/elastic/integrations/issues/3487, https://github.com/elastic/integrations/issues/3488
Collector:
1. added leader election setting as an advanced option
2. …
> Prometheus integration: minor enhancements as an outcome of evaluation issues

- packages/suricata/changelog.yml
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
- packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/dns-answer-v1.yml
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/dns-answer-v2.yml
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/dns.yml
- packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/tls.yml
- packages/suricata/data_stream/eve/sample_event.json
- packages/suricata/docs/README.md
- packages/suricata/manifest.yml
This adds the SNI host to `related.hosts` when the event is a TLS event and cleans up some template invocations.
- Closes #3521
> suricata: add SNI to related.hosts for TLS events

- packages/windows/changelog.yml
- packages/windows/data_stream/service/agent/stream/stream.yml.hbs
- packages/windows/data_stream/service/manifest.yml
- packages/windows/manifest.yml
- Enhancement
This PR adds the [processors](https://www.elastic.co/guide/en/beats/metricbeat/current/filtering-and-enhancing-data.html) for the windows integration UI for windows service data stream, So that users can provide the processors input from the UI and filter out the services based on service display name or service state.
- Clone the PR in windows machine.
- Build the integration using ```elastic-package``` commands
- Goto Integration page -> Search for windows -> Update to the latest package version
- Add the windows integration.
- Under the windows service metrics find the Processors yaml input box
- Specify the Processors for filtering the windows services.
- Closes [#2866](https://github.com/elastic/integrations/issues/2866)
- Closes …
> [Windows enhancement ]Added processor field for service data stream in windows package

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudfront_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/ec2_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/elb_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/firewall_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/route53_public_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/route53_resolver_logs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/s3access/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
- packages/aws/manifest.yml
Upstream event forwarders like Logstash can add their `event.original` field so we should add a check to see if `event.original` exists before copying `message` field to `event.original`.
> [AWS] check if event.original exists before copying message field

- docs/generic_guidelines.md
Add guidance on image format to mandate `svg` for logos since `png` may crash Kibana. `png` is fine for other images, this only applies to the integration logo.
Updated the generic guidelines to mandate use of `svg` images for Integration logo after observing that `png` crashes the Integrations browser
*this is a change to docs, not a new integration*
> Mandate SVG logo in docs

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
- packages/kubernetes/manifest.yml
This is part of the fix for data duplication that happens when there
are multiple filestream inputs configured with the same ID.
- Relates https://github.com/elastic/beats/issues/31512
> add container ID as part of Kubernetes Cotainer Logs filestream input

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
This attempt to enrich user details from the event_data.MemberSid field if possible and the information is not othewise available.
- Closes #3309
> windows: enrich user details from MemberSid where possible

- .ci/Jenkinsfile
Issue: https://github.com/elastic/ingest-dev/issues/1119
This PR modifies the Jenkins CI pipeline to publish packages to Package Storage v2.
Unfortunately, we can't run sign&publish for every package due to the DoS effect/fail2ban, but we need to prepare packages in a batch to pass them to the Elastic signing job.  
As a result of running the CI job, all packages stored in Integrations will be pushed to the v2 storage.
> Publish package to the Package Storage v2

- .ci/Jenkinsfile
- .ci/schedule-daily.groovy
This PR increases timeout for CI jobs to manage to finish package publishing to Package Storage v2.
Related: https://github.com/elastic/integrations/pull/3658
> Fix: increase CI job timeout due to publishing

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/docs/README.md
- packages/cloud_security_posture/manifest.yml
Update the cloud security posture package README - remove the Kibana configuration instructions (since the Kibana plugin is enabled by default for 8.4)
> [Cloud Posture] Remove Kibana configuration from README

- packages/tcp/changelog.yml
- packages/tcp/data_stream/generic/manifest.yml
- packages/tcp/manifest.yml
- packages/udp/changelog.yml
- packages/udp/data_stream/generic/manifest.yml
- packages/udp/manifest.yml
- Clarified description text to include RFC 3164 and 5424 as supported formats
- Closes #3731
> [tcp/udp] Improve syslog parsing description

- packages/system/changelog.yml
- packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-expected.json
- packages/system/data_stream/auth/_dev/test/pipeline/test-multiline.log
- packages/system/data_stream/auth/_dev/test/pipeline/test-multiline.log-config.yml
- packages/system/data_stream/auth/_dev/test/pipeline/test-multiline.log-expected.json
- packages/system/data_stream/auth/agent/stream/log.yml.hbs
- packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/auth/manifest.yml
- packages/system/manifest.yml
This adds config options for tags, processors, and preserve original event to the system.auth data stream.
It improves the pipeline by splitting the main grok processor into two operations. First it groks the header common to all messages. Then the second grok extracts information from a specific set of messages. Previously all of the patterns in the single grok shared the same header so the the header was being parsed multiple times while trying to find a matching pattern. Additionally the patterns where not anchored so those were added.
I added a convert processor to check the `source.ip` for validity.
I added an `if` condition to the script processor to prevent `cannot access method/field [event] from a null def reference` errors that were being ignored with `ignore_failure: true`.
- …
> [system.auth] Split grok parsing, add tags/processors/preserve_original_event

- .ci/Jenkinsfile
This PR fixes the issue with broken pipelines when there is nothing to be published. The signing pipeline shouldn't be called.
> Fix: don't call signing if nothing to published

- packages/gcp/changelog.yml
- packages/gcp/manifest.yml
As https://github.com/elastic/kibana/pull/136289 has been merged we can re add compatibility for this package to 7.17 track.
- Closes #3714
> [GCP] add back compatibility to 7.17 track

- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_umbrella/data_stream/log/fields/ecs.yml
- packages/cisco_umbrella/docs/README.md
- packages/cisco_umbrella/manifest.yml
Enriches the `dns` fields from `dns.question.name` to `dns.question.registered_domain`, `dns.question.top_level_domain` and `dns.question.sudomain`.
> [cisco_umbrella] Enrich DNS fields

- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
- packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/audit/sample_event.json
- packages/gcp/data_stream/dns/sample_event.json
- packages/gcp/data_stream/firewall/sample_event.json
- packages/gcp/data_stream/vpcflow/sample_event.json
- packages/gcp/docs/README.md
- packages/gcp/docs/audit.md
- packages/gcp/docs/dns.md
- packages/gcp/docs/firewall.md
- packages/gcp/docs/vpcflow.md
- packages/gcp/manifest.yml
This resolves a set of TODOs by removing duplicated fields.
- Closes #3397
> gcp: remove gcp.audit.* fields duplicated in ECS fields

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/sip/agent/stream/sip.yml.hbs
- packages/network_traffic/data_stream/sip/manifest.yml
- packages/network_traffic/manifest.yml
Exposes the newly added TCP transport option to the sip protocol.
> [network_traffic] Add option to use TCP for the SIP protocol.

- packages/gcp/changelog.yml
- packages/gcp/data_stream/compute/manifest.yml
- packages/gcp/manifest.yml
While testing the `gcp` integration I noticed there have been a regression in the GCP Billing policy templated (incorrectly named `Billine`), and found a bug in the GCP Compute default `period` value (which was `10s` when the minimum acceptable in Metricbeat is `60s`; this produces an error if trying to run the default configuration).
-
> Fix a typo and a bug in `gcp` integration package

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/system/test-logfile-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-tcp-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-tls-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-udp-config.yml
- packages/panw/data_stream/panos/agent/stream/tcp.yml.hbs
- packages/panw/data_stream/panos/agent/stream/udp.yml.hbs
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
- packages/panw/manifest.yml
- Add processor to preserve original event message when using tcp/udp
with syslog in agent config
```
cd packages/panw && elastic-package test
```
- Closes #3774
> [panw] Preserve original event for syslog messages

- packages/postgresql/changelog.yml
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-aws.log
- packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-aws.log-expected.json
- packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-aws-log.yml
- packages/postgresql/manifest.yml
This PR is to add support for brackets around `user.name` and `postgresql.log.database` in ingest pipeline for parsing AWS RDS Postgresql logs.
> Fix pipeline when user.name and postgresql.log.database with brackets

- docs/how_to_test_new_indexing_features.md
Update the docs about enabling synthetic source due to a recent change in Elasticsearch.
See https://github.com/elastic/elasticsearch/pull/88211
> docs: update instructions for synthetic source

- packages/azure/_dev/build/docs/README.md
- packages/azure/_dev/build/docs/activitylogs.md
- packages/azure/_dev/build/docs/adlogs.md
- packages/azure/_dev/build/docs/eventhub.md
- packages/azure/_dev/build/docs/firewall_logs.md
- packages/azure/_dev/build/docs/platformlogs.md
- packages/azure/_dev/build/docs/springcloudlogs.md
- packages/azure/changelog.yml
- packages/azure/docs/README.md
- packages/azure/docs/activitylogs.md
- packages/azure/docs/adlogs.md
- packages/azure/docs/eventhub.md
- packages/azure/docs/firewall_logs.md
- packages/azure/docs/platformlogs.md
- packages/azure/docs/springcloudlogs.md
- packages/azure/manifest.yml
Currently, Elastic Agent collects Azure logs running Filebeat behind the scenes. The current Filebeat implementation design requires using one event hub for each log type and [today's Filebeat documentation](https://www.elastic.co/guide/en/beats/filebeat/8.3/filebeat-module-azure.html) reports that.
This PR adds the same Event Hub configuration recommendations for Azure Logs integrations.
I am adding this information because multiple people have asked this question lately.
> [Azure Logs] Add recommendations for event hub configuration

- packages/awsfargate/changelog.yml
- packages/awsfargate/data_stream/task_stats/fields/fields.yml
- packages/awsfargate/data_stream/task_stats/sample_event.json
- packages/awsfargate/docs/README.md
- packages/awsfargate/manifest.yml
This PR adds DesiredStatus and KnownStatus among the collected metrics for ECS Fargate. The values are collected at the task level, not at the container level. More info at: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html
Related PR for beats https://github.com/elastic/beats/pull/32342
To test the end-to-end data flow, the easiest approach involves running [amazon-ecs-local-container-endpoints](https://github.com/awslabs/amazon-ecs-local-container-endpoints) and elastic-agent in two Docker containers on the same network (more info available at this [blog post from AWS](https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/))
- Closes …
> [AWS Fargate] Added support for DesiredStatus and KnownStatus for ECS Tasks

- packages/cisco_duo/changelog.yml
- packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/admin/sample_event.json
- packages/cisco_duo/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/auth/sample_event.json
- packages/cisco_duo/data_stream/offline_enrollment/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/offline_enrollment/sample_event.json
- packages/cisco_duo/data_stream/summary/_dev/test/pipeline/test-summary.log-expected.json
- packages/cisco_duo/data_stream/summary/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/summary/sample_event.json
- packages/cisco_duo/data_stream/telephony/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_duo/data_stream/telephony/sample_event.json
- packages/cisco_duo/docs/README.md
- packages/cisco_duo/manifest.yml
Type of change
- Enhancement
This PR adds support for handling bad values in ip and date fields.
- Closes https://github.com/elastic/integrations/issues/3696
> [cisco_duo] Fix bad value in ip and date fields

- packages/aws/changelog.yml
- packages/aws/data_stream/dynamodb/agent/stream/stream.yml.hbs
- packages/aws/data_stream/dynamodb/fields/package-fields.yml
- packages/aws/data_stream/dynamodb/sample_event.json
- packages/aws/data_stream/usage/agent/stream/stream.yml.hbs
- packages/aws/data_stream/usage/fields/package-fields.yml
- packages/aws/data_stream/usage/sample_event.json
- packages/aws/docs/dynamodb.md
- packages/aws/docs/usage.md
- packages/aws/manifest.yml
This PR is to move lightweight module configuration from metricbeat into integrations for usage.
closes https://github.com/elastic/integrations/issues/3606 
closes https://github.com/elastic/integrations/issues/3597
> [AWS] Move usage lightweight module config into integration

- packages/aws/changelog.yml
- packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-cloudwatch.yml.hbs
- packages/aws/manifest.yml
Bug
Fix data_stream.dataset indentation on cloudwatch_logs `aws-cloudwatch.yml.hbs`
-
> Fix data_stream.dataset indentation on cloudwatch_logs integration

- packages/elastic_package_registry/changelog.yml
- packages/elastic_package_registry/data_stream/metrics/manifest.yml
- packages/elastic_package_registry/manifest.yml
Remove release experimental field, to just depend on semantic versioning.
- Relates https://github.com/elastic/package-registry/issues/797
> Remove release experimental, depend just on semver

- packages/aws/changelog.yml
- packages/aws/data_stream/transitgateway/agent/stream/stream.yml.hbs
- packages/aws/data_stream/transitgateway/fields/fields.yml
- packages/aws/data_stream/transitgateway/fields/package-fields.yml
- packages/aws/data_stream/transitgateway/sample_event.json
- packages/aws/docs/transitgateway.md
- packages/aws/manifest.yml
This PR is to move lightweight module configuration from Metricbeat into integrations for Transit Gateway.
- Closes #3605
> [AWS] Move transit gateway lightweight module config into integration

- packages/aws/changelog.yml
- packages/aws/data_stream/natgateway/agent/stream/stream.yml.hbs
- packages/aws/data_stream/natgateway/sample_event.json
- packages/aws/docs/natgateway.md
- packages/aws/manifest.yml
This PR is to move lightweight module configuration from Metricbeat into integrations for NATGateway.
- Closes #3600
> [AWS] Move natgateway lightweight module config into integration

- packages/apache/changelog.yml
- packages/apache/manifest.yml
`license` field is deprecated as of https://github.com/elastic/package-spec/pull/355, use the new fields in the apache package.
- Related to https://github.com/elastic/package-spec/issues/298
> [Apache] Use new labels for license and subscription

- packages/infoblox_nios/_dev/build/build.yml
- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log-expected.json
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
- packages/infoblox_nios/data_stream/log/fields/fields.yml
- packages/infoblox_nios/docs/README.md
- packages/infoblox_nios/manifest.yml
- update infoblox_nios to ECS 8.4.0
- switch to ECS allowed values in `dns.header_flags`, original values are now in `infoblox_nios.log.dns.header_flags`
Closes #3884
> [infoblox_nios] Update ECS to 8.4.0

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/manifest.yml
This PR fixes a problem that the Prometheus package has to ingest histogram data type
I've tried different approaches but this one seems to be the only one that works. 
* Install Prometheus or use a docker container
a. I've used a docker image following this [doc](https://prometheus.io/docs/prometheus/latest/installation/) and [this](https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml) example for the `prometheus.yml` config file
b. Make sure that http://localhost:9090/metrics has data
* Install the Prometheus integration
a. If using docker, run ` docker run -it --rm alpine nslookup host.docker.internal  ` to retrieve the host
b. **DISABLE** the Leader Election option (it seems that we have a bug here too)
c. Clear all authentication fields 
Closes …
> [Prometheus] Add dynamic mapping to fix prometheus histogram type

- packages/aws_logs/_dev/build/docs/README.md
Added new content based on the new documentation guidelines
>
> Update Readme - First draft of AWS integration edits

- packages/aws/_dev/build/docs/waf.md
>
In the logs section before I made my revisions, was this sentence:
_Export logs from Kinesis Data Firehose to Amazon S3 bucket which has SQS notification setup …
> Update WAF - First draft of AWS integration edits

- packages/aws/_dev/build/docs/vpcflow.md
> Update vpcflow.md - First draft of AWS integration edits

- packages/aws/_dev/build/docs/usage.md
> Update AWS Usage - First draft of AWS integration edits

- packages/aws/_dev/build/docs/sns.md
> Update SNS - First draft of AWS integration edits

- packages/aws/_dev/build/docs/s3_storage_lens.md
>  Update S3 Storage Lens- First draft of AWS integration edits

- packages/aws/_dev/build/docs/s3.md
> Update S3 - First draft of AWS integration edits

- packages/aws/_dev/build/docs/route53.md
> Update Route 53 -  First draft of AWS integration edits
