- packages/nagios_xi/changelog.yml
- packages/nagios_xi/data_stream/events/agent/stream/stream.yml.hbs
- packages/nagios_xi/data_stream/host/agent/stream/stream.yml.hbs
- packages/nagios_xi/data_stream/service/agent/stream/stream.yml.hbs
- packages/nagios_xi/manifest.yml
> nagios_xi: add support for http request trace logging

- packages/aws/changelog.yml
- packages/aws/data_stream/billing/manifest.yml
- packages/aws/manifest.yml
Disables TSDB on AWS Billing.
The reason for this decision is explained [in this issue](https://github.com/elastic/integrations/issues/7345).
We need to add this changes on version `1.46` so this can take effect on the same Kibana version the changes were first introduced.
> [AWS] Disable TSDB on AWS Billing

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
We want the project id to be missing in case of a cloudshell deployment. 
When deploying the agent through GCP Cloud Shell, the Project ID is not provided, Cloudbeat detects this and  takes action by retrieving the Project ID from the associated service account of the instance. This ensures that the necessary Project ID is acquired and utilized.
Fix the following error:
```
[elastic_agent.cloudbeat][error] Exiting: launcher could not run Beater: could not create beater: failed to get GCP identity: unable to get project with id 'projects/SET_PROJECT_NAME': googleapi: Error 400: Fail to resolve resource 'projects/SET_PROJECT_NAME', badRequest
```
> [Cloud Security] Update GCP's policy manifest

- packages/lastpass/changelog.yml
- packages/lastpass/data_stream/event_report/_dev/test/pipeline/test-event-report.log-expected.json
- packages/lastpass/data_stream/event_report/_dev/test/system/test-default-config.yml
- packages/lastpass/data_stream/event_report/agent/stream/httpjson.yml.hbs
- packages/lastpass/data_stream/event_report/elasticsearch/ingest_pipeline/default.yml
- packages/lastpass/data_stream/event_report/manifest.yml
- packages/lastpass/data_stream/event_report/sample_event.json
- packages/lastpass/docs/README.md
- packages/lastpass/manifest.yml
The LastPass documentation states that the timezone for events will be US/Eastern, but we have user reports of events with other timezones, so allow user configuration.
Also fix `event.type` value for authentication which was not one of the acceptable values.
-
> lastpass: allow users to specify time zone for event_report events

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Adds more organization-level read permissions
This will future-proof our CloudFormation template for future changes like https://github.com/elastic/cloudbeat/issues/1177 and https://github.com/elastic/cloudbeat/issues/1214 that will require more permissions in the organization level. After merging those, newer CloudFormation templates can trim down the required permissions again.
- Relates https://github.com/elastic/cloudbeat/pull/1226
> [Cloud Security] Update CSPM url

- packages/kibana/changelog.yml
- packages/kibana/manifest.yml
This PR adds the `basepath` setting inside the Kibana integration
- Go to `integrations/packages/kibana`
- Follow [this test guide](https://github.com/elastic/elastic-package/blob/main/docs/howto/install_package.md#kibana--870)
- Open kibana integration installation page and check for basepath (https://127.0.0.1:5601/app/fleet/integrations/kibana-2.3.6/add-integration)
- Closes [#7359](https://github.com/elastic/integrations/issues/7359)
> [Kibana] Add missing "basepath" variable in Kibana integration settings

- packages/cisco_ise/_dev/deploy/docker/docker-compose.yml
- packages/cisco_ise/changelog.yml
- packages/cisco_ise/data_stream/log/_dev/test/system/test-filestream-config.yml
- packages/cisco_ise/data_stream/log/agent/stream/filestream.yml.hbs
- packages/cisco_ise/data_stream/log/fields/ecs.yml
- packages/cisco_ise/data_stream/log/manifest.yml
- packages/cisco_ise/docs/README.md
- packages/cisco_ise/manifest.yml
> cisco_ise: add support for filestream input

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log-expected.json
- packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/flows.yml
- packages/cisco_meraki/manifest.yml
Cisco has changed the event_type for flow/ruleset logs, from flows to multiple other types. See the info box in the "Flows" paragraph in [documentation](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Server_Overview_and_Configuration), and the list of [event_types](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples) This causes the logs-cisco_meraki.log pipeline to skip the logs-cisco_meraki.log-flows pipeline.
The flows pipeline also needs updating to correctly parse the new event types.
- Closes #7387
> [cisco_meraki] Address the changes in Firmware MX18.101

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
- packages/o365/data_stream/audit/manifest.yml
- packages/o365/manifest.yml
Fixes the following issue:
- Whenever an error (user configured, such as insufficient token permissions, setting `initial_interval` longer than 7 days which is unsupported by API) occurred inside the CEL program the timestamps are saved in its state. If the error is resolved after few days the CEL program tries to fetch the data starting from the saved timestamp which could now be more than 7 days ago. However, based on API spec, the `startTime` parameter shouldn't be more than 7 days old.
- [API reference](https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#:~:text=Both%20must%20be%20specified%20(or%20both%20omitted)%20and%20they%20must%20be%20no%20more%20than%2024%20hours%20apart%2C%20with%20the%20start%20time%20no%20more%20than …
> [O365] Fix API timestamp issue in CEL program

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/f621a5a40490219314098fa5753acc0e14187daf
* https://github.com/elastic/ia-trade-team/issues/154
None
> [Security Rules] Update security rules package to v8.7.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3bd648b243882f1cd548203f3678ab3277fa8b05
* https://github.com/elastic/ia-trade-team/issues/154
None
> [Security Rules] Update security rules package to v8.8.9

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/eae72cf90f921e1300ebfaad813c0d1d6b54f8c8
* https://github.com/elastic/ia-trade-team/issues/154
None
> [Security Rules] Update security rules package to v8.9.4

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/44ac8f762d9805223201658762bfe92ae420d042
* https://github.com/elastic/ia-trade-team/issues/154
None
> [Security Rules] Update security rules package to v8.10.1

- packages/cisco_secure_email_gateway/changelog.yml
- packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_secure_email_gateway/manifest.yml
Adjust a Grok pattern applied to `log.file.path` so that it matches Windows-style paths like `V:\\DATA\\mail_logs.@20230817T054656.s` as well as Unix-style paths like `/data/mail_logs.@20230817T054656.s`.
Doesn't break existing tests:
```
cd packages/cisco_secure_email_gateway
```
- Relates https://github.com/elastic/sdh-beats/issues/3729
> [cisco_secure_email_gateway] Match both Unix and Windows-style paths

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
> cisco_ios: support ingesting NTP log messages

- packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs
- packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
- packages/aws_logs/data_stream/generic/manifest.yml
Addresses two distinct problems happening to the CloudWatch and S3 integrations.
In a previous [PR](https://github.com/elastic/integrations/pull/5794/), I added an extra `number_of_workers` advanced configuration setting by mistake while adding it to a group of CloudWatch-based integrations missing it.
This change applies to following changes:
- Removes the extra definition.
- Reuse the later setting description because it contains more details.
If we set the "Bucket List Prefix" option, the `number_of_workers` is defined twice creating the "duplicated mapping key" error.
This PR re-groups the S3 settings to avoid defining the `number_of_workers` setting multiple times.
TBA
> [AWS] Remove duplicated `number_of_workers` settings from the custom logs integration

- packages/atlassian_confluence/changelog.yml
- packages/atlassian_confluence/data_stream/audit/agent/stream/stream.yml.hbs
- packages/atlassian_confluence/data_stream/audit/manifest.yml
- packages/atlassian_confluence/manifest.yml
Enhancement - Adds support for setting [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) to Atlassian Confluence Log File integration. This allows for defining this integration in a policy, but only having it run on during specific condition.
Install new version, confirm that condition field is available and can be set.
-
> [Atlassian Confluence] Add `condition` support to Confluence Log File Integration

- packages/atlassian_bitbucket/changelog.yml
- packages/atlassian_bitbucket/data_stream/audit/agent/stream/stream.yml.hbs
- packages/atlassian_bitbucket/data_stream/audit/manifest.yml
- packages/atlassian_bitbucket/manifest.yml
Enhancement - Adds support for setting [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) to Atlassian Bitbucket Log File integration. This allows for defining this integration in a policy, but only having it run on during specific conditions.
Install new version, confirm that `condition` field is available and can be set.
-
> [Atlassian Bitbucket] Add `condition` support to Bitbucket Log File Integration

- packages/aws/changelog.yml
- packages/aws/data_stream/ec2_metrics/fields/ecs.yml
- packages/aws/data_stream/ec2_metrics/fields/fields.yml
- packages/aws/docs/ec2.md
- packages/aws/manifest.yml
Set the dimension fields for EC2 data stream.
All `dimension.*` fields in `fields.yml` are dimensions.
For the ecs fields, the reasoning for the fields can be found in [this comment](https://github.com/elastic/integrations/issues/5193#issuecomment-1536090359).
Result of successful [testing](https://github.com/elastic/TSDB-migration-test-kit):
```
All 130 documents taken from index .ds-metrics-aws.ec2_metrics-default-2023.08.22-000001 were successfully placed to index tsdb-index-enabled.
```
> [AWS] Add dimensions to EC2 data stream.

- packages/aws_logs/changelog.yml
- packages/aws_logs/manifest.yml
Update the changelog to release a new version of the Custom AWS Logs integration.
In the previous PR, missed updating the changelog before merging the PR 🤦  ; the whole purpose of this PR is to release #7319.
> [AWS] Remove duplicated number_of_workers settings from the custom logs integration (part 2)

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/vulnerabilities/fields/cloud.yml
- packages/cloud_security_posture/data_stream/vulnerabilities/fields/vulnerability.yml
- packages/cloud_security_posture/manifest.yml
Fixing capitalized value and changing type of tags to objects list
> [cloud_security_posture] Fixing vulnerability mappings

- packages/aws/changelog.yml
- packages/aws/data_stream/ec2_metrics/fields/fields.yml
- packages/aws/docs/ec2.md
- packages/aws/manifest.yml
Add metric type to EC2.
All metrics are `gauge` since they are all computed as aggregations. 
There are a few numeric fields (example `instance.state.code`) that I did not mark as a metric, since they seem to be all constant.
> [AWS][EC2] Add metric type to EC2

- packages/couchbase/changelog.yml
- packages/couchbase/data_stream/cluster/fields/ecs.yml
- packages/couchbase/docs/README.md
- packages/couchbase/manifest.yml
- Enhancement
Add dimensions to `bucket` datastream
1. Build verification
`elastic-package build`
`elastic-package stack up -v -d --services package-registry`
- Relates #7378
> [Couchbase] Add dimensions mapping to cluster datastream

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/manifest.yml
Upgrades osquery mappings to match osquery 5.8.2 schema
- Requires https://github.com/elastic/beats/pull/36133
> Osquery_manager: Upgrade osquery mappings to match osquery 5.8.2 schema

- packages/gcp/changelog.yml
- packages/gcp/kibana/dashboard/gcp-8f9c6cc0-909d-11ea-8180-7b0dacd9df87.json
- packages/gcp/manifest.yml
- High
- Enhancement
- Manually migrate `GCP Load Balancing L3` visualizations to the lens in the current Kibana version `8.7.1` itself. 
- Statistics for `GCP Load Balancing TCP L3` Lens migration:
<html>
<body>
  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Vizualization | Old Control panels | Lens | Vizualization | New Input controls
[Metrics GCP] Load Balancing L3 Overview | 0 | 4 | 1 | 4 | 0 | 1
</div></div><br class="Apple-interchange-newline">
</body>
</html>
- Relates #7256
> [O11y][GCP] Migrate GCP Load Balancing L3 Overview dashboard to lens

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-sysmon-operational-events.json-expected.json
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml
- packages/windows/data_stream/forwarded/fields/winlog.yml
- packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/fields/winlog.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
See title. The field is retained because it may contain information that is useful.
The `winlog.event_data.Detail` field is dropped from the definitions as it is not used and is likely there as a typo of `….Details`.
- Closes #7310
> windows: retain winlog.event_data.Details

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-sysmon-operational-events.json-expected.json
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell_operational.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml
- packages/windows/data_stream/forwarded/sample_event.json
- packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell/sample_event.json
- packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell_operational/sample_event.json
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/sample_event.json
- packages/windows/docs/README.md
- packages/windows/manifest.yml
> windows: reconcile forwarded event pipelines with their non-forwarded equivalents

- packages/cloud_defend/changelog.yml
- packages/cloud_defend/manifest.yml
Updates documentation to reflect available "process blocking" feature.
Original change: https://github.com/elastic/integrations/pull/6987
> [Cloud Security] D4C v1.2.0 (documentation update)

- packages/gcp/changelog.yml
- packages/gcp/data_stream/cloudsql_mysql/fields/fields.yml
- packages/gcp/data_stream/cloudsql_postgresql/fields/fields.yml
- packages/gcp/data_stream/cloudsql_sqlserver/fields/fields.yml
- packages/gcp/docs/cloudsql.md
- packages/gcp/manifest.yml
Metric type of GCP CloudSQL metrics can be found [here](https://cloud.google.com/sql/docs/mysql/admin-api/metrics).
Set the metric type for:
Changes:
1. Switch every delta metric marked as `counter` to `gauge`.
- Related issue for delta metrics: https://github.com/elastic/elasticsearch/issues/98171
2. Add metric type to the metrics without type.
Relates to https://github.com/elastic/integrations/issues/7555.
> [GCP][CloudSQL] Set metric type

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/kibana/dashboard/azure_metrics-d8e3c5f0-feaf-11eb-8fff-87871c582eca.json
- packages/azure_metrics/manifest.yml
- High
- Enhancement
- Manually migrate `Compute VM Guest Linux Metrics` visualizations to the lens in the current Kibana version `8.4.0` itself. 
- Statistics for `Compute VM Guest Linux Metrics` Lens migration:
<html>
<body>
  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Visualization | Old Input Controls | Lens | Visualization | New control panels
[Azure Metrics] Compute VM Guest Linux Metrics Overview | 0 | 9 | 1 | 9 | 0 | 1
</body>
</html>
- Relates #7433
Before Migration
After Migration
> [O11y][Azure Metrics] Migrate Compute VM Guest Linux Metrics Overview dashboard to lens

- packages/php_fpm/_dev/build/docs/README.md
- packages/php_fpm/changelog.yml
- packages/php_fpm/data_stream/pool/fields/ecs.yml
- packages/php_fpm/data_stream/process/fields/ecs.yml
- packages/php_fpm/docs/README.md
- packages/php_fpm/manifest.yml
- Bug
Added host.ip field in ecs.yml and added re-indexing steps to resolve conflicts for existing users.
- Closes #7212
- Relates #7211
> [O11y][PHP-FPM] Resolve the conflict in host.ip field

- packages/golang/_dev/build/docs/README.md
- packages/golang/changelog.yml
- packages/golang/data_stream/expvar/fields/ecs.yml
- packages/golang/data_stream/heap/fields/ecs.yml
- packages/golang/docs/README.md
- packages/golang/manifest.yml
- Bug
Added host.ip field in ecs.yml and added re-indexing steps to resolve conflicts for existing users.
- Closes #7240 
- Relates #7239
> [O11y][GoLang] Resolve the conflict in host.ip field

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
- packages/o365/manifest.yml
The default limit in the Filebeat input is 1MiB which is too small for some responses, resulting in loss of visibility in debugging issues in the integration, so increase to 5MiB.
-
> o365: increase CEL resource.tracer.maxsize limit

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
> cisco_asa: add support for unspecified reason AAA user authentication rejection

- packages/fortinet_fortigate/_dev/build/docs/README.md
- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/data_stream/log/manifest.yml
- packages/fortinet_fortigate/docs/README.md
- packages/fortinet_fortigate/manifest.yml
- It enables the RFC 6587 by default on the TCP input. Regarding the [Fortigate reference](https://docs.fortinet.com/document/fortigate/7.4.0/cli-reference/405620/config-log-syslogd-setting), when the syslog mode is set to `reliable`, it uses RFC 6587 for TCP forwarding.
- Added a note in the docs, just in case it would help users to be warned about this.
The framing value has been set to `rfc6587` by default because I assume that the reliable mode should be the default one when forwarding over TCP syslog from Fortigate, the other available option is `legacy-reliable`.
> [Fortinet Fortigate] Change default TCP framing to RFC 6587

- packages/cisco_secure_email_gateway/changelog.yml
- packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_secure_email_gateway/manifest.yml
This fixes the change attempted in https://github.com/elastic/integrations/pull/7452. The problem was insufficient escaping.
Here's a summary of the various versions:
```
Original pattern raw:
^%{DATA}/%{WORD:cisco_secure_email_gateway.log.category.name}.@%{GREEDYDATA}.s$
Fixed pattern raw:
^%{DATA}/[\\/]%{WORD:cisco_secure_email_gateway.log.category.name}.@%{GREEDYDATA}.s$
Assumed fixed pattern as the broken string:
"^%{DATA}[\\/]%{WORD:cisco_secure_email_gateway.log.category.name}.@%{GREEDYDATA}.s$"
Assumed fixed pattern, raw from the broken string:
^%{DATA}[\/]%{WORD:cisco_secure_email_gateway.log.category.name}.@%{GREEDYDATA}.s$
Actually fixed pattern as the correct string:
"^%{DATA}[\\\\/]%{WORD:cisco_secure_email_gateway.log.category.name}.@%{GREEDYDATA}.s$"
Actually fixed pattern, …
```
> [cisco_secure_email_gateway] Correct escaping to match both Unix and Windows-style paths

- packages/ti_otx/changelog.yml
- packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-no-preserve-ndjson.log-expected.json
- packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-sample-ndjson.log-expected.json
- packages/ti_otx/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/ti_otx/data_stream/threat/sample_event.json
- packages/ti_otx/docs/README.md
- packages/ti_otx/manifest.yml
- Ensure event.category is an array
- Ensure event.type is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.10.0 packages/ti_otx
```
> [ti_otx] - update package-spec to 2.10.0

- packages/ti_threatq/changelog.yml
- packages/ti_threatq/data_stream/threat/_dev/test/pipeline/test-threatq-no-preserve-ndjson.log-expected.json
- packages/ti_threatq/data_stream/threat/_dev/test/pipeline/test-threatq-sample-ndjson.log-expected.json
- packages/ti_threatq/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/ti_threatq/data_stream/threat/sample_event.json
- packages/ti_threatq/docs/README.md
- packages/ti_threatq/manifest.yml
- Ensure event.category is an array
- Ensure event.type is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.10.0 packages/ti_threatq
```
> [ti_threatq] - update package-spec to 2.10.0

- packages/pfsense/changelog.yml
- packages/pfsense/data_stream/log/fields/fields.yml
- packages/pfsense/data_stream/log/sample_event.json
- packages/pfsense/docs/README.md
- packages/pfsense/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.10.0 packages/pfsense
```
> [pfsense] - update package-spec to 2.10.0

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/container_service/_dev/test/pipeline/test-azure-container-service.json
- packages/azure_metrics/data_stream/container_service/_dev/test/pipeline/test-azure-container-service.json-expected.json
- packages/azure_metrics/data_stream/container_service/elasticsearch/ingest_pipeline/default.yml
- packages/azure_metrics/manifest.yml
Since values from Azure come in lowercase and capitalized versions (e.g., True/true/False/false), we picked lowercase as canonical case for these values.
- Closes #7220
Before:
After normalization:
> [Azure] [Container Service] Normalize azure.dimensions.status metric values to lowercase

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/auditbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_logs/fields/fields.yml
- packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
- packages/elastic_agent/manifest.yml
This adds more in depth metrics for viewing output batches sizes, batches/sec, and input queue sizes. This helps with tuning `workers` and `bulk_max_size` to avoid filling up the queues.
For the input queue metrics, we currently only have this data on the `logs-elastic_agent.*beat-*` data streams, rather than on the `metrics-*` data streams. Fixing this requires some fixes in Agent and I'd like to get value out on this sooner, so I'm deciding to map these fields for now on `logs` and we'll fix later (opened https://github.com/elastic/elastic-agent/issues/3334) on a future Agent version.
@elastic/elastic-agent-data-plane I would like confirmation that I am interpreting this metric fields correctly.
`elastic-package stack up && elastic-package build && elastic-package install`
Go to Fleet …
> [Elastic Agent] Add queue depth, output batch size and rate

- packages/ti_rapid7_threat_command/changelog.yml
- packages/ti_rapid7_threat_command/data_stream/alert/sample_event.json
- packages/ti_rapid7_threat_command/data_stream/ioc/fields/fields.yml
- packages/ti_rapid7_threat_command/data_stream/ioc/sample_event.json
- packages/ti_rapid7_threat_command/data_stream/vulnerability/sample_event.json
- packages/ti_rapid7_threat_command/docs/README.md
- packages/ti_rapid7_threat_command/manifest.yml
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.10.0 packages/ti_rapid7_threat_command
```
> [ti_rapid7_threat_command] - update package-spec to 2.10.0

- packages/forgerock/changelog.yml
- packages/forgerock/data_stream/am_access/sample_event.json
- packages/forgerock/data_stream/am_activity/sample_event.json
- packages/forgerock/data_stream/am_authentication/sample_event.json
- packages/forgerock/data_stream/am_config/_dev/test/pipeline/test-am-config.log-expected.json
- packages/forgerock/data_stream/am_config/elasticsearch/ingest_pipeline/default.yml
- packages/forgerock/data_stream/am_config/sample_event.json
- packages/forgerock/data_stream/am_core/sample_event.json
- packages/forgerock/data_stream/idm_access/sample_event.json
- packages/forgerock/data_stream/idm_activity/sample_event.json
- packages/forgerock/data_stream/idm_authentication/sample_event.json
- packages/forgerock/data_stream/idm_config/sample_event.json
- packages/forgerock/data_stream/idm_core/sample_event.json
- packages/forgerock/data_stream/idm_sync/sample_event.json
- packages/forgerock/docs/README.md
- packages/forgerock/manifest.yml
- Ensure event.category is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.10.0 packages/forgerock
```
> [forgerock] - update package-spec to 2.10.0

- packages/statsd_input/changelog.yml
- packages/statsd_input/manifest.yml
Adds changelog entry for https://github.com/elastic/integrations/pull/6580 as it was not done in that PR.
> statsd_input: Add changelog entry for PR #6580

- packages/iis/changelog.yml
- packages/iis/data_stream/access/agent/stream/log.yml.hbs
- packages/iis/data_stream/application_pool/agent/stream/stream.yml.hbs
- packages/iis/data_stream/error/agent/stream/log.yml.hbs
- packages/iis/data_stream/webserver/agent/stream/stream.yml.hbs
- packages/iis/data_stream/website/agent/stream/stream.yml.hbs
- packages/iis/manifest.yml
Enhancement - Adds support for setting [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) to both log file collection and metrics. This allows for defining this integration in a policy, but only having it run on during specific conditions.
Note: Log files share a top-level condition value, and metrics share a top-level condition.
Install new version, confirm that condition fields are available and can be set.
-
> [IIS] Add `condition` support to logs and metrics

- packages/apache/changelog.yml
- packages/apache/data_stream/access/agent/stream/log.yml.hbs
- packages/apache/data_stream/error/agent/stream/log.yml.hbs
- packages/apache/data_stream/status/agent/stream/stream.yml.hbs
- packages/apache/manifest.yml
Enhancement - Adds support for setting [`condition`](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) to both Log file collection and metrics. This allows for defining this integration in a policy, but only having it run on during specific conditions.
Note: Log file (access/error) share a top-level `condition` value, and metrics is an independent value.
Install new version, confirm that `condition` fields are available and can be set.
-
> [Apache] Add `condition` support to logs and metrics

- packages/citrix_adc/_dev/build/docs/README.md
- packages/citrix_adc/changelog.yml
- packages/citrix_adc/data_stream/interface/fields/ecs.yml
- packages/citrix_adc/data_stream/lbvserver/fields/ecs.yml
- packages/citrix_adc/data_stream/service/fields/ecs.yml
- packages/citrix_adc/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/citrix_adc/data_stream/system/fields/ecs.yml
- packages/citrix_adc/data_stream/vpn/fields/ecs.yml
- packages/citrix_adc/docs/README.md
- packages/citrix_adc/manifest.yml
- Bug
- Added host.ip field in ecs.yml to avoid field conflicts for users.
- Updated the condition in system datastream for ingest_pipeline.
- Closes https://github.com/elastic/integrations/issues/7282
- Relates https://github.com/elastic/integrations/issues/7243
> [O11y][Citrix ADC] Resolve the conflicts in host.ip field

- packages/qualys_vmdr/_dev/build/docs/README.md
- packages/qualys_vmdr/changelog.yml
- packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
- packages/qualys_vmdr/data_stream/asset_host_detection/manifest.yml
- packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
- packages/qualys_vmdr/data_stream/knowledge_base/agent/stream/input.yml.hbs
- packages/qualys_vmdr/data_stream/knowledge_base/elasticsearch/ingest_pipeline/default.yml
- packages/qualys_vmdr/data_stream/knowledge_base/fields/fields.yml
- packages/qualys_vmdr/data_stream/knowledge_base/manifest.yml
- packages/qualys_vmdr/data_stream/knowledge_base/sample_event.json
- packages/qualys_vmdr/docs/README.md
- packages/qualys_vmdr/kibana/dashboard/qualys_vmdr-017c0220-1001-11ee-b28e-615808a979fd.json
- packages/qualys_vmdr/kibana/dashboard/qualys_vmdr-686c4470-11b6-11ee-a722-91244a8ae892.json
- packages/qualys_vmdr/manifest.yml
Type of change
- Bug
- Replace `logs` keyword with `data`.
- Shift input parameter textbox from advance to main section in `manifest.yml` file.
- Error handling for different filter (input parameter) `details=None` in Knowledge Base data stream causes adding 2 more fields such as `id_range` and `ids`.
Move to integrations/packages/qualys_vmdr directory.
```elastic-package test```
- Closes https://github.com/elastic/infosec/issues/14223
```
[root@co7 qualys_vmdr]# elastic-package test -v
2023/08/28 15:26:32 DEBUG Enable verbose logging
2023/08/28 15:26:32  INFO New version is available - v0.85.0. Download from: …
```
> [qualys_vmdr] Update data collection of knowledge base data stream

- packages/couchbase/changelog.yml
- packages/couchbase/data_stream/database_stats/fields/ecs.yml
- packages/couchbase/data_stream/database_stats/fields/fields.yml
- packages/couchbase/docs/README.md
- packages/couchbase/manifest.yml
- Enhancement
Add dimensions to `database_stats` datastream
1. Build verification
`elastic-package build`
`elastic-package stack up -v -d --services package-registry`
- Relates #7378
> [Couchbase] Added dimensions mapping to database_stats datastream

- packages/netflow/_dev/build/build.yml
- packages/netflow/changelog.yml
- packages/netflow/manifest.yml
- packages/network_traffic/_dev/build/build.yml
- packages/network_traffic/changelog.yml
- packages/network_traffic/manifest.yml
- packages/suricata/_dev/build/build.yml
- packages/suricata/changelog.yml
- packages/suricata/manifest.yml
See title.
This is a counter proposal for #7271, #7273 and #7275.
/cc @MakoWish 
- Fixes #7270
- Closes #7271
- Fixes #7272
- Closes #7273
- Fixes #7274
- Closes #7275
> netflow,network_traffic,suricata: use dynamic field definitions

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/kibana/dashboard/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824.json
- packages/elastic_agent/kibana/dashboard/elastic_agent-1a4e7280-6b5e-11ed-98de-67bdecd21824.json
- packages/elastic_agent/kibana/dashboard/elastic_agent-a148dc70-6b3c-11ed-98de-67bdecd21824.json
- packages/elastic_agent/kibana/search/elastic_agent-462b68c0-b10b-11ed-957f-f1c897630287.json
- packages/elastic_agent/kibana/search/elastic_agent-522c9e20-ad53-11ed-957f-f1c897630287.json
- packages/elastic_agent/manifest.yml
Fixing couple of charts in the agent integration
Added a new dataset to include both metrics and logs data streams for the relevant charts
-
> Add a new dataset to include both metrics and logs for the active integrations and agent charts

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/fields/base-fields.yml
- packages/prometheus/data_stream/collector/fields/ecs.yml
- packages/prometheus/data_stream/query/fields/base-fields.yml
- packages/prometheus/data_stream/query/fields/ecs.yml
- packages/prometheus/data_stream/remote_write/fields/base-fields.yml
- packages/prometheus/data_stream/remote_write/fields/ecs.yml
- packages/prometheus/docs/README.md
- packages/prometheus/manifest.yml
1, There is no need to set `event.dataset` explicitly - this should be done on the elastic-agent side https://github.com/elastic/beats/pull/20076.
due to the existence of predefined value, there can happen this error:
```
{"type":"illegal_argument_exception","reason":"[constant_keyword] field [event.dataset] only accepts values that are equal to the value defined in the mappings [prometheus.collector], but got [prometheus.topolvm]"}}, dropping event!
```
Since the type defined for this field in ecs is `keyword`, I decided to switch to ecs definition.
- Closes https://github.com/elastic/integrations/issues/7654
> [prometheus] Use ecs definition of the 'event.dataset' field

- packages/entityanalytics_okta/changelog.yml
- packages/entityanalytics_okta/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
- packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
- packages/entityanalytics_okta/data_stream/user/fields/ecs.yml
- packages/entityanalytics_okta/data_stream/user/sample_event.json
- packages/entityanalytics_okta/docs/README.md
- packages/entityanalytics_okta/kibana/dashboard/entityanalytics_okta-e5242a60-0f35-11ee-8319-1d33c4a0c7ae.json
- packages/entityanalytics_okta/manifest.yml
Type of change
- Enhancement
- Add user.geo.\*, user.organization.\*, and asset categorization mappings.
- Move to integrations/packages/entityanalytics_okta directory.
```
2023/08/11 15:20:19 DEBUG Enable verbose logging
Run test suite for the package
Run static tests for the package
--- Test results for package: entityanalytics_okta - START ---
╭──────────────────────┬─────────────┬───────────┬──────────────────────────┬────────┬──────────────╮
│ PACKAGE              │ DATA STREAM │ TEST TYPE │ TEST NAME                │ RESULT │ TIME ELAPSED │
├──────────────────────┼─────────────┼───────────┼──────────────────────── …
```
> [entityanalytics_okta] Add the ECS mapping for entityanalytics_okta package.

- packages/aws/changelog.yml
- packages/aws/kibana/dashboard/aws-a4482820-03aa-11ee-84d4-7f15bab18041.json
- packages/aws/manifest.yml
- High
- Bugfix
Updates aggregation types in the metrics dashboard for AWS API Gateway to match the statistics used in the integration.
-
Example for [REST] Count.
Before:
After:
> [AWS] [API Gateway] Fix aggregation types for metrics dashboard

- packages/m365_defender/changelog.yml
- Bug
Looks like the wrong PR number was added to the link.
> [m365_defender] Correct link to PR - Update changelog.yml

- packages/airflow/changelog.yml
- packages/airflow/data_stream/statsd/fields/fields.yml
- packages/airflow/docs/README.md
- packages/airflow/kibana/dashboard/airflow-a3aa42d0-a465-11ed-9ff0-ab4dd59e4c75.json
- packages/airflow/manifest.yml
- Bug
This PR modifies the metric_type of `airflow.scheduler.heartbeat` from counter to gauge. Despite the field being labeled as a counter in the airflow [documentation](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/metrics.html#counters), the behavior of the values—consistently 1 or 2—suggests it aligns better with the characteristics of a gauge metric. 
Additionally,  dashboard is modified to accurately represent this data, with the aggregator function updated to use last_value.
- Relates #7504
> [Airflow] Remove metric_type mapping for 'airflow.scheduler.heartbeat' field and adjust the dashboard to visualize this 

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/43728cb8a3d62d95538e569d3b40badb4f8f2257
* https://github.com/elastic/ia-trade-team/issues/169
None
> [Security Rules] Update security rules package to v8.7.12

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/13af93785a8aad35ff26ef35b4cf191441167a22
* https://github.com/elastic/ia-trade-team/issues/169
None
> [Security Rules] Update security rules package to v8.9.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2e74d5095094a7d5913fd2592a77724b6f5fd440
* https://github.com/elastic/ia-trade-team/issues/169
None
> [Security Rules] Update security rules package to v8.10.2

- packages/aws/changelog.yml
- packages/aws/kibana/dashboard/aws-a4482820-03aa-11ee-84d4-7f15bab18041.json
- packages/aws/manifest.yml
1) Adds filter based on `aws.dimensions.Stage` to ensure that only documents containing this dimension are considered while visualizing the data. This is necessary due to an extra document currently being present in the metrics:
The `lucian-REST-PetStore` API has 2 stages (dev, prod), each with 32 and 64 aws.apigateway.metrics.Count.sum respectively, representing the number of requests made to them. 
However, another document is present in the metrics with the combined number of requests (96) which also has no `aws.dimensions.Stage` present.
A new issue will be made to document exactly why this additional document is being generated.
2) Adds control groups using `aws.dimensions.ApiId` (HTTP, WebSocket), `aws.dimensions.ApiName` (REST) and `aws.dimensions.Stage` (REST, HTTP and WebSocket). …
> [AWS] [API Gateway] Add dashboard filters, control groups and clean up

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/incident/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/manifest.yml
See title.
(The majority of the work fixing template snippets in m365_defender was done in #7522, so this is just to knock it on the head).
- For #7641
> m365_defender: fix template snippet escaping behaviour and add event.kind for pipeline errors

- packages/docker/_dev/build/docs/README.md
- packages/docker/changelog.yml
- packages/docker/docs/README.md
- packages/docker/manifest.yml
remove mention of windows support from docker documentation
> Remove confusing documentation about Windows support from docker integration

- packages/checkpoint/changelog.yml
- packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
- packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/checkpoint/data_stream/firewall/fields/fields.yml
- packages/checkpoint/docs/README.md
- packages/checkpoint/manifest.yml
- packages/github/changelog.yml
- packages/github/data_stream/dependabot/fields/fields.yml
- packages/github/docs/README.md
- packages/github/manifest.yml
- packages/hid_bravura_monitor/changelog.yml
- packages/hid_bravura_monitor/data_stream/winlog/fields/winlog.yml
- packages/hid_bravura_monitor/docs/README.md
- packages/hid_bravura_monitor/manifest.yml
Makes fields with the same name agree in type.
- Fixes #7708 
- Fixes #7709 
- Fixes #7710
> checkpoint,github,hid_bravura_monitor: make types match

- packages/oracle/changelog.yml
- packages/oracle/data_stream/performance/agent/stream/stream.yml.hbs
- packages/oracle/manifest.yml
- Bug
The query `SELECT name, physical_reads, db_block_gets, consistent_gets, 1 - (physical_reads / (db_block_gets + consistent_gets)) "Hit_Ratio" FROM V$BUFFER_POOL_STATISTICS` may result in error when `(db_block_gets + consistent_gets)` is zero.
- Closes https://github.com/elastic/sdh-beats/issues/3762
After the change
The PR is related to an SDH
> [Oracle] Resolve divisor error in performance datastream

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/cluster_stats/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/enrich/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_recovery/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/index_summary/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/ingest_pipeline/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/ml_job/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/node/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/node_stats/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/pending_tasks/agent/stream/stream.yml.hbs
- packages/elasticsearch/data_stream/shard/agent/stream/stream.yml.hbs
- packages/elasticsearch/manifest.yml
Closes https://github.com/elastic/integrations/issues/7377
Adds support for api_key authentication in elasticsearch integration
- create an api key and grab the beats format[1]
- configure elasticsearch integration to use that api_key instead of username/password
- elasticsearch data is successfully collecting documents and Stack Monitoring shows up. No authentication failure appears in elastic-agent logs/metrics-* data
[1]
> [elasticsearch] add api_key authentication

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Adds 2 new input vars: `organization_id` and `account_type`
closes https://github.com/elastic/integrations/issues/7398
> [Cloud Security] Add support for GCP org 

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Update the CloudFormation template to install cfn-signal for multiple linux distributions to keep the template backward compatible.
- Fixes: https://github.com/elastic/security-team/issues/7507
> [cloud_security_posture] Update CloudFormation cfn-signal installation (1.5)

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Update the CloudFormation template to install `cfn-signal` for multiple linux distributions to keep the template backward compatible.
- Fixes: https://github.com/elastic/security-team/issues/7507
> [cloud_security_posture] Update CloudFormation cfn-signal installation

- packages/ibmmq/_dev/deploy/docker/docker-compose.yml
- packages/ibmmq/changelog.yml
- packages/ibmmq/manifest.yml
- Bug
- This PR updates the docker image for IBM MQ. Refer to more details in this [comment](https://github.com/elastic/observability-test-environments/issues/10575#issuecomment-1708563294).
> [O11y][IBM MQ] Update the docker image

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-ipd-summary.log-expected.json
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
- Change the conversion function for Win32 timestamps to produce a millisecond result. A mapping error was occuring when trying to map certain fields, such as crowdstrike.event.PrecedingActivityTimeStamp, since (by default) the date field only handles string-based timestamps and millisecond-based unix timestamps.
- `elastic-package test`
- #7547
> [crowdstrike] Convert Win32 timestamps to unix millisecond timestamp

- packages/citrix_adc/changelog.yml
- packages/citrix_adc/manifest.yml
- Enhancement
Migrates the integration from BETA to GA.
- Closes https://github.com/elastic/integrations/issues/7243
> [Citrix ADC] Migrate to GA

- packages/couchdb/changelog.yml
- packages/couchdb/manifest.yml
- Enhancement
Migrates the integration from BETA to GA.
- Closes https://github.com/elastic/integrations/issues/7253
> [CouchDB] Migrate to GA

- packages/zookeeper/changelog.yml
- packages/zookeeper/data_stream/connection/fields/fields.yml
- packages/zookeeper/docs/README.md
- packages/zookeeper/manifest.yml
- Enhancement
Added metric_type mapping for connections datastream.
- Mapping tests completed
- Dashboard tests completed
- https://github.com/elastic/integrations/issues/7752
> [Zookeeper] Added metric type mapping for connection datastream

- docs/developer_tsdb_migration_guidelines.md
Changes:
- The TSDB migration test kit is referenced in this kit.
- Fix the steps order.
> [Documentation] Update TSDB guidelines to provide testing guidance

- packages/atlassian_jira/_dev/deploy/docker/files/config.yml
- packages/atlassian_jira/changelog.yml
- packages/atlassian_jira/data_stream/audit/_dev/test/system/test-api-cloud-config.yml
- packages/atlassian_jira/data_stream/audit/_dev/test/system/test-api-config.yml
- packages/atlassian_jira/data_stream/audit/_dev/test/system/test-files-config.yml
- packages/atlassian_jira/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/atlassian_jira/data_stream/audit/manifest.yml
- packages/atlassian_jira/manifest.yml
- Ensure that from/to timestamps are properly encoded as positive (+) timezone offsets may be interpreted as spaces by the other end (Jira Cloud).
> [atlassian_jira] Ensure from/to timestamps are properly encoded

- packages/aws/changelog.yml
- packages/aws/data_stream/guardduty/_dev/test/system/test-default-config.yml
- packages/aws/data_stream/guardduty/agent/stream/httpjson.yml.hbs
- packages/aws/manifest.yml
The AWS documentation specifies that the maxResults parameter be
[droopingCamelCase](https://docs.aws.amazon.com/guardduty/latest/APIReference/API_ListFindings.html), while we are using CamelCase. This results in API
requests being rejected with the following error
```
{
"message": "The request is rejected because the JSON could not be processed.",
"__type": "InvalidInputException"
}
```
Also re-enable system tests for the data stream; the skip was in
place because we were testing on versions below 8.6. The kibana
version is now v8.9.0, so we can re-enable it.
- Closes #4911
> aws: fix GuardDuty API call parameter

- packages/ti_recordedfuture/changelog.yml
- packages/ti_recordedfuture/elasticsearch/transform/latest_ioc/manifest.yml
- packages/ti_recordedfuture/manifest.yml
In preparation for upgrading to package-spec 3.0.0, this replaces YAML keys containing dots with an unambiguous YAML form. It also removes the empty _meta object from the transform definition.
> [ti_recordedfuture] Remove dotted-yaml keys

- packages/ti_anomali/changelog.yml
- packages/ti_anomali/elasticsearch/transform/latest_ioc/manifest.yml
- packages/ti_anomali/manifest.yml
In preparation for upgrading to package-spec 3.0.0, this replaces YAML keys containing dots with an unambiguous YAML form. It also removes the empty _meta object from the transform definition.
> [ti_anomali] Remove dotted-yaml keys

- packages/ti_maltiverse/changelog.yml
- packages/ti_maltiverse/elasticsearch/transform/latest/manifest.yml
- packages/ti_maltiverse/manifest.yml
In preparation for upgrading to package-spec 3.0.0, this replaces YAML keys containing dots with an unambiguous YAML form.
> [ti_maltiverse] Remove dotted yaml keys

- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/_dev/build/docs/container-logs.md
- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container_logs/_dev/test/pipeline/test-common-config.yml
- packages/kubernetes/data_stream/container_logs/_dev/test/pipeline/test-nginx.log
- packages/kubernetes/data_stream/container_logs/_dev/test/pipeline/test-nginx.log-expected.json
- packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/container_logs/elasticsearch/ingest_pipeline/default.yml
- packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
- packages/kubernetes/data_stream/container_logs/fields/ecs.yml
- packages/kubernetes/data_stream/container_logs/manifest.yml
- packages/kubernetes/data_stream/container_logs/routing_rules.yml
- packages/kubernetes/docs/README.md
- packages/kubernetes/docs/container-logs.md
- packages/kubernetes/manifest.yml
If available, the reroute processor uses the pod's annotations `kubernetes.annotations.elastic.co/dataset` and `kubernetes.annotations.elastic.co/namespace` in the event to route log documents to a custom dataset and namespace. It falls back to the original values if such annotations are not available in the event.
In addition, the integration sets the following fields:
- `service.name` with the value of `app.kubernetes.io/name` label or `kubernetes.container.name` field, in this order of preference.
- `service.version` with the value of `app.kubernetes.io/version` label, if present.
Using this deployment to run nginx to generate container logs:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx-deployment
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template: …
```
> [Kubernetes] Reroute container logs based on pod annotations

- packages/bitdefender/changelog.yml
- packages/bitdefender/data_stream/push_configuration/elasticsearch/ingest_pipeline/default.yml
- packages/bitdefender/data_stream/push_notifications/elasticsearch/ingest_pipeline/default.yml
- packages/bitdefender/data_stream/push_statistics/elasticsearch/ingest_pipeline/default.yml
- packages/bitdefender/manifest.yml
- packages/forcepoint_web/changelog.yml
- packages/forcepoint_web/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
- packages/forcepoint_web/manifest.yml
- packages/jumpcloud/changelog.yml
- packages/jumpcloud/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/jumpcloud/manifest.yml
- packages/tines/changelog.yml
- packages/tines/data_stream/audit_logs/elasticsearch/ingest_pipeline/default.yml
- packages/tines/data_stream/time_saved/elasticsearch/ingest_pipeline/default.yml
- packages/tines/manifest.yml
The ingest node pipelines contained a version attribute that is not useful in Fleet pipelines. This will not be allowed in future versions of package-spec.
Relates: https://github.com/elastic/package-spec/issues/529
- Relates https://github.com/elastic/package-spec/issues/529
- Relates https://github.com/elastic/integrations/issues/7810
> [bitdefender,forcepoint_web,jumpcloud,tines] Remove version from ingest pipeline definitions

- packages/log/agent/input/input.yml.hbs
- packages/log/changelog.yml
- packages/log/manifest.yml
- Enhancement
Expose ignore_older option for the Custom Logs integration.
1.  Build package and startup test environment:
```
cd package/log
elastic-package stack up -v -d --services package-registry
```
2.  Add a new "Custom Logs" integration to a policy
3.  Verify if the correct logs are collected by the datastream
- Closes #7614
> [Custom Logs] Implement input parameter ignore_older

- packages/amazon_security_lake/_dev/build/docs/README.md
- packages/amazon_security_lake/changelog.yml
- packages/amazon_security_lake/docs/README.md
- packages/amazon_security_lake/manifest.yml
Type of change
- Bugfix
- User guide indentation fixing
- Move to integrations/packages/amazon_security_lake directory.
> [amazon_security_lake] User guide indentation fixing

- packages/ti_util/changelog.yml
- packages/ti_util/kibana/dashboard/ti_util-9eff2529-fff5-4064-b825-fa089f260bfa.json
- packages/ti_util/manifest.yml
The `ti_util` generic threat intelligence dashboard wasn't picking up my data.
It was looking for a wildcard value (`ti_*`) using a `match_phrase` query type.
> [ti_util] Change dashboard queries from `match_phrase` to `wildcard`

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.7.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ff3de2331edc3dc663601a9b8d9429f85c2c03eb
None
> [Security Rules] Update security rules package to v8.7.13

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e09ebe539070d499f4116c03d5148b9b20cee1a4
None
> [Security Rules] Update security rules package to v8.8.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dd66fb87b4060e97e84622eb0f4e4e1f2efb692a
None
> [Security Rules] Update security rules package to v8.9.6

- packages/sql_input/agent/input/input.yml.hbs
- packages/sql_input/changelog.yml
- packages/sql_input/manifest.yml
Enhancement
This PR adds two (2) new field settings to the SQL Input integration.
1. Adds the ability to set `condition`.
- The ability to set this value allows for having multiple SQL Input integrations in the same Agent policy while only having them run on specific hosts. (Most likely to be used with the `host` metadata; ex; `host.name` or `host.platform`.
2. Adds the ability to set `processors`.
- The ability to set `processors` to manipulate collected data before sending to Elasticsearch.
- I added both `condition` and `processors` as "advanced" fields.
<details>
<summary>Before Upgrade</summary>
```yaml
inputs:
- id: sql/metrics-sql-12f9198a-ae28-48f4-aae6-63b23781e064
name: sql-1
revision: 1
type: sql/metrics
meta:
package:
name: sql
version: 0.1.0
data_stream: …
```
> Add `condition` and `processors` settings to SQL Input

- packages/cisco_secure_email_gateway/changelog.yml
- packages/cisco_secure_email_gateway/data_stream/log/fields/fields.yml
- packages/cisco_secure_email_gateway/docs/README.md
- packages/cisco_secure_email_gateway/manifest.yml
The `type` and `filepath` fields were unused so this removes them.
> [cisco_secure_email_gateway] Remove unused field mappings

- packages/hid_bravura_monitor/changelog.yml
- packages/hid_bravura_monitor/data_stream/log/manifest.yml
- packages/hid_bravura_monitor/data_stream/winlog/fields/base-fields.yml
- packages/hid_bravura_monitor/data_stream/winlog/fields/ecs.yml
- packages/hid_bravura_monitor/data_stream/winlog/fields/fields.yml
- packages/hid_bravura_monitor/docs/README.md
- packages/hid_bravura_monitor/manifest.yml
For field type consistency, use the ECS value for `message` and `tags`.
Also fix an inconsistency between the data streams for the `processors` variable description.
> [hid_bravura_monitor] Use ECS definition for message and tags

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/manifest.yml
- packages/auditd/manifest.yml
auditd is not a generic input type that you would be applying to different sources. It specifically reads the output of the Linux auditd daemon. It does not need to be able to write to arbitrary logs-* data streams.
Relates: https://github.com/elastic/integrations/pull/6808#issuecomment-1623650344
- Relates https://github.com/elastic/integrations/pull/6808#issuecomment-1623650344
- Relates https://github.com/elastic/integrations/issues/7810
> [auditd] Remove elasticsearch.dynamic_{dataset,namespace}

- packages/symantec_endpoint/changelog.yml
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-policy-rfc3164-sep14-3ru7.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc3164.log-expected.json
- packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc5424.log-expected.json
- packages/symantec_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/symantec_endpoint/data_stream/log/fields/agent.yml
- packages/symantec_endpoint/data_stream/log/fields/ecs.yml
- packages/symantec_endpoint/data_stream/log/fields/fields.yml
- packages/symantec_endpoint/docs/README.md
- packages/symantec_endpoint/manifest.yml
ECS added log.syslog fields and those needed to be adopted by symantec_endpoint to avoid type conflicts across integrations and to make the syslog data representation consist.
As much as possible this tries to avoid breaking changes, but the field data type of log.syslog.version had to change from long to keyword to be consistent with ECS.
The other existing symantec_endpoint log.syslog fields that are not part of ECS were maintained and documented as deprecated. log.syslog.process.name is an alias to ECS log.syslog.appname. And log.syslog.process.name is kept as a long representation of ECS log.syslog.procid.
Fixes #7843
- Relates #7843
> [symantec_endpoint] Adopt ECS log.syslog mappings

- packages/tenable_io/changelog.yml
- packages/tenable_io/data_stream/asset/manifest.yml
- packages/tenable_io/data_stream/asset/sample_event.json
- packages/tenable_io/data_stream/plugin/manifest.yml
- packages/tenable_io/data_stream/plugin/sample_event.json
- packages/tenable_io/data_stream/scan/sample_event.json
- packages/tenable_io/data_stream/vulnerability/manifest.yml
- packages/tenable_io/data_stream/vulnerability/sample_event.json
- packages/tenable_io/docs/README.md
- packages/tenable_io/manifest.yml
Type of change
- Enhancement
Updated default value of interval parameter to 1h for Asset and Vulnerability and Enabled the plugin data stream.
Move to integrations/packages/tenable_io directory.
`elastic-package test`
Attaching the test file below - 
[test-file.log](https://github.com/elastic/integrations/files/12671138/test-file.log)
> [tenable_io] Updated Default value of Interval Paramter and Enabled Plugin Data Stream

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/apm_server_logs/fields/fields.yml
- packages/elastic_agent/data_stream/apm_server_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/auditbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/auditbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/cloud_defend_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/elastic_agent_logs/fields/fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/beat-stats-fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/endpoint_sercurity_logs/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/fleet_server_logs/fields/fields.yml
- packages/elastic_agent/data_stream/fleet_server_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_metrics/fields/fields.yml
- packages/elastic_agent/manifest.yml
Fix mapping and description for the `system.process.cpu.{system,user,total}.time.ms` fields. The fields should be of type `long` instead of `date`.
Align mapping for the `beat.stats.libbeat.config.{running,starts,stops}` fields with the `beat` integration. The beat integration uses `long` so align to that.
For the `message` field, consistently use the ECS defined mapping type of `match_only_text`.
- Fixes https://github.com/elastic/integrations/issues/7846
- Fixes https://github.com/elastic/integrations/issues/4245
> [elastic_agent] Fix inconsistencies in field mapping types

- packages/windows/changelog.yml
- packages/windows/data_stream/perfmon/agent/stream/stream.yml.hbs
- packages/windows/data_stream/perfmon/manifest.yml
- packages/windows/manifest.yml
Add the `refresh_wildcard_counters` [variable](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-windows-perfmon.html#_configuration_19) to the windows perfmon data stream.
1. `elastic-package build`
2. `elastic-package stack up -d`
3. login to Kibana
4. create empty policy
5. make add windows integration
6. Enable `refresh_wildcard_counters` variable
7. Save policy
8. Inspect policy, make sure variable exists and is `true`
- Closes #7895
> [windows] perfmon add refresh_wildcard_counters variable

- packages/couchbase/changelog.yml
- packages/couchbase/data_stream/bucket/manifest.yml
- packages/couchbase/data_stream/cache/manifest.yml
- packages/couchbase/data_stream/cbl_replication/manifest.yml
- packages/couchbase/data_stream/cluster/manifest.yml
- packages/couchbase/data_stream/database_stats/manifest.yml
- packages/couchbase/data_stream/miscellaneous/manifest.yml
- packages/couchbase/data_stream/query_index/manifest.yml
- packages/couchbase/data_stream/resource/manifest.yml
- packages/couchbase/data_stream/xdcr/manifest.yml
- packages/couchbase/manifest.yml
- Enhancement
Added TSDB related changes for Couchbase package
> [Couchbase] TSDB enablement for couchbase

- packages/apache_tomcat/changelog.yml
- packages/apache_tomcat/data_stream/cache/agent/stream/stream.yml.hbs
- packages/apache_tomcat/data_stream/cache/manifest.yml
- packages/apache_tomcat/data_stream/cache/sample_event.json
- packages/apache_tomcat/data_stream/connection_pool/agent/stream/stream.yml.hbs
- packages/apache_tomcat/data_stream/connection_pool/manifest.yml
- packages/apache_tomcat/data_stream/connection_pool/sample_event.json
- packages/apache_tomcat/data_stream/memory/agent/stream/stream.yml.hbs
- packages/apache_tomcat/data_stream/memory/manifest.yml
- packages/apache_tomcat/data_stream/memory/sample_event.json
- packages/apache_tomcat/data_stream/request/agent/stream/stream.yml.hbs
- packages/apache_tomcat/data_stream/request/manifest.yml
- packages/apache_tomcat/data_stream/request/sample_event.json
- packages/apache_tomcat/data_stream/session/agent/stream/stream.yml.hbs
- packages/apache_tomcat/data_stream/session/manifest.yml
- packages/apache_tomcat/data_stream/session/sample_event.json
- packages/apache_tomcat/data_stream/thread_pool/agent/stream/stream.yml.hbs
- packages/apache_tomcat/data_stream/thread_pool/manifest.yml
- packages/apache_tomcat/data_stream/thread_pool/sample_event.json
- packages/apache_tomcat/docs/README.md
- packages/apache_tomcat/manifest.yml
- Bug
- This PR removes the forwarded tag from the metricbeat-based data streams.
- Relates #7635
> [O11y][Apache Tomcat] Remove forwarded tag from metrics data streams 

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
This adds a URL to the ARM template that is used for CSPM Azure onboarding. The file is hosted directly in the [elastic/cloudbeat](https://github.com/elastic/cloudbeat) repo. Azure does not support modifying the template parameters via a link like in AWS. The link is hardcoded to the `main` branch for now but should be updated to point to the $current_version branch.
- Fixes https://github.com/elastic/cloudbeat/issues/1296
- Related to https://github.com/elastic/cloudbeat/issues/1320 (branch approach is the same)
https://github.com/elastic/integrations/assets/5778622/674255ef-82da-4592-8a79-e81228cdef62
> [Cloud Security] Add Azure ARM url

- packages/salesforce/_dev/build/docs/README.md
- packages/salesforce/changelog.yml
- packages/salesforce/data_stream/apex/agent/stream/httpjson.yml.hbs
- packages/salesforce/data_stream/apex/manifest.yml
- packages/salesforce/data_stream/login_rest/agent/stream/httpjson.yml.hbs
- packages/salesforce/data_stream/login_rest/manifest.yml
- packages/salesforce/data_stream/logout_rest/agent/stream/httpjson.yml.hbs
- packages/salesforce/data_stream/logout_rest/manifest.yml
- packages/salesforce/data_stream/setupaudittrail/agent/stream/httpjson.yml.hbs
- packages/salesforce/data_stream/setupaudittrail/manifest.yml
- packages/salesforce/docs/README.md
- packages/salesforce/manifest.yml
- Enhancement
- This PR increases the default timeout 30s to 5m (by adding a new field) for the following datastreams: login-rest, logout-rest, setupaudittrail, apex-rest
- If users by any chance still facing a timeout issue then they can increase the timeout from the UI advanced option to get unblocked from the timeout issue.
- Closes https://github.com/elastic/integrations/issues/7880
> [Salesforce] Add request timeout parameter in configuration

- packages/awsfirehose/changelog.yml
- packages/awsfirehose/data_stream/logs/routing_rules.yml
- packages/awsfirehose/manifest.yml
This PR is to enhance routing rules for WAF logs based its log format instead of firehose stream name and cloudwatch log group name. This way when WAF logs are sent to S3 bucket -> lambda -> firehose, our `awsfirehose` integration will still be able to route it correctly.
~~This PR also removes all `namespace` in routing rules since we are using the default, no need to specify it.~~ (will make this a separate change, this is causing error when running ` elastic-package test -v --report-format xUnit --report-output file --test-coverage
` command)
> Add routing rules for WAF logs based on log format

- packages/box_events/_dev/build/build.yml
- packages/box_events/changelog.yml
- packages/box_events/data_stream/events/_dev/test/pipeline/test-anomalous-download.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-copy.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-create.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-download.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-event-types.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-malicious-content.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-preview.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-rename.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-suspicious-locations.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-suspicious-sessions.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-trash.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-upload.log-expected.json
- packages/box_events/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/box_events/data_stream/events/sample_event.json
- packages/box_events/manifest.yml
- Updates the box_events integration to ECS 8.10
- Due to the number of categorization updates, and updates to both `event.category` as well as `event.type`, I set this to a major upgrade.
- I did my best to update these categorization fields as accurately and consistently as possible. Feel free to make suggestions though if you see any issues. 
> [ECS] Updating box_events to ECS 8.10 & ECS field validation updates

- packages/cisco_asa/_dev/build/build.yml
- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sip.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/sample_event.json
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
- Updates the cisco_asa integration to ECS 8.10
> [ECS] Updating cisco_asa to ECS 8.10 & ECS field validation updates

- packages/cisco_ftd/_dev/build/build.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-firepower-management.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-endpoint-profile.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-inbound-outbound.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-no-type-id.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log-expected.json
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log-expected.json
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
- Updates the cisco_ftd integration to ECS 8.10
> [ECS] Updating cisco_ftd to ECS 8.10 & ECS field validation updates

- packages/keycloak/_dev/build/build.yml
- packages/keycloak/changelog.yml
- packages/keycloak/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
- packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/events.yml
- packages/keycloak/manifest.yml
- Updates the keycloak integration to ECS 8.10
> [ECS] Updating keycloak to ECS 8.10 & ECS field validation updates

- packages/ping_one/_dev/build/build.yml
- packages/ping_one/changelog.yml
- packages/ping_one/data_stream/audit/_dev/test/pipeline/test-pipeline-audit.log-expected.json
- packages/ping_one/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/ping_one/data_stream/audit/sample_event.json
- packages/ping_one/docs/README.md
- packages/ping_one/manifest.yml
- Updates the ping_one integration to ECS 8.10
> [ECS] Updating ping_one to ECS 8.10 & ECS field validation updates

- packages/proofpoint_tap/_dev/build/build.yml
- packages/proofpoint_tap/changelog.yml
- packages/proofpoint_tap/data_stream/clicks_blocked/_dev/test/pipeline/test-clicks-blocked.log-expected.json
- packages/proofpoint_tap/data_stream/clicks_blocked/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/clicks_blocked/sample_event.json
- packages/proofpoint_tap/data_stream/clicks_permitted/_dev/test/pipeline/test-clicks-permitted.log-expected.json
- packages/proofpoint_tap/data_stream/clicks_permitted/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/clicks_permitted/sample_event.json
- packages/proofpoint_tap/data_stream/message_blocked/_dev/test/pipeline/test-message-blocked.log-expected.json
- packages/proofpoint_tap/data_stream/message_blocked/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/message_blocked/sample_event.json
- packages/proofpoint_tap/data_stream/message_delivered/_dev/test/pipeline/test-message-delivered.log-expected.json
- packages/proofpoint_tap/data_stream/message_delivered/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/message_delivered/sample_event.json
- packages/proofpoint_tap/docs/README.md
- packages/proofpoint_tap/manifest.yml
- Updates the proofpoint_tap integration to ECS 8.10
> [ECS] Updating proofpoint_tap to ECS 8.10 & ECS field validation updates

- packages/slack/_dev/build/build.yml
- packages/slack/changelog.yml
- packages/slack/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
- packages/slack/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/slack/data_stream/audit/sample_event.json
- packages/slack/docs/README.md
- packages/slack/manifest.yml
- Updates the slack integration to ECS 8.10
> [ECS] Updating slack to ECS 8.10 & ECS field validation updates

- packages/ti_rapid7_threat_command/_dev/build/build.yml
- packages/ti_rapid7_threat_command/changelog.yml
- packages/ti_rapid7_threat_command/data_stream/alert/sample_event.json
- packages/ti_rapid7_threat_command/data_stream/ioc/sample_event.json
- packages/ti_rapid7_threat_command/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability-event.json-expected.json
- packages/ti_rapid7_threat_command/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/ti_rapid7_threat_command/data_stream/vulnerability/sample_event.json
- packages/ti_rapid7_threat_command/docs/README.md
- packages/ti_rapid7_threat_command/manifest.yml
- Updates the ti_rapid7_threat_command integration to ECS 8.10
> [ECS] Updating ti_rapid7_threat_command to ECS 8.10 & ECS field validation updates

- .github/CODEOWNERS
- packages/cloud_defend/manifest.yml
The github team responsible for cloud-defend has changed, update to the new team name in CODEOWNERS.
- Closes #7784
> Update cloud_defend codeowners to new team

- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/loadbalancing_logs/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/manifest.yml
- Bug
This PR adds the if check for event.original and the ignore_missing check for the renaming of message to event.original
The packages where the changes are made are as below:
- loadbalancing_logs
- vpcflow
- firewall
- audit
- dns
- Relates https://github.com/elastic/integrations/issues/7822
> [GCP] Update null checks anf if checks in the rename

- packages/github/_dev/build/docs/README.md
- packages/github/changelog.yml
- packages/github/data_stream/audit/manifest.yml
- packages/github/docs/README.md
- packages/github/manifest.yml
Github token doesn't require `admin:org` scope in order to fetch the audit logs of an organization. This PR removes that scope from the token permissions.
- Fix docs
> [Github] Fix docs for Audit log permissions

- packages/log/agent/input/input.yml.hbs
- packages/log/changelog.yml
- packages/log/manifest.yml
- Enhancement
Expose exclude_files option for the Custom Logs integration.
1. Build package and startup test environment:
```
cd package/log
elastic-package stack up -v -d
```
2. Add a new "Custom Logs" integration to a policy
3. Verify if the correct logs are collected by the datastream
- Closes #7939
> [Custom Logs] Implement input parameter exclude_files

- packages/1password/changelog.yml
- packages/1password/data_stream/audit_events/sample_event.json
- packages/1password/data_stream/item_usages/_dev/test/pipeline/test-itemusages.json-expected.json
- packages/1password/data_stream/item_usages/elasticsearch/ingest_pipeline/default.yml
- packages/1password/data_stream/item_usages/fields/ecs.yml
- packages/1password/data_stream/item_usages/sample_event.json
- packages/1password/data_stream/signin_attempts/_dev/test/pipeline/test-signinattempts.json-expected.json
- packages/1password/data_stream/signin_attempts/elasticsearch/ingest_pipeline/default.yml
- packages/1password/data_stream/signin_attempts/fields/ecs.yml
- packages/1password/data_stream/signin_attempts/sample_event.json
- packages/1password/docs/README.md
- packages/1password/manifest.yml
Correcting invalid ECS `os.*` field usages at the root-level
> [ECS][1password] Correcting invalid ECS field usages at root-level

- packages/cisco_aironet/changelog.yml
- packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log-expected.json
- packages/cisco_aironet/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_aironet/data_stream/log/fields/ecs.yml
- packages/cisco_aironet/data_stream/log/sample_event.json
- packages/cisco_aironet/docs/README.md
- packages/cisco_aironet/manifest.yml
Correcting invalid ECS `interface.id` field usage at the root-level
> [ECS][cisco_aironet] Correcting invalid ECS field usages at root-level

- packages/cloudflare_logpush/changelog.yml
- packages/cloudflare_logpush/data_stream/access_request/sample_event.json
- packages/cloudflare_logpush/data_stream/audit/sample_event.json
- packages/cloudflare_logpush/data_stream/casb/sample_event.json
- packages/cloudflare_logpush/data_stream/device_posture/sample_event.json
- packages/cloudflare_logpush/data_stream/dns/sample_event.json
- packages/cloudflare_logpush/data_stream/firewall_event/sample_event.json
- packages/cloudflare_logpush/data_stream/gateway_dns/sample_event.json
- packages/cloudflare_logpush/data_stream/gateway_http/sample_event.json
- packages/cloudflare_logpush/data_stream/gateway_network/sample_event.json
- packages/cloudflare_logpush/data_stream/http_request/sample_event.json
- packages/cloudflare_logpush/data_stream/nel_report/sample_event.json
- packages/cloudflare_logpush/data_stream/network_analytics/sample_event.json
- packages/cloudflare_logpush/data_stream/network_session/_dev/test/pipeline/test-pipeline-network-session.log-expected.json
- packages/cloudflare_logpush/data_stream/network_session/elasticsearch/ingest_pipeline/default.yml
- packages/cloudflare_logpush/data_stream/network_session/fields/ecs.yml
- packages/cloudflare_logpush/data_stream/network_session/sample_event.json
- packages/cloudflare_logpush/data_stream/spectrum_event/sample_event.json
- packages/cloudflare_logpush/data_stream/workers_trace/sample_event.json
- packages/cloudflare_logpush/docs/README.md
- packages/cloudflare_logpush/manifest.yml
Correcting invalid ECS `vlan.id` field usage at the root-level
> [ECS][cloudflare_logpush] Correcting invalid ECS field usages at root-level

- packages/fireeye/changelog.yml
- packages/fireeye/data_stream/nx/_dev/test/pipeline/test-nx.log-expected.json
- packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/renaming-raws.yml
- packages/fireeye/data_stream/nx/fields/ecs.yml
- packages/fireeye/data_stream/nx/sample_event.json
- packages/fireeye/docs/README.md
- packages/fireeye/manifest.yml
Correcting invalid ECS `interface.name` field usage at the root-level
> [ECS][fireeye] Correcting invalid ECS field declarations at root-level

- packages/entityanalytics_entra_id/_dev/build/build.yml
- packages/entityanalytics_entra_id/changelog.yml
- packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-users.json-expected.json
- packages/entityanalytics_entra_id/data_stream/entity/elasticsearch/ingest_pipeline/default.yml
- packages/entityanalytics_entra_id/data_stream/entity/sample_event.json
- packages/entityanalytics_entra_id/docs/README.md
- packages/entityanalytics_entra_id/manifest.yml
- packages/qualys_vmdr/_dev/build/build.yml
- packages/qualys_vmdr/changelog.yml
- packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/pipeline/test-asset-host-detection.log-expected.json
- packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
- packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
- packages/qualys_vmdr/data_stream/knowledge_base/_dev/test/pipeline/test-knowledge-base.log-expected.json
- packages/qualys_vmdr/data_stream/knowledge_base/elasticsearch/ingest_pipeline/default.yml
- packages/qualys_vmdr/data_stream/knowledge_base/sample_event.json
- packages/qualys_vmdr/docs/README.md
- packages/qualys_vmdr/manifest.yml
- packages/trellix_edr_cloud/_dev/build/build.yml
- packages/trellix_edr_cloud/changelog.yml
- packages/trellix_edr_cloud/data_stream/event/_dev/test/pipeline/test-event.log-expected.json
- packages/trellix_edr_cloud/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/trellix_edr_cloud/data_stream/event/sample_event.json
- packages/trellix_edr_cloud/docs/README.md
- packages/trellix_edr_cloud/manifest.yml
Updates the following SEI packages to ECS version 8.10:
- entityanalytics_entra_id
- qualys_vmdr
- trellix_edr_cloud
Changes generated by:
```
go install github.com/andrewkroh/go-examples/elastic-package-changelog@main
go run github.com/andrewkroh/go-examples/ecs-update@main -owner elastic/security-external-integrations -ecs-version=8.10.0 -ecs-git-ref=v8.10.0 -pr 7961 packages/<PACKAGE>
```
> [ECS] Update SEI packages to ECS 8.10 (Part 5)

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/sample_event.json
- packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log-expected.json
- packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/data_stream/fdr/fields/ecs.yml
- packages/crowdstrike/data_stream/fdr/sample_event.json
- packages/crowdstrike/docs/README.md
- packages/crowdstrike/manifest.yml
Correcting invalid ECS `os.*` field usage at the root-level
> [ECS][crowdstrike] Correcting invalid ECS field usages at root-level

- packages/docker/changelog.yml
- packages/docker/data_stream/container_logs/fields/base-fields.yml
- packages/docker/docs/README.md
- packages/docker/manifest.yml
The docker integration has the `message` field mapped as a keyword while every other integration uses `match_only_text` (ECS) or `text`.
Fixes: #5679
- Relates #5679
> [docker] Fix 'message' data type to align with ECS

- packages/oracle_weblogic/changelog.yml
- packages/oracle_weblogic/data_stream/admin_server/fields/base-fields.yml
- packages/oracle_weblogic/data_stream/domain/fields/base-fields.yml
- packages/oracle_weblogic/data_stream/managed_server/fields/base-fields.yml
- packages/oracle_weblogic/docs/README.md
- packages/oracle_weblogic/manifest.yml
The admin_server, domain, and managed_server data streams had the `message` field mapped as a `keyword`. All other integrations use a text-family field type. The field is specified by ECS so this will now reference the ECS definition.
This causes a conflict in the `logs-*` data view.
> [oracle_weblogic] Use ECS definition for 'message' field type

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-decryption-sample.log-expected.json
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/decryption.yml
- packages/panw/data_stream/panos/fields/ecs.yml
- packages/panw/data_stream/panos/sample_event.json
- packages/panw/docs/README.md
- packages/panw/manifest.yml
Correcting invalid ECS `x509.*` field usages at the root-level
> [ECS][panw] Correcting invalid ECS field usages at root-level

- packages/sentinel_one/changelog.yml
- packages/sentinel_one/data_stream/activity/_dev/test/pipeline/test-pipeline-activity.log-expected.json
- packages/sentinel_one/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/activity/fields/ecs.yml
- packages/sentinel_one/data_stream/activity/sample_event.json
- packages/sentinel_one/data_stream/agent/sample_event.json
- packages/sentinel_one/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/alert/fields/ecs.yml
- packages/sentinel_one/data_stream/alert/sample_event.json
- packages/sentinel_one/data_stream/group/sample_event.json
- packages/sentinel_one/data_stream/threat/sample_event.json
- packages/sentinel_one/docs/README.md
- packages/sentinel_one/manifest.yml
Correcting invalid ECS `os.*` field usages at the root-level
> [ECS][sentinel_one] Correcting invalid ECS field usages at root-level

- packages/trend_micro_vision_one/changelog.yml
- packages/trend_micro_vision_one/data_stream/alert/sample_event.json
- packages/trend_micro_vision_one/data_stream/audit/sample_event.json
- packages/trend_micro_vision_one/data_stream/detection/_dev/test/pipeline/test-pipeline-detection.log-expected.json
- packages/trend_micro_vision_one/data_stream/detection/elasticsearch/ingest_pipeline/default.yml
- packages/trend_micro_vision_one/data_stream/detection/fields/ecs.yml
- packages/trend_micro_vision_one/data_stream/detection/sample_event.json
- packages/trend_micro_vision_one/docs/README.md
- packages/trend_micro_vision_one/manifest.yml
Correcting invalid ECS `os.*` field usages at the root-level
> [ECS][trend_micro_vision_one] Correcting invalid ECS field usages at root-level

- packages/hashicorp_vault/_dev/build/build.yml
- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
- packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-faked-all-fields.log-expected.json
- packages/hashicorp_vault/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/hashicorp_vault/data_stream/audit/sample_event.json
- packages/hashicorp_vault/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
- packages/hashicorp_vault/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/hashicorp_vault/data_stream/log/sample_event.json
- packages/hashicorp_vault/data_stream/metrics/sample_event.json
- packages/hashicorp_vault/docs/README.md
- packages/hashicorp_vault/manifest.yml
- Updates the hashicorp_vault integration to ECS 8.10
> [ECS] Updating hashicorp_vault to ECS 8.10 & ECS field validation updates

- packages/spring_boot/_dev/build/docs/README.md
- packages/spring_boot/changelog.yml
- packages/spring_boot/data_stream/audit_events/fields/ecs.yml
- packages/spring_boot/data_stream/gc/fields/ecs.yml
- packages/spring_boot/data_stream/memory/elasticsearch/ingest_pipeline/default.yml
- packages/spring_boot/data_stream/memory/fields/ecs.yml
- packages/spring_boot/data_stream/threading/fields/ecs.yml
- packages/spring_boot/docs/README.md
- packages/spring_boot/manifest.yml
- Bug
- Added host.ip field in ecs.yml and added re-indexing steps to resolve conflicts for existing users.
- Updating the Readme.md with the instruction on how user can monitor their application with following functions: [InMemoryHttpTraceRepository](https://javadoc.io/static/org.springframework.boot/spring-boot-actuator/2.2.1.RELEASE/org/springframework/boot/actuate/trace/http/InMemoryHttpTraceRepository.html#:~:text=Class-,InMemoryHttpTraceRepository,-java.lang.Object)
[InMemoryAuditEventRepository](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/audit/InMemoryAuditEventRepository.html#:~:text=Class-,InMemoryAuditEventRepository,-java.lang.Object)
- Remove the incorrect rename processor from the memory datastream pipeline
- Closes …
> [O11y][Springboot] Resolve the conflicts in host.ip field, update readme and remove incorrect rename processor

- packages/universal_profiling_collector/agent/input/input.yml.hbs
- packages/universal_profiling_collector/changelog.yml
- packages/universal_profiling_collector/manifest.yml
- packages/universal_profiling_symbolizer/agent/input/input.yml.hbs
- packages/universal_profiling_symbolizer/changelog.yml
- packages/universal_profiling_symbolizer/manifest.yml
Add configuration options for universal_profiling integrations (collector/symbolizer) to set logging, telemetry and memory limits for the running binaries.
* Run a local stack with `elastic-stack up` (stack version 8.10 or higher)
* Build an install the new packages in Kibana
* Create an agent policy and enroll an agent locally
* Configure the new `vars`
* Validate they are actually used in the binaries
> [Universal Profiling] Add inputs for collector/symbolizer

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/common.yml
- packages/synthetics/data_stream/browser_network/fields/common.yml
- packages/synthetics/data_stream/browser_screenshot/fields/common.yml
- packages/synthetics/data_stream/http/fields/common.yml
- packages/synthetics/data_stream/icmp/fields/common.yml
- packages/synthetics/data_stream/tcp/fields/common.yml
- packages/synthetics/manifest.yml
Fixes mappings regression introduced by https://github.com/elastic/integrations/pull/7813
monitor fields properties got inside meta mistakenly.
> [Synthetics] Fixes mappings regression 

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/fields/fields.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
- `o365.audit.ExchangeMetaData.*`
- `o365.audit.ExceptionInfo.*`
- `o365.audit.ExtendedProperties.*`
- `o365.audit.Item.*`
- `o365.audit.Item.*.*`
- `o365.audit.ModifiedProperties.*.*`
- `o365.audit.Parameters.*`
- `o365.audit.SharePointMetaData.*`
Remove `o365.audit.Members.*`; `o365.audit.Members` is already defined as a flattened field.
After this change the dynamic mappings are:
```
"dynamic_templates": [
{
"container.labels": {
"path_match": "container.labels.*",
"match_mapping_type": "string",
"mapping": {
"type": "keyword"
}
}
},
{
"o365.audit.ExchangeMetaData.*": {
"path_match": "o365.audit.ExchangeMetaData.*",
"match_mapping_type": "long",
"mapping": {
"type": "long"
}
}
},
{
"o365.audit.ExceptionInfo.*": {
"path_match": "o365.audit.ExceptionInfo.*",
"mapping": {
"type": …
```
> o365: fix mappings for dynamically mapped fields

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/fields.yml
- packages/cisco_asa/data_stream/log/sample_event.json
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
> cisco_asa: expand set of accepted auth rejection reasons and retain reason

- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/manifest.yml
Bumps the minimum `kibana.version` in manifest.yml to make it mandatory to use ^8.10.2 stack for the new `fetch_from_all_databases` feature which was not enforced earlier.
Based on a conversation with @ishleenk17 and also referring to https://github.com/elastic/integrations/blob/faef732498b4749407af54b6ee0d75c4f904eb1d/docs/tips_for_building_integrations.md?plain=1#L110 made a decision to bump the `kibana.version`.
> Update: Upgrading the stack to ^8.10.2 as 8.10.0 and 8.10.1 have security flaws and it is recommended to use ^8.10.2
- Relates https://github.com/elastic/integrations/pull/7500
> microsoft_sqlserver: Bump minimum `kibana.version`

- packages/gcp/changelog.yml
- packages/gcp/data_stream/loadbalancing_logs/manifest.yml
- packages/gcp/kibana/dashboard/gcp-1ae960c0-f9f8-11eb-bc38-79936db7c106.json
- packages/gcp/kibana/dashboard/gcp-2b0fd7b0-feac-11ea-b032-d59f894a5072.json
- packages/gcp/kibana/dashboard/gcp-48e12760-cbe4-11ec-b519-85ccf621cbbf.json
- packages/gcp/kibana/dashboard/gcp-6041d970-a6ae-11ea-950e-d57608e3aa51.json
- packages/gcp/kibana/dashboard/gcp-76c9e920-e890-11ea-bf8c-d13ebf358a78.json
- packages/gcp/kibana/dashboard/gcp-8a1fb690-cbeb-11ec-b519-85ccf621cbbf.json
- packages/gcp/kibana/dashboard/gcp-8f9c6cc0-909d-11ea-8180-7b0dacd9df87.json
- packages/gcp/kibana/dashboard/gcp-9484a4cd-685f-450e-aeaa-728fbdbea20f.json
- packages/gcp/kibana/dashboard/gcp-aa5b8bd0-9157-11ea-8180-7b0dacd9df87.json
- packages/gcp/kibana/dashboard/gcp-ca401040-8e52-11ea-9fa6-4d675d5290dc.json
- packages/gcp/kibana/dashboard/gcp-f40ee870-5e4a-11ea-a4f6-717338406083.json
- packages/gcp/kibana/tags.yml
- packages/gcp/manifest.yml
Add tags.yml file so that integration's dashboards and saved searches are tagged with "Security Solution" and displayed in the Security Solution UI.
Upgrade to package spec 3.0
Add missing dashboard filters and remove orphan dashboard references.
- Relates https://github.com/elastic/integrations/issues/7483
> [gcp] Add tags.yml file and upgrade to package spec 3.0

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
- packages/juniper_srx/changelog.yml
- packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/juniper_srx/manifest.yml
> cisco_asa,cisco_ftd,juniper_srx: remove redundant regular expression quantifier

- packages/forgerock/changelog.yml
- packages/forgerock/data_stream/am_access/fields/forgerock-fields.yml
- packages/forgerock/data_stream/am_activity/fields/forgerock-fields.yml
- packages/forgerock/docs/README.md
- packages/forgerock/manifest.yml
> forgerock: use dynamic mappings for object fields

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
bumps `cloudshell_git_branch` to `8.11` and removes the `-preview` version suffix
-
> [Cloud Security] Bump integration version

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/fields.yml
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
It fixes the processing of events 313005 with the following format:
```
<188>May 5 17:51:17 dev01: %ASA-4-313005: No matching connection for ICMP error message: icmp src srcif:192.168.2.2 dst dstif:192.168.2.3 (type 3, code 2) on srcif interface. Original IP payload: protocol 51 src 192.168.2.2 dst 192.168.2.3.
```
which contains a protocol IANA number inside the original IP payload that was not being parsed.
> [Cisco ASA] Fix the processing of the protocol field for 313005

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/data_stream/incident/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/m365_defender/manifest.yml
- packages/m365_defender/validation.yml
Add condition in `rename` processor from `message` to `event.original` to check if the field already exists
- Closes https://github.com/elastic/integrations/issues/8034
- Relates #3451
> [m365_defender] Fix duplicate event.original field

- packages/zeek/changelog.yml
- packages/zeek/data_stream/intel/fields/fields.yml
- packages/zeek/docs/README.md
- packages/zeek/manifest.yml
See title.
```
"dynamic_templates": [
{
"zeek.intel.seen.f.*": {
"path_match": "zeek.intel.seen.f.*",
"mapping": {
"type": "keyword"
}
}
},
{
"strings_as_keyword": {
"match_mapping_type": "string",
"mapping": {
"ignore_above": 1024,
"type": "keyword"
}
}
}
],
```
- Closes #8063
> zeek: use dynamic mapping for object fields

- packages/apache_spark/changelog.yml
- packages/apache_spark/data_stream/driver/agent/stream/stream.yml.hbs
- packages/apache_spark/manifest.yml
- Bugfix
- Fix typo error for MBean `metrics:name=.driver.spark.streaming..inputRate-total,type=gauge` whose data is not being collected.
- Closes #8060
> [O11y][Apache Spark] Update MBean for driver datastream

- packages/couchdb/changelog.yml
- packages/couchdb/data_stream/server/agent/stream/stream.yml.hbs
- packages/couchdb/data_stream/server/fields/ecs.yml
- packages/couchdb/data_stream/server/manifest.yml
- packages/couchdb/data_stream/server/sample_event.json
- packages/couchdb/docs/README.md
- packages/couchdb/manifest.yml
- Bug
- This PR remove forwarded tag from the metricbeat-based data streams.
- Relates #7635
> [O11y][CouchDB] Remove forwarded tag from metrics data streams

- packages/ibmmq/changelog.yml
- packages/ibmmq/data_stream/qmgr/agent/stream/stream.yml.hbs
- packages/ibmmq/data_stream/qmgr/manifest.yml
- packages/ibmmq/data_stream/qmgr/sample_event.json
- packages/ibmmq/docs/README.md
- packages/ibmmq/manifest.yml
- Bug
- This PR remove forwarded tag from the metricbeat-based data streams.
- Relates #7635
> [O11y][IBM MQ] Remove forwarded tag from metrics data streams

- packages/zookeeper/changelog.yml
- packages/zookeeper/data_stream/connection/fields/agent.yml
- packages/zookeeper/data_stream/connection/fields/ecs.yml
- packages/zookeeper/docs/README.md
- packages/zookeeper/manifest.yml
- Enhancement
Added dimension mapping for connection datastream.
- Mapping tests completed
- Dashboard tests completed
- https://github.com/elastic/integrations/issues/7752
> [Zookeeper] Added dimensions mapping to Zookeeper connection datastream

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/events/manifest.yml
- packages/cisco_meraki/data_stream/log/manifest.yml
- packages/cisco_meraki/manifest.yml
- Bug
Removed experimental release tags from data streams. The integration was made GA with 8.4 but the tags remained, which was a bug.
- Relates #3859
> [integrations][Cisco Meraki] - Removed experimental release tags from data streams

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/790fa9a82621844f2dbe1de227540049bf6162b8
None
None
> [Security Rules] Update security rules package to v8.8.12

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/0300a17fa8878b6ee2273de5767b55d86be610f4
None
None
> [Security Rules] Update security rules package to v8.9.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2062c6c33b9e773ae77597ad636e65fd9fb4d708
None
None
> [Security Rules] Update security rules package to v8.11.1

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log-expected.json
- packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
- packages/infoblox_nios/data_stream/log/fields/ecs.yml
- packages/infoblox_nios/data_stream/log/fields/fields.yml
- packages/infoblox_nios/docs/README.md
- packages/infoblox_nios/manifest.yml
When looking at the differences between the infoblox NIOS DNS dataset and our `network_packet_capture` dataset I discovered that we are not using `dns.flags` to print out the DNS flags such as: 
```
- = recursion not available
+ = recursion available (from DNS message header)
A = authoritative answer (from DNS message header)
t = truncated response (from DNS message header)
E = EDNS OPT record present (from DNS message header)
D = DNSSEC OK (from EDNS OPT RR)
V = responding server has validated DNSSEC records
L = response contains DTC synthetic record
```
Taken from: [Infoblox DNS](https://docs.infoblox.com/space/NAG8/22252254/Capturing+DNS+Queries+and+Responses)
This is an example taken from our `network packet capture dns` dataset:
```json
"dns": {
"response_code": "NOERROR", …
```
> Infoblox_nios: add client geoip and registered_domain processors to dns data

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
CloudFormation: Fix missing tags in cloud-security account
This is a temporary fix that tags required resources for the build to succeed. We can revert it after the QA cycle to find a more elegant solution.
See https://github.com/elastic/cloudbeat/pull/1415
> [Cloud Security] Add Elastic-specific tags in CloudFormation

- packages/salesforce/changelog.yml
- packages/salesforce/data_stream/apex/_dev/test/pipeline/test-apex.log-expected.json
- packages/salesforce/data_stream/apex/_dev/test/pipeline/test-common-config.yml
- packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/login_rest/_dev/test/pipeline/test-common-config.yml
- packages/salesforce/data_stream/login_rest/_dev/test/pipeline/test-login-rest.log-expected.json
- packages/salesforce/data_stream/login_rest/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/login_rest/sample_event.json
- packages/salesforce/data_stream/login_stream/_dev/test/pipeline/test-common-config.yml
- packages/salesforce/data_stream/login_stream/_dev/test/pipeline/test-login-stream.log-expected.json
- packages/salesforce/data_stream/login_stream/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/login_stream/sample_event.json
- packages/salesforce/data_stream/logout_rest/_dev/test/pipeline/test-common-config.yml
- packages/salesforce/data_stream/logout_rest/_dev/test/pipeline/test-logout-rest.log-expected.json
- packages/salesforce/data_stream/logout_rest/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/logout_rest/sample_event.json
- packages/salesforce/data_stream/logout_stream/_dev/test/pipeline/test-common-config.yml
- packages/salesforce/data_stream/setupaudittrail/_dev/test/pipeline/test-common-config.yml
- packages/salesforce/docs/README.md
- packages/salesforce/manifest.yml
- packages/salesforce/validation.yml
The biggest change here is the modification of the simple `rename` processors to `script` in order to get the formatting of the list the way elastic-package wants it. I'm not sold on these changes, since it adds complexity for no change in behaviour. 
@jsoriano is there any way we could make changes in the validation for cases like this to avoid the added overhead in the ingest pipelines?
> [salesforce] Update package to format_version 3.0.0

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/storage_account/manifest.yml
- packages/azure_metrics/manifest.yml
- Enhancement
Enable time series data streams for the storage_account metrics dataset. This dramatically reduces storage for metrics and is expected to progressively improve query [performance](https://www.elastic.co/blog/70-percent-storage-savings-for-metrics-with-elastic-observability). For more details, see https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html.
The changes have been validated using the `TSDB migration test kit`.
- Closes #7215 
Refer #7215
> [Azure][Storage_account] Enable TSDB

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
CloudFormation: Use link parametrized only by version, removes the need to open a new PR for each change.
Additionally, fixes the tag issue for CNVM that was forgotten in #8226.
<!-- Recommended
- https://github.com/elastic/cloudbeat/pull/1415
- #8226
- https://github.com/elastic/cloudbeat/issues/1320
> [Cloud Security] Base CloudFormation url only on version

- packages/system/changelog.yml
- packages/system/data_stream/security/fields/winlog.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/fields/winlog.yml
- packages/windows/manifest.yml
Added `winlog.event_data.EnabledPrivilegeList` field as type "keyword" in the following integrations:
- windows integration, forward data stream
- system integration, security data stream
This is needed for rule verification in the "security_detection_engine" integration and the "SeDebugPrivilege Enabled by a Suspicious Process" rule.
- Closes elastic/kibana#169077
> Added field `winlog.event_data.EnabledPrivilegeList` to windows and system integration

- packages/kubernetes/changelog.yml
- packages/kubernetes/kibana/dashboard/kubernetes-9bf990a0-bcb1-11ec-b64f-7dd6e8e82013.json
- packages/kubernetes/manifest.yml
- High
- Enhancement
- Manually migrate `K8s Jobs` visualizations to the lens in the current Kibana version `8.10.2` itself. 
- Statistics for `K8s Jobs` Lens migration:
  | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Vizualization | Lens | Vizualization
[Metrics Kubernetes] Jobs | 2 | 3 | 5 | 0
- Relates #7774
Before Migration:
After Migration:
> [O11y][K8] Migrate `Jobs`  dashboard visualizations to lens

- packages/airflow/changelog.yml
- packages/airflow/data_stream/statsd/fields/ecs.yml
- packages/airflow/manifest.yml
- packages/cockroachdb/changelog.yml
- packages/cockroachdb/data_stream/status/fields/ecs.yml
- packages/cockroachdb/manifest.yml
Add `dimension: true` for a couple of packages (airflow and cockroachdb) which was previously missed in https://github.com/elastic/integrations/pull/8170 during package-spec v3 migration.
> Add `dimension` field previously missed during package-spec v3 migration

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-security-1100.json
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-security-1100.json-expected.json
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
Apparently some events from Windows servers and workstations in Security channel have a lowercase channel name. This has not been observed in other channels, but defensively apply the same care there.
- For elastic/beats#36670
> windows: make pipeline routing robust to channel letter case

- packages/ti_rapid7_threat_command/changelog.yml
- packages/ti_rapid7_threat_command/manifest.yml
This package fails to start in stacks without the security plugin, as it requires
the security rule object type.
When trying to install with `elastic-package install`:
```
Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Encountered 2 errors creating saved objects: [{\"type\":\"security-rule\",\"id\":\"af814670-3279-11ed-93fa-d354b323cd1b\",\"error\":{\"type\":\"unsupported_type\"}},{\"type\":\"security-rule\",\"id\":\"eaecc8f0-6704-11ed-80b2-9bbc46f73b72\",\"error\":{\"type\":\"unsupported_type\"}}]"}
```
Add the required capabilities to the manifest.
As a follow up we will need to remove the 1.10.0 and 1.11.0 versions of the package from the registry. cc @mrodm
- Found in …
> [ti_rapid7_threat_command] Fix required stack capabilities

- packages/google_workspace/changelog.yml
- packages/google_workspace/manifest.yml
- packages/infoblox_bloxone_ddi/changelog.yml
- packages/infoblox_bloxone_ddi/data_stream/dns_config/manifest.yml
- packages/infoblox_bloxone_ddi/data_stream/dns_data/manifest.yml
- packages/infoblox_bloxone_ddi/manifest.yml
> google_workspace,infoblox_bloxone_ddi: fix documentation for initial interval config

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c15fb1a4e164e788ec733011f29430e3a1b76d03
* https://github.com/elastic/ia-trade-team/issues/197
None
> [Security Rules] Update security rules package to v8.8.13

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/46c430d4d447e5bee2f45cf122f9e0de13330de7
* https://github.com/elastic/ia-trade-team/issues/197
None
> [Security Rules] Update security rules package to v8.10.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/38bc110dc50d090a1acfcf4176fd576c6ca99c0b
* https://github.com/elastic/ia-trade-team/issues/197
None
> [Security Rules] Update security rules package to v8.11.2

- packages/tcp/changelog.yml
- packages/tcp/data_stream/generic/manifest.yml
- packages/tcp/manifest.yml
- packages/tcp/validation.yml
- packages/udp/changelog.yml
- packages/udp/data_stream/generic/manifest.yml
- packages/udp/manifest.yml
- packages/udp/validation.yml
This PR adds two flags to the datastream manifest for the TCP and UDP input packages, which allows the use of reroute processors, this is similar to for example https://github.com/elastic/integrations/pull/6340/.
- Relates #6340
> [UDP/TCP] Add reroute processor support

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
- packages/cloud_security_posture/manifest.yml
The GCP Organization ID must be explicitly passed to the agent as string to avoid parsing issues.
-
> [cloud_security_posture] GCP OrganizationId must be string

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/pf_elastic_collector/fields/base-fields.yml
- packages/elastic_agent/data_stream/pf_elastic_collector/fields/ecs.yml
- packages/elastic_agent/data_stream/pf_elastic_collector/fields/fields.yml
- packages/elastic_agent/data_stream/pf_elastic_collector/manifest.yml
- packages/elastic_agent/data_stream/pf_elastic_symbolizer/fields/base-fields.yml
- packages/elastic_agent/data_stream/pf_elastic_symbolizer/fields/ecs.yml
- packages/elastic_agent/data_stream/pf_elastic_symbolizer/fields/fields.yml
- packages/elastic_agent/data_stream/pf_elastic_symbolizer/manifest.yml
- packages/elastic_agent/data_stream/pf_host_agent_logs/fields/base-fields.yml
- packages/elastic_agent/data_stream/pf_host_agent_logs/fields/ecs.yml
- packages/elastic_agent/data_stream/pf_host_agent_logs/fields/fields.yml
- packages/elastic_agent/data_stream/pf_host_agent_logs/manifest.yml
- packages/elastic_agent/manifest.yml
So far logs of Universal Profiling services were not picked and indexed to make them available via Kibana. Add a dedicated `data_stream` for each Universal Profiling service.
> [elastic_agent] add data_streams for Universal Profiling services

- packages/modsecurity/changelog.yml
- packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
- packages/modsecurity/data_stream/auditlog/fields/ecs.yml
- packages/modsecurity/docs/README.md
- packages/modsecurity/manifest.yml
See title.
- Ref https://github.com/elastic/elastic-package/issues/1451#issuecomment-1774861044
> modsecurity: add missing destination.{as,geo}.* field definitions and mapping

- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/data_stream/metrics/manifest.yml
- packages/hashicorp_vault/manifest.yml
- Enhancement
- WHAT : Enable time series data streams for the metrics datasets.
- WHY :  This improves storage usage and query performance. 
Completed the data verification using TSDB Migration Toolkit
elastic-package stack up -v -d --services package-registry
Install / Update the package
Index settings and mapping verifications
- Relates #8128 
Package installation validation
Index settings validation
> [Hashicorp Vault] TSDB enablement for Hashicorp vault

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/log/fields/ecs.yml
- packages/cisco_meraki/docs/README.md
- packages/cisco_meraki/manifest.yml
- packages/zscaler_zpa/changelog.yml
- packages/zscaler_zpa/data_stream/browser_access/elasticsearch/ingest_pipeline/default.yml
- packages/zscaler_zpa/manifest.yml
cisco_meraki:
* add missing definitions for `client.as.{number,organization.name)`.
zscalar_zpa:
* rename `client.as.{asn,organization_name}` to their corresponding ECS fields.
- Ref https://github.com/elastic/elastic-package/issues/1451#issuecomment-1774861044
> cisco_meraki,zscalar_zpa: fix field mappings and definitions

- packages/system/_dev/deploy/docker/docker-compose.yml
- packages/system/_dev/deploy/docker/sample_logs/syslog.log
- packages/system/changelog.yml
- packages/system/data_stream/syslog/_dev/test/system/test-default-config.yml
- packages/system/data_stream/syslog/agent/stream/log.yml.hbs
- packages/system/data_stream/syslog/fields/agent.yml
- packages/system/data_stream/syslog/fields/ecs.yml
- packages/system/data_stream/syslog/fields/fields.yml
- packages/system/data_stream/syslog/sample_event.json
- packages/system/docs/README.md
- packages/system/manifest.yml
- Fix indentation of tags inside `system.syslog` input configuration.
- Add system tests for `system.syslog` datastream
- Add missing fields "input.type", "log.file.path", and "log.offset" into syslog datastream.
`$  elastic-package stack down && elastic-package build && elastic-package stack up --version=8.10.3 -d -v 
&& eval "$(elastic-package stack shellinit)" && elastic-package test system --generate --data-streams syslog -v `
```
--- Test results for package: system - START ---
╭─────────┬─────────────┬───────────┬───────────┬────────┬──────────────╮
│ PACKAGE │ DATA STREAM │ TEST TYPE │ TEST NAME │ RESULT │ TIME ELAPSED │
├─────────┼─────────────┼───────────┼───────────┼────────┼──────────────┤
│ system  │ syslog      │ system    │ default   │ PASS   │  44.8591515s │ …
```
> [System] Fix indentation of tags inside syslog datastream

- .ci/Jenkinsfile
- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/docs/README.md
Add support for Kubernetes latest version 1.28.
https://github.com/elastic/observability-dev/issues/2802
> [Kubernetes] Update K8s version for 1.28 compatibility

- packages/cisco_meraki/changelog.yml
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-airmarshal-events.log-expected.json
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-events.log-expected.json
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log-expected.json
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-ip-flow.log
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-ip-flow.log-expected.json
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-security-events.log-expected.json
- packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-urls.log-expected.json
- packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/ipflows.yml
- packages/cisco_meraki/manifest.yml
Several dissect processors have been replaced by a `kv` processor that makes the processing of `ip_flow` events less restrictive, so now ICMP events are also processed as well as TCP/UDP ones.
The changes related to this fix are applied in the `ipflows` ingest pipeline and the test file test-ip-flow.log. Further changes in the pull request are a consequence of unrelated changes that fixed the format of some special characters when running pipeline tests.
> [Cisco Meraki] Simplify ipflows pipeline to cover ICMP events

- .ci/Jenkinsfile
Now benchmarks results are generated as JSON files, this changes Jenkinsfile to use these instead of the old XML ones.
> [ci] Fix Jenkinsfile to use the json files for pipeline benchmarks reporting

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
- packages/o365/data_stream/audit/manifest.yml
- packages/o365/manifest.yml
If an API call takes some time to reach the server, the startTime parameter may have slipped into the time before 168h before now. So reduce our window from 168h to 167h55m to allow leeway for this.
Similarly, the allowable interval from start to end time is 24h, and it is possible that the end time now() call is some time after the start time now() call. CEL has no subexpression evaluation order guarantee, so we cannot ensure end is called first by re-ordering the lines. So work around the old behaviour of the now global until the kibana.version for the package is guaranteed to provide an eval-start now value, when we are depending on v8.10.1 (v8.9.1 is also valid, but limiting on that would allow v8.10.0 which does not have the fix).
-
> o365: prevent API calls having a start time more than 168h in the past

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/container_registry/fields/fields.yml
- packages/azure_metrics/data_stream/database_account/fields/package-fields.yml
- packages/azure_metrics/docs/README.md
- packages/azure_metrics/docs/container_registry.md
- packages/azure_metrics/manifest.yml
- add missing dimensions to the database_account datastream
- fix typo in the fields definition of the container_registry datastream
-
> [azure_metrics] add missing dimensions to the database_account datastream; fix typo in container_registry datastream

- packages/atlassian_confluence/_dev/deploy/docker/files/config.yml
- packages/atlassian_confluence/changelog.yml
- packages/atlassian_confluence/data_stream/audit/agent/stream/httpjson.yml.hbs
- packages/atlassian_confluence/data_stream/audit/sample_event.json
- packages/atlassian_confluence/docs/README.md
- packages/atlassian_confluence/manifest.yml
Currently the pagination settings specifically for atlassian cloud do not have a failure condition on pagination, and therefore ends up paginating forever.
There is a few ways to resolve this, I think maybe the best approach would have been to simply utilize the "next" link that is included in each response, as the "next" value is missing once there is no more results. This is done for the on-prem version of confluence (and other atlassian products like jira).
However to keep the state working as it is, I have added the failure condition instead, which also works just fine.
There should be some investigation into making the pagination smarter on these niche scenarios.
> [Atlassian Confluence] Adding new pagination conditions

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/auditbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/auditbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/beat-stats-fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_input_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/filebeat_input_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/filebeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/metricbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/osquerybeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_metrics/fields/ecs.yml
- packages/elastic_agent/data_stream/packetbeat_metrics/fields/fields.yml
- packages/elastic_agent/manifest.yml
The metrics from Elastic-Agent package define some time series but
not enough dimensions for the entries to be unique. This commit adds
new mappings and dimensions to make all metrics events unique as well
as unifies the dimensions from Elastic-Agent and Beats.
The combination of the dimension fields plus the timestamp field must be unique within the timeseries. In the case of the indexes used by the Elastic-Agent integration that will make Elasticsearch return 409 Conflict for the duplicated event.
This PR uses the following fields for metrics from Elastic-Agent and Beats:
- `agent.id`: Each deployed Elastic-Agent has got a unique ID, this ID is present in each event generated by its components, hence different Beats process share the same ID.
- `component.id`: Each component run by …
> Improve and unify dimensions for Elastic-Agent and Beats metrics

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
- packages/o365/data_stream/audit/manifest.yml
- packages/o365/manifest.yml
API responses may be very large, so allow users to specify the length of the response interval. Set the default to a reasonably short value to favour a slow flow rate over an OOM for the worse case.
-
> o365: allow user configuration of API request batch size

- packages/etcd/changelog.yml
- packages/etcd/data_stream/leader/fields/fields.yml
- packages/etcd/data_stream/leader/sample_event.json
- packages/etcd/docs/README.md
- packages/etcd/manifest.yml
- Bug
Fix the field mappings under leader datastream
The field mapping of the leader datastream is incorrect. 
This change fixes the incorrect field mapping.
- Verification of field mappings after the change
- Closes #8373
> [etcd] Fix incorrect field mapping in leader dataset

- catalog-info.yaml
Updates the cron to trigger the schedule-daily Buildkite pipeline, so it runs similar to when Jenkins runs this same pipeline (tried to not use the same hours as in Jenkins to avoid creating so many VMs at the same time):  https://github.com/elastic/integrations/blob/c87d2f78f530d281fc9a2823de3c1b0a7e8a4605/.ci/schedule-daily.groovy#L22
-
> [Buildkite] Update cronline for schedule-daily job

- .buildkite/scripts/common.sh
- .buildkite/scripts/test_integrations_with_serverless.sh
- .buildkite/scripts/test_one_package.sh
- .buildkite/scripts/trigger_integrations_in_parallel.sh
Fix the calculation of from and to changesets when the build is triggered from the `main` or `backport-*` branches.
Moreover, this calculation has been move at the beginning of the pipeline. This help us to avoid querying to Buildkite for the previous builds for each package tested.
- Relates https://github.com/elastic/integrations/pull/8316
- Relates https://github.com/elastic/integrations/pull/8462
> [Buildkite] Reuse from and to changesets in Buildkite scripts

- .buildkite/scripts/common.sh
Fixes the value of the commit got from the Buldkite API to use raw strings.
Previously, the strings of those variables contained double quotes and it caused that git commands failed.
- Relates https://github.com/elastic/integrations/pull/8463
> [Buildkite] Output raw strings instead of JSON strings in commits from API

- packages/gcp/changelog.yml
- packages/gcp/data_stream/audit/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/audit/fields/fields.yml
- packages/gcp/data_stream/audit/manifest.yml
- packages/gcp/data_stream/audit/sample_event.json
- packages/gcp/data_stream/dns/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/dns/fields/fields.yml
- packages/gcp/data_stream/dns/manifest.yml
- packages/gcp/data_stream/dns/sample_event.json
- packages/gcp/data_stream/firewall/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/firewall/fields/fields.yml
- packages/gcp/data_stream/firewall/manifest.yml
- packages/gcp/data_stream/firewall/sample_event.json
- packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-expected.json
- packages/gcp/data_stream/vpcflow/agent/stream/gcp-pubsub.yml.hbs
- packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
- packages/gcp/data_stream/vpcflow/fields/fields.yml
- packages/gcp/data_stream/vpcflow/manifest.yml
- packages/gcp/data_stream/vpcflow/sample_event.json
- packages/gcp/docs/README.md
- packages/gcp/docs/audit.md
- packages/gcp/docs/dns.md
- packages/gcp/docs/firewall.md
- packages/gcp/docs/vpcflow.md
- packages/gcp/manifest.yml
> gcp: add keep_json option for audit, dns, firewall and vpcflow datastreams

- packages/cloudflare_logpush/_dev/build/docs/README.md
- packages/cloudflare_logpush/changelog.yml
- packages/cloudflare_logpush/docs/README.md
- packages/cloudflare_logpush/manifest.yml
We have recently received feedback reporting that when configuring the HTTP endpoint for Cloudflare Logpush, incoming HTTP messages may contain an invalid `Content-Type` header while the HTTP endpoint input expects `application/json`. It leads to this error:
```
"error_message": "error 415: error pushing: error uploading to https: 415 {\"message\":\"wrong Content-Type header, expecting application/json\"}",
```
This pull request defines the `Content-Type` header when configuring the destination for the HTTP endpoint in the setup guide.
- Closes https://github.com/elastic/integrations/issues/8342
> [Cloudflare Logpush] Add content-type header to HTTP endpoint setup docs

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
- packages/ti_misp/data_stream/threat_attributes/manifest.yml
- packages/ti_misp/manifest.yml
EnforceWarningList is a request body parameter that is used in the MISP API to filter out values that are believed to be false positives, as documented here: https://www.circl.lu/doc/misp/warninglists/#misp-warning-lists-introduction-the-dilemma-of-false-positive
SPEC: https://raw.githubusercontent.com/MISP/MISP/develop/app/webroot/doc/openapi.yaml
I decided to instead of setting this to true or false in the .yml.hbs file, I only actually set it once its true, in case older versions of MISP do not support this parameter. The default value is also false, to not change any behavior by default when upgrading.
> [TI_MISP] Add support for EnforceWarningList filter parameter

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6bbb29399564cd2a624903e255d7d00ef2bdcf8a
None
None
> [Security Rules] Update security rules package to v8.8.14

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b77b7fc53e3b9e919b0631386d21b3d275f2236e
None
None
> [Security Rules] Update security rules package to v8.9.9

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b342660c3a08c3a3b402fd8414fc1a4f32d94a64
None
None
> [Security Rules] Update security rules package to v8.11.3

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
- packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
- packages/cloud_security_posture/manifest.yml
As mentioned on https://github.com/elastic/cloudbeat/issues/1478 currently only CSPM AWS runs on a 24h cycle, GCP and Azure run on a 4h cycle (default value), while all CSPM should run on a 24h period.
Add 24h period configuration to all CSPMs. AWS already had, added to GCP and Azure.
- Closes https://github.com/elastic/cloudbeat/issues/1478
> Add 24h period configuration to all CSPM providers

- packages/osquery_manager/changelog.yml
- packages/osquery_manager/data_stream/result/fields/osquery.yml
- packages/osquery_manager/manifest.yml
Upgrades osquery mappings to match osquery 5.10.2 schema
- Requires https://github.com/elastic/beats/pull/37115
> Osquery_manager: Upgrade osquery mappings to match osquery 5.10.2 schema

- packages/ded/changelog.yml
- packages/ded/docs/README.md
- packages/ded/kibana/ml_module/ded-ml.json
- packages/ded/manifest.yml
- packages/dga/changelog.yml
- packages/dga/docs/README.md
- packages/dga/kibana/ml_module/dga-ml.json
- packages/dga/manifest.yml
- packages/lmd/changelog.yml
- packages/lmd/docs/README.md
- packages/lmd/elasticsearch/transform/pivot_transform/transform.yml
- packages/lmd/kibana/ml_module/lmd-ml.json
- packages/lmd/manifest.yml
- packages/problemchild/changelog.yml
- packages/problemchild/docs/README.md
- packages/problemchild/kibana/ml_module/problemchild-ml.json
- packages/problemchild/manifest.yml
Per discussion brought up by @SourinPaul , here is a draft PR illustrating what the packages would look like with the data frozen tier and data cold tier filtered out. The PR also lints/formats these files with `elastic-package` to make sure the additional field conforms to style guides.
However, we must first discuss with the authors of those respective packages if that is the **expected behavior** before merging. @ajosh0504 @sodhikirti07 [Edit] We've discussed these changes and gotten approval.
Affected packages:
Additional info:
> Apoorva - Agree with the suggestion [...] to exclude cold/frozen tier from the module query. We seem to be doing it in our OOTB jobs in Kibana as well, so looks like the way to go to prevent ML jobs from hitting those tiers. Eg: …
> Set frozen/cold tier for Security ML integrations

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/compute_vm/manifest.yml
- packages/azure_metrics/data_stream/compute_vm_scaleset/manifest.yml
- packages/azure_metrics/data_stream/container_instance/manifest.yml
- packages/azure_metrics/data_stream/container_registry/manifest.yml
- packages/azure_metrics/data_stream/container_service/manifest.yml
- packages/azure_metrics/data_stream/database_account/manifest.yml
- packages/azure_metrics/data_stream/monitor/manifest.yml
- packages/azure_metrics/data_stream/storage_account/manifest.yml
- packages/azure_metrics/manifest.yml
Add permissions to reroute metrics events in all data streams in Azure Metrics.
The additional permissions will allow us to route metrics events to use the Azure resource type as dataset to partition metrics.
Rerouting can be set up by defining routing rules at the integration level or allowing users to add a [reroute processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/reroute-processor.html) to the custom ingest pipeline.
1. Install the Azure Monitor integration
2. Add a custom pipeline
Here's a sample custom pipeline:
```
[
{
"reroute": {
"dataset": [
"whatever"
],
"if": "ctx.network?.name == 'Whatever'"
}
}
]
```
**Note**: don't forget to set `_index` to a valid value like `metrics-azure.monitor-default`, or you'll get an error from the pipeline simulator. 
Test …
> Allow rerouting of Azure Metrics events to a different data stream

- packages/aws/changelog.yml
- packages/aws/data_stream/sqs/agent/stream/stream.yml.hbs
- packages/aws/data_stream/sqs/elasticsearch/ingest_pipeline/default.yml
- packages/aws/data_stream/sqs/fields/fields.yml
- packages/aws/docs/sqs.md
- packages/aws/manifest.yml
This PR changes the statistic method that we use to pull SQS cloudwatch metrics. 
ApproximateAgeOfOldestMessage: average -> max
NumberOfMessagesDeleted: average -> sum
NumberOfEmptyReceives: average -> sum
NumberOfMessagesReceived: average -> sum
NumberOfMessagesSent: average -> sum
> [AWS] Change SQS metrics statistic method

- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-expected.json
- packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_umbrella/manifest.yml
Previously, the `cisco.umbrella._tmp` field was unconditionally being assigned a new hash map when `cisco.umbrella.identity` contained multiple identities, deleting already collected information including the `@timestamp`. Fix this by making the map construction conditional.
- Fixes #8517
> cisco_umbrella: don't clobber temporary field when collecting identities

- .ci/jobs/integrations-daily.yml
- .ci/schedule-daily.groovy
- catalog-info.yaml
This PR disables Jenkins daily job in favor of the Buildkite pipeline:
- https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations-daily/
- https://buildkite.com/elastic/integrations-schedule-daily/
- ~[ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~
-
> Disable jenkins daily job in favor of Buildkite pipeline

- packages/sophos/changelog.yml
- packages/sophos/data_stream/utm/_dev/test/pipeline/test-sophos-utm-dhcp.log-expected.json
- packages/sophos/data_stream/utm/_dev/test/pipeline/test-sophos-utm-dns.log-expected.json
- packages/sophos/data_stream/utm/_dev/test/pipeline/test-sophos-utm-http.log-expected.json
- packages/sophos/data_stream/utm/_dev/test/pipeline/test-sophos-utm-packetfilter.log-expected.json
- packages/sophos/data_stream/utm/elasticsearch/ingest_pipeline/default.yml
- packages/sophos/data_stream/utm/sample_event.json
- packages/sophos/docs/README.md
- packages/sophos/manifest.yml
The security app depends on the host.name field to be set in order for hosts to be visible. The utm datastream currently sets the `host.hostname` to the host name present in the syslog header. Copy that value across to `host.name` as lowercase to ensure that hosts are visible in the app.
- Closes #8528
> sophos: retain host name information in host.name as well as host.hostname

- .ci/schedule-daily.groovy
8.11.0 has been released. Move daily testing toward 8.12-SNAPSHOT.
https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations-daily/
> ci - bump daily job to use 8.12-SNAPSHOT

- .buildkite/pipeline.schedule-daily.yml
8.11.0 has been released. Move daily testing toward 8.12-SNAPSHOT.
https://buildkite.com/elastic/integrations-schedule-daily/builds?branch=main
- Relates https://github.com/elastic/integrations/pull/8471
> [Buildkite] Update buildkite daily job as in Jenkins

- packages/auditd_manager/changelog.yml
- packages/auditd_manager/data_stream/auditd/agent/stream/auditd.yml.hbs
- packages/auditd_manager/data_stream/auditd/manifest.yml
- packages/auditd_manager/manifest.yml
The valid options for socket_type in auditbeat are unicast, multicast and '', checked during config validation, so provide a selection which maps 'auto' to ''.
Unfortunately, we are not able to check that the combination of socket type and immutability are valid (this would require that we be able to compare a value in the template to 'multicast', but no comparison helpers exist in the handlbars instance used for integration config templates). The best we can do is tell users not to do this; it will show up in log failures.
- Closes #8557
> auditd_manager: make socket type selection a set of options and correct documentation

- packages/trendmicro/_dev/deploy/docker/docker-compose.yml
- packages/trendmicro/changelog.yml
- packages/trendmicro/data_stream/deep_security/_dev/test/system/test-filestream-config.yml
- packages/trendmicro/data_stream/deep_security/_dev/test/system/test-tcp-config.yml
- packages/trendmicro/data_stream/deep_security/_dev/test/system/test-tls-config.yml
- packages/trendmicro/data_stream/deep_security/_dev/test/system/test-udp-config.yml
- packages/trendmicro/data_stream/deep_security/agent/stream/stream.yml.hbs
- packages/trendmicro/data_stream/deep_security/agent/stream/tcp.yml.hbs
- packages/trendmicro/data_stream/deep_security/agent/stream/udp.yml.hbs
- packages/trendmicro/data_stream/deep_security/manifest.yml
- packages/trendmicro/manifest.yml
> trendmicro: add support for tls and test tcp/udp inputs

- packages/entityanalytics_entra_id/_dev/build/docs/README.md
- packages/entityanalytics_entra_id/changelog.yml
- packages/entityanalytics_entra_id/docs/README.md
- packages/entityanalytics_entra_id/manifest.yml
This PR updates the minimum compatible Kibana version for Microsoft Entra ID Entity Analytics integration.
Closes https://github.com/elastic/integrations/issues/8422
> Update the Kibana version for Microsoft Entra ID Entity Analytics integration

- packages/elastic_agent/data_stream/auditbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/beat-stats-fields.yml
- packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_logs/fields/fields.yml
Added `beat.stats.libbeat.pipeline.queue.max_events` to elastic agent mappings as introduced/exposed in https://github.com/elastic/beats/pull/37189
> Added `beat.stats.libbeat.pipeline.queue.max_events` to elastic agent

- packages/iis/changelog.yml
- packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/iis/manifest.yml
- Bug
The datatype for `network.forwarded_ip` field is set to `IPORHOST` in the ingest pipeline processor. The datatype should be of type `IP`
- Fixes #7426
> Fix network.forwarded_ip datatype in ingest pipeline

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/sample_event.json
- packages/network_traffic/data_stream/cassandra/sample_event.json
- packages/network_traffic/data_stream/dhcpv4/sample_event.json
- packages/network_traffic/data_stream/dns/sample_event.json
- packages/network_traffic/data_stream/flow/sample_event.json
- packages/network_traffic/data_stream/http/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/http/fields/protocol.yml
- packages/network_traffic/data_stream/http/sample_event.json
- packages/network_traffic/data_stream/icmp/elasticsearch/ingest_pipeline/default.yml
- packages/network_traffic/data_stream/icmp/sample_event.json
- packages/network_traffic/data_stream/memcached/sample_event.json
- packages/network_traffic/data_stream/mongodb/sample_event.json
- packages/network_traffic/data_stream/mysql/sample_event.json
- packages/network_traffic/data_stream/nfs/sample_event.json
- packages/network_traffic/data_stream/pgsql/sample_event.json
- packages/network_traffic/data_stream/redis/sample_event.json
- packages/network_traffic/data_stream/sip/sample_event.json
- packages/network_traffic/data_stream/thrift/sample_event.json
- packages/network_traffic/data_stream/tls/sample_event.json
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
Currently, detection rules depend on three non-ECS-compliant fields:
- `type` (all except flows)
- `http.request.headers.authorization` (http)
- `http.response.headers.content-type` (http)
With the exception of flows and icmp, `type` is already set in `network.protocol` as well. So make the following copies:
- `type` field into `network.protocol` for icmp
- `http.request.headers.authorization` to `network_traffic.http.request.headers.authorization` for http
- `http.response.headers.content-type` to `http.response.mime_type` for http
- For #8185
> network_traffic: copy non-ECS fields to ECS-compliant locations for detection rules

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.8.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d0411d6828c65addaf341a2b25504e3d600d8dd4
None
None
> [Security Rules] Update security rules package to v8.8.15

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/700f3c45f91572088b8d5812433665212743493f
None
None
> [Security Rules] Update security rules package to v8.9.10

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/9d34fc21aefb4336a771cad1f24d34216ebd783c
None
None
> [Security Rules] Update security rules package to v8.10.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/1d05f4943659dcb3529ef6fa601342d5efb28e9a
None
None
> [Security Rules] Update security rules package to v8.11.4

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/data_stream/audit/elasticsearch/ingest_pipeline/pipeline-json.yml
- packages/elasticsearch/manifest.yml
Fixes an issue where `elasticsearch.audit.user.run_as.name` being missing would cause the processor to error (though ignored).
This is an issue because in high throughput clusters, these error numbers can skew failure ratios with other processors.
- Closes #8305
Before Upgrade:
After Upgrade:
> [Elasticsearch] Pipeline Convert Processor `ignore_missing` for `elasticsearch.audit.user.run_as.name`

- packages/redisenterprise/changelog.yml
- packages/redisenterprise/data_stream/node/manifest.yml
- packages/redisenterprise/data_stream/proxy/manifest.yml
- packages/redisenterprise/manifest.yml
This PR enables TSDB for RedisEnterprise.
- Closes #6268
> [RedisEnterprise] Enable TSDB

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Support Azure account type for organizations.
- Closes https://github.com/elastic/cloudbeat/issues/1597
> [cloud_security_posture] Support Azure account type

- packages/prisma_cloud/changelog.yml
- packages/prisma_cloud/data_stream/alert/agent/stream/input.yml.hbs
- packages/prisma_cloud/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
- packages/prisma_cloud/data_stream/alert/manifest.yml
- packages/prisma_cloud/data_stream/alert/sample_event.json
- packages/prisma_cloud/data_stream/audit/agent/stream/input.yml.hbs
- packages/prisma_cloud/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/prisma_cloud/data_stream/audit/manifest.yml
- packages/prisma_cloud/data_stream/audit/sample_event.json
- packages/prisma_cloud/data_stream/host/manifest.yml
- packages/prisma_cloud/data_stream/host_profile/manifest.yml
- packages/prisma_cloud/docs/README.md
- packages/prisma_cloud/manifest.yml
Type of change
- BugFix
**1. Change the default value of HTTP Client Timeout from 30s to 60s**
For the larger dataset, Prisma API is taking a longer wait time to send the response that is greater than `30s` hence update the default value of timeout to `60s` for all the data streams.
**2. Update the Cursor Logic of the Alert and Audit Data Stream**
There was a bug in the cursor implementation, earlier it was storing the value  `(now - lastUpdated.max)` which resulted in the wrong subsequent requests call. Hence updated the cursor implementation to `now() - cursor` at the time of request call.
Also, use `getMinutes()` instead of `getHours()` to get a more precise time as the Prisma API filter supports the minimum time unit as a minute.
**3. Add fingerprint to the Audit Data Stream.**
As the …
> [prisma_cloud] Update the Cursor in the Data Collection of Alert and Audit Data Stream and HTTP Timeout Default Values

- packages/fleet_server/changelog.yml
- packages/fleet_server/data_stream/output_health_logs/elasticsearch/ilm/default_policy.json
- packages/fleet_server/data_stream/output_health_logs/fields/base-fields.yml
- packages/fleet_server/data_stream/output_health_logs/fields/fields.yml
- packages/fleet_server/data_stream/output_health_logs/lifecycle.yml
- packages/fleet_server/data_stream/output_health_logs/manifest.yml
- packages/fleet_server/manifest.yml
Start kibana locally and upload the new version of the package from `/build/packages` folder (or use elastic-package)
```
curl -XPOST -H 'content-type: application/zip' -H 'kbn-xsrf: true' http://localhost:5601/api/fleet/epm/packages -u elastic:changeme --data-binary @fleet_server-1.5.0.zip
```
The package installs successfully and the index template is created with the right fields and ilm policy.
The data streams are going to be populated by fleet-server: https://github.com/elastic/fleet-server/pull/3127
The output health will be queried by kibana by output id (output keyword field) to show the state of remote es outputs on UI 
Relates https://github.com/elastic/fleet-server/issues/3116
> added output_health data stream to fleet_server

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
We need to pull the templates from `main` branch up until we branch out to `8.12`.
-
> [cloud_security_posture] Bump Azure ARM template branch to main until 8.12 branch created

- packages/apache_tomcat/changelog.yml
- packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/apache_tomcat/manifest.yml
The customer is using this Integration on an ESS and had ~10-14ms per doc average processing Time.
After taking a look at the pipeline definition I recognised the "inefficient" way how the grok processing is done.
First test of restructuring the grok process (without changing what it is doing, just how it is done) I had an average of 0-5-0.-7ms, so a huge performance improvement with just a little restructuring.
> [apache_tomcat.access] Restructure Grok pattern and ingest pipeline to improve performance

- packages/ti_opencti/changelog.yml
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-domain-name-with-external-reference.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-domain-name-with-external-reference.json-expected.json
- packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
- packages/ti_opencti/manifest.yml
```
[ti_opencti] Fix processing of externalReferences (#8556)
The contents of externalReferences.edges were being processed with the
append processor and mistakenly flattened into scalar values. To fix
that they are now handled in Painless, as objects.
Additional checks were added for collection fields that may be null,
after some were observed in example data added to test the
externalReferences fix.
```
```
cd packages/ti_opencti
elastic-package stack up -d
elastic-package test -v
```
- Closes #8457
> [ti_opencti] Fix processing of externalReferences

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Adopt Secrets in Cloud Posture Management
Based on https://github.com/elastic/package-spec/pull/665 definition of what is possibly a secret the following the keys were labeled as secrets:
- cloudbeat/cis_eks
- session_token
- cloudbeat/cis_aws
- secret_access_key
- cloudbeat/cis_azure
- azure.credentials.client_secret
- azure.credentials.client_password
- azure.credentials.client_certificate_password
Based on the criteria used of what potentially is a secret, more fields would have been classified as secret. Below you can find why they were not:
- cloudbeat/cis_eks
-  session_token 
- Not flagged as secret because it's a temporary token
- cloudbeat/cis_aws
-  session_token 
- Not flagged as secret because it's a temporary token
Adoption of secrets is a [kibana wide effort …
> Adopt Secrets in Cloud Posture Management

- .buildkite/scripts/common.sh
- .buildkite/scripts/process_benchmarks.sh
Fix method to check if a build is part of a Pull Request or not.
Checked in this build from main: https://buildkite.com/elastic/integrations/builds/7057#018c3421-022d-4242-b582-fdaa028454df
In that build, `Publish benchmarks` step must not run since it is a build triggered from main branch.
- Relates #8072
> [Buildkite] Update condition to check whether or not a build is a PR

- packages/activemq/changelog.yml
- packages/activemq/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/activemq/manifest.yml
- packages/coredns/changelog.yml
- packages/coredns/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/coredns/manifest.yml
- packages/ibmmq/changelog.yml
- packages/ibmmq/data_stream/errorlog/elasticsearch/ingest_pipeline/default.yml
- packages/ibmmq/manifest.yml
- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/log/elasticsearch/ingest_pipeline/pipeline-json.yml
- packages/mongodb/manifest.yml
- packages/salesforce/changelog.yml
- packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/login_rest/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/login_stream/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/logout_rest/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/logout_stream/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/data_stream/setupaudittrail/elasticsearch/ingest_pipeline/default.yml
- packages/salesforce/manifest.yml
- packages/spring_boot/changelog.yml
- packages/spring_boot/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
- packages/spring_boot/data_stream/http_trace/elasticsearch/ingest_pipeline/default.yml
- packages/spring_boot/manifest.yml
- packages/vsphere/changelog.yml
- packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/vsphere/manifest.yml
This PR add null and ignore_missing check to handle event.original field in multiple packages which are as follows:
- ActiveMQ
- CoreDns
- IBMMQ
- MongoDB
- Salesforce
- Spring_Boot
- vSphere
- Relates #7822
> Add null and ignore_missing check to handle event.original field.

- packages/azure_billing/changelog.yml
- packages/azure_billing/kibana/dashboard/azure_billing-d3efeb30-c1c7-11ea-b7e7-0f48178cdb3c.json
- packages/azure_billing/manifest.yml
Added global datastream filter to improve dashboard speed and utilization of the cluster. According to the [dashboard guideline](https://github.com/elastic/integrations/blob/43d3ba0422800bfe416bd4a1ef00b78ef2a9f9d0/docs/dashboard_guidelines.md#visualizations-should-contain-a-filter).
closes #6946
> [Enhancement] Add azure.billing filter to dashboard to improve performance

- packages/universal_profiling_agent/changelog.yml
- packages/universal_profiling_agent/manifest.yml
Starting with the release of 8.12 [Kibana will show the required privileges](https://github.com/elastic/kibana/pull/170478) of integrations. Universal Profiling Agent requires `root` privileges to run.
> Universal Profiling: add privileges section

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Bumping version of links for `8.12` branch
- Closes https://github.com/elastic/cloudbeat/issues/1603
> [cloud_security_posture] 8.12 version bump

- packages/iis/_dev/build/docs/README.md
- packages/iis/changelog.yml
- packages/iis/docs/README.md
- packages/iis/manifest.yml
- Enhancement
Add note on the custom access log format processing.
- Closes #8102
> [IIS Access Log]: Update documentation for custom log processing

- packages/sentinel_one_cloud_funnel/changelog.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-command-script.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-cross-process.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-dns.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-file.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-indicator.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-login.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-module.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-network-action.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-process.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-registry.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-scheduled-task.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-threat-intelligence-indicator.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-url.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-process.yml
- packages/sentinel_one_cloud_funnel/manifest.yml
```
[sentinel_one_cloud_funnel] `process.*` changes for Analyzer (#8608)
In order to support Analyzer:
- Populate the `process.entity_id` field.
- For process creation events, populate `process.*` fields with
target/new process information rather than source/parent information.
```
---
**Earlier title**: [EDR Workflows] Adjust Sentinel One Cloud Funnel mappings to support Analyzer - entity_id
**Earlier description**:
This PR adds mapping to `process.entity_id` and `process.parent.entity_id` in default.yml. 
Moreover it overwrites `process.parent` with `src.process` data, and process with `tgt.process` for `process-pipeline.yml`
There was a suggestion that we might actually also map `event.type` more dynamically, because now it's just set to [info]. But this can be done in the future :) …
> [EDR Workflows] Adjust Sentinel One Cloud Funnel mappings to support Analyzer - entity_id

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/data_stream/compute_vm/manifest.yml
- packages/azure_metrics/data_stream/compute_vm_scaleset/manifest.yml
- packages/azure_metrics/data_stream/container_instance/manifest.yml
- packages/azure_metrics/data_stream/container_registry/manifest.yml
- packages/azure_metrics/data_stream/container_service/manifest.yml
- packages/azure_metrics/data_stream/database_account/manifest.yml
- packages/azure_metrics/data_stream/monitor/manifest.yml
- packages/azure_metrics/manifest.yml
Enable tsds on all remaining datastreams
Tested with `TSDB-migration-test-kit`
1. install integration version `1.3.0` - gather some data
2. upgrade integration to `1.4.0`.
3. to run `TSDB-migration-test-kit` set settings:
```
"docs_index": 0,   ## an index 000001 (tsds not enabled yet)
"settings_mappings_index": 1,  ## use settings from the index `000002` (tsds enabled)
```
- Closes https://github.com/elastic/integrations/issues/7140
> [azure_metrics] Enable tsds on all remaining datastreams

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/fields/resource.yml
- packages/cloud_security_posture/data_stream/findings/fields/result.yml
- packages/cloud_security_posture/manifest.yml
Remove fields that had `enabled: false`, to prevent mapping issues
Follow the [guide](https://docs.elastic.dev/security-solution/cloud-security/qa/test-integration-package) to test it locally.
- https://github.com/elastic/security-team/issues/8179
- https://github.com/elastic/cloudbeat/issues/1575
> [Cloud Security] Remove disabled fields

- packages/azure/_dev/build/docs/README.md
- packages/azure/changelog.yml
- packages/azure/docs/README.md
- packages/azure/manifest.yml
On the [Azure Logs](https://docs.elastic.co/integrations/azure) integration doc page, this PR:
- Updates the storage account requirements 
- Simplifies the setup procedure
This doc fix impacts the following Azure doc pages as well:
├── activitylogs
├── application_gateway
├── auditlogs
├── eventhub
├── firewall_logs
├── identity_protection
├── platformlogs
├── provisioning
├── signinlogs
└── springcloudlogs
Closes https://github.com/elastic/integrations/issues/7586
Doc preview:
> Azure Logs - Extend storage account settings

- packages/apache_tomcat/changelog.yml
- packages/apache_tomcat/data_stream/connection_pool/fields/fields.yml
- packages/apache_tomcat/docs/README.md
- packages/apache_tomcat/manifest.yml
This PR proposes a better wording for the field `ms`.
> [Apache Tomcat]: Improve wording on milliseconds

- packages/mongodb/changelog.yml
- packages/mongodb/data_stream/status/fields/fields.yml
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
This PR proposes a better wording for the field `total.ms`.
> [MongoDB]: Improve wording on milliseconds

- packages/postgresql/changelog.yml
- packages/postgresql/data_stream/statement/fields/fields.yml
- packages/postgresql/docs/README.md
- packages/postgresql/manifest.yml
This PR proposes a better wording for the fields `query.time.total.ms`, `query.time.min.ms`, `query.time.max.ms`, and `query.time.mean.ms`.
> [PostgreSQL]: Improve wording on milliseconds

- packages/system/changelog.yml
- packages/system/data_stream/diskio/fields/fields.yml
- packages/system/docs/README.md
- packages/system/manifest.yml
This PR proposes a better wording for the fields `read.time`, `write.time`, and `io.time`.
> [System]: Improve wording on milliseconds

- packages/auth0/changelog.yml
- packages/auth0/data_stream/logs/fields/fields.yml
- packages/auth0/docs/README.md
- packages/auth0/manifest.yml
This PR proposes a better wording for the field `elapsedTime`.
> [Auth0]: Improve wording on milliseconds

- docs/developer_workflow_bug_fix_older_package_version.md
Update backports documentation with the temporary workflow till https://github.com/elastic/integrations/issues/8721 is implemented.
> Update backports developer workflow about permissions to create the branch

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/f36cb548fa7e4077a0894f8cbe4bdb8f5486c7ef
None
None
> [Security Rules] Update security rules package to v8.9.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/69f9bb416d37af8b1627fc7070f45ee8ff448bf9
None
None
> [Security Rules] Update security rules package to v8.11.5

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/08a61054693b2f0f81a6d333c3420cdb8dbb0dad
None
None
> [Security Rules] Update security rules package to v8.12.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/760735c90b41961bae06578bdc005051c40dd036
None
None
> [Security Rules] Update security rules package to v8.10.8

- .buildkite/pipeline.backport.yml
- catalog-info.yaml
Backport pipeline initiation
Added the Buildkite pipeline configuration and "dummy" pipeline
https://github.com/elastic/integrations/issues/8721
> backport pipeline initiation

- packages/gcp/changelog.yml
- packages/gcp/data_stream/cloudrun_metrics/manifest.yml
- packages/gcp/data_stream/cloudsql_mysql/manifest.yml
- packages/gcp/data_stream/cloudsql_postgresql/manifest.yml
- packages/gcp/data_stream/cloudsql_sqlserver/manifest.yml
- packages/gcp/data_stream/compute/manifest.yml
- packages/gcp/data_stream/dataproc/manifest.yml
- packages/gcp/data_stream/gke/manifest.yml
- packages/gcp/data_stream/loadbalancing_metrics/manifest.yml
- packages/gcp/data_stream/pubsub/manifest.yml
- packages/gcp/data_stream/redis/manifest.yml
- packages/gcp/data_stream/storage/manifest.yml
- packages/gcp/manifest.yml
Enables TSDB for metrics data streams.
- Relates #7555
> [GCP] Enable TSDB

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-enriched.log
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-enriched.log-expected.json
- packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/auditd/data_stream/log/fields/fields.yml
- packages/auditd/docs/README.md
- packages/auditd/manifest.yml
Spec for format: https://github.com/linux-audit/audit-documentation/wiki/SPEC-Audit-Event-Enrichment
- Closes #5343
> auditd: handle ENRICHED auditd format

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
- packages/crowdstrike/data_stream/fdr/agent/stream/stream.yml.hbs
- packages/crowdstrike/data_stream/fdr/manifest.yml
- packages/crowdstrike/manifest.yml
> crowdstrike: allow aidmaster metadata to be retained after host enrichment

- .buildkite/pipeline.schedule-daily.yml
- .ci/schedule-daily.groovy
Update version used in schedule daily jobs to be 8.12-SNAPSHOT.
Tested locally with:
```shell
elastic-package stack up -v -d --version 8.12-SNAPSHOT
```
- Relates #8471 
- Relates #8560
> Update schedule daily version to 8.12-SNAPSHOT

- packages/apache_tomcat/changelog.yml
- packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
- packages/apache_tomcat/manifest.yml
Restructuring apache_tomcat.access ingest pipeline to use dissect as first step and split grok into multiple processors to improve perfomance.
On test-env the ingest performance was more den doubled, from ~0.899ms per Document (average) to ~0.253ms per Document (average)
> [apache_tomcat] Improve access pipeline performance by split grok and switch to dissect

- .github/CODEOWNERS
- packages/aws/manifest.yml
- packages/aws_logs/manifest.yml
- packages/awsfargate/manifest.yml
- packages/awsfirehose/manifest.yml
- packages/azure/manifest.yml
- packages/azure_application_insights/manifest.yml
- packages/azure_billing/manifest.yml
- packages/azure_metrics/manifest.yml
- packages/gcp/manifest.yml
- packages/gcp_metrics/manifest.yml
Integrations cloud packages update CODEOWNERS as per [issue](https://github.com/elastic/observability-dev/issues/3000).
> Update cloud packages codeowner

- packages/etcd/_dev/deploy/variants.yml
- packages/etcd/changelog.yml
- packages/etcd/data_stream/metrics/manifest.yml
- packages/etcd/manifest.yml
- Enhancement
- Enable time series data streams for the metrics datasets.
- This improves storage usage and query performance.
- Relates https://github.com/elastic/integrations/issues/8327
https://github.com/elastic/integrations/pull/8438#issue-1984441530
https://github.com/elastic/integrations/pull/8438#issue-1984441530
> [etcd] Enable TSDB for metrics datastream

- packages/ti_opencti/_dev/build/docs/README.md
- packages/ti_opencti/changelog.yml
- packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
- packages/ti_opencti/docs/README.md
- packages/ti_opencti/manifest.yml
```
[ti_opencti] Support OpenCTI 5.12 by removing filters parameter (#8744)
In version 5.12, OpenCTI made breaking changes to how its filters work:
https://docs.opencti.io/5.12.X/reference/filters-migration/
The GraphQL query used in the OpenCTI integration had unused placeholder
parameters for filters, which made the query invalid for 5.12. By
removing the filter parameters, the integration will for 5.12, as well
as earlier versions.
```
The change in this PR can be manually tested by building and installing the integration, and consuming data from the [public demo instance of OpenCTI](https://demo.opencti.io/) (free account required).
Outside of Elastic, the new version of the GraphQL query can be tested in the [GraphQL playground](https://demo.opencti.io/graphql) of the demo instance. …
> [ti_opencti] Support OpenCTI 5.12.X by removing filters parameter

- packages/rapid7_insightvm/changelog.yml
- packages/rapid7_insightvm/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability.log-expected.json
- packages/rapid7_insightvm/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/rapid7_insightvm/data_stream/vulnerability/sample_event.json
- packages/rapid7_insightvm/docs/README.md
- packages/rapid7_insightvm/manifest.yml
See title
`elastic-package stack down && elastic-package build && elastic-package stack up --version=8.11.0 -d -v  --services=elasticsearch && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v`
```
Run pipeline tests for the package
--- Test results for package: rapid7_insightvm - START ---
╭──────────────────┬───────────────┬───────────┬────────────────────────┬────────┬──────────────╮
│ PACKAGE          │ DATA STREAM   │ TEST TYPE │ TEST NAME              │ RESULT │ TIME ELAPSED │
├──────────────────┼───────────────┼───────────┼────────────────────────┼────────┼──────────────┤
│ rapid7_insightvm │ asset         │ pipeline  │ test-asset.log         │ PASS   │   2.026667ms │
│ rapid7_insightvm │ vulnerability │ pipeline  │ test-vulnerability.log │ …
```
> [Rapid7 InsightVM] Split vulnerability categories into array

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_audit.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
- packages/infoblox_nios/manifest.yml
There are 2 style of log formats (regards to how timestamps are handled).
1. `<29>Mar 21 09:53:51 infoblox.localdomain httpd[]: 2022-03-18 13:24:41.705Z [admin]: ........`
2. `<30>Mar 27 08:32:59 infoblox.localdomain dhcpd[2567]: ............`
**Event 1**: Contains 2 timestamps inside the log. In current default pipeline, the first timestamp `Mar 21 09:53:51` is set as `event.created` and then individual pipelines sets second timestamp as `@timestamp` if present.
**Event 2**: Contains 1 timestamp inside the log. In current default pipeline, the only timestamp `Mar 27 08:32:59` is set as `event.created` and a [set processor](https://github.com/elastic/integrations/blob/main/packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L78-L81) copies that into …
> [Infoblox NIOS] Update timestamp parsing logic

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/kibana/csp_rule_template/6e339632-0d1c-5a7c-8ca3-fac5813932d9.json
- packages/cloud_security_posture/kibana/csp_rule_template/72bb12e0-31c0-54f4-a409-4aace3b602be.json
- packages/cloud_security_posture/kibana/csp_rule_template/bb264405-de3e-5b91-9654-2056f905fc67.json
- packages/cloud_security_posture/manifest.yml
Add CIS Azure 6.2, 6.3, 6.4 Rule Template 
Implementations:
- https://github.com/elastic/cloudbeat/pull/1659
- https://github.com/elastic/cloudbeat/pull/1690
- https://github.com/elastic/cloudbeat/pull/1691
Implement Azure CIS benchmarks
- Part of https://github.com/elastic/cloudbeat/issues/1419
> Add CSPM Rules 6.2, 6.3 and 6.4

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Rollback [secrets adoption](https://github.com/elastic/integrations/issues/8610)
Because this [fleet bug is blocking](https://github.com/elastic/kibana/issues/173718) our team
- Rollback because of https://github.com/elastic/kibana/issues/173718
- Re-opens https://github.com/elastic/security-team/issues/7380
> Rollback Cloud Security Posture Secrets Adoption

- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
This PR fixes the parsing of a 113005 Cisco ASA message as follows:
```
<166>ACA1a-FW-FTDV01 %FTD-6-113005: AAA user authentication Rejected : reason = AAA failure : server = 192.168.0.38 : user = scan : user IP = 192.168.0.139
```
The `grok` processor failed because of an unexpected space after `AAA user authentication Rejected`. This can potentially happen with every field so now the pattern expects that every value can be followed by spaces.
> [Cisco FTD] Fix the handling of spaces in 113005 messages

- packages/ti_opencti/changelog.yml
- packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
- packages/ti_opencti/manifest.yml
```
Tolerate suffixes on the OpenCTI instance URL (#8791)
Although a base URL such as 'https://demo.opencti.io' is requested in
the integration settings, we will also tolerate URLs with a trailing
forward slash or '/graphql' path.
```
> Tolerate suffixes on the OpenCTI instance URL

- packages/o365/_dev/build/docs/README.md
- packages/o365/changelog.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
From a suggestion in an SDH, a note in the setup guide has been added explaining that the Token URL can be added to generate auth tokens. Otherwise, the Tenant ID is used for that purpose, which is a required field.
> [o365] Add note about Token URL in the setup guide

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/kibana/dashboard/elasticsearch-ea5b81a0-7fbf-11ed-8509-ddabeb9daeaf.json
- packages/elasticsearch/manifest.yml
In this PR we disable the `otherBucket` aggregation because in combination with the top 100 limit of the two panels it creates a quite heavy query. Since this is a managed dashboards and we do not control the scale of the clusters it runs on we prefer it is as lightweight as possible.
- Dashboard was created in https://github.com/elastic/integrations/pull/4597
> Disable otherBucket option in the panels of ingest pipeline details

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a21bd8e23062763e9657c53b32bdc23df3dc5ca8
None
None
> [Security Rules] Update security rules package to v8.9.12

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/f882c2091960e38d3237407aad50c4d84900a633
None
None
> [Security Rules] Update security rules package to v8.10.9

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/b319d0e68ba3a7911de400665df4ca8901cdf548
None
None
> [Security Rules] Update security rules package to v8.11.6

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/9a1f6e9d207c1437c6e2f31e074dec5c617eca93
None
None
> [Security Rules] Update security rules package to v8.12.2

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/fields/resource.yml
- packages/cloud_security_posture/data_stream/findings/fields/result.yml
- packages/cloud_security_posture/manifest.yml
Those fields were removed in 1.7.1 [[Cloud Security] Remove disabled fields](https://github.com/elastic/integrations/pull/8679/files#top) but then brought back in 1.7.3 [[Cloud security] rollback disabled fields mappings](https://github.com/elastic/integrations/pull/8812/files#top) after discovering an issue in serverless which seemed related to the changes around these fields [[Bug][Cloud Security] Transform fail to index documents after package upgrade](https://github.com/elastic/security-team/issues/8328#top)
After investigation, there was no evidence that the issue discovered affects ESS release, therefore to avoid last-minute changes before the release, this PR is reverting the revert, to get back to the state that was well tested during the QA cycle
> [Cloud Security] revert to have disabled fields removed

- packages/oracle/_dev/build/docs/README.md
- packages/oracle/changelog.yml
- packages/oracle/docs/README.md
- packages/oracle/manifest.yml
- Enhancement
Setting the runtime library path is essential for Oracle Integration to work. 
Document additional methods of setting the runtime library path by setting values in elastic-agent configuration. 
https://github.com/elastic/integrations/issues/8750
> [Oracle] Document alternate method of adding runtime library path

- packages/tenable_io/changelog.yml
- packages/tenable_io/data_stream/asset/agent/stream/httpjson.yml.hbs
- packages/tenable_io/data_stream/asset/sample_event.json
- packages/tenable_io/data_stream/vulnerability/_dev/test/system/test-default-config.yml
- packages/tenable_io/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
- packages/tenable_io/data_stream/vulnerability/sample_event.json
- packages/tenable_io/docs/README.md
- packages/tenable_io/manifest.yml
- Currently there is a way to capture the chain request/responses that is undocumented in the httpjson input. This PR adds the new chain tracer files.
- This PR also adds request tracing into `vulnerability` datastream.
**NOTE:** This PR hardcodes the tracer filenames instead of using the default filename `"../../logs/httpjson/http-request-trace-*.ndjson"`. This is because of the non-sanitisation of chain request tracer filenames explained in https://github.com/elastic/beats/issues/37551 
` elastic-package stack down && elastic-package build && elastic-package stack up --version=8.11.3 -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test system --generate  -v`
```
--- Test results for package: tenable_io - START --- …
```
> [Tenable IO] Add request tracing to vulnerability datastream and capture chain requests

- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/data_stream/log/fields/base-fields.yml
- packages/fortinet_fortigate/manifest.yml
> [fortinet_fortigate]Adapt event.module value

- packages/tcp/changelog.yml
- packages/tcp/data_stream/generic/fields/ecs.yml
- packages/tcp/manifest.yml
- packages/udp/changelog.yml
- packages/udp/data_stream/generic/fields/ecs.yml
- packages/udp/manifest.yml
It has been reported an error in the Custom UDP integration. Since `log.syslog.structured_data` is not defined in the ECS template, each subfield in this object is mapped and indexed separately potentially leading to a mapping explosion. 
This PR adds the missing log.syslog.* ECS mappings to the ECS template in UDP and TCP integrations, so the content of `log.syslog.structured_data` is mapped as a single field. 
```
cd packages/tcp && elastic-package test
cd packages/udp && elastic-package test
```
> [TCP/UDP] Add missing ECS syslog mapping

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/event/_dev/test/pipeline/test-device.log-expected.json
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
- packages/m365_defender/manifest.yml
`process.command_line` was overwritten by `process.parent.command_line` due to a typo in the script parsing the parent.command line 
fix process.command_line overwritten by process.parent.command_line
-
> M365 Defender integration - fix on process.command_line 

- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
Hello Folk, 
I have added one additional nullcheck for the cisco-ftd integration due to experiencing a bug. In certain configurations, it was possible to experience an processing error, causing the integration to crash out on this part. This additional nullcheck is a quick and easy solution with virtually no impact on performance and causing no breaking changes. 
I would also like to recommend to add a pipeline test for the future, to test these changes based on a conversation with @bhapas
> [Cisco FTD] added nullcheck for Network Directionality when zones aren't configured

- packages/aws/changelog.yml
- packages/aws/data_stream/guardduty/agent/stream/httpjson.yml.hbs
- packages/aws/manifest.yml
The calculations for `findingCriteria.criterion.updatedAt.*Than` included a time truncation with the resolution of an hour. This has the effect that if there was no successful execution of the `last_execution_datetime template` the `greaterThan` and `lessThan` values would be equal 1 in hour/initial_interval times, resulting in spurious requests that required satisfaction of a null set. The truncation also prevents progression of the criteria for 1 - (1 in hour/initial_interval) HTTPJSON periodic request cycles.
Not marking as closing the issue as I think there are still problems with the template evaluation that are not currently diagnosable with HTTPJSON's existing template logging (will be able to look at this when v8.11 is more prevalent ).
- For #8601
> aws: fix query range calculation for GuardDuty datastream

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/ecs.yml
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/data_stream/log/fields/ecs.yml
- packages/cisco_ftd/docs/README.md
- packages/cisco_ftd/manifest.yml
See title.
Note that the suggested approach was not used in order to ensure that he workgroup domain prefix is removed from the email address.
- Closes #8895
> cisco_asa,cisco_ftd: retain source and destination user emails if present

- packages/ti_opencti/changelog.yml
- packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
- packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
- packages/ti_opencti/manifest.yml
```
[ti_opencti] Keep expected nulls, improve error handling (#8875)
* Set `keep_null: true` to avoid loss of fields between the CEL
program and the ingest pipeline.
* Handle server responses with errors gracefully in the CEL program
and in the ingest pipeline.  
```
While ingesting from the public demo instance of OpenCTI, I observed a large number of errors, containing the message `Processor "rename" with tag "" in pipeline \"logs-ti_opencti.indicator-0.3.4" failed with message "field [description] doesn't exist"`. The `event.original` value showed that `description` key existed and had a `null` value, and the pipeline did [correctly handle](https://github.com/elastic/integrations/blob/2f76c8a9c9a796c0e04adc84c6b524f88d7d3e35/packages/ti_opencti/data_stream/indicator/elasticsearch/ingest …
> [ti_opencti] Keep expected nulls, improve error handling

- packages/nginx/_dev/benchmark/rally/stubstatus-benchmark/template.ndjson
When ingesting data with the `stream` command, the current track failed with the following error:
```
{"errors":true,"took":0,"ingest_took":1,"items":[{"create":{"_index":"metrics-nginx.stubstatus-ep","_id":null,"status":400,"error":{"type":"illegal_argument_exception","reason":"the document timestamp [2024-01-17T13:58:56.000Z] is outside of ranges of currently writable indices [[2024-01-17T10:46:15.000Z,2024-01-17T13:33:47.000Z]]"}}}
```
The reason was, that the timestamp used did not contain any timezone so it was in UTC. TSDB automatically sets up a range based on `now` for the local setup so when you were too far out from UTC ingestion failed. Adding the local timezone to the timezone fixes this and also ensures data that is ingested with `stream` shows up as "current" data in …
> [Nginx] Fix stubstatus benchmark

- packages/mysql/_dev/benchmark/rally/performance-benchmark/template.ndjson
Following the changes in this [PR](https://github.com/elastic/integrations/pull/8914), checked for the remaining packages which require the change. Found only 1 data stream in which the fix needs to be made. Please go through the above linked PR for the fix done.
> [MySQL] Fix performance benchmarking

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/event/_dev/test/pipeline/test-device.log-expected.json
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_app_and_identity.yml
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
- packages/m365_defender/data_stream/event/fields/ecs.yml
- packages/m365_defender/docs/README.md
- packages/m365_defender/manifest.yml
> m365_defender: add geoip processing to {source,destination}.ip

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json
- packages/o365/data_stream/audit/_dev/test/pipeline/test-sec-comp-alerts-events.json-expected.json
- packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/o365/manifest.yml
```
[o365] Add extra values to `related.user` (#8803)
The `o365.audit.Parameters.User` value will be added to `related.user`,
when it is populated.
The `o365.audit.Data.*` fields `f3u`, `suid`, `tsd` and `trc` seem to
have values that match the format of an email address, and will be added
to `related.user` in those cases.
```
These changes were suggested by a user in https://github.com/elastic/integrations/issues/4319.
Available example data includes `o365.audit.Parameters.User` values such as
```
EURPR01A002.prod.outlook.com/Microsoft Exchange Hosted Organizations/testsiem.onmicrosoft.com/Discovery Management
EURPR01A002.prod.outlook.com/Microsoft Exchange Hosted Organizations/testsiem.onmicrosoft.com/Discovery Management
```
Available example data shows the `o365.audit.Data.*` fields …
> [o365] Add extra values to `related.user`

- packages/activemq/_dev/build/docs/README.md
- packages/activemq/changelog.yml
- packages/activemq/data_stream/broker/fields/ecs.yml
- packages/activemq/data_stream/log/fields/ecs.yml
- packages/activemq/data_stream/queue/fields/ecs.yml
- packages/activemq/data_stream/topic/fields/ecs.yml
- packages/activemq/docs/README.md
- packages/activemq/manifest.yml
- Added host.ip to ecs.yml file to resolve host.ip field conflict
- Provided troubleshooting for the existing users if they are facing the conflicting issue.
- Closes #8862
> [O11y][ActiveMQ] Resolve host.ip field conflict

- packages/keycloak/_dev/build/docs/README.md
- packages/keycloak/changelog.yml
- packages/keycloak/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/keycloak/data_stream/log/_dev/test/pipeline/test-log.log
- packages/keycloak/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
- packages/keycloak/data_stream/log/agent/stream/filestream.yml.hbs
- packages/keycloak/data_stream/log/manifest.yml
- packages/keycloak/docs/README.md
- packages/keycloak/manifest.yml
In order to process multiline logs, this pull request makes the parsers configurable for the Keycloak integration.
> [Keycloak] Make parsers configurable to support multiline logs

- packages/oracle/_dev/build/docs/README.md
- packages/oracle/changelog.yml
- packages/oracle/docs/README.md
- packages/oracle/manifest.yml
This PR applies Header level 3 to the **Oracle DSN Configuration** section to make it more discoverable.
Closes [#123](https://github.com/elastic/integrations/issues/8607)
> Make Oracle DSN configuration details more discoverable

- packages/containerd/changelog.yml
- packages/containerd/data_stream/cpu/fields/base-fields.yml
- packages/containerd/data_stream/cpu/fields/ecs.yml
- packages/containerd/docs/README.md
- packages/containerd/manifest.yml
Adds dimensions mappings and ECS fields.
-
> [containerd] Add cpu dimensions

- packages/containerd/changelog.yml
- packages/containerd/data_stream/blkio/manifest.yml
- packages/containerd/data_stream/cpu/manifest.yml
- packages/containerd/data_stream/memory/manifest.yml
- packages/containerd/manifest.yml
Enables TSDB for metrics data streams.
<strong>TSDB tests:</strong>
<details><summary>memory</summary>
<p>
```
Testing data stream metrics-containerd.memory-default.
Index being used for the documents is .ds-metrics-containerd.memory-default-2024.01.23-000001.
Index being used for the settings and mappings is .ds-metrics-containerd.memory-default-2024.01.23-000001.
The time series fields for the TSDB index are: 
- dimension (10 fields):
- agent.id
- cloud.account.id
- cloud.availability_zone
- cloud.instance.id
- cloud.provider
- cloud.region
- container.id
- containerd.namespace
- host.name
- service.address
- counter (3 fields):
- containerd.memory.kernel.fail.count
- containerd.memory.swap.fail.count
- containerd.memory.usage.fail.count
- gauge (16 fields):
- container.memory.usage
- …
```
> [containerd] Enable TSDB

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/_dev/test/pipeline/test-platform-attribute-events.json
- packages/o365/data_stream/audit/fields/ecs.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
- Add the error.message field to the ECS mappings
- When not explicitly mapped in ecs.yml, error.message will assume a default type of keyword which conflicts with the ECS-defined type of match_only_text.
> [o365] Add error.message ECS field mapping

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2c4f6f5364f6bd9dfec73b0a5f04c89487ee7ad9
None
None
> [Security Rules] Update security rules package to v8.9.13

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/80be303533192f9b1becf18768adbf08bc02eb22
None
None
> [Security Rules] Update security rules package to v8.10.10

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2a48ca99066fbcc8c7611d596ea3a03aa873a927
None
None
> [Security Rules] Update security rules package to v8.12.3

- packages/elasticsearch/changelog.yml
- packages/elasticsearch/kibana/dashboard/elasticsearch-b1399af0-628c-11ee-9c63-732d7f759a7a.json
- packages/elasticsearch/manifest.yml
The visualizations in the Elasticsearch storage dashboards rely on the `elasticsearch.cluster.stats.indices.store.size.bytes` field, but one visualization, "Total Storage over time", was using `elasticsearch.index.summary.total.store.size.bytes` instead, causing values to be inconsistent across the dashboard.
This commit eliminates this inconsistency.
-->
Start a stack using `elastic-package` and install the integration. Confirm that this particular viz shows different totals compared to the rest. After introducing this change one can observe that the visualization is no longer showing a different total.
You can see inconsistent Y axis values
> [Elasticsearch] Make "Total Storage over time" viz consistent with others by using same sourceField

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
- packages/o365/data_stream/audit/manifest.yml
- packages/o365/manifest.yml
The OAuth2 scopes configuration is currently hard-coded for the CEL input. This change exposes it as a configuration value. The existing default has been preserved and the ability to add multiple scopes has been added.
- Relates elastic/sdh-beats#4311
> [o365] Expose OAuth2 token scopes configuration value

- packages/etcd/_dev/build/docs/README.md
- packages/etcd/changelog.yml
- packages/etcd/docs/README.md
- packages/etcd/manifest.yml
- Enhancement
Make ETCD Integration package GA.
- Relates https://github.com/elastic/integrations/issues/8441
> Make etcd integration package GA

- packages/lastpass/changelog.yml
- packages/lastpass/data_stream/event_report/elasticsearch/ingest_pipeline/default.yml
- packages/lastpass/manifest.yml
Make conditional field accesses safe for method calls and clean up grok expressions to reduce escape spam.
- For #8646
> lastpass: conditional field access and grok cleanup

- packages/squid/changelog.yml
- packages/squid/data_stream/log/fields/ecs.yml
- packages/squid/docs/README.md
- packages/squid/manifest.yml
* Add http.request.body.bytes to ECS mappings.
* http.request.body.bytes is currently being mapped by default to keyword which is incompatible with the ECS mapping (long) which causes en error in Data Quality check.
1. Add ECS mappings
2. Ingest data
3. Run Data Quality check to validate it does not find the mappings of http.request.body.bytes incompatible with expected value.
> [Squid] Add http.request.body.bytes to ecs mappings

- packages/nagios_xi/changelog.yml
- packages/nagios_xi/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/nagios_xi/data_stream/host/elasticsearch/ingest_pipeline/default.yml
- packages/nagios_xi/data_stream/service/elasticsearch/ingest_pipeline/default.yml
- packages/nagios_xi/manifest.yml
> nagios_xi: fix handling of potentially null method call receivers

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
- packages/o365/manifest.yml
This also allows secret annotation to be able to be informed about this field when that is implemented, preventing it being rendered into configs.
-
> o365: prevent tenant ID being rendered into debug logs

- packages/oracle/_dev/build/docs/README.md
- packages/oracle/changelog.yml
- packages/oracle/docs/README.md
- packages/oracle/manifest.yml
```
[oracle] README updates regarding DSN formats (#8841)
- Remove unsupported DSN format.
- Add note about URL encoding special characters.
- Add logfmt-encoded DSN format.
```
The `oracle` integration uses Filebeat's `sql` input. That uses the [GO DRiver for ORacle DB](https://github.com/godror/godror) to parse Oracle DSNs. When supplied with the removed format, it parses the joined username and password as only a username, with no password, as demonstrated by the following script.
<details>
<summary>DSN parsing script</summary>
Script:
```go
package main
import (
"fmt"
"github.com/godror/godror"
)
func main() {
params, err := godror.ParseDSN("sys:Oradoc_db1@0.0.0.0:1521/ORCLCDB.localdomain?sysdba=1")
if err != nil {
fmt.Println(err)
} else {
fmt.Println(params.Username) …
```
> [oracle] README updates regarding DSN formats

- packages/network_traffic/_dev/build/docs/README.md
- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/manifest.yml
- packages/network_traffic/data_stream/cassandra/manifest.yml
- packages/network_traffic/data_stream/dhcpv4/manifest.yml
- packages/network_traffic/data_stream/dns/manifest.yml
- packages/network_traffic/data_stream/flow/manifest.yml
- packages/network_traffic/data_stream/http/manifest.yml
- packages/network_traffic/data_stream/icmp/manifest.yml
- packages/network_traffic/data_stream/memcached/manifest.yml
- packages/network_traffic/data_stream/mongodb/manifest.yml
- packages/network_traffic/data_stream/mysql/manifest.yml
- packages/network_traffic/data_stream/nfs/manifest.yml
- packages/network_traffic/data_stream/pgsql/manifest.yml
- packages/network_traffic/data_stream/redis/manifest.yml
- packages/network_traffic/data_stream/sip/manifest.yml
- packages/network_traffic/data_stream/thrift/manifest.yml
- packages/network_traffic/data_stream/tls/manifest.yml
- packages/network_traffic/docs/README.md
- packages/network_traffic/manifest.yml
Add notice of significance, links to instructions for how to migrate legacy data and to the timeline for behaviour retirement.
The option is changed from show_user:false to show_user:true to avoid the [leopard in the cellar problem](https://www.goodreads.com/quotes/40705-but-the-plans-were-on-display-on-display-i-eventually).
- For #8185
> network_traffic: add notice for deprecation of map_to_ecs behaviour

- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
- packages/ti_misp/data_stream/threat_attributes/manifest.yml
- packages/ti_misp/manifest.yml
For users that wants to fetch a lot of historical data the pagination will take forever, let's keep the default limit as it was before, but allow overriding it in case it is required, this was not possible before.
> [TI_MISP] Adding new UI options for attributes to ti_misp

- packages/netscout/changelog.yml
- packages/netscout/manifest.yml
- packages/radware/changelog.yml
- packages/radware/manifest.yml
- Deprecate the netscout and radware integrations
> [netscout,radware] Deprecate integrations

- packages/ti_misp/_dev/deploy/docker/files/config.yml
- packages/ti_misp/changelog.yml
- packages/ti_misp/data_stream/threat/_dev/test/system/test-default-config.yml
- packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs
- packages/ti_misp/data_stream/threat_attributes/_dev/test/system/test-default-config.yml
- packages/ti_misp/data_stream/threat_attributes/agent/stream/httpjson.yml.hbs
- packages/ti_misp/manifest.yml
```
[ti_misp] Pagination fixes (#9073)
This change fixes several bugs in pagination logic.
For the threat (events) and threat_attributes (attributes) data streams:
* Access the timestamp correctly in the cursor data, as a string not a
`time.Time` value.
* Reuse the initial timestamp value until a new one comes from the
server (rather resetting it with `initial_inteveral` until a
timestamp appears in the cursor data).
* Add `"order":"timestamp"` parameter to requests, so that MISP queries
the database with an explicit ORDER BY clause.
* Adjust the system test stubs so that the tests cover several page
sequences, require correct timestamp values after the first sequence,
and match with the new `order` parameter.
For the threat_attributes (attributes) data stream only:
* Correct the …
```
> [ti_misp] Pagination fixes

- packages/azure/changelog.yml
- packages/azure/data_stream/auditlogs/fields/fields.yml
- packages/azure/docs/adlogs.md
- packages/azure/manifest.yml
- Define the `connection_string` and `storage_account_key` variables as secrets.
- Bump the package-spec version to `3.0.2` (secrets requirement)
- Bump Kibana version constraints to `^8.12.0` (`^8.10.0` to get secrets support, `^8.12.0` to avoid known bugs)
This ensures their values are encrypted and hidden from the settings UI in Kibana, significantly enhancing security.
- Relates https://github.com/elastic/integrations/issues/8610
> Add secrets support to the Azure Logs integation

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/fields/ecs.yml
- packages/windows/manifest.yml
Bug
* Add fields error.message and http.request.body.bytes to the ECS mappings
* Data Quality check finds default mapping of these fields (defaults to keyword) incompatible with ECS expected mapping types of match_long_text as well as long respectively.
1. Add mappings to component template.
2. Ingest data
3. Validate mappings through devtools and correlate with ECS OR run Data Quality check in Security dashboard.
> [windows.forwarded] Add fields to ECS mappings

- packages/synthetics/manifest.yml
- packages/synthetics_dashboards/changelog.yml
- packages/synthetics_dashboards/kibana/dashboard/synthetics_dashboards-e465c570-1561-11ee-9d3b-15ab835418fd.json
- packages/synthetics_dashboards/manifest.yml
Add capabilities to synthetics packages so they are not available in offerings that miss these capabilities.
**Not added because this would release a new version, that would not be filtered because of [special case](https://github.com/elastic/kibana/blob/11fe56b58636fa7fccfd871b8caccb882c888bc1/x-pack/plugins/fleet/server/services/epm/registry/index.ts#L99-L106) in Kibana.**
- https://github.com/elastic/integrations/pull/9066/files#r1479623917
- https://github.com/elastic/kibana/pull/176285
> Add capabilities to synthetics packages

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.9.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/4ead9ee249e9428c2299ffe92f601268585ea646
None
None
> [Security Rules] Update security rules package to v8.9.14

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/98b7a409fca432612deafd33b9a36a70358d0d11
None
None
> [Security Rules] Update security rules package to v8.10.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/10d36f68728553ca1e5c8ec01644e45340d358f4
None
None
> [Security Rules] Update security rules package to v8.11.8

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dadffb1d5cb44abb28680b6b45eed437fac89f91
None
None
> [Security Rules] Update security rules package to v8.12.4

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/fields/ecs.yml
- packages/crowdstrike/docs/README.md
- packages/crowdstrike/manifest.yml
> crowdstrike: add missing fdr host field type mappings

- packages/zoom/changelog.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/account.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/chat_channel.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/chat_message.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/default.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/meeting.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/phone.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/recording.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/user.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/webinar.yml
- packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/zoomroom.yml
- packages/zoom/manifest.yml
```
* remove redundant ctx null-safe field accesses
* use non-escaping mustache templates
* remove redundant quotes
* make long contains lists render with a reasonable width
* use direct comparison when lists have only a single element
* ensure that null-safe field access is uniformly applied
* ensure that null-safe method calls are correctly applied
```
- For #8646
> zoom: clean-up

- packages/o365/changelog.yml
- packages/o365/kibana/dashboard/o365-712e2c00-685d-11ea-8d6a-292ef5d68366.json
- packages/o365/kibana/search/o365-8b8e5a10-6886-11ea-8d6a-292ef5d68366.json
- packages/o365/kibana/tag/o365-security-solution-default.json
- packages/o365/manifest.yml
```
[o365] Fix dashboard panel filters (#8983)
- Added missing `data_stream.dataset: "o365.audit"` filter to the
"Top users by authentication outcome" panel.
- Replaced `data_stream.dataset: "o365.audit"` as a query with an
equivalent filter in other panels.
```
- Closes #8970
> [o365] Fix dashboard panel filters

- packages/ti_crowdstrike/changelog.yml
- packages/ti_crowdstrike/data_stream/intel/agent/stream/cel.yml.hbs
- packages/ti_crowdstrike/data_stream/ioc/agent/stream/cel.yml.hbs
- packages/ti_crowdstrike/manifest.yml
Previously, failed requests would continue through the standard happy path, potentially resulting in an uninformative CEL error when the data shape does not match the program's expectations. We have the HTTP status code, so make use of this to return an error object in the case that we get a non-success.
- Closes #9051
> ti_crowdstrike: improve error reporting for unsuccessful API requests

- packages/oracle/_dev/build/docs/README.md
- packages/oracle/changelog.yml
- packages/oracle/docs/README.md
- packages/oracle/manifest.yml
- Enhancement
README updates regarding mandatory user permission.
This helps to assign permissions to Oracle user for configuring Oracle Integration
elastic-package stack up -v -d --services package-registry
- Closes https://github.com/elastic/ingest-docs/issues/226
> [Oracle] README updates regarding mandatory user permission

- packages/ti_opencti/_dev/build/docs/README.md
- packages/ti_opencti/_dev/deploy/docker/files/config.yml
- packages/ti_opencti/changelog.yml
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-cryptocurrency-wallet.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-domain-name-with-external-reference.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-domain-name.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-email-addr.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-email-message.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-file-with-name.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-file-with-sha256.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-hostname.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-ipv4-addr.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-ipv6-addr.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-mutex.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-phone-number.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-process.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-unknown.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-url.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-user-agent.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-windows-registry-key.json
- packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
- packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
- packages/ti_opencti/docs/README.md
- packages/ti_opencti/manifest.yml
```
[ti_opencti] Update for OpenCTI v5.12.24 GraphQL schema change (#9088)
There were breaking changes to the GraphQL schema in OpenCTI v5.12.24,
due to a change in sub list loading strategy.
The previous GraphQL query does not work on OpenCTI v5.12.24 (and
presumably later) and the updated query in this change will not work
on earlier versions of OpenCTI.
For more information, please refer to:
- https://github.com/OpenCTI-Platform/opencti/releases/tag/5.12.24
- https://github.com/OpenCTI-Platform/opencti/pull/5721
```
```
elastic-package install
elastic-package test -v
```
* Build and install.
* Add a policy with credentials for https://demo.opencti.io/.
Copy the [updated GraphQL query](https://github.com/chrisberkhout/elastic-integrations/blob/ti_opencti-update-grap …
> [ti_opencti] Update for OpenCTI v5.12.24 GraphQL schema change

- packages/php_fpm/_dev/build/docs/README.md
- packages/php_fpm/changelog.yml
- packages/php_fpm/docs/README.md
- packages/php_fpm/manifest.yml
- Updated README as per the [doc template](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md#overview).
- Closes #9034
> [O11y][PHP-FPM] Update README to use documentation guidelines

- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
```
[cisco_ftd] Null handling and other clean-up (#)
- Add space around the conditional operator.
- Remove trailing whitespace.
- Combine 'not null and is value' checks.
- Remove redundant null-safe accesses.
- Combine 'is null or not value' checks.
```
> [cisco_ftd] Null handling and other clean-up

- packages/nginx/_dev/benchmark/rally/error-benchmark/config.yml
- packages/nginx/_dev/benchmark/rally/error-benchmark/fields.yml
- packages/nginx/_dev/benchmark/rally/error-benchmark/template.ndjson
In https://github.com/elastic/integrations/pull/8762 error log generation was added. The message was a random message generated. This changes it to have a partially more realistic message generated based on some actual logs. The enum values for the different fields are hardcoded. It would be nice to have for host, ip and paths some partially random generation that could be used as function with cardinality.
> [Nginx] Improve generated error message

- packages/awsfargate/_dev/build/docs/README.md
- packages/awsfargate/changelog.yml
- packages/awsfargate/docs/README.md
- packages/awsfargate/manifest.yml
Update documentation and change docs stack version to 8.12.0.
Run the elastic stack using `elastic-package` and set up the AWS Fargate integration (under beta integrations).
- Closes #9118
> [AWS Fargate] Update documentation

- packages/hashicorp_vault/changelog.yml
- packages/hashicorp_vault/data_stream/metrics/manifest.yml
- packages/hashicorp_vault/manifest.yml
- packages/zeek/changelog.yml
- packages/zeek/manifest.yml
- Set sensitive values in hashicorp_vault and zeek packages
- Updated package-spec to 3.0.2 to leverage secrets validation checks.
```
```
- Relates elastic/security-team#7388
> [hashicorp_vault,zeek] Set sensitive values as secret

- packages/panw/changelog.yml
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
- packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-tunnel-inspection-sample.log-expected.json
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
- packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/traffic.yml
- packages/panw/data_stream/panos/fields/fields.yml
- packages/panw/docs/README.md
- packages/panw/manifest.yml
Add session.start_time for ML jobs
Addresses SDH: https://github.com/elastic/sdh-beats/issues/4367
- Relates https://github.com/elastic/sdh-beats/issues/4367
> [panw] Add session.start_time for ML jobs

- packages/kubernetes/_dev/benchmark/rally/state_pod-benchmark.yml
- packages/kubernetes/_dev/benchmark/rally/statepod-benchmark/config.yml
- packages/kubernetes/_dev/benchmark/rally/statepod-benchmark/fields.yml
- packages/kubernetes/_dev/benchmark/rally/statepod-benchmark/template.ndjson
- This PR adds benchmarking templates to the `state_pod` data stream of `Kubernetes`
Run this command from package root
- `elastic-package benchmark rally --benchmark state_pod-benchmark -v`
- `elastic-package benchmark stream --benchmark state_pod-benchmark -v`
- Relates #8636 
```
--- Benchmark results for package: kubernetes - START ---
╭────────────────────────────────────────────────────────────────────────────────────╮
│ info                                                                               │
├────────────────────────┬───────────────────────────────────────────────────────────┤
│ benchmark              │                                       state_pod-benchmark │
│ description            │      Benchmark 20000 kubernetes.state_pod events ingested │
│ run ID …
```
> [O11y][Kubernetes] Rally benchmark `kubernetes.state_pod`

- packages/proofpoint_tap/changelog.yml
- packages/proofpoint_tap/data_stream/clicks_blocked/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/clicks_permitted/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/message_blocked/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/message_delivered/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/manifest.yml
```
[proofpoint_tap] Clean up null handling (#)
```
> [proofpoint_tap] Clean up null handling

- packages/azure/changelog.yml
- packages/azure/manifest.yml
Update the field type from `text` to `password` on fields marked as `secret`.
The `connection_string` and `storage_account_key` have been marked as `secret` in the previous PR https://github.com/elastic/integrations/pull/9022, but I did not update the field type as password.
AFAIK, leaving the type as `text` does not have side effects; however, I want to align the field type with the semantics.
- Relates #9022
> Azure Logs: set field type to password on secret fields

- packages/kubernetes/_dev/build/docs/README.md
- packages/kubernetes/_dev/build/docs/container-logs.md
- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/container_logs/_dev/test/pipeline/test-common-config.yml
- packages/kubernetes/data_stream/container_logs/_dev/test/pipeline/test-nginx.log-expected.json
- packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
- packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
- packages/kubernetes/data_stream/container_logs/fields/ecs.yml
- packages/kubernetes/docs/README.md
- packages/kubernetes/docs/container-logs.md
- packages/kubernetes/manifest.yml
Added support of preserve_original_event on kubernetes container logs based on pod annotations.
This is useful when events are rerouted to specific integrations, since enabling the feature there has no effect on events shipped by the kubernetes integration.
As a workaround and POC I added custom processors to the fleet configuration but I would prefer if it would be generally available. 
-
> Support 'preserve_original_event' on kubernetes container logs

- packages/sophos_central/changelog.yml
- packages/sophos_central/data_stream/alert/agent/stream/httpjson.yml.hbs
- packages/sophos_central/data_stream/event/agent/stream/httpjson.yml.hbs
- packages/sophos_central/manifest.yml
The Sophos Central API requires that request are within the last 24 hours, so clamp the from_date parameter to within this constraint to prevent invalid user input or invalid cursors from causing request failure.
- Closes #9140
> sophos_central: ensure from_date parameter is within bounds

- packages/cyberarkpas/changelog.yml
- packages/cyberarkpas/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/cyberarkpas/manifest.yml
```
[cyberarkpas] Clean up null handling, formatting (#)
- Remove redundant quotes.
- Add space around conditional operator.
- Check for null before > operator.
```
> [cyberarkpas] Clean up null handling, formatting

- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_defender_endpoint/manifest.yml
```
[microsoft_defender_endpoint] Clean up null handling (#)
- Remove redundant quotes and brackets.
```
> [microsoft_defender_endpoint] Clean up null handling

- packages/ti_cif3/changelog.yml
- packages/ti_cif3/data_stream/feed/elasticsearch/ingest_pipeline/default.yml
- packages/ti_cif3/manifest.yml
```
[ti_cif3] Clean up null handling (#)
- Make access after null-safe access also be null-safe.
```
> [ti_cif3] Clean up null handling

- packages/tenable_sc/changelog.yml
- packages/tenable_sc/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
- packages/tenable_sc/data_stream/plugin/elasticsearch/ingest_pipeline/default.yml
- packages/tenable_sc/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/tenable_sc/manifest.yml
```
[tenable_sc] Clean up null handling (#)
- Check for null before > operator.
- Add not null check to 'not value' checks.
```
> [tenable_sc] Clean up null handling

- .buildkite/hooks/pre-command
This PR adds the dot character as a new one to be replaced by a dash in the labels used by terraform.
Error when trying to use dots in GCP resources:
```
Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.labels': ''. Label value 'elastic-dependabot-go-modules-helm.sh-helm-v3-3.14.1' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters long. International characters are allowed., invalid
```
Example:
```
$ BUILDKITE_BRANCH="elastic:dependabot/go_modules/helm.sh/helm/v3-3.14.1"
$ echo "$BUILDKITE_BRANCH" | tr '[:upper:]' '[:lower:]' | tr '_/\:. ' '-'
elastic-dependabot-go-modules-helm-sh-helm-v3-3-14-1
```
> Replace dots in branch names by dash in Terraform labels

- packages/apm/changelog.yml
- packages/apm/data_stream/app_logs/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/rum_traces/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_destination_10m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_destination_1m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_destination_60m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_summary_10m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_summary_1m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_summary_60m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_transaction_10m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_transaction_1m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/service_transaction_60m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/transaction_10m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/transaction_1m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/data_stream/transaction_60m_metrics/elasticsearch/ingest_pipeline/default.yml
- packages/apm/manifest.yml
~Update apm version and min required Kibana version to 8.14.0.~
* Bump version to `8.13.1-preview-<timestamp>`, but leave min required Kibana version at `8.13.0`. This is necessary to avoid CI failures and be able to bundle this apm version with the latest Kibana snapshot. 
* Remove grok processor for `observer.version_xx` and the actual version check in the pipeline.
> apm: update package version 8.13.1-preview

- packages/infoblox_nios/changelog.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_audit.yml
- packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
- packages/infoblox_nios/manifest.yml
```
[infoblox_nios] Clean up null handling, formatting (#)
- Remove redundant quotes.
- Remove trailing whitespace.
```
> [infoblox_nios] Clean up null handling, formatting

- packages/panw_cortex_xdr/changelog.yml
- packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
- packages/panw_cortex_xdr/data_stream/incidents/elasticsearch/ingest_pipeline/default.yml
- packages/panw_cortex_xdr/manifest.yml
```
[panw_cortex_xdr] Clean up null handling (#)
- Remove redundant quotes and brackets.
```
> [panw_cortex_xdr] Clean up null handling

- packages/mongodb/_dev/build/docs/README.md
- packages/mongodb/changelog.yml
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
This PR updates the Kibana version condition for mongodb multihost fix support which is available from version 8.9.0 and it also adds configuration examples for MongoDB `hosts` field to the documentation.
- Closes #9162
> [MongoDB] Update the Kibana version condition for multi-host fix and documentation

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d6c57956c081d033d4fa8ee886c0874455c78998
None
None
> [Security Rules] Update security rules package to v8.10.12

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/38a05e1f6566a8b33fc35d4c2f446ca011601589
None
None
> [Security Rules] Update security rules package to v8.12.5

- packages/jamf_compliance_reporter/changelog.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_app_metrics.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_audit.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_chdir.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_chroot.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_execve.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_mount.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_posix_spawn.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_unmount.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_event.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_license_info_event.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_print_event_information.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_prohibited_app_blocked.yml
- packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_unified_log_event.yml
- packages/jamf_compliance_reporter/manifest.yml
```
[jamf_compliance_reporter] Clean up null handling, other checks, scripting (#)
- Add 'not null' check to 'not value' checks.
- Correct date conversion conditions to check source values.
- Add 'not null' check before .entrySet().
- Avoid trying to cast null to long/int.
```
> [jamf_compliance_reporter] Clean up null handling, other checks, scripting

- packages/mattermost/changelog.yml
- packages/mattermost/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/mattermost/manifest.yml
```
[mattermost] Clean up null handling and Painless scripts (#)
- Reformat Painless scripts.
- Merge if statements with else where conditions are mutually exclusive.
```
> [mattermost] Clean up null handling and Painless scripts

- packages/github/changelog.yml
- packages/github/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/github/data_stream/code_scanning/elasticsearch/ingest_pipeline/default.yml
- packages/github/data_stream/dependabot/elasticsearch/ingest_pipeline/default.yml
- packages/github/data_stream/issues/elasticsearch/ingest_pipeline/default.yml
- packages/github/data_stream/secret_scanning/elasticsearch/ingest_pipeline/default.yml
- packages/github/manifest.yml
```
[github] Clean up null handling, formatting (#)
- Make access after null-safe access also be null-safe.
- Make nullable checks boolean.
- Remove redundant quotes.
```
> [github] Clean up null handling, formatting

- packages/mongodb/changelog.yml
- packages/mongodb/manifest.yml
This PR updates the Kibana version condition for MongoDB integration to address the fix for MongoDB disk space exhaustion.
- Closes #9220
> [MongoDB] Update the Kibana version condition for the fix of disk space exhaustion.

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
- During initial development, a period at the end of the repeated messages grok was added by mistake
- The period has been removed and tests updated
```
```
- Relates #8989
> [cisco_ios] Remove erroneous period from repeated messages grok

- packages/mysql/changelog.yml
- packages/mysql/data_stream/performance/fields/fields.yml
- packages/mysql/manifest.yml
- Bug
Added missing dimension, `table_io_waits.index.name`, to the performance datastream, to resolve missing data problem
Manual verification 
-
> [MySQL] Added missing dimensions to the performance datastream

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/manifest.yml
- packages/eset_protect/changelog.yml
- packages/eset_protect/manifest.yml
- packages/forcepoint_web/changelog.yml
- packages/forcepoint_web/data_stream/logs/manifest.yml
- packages/forcepoint_web/manifest.yml
- packages/imperva_cloud_waf/changelog.yml
- packages/imperva_cloud_waf/data_stream/event/manifest.yml
- packages/imperva_cloud_waf/manifest.yml
- packages/ti_crowdstrike/changelog.yml
- packages/ti_crowdstrike/manifest.yml
- packages/ti_eclecticiq/changelog.yml
- packages/ti_eclecticiq/manifest.yml
- packages/ti_threatconnect/changelog.yml
- packages/ti_threatconnect/data_stream/indicator/fields/fields.yml
- packages/ti_threatconnect/docs/README.md
- packages/ti_threatconnect/manifest.yml
- Set sensitive values in several services integrations as secret
- Marked non-sensitive values as not a secret
- Upgraded pkg-spec to 3.0.3 where possible, gaining secrets validation from 3.0.2
- Relates elastic/security-team#7388
> Set sensitive values as secret in services integrations

- packages/ti_crowdstrike/changelog.yml
- packages/ti_crowdstrike/data_stream/intel/manifest.yml
- packages/ti_crowdstrike/manifest.yml
The `ilm_policy` is not defined for intel data_stream. This helps user saves space.
> [ti_crowdstrike] Add ilm policy to intel data stream

- packages/sentinel_one_cloud_funnel/changelog.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-command-script.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-cross-process.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-dns.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-file.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-indicator.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-login.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-module.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-network-action.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-process.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-registry.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-scheduled-task.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-threat-intelligence-indicator.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-url.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-command-script.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-dns.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-file.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-login.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-network-action.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-process.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-registry.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-url.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/fields/fields.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/manifest.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/sample_event.json
- packages/sentinel_one_cloud_funnel/docs/README.md
- packages/sentinel_one_cloud_funnel/manifest.yml
See title.
First
```
$ export AWS_DEFAULT_PROFILE=elastic-siem
$ aws-mfa --profile=elastic-siem
$ eval $(grep ^aws ~/.aws/credentials | gsed -r 's/^(aws[^ ]+) = (.*)$/export \U\1\E=\2/g')
```
(`gsed` is GNU `sed` so if on macos you will need to install that, if on linux `s/gsed/sed/` in the command above)
then test with `elastic-package` as normal.
- Closes #9086
> sentinel_one_cloud_funnel: improve detection rules support

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/remote_write/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/remote_write/manifest.yml
- packages/prometheus/manifest.yml
- Enhancement
Add option to provide a CA in SSL Settings of Prometheus.
This allows to allow providing the root CA for Prometheus HTTPS/TLS to implement mTLS.
> [Prometheus] SSL Certificate Authorities for remote_write

- .buildkite/scripts/backport_branch.sh
Do not run `git add` command if the `.ci` folder does not exist (Jenkins folder)
> Check whether or not jenkins folder exists in backport branches

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/94243f583b9fb511abff18899106cd140d8dd392
None
None
> [Security Rules] Update security rules package to v8.13.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/90b694bfc849f6fb58430857ca2cdebc3280861a
None
None
> [Security Rules] Update security rules package to v8.12.6

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/98cfc81c4a42bcd307bf32d89af326c3022491e4
None
None
> [Security Rules] Update security rules package to v8.10.13

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/59812dac4e586019d1801c6cc95ca1c89d01e59e
None
None
> [Security Rules] Update security rules package to v8.11.10

- .buildkite/scripts/run_sonar_scanner.sh
- .buildkite/scripts/trigger_integrations_in_parallel.sh
Avoid fail job if no XML files are downloaded in sonarqube step, following the same strategy as in JUnit plugin: https://github.com/buildkite-plugins/junit-annotate-buildkite-plugin/blob/524ac3323eeab88cb74a1eb63e17134b4d1bf3d9/hooks/command#L37-L40
Example failing build:
https://buildkite.com/elastic/integrations/builds/9406#_
> Download coverage reports and merge them
2024-03-07 10:34:26 INFO   Searching for artifacts: "build/test-coverage/coverage-*.xml"
fatal: failed to download artifacts: No artifacts found for downloading
🚨 Error: The command exited with status 1
Example build with this change and no test packages:
https://buildkite.com/elastic/integrations/builds/9419
> Download coverage reports and merge them
💥 Could not download XML artifacts. Skip coverage.
Relates #9297
> [Buildkite] Avoid fail job if no XML files are downloaded in sonarqube step

- packages/ti_mandiant_advantage/changelog.yml
- packages/ti_mandiant_advantage/data_stream/threat_intelligence/fields/ecs.yml
- packages/ti_mandiant_advantage/docs/README.md
- packages/ti_mandiant_advantage/manifest.yml
> ti_mandiant_advantage: remove invalid non-leaf field definition

- packages/microsoft_exchange_server/changelog.yml
- packages/microsoft_exchange_server/kibana/dashboard/microsoft_exchange_server-2b868ef0-c041-11ee-a682-0f218cc418af.json
- packages/microsoft_exchange_server/kibana/dashboard/microsoft_exchange_server-8e9d55c5-637a-4fd8-b53b-9501e98a8e88.json
- packages/microsoft_exchange_server/kibana/search/microsoft_exchange_server-75b14bd0-c034-11ee-a682-0f218cc418af.json
- packages/microsoft_exchange_server/kibana/search/microsoft_exchange_server-ee0a5030-c03f-11ee-a682-0f218cc418af.json
- packages/microsoft_exchange_server/manifest.yml
Due to removal of the duplicated field in PR #9197 the dashboard adjustments to use only the ECS field was missing
> Fix Exchange Server Dashboard references

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/manifest.yml
- packages/cloud_security_posture/manifest.yml
Label secret keys in Cloud Security Posture Integration.
Labeled fields:
- secret_access_key
- secret_access_key
- gcp.credentials.json
- azure.credentials.client_secret
- azure.credentials.client_password
- azure.credentials.client_certificate_password
- Pull integrations branch, `cd` to the root integrations folder
- Start elastic stack
-  `elastic-package stack up -v --version 8.14.0-SNAPSHOT`
- Build `cloud_security_posture
- `cd packages/cloud_security_posture`
- `elastic-package build`
- Bring `package-registry` up
- `elastic-package stack up -d -v --version 8.14.0-SNAPSHOT --services package-registry`
- Bring `fleet-server` up
- `elastic-package stack up -d -v --version 8.14.0-SNAPSHOT --services fleet-server`
- In your browser, open Integrations page inside local Kibana instance
- …
> [Cloud Security Posture] Label keys as secrets

- packages/aws/changelog.yml
- packages/aws/data_stream/apigateway_metrics/manifest.yml
- packages/aws/data_stream/ebs/manifest.yml
- packages/aws/data_stream/ec2_metrics/manifest.yml
- packages/aws/data_stream/ecs_metrics/manifest.yml
- packages/aws/data_stream/elb_metrics/manifest.yml
- packages/aws/data_stream/emr_metrics/manifest.yml
- packages/aws/data_stream/firewall_metrics/manifest.yml
- packages/aws/data_stream/kafka_metrics/manifest.yml
- packages/aws/data_stream/kinesis/manifest.yml
- packages/aws/data_stream/lambda/manifest.yml
- packages/aws/data_stream/natgateway/manifest.yml
- packages/aws/data_stream/rds/manifest.yml
- packages/aws/data_stream/redshift/manifest.yml
- packages/aws/data_stream/s3_daily_storage/manifest.yml
- packages/aws/data_stream/s3_request/manifest.yml
- packages/aws/data_stream/s3_storage_lens/manifest.yml
- packages/aws/data_stream/sns/manifest.yml
- packages/aws/data_stream/sqs/manifest.yml
- packages/aws/data_stream/transitgateway/manifest.yml
- packages/aws/data_stream/usage/manifest.yml
- packages/aws/data_stream/vpn/manifest.yml
- packages/aws/manifest.yml
Improve the description of `latency` parameter in integration setup for integrations using the `cloudwatch` metricset.
The current description is lacking, especially in warning the user that data points might be missing due to delay in processing metrics in AWS CloudWatch.
In our official [aws module docs](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html), the description of latency is more verbose.
- run `elastic-package stack up`
- inspect the integrations setup pages with updated descriptions
- Closes #9335
> [AWS] Improve latency description in integration setup

- packages/sentinel_one_cloud_funnel/changelog.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-process.log-expected.json
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-process.yml
- packages/sentinel_one_cloud_funnel/manifest.yml
> sentinel_one_cloud_funnel: improve process handling

- packages/windows/changelog.yml
- packages/windows/data_stream/applocker_exe_and_dll/fields/agent.yml
- packages/windows/data_stream/applocker_msi_and_script/fields/agent.yml
- packages/windows/data_stream/applocker_packaged_app_deployment/fields/agent.yml
- packages/windows/data_stream/applocker_packaged_app_execution/fields/agent.yml
- packages/windows/data_stream/forwarded/fields/agent.yml
- packages/windows/data_stream/perfmon/fields/agent.yml
- packages/windows/data_stream/powershell/fields/agent.yml
- packages/windows/data_stream/powershell_operational/fields/agent.yml
- packages/windows/data_stream/service/fields/agent.yml
- packages/windows/data_stream/sysmon_operational/fields/agent.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Adds explicit mapping for `host.os.type`.
Newer versions of the stack will add the ECS templates automatically, but since this integrations is supported since 8.8 this will fix any potential error in mappings for this field.
> [windows] Map host.os.type explicitly for all data streams.

- packages/trendmicro/changelog.yml
- packages/trendmicro/data_stream/deep_security/_dev/test/pipeline/test-trendmicro.json
- packages/trendmicro/data_stream/deep_security/_dev/test/pipeline/test-trendmicro.json-expected.json
- packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/malware-event.yml
- packages/trendmicro/data_stream/deep_security/sample_event.json
- packages/trendmicro/docs/README.md
- packages/trendmicro/manifest.yml
Type of change
- Enhancement
**Add ECS categorizations for anti-malware events.**
Based on guidance from Trend Micro, we have categorized the below-mentioned event id's as malware alerts (i.e. `event.category : malware`, `event.type: info`, `event.kind: alert`)
IDs = [4000000, 4000001, 4000002, 4000003, 4000010, 4000011, 4000012, 4000013, 4000020, 4000030]
Move to integrations/packages/trendmicro directory.
- Closes https://github.com/elastic/integrations/issues/9250
[test-trend-micro_2.2.0.log](https://github.com/elastic/integrations/files/14692383/test-trend-micro_2.2.0.log)
> [trendmicro] Add ECS Categorization for Anti-malware Events

- packages/box_events/changelog.yml
- packages/box_events/data_stream/events/_dev/test/pipeline/test-suspicious-locations.log-expected.json
- packages/box_events/data_stream/events/_dev/test/pipeline/test-suspicious-sessions.log-expected.json
- packages/box_events/data_stream/events/_dev/test/system/test-httpjson-config.yml
- packages/box_events/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/box_events/data_stream/events/fields/ecs.yml
- packages/box_events/data_stream/events/fields/fields.yml
- packages/box_events/docs/README.md
- packages/box_events/manifest.yml
> box_events: update manifest version format to v3.0.3

- packages/cloud_defend/changelog.yml
- packages/cloud_defend/manifest.yml
D4C [doc](https://docs.elastic.co/integrations/cloud_defend) update to reflect correct subscription tier.
> [D4C] Update subscription tier in manifest.yml

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.11
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/eaf4658620b0d6aff56dbb7084d08988141b7a4b
None
None
> [Security Rules] Update security rules package to v8.11.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.7
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/eaf4658620b0d6aff56dbb7084d08988141b7a4b
None
None
> [Security Rules] Update security rules package to v8.12.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.2
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/eaf4658620b0d6aff56dbb7084d08988141b7a4b
None
None
> [Security Rules] Update security rules package to v8.13.2

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
- packages/crowdstrike/data_stream/fdr/agent/stream/stream.yml.hbs
- packages/crowdstrike/data_stream/fdr/manifest.yml
- packages/crowdstrike/manifest.yml
Fix cache option naming for FDR data stream: `write_period` to `write_interval`
Relates https://github.com/elastic/beats/pull/38561
> [crowdstrike] Fix cache option name in FDR data stream.

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
The current code assumes that the only way that `event.timezone` can be set is from within the ingest pipeline. This is not the case since it can be obtained from the system `TZ` env var. So do not block setting the timezone from the `tz_config` value if `event.timezone` is already set, but do set `event.timezone` to UTC if it is missing as a fallback.
-
> cisco_ios: fix handling of timezone configurations

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
- packages/cloud_security_posture/manifest.yml
This PR adds a backport version to cloud_security_posture package 1.8.*, it includes the following changes:
- Fixed Pipeline Ingest Error due to missing cluster_id used in the `copy_from`;
Reasoning: Pipeline error were preventing the following pipelines from being executed + generating unnecessary data
- Sets placeholder value for azure `account.id` when it is not available;
- Sets placeholder value for gcp `account.id` when it is not available;
Reasoning:  GCP and Azure integrations can push data belonging to a CSPM Organization where the `cloud.account.id` field can be missing, but The Cloud Security features in Kibana 8.13 require the field `cloud.account.id` to be always available in the Cloud Security Posture indices.
- Removes `cloud.account.name` when it is empty;
Reasoning:  GCP …
> [Cloud Security] Backport 1.8.1

- packages/fortinet_fortigate/changelog.yml
- packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet-json.json
- packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet-json.json-expected.json
- packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/fortinet_fortigate/manifest.yml
```
[fortigate] Log parsing error fix
In some pipelines, the `event.original_message` field is set before the integration gets the event, which blocks the processor from copying `message` into that field. As there is no need to preserve whatever was already put into that field, we replace the `rename` to a `set` and `remove`.
- A new test was added to verify the problem is addressed
- Existing tests continue to pass
```
`elastic-package test pipeline` in the `packages/fortinet_fortigate` directory verifies the update and new test case.
- A fix for https://github.com/elastic/sdh-beats/issues/4534
> Fortigate logs parsing with kafka logstash

- packages/auditd_manager/changelog.yml
- packages/auditd_manager/manifest.yml
- packages/fim/changelog.yml
- packages/fim/manifest.yml
- packages/network_traffic/changelog.yml
- packages/network_traffic/manifest.yml
- packages/system_audit/changelog.yml
- packages/system_audit/manifest.yml
This PR marks the appropriate linux integrations of [#8647] as requiring or not root
- Relates #8642
- Closes https://github.com/elastic/integrations/issues/8647
> feat [#8647]: mark linux integrations requiring root

- packages/http_endpoint/changelog.yml
- packages/http_endpoint/data_stream/generic/agent/stream/http.yml.hbs
- packages/http_endpoint/data_stream/generic/manifest.yml
- packages/http_endpoint/manifest.yml
> http_endpoint: allow user specified HTTP method

- packages/lastpass/changelog.yml
- packages/lastpass/data_stream/event_report/agent/stream/httpjson.yml.hbs
- packages/lastpass/manifest.yml
The response page index starts with `0` as per the agent logs: 
`"message":"last received page: &httpjson.response{page:0, .....{\"Event1\":map[string]interface {}{..... \"Time\":\"2024-02-14 21:20:48\", ......,`. The response at page `0` contains `Event1`. But the input's cursor checks page index `1` for `Event1` leading to failed template evaluation.
Fixing it by updating the page index to `0`.
> [LastPass] Fix page index for event reports

- packages/gcp/changelog.yml
- packages/gcp/data_stream/storage/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/storage/manifest.yml
- packages/gcp/manifest.yml
Add custom processors and tags to gcp storage integration
> Add custom processors and tags to gcp storage integration

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
- packages/cloud_security_posture/manifest.yml
This PR Fixes the Ingest Pipeline Error, this error was due to a missing check for the presence of the `cluster_id` field used in the copy_from.
Follow the guide described [here](https://docs.elastic.dev/security-solution/cloud-security/qa/test-integration-package) to test this PR locally.
To collect the necessary data you can execute the following Reindex command in the dev tools (The pipeline is the important part!), point host and credentials to one of the long-running environments
- It fixes https://github.com/elastic/integrations/issues/9435
> [Cloud Security] Fix cluster_id missing error in the Ingest Pipeline

- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
- packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
This PR handles properly cisco_ftd messages with id 113005 that the username is hidden 
Ref https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs1.html#con_8293726 (credits @taylor-swanson )
N/A
inside the `cisco_ftd` package run:
```elastic-package test```
- Relates https://github.com/elastic/sdh-beats/issues/4563
N/A
> Fix the Grok parser for 113005 messages

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
cisco_ios: Fix hostname parsing for names that contain '_' underscore characters
- Relates https://github.com/elastic/sdh-beats/issues/4567
> cisco_ios: Fix hostname parsing for names that contain '_' underscore characters

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/112ae41cd3740a02010e78d2763a5943960b9ad4
None
None
> [Security Rules] Update security rules package to v8.11.12

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/14b6305f06580c747cda2adadc3e84c32e32b822
None
None
> [Security Rules] Update security rules package to v8.12.8

- packages/cloud_defend/changelog.yml
- packages/cloud_defend/docs/README.md
- packages/cloud_defend/manifest.yml
Update D4C support matrix to reflect the tested k8s versions.
> [D4C] Update support matrix in README.md

- packages/bluecoat/_dev/deploy/docker/docker-compose.yml
- packages/cisco_ise/_dev/deploy/docker/docker-compose.yml
- packages/cisco_secure_email_gateway/_dev/deploy/docker/docker-compose.yml
- packages/cyberarkpas/_dev/deploy/docker/docker-compose.yml
- packages/cylance/_dev/deploy/docker/docker-compose.yml
- packages/f5/_dev/deploy/docker/docker-compose.yml
- packages/fireeye/_dev/deploy/docker/docker-compose.yml
- packages/infoblox_nios/_dev/deploy/docker/docker-compose.yml
- packages/jamf_compliance_reporter/_dev/deploy/docker/docker-compose.yml
- packages/netscout/_dev/deploy/docker/docker-compose.yml
- packages/netskope/_dev/deploy/docker/docker-compose.yml
- packages/pfsense/_dev/deploy/docker/docker-compose.yml
- packages/pps/_dev/deploy/docker/docker-compose.yml
- packages/qnap_nas/_dev/deploy/docker/docker-compose.yml
- packages/radware/_dev/deploy/docker/docker-compose.yml
- packages/sonicwall_firewall/_dev/deploy/docker/docker-compose.yml
- packages/sophos/_dev/deploy/docker/docker-compose.yml
- packages/squid/_dev/deploy/docker/docker-compose.yml
- packages/tanium/_dev/deploy/docker/docker-compose.yml
- packages/thycotic_ss/_dev/deploy/docker/docker-compose.yml
- packages/tomcat/_dev/deploy/docker/docker-compose.yml
- packages/zscaler_zia/_dev/deploy/docker/docker-compose.yml
- packages/zscaler_zpa/_dev/deploy/docker/docker-compose.yml
Use the default entrypoint (/stream) when running commands using the
elastic/stream image. Version v0.15.0 switches to an alpine base image
which does not have /bin/bash.
The only reason to use a shell entrypoint was for glob expansion and that feature
has been available in elastic/stream since v0.5.0.
> Remove entrypoint override for elastic/stream

- packages/microsoft_defender_endpoint/changelog.yml
- packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_defender_endpoint/manifest.yml
- Bug
In instances where the event.original field already exists when received by the ingest pipeline, such as when the sender is Logstash with ecs_compatibility set to either v1 or v8, not specifically removing the message field breaks the [rename processor where `json.title` is moved to the `message` field](https://github.com/elastic/integrations/blob/45558de341d56b6796e75f665f26d6230a0b4861/packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L81-L84). 
To solve that issue, this PR adds a separate remove processor that remove the `message` field, if the `event.original` field is present. This then allows the later `json.title` rename processor to work.
> Microsoft Defender for Endpoint: Logstash compatibility. Remove message field if event.original exists

- .buildkite/pipeline.schedule-daily.yml
Builds with 7.17-SNAPSHOT are failing now because Fleet Server cannot bootstrap with the self-signed certificates provided by `elastic-package` (see https://github.com/elastic/fleet-server/issues/3435).
Use latest version known to work.
> Use version 7.17.19 to workaround issue in 7.17 snapshot

- packages/o365/changelog.yml
- packages/o365/data_stream/audit/_dev/test/pipeline/test-stringly-json-events.json
- packages/o365/data_stream/audit/_dev/test/pipeline/test-stringly-json-events.json-expected.json
- packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/o365/data_stream/audit/fields/fields.yml
- packages/o365/docs/README.md
- packages/o365/manifest.yml
In some cases, this field may be a string. This results in a mapping failure. So in cases where the field is a string, conditionally parse out the JSON.
---
See caveat [here](https://github.com/elastic/beats/issues/37800#issuecomment-2033372193).
- For elastic/beats#37800
> o365: improve handling of o365.audit.OperationProperties

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/_dev/test/pipeline/test-findings-log.json
- packages/cloud_security_posture/data_stream/findings/_dev/test/pipeline/test-findings-log.json-expected.json
- packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
- packages/cloud_security_posture/manifest.yml
It fixes https://github.com/elastic/kibana/issues/178904
This PR updates the Findings Ingest Pipeline to remove empty `cloud.account.id` and `cloud.account.name` fields in a Findings document. This fixes issues in Kibana when those fields are empty.
This PR also introduces Ingest Pipelines tests and adds tests to cover pipeline processors in a findings document. It can be tested following the documentation [here](https://github.com/elastic/elastic-package/blob/main/docs/howto/pipeline_testing.md) 
**Before changes:**
Fields with empty `cloud.account.name`
Bug in group by cloud account visualization, result is hidden due to empty field [#178904](https://github.com/elastic/kibana/issues/178904)
**After changes:**
No more fields with empty `cloud.account.name`
Fields are instead missing …
> [Cloud Security] [Findings Ingest Pipeline] Remove cloud.account.id and cloud.account.name empty fields from the latest findings document

- packages/cisco_aironet/changelog.yml
- packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log
- packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log-expected.json
- packages/cisco_aironet/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_aironet/manifest.yml
This PR fixes parsing of CLIENT_ORCH_LOG in cisco aironet integration
N/A
- Closes https://github.com/elastic/integrations/issues/8828
N/A
> [cisco_aironet]: handle CLIENT_ORCH_LOG messages

- packages/prisma_cloud/changelog.yml
- packages/prisma_cloud/data_stream/alert/fields/fields.yml
- packages/prisma_cloud/data_stream/host/_dev/test/pipeline/test-host.log-expected.json
- packages/prisma_cloud/data_stream/host/elasticsearch/ingest_pipeline/default.yml
- packages/prisma_cloud/data_stream/host/fields/fields.yml
- packages/prisma_cloud/data_stream/host/sample_event.json
- packages/prisma_cloud/docs/README.md
- packages/prisma_cloud/manifest.yml
> prisma_cloud: update manifest version format to v3.0.3

- packages/proofpoint_tap/changelog.yml
- packages/proofpoint_tap/data_stream/message_blocked/elasticsearch/ingest_pipeline/default.yml
- packages/proofpoint_tap/data_stream/message_blocked/fields/ecs.yml
- packages/proofpoint_tap/data_stream/message_blocked/sample_event.json
- packages/proofpoint_tap/data_stream/message_delivered/fields/ecs.yml
- packages/proofpoint_tap/docs/README.md
- packages/proofpoint_tap/manifest.yml
> proofpoint_tap: update manifest version format to v3.0.3

- packages/azure_metrics/changelog.yml
- packages/azure_metrics/kibana/dashboard/azure_metrics-b165ef60-32f7-11ea-a83e-25b8612d00cc.json
- packages/azure_metrics/manifest.yml
- Enhancement
- Migration of the visualizations to lens.
- Please refer the Screenshots mentioned in the description of the PR for comparison. 
<html>
<body>
Azure Metrics | Before Migration |   | After Migration |  
-- | -- | -- | -- | --
  | Lens | Visualization | Lens | Visualization
[Azure Metrics] Blob Storage Overview | 0 | 10 | 10 | 0
</body>
</html>
- Relates #7788
> [O11y][Azure Metrics] Migrate Blob Storage Overview dashboard to lens

- packages/jamf_protect/changelog.yml
- packages/jamf_protect/data_stream/alerts/_dev/test/pipeline/test-jamf-protect-alerts-sample-logs.log-expected.json
- packages/jamf_protect/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
- packages/jamf_protect/data_stream/alerts/fields/ecs.yml
- packages/jamf_protect/docs/README.md
- packages/jamf_protect/manifest.yml
- Adding `process.parent.entity_id` to prepare for Kibana updates.
```elastic-package stack down && elastic-package build && elastic-package stack up -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test system --generate  -v```
```
--- Test results for package: jamf_protect - START ---
╭──────────────┬────────────────────┬───────────┬───────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE      │ DATA STREAM        │ TEST TYPE │ TEST NAME                                                             │ RESULT │ TIME ELAPSED │
├──────────────┼────────────────────┼───────────┼───────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ jamf_protect │                    │ asset     │ …
```
> [Jamf Protect] Adding process.parent.entity_id ECS mapping

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `cisco_ios`
```
character class has '-' without escape
```
N/A 
N/A
N/A
> [cisco_ios]: escape hyphen inside regex char list

- packages/activemq/changelog.yml
- packages/activemq/data_stream/broker/_dev/test/pipeline/test-broker.json
- packages/activemq/data_stream/broker/_dev/test/pipeline/test-broker.json-expected.json
- packages/activemq/data_stream/broker/_dev/test/pipeline/test-common-config.yml
- packages/activemq/data_stream/queue/_dev/test/pipeline/test-common-config.yml
- packages/activemq/data_stream/queue/_dev/test/pipeline/test-queue.json
- packages/activemq/data_stream/queue/_dev/test/pipeline/test-queue.json-expected.json
- packages/activemq/data_stream/topic/_dev/test/pipeline/test-common-config.yml
- packages/activemq/data_stream/topic/_dev/test/pipeline/test-topic.json
- packages/activemq/data_stream/topic/_dev/test/pipeline/test-topic.json-expected.json
- packages/activemq/manifest.yml
- Enhancement
- Add pipeline tests for Broker, Queue and Topic data streams.
- Relates #8863
> [O11y][ActiveMQ] Add pipeline tests for Broker, Queue and Topic data streams

- packages/cisco_ftd/changelog.yml
- packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ftd/manifest.yml
After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `cisco_ftd`
```
character class has '-' without escape
```
N/A 
N/A
N/A
> [cisco_ftd]: escape hyphen inside regex char list

- .buildkite/hooks/pre-command
- .buildkite/pipeline.publish.yml
- .buildkite/pipeline.schedule-daily.yml
- .buildkite/pipeline.serverless.yml
- .buildkite/pipeline.yml
- .buildkite/pull-requests.json
- catalog-info.yaml
Add a new Buildkite pipeline to publish packages out of the testing (main) pipeline https://buildkite.com/elastic/integrations
For now, the steps related to publish packages are set as DRY_RUN mode, so they will not publish any package. In this PR, it is kept the publication process in the testing (main) pipeline.
> Add Buildkite pipeline to publish packages (DRY_RUN mode enabled)

- .buildkite/pipeline.schedule-daily.yml
Bump to 8.14.0-SNAPSHOT for daily stack testing.
> .buildkite/pipeline.schedule-daily - Use v8.14 snapshot

- packages/cisco_nexus/changelog.yml
- packages/cisco_nexus/data_stream/log/elasticsearch/ingest_pipeline/pipeline_extract_message.yml
- packages/cisco_nexus/manifest.yml
After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `cisco_nexus`
```
detected ingest pipeline warnings: 1: regular expression has redundant nested repeat operator * /(?:^(?:(?:.*)(?:\s*)?(?i)interface)(?:\s*)(?<DATA:cisco_nexus.log.interface.name>.*?) is up in mode (?<DATA:cisco_nexus.log.interface.mode>.*?)$)|(?:^(?:(?:.*)(?:\s*)?(?i)interface)(?:\s*)(?<DATA:cisco_nexus.log.interface.name>.*?) is (?:.*)$)|(?:^(?:(?:.*)(?:\s*)?(?i)interface)(?:\s*)(?<DATA:cisco_nexus.log.interface.name>.*?), operational speed changed to …
```
> [cisco_nexus]: remove redundant nested repeat operator

- packages/statsd_input/_dev/test/system/test-default-config.yml
- packages/statsd_input/changelog.yml
- packages/statsd_input/manifest.yml
- packages/statsd_input/sample_event.json
-  Fixed system tests to new `hit_count` received as now the metrics would be received in individual documents as per this [fix](https://github.com/elastic/beats/pull/36925)
- Updated the Kibana version to `8.11.0` as per [comment](https://github.com/elastic/integrations/pull/8564#issuecomment-1829137937)
1. elastic-package check
2. elastic-package stack up -d -v
3. elastic-package test -v
- Closes #9584
> [O11y][StatsD Input] Update to Kibana 8.11 for beats fixes

- packages/mongodb/_dev/build/docs/README.md
- packages/mongodb/changelog.yml
- packages/mongodb/docs/README.md
- packages/mongodb/manifest.yml
- Enhancement
- Update README with support of LDAP authentication.
- Closes #9263
> [O11y][MongoDB] Update README with support of LDAP authentication

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
This is part 1 of a 2 part change. This PR changes the pipeline so ECS categorization happens in one centralized script processor. Aside from a couple of test cases, ECS categorization of the different message types has not changed in this PR (at least what can be verified through pipeline tests). A follow up PR will apply new categorizations where necessary. This is to reduce diff noise and should make it easier to verify correctness of the pipeline changes.
The related issue mentions removing FTD-related code. I have not yet verified if FTD needs to be handled in this pipeline, and as such, code relating to FTD has not been removed or altered.
- Add script processor with params table to set ECS event categorization fields for messages
- Improve top-level error handling, remove redundant …
> [cisco_asa] Improve ECS event categorization

- packages/sentinel_one_cloud_funnel/changelog.yml
- packages/sentinel_one_cloud_funnel/data_stream/event/agent/stream/gcs.yml.hbs
- packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-registry.yml
- packages/sentinel_one_cloud_funnel/manifest.yml
> sentinel_one_cloud_funnel: fix original data preservation for gcs

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_namespace/fields/base-fields.yml
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
- WHAT:  declare kubernetes.labels and kubernetes.annotations in state_namespace data stream.
- WHY:  As part of https://github.com/elastic/beats/issues/37243 state_namespace metricset is since beats 8.14.0 enriched with kubernetes metadata.
- Closes https://github.com/elastic/integrations/issues/9625
> Declare metadata fields in state_namespace data stream

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
- Add apostrophe to the character set for username/email groks
- Add test case
```
```
- Relates elastic/sdh-beats#4623
> [cisco_asa] Allow apostrophes in usernames

- packages/logstash/_dev/deploy/docker/config/logstash.yml
- packages/logstash/_dev/deploy/docker/docker-compose.yml
- packages/logstash/_dev/deploy/variants.yml
- packages/logstash/changelog.yml
- packages/logstash/data_stream/log/_dev/test/system/test-default-config.yml
- packages/logstash/data_stream/node_cel/agent/stream/cel.yml.hbs
- packages/logstash/data_stream/slowlog/_dev/test/system/test-default-config.yml
- packages/logstash/manifest.yml
An update to the cel-go library added stricter type checking, and made certain overload operations invalid in CEL scripts. This is a work-around to "hide" the type in an array, until a better fix is available.
Closes: #9546,#9319
> [Logstash] Fix node cel script type checking issue

- packages/azure/data_stream/graphactivitylogs/_dev/test/pipeline/test-common-config.yml
- packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/iis/data_stream/error/_dev/test/pipeline/test-common-config.yml
- packages/imperva_cloud_waf/data_stream/event/_dev/test/pipeline/test-common-config.yml
- packages/keycloak/data_stream/log/_dev/test/pipeline/test-common-config.yml
- packages/m365_defender/data_stream/event/_dev/test/pipeline/test-common-config.yml
- packages/netskope/data_stream/alerts/_dev/test/pipeline/test-common-config.yml
- packages/netskope/data_stream/events/_dev/test/pipeline/test-common-config.yml
- packages/ti_crowdstrike/data_stream/intel/_dev/test/pipeline/test-common-config.yml
- packages/ti_rapid7_threat_command/data_stream/ioc/_dev/test/pipeline/test-common-config.yml
Ignore the existence of an invalid  `url.extension` field. Stack versions < 8.14 had a bug that populated the field with bad data. After a package uses a minimum stack version of 8.14.0 then this addition to `dynamic_fields` can be removed.
This fixes errors like this which occur under v8.14.0
test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -1797,7 +1797,6 @@
"preserve_duplicate_custom_fields"
],
"url": {
-                "extension": "com/page",
"original": "www.example.com/page",
"path": "www.example.com/page"
}
Relates: https://github.com/elastic/elasticsearch/pull/105689
- Relates: https://github.com/elastic/elasticsearch/pull/105689
- https://buildkite.com/elastic/integrations/builds/10450
> pipeline tests - Ignore url.extension for ES < 8.14

- packages/eset_protect/changelog.yml
- packages/eset_protect/data_stream/detection/agent/stream/cel.yml.hbs
- packages/eset_protect/data_stream/detection/sample_event.json
- packages/eset_protect/data_stream/device_task/agent/stream/cel.yml.hbs
- packages/eset_protect/data_stream/device_task/sample_event.json
- packages/eset_protect/data_stream/event/_dev/test/pipeline/test-event.log-expected.json
- packages/eset_protect/data_stream/event/sample_event.json
- packages/eset_protect/docs/README.md
- packages/eset_protect/manifest.yml
Type of change
- Enhancement
- Update grant type to password for detection and device_dask as client_credentials grant type is deprecated.
- Move to integrations/packages/eset_protect directory.
> [eset_protect] Update grant type to password

- packages/docker/changelog.yml
- packages/docker/data_stream/container/fields/fields.yml
- packages/docker/data_stream/container_logs/fields/base-fields.yml
- packages/docker/data_stream/container_logs/fields/fields.yml
- packages/docker/data_stream/cpu/fields/fields.yml
- packages/docker/data_stream/diskio/fields/fields.yml
- packages/docker/data_stream/event/fields/fields.yml
- packages/docker/data_stream/healthcheck/fields/fields.yml
- packages/docker/data_stream/image/fields/fields.yml
- packages/docker/data_stream/info/fields/fields.yml
- packages/docker/data_stream/memory/fields/fields.yml
- packages/docker/data_stream/network/fields/fields.yml
- packages/docker/manifest.yml
- WHAT: Bump format version, fix failing system tests - https://github.com/elastic/integrations/issues/9624
- WHY:  fix https://github.com/elastic/integrations/issues/9624
- Closes https://github.com/elastic/integrations/issues/9624
> [docker] bump format version, fix failing system tests 

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sgt-tag-name.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
- Remapped layer 3 protocols (`icmp`) to `network.type`
- Remapped layer 4 protocols (`tcp`) to `network.transport`
Reference for Cisco ASA message types: https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-101001-to-199021.html
- Ensure that network protocols are assigned to the correct ECS field based on their layer.
```
elastic-package 
```
- Relates elastic/sdh-beats#4627
> [cisco_asa] Fix categorization of network protocols

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
https://www.cisco.com/c/en/us/td/docs/ios/12_2sy/system/messages/122sysms/sm2sy05.html (see IPV6_ACL-6)
- The existing pattern for IPACCESSLOGSP and ACCESSLOGSP logs only handles IPACCESSLOGSP. ACCESSLOGSP follows a slightly different pattern. Added a new dissect for this log type.
```
```
- Relates elastic/sdh-beats#4623
> [cisco_ios] Fix handling of ACCESSLOGSP logs

- packages/oracle/changelog.yml
- packages/oracle/kibana/dashboard/oracle-55661160-08c7-11ed-9abf-15e60715cfab.json
- packages/oracle/kibana/dashboard/oracle-59eeb380-08d7-11ed-9abf-15e60715cfab.json
- packages/oracle/kibana/dashboard/oracle-6b4866c0-1599-11ed-9607-2ba0819b3835.json
- packages/oracle/kibana/dashboard/oracle-9e19fb00-08e1-11ed-9abf-15e60715cfab.json
- packages/oracle/kibana/dashboard/oracle-b6b2c9f0-13a7-11ed-9607-2ba0819b3835.json
- packages/oracle/kibana/dashboard/oracle-bdb780f0-156a-11ed-9607-2ba0819b3835.json
- packages/oracle/manifest.yml
Add a global filter to the dashboard and remove the subfilters on the dataset and a global filter on the dataset is introduced. Filters on data_stream.dataset are applied with a phrase type filter on the dataset that is being used in that particular dashboard.
- Relates https://github.com/elastic/integrations/issues/9323
<details>
<summary>Memory Metrics </summary>
Before:
After:
</summary>
</details>
<details>
<summary>Sysmetric </summary>
Before:
After:
</summary>
</details>
<details>
<summary>System Statistics Metrics </summary>
Before:
After:
</summary>
</details>
<details>
<summary>Overview </summary>
Before:
After:
</summary>
</details>
<details>
<summary>Performance Metrics</summary>
Before:
After:
</summary>
</details>
<details>
<summary>Tablespace</summary>
Before:
After: …
> [Oracle] Add global filter in dashboard for Oracle

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.16.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3cc76c318bc5050ffa61c2892b8c409e03a2f453
None
None
> [Security Rules] Update security rules package to v8.10.16

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dfd261590ba424e69a5802ede2ebade937198d5f
None
None
> [Security Rules] Update security rules package to v8.11.13

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c208787d65fff674a2cc801273ff0ae06c29ec85
None
None
> [Security Rules] Update security rules package to v8.13.4

- packages/azure_metrics/_dev/build/docs/compute_vm.md
- packages/azure_metrics/_dev/build/docs/compute_vm_scaleset.md
- packages/azure_metrics/_dev/build/docs/container_instance.md
- packages/azure_metrics/_dev/build/docs/container_registry.md
- packages/azure_metrics/_dev/build/docs/container_service.md
- packages/azure_metrics/_dev/build/docs/database_account.md
- packages/azure_metrics/_dev/build/docs/monitor.md
- packages/azure_metrics/_dev/build/docs/storage_account.md
- packages/azure_metrics/changelog.yml
- packages/azure_metrics/docs/compute_vm.md
- packages/azure_metrics/docs/compute_vm_scaleset.md
- packages/azure_metrics/docs/container_instance.md
- packages/azure_metrics/docs/container_registry.md
- packages/azure_metrics/docs/container_service.md
- packages/azure_metrics/docs/database_account.md
- packages/azure_metrics/docs/monitor.md
- packages/azure_metrics/docs/storage_account.md
- packages/azure_metrics/manifest.yml
This PR:
- Removes duplicate and confusing content related to Kibana configurations, authentication, and costs. 
- Adds references to generic instructions documented on the [Azure Resource Metrics](https://docs.elastic.co/integrations/azure_metrics#setup) page.
- Adds the `Requirements` and `Setup` sections to comply with the [documentation guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md).
- Fixes product names and capitalization
The doc updates impact the following Azure doc pages:
- [Container service metrics](https://docs.elastic.co/integrations/azure_metrics/container_service)
- [Database Account metrics](https://docs.elastic.co/integrations/azure_metrics/database_account)
- [Storage Account …
> Consolidate content on Azure metrics pages

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
- packages/cloud_security_posture/manifest.yml
This PR adds a backport version to cloud_security_posture package 1.7.*, it includes the following changes:
- Fixed Pipeline Ingest Error due to missing cluster_id used in the `copy_from`;
Reasoning: Pipeline error were preventing the following pipelines from being executed + generating unnecessary data
- Sets placeholder value for azure `cloud.account.id` when it is not available;
- Sets placeholder value for gcp `cloud.account.id` when it is not available;
- Sets placeholder value for aws `cloud.account.id` when it is not available;
Reasoning:  GCP and Azure agents version 8.12 can push data belonging to a CSPM Organization where the `cloud.account.id` field can be missing, but The Cloud Security features in Kibana 8.12 require the field `cloud.account.id` to be always available in the …
> [Cloud Security] Backport 1.7.5

- packages/aws_logs/changelog.yml
- packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs
- packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
- packages/aws_logs/data_stream/generic/manifest.yml
- packages/aws_logs/manifest.yml
Add a `custom` variable to allow passing additional settings to the input.
Closes #9509
- Closes #9509
> [aws_logs] Add custom settings variable

- packages/system/changelog.yml
- packages/system/kibana/dashboard/system-d401ef40-a7d5-11e9-a422-d144027429da.json
- packages/system/manifest.yml
The PR fixes a few typos in the Failed and Blocked Accounts Dashboard in the System Integration wherein the word Account(s) was misspelled as `Acoounts` or `Acconts`
- All typos fixed
- No breaking changes, and no errors reported while building the package
- Run `elastic-package check && elastic-package test`
> [System] Fix typos in Failed and Blocked Accounts dashboard

- packages/fim/changelog.yml
- packages/fim/manifest.yml
This PR adds the option of `auto` to the backend variable and marks as it default. 
N/A
N/A
N/A
Without the auto option agent in other OSs than linux is failing because of [this](https://github.com/elastic/beats/blob/main/auditbeat/module/file_integrity/config.go#L186)
> [fim]: add auto option for backend and make it the default one

- .buildkite/scripts/common.sh
Add retry suffix in folder for logs to avoid mixing files from different runs.
> [Buildkite] Add retry suffix for logs 

- .buildkite/scripts/common.sh
Skip "elastic-package install" command in Serverless builds. "elastic-package test asset" already performs the installation of the package too.
> [Buildkite] Skip install package command in serverless builds for some packages

- packages/nginx/_dev/deploy/docker/nginx.conf
Add support in nginx test configuration file (nginx.conf) to listen also in ipv6.
Latest versions of docker (from 26.0.0) runs healthchecks with ipv6:
- https://docs.docker.com/engine/release-notes/26.0/#bug-fixes-and-enhancements-2
> By default, IPv6 will remain enabled on a container's loopback interface when the container is not connected to an IPv6-enabled network. For example, containers that are only connected to an IPv4-only network now have the ::1 address on their loopback interface.
If not added this setting, container cannot be started due to the failing healthcheck:
```
$ docker logs -f elastic-package-service-nginx-1
...
2024/04/26 09:32:41 [error] 29#29: *42 open() "/usr/share/nginx/html/server-status" failed (2: No such file or directory), client: ::1, server: localhost, …
```
> [nginx] Update test nginx configuration file to listen in ipv6 too 

- packages/azure/changelog.yml
- packages/azure/data_stream/graphactivitylogs/_dev/test/pipeline/test-common-config.yml
- packages/azure/data_stream/graphactivitylogs/fields/ecs.yml
- packages/azure/docs/graphactivitylogs.md
- packages/azure/manifest.yml
- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
- packages/crowdstrike/manifest.yml
Fix flaky tests.
- `azure.graphactivitylogs`: Add missing ECS field definitions.
- `crowdstrike.falcon`: Update `geoip` processor to `destination` instead of `source`.
- Closes https://github.com/elastic/integrations/issues/9640
- Closes https://github.com/elastic/integrations/issues/9639
> [Crowdstrike,Azure] Fix flaky tests with ECS fields

- .github/CODEOWNERS
Removing separate entry of codeowners for system package kibana paths. This will avoid delays in PRs to system package, as per discussion [here](https://github.com/elastic/integrations/pull/9573#issuecomment-2071593992).
> Remove separate codeowners for system package kibana paths.

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_container/fields/fields.yml
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
- WHAT: remove deprecated fields, see https://github.com/elastic/beats/pull/28046
- WHY:  align with the beats implementation
-
> [kubernetes] Remove deprecated fields, add missing status.last_terminated_reason metric

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.17.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6938b486c377295c8221c2b3697e3448d70f0c6b
None
None
> [Security Rules] Update security rules package to v8.10.17

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/fdb4ed4eac7eb3aa9b4e61aea9dc09520a0541f2
None
None
> [Security Rules] Update security rules package to v8.12.10

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3d7af55efe22b9ef786be69f266c43b676ba2d09
None
None
> [Security Rules] Update security rules package to v8.13.5

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/alert/agent/stream/cel.yml.hbs
- packages/crowdstrike/data_stream/host/agent/stream/cel.yml.hbs
- packages/crowdstrike/manifest.yml
> crowdstrike: refactor alert and host collectors and improve error handling

- .buildkite/hooks/pre-command
- .buildkite/pipeline.publish.yml
Update pre-command hook after start publishing packages from [integrations-publish](https://buildkite.com/elastic/integrations-publish).
- Follows #9712 
> [Buildkite] Update pre-command hook

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/auditbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/beat-stats-fields.yml
- packages/elastic_agent/data_stream/filebeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_logs/fields/fields.yml
- packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
- packages/elastic_agent/manifest.yml
closes: https://github.com/elastic/beats/issues/38708
For more context: https://github.com/elastic/beats/pull/39205
This PR adds support in integrations for the new queue percentage full metric. As part of this, we:
- Add a `Queue Usage` panel to the agent metrics dashboard
- Add a `queue.filled.pct.events` field to the integrations
I haven't tinkered with integrations in ages, so...I hopefully haven't broken anything.
> Add panel to dashboard, add percent field

- packages/eset_protect/_dev/build/build.yml
- packages/eset_protect/changelog.yml
- packages/eset_protect/manifest.yml
- packages/imperva_cloud_waf/_dev/build/build.yml
- packages/imperva_cloud_waf/changelog.yml
- packages/imperva_cloud_waf/manifest.yml
- packages/sentinel_one_cloud_funnel/_dev/build/build.yml
- packages/sentinel_one_cloud_funnel/changelog.yml
- packages/sentinel_one_cloud_funnel/manifest.yml
- packages/ti_crowdstrike/_dev/build/build.yml
- packages/ti_crowdstrike/changelog.yml
- packages/ti_crowdstrike/manifest.yml
```
[eset_protect][imperva_cloud_waf][sentinal_one_cloud_funnel][ti_crowdstrike] Use modern ecs@mappings (#)
- Remove `dependencies.ecs.import_mappings: true`.
- Set `8.13` as the minimum stack version.
```
- Relates #9192
> [eset_protect][imperva_cloud_waf][sentinal_one_cloud_funnel][ti_crowdstrike] Use modern ecs@mappings

- packages/redis/changelog.yml
- packages/redis/data_stream/info/agent/stream/stream.yml.hbs
- packages/redis/data_stream/key/agent/stream/stream.yml.hbs
- packages/redis/data_stream/keyspace/agent/stream/stream.yml.hbs
- packages/redis/manifest.yml
Add AUTH (username) and SSL/TLS support for key, keyspace, and info data streams.
- Relates #5427
> [O11y][Redis] Add AUTH (username) and SSL/TLS support

- packages/azure_functions/changelog.yml
- packages/azure_functions/data_stream/metrics/agent/stream/stream.yml.hbs
- packages/azure_functions/manifest.yml
The PR contains a change to remove the`add_cloud_metadata` flag. As seen from the [code](https://github.com/elastic/beats/blob/ff424ea42bbd9256725683354a41983d23957759/x-pack/metricbeat/module/azure/data.go#L285), if set to true, the metricset tries to look for a VM using a dimension value or the actual resource ID. This isn't required for Azure Functions. Hence, it is being removed.
> [Azure_Functions] Remove `add_cloud_metadata` flag from the Agent config

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.11-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/69b3a1d89fcebb242e7f8a7d0b048358c59b5056
None
None
> [Security Rules] Update security rules package to v8.12.11-beta.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.15-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/947e8fd9652b3d739798392c9a37ff99dbdea55a
None
None
> [Security Rules] Update security rules package to v8.11.15-beta.1

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.10.18.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/21ae489caee40b974c2f77195b44d2d820229f8c
None
None
> [Security Rules] Update security rules package to v8.10.18

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/69b3a1d89fcebb242e7f8a7d0b048358c59b5056
None
None
> [Security Rules] Update security rules package to v8.12.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/947e8fd9652b3d739798392c9a37ff99dbdea55a
None
None
> [Security Rules] Update security rules package to v8.11.15

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ae23547065f6a75437adf6007653af8218b257d3
None
None
> [Security Rules] Update security rules package to v8.13.6

- packages/trend_micro_vision_one/changelog.yml
- packages/trend_micro_vision_one/data_stream/alert/_dev/test/pipeline/test-common-config.yml
- packages/trend_micro_vision_one/data_stream/alert/_dev/test/pipeline/test-pipeline-alert.log-expected.json
- packages/trend_micro_vision_one/data_stream/alert/_dev/test/system/test-default-config.yml
- packages/trend_micro_vision_one/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
- packages/trend_micro_vision_one/data_stream/alert/fields/fields.yml
- packages/trend_micro_vision_one/data_stream/alert/sample_event.json
- packages/trend_micro_vision_one/docs/README.md
- packages/trend_micro_vision_one/manifest.yml
See title.
- Depends elastic/elastic-package#1746
- For #9237
> trend_micro_vision_one: update manifest version format to v3.0.3

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/pod/fields/fields.yml
- packages/kubernetes/docs/kubelet.md
- packages/kubernetes/manifest.yml
- WHAT: remove percent unit for the pod memory metrics that are reported in bytes
- WHY:  metrics are represented in kibana incorrectly when `unit: percent` is defined
-
> [Kubernetes] remove percent unit for the pod memory metrics that are reported in bytes

- packages/apache/changelog.yml
- packages/apache/kibana/dashboard/apache-Logs-Apache-Dashboard.json
- packages/apache/kibana/search/apache-errors-log.json
- packages/apache/manifest.yml
Rename `apache2.error.integration` to `apache.error.module`
- https://github.com/elastic/beats/pull/39481 
- https://github.com/elastic/beats/issues/39480
> [Apache] Rename apache2.error.integration to apache.error.module

- packages/ti_threatconnect/changelog.yml
- packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
- packages/ti_threatconnect/manifest.yml
All non-200 HTTP status codes are treated as error conditions. The ThreatConnect API docs[1] indicate that 200 and 201 are success codes used by their API, but this integration does not make use of object creation, so 201 is not handled here.
[1]https://docs.threatconnect.com/en/latest/rest_api/v3/http_status_codes.html
See title.
This has been manually tested by altering the system test deployment to be
```
rules:
- path: /api/v3/indicators
methods: ["GET"]
query_params:
resultStart: 0
resultLimit: 2
responses:
- status_code: 401
headers:
Content-Type:
- application/json
body: |-
{"error": "unauthorized"}
```
Running the system test then results in the following event, as expected.
```
{
"@timestamp": "2024-05-10T00:00:33.092Z",
"agent": {
"ephemeral_id": …
```
> ti_threatconnect: add error handling to API requests

- packages/activemq/data_stream/log/_dev/test/system/test-logfile-config.yml
- packages/crowdstrike/data_stream/fdr/_dev/test/system/test-default-config.yml
- packages/crowdstrike/data_stream/fdr/_dev/test/system/test-keep-metadata-config.yml
- packages/fortinet_fortimanager/data_stream/log/_dev/test/system/test-logfile-config.yml
- packages/fortinet_fortimanager/data_stream/log/_dev/test/system/test-tcp-config.yml
- packages/fortinet_fortimanager/data_stream/log/_dev/test/system/test-tls-config.yml
- packages/fortinet_fortimanager/data_stream/log/_dev/test/system/test-udp-config.yml
- packages/m365_defender/data_stream/incident/_dev/test/system/test-default-config.yml
- packages/mysql/data_stream/slowlog/_dev/test/system/test-default-config.yml
- packages/oracle/data_stream/database_audit/_dev/test/system/test-logfile-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-logfile-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-tcp-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-tls-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-udp-config.yml
- packages/panw/data_stream/panos/_dev/test/system/test-udp-tz-config.yml
- packages/spring_boot/data_stream/http_trace/_dev/test/system/test-default-config.yml
- packages/tanium/data_stream/threat_response/_dev/test/system/test-http-endpoint-config.yml
- packages/tanium/data_stream/threat_response/_dev/test/system/test-tcp-config.yml
- packages/tenable_io/data_stream/vulnerability/_dev/test/system/test-default-config.yml
- packages/ti_threatconnect/data_stream/indicator/_dev/test/system/test-default-config.yml
https://github.com/elastic/elastic-package/pull/1738 is adding a check to `elastic-package` system tests to validate that no documents are degraded (which means at least one field didn't get indexed correctly and ended up ignored).
As there are [a bunch of existing issues](https://github.com/elastic/integrations/pull/9439) this check is highlighting (see https://github.com/elastic/integrations/issues/9696 and https://github.com/elastic/integrations/issues/9572), this PR is skipping the check for these fields to allow rolling out the check while fixing the issues in parallel.
This addition will currently have no effect at all, but will make sure the release of https://github.com/elastic/elastic-package/pull/1738 won't break the build for these packages.
> Skip ignored fields check for offending data streams

- packages/universal_profiling_symbolizer/changelog.yml
- packages/universal_profiling_symbolizer/manifest.yml
Revert "[Universal profiling symbolizer] use secrets variables (#9807)"
- https://github.com/elastic/integrations/issues/9845
> [Universal profiling symbolizer] revert use of secrets variables

- packages/logstash/changelog.yml
- packages/logstash/data_stream/node_cel/agent/stream/cel.yml.hbs
- packages/logstash/data_stream/pipeline/agent/stream/cel.yml.hbs
- packages/logstash/data_stream/plugins/agent/stream/cel.yml.hbs
- packages/logstash/manifest.yml
While `condition` is an option for the Logstash cel-based metrics, the condition parameter was not specified in the stream definitions.
Fixes: #9800
> [Logstash] Add condition to Logstash cel streams

- packages/cloud_security_posture/changelog.yml
- packages/cloud_security_posture/manifest.yml
Add cloud formation credentials template url which help users create stack to automate direct access keys to copy and paste to input fields
- Relates [#175977](https://github.com/elastic/kibana/issues/175977)
> [Cloud Security] add the cloud formation credentials url

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.16.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ed48d9fd5796c2de459d0726e88dc77f52c91fb9
None
None
> [Security Rules] Update security rules package to v8.11.16

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d7170886f06a5b5057ea33a3822be26d9696044c
None
None
> [Security Rules] Update security rules package to v8.12.12

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/32049a811babee84c121c0c9432c9cd93f9389ce
None
None
> [Security Rules] Update security rules package to v8.13.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.14.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a2b7f8d703c02598bb190aecb865d69d4a084f82
None
None
> [Security Rules] Update security rules package to v8.14.1

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sgt-tag-name.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sip.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/sample_event.json
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
This is part 2 of a 2 part change. This PR improves the ECS categorizations for various message types. Existing messages have been improved and new message types have been added where necessary.
For an overview of the different message types, [see this spreadsheet](https://docs.google.com/spreadsheets/d/1kAQ5bYZOWp4TBO_k1fWgCot1v11POngMG2HNTLHDBXg/edit?usp=sharing).
- Improve ECS categorizations for messages
```
```
- Closes #9461 
- Relates elastic/enhancements#19899
> [cisco_asa] Improve ECS categorizations

- packages/cassandra/_dev/build/docs/README.md
- packages/cassandra/changelog.yml
- packages/cassandra/docs/README.md
- packages/cassandra/manifest.yml
Added detailed instructions for Jolokia setup in Apache Cassandra README.
- Closes #9749
> [O11y][Cassandra] Add documentation for Jolokia setup

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
This PR fixes parsing issues with syslog messages that contain a timezone with offset in their timestamp
N/A
`elastic-package test pipeline -v`
- Relates https://github.com/elastic/integrations/issues/9857
N/A
> [cisco_ios] fix timezone with offset parsing

- packages/system/changelog.yml
- packages/system/data_stream/application/manifest.yml
- packages/system/data_stream/process/fields/fields.yml
- packages/system/data_stream/security/manifest.yml
- packages/system/data_stream/syslog/manifest.yml
- packages/system/manifest.yml
Mark logs-system.syslog data stream as requires root
Reading syslog files requires root, so if this data stream is in use the agent will require root privileges. Adding `agent.privileges.root: true` makes Fleet/Agent aware of the requirement for escalated privileges. 
Run an agent with the system integration and verify it collects data when run as a root user. I don't think the majority of the non-root agent work is "wired up" so there won't be anything obvious to test at this time. See https://github.com/elastic/kibana/pull/183283. 
Closes https://github.com/elastic/integrations/issues/9886
> [System] Mark `logs-system.syslog` data stream as requires root

- packages/http_endpoint/_dev/deploy/docker/docker-compose.yml
- packages/http_endpoint/_dev/test/system/test-http-acked-config.yml
- packages/http_endpoint/changelog.yml
See title.
This is a partner to elastic/beats#39410. The URL query param is ignored by the current version of filebeat, so the test is expected to work with the current version. It has also tested on the change at elastic/beats#39410 with the following outcome.
```
╭───────────────┬─────────────┬───────────┬────────────┬────────┬─────────────────╮
│ PACKAGE       │ DATA STREAM │ TEST TYPE │ TEST NAME  │ RESULT │    TIME ELAPSED │
├───────────────┼─────────────┼───────────┼────────────┼────────┼─────────────────┤
│ http_endpoint │             │ system    │ http-acked │ PASS   │ 1m11.438697878s │
│ http_endpoint │             │ system    │ http       │ PASS   │   41.720220895s │
╰───────────────┴─────────────┴───────────┴────────────┴────────┴─────────────────╯
```
-
> http_endpoint: test ack api

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-asr920.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog-header.log-expected.json
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
N/A
`elastic-package test pipeline -v`
- Related https://github.com/elastic/integrations/issues/9857
Kibana displays the timestamp in the timezone of the client
> [cisco_ios] fix timestamp with zones parsing

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/endpoint_security_metrics/fields/fields.yml
- packages/elastic_agent/manifest.yml
Needed for https://github.com/elastic/elastic-agent/issues/4083
This adds  `component.*` values used by the agent metrics to monitor the beats. We have these values for all the other beats, but they're missing for endpoint.
~~[ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~
> Add component values to endpoint metrics

- packages/beaconing/changelog.yml
- packages/beaconing/elasticsearch/transform/pivot_transform/fields/fields.yml
- packages/beaconing/elasticsearch/transform/pivot_transform/transform.yml
- packages/beaconing/manifest.yml
The backup timestamp field `event.ingested` must be generated by the Beaconing integration package in order for the associated detection rules to not generate an error message.
`event.ingested` was added to the pivot aggregation as a backup timestamp. The operation of the pivot was verified on a test dataset with and without the field `event.ingested`.
Related SDH:
* https://github.com/elastic/detection-rules/issues/3703
Test with `elastic-package build`, see integration package [testing instructions](https://github.com/elastic/integrations/blob/main/docs/testing_and_validation.md).
* https://github.com/elastic/detection-rules/issues/3703
> Add field 'event.ingested' to transform

- packages/jamf_protect/changelog.yml
- packages/jamf_protect/data_stream/alerts/_dev/test/pipeline/test-jamf-protect-alerts-sample-logs.log-expected.json
- packages/jamf_protect/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
- packages/jamf_protect/data_stream/alerts/fields/ecs.yml
- packages/jamf_protect/data_stream/alerts/fields/fields.yml
- packages/jamf_protect/data_stream/alerts/sample_event.json
- packages/jamf_protect/data_stream/telemetry/sample_event.json
- packages/jamf_protect/data_stream/web_threat_events/fields/ecs.yml
- packages/jamf_protect/data_stream/web_threat_events/sample_event.json
- packages/jamf_protect/data_stream/web_traffic_events/_dev/test/pipeline/test-jamf-protect-traffic-sample-logs.log-expected.json
- packages/jamf_protect/data_stream/web_traffic_events/elasticsearch/ingest_pipeline/default.yml
- packages/jamf_protect/data_stream/web_traffic_events/fields/ecs.yml
- packages/jamf_protect/data_stream/web_traffic_events/sample_event.json
- packages/jamf_protect/docs/README.md
- packages/jamf_protect/manifest.yml
- packages/jamf_protect/validation.yml
See title.
Note removal of ECS fields. The probably best approach to address these issues would be to retain a jamf_protect object to hold items like these. This is not done in this change.
- Closes #9905
- For #8610
> jamf_protect: update manifest format version to v3.0.3

- packages/crowdstrike/changelog.yml
- packages/crowdstrike/data_stream/alert/agent/stream/cel.yml.hbs
- packages/crowdstrike/data_stream/host/agent/stream/cel.yml.hbs
- packages/crowdstrike/manifest.yml
```
[crowdstrike] Fix handling of empty responses in CEL (#)
This fixes a bug in which a GET request that returns no resources is
mistakenly followed by a POST request for no resources, which seem
to have been met with 400s from the server.
Additional improvements:
- Label error messages as resulting from either a GET or a POST request.
- Ensure the value of "errors" is an array, even for the error cases.
```
> [crowdstrike] Fix handling of empty responses in CEL

- packages/jamf_protect/changelog.yml
- packages/jamf_protect/manifest.yml
- packages/ti_threatconnect/changelog.yml
- packages/ti_threatconnect/manifest.yml
```
Promote packages to GA (#)
Promote the following packages to GA:
- jamf_protect
- ti_threatconnect
Both are partner supported.
```
- Closes #9954
- Closes #9961
> Promote packages to GA

- packages/microsoft_exchange_server/changelog.yml
- packages/microsoft_exchange_server/data_stream/httpproxy/fields/ecs.yml
- packages/microsoft_exchange_server/data_stream/imap4_pop3/fields/ecs.yml
- packages/microsoft_exchange_server/data_stream/messagetracking/fields/ecs.yml
- packages/microsoft_exchange_server/data_stream/smtp/fields/ecs.yml
- packages/microsoft_exchange_server/manifest.yml
Adjust mapping to include agent & host field to avoid mapping conflicts like these:
> [Microsoft Exchange Server] Adjust mapping to include agent & host field to avoid mapping conflicts

- docs/subobjects_adoption_guide.md
Add history, usage, and recommendations for using the subobjects mapping parameter in Elasticsearch and in integrations.
> [docs] Add the subobjects adoption guide to docs

- packages/logstash/changelog.yml
- packages/logstash/data_stream/node_cel/agent/stream/cel.yml.hbs
- packages/logstash/manifest.yml
Logstash monitoring with metricbeat and self include `cluster_uuid` which will be used during the queries (example telemetry collection). However, with agent driven monitoring we are losing the cluster UUID. This change fixes the explained bug.
Use the Logstash integration, install the agent and copy the change script into the policy. We can see the cluster UUID will be reflected in `.ds-metrics-logstash.node*` indices. Also query against `cluster_uuid` (which is an alias for `logstash.elasticsearch.cluster.id`) also works as expected.
```
// example query
GET .ds-metrics-logstash.node*/_search
{
"query": {
"bool": {
"filter": [
{
"terms": {
"cluster_uuid": [
"wjK4bDWFQxKggvldnpKeng"
]
}
},
{
"bool": {
"should": [
{
"term": {
"type": "logstash_stats"
}
},
{
"term": {
"metricset.name": …
```
> Add cluster UUID to the Logstash node datastream.

- packages/lastpass/_dev/deploy/docker/files/config.yml
- packages/lastpass/changelog.yml
- packages/lastpass/data_stream/detailed_shared_folder/_dev/test/system/test-default-config.yml
- packages/lastpass/data_stream/detailed_shared_folder/agent/stream/httpjson.yml.hbs
- packages/lastpass/data_stream/detailed_shared_folder/manifest.yml
- packages/lastpass/data_stream/detailed_shared_folder/sample_event.json
- packages/lastpass/docs/README.md
- packages/lastpass/manifest.yml
```
Add pagination to `detailed_shared_folder` data.
When `data.pagesize` and `data.pageindex` properties are omitted from the 
request body, by default the API returns all shared folders. Internally, LastPass does 
multiple backend calls which could result in `429 Too Many Requests`. 
To prevent this, add `data.pagesize` and `data.pageindex` to request body.
Other changes:
- Update request `body.data: all` to `body.data.data: all` as per the API guide.
- Update system tests to contain pagination request.
- Add `assert.hit_count` to system test config.
```
Reference - https://support.lastpass.com/s/document-item?language=en_US&bundleId=lastpass&topicId=LastPass/api_shared_folder_detailed_data.html&_LANG=enus
`elastic-package stack down && elastic-package build && elastic-package stack up …
> lastpass: Add `pagesize` and `pageindex` to `detailed_shared_folder` datastream

- packages/apache_tomcat/changelog.yml
- packages/apache_tomcat/data_stream/access/agent/stream/filestream.yml.hbs
- packages/apache_tomcat/data_stream/access/manifest.yml
- packages/apache_tomcat/data_stream/catalina/agent/stream/filestream.yml.hbs
- packages/apache_tomcat/data_stream/catalina/manifest.yml
- packages/apache_tomcat/data_stream/localhost/agent/stream/filestream.yml.hbs
- packages/apache_tomcat/data_stream/localhost/manifest.yml
- packages/apache_tomcat/manifest.yml
`harvester_limit` was configured wrongly in `hbs.yml` file which leads to the following error while saving the integration.
This PR is raised to fix the above issue. After fix we are able to save the integration and agent policy is getting updated properly.
- Move to integrations/packages/apache_tomcat) directory.
- Run the following command to run tests. elastic-package test
- Relates https://github.com/elastic/enhancements/issues/21308
> [Apache Tomcat] Fix improperly configured fields `harvester_limit` and `close.on_state_change.inactive`

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.14.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/521ad875c90c0a34a5e5872100476752da9da4c0
None
None
> [Security Rules] Update security rules package to v8.14.2

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/fa968c7774e4761c995b3bcde72e3ef8819f0e67
None
None
> [Security Rules] Update security rules package to v8.13.8

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.17.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/5839b408ca54f1cb14506c056041dd521ce1b600
None
None
> [Security Rules] Update security rules package to v8.11.17

- packages/bitdefender/_dev/build/docs/README.md
- packages/bitdefender/changelog.yml
- packages/bitdefender/data_stream/push_notifications/elasticsearch/ingest_pipeline/default.yml
- packages/bitdefender/docs/README.md
- packages/bitdefender/manifest.yml
```
Update doc with input limitations.
The http_endpoint input limitation on jsonRPC format 
is not properly explained inside the doc, which is confusing to users. 
Update the doc explaining the input limitation on jsonRPC format.
Other changes:
- Remove comments from pipeline definition.
```
Before:
After:
> bitdefender: Update doc with input limitation collecting jsonRPC format.

- packages/cisco_ios/changelog.yml
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog-header.log
- packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog-header.log-expected.json
- packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_ios/manifest.yml
* Update `if` clause for `grok_child_message` entry so it does not try to parse log messages that do not contain submessages that start with `%`.  Added test using log message from SDH that was throwing an error and verified the tests pass.
```
elastic-package test pipeline
```
- Relates https://github.com/elastic/sdh-beats/issues/4754
Log message that triggered the bug:
```
<171>250756222: FNZPRPE11: 328926563: May 8 14:21:40.139 MDT: %IOSXE-3-PLATFORM: R0/0: bcm_switch: SchanTimeOut:soc_schan_op operation timed out
```
Error message that was being created:
```
Processor "conditional" with tag "grok_child_message" in pipeline "logs-cisco_ios.log-1.26.6" failed with message "Provided Grok expressions do not match field value: [SchanTimeOut:soc_schan_op operation …
```
> [cisco_ios] Update 'if' case in grok to handle IOSXE log message that was erroring

- packages/azure_openai/changelog.yml
- packages/azure_openai/kibana/dashboard/azure_openai-21d9a0d0-e6a0-4b34-bc6d-ce6560a1dab3.json
- packages/azure_openai/kibana/dashboard/azure_openai-5b98323b-7e41-408d-8b82-9cc41d4ed747.json
- packages/azure_openai/kibana/search/azure_openai-8bbccfdf-236f-4834-b0ac-fd32a56e05f0.json
- packages/azure_openai/manifest.yml
- Enhancement
- This PR adds the saved search to load the overview of logs in the logs dashboard.
- Rename metrics name in the overview dashboard.
- Removes the LENS which gets duplicated after adding saved search.
- Change the time range to last 48 hours in the logs dashboard.
Install the integration and verify the dashboard loads data properly in all the dashbaords.
> [Azure OpenAI] Add saved search to the Logs dashboard.

- packages/azure_network_watcher_nsg/_dev/deploy/docker/docker-compose.yml
- packages/azure_network_watcher_vnet/_dev/deploy/docker/docker-compose.yml
Update docker scenario for these packages to not use the full service name. Those containers can access the required service just with the service name in the same compose.
This will also help us to update how elastic-package manages these compose scenarios in the context of https://github.com/elastic/elastic-package/issues/787
Run system tests in both packages:
```shell
elastic-package stack up -v -d
cd /path/package
elastic-package test system -v
elastic-package stack down
```
- https://github.com/elastic/elastic-package/issues/787
> Update azure network watcher packages docker scenario

- packages/azure_openai/changelog.yml
- packages/azure_openai/kibana/dashboard/azure_openai-21d9a0d0-e6a0-4b34-bc6d-ce6560a1dab3.json
- packages/azure_openai/kibana/search/azure_openai-588ff5b1-0b56-4a9d-aadf-9658403870d0.json
- packages/azure_openai/manifest.yml
- Enhancement
- This PR updates the overview dashboard for the Azure OpenAI integrations. Currently the average response time will be empty and this will have data once we have the PTU changes.
- Filter by Model Deployment Name, Model Version and API Names.
- The estimated cost needs more research on how to dynamically fetch the cost for calculations based on token usage. Not considering the cost estimation in this PR.
Install the integrations and verify the dashboard loads appropriate data.
-
> Update overview dashboard

- packages/azure_openai/changelog.yml
- packages/azure_openai/kibana/dashboard/azure_openai-21d9a0d0-e6a0-4b34-bc6d-ce6560a1dab3.json
- packages/azure_openai/manifest.yml
- Enhancement
This PR updates the overall latency in the overview dashboard and the PTU latency will go into the metrics dashboard.
Verify the average latency loads in the dashboard properly in the overview dashboard.
> [Azure OpenAI] Update overall latency to the overview dashboard

- packages/windows/changelog.yml
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-events.json-expected.json
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-operational-events.json
- packages/windows/data_stream/forwarded/_dev/test/pipeline/test-powershell-operational-events.json-expected.json
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/powershell_operational.yml
- packages/windows/data_stream/forwarded/fields/fields.yml
- packages/windows/data_stream/powershell_operational/_dev/test/pipeline/test-events.json
- packages/windows/data_stream/powershell_operational/_dev/test/pipeline/test-events.json-expected.json
- packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell_operational/fields/fields.yml
- packages/windows/docs/README.md
- packages/windows/manifest.yml
Adds parsing for powershell script signatures and generates a hash of the flattened script block so they can be used as part of rules.
- Closes https://github.com/elastic/integrations/issues/3180
> [windows] Add script block hash and signature to powershell pipelines

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/endpoint_security_metrics/fields/fields.yml
- packages/elastic_agent/manifest.yml
I realized that with https://github.com/elastic/elastic-agent/pull/4789, endpoint actually needs _all_ of the process metrics previously used by only metricbeat and filebeat. This just copies the process definitions into endpoint.
> Use all process metrics values for endpoint

- packages/azure_openai/changelog.yml
- packages/azure_openai/data_stream/metrics/manifest.yml
- packages/azure_openai/manifest.yml
- Bug
This PR disables the TSDB for metrics datastream which is considered for later.
- Install the integrations with the changes
- Compare pre and post installation the data ingestion rate should be equal to the request rate.
- Also verify the data with the Azure monitor metrics.
> [Azure OpenAI] Disable TSDB on metrics datastream

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/ecs.yml
- packages/cisco_asa/data_stream/log/fields/fields.yml
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
Add support for the following log types:
106006, 106012, 113008, 113009, 113015, 113039, 302010, 315011, 716002, 716058, 716059, 721016, 721018, 722022, 722023, 722028, 722032, 722033, 722034, 722055, 725001, 725002, 725007, 725016, 737003, 737006, 737016, 737026, 737034, 113019, 113004, 113005, 113008, 113009, 716003, 716039
- Add additional log types to integration
- Add new mappings
- Add test cases
```
```
- Closes #5256
> [cisco_asa] Add additional log types

- packages/http_endpoint/_dev/test/system/test-http-config.yml
- packages/http_endpoint/agent/input/http.yml.hbs
- packages/http_endpoint/changelog.yml
- packages/http_endpoint/manifest.yml
See title.
Run elastic-package tests and then collect a diagnostic bundle. Examine the logs in logs/http_endpoint. There should be no path containing the `*` character, but there should be logs.
- Closes #9899
- Depends elastic/beats#39410
- Depends elastic/beats#39656
> http_endpoint: provide request tracing support

- packages/ti_abusech/changelog.yml
- packages/ti_abusech/elasticsearch/transform/latest_malware/fields/base-fields.yml
- packages/ti_abusech/elasticsearch/transform/latest_malware/fields/ecs.yml
- packages/ti_abusech/elasticsearch/transform/latest_malware/transform.yml
- packages/ti_abusech/elasticsearch/transform/latest_malwarebazaar/fields/base-fields.yml
- packages/ti_abusech/elasticsearch/transform/latest_malwarebazaar/fields/ecs.yml
- packages/ti_abusech/elasticsearch/transform/latest_malwarebazaar/transform.yml
- packages/ti_abusech/elasticsearch/transform/latest_threatfox/fields/base-fields.yml
- packages/ti_abusech/elasticsearch/transform/latest_threatfox/fields/ecs.yml
- packages/ti_abusech/elasticsearch/transform/latest_threatfox/transform.yml
- packages/ti_abusech/elasticsearch/transform/latest_url/fields/base-fields.yml
- packages/ti_abusech/elasticsearch/transform/latest_url/fields/ecs.yml
- packages/ti_abusech/elasticsearch/transform/latest_url/transform.yml
- packages/ti_abusech/manifest.yml
```
Adjust field mappings for transform.
Some fields such as event.module were missing from the destination index.
The field mappings are getting overwritten when same prefix exists in 
multiple files. To prevent this, all fields with same prefix are moved into 
single file, in this case ecs.yml. This is only a temporary fix until 
kibana.version is updated to >= 8.14.0, in which the root issue is fixed.
```
- Relates https://github.com/elastic/integrations/issues/10032
- Relates https://github.com/elastic/kibana/pull/177608
> ti_abusech: Adjust field mappings for transform

- packages/fortinet_fortiproxy/changelog.yml
- packages/fortinet_fortiproxy/kibana/tags.yml
- packages/fortinet_fortiproxy/manifest.yml
- Add tags.yml file so that integration's dashboards and saved searches are tagged with "Security Solution" and displayed in the Security Solution UI.
- Expanded categories
> [fortinet_fortiproxy] Add security solution tags and expand categories.

- packages/sentinel_one/changelog.yml
- packages/sentinel_one/data_stream/agent/_dev/test/pipeline/test-pipeline-agent.log-expected.json
- packages/sentinel_one/data_stream/agent/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/agent/fields/fields.yml
- packages/sentinel_one/data_stream/threat/_dev/test/pipeline/test-pipeline-threat.log-expected.json
- packages/sentinel_one/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
- packages/sentinel_one/data_stream/threat/fields/fields.yml
- packages/sentinel_one/docs/README.md
- packages/sentinel_one/manifest.yml
```
[sentinel_one] Add agent.id to all agent related data (#)
If the data is associated with a SentinelOne agent, include the agent's
ID in the final document, as `sentinel_one.<source_type>.agent.id`.
For the `agent` and `threat` data streams, the value was already stored
in `host.id`, but it was added to `sentinel_one.<source_type>.agent.id`.
For the `activity` data stream, this was already done.
For the `alert` data stream, no agent ID is available. There is a field
`agentDetectionInfo.uuid`, described in the documentation as the
"UUID of the agent", which seems to be a different value, and was
already stored in `observer.serial_number`.
For the `group` data stream there is no field that identifies an agent.
```
It's was already done in the `activity` data stream …
> [sentinel_one] Add agent.id to all agent related data

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.18.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/24d79f230e99af01ab51df38ed749cd111e1089c
None
None
> [Security Rules] Update security rules package to v8.11.18

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/fec35282affd5b57894ee7b65ba620e16153c30c
None
None
> [Security Rules] Update security rules package to v8.12.14

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/4e41596eef2bb1ff2b5cca89ca779c0bbdc73a2a
None
None
> [Security Rules] Update security rules package to v8.13.9

- packages/microsoft_sqlserver/_dev/build/docs/README.md
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/docs/README.md
- packages/microsoft_sqlserver/manifest.yml
This is an update to the MSSQL integration docs to indicate that the `transaction_logs` metrics requires version 2016 or later.  Per [MS documentation](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-log-stats-transact-sql?view=sql-server-ver16) the collection requires a table that was not present in earlier server versions.
Closes https://github.com/elastic/integrations/issues/10024
> Update MSSQL doc for version requirements

- packages/azure_billing/_dev/build/docs/README.md
- packages/azure_billing/changelog.yml
- packages/azure_billing/docs/README.md
- packages/azure_billing/manifest.yml
- packages/azure_functions/_dev/build/docs/README.md
- packages/azure_functions/changelog.yml
- packages/azure_functions/docs/README.md
- packages/azure_functions/manifest.yml
This PR replaces `Azure AD` with `Microsoft Entra ID` on the [Azure Billing Metrics](https://www.elastic.co/docs/current/integrations/azure_billing#setup) page.
Relates https://github.com/elastic/integration-docs/issues/438
> Replace Azure AD with Microsoft Entra ID

- .buildkite/pipeline.serverless.yml
Update default timeout for serverless step up to 4 hours.
The last 2 builds were failing due to hit that timeout
- https://buildkite.com/elastic/integrations-schedule-daily/builds/229
- https://buildkite.com/elastic/integrations-schedule-daily/builds/230
> [Buildkite] Update default timeout for pipeline serverless

- packages/logstash/changelog.yml
- packages/logstash/data_stream/pipeline/elasticsearch/ingest_pipeline/default.yml
- packages/logstash/data_stream/pipeline/fields/fields.yml
- packages/logstash/docs/README.md
- packages/logstash/kibana/dashboard/logstash-4bbf4a50-6ece-11ee-910d-eb0006359086.json
- packages/logstash/kibana/dashboard/logstash-4f60a1e0-6eab-11ee-86f6-d7074508d975.json
- packages/logstash/kibana/dashboard/logstash-79270240-48ee-11ee-8cb5-99927777c522.json
- packages/logstash/kibana/dashboard/logstash-8f8c78a0-6e9e-11ee-86f6-d7074508d975.json
- packages/logstash/kibana/dashboard/logstash-9d450b10-4680-11ee-9ddc-919f87fe352d.json
- packages/logstash/kibana/dashboard/logstash-a42d7060-45e6-11ee-957b-3720c0b0fbc5.json
- packages/logstash/kibana/dashboard/logstash-b516a470-71ea-11ee-aadf-e577130ac888.json
- packages/logstash/kibana/dashboard/logstash-b5234e70-6f54-11ee-910d-eb0006359086.json
- packages/logstash/kibana/dashboard/logstash-bc1a8050-5ee1-11ee-8e78-bf6865bc3ffc.json
- packages/logstash/kibana/dashboard/logstash-c0594170-526a-11ee-9ecc-31444cb79548.json
- packages/logstash/kibana/dashboard/logstash-ee860840-41ed-11ee-874b-fdb94cc3273a.json
- packages/logstash/kibana/dashboard/logstash-fe17b800-6eb4-11ee-86f6-d7074508d975.json
- packages/logstash/manifest.yml
This commit adds support for pipeline level worker utilization from the Logstash API
This involves
* Adding mapping to the fields for the worker_utilization metrics in the pipeline datastream
* Adding exclusions to the ingest pipeline to tidy up the data coming in
* Adding visualizations to the `pipelines` and `single pipeline view` dashboards
Additionally, this PR removes some incorrect flow metrics from the dashboards - previously, the summary tables in the pipeline details view would show flow metrics _summing_ all data across the picker time period, giving a nonsense value.
Install the integration, and point to a recent version of Logstash. Verify that the `worker_utilization` visualizations are present, and reflect the data from the version of Logstash
Relates #10028  
Closes #10029 …
> [Logstash] Add pipeline level worker utilization

- packages/ti_abusech/changelog.yml
- packages/ti_abusech/data_stream/malwarebazaar/agent/stream/cel.yml.hbs
- packages/ti_abusech/manifest.yml
> ti_abusech: improve error handling and reporting in malwarebazaar data stream

- packages/sentinel_one/changelog.yml
- packages/sentinel_one/data_stream/activity/manifest.yml
- packages/sentinel_one/data_stream/agent/manifest.yml
- packages/sentinel_one/data_stream/alert/manifest.yml
- packages/sentinel_one/data_stream/group/manifest.yml
- packages/sentinel_one/data_stream/threat/manifest.yml
- packages/sentinel_one/manifest.yml
```
[sentinel_one] Change default interval to 30s for all data streams
```
Merge #10102 first, then with this #9879 will be closed.
- Relates #10102
- Closes #9879
> [sentinel_one] Change default interval to 30s for all data streams

- packages/microsoft_exchange_online_message_trace/changelog.yml
- packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/httpjson.yml.hbs
- packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/log.yml.hbs
- packages/microsoft_exchange_online_message_trace/manifest.yml
Adds a check to the templates to avoid failing when `local_domains` is empty.
> [microsoft_exchange_online_message_trace] Fix template to not fail without local domains.

- packages/cisco_aironet/changelog.yml
- packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log
- packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log-expected.json
- packages/cisco_aironet/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_aironet/manifest.yml
https://github.com/elastic/sdh-beats/issues/4827
The existing grok patterns handling LOG-3-Q_IND for Cisco Aironet do not cover every possible situation. It is better to make parsing optional.
-
> [CISCO AIRONET] Allow failure for LOG-3-Q_IND matching

- packages/logstash/changelog.yml
- packages/logstash/data_stream/pipeline/agent/stream/cel.yml.hbs
- packages/logstash/data_stream/pipeline/fields/fields.yml
- packages/logstash/docs/README.md
- packages/logstash/kibana/dashboard/logstash-a42d7060-45e6-11ee-957b-3720c0b0fbc5.json
- packages/logstash/kibana/dashboard/logstash-bc1a8050-5ee1-11ee-8e78-bf6865bc3ffc.json
- packages/logstash/kibana/dashboard/logstash-c0594170-526a-11ee-9ecc-31444cb79548.json
- packages/logstash/manifest.yml
This commit adds pipeline information to the Pipelines View. This involves retrieving the `info` object from the `pipelines` view to retrieve `ephemeral_id`, `workers`, `batch_size` and `batch_delay` for each pipeline. 
Additionally, this commit adds a table to the Pipelines View to show `workers`, `batch_size`, `batch_delay`, the type of queue being used, and the current size of the queue if it is a persistent queue
Install the integration, and point to a recent version of Logstash. Verify that the Pipelines View shows the correct data for each pipeline
> [Logstash] Add pipeline info to pipeline screen

- packages/system/changelog.yml
- packages/system/data_stream/filesystem/agent/stream/stream.yml.hbs
- packages/system/manifest.yml
closes https://github.com/elastic/integrations/issues/7703
This fixes an issue where the `filesystem.ignore_types:` field in the integration wasn't formatting the YAML list correctly.
> Fix formatting of filesystem ignore types

- packages/ti_opencti/changelog.yml
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-ipv4-addr-createdby-is-null.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-ipv4-addr-createdby-is-null.json-expected.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-windows-registry-key-no-hive.json
- packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-windows-registry-key-no-hive.json-expected.json
- packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
- packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/ecs_from_windows_registry_key.yml
- packages/ti_opencti/manifest.yml
```
[ti_opencti] Ignore missing createdBy, improve reg hive name handling
- Avoid failing the pipeline if the createdBy field is null or absent.
- Avoid failing if a Windows registry key name doesn't have a path
separator in it.
- Match and normalize specific Windows registry hive names rather than
assuming the first part of a path is a hive. The
`opencti.observable.windows_registry_key.attribute_key` value is
unchanged, but the ECS field `threat.indicator.registry.hive` is now
set to the abbreviated name, as expected.
```
- Closes #10195
> [ti_opencti] Ignore missing createdBy, improve reg hive name handling

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/data_stream/log/fields/ecs.yml
- packages/cisco_asa/docs/README.md
- packages/cisco_asa/manifest.yml
- Ensure that the user agent is extracted to user_agent.original for 722055 logs
- Add sample logs
- Add user_agent.original to ecs fields
```
cd packages_cisco/asa
```
- Closes #10220
> [cisco_asa] Extract user agent from 722055 logs to correct field

- packages/zscaler_zia/changelog.yml
- packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
- packages/zscaler_zia/manifest.yml
In some cases, zscaler sents not encoded urls which den causes an parsing failure if the url contains e.g. a %
> Prevent failure on not encoded url`s

- packages/ti_eclecticiq/changelog.yml
- packages/ti_eclecticiq/data_stream/threat/agent/stream/input.yml.hbs
- packages/ti_eclecticiq/manifest.yml
```
Add CEL resource.tracer limit.
We have seen cases where the response size exceeds the default 
`resource.tracer.maxsize` 1 MB and responses are dropped. 
Add `resource.tracer.maxsize` and `resource.tracer.maxbackups` 
to capture large responses and avoid loss of visibility.
```
> ti_eclecticiq: Add CEL resource.tracer limit

- packages/prometheus/changelog.yml
- packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
- packages/prometheus/data_stream/collector/manifest.yml
- packages/prometheus/manifest.yml
- Enhancement
- WHAT: Introduced ssl.verificatin_mode none and removing default password for collector metrciset
- WHY
1. Clone this repo
2. Navigate to `integrations/packages/prometheus` 
3. `elastic-pacakge build`
4. elastic-package stack up -d -v --version=8.14.0
5. Install prometheus integration with following parameters
6. Set `SSL Verification mode `: not
- Relates #https://github.com/elastic/integrations/issues/9307
> [Prometheus Collector]Set ssl verification mode none and default username to empty

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.19.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/30f5784613e0fb833e69e001796c5e96b3cb6489
None
None
> [Security Rules] Update security rules package to v8.11.19

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.15.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/051363efa87196f74a4051129440342d46d6b457
None
None
> [Security Rules] Update security rules package to v8.12.15

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.10.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c0aab8fde05dc6e0ac1b0dfe8d64c7955655c07c
None
None
> [Security Rules] Update security rules package to v8.13.10

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.14.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dbeed6d99511206ffb55d6be9a88f509a48d6bed
None
None
> [Security Rules] Update security rules package to v8.14.4

- packages/gcp/changelog.yml
- packages/gcp/data_stream/cloudsql_postgresql/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/cloudsql_postgresql/manifest.yml
- packages/gcp/data_stream/compute/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/compute/manifest.yml
- packages/gcp/data_stream/firestore/agent/stream/stream.yml.hbs
- packages/gcp/data_stream/firestore/manifest.yml
- packages/gcp/manifest.yml
Add custom processors and tags to gcp Compute, Firestore and PostgreSQL integrations
> Add tags and processors on GCP Compute, Firestore, PostgreSQL

- packages/cloud_security_posture/data_stream/findings/fields/ecs.yml
Add `user.*` field mappings for Cloud Security Posture integration.
Follow-up to https://github.com/elastic/cloudbeat/issues/2081
> Add user mappings for Cloud Security Posture

- packages/m365_defender/changelog.yml
- packages/m365_defender/data_stream/event/_dev/test/pipeline/test-device.log-expected.json
- packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
- packages/m365_defender/manifest.yml
See title
`elastic-package test pipeline --generate -v`
```
--- Test results for package: m365_defender - START ---
╭───────────────┬─────────────┬───────────┬─────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE       │ DATA STREAM │ TEST TYPE │ TEST NAME                           │ RESULT │ TIME ELAPSED │
├───────────────┼─────────────┼───────────┼─────────────────────────────────────┼────────┼──────────────┤
│ m365_defender │ alert       │ pipeline  │ test-alert.log                      │ PASS   │   3.680791ms │
│ m365_defender │ event       │ pipeline  │ test-alert.log                      │ PASS   │    2.53025ms │
│ m365_defender │ event       │ pipeline  │ test-app-and-identity.log           │ PASS   │   3.684792ms │
│ m365_defender │ event       │ pipeline  │ …
```
> m365_defender: Fix process executable containing duplicate process name.

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.16.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c917b30feeec22e85d871882d8c1f9e77d41d0f1
None
None
> [Security Rules] Update security rules package to v8.12.16

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.20.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a1b34e021188c1a5ecbd4345645caf9041cf2f62
None
None
> [Security Rules] Update security rules package to v8.11.20

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.11.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ff8ae4301fd86f24c6164bc5c314312c972fbe42
None
None
> [Security Rules] Update security rules package to v8.13.11

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.14.5.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e4d18012de7cc4ffc30cc5b31b1d508fbbd8dffd
None
None
> [Security Rules] Update security rules package to v8.14.5

- packages/wiz/changelog.yml
- packages/wiz/data_stream/audit/agent/stream/cel.yml.hbs
- packages/wiz/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/wiz/data_stream/issue/agent/stream/cel.yml.hbs
- packages/wiz/data_stream/issue/elasticsearch/ingest_pipeline/default.yml
- packages/wiz/data_stream/vulnerability/agent/stream/cel.yml.hbs
- packages/wiz/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/wiz/manifest.yml
Fix state retention between iterations and clean up CEL code structure.
-
> wiz: fix state retention between iterations

- packages/opencanary/changelog.yml
- packages/opencanary/data_stream/events/_dev/test/pipeline/test-events.log-expected.json
- packages/opencanary/data_stream/events/elasticsearch/ingest_pipeline/default.yml
- packages/opencanary/manifest.yml
**Type of Change**:
- Bug
Fixes and issue where all source and destination details were removed if the source or destination port was an invalid "-1". The intent was to remove `source.port` if the value was "-1", or `destination.port` if the value was "-1". The `remove` processors were removing the root `source` or `destination` fields. 
https://github.com/elastic/integrations/blob/466ca328df748d401081388190dec7cf4f7d781d/packages/opencanary/data_stream/events/elasticsearch/ingest_pipeline/default.yml#L736-L749
- Closes #10287
> [OpenCanary] Correct issue with `remove` processors for source and destination ports

- packages/iis/changelog.yml
- packages/iis/data_stream/application_pool/agent/stream/stream.yml.hbs
- packages/iis/data_stream/application_pool/manifest.yml
- packages/iis/data_stream/error/_dev/test/pipeline/test-common-config.yml
- packages/iis/data_stream/webserver/agent/stream/stream.yml.hbs
- packages/iis/data_stream/webserver/manifest.yml
- packages/iis/data_stream/website/agent/stream/stream.yml.hbs
- packages/iis/data_stream/website/manifest.yml
- packages/iis/manifest.yml
Add processors capability to IIS Metrics
- Closes https://github.com/elastic/integrations/issues/10271
> [IIS] Add processors capability to IIS Metrics

- packages/wiz/changelog.yml
- packages/wiz/data_stream/audit/agent/stream/cel.yml.hbs
- packages/wiz/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/wiz/data_stream/issue/agent/stream/cel.yml.hbs
- packages/wiz/data_stream/issue/elasticsearch/ingest_pipeline/default.yml
- packages/wiz/data_stream/vulnerability/agent/stream/cel.yml.hbs
- packages/wiz/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/wiz/manifest.yml
Also add redact.fields entry to suppress redaction warning.
---
Manually checked behaviour by changing 200 status codes in system test deployment to 401. Correct behaviour observed.
-
> wiz: fix input error handling in ingest pipeline

- packages/aws/changelog.yml
- packages/aws/data_stream/elb_metrics/agent/stream/stream.yml.hbs
- packages/aws/data_stream/elb_metrics/fields/fields.yml
- packages/aws/docs/elb.md
- packages/aws/manifest.yml
Added TargetResponseTime metrics in AWS Application ELB.
I've tested with elastic-package, and run the tests and  TargetResponseTime comes into elb metrics.
```
"aws": {
"applicationelb": {
"metrics": {
"HealthyHostCount": {
"max": 1
},
"RequestCount": {
"sum": 4
},
"TargetResponseTime": {
"avg": 0.0014383333333333333
},
"UnHealthyHostCount": {
"max": 0
}
}
},
```
- Closes #9201
> AWS: TargetResponseTime metrics added to Application elb

- packages/cisco_asa/changelog.yml
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
- packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
- packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/cisco_asa/manifest.yml
Bug Fix
[cisco_asa] Customer reports grok failures for 138008, 725001 messages
- Customer was seeing a spacing variation in 138008, and a missing numeric version for SSL/TLS in 725001
- Updated parsing code to handle the message variations
- Added sample data and verified the fix
```
```
-
> [cisco_asa] Grok parsing fixes for an SDH

- .buildkite/pipeline.serverless.yml
- dev/testsreporter/testsreporter.go
Add the required version to install `gh` tool in pipeline.
Example of build failed: https://buildkite.com/elastic/integrations-serverless/builds/509#01907639-ce7b-4310-9e84-e886d735b0e6/88-116
- Follows https://github.com/elastic/integrations/pull/10234
- Relates https://github.com/elastic/integrations/issues/6071
> [CI] Add gh cli version to report failing tests in daily jobs

- .buildkite/pipeline.schedule-daily.yml
Bump to 8.15.0-SNAPSHOT for dailying stack testing.
Also use gvm v0.5.2 to be consistent with other buildkite pipelines.
> .buildkite/pipeline.schedule-daily - Use v8.15 snapshot (#9585)

- packages/tenable_io/changelog.yml
- packages/tenable_io/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
- packages/tenable_io/manifest.yml
From some customer's feedback, current fields for generating the fingerprint could not be enough in some cases to identify unique entries. When a vulnerability gets fixed, a new record can be triggered with the same `last_found` but including a `last_fixed` date.
These kind of events may be dropped since there exists any other entry with the same fingerprint as `_id`.
This pull request adds the `last_fixed` field to the fingerprint calculation.
-
> [tenable_io] Include last_fixed date in the fingerprint to avoid duplicated entries

- .buildkite/pipeline.serverless.yml
- dev/testsreporter/reporter.go
Set SERVERLESS environment variable globally. All this Buildkite pipeline is intended to test packages with Elastic serverless.
It also fixes the scenario when there is no closed issue present in the description when the tool is trying to update an existing GitHub issue.
Failed build: https://buildkite.com/elastic/integrations-serverless/builds/510#01907b60-6a24-4da2-afd7-9c6a333329a2/839-880
Issues to update the title to include `[Serverless observability]`:
- #10372 
- #10373
- Follows #10234 
- Relates #6071
> [CI] Fix reporting failing tests in serverless pipeline

- packages/aws/data_stream/waf/_dev/test/system/test-default-config.yml
Bug
https://github.com/elastic/elastic-package/pull/1738 is adding a check to elastic-package system tests for validating `_ignored` fields.
Creating this PR to ignore the check for AWS WAF, for the fields 
- `aws.waf.terminating_rule_match_details.location`
- `aws.waf.non_terminating_matching_rules.ruleMatchDetails.location`
- `aws.waf.rule_group_list.nonTerminatingMatchingRules.ruleMatchDetails.location`
```
elastic-package test system -d waf -v
```
```
--- Test results for package: aws - START ---
╭─────────┬─────────────┬───────────┬───────────┬────────┬─────────────────╮
│ PACKAGE │ DATA STREAM │ TEST TYPE │ TEST NAME │ RESULT │    TIME ELAPSED │
├─────────┼─────────────┼───────────┼───────────┼────────┼─────────────────┤
│ aws     │ waf         │ system    │ default   │ PASS   │ …
```
> Add skip ignored fields for AWS WAF fields

- packages/auditd/changelog.yml
- packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
- packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/auditd/manifest.yml
`stop` is not a valid `event.type`, use `end` where applicable.
https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-type.html#ecs-event-type-end
Related to: https://github.com/elastic/sdh-beats/issues/4763
I've tested with `elastic-package`, and run the tests for the respective package.
Related to: https://github.com/elastic/sdh-beats/issues/4763
> auditd: Fix invalid event.type: stop->end

- packages/jolokia_input/agent/input/input.yml.hbs
- packages/jolokia_input/changelog.yml
- packages/jolokia_input/manifest.yml
Add the processors option to Jolokia Input integration.
- Used the kubernetes integration as reference to add the processors option: [data stream apiserver](https://github.com/elastic/integrations/tree/main/packages/kubernetes/data_stream/apiserver).
1. Install Elastic Agent.
2. Add Jolokia Input integration.
3. Set up a processor.
- Closes #10033
> [Jolokia Input] Add processors option

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.11.21.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/8909a95486fbf1696bd6b10cd57149faf0661148
None
None
> [Security Rules] Update security rules package to v8.11.21

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.17.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/21313f3e81e336509eabd943a5f81d2f294aacc8
None
None
> [Security Rules] Update security rules package to v8.12.17

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.14.6.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/0ea5fc22203140da4f4f7fe7a4b1ab6b606e3715
None
None
> [Security Rules] Update security rules package to v8.14.6

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2cb5de5029f81bdddcce4ce00f929b32c2ff22df
None
None
> [Security Rules] Update security rules package to v8.13.12

- .buildkite/pipeline.schedule-daily.yml
- .buildkite/pipeline.yml
Update Elastic stack version 7.17.x to the latest snapshot.
Previously, it was used 7.17-SNAPSHOT, but it looks like this is not updated. Latest kibana docker image 7.17-SNAPSHOT has these labels:
```
"org.label-schema.build-date": "2024-03-25T11:07:08.779Z",
"org.label-schema.version": "7.17.19-SNAPSHOT",
```
Latest 7.17.23-SNAPSHOT has these ones:
```
"org.label-schema.build-date": "2024-07-08T11:06:40.687Z",
"org.label-schema.version": "7.17.23-SNAPSHOT",
```
Build running PR pipeline with 7.17.23-SNAPSHOT: https://buildkite.com/elastic/integrations/builds/13450
- ~[ ] I have verified that Kibana version constraints are current according to …
> Update daily job with 7.17.23-SNAPSHOT stack version

- packages/elastic_agent/changelog.yml
- packages/elastic_agent/data_stream/apm_server_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/auditbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/cloud_defend_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_logs/fields/fields.yml
- packages/elastic_agent/data_stream/cloudbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/elastic_agent_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/endpoint_security_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_input_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/filebeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/fleet_server_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/heartbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/metricbeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/osquerybeat_metrics/fields/fields.yml
- packages/elastic_agent/data_stream/packetbeat_metrics/fields/fields.yml
- packages/elastic_agent/kibana/dashboard/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824.json
- packages/elastic_agent/kibana/dashboard/elastic_agent-1a4e7280-6b5e-11ed-98de-67bdecd21824.json
- packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
- packages/elastic_agent/manifest.yml
- packages/elastic_agent/validation.yml
Migrate the elastic_agent integration to package spec v3.
- Mappings were updated as required
- Missing filters (SVR00002) errors are now ignored because some dashboards cannot have a common filter in all visualistaions.
Changes to dashboards:
- [Elastic Agent] Agent Info
- Removed missing reference
- [Elastic Agent] Agent metrics
- Visualisations were migrated to lens
- cgroup CPU percentage was removed from the Elastic-Agent Metrics dashboard because we don't collect those metrics on a default installation with monitoring enabled
1. Using `elastic-package` build the elastic_agent integration
2. Using `elastic-package` bring up the stack
3. Go to the dashboards:
- [Elastic Agent] Agent Info
- [Elastic Agent] Integrations
- [Elastic Agent] Agent metrics
- Closes …
> Migrate elastic_agent integration to package spec v3

- .buildkite/hooks/post-checkout
- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- .buildkite/scripts/common.sh
Use the same commit (SHA changeset) from the target branch, e.g. main branch, for all steps run in the Buildkite pipeline in the context of Pull Requests. This commit from main will be used in the` post-checkout` hook when available. Using the same changeset from the target branch in all steps avoids that some steps could be using a newer commit from the target branch if a new PR is merged during the build is running. That would create a different merge branch in the post-checkout hook with different contents.
For instance in this build, sonar step runs a different changeset than previous steps:
https://buildkite.com/elastic/integrations/builds/13288
Looking into that build, it can be observed how two different steps are using different changesets from main (there was a PR merged while …
> [CI] Use the same commit from target branch for all steps in post-checkout hook

- .buildkite/scripts/common.sh
Policy tests only make use of remote APIs, so they should work in serverless.
Thanks @mrodm for the suggestion!
> Enable policy tests in serverless builds

- packages/network_traffic/changelog.yml
- packages/network_traffic/data_stream/amqp/agent/stream/amqp.yml.hbs
- packages/network_traffic/data_stream/cassandra/agent/stream/cassandra.yml.hbs
- packages/network_traffic/data_stream/dhcpv4/agent/stream/dhcpv4.yml.hbs
- packages/network_traffic/data_stream/dns/agent/stream/dns.yml.hbs
- packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
- packages/network_traffic/data_stream/http/agent/stream/http.yml.hbs
- packages/network_traffic/data_stream/icmp/agent/stream/icmp.yml.hbs
- packages/network_traffic/data_stream/memcached/agent/stream/memcached.yml.hbs
- packages/network_traffic/data_stream/mongodb/agent/stream/mongodb.yml.hbs
- packages/network_traffic/data_stream/mysql/agent/stream/mysql.yml.hbs
- packages/network_traffic/data_stream/nfs/agent/stream/nfs.yml.hbs
- packages/network_traffic/data_stream/pgsql/agent/stream/pgsql.yml.hbs
- packages/network_traffic/data_stream/redis/agent/stream/redis.yml.hbs
- packages/network_traffic/data_stream/sip/agent/stream/sip.yml.hbs
- packages/network_traffic/data_stream/thrift/agent/stream/thrift.yml.hbs
- packages/network_traffic/data_stream/tls/agent/stream/tls.yml.hbs
- packages/network_traffic/manifest.yml
This creates a configuration option for `with_vlans` in the manifest that gets propagated to all data streams that packetbeat can use in fleet managed mode instead of the CLI flag.
- Relates #10059
> Replicated `never_install` functionality for `with_vlans`

- .buildkite/pipeline.serverless.yml
- .buildkite/pipeline.yml
- .buildkite/scripts/common.sh
- packages/network_traffic/_dev/test/config.yml
- packages/zeek/_dev/test/config.yml
Enable independent Elastic Agents and enable to run system tests in parallel for `network_traffic` and `zeek` packages.
- Closes #10201
> [CI] Enable independent agents parallel tests

- packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
- packages/qualys_vmdr/changelog.yml
- packages/qualys_vmdr/data_stream/user_activity/_dev/test/system/test-user-activity-config.yml
- packages/qualys_vmdr/data_stream/user_activity/agent/stream/cel.yml.hbs
- packages/qualys_vmdr/manifest.yml
Fix handling of the qualys VMDR activity_log API response. The response includes elements that are not documented. The response body contains wrappers around the CSV and an optional footer containing the pagination URL when the response was truncated.
The implementation here may be optimized after elastic/mito#67 becomes available in a release of Elastic Agent.
Fixes #10183
- Fixes #10183
> qualys_vmdr.user_activity - handle headers and footers

- packages/system/changelog.yml
- packages/system/data_stream/auth/agent/stream/log.yml.hbs
- packages/system/manifest.yml
Elastic Agent: ensure syslog processor is not used with 7.17.X agents by adding a condition.
Tests:
- Closes https://github.com/elastic/integrations/issues/10457
> Elastic Agent: ensure syslog processor is not used with 7.17.X agents

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/state_container/fields/fields.yml
- packages/kubernetes/docs/kube-state-metrics.md
- packages/kubernetes/manifest.yml
- WHAT: Add last_terminated_timestamp metric to the kubernetes.state_container datastream
- WHY: Reflect corresponding changes in beats - https://github.com/elastic/beats/pull/39200 
Relates https://github.com/elastic/elastic-agent/issues/3802
- Closes https://github.com/elastic/elastic-agent/issues/3802
> [Kubernetes] Add last_terminated_timestamp metric to state_container datastream

- packages/synthetics/changelog.yml
- packages/synthetics/data_stream/browser/fields/synthetics.yml
- packages/synthetics/manifest.yml
+ Follow up of the mapping changes from Synthetics - https://github.com/elastic/beats/pull/40230/
> [Synthetics] add journey.duration mapping to browser fields

- packages/cisco_ise/changelog.yml
- packages/cisco_ise/data_stream/log/manifest.yml
- packages/cisco_ise/manifest.yml
Fix the Cisco_ISE toggle description for filestream input
This is to follow up on SDH that was fixed earlier, this fixes the incorrect UX toggle description.
Before the change:
After this change:
> Fix the Cisco_ISE toggle description for filestream input

- packages/cisco_umbrella/changelog.yml
- packages/cisco_umbrella/data_stream/log/_dev/test/system/test-default-config.yml
- packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
- packages/cisco_umbrella/data_stream/log/manifest.yml
- packages/cisco_umbrella/manifest.yml
There is an issue in the Filebeat AWS input where when `file_selectors` is set, the global `parsers` is overwritten by individual parsers for each entry in `file_selectors`.
In the Cisco Umbrella integration, `file_selectors` should not be hardcoded because it is permanently avoiding `parsers` to work, which is used to apply the multiline configuration for audit logs.
This PR fixes that by making `file_seletors` configurable so `parsers` can be set individually in there. In case `file_selectors` is not configured, `parsers` are applied globally.
> [cisco_umbrella] Fix handling of parsers when file_selectors is not empty

- packages/f5_bigip/changelog.yml
- packages/f5_bigip/data_stream/log/_dev/test/pipeline/test-pipeline-bigip-asm.log-expected.json
- packages/f5_bigip/data_stream/log/elasticsearch/ingest_pipeline/pipeline_bigipasm.yml
- packages/f5_bigip/data_stream/log/sample_event.json
- packages/f5_bigip/docs/README.md
- packages/f5_bigip/manifest.yml
Type of change
- Bug
Modifying the value of `event.kind` dynamically according to [severity levels](https://clouddocs.f5.com/api/irules/ASM__severity.html). For the severity values of Emergency, Alert, Critical, Error, and Warning, `event.kind` is set to alert.
- Move to integrations/packages/f5_bigip directory.
- Closes #10528
> [f5_bigip] Update event.kind values based on severity

- packages/kubernetes/changelog.yml
- packages/kubernetes/data_stream/audit_logs/agent/stream/stream.yml.hbs
- packages/kubernetes/manifest.yml
- Bug
- WHAT: Fix missing processors block in kubernetes.audit_logs integration
- WHY:  User cannot add new processors in the kubernetes.audit_logs  data stream through Kibana anymore
-
> Fix missing processors block in kubernetes.audit_logs integration

- packages/keycloak/changelog.yml
- packages/keycloak/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
- packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/default.yml
- packages/keycloak/data_stream/log/manifest.yml
- packages/keycloak/manifest.yml
- Bug
1. The default parser regex pattern was faulty based on the parser requirements, hence updated it accordingly. 
2. The existing GROK pattern did not pick up multiline error logs, hence updated it accordingly and regenerated tests reflecting the change.
I revisited the url extention issue and seems even after a revert the extension field is no longer generated. This seems it might not be related to this change but rather how url extensions are now handled in ecs. It seems only file extensions are parsed now instead of a ".path".  (could be wrong) 
-
> [integrations][keycloak] - Fixed parser config default value and updated GROK pattern to account for multiline error logs

- packages/hid_bravura_monitor/changelog.yml
- packages/hid_bravura_monitor/data_stream/winlog/elasticsearch/ingest_pipeline/default.yml
- packages/hid_bravura_monitor/manifest.yml
- packages/microsoft_dnsserver/changelog.yml
- packages/microsoft_dnsserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_dnsserver/manifest.yml
- packages/microsoft_sqlserver/changelog.yml
- packages/microsoft_sqlserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
- packages/microsoft_sqlserver/data_stream/performance/manifest.yml
- packages/microsoft_sqlserver/data_stream/transaction_log/manifest.yml
- packages/microsoft_sqlserver/manifest.yml
- packages/system/changelog.yml
- packages/system/data_stream/application/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
- packages/system/data_stream/system/elasticsearch/ingest_pipeline/default.yml
- packages/system/manifest.yml
- packages/windows/changelog.yml
- packages/windows/data_stream/applocker_exe_and_dll/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/applocker_msi_and_script/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/applocker_packaged_app_deployment/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/applocker_packaged_app_execution/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
- packages/windows/data_stream/windows_defender/elasticsearch/ingest_pipeline/default.yml
- packages/windows/manifest.yml
Convert error.code to string for winlog inputs.
Winlog integrations populate `error.code` coming from the windows events. The original field is a uint32, and it needs to be converted to a string to comply with the ECS `error.code` keyword type.
> Convert error.code to string for winlog inputs

- packages/ti_crowdstrike/changelog.yml
- packages/ti_crowdstrike/data_stream/intel/agent/stream/cel.yml.hbs
- packages/ti_crowdstrike/data_stream/ioc/agent/stream/cel.yml.hbs
- packages/ti_crowdstrike/manifest.yml
The previous code used plain string operations to construct URL queries, allowing inclusion of invalid syntax when timestamps are in eastern time zones due to the inclusion of the '+' for the time zone offset. Use format_query to properly format URL queries.
In the ioc data stream, timestamps are RFC3339 formatted. These are usually sortable by stringly comparison, but not always, so make sure the comparisons are always based on time by converting candidate cursor timestamps to the timestamp type before comparison.
Also make use of optional types more carefully.
- Fixes #10526
> ti_crowdstrike: fix time stamp handling

- packages/kibana/_dev/deploy/docker/docker-compose.yml
Tests are frequently failing with connectivity errors with Kibana, try to improve the healthcheck.
Fixes https://github.com/elastic/integrations/issues/10525
Fixes https://github.com/elastic/integrations/issues/10524
Fixes https://github.com/elastic/integrations/issues/10513
Fixes https://github.com/elastic/integrations/issues/10482
> [kibana] Improve docker scenario healthcheck

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.12.18.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d6bb88fa69de6f9a1ec4cecefb3c9f84127c60d9
None
None
> [Security Rules] Update security rules package to v8.12.18

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.13.13.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/2701b5bbf6cdfc2b9b15a552cf845326261f6013
None
None
> [Security Rules] Update security rules package to v8.13.13

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.14.7.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/bdee4d45e9e7b4afc597371d231a438ff096096a
None
None
> [Security Rules] Update security rules package to v8.14.7

- packages/security_detection_engine/changelog.yml
- packages/security_detection_engine/manifest.yml
Update the Security Rules package to version 8.15.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/7b64cde1d55724e09b23c8a6e9ff60ea84e8bcb6
None
None
> [Security Rules] Update security rules package to v8.15.1

- packages/cisco_ftd/changelog.yml
- packages/cisco_ios/changelog.yml
- packages/cisco_nexus/changelog.yml
- packages/cisco_secure_email_gateway/changelog.yml
- packages/fim/changelog.yml
- packages/juniper_junos/changelog.yml
- packages/juniper_netscreen/changelog.yml
- packages/nginx_ingress_controller/changelog.yml
- packages/pfsense/changelog.yml
- packages/pulse_connect_secure/changelog.yml
- packages/security_detection_engine/changelog.yml
```
Fixed typos in changelog url links to GitHub
```
N/A
If you browse the the old URLs (`.../pulls/...` rather than `.../pull/...`) then you incorrectly end up at the GitHub search bar.
> Fixed typos in changelog url links to GitHub

- packages/sql_input/_dev/deploy/docker/docker-compose.yml
Latest image changed some things, at least the tools used for healthcheck
are installed in a different directory, and it looks like the service is started
with self-signed certificate.
These changes make healthchecks to fail consistently.
Pin the docker image to the newest version known to work.
> [sql_input] Pin mssql docker image used for testing

- .buildkite/pull-requests.json
Add github user to be allowed user to trigger builds in the [integrations pipeline](https://buildkite.com/elastic/integrations)
Example PR that build is not triggered:
https://github.com/elastic/integrations/pull/10636
> [CI] Add new user into allowed list
