elastic/integrations

packages/cisco_ios/changelog.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ios/data_stream/log/fields/ecs.yml
packages/cisco_ios/data_stream/log/fields/fields.yml
packages/cisco_ios/docs/README.md
packages/cisco_ios/manifest.yml

Adds support for ingesting IOSXE-*-PLATFORM messages.
/cc @rmelt
- Closes #7423

cisco_ios: support IOSXE-*-PLATFORM messages

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/fields/cloud.yml
packages/cloud_security_posture/data_stream/vulnerabilities/fields/cloud.yml
packages/cloud_security_posture/manifest.yml

Add mapping to the `cloud.Organization` fields we introduced recently.
- Relates https://github.com/elastic/integrations/issues/6245

[Cloud Security] Add org mapping for CSPM

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/07639887-da3a-4fbf-9532-8ce748ff8c50_1.json
packages/security_detection_engine/kibana/security_rule/0c41e478-5263-4c69-8f9e-7dfd2c22da64_3.json
packages/security_detection_engine/kibana/security_rule/14dab405-5dd9-450c-8106-72951af2391f_1.json
packages/security_detection_engine/kibana/security_rule/1f460f12-a3cf-4105-9ebb-f788cc63f365_1.json
packages/security_detection_engine/kibana/security_rule/210d4430-b371-470e-b879-80b7182aa75e_1.json
packages/security_detection_engine/kibana/security_rule/345889c4-23a8-4bc0-b7ca-756bd17ce83b_1.json
packages/security_detection_engine/kibana/security_rule/39157d52-4035-44a8-9d1a-6f8c5f580a07_1.json
packages/security_detection_engine/kibana/security_rule/3b47900d-e793-49e8-968f-c90dc3526aa1_107.json
packages/security_detection_engine/kibana/security_rule/53dedd83-1be7-430f-8026-363256395c8b_1.json
packages/security_detection_engine/kibana/security_rule/54902e45-3467-49a4-8abc-529f2c8cfb80_105.json
packages/security_detection_engine/kibana/security_rule/5c895b4f-9133-4e68-9e23-59902175355c_1.json
packages/security_detection_engine/kibana/security_rule/800e01be-a7a4-46d0-8de9-69f3c9582b44_1.json
packages/security_detection_engine/kibana/security_rule/a5eb21b7-13cc-4b94-9fe2-29bb2914e037_1.json
packages/security_detection_engine/kibana/security_rule/a61809f3-fb5b-465c-8bff-23a8a068ac60_3.json
packages/security_detection_engine/kibana/security_rule/aab184d3-72b3-4639-b242-6597c99d8bca_4.json
packages/security_detection_engine/kibana/security_rule/afd04601-12fc-4149-9b78-9c3f8fe45d39_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_1.json
packages/security_detection_engine/kibana/security_rule/cd82e3d6-1346-4afd-8f22-38388bbf34cb_1.json
packages/security_detection_engine/kibana/security_rule/d3551433-782f-4e22-bbea-c816af2d41c6_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_5.json
packages/security_detection_engine/kibana/security_rule/f3e22c8b-ea47-45d1-b502-b57b6de950b3_3.json
packages/security_detection_engine/kibana/security_rule/f59668de-caa0-4b84-94c1-3a1549e1e798_1.json
packages/security_detection_engine/kibana/security_rule/f7c4dc5a-a58d-491d-9f14-9b66507121c0_108.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.7.13-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ff3de2331edc3dc663601a9b8d9429f85c2c03eb
None

[Security Rules] Update security rules package to v8.7.13-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/07639887-da3a-4fbf-9532-8ce748ff8c50_1.json
packages/security_detection_engine/kibana/security_rule/0c41e478-5263-4c69-8f9e-7dfd2c22da64_3.json
packages/security_detection_engine/kibana/security_rule/14dab405-5dd9-450c-8106-72951af2391f_1.json
packages/security_detection_engine/kibana/security_rule/1f460f12-a3cf-4105-9ebb-f788cc63f365_1.json
packages/security_detection_engine/kibana/security_rule/210d4430-b371-470e-b879-80b7182aa75e_1.json
packages/security_detection_engine/kibana/security_rule/345889c4-23a8-4bc0-b7ca-756bd17ce83b_1.json
packages/security_detection_engine/kibana/security_rule/39157d52-4035-44a8-9d1a-6f8c5f580a07_1.json
packages/security_detection_engine/kibana/security_rule/3b47900d-e793-49e8-968f-c90dc3526aa1_107.json
packages/security_detection_engine/kibana/security_rule/53dedd83-1be7-430f-8026-363256395c8b_1.json
packages/security_detection_engine/kibana/security_rule/54902e45-3467-49a4-8abc-529f2c8cfb80_105.json
packages/security_detection_engine/kibana/security_rule/5c895b4f-9133-4e68-9e23-59902175355c_1.json
packages/security_detection_engine/kibana/security_rule/800e01be-a7a4-46d0-8de9-69f3c9582b44_1.json
packages/security_detection_engine/kibana/security_rule/a5eb21b7-13cc-4b94-9fe2-29bb2914e037_1.json
packages/security_detection_engine/kibana/security_rule/a61809f3-fb5b-465c-8bff-23a8a068ac60_3.json
packages/security_detection_engine/kibana/security_rule/aab184d3-72b3-4639-b242-6597c99d8bca_4.json
packages/security_detection_engine/kibana/security_rule/afd04601-12fc-4149-9b78-9c3f8fe45d39_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_1.json
packages/security_detection_engine/kibana/security_rule/cd82e3d6-1346-4afd-8f22-38388bbf34cb_1.json
packages/security_detection_engine/kibana/security_rule/d3551433-782f-4e22-bbea-c816af2d41c6_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_4.json
packages/security_detection_engine/kibana/security_rule/f3e22c8b-ea47-45d1-b502-b57b6de950b3_3.json
packages/security_detection_engine/kibana/security_rule/f59668de-caa0-4b84-94c1-3a1549e1e798_1.json
packages/security_detection_engine/kibana/security_rule/f7c4dc5a-a58d-491d-9f14-9b66507121c0_108.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.8.11-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e09ebe539070d499f4116c03d5148b9b20cee1a4
None

[Security Rules] Update security rules package to v8.8.11-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/07639887-da3a-4fbf-9532-8ce748ff8c50_1.json
packages/security_detection_engine/kibana/security_rule/0c41e478-5263-4c69-8f9e-7dfd2c22da64_3.json
packages/security_detection_engine/kibana/security_rule/14dab405-5dd9-450c-8106-72951af2391f_1.json
packages/security_detection_engine/kibana/security_rule/1f460f12-a3cf-4105-9ebb-f788cc63f365_1.json
packages/security_detection_engine/kibana/security_rule/210d4430-b371-470e-b879-80b7182aa75e_1.json
packages/security_detection_engine/kibana/security_rule/345889c4-23a8-4bc0-b7ca-756bd17ce83b_1.json
packages/security_detection_engine/kibana/security_rule/39157d52-4035-44a8-9d1a-6f8c5f580a07_1.json
packages/security_detection_engine/kibana/security_rule/3b47900d-e793-49e8-968f-c90dc3526aa1_107.json
packages/security_detection_engine/kibana/security_rule/53dedd83-1be7-430f-8026-363256395c8b_1.json
packages/security_detection_engine/kibana/security_rule/54902e45-3467-49a4-8abc-529f2c8cfb80_105.json
packages/security_detection_engine/kibana/security_rule/5c895b4f-9133-4e68-9e23-59902175355c_1.json
packages/security_detection_engine/kibana/security_rule/800e01be-a7a4-46d0-8de9-69f3c9582b44_1.json
packages/security_detection_engine/kibana/security_rule/a5eb21b7-13cc-4b94-9fe2-29bb2914e037_1.json
packages/security_detection_engine/kibana/security_rule/a61809f3-fb5b-465c-8bff-23a8a068ac60_3.json
packages/security_detection_engine/kibana/security_rule/aab184d3-72b3-4639-b242-6597c99d8bca_4.json
packages/security_detection_engine/kibana/security_rule/afd04601-12fc-4149-9b78-9c3f8fe45d39_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_1.json
packages/security_detection_engine/kibana/security_rule/cd82e3d6-1346-4afd-8f22-38388bbf34cb_1.json
packages/security_detection_engine/kibana/security_rule/d3551433-782f-4e22-bbea-c816af2d41c6_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_4.json
packages/security_detection_engine/kibana/security_rule/f3e22c8b-ea47-45d1-b502-b57b6de950b3_3.json
packages/security_detection_engine/kibana/security_rule/f59668de-caa0-4b84-94c1-3a1549e1e798_1.json
packages/security_detection_engine/kibana/security_rule/f7c4dc5a-a58d-491d-9f14-9b66507121c0_108.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.9.6-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dd66fb87b4060e97e84622eb0f4e4e1f2efb692a
None

[Security Rules] Update security rules package to v8.9.6-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/07639887-da3a-4fbf-9532-8ce748ff8c50_1.json
packages/security_detection_engine/kibana/security_rule/0c41e478-5263-4c69-8f9e-7dfd2c22da64_3.json
packages/security_detection_engine/kibana/security_rule/14dab405-5dd9-450c-8106-72951af2391f_1.json
packages/security_detection_engine/kibana/security_rule/1f460f12-a3cf-4105-9ebb-f788cc63f365_1.json
packages/security_detection_engine/kibana/security_rule/210d4430-b371-470e-b879-80b7182aa75e_1.json
packages/security_detection_engine/kibana/security_rule/345889c4-23a8-4bc0-b7ca-756bd17ce83b_1.json
packages/security_detection_engine/kibana/security_rule/39157d52-4035-44a8-9d1a-6f8c5f580a07_1.json
packages/security_detection_engine/kibana/security_rule/3b47900d-e793-49e8-968f-c90dc3526aa1_107.json
packages/security_detection_engine/kibana/security_rule/53dedd83-1be7-430f-8026-363256395c8b_1.json
packages/security_detection_engine/kibana/security_rule/54902e45-3467-49a4-8abc-529f2c8cfb80_105.json
packages/security_detection_engine/kibana/security_rule/5c895b4f-9133-4e68-9e23-59902175355c_1.json
packages/security_detection_engine/kibana/security_rule/800e01be-a7a4-46d0-8de9-69f3c9582b44_1.json
packages/security_detection_engine/kibana/security_rule/a5eb21b7-13cc-4b94-9fe2-29bb2914e037_1.json
packages/security_detection_engine/kibana/security_rule/a61809f3-fb5b-465c-8bff-23a8a068ac60_3.json
packages/security_detection_engine/kibana/security_rule/aab184d3-72b3-4639-b242-6597c99d8bca_4.json
packages/security_detection_engine/kibana/security_rule/afd04601-12fc-4149-9b78-9c3f8fe45d39_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_1.json
packages/security_detection_engine/kibana/security_rule/cd82e3d6-1346-4afd-8f22-38388bbf34cb_1.json
packages/security_detection_engine/kibana/security_rule/d3551433-782f-4e22-bbea-c816af2d41c6_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_4.json
packages/security_detection_engine/kibana/security_rule/f3e22c8b-ea47-45d1-b502-b57b6de950b3_3.json
packages/security_detection_engine/kibana/security_rule/f59668de-caa0-4b84-94c1-3a1549e1e798_1.json
packages/security_detection_engine/kibana/security_rule/f7c4dc5a-a58d-491d-9f14-9b66507121c0_108.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.10.3-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/80f16bb7ac146a76cd2537a6b745f2b8f525c804
None

[Security Rules] Update security rules package to v8.10.3-beta.1

---

packages/cloud_security_posture/data_stream/findings/fields/fields.yml
packages/cloud_security_posture/data_stream/vulnerabilities/fields/fields.yml

Added mappings to package_policy id and revision.
Relates to https://github.com/elastic/cloudbeat/issues/1298
-

[Cloud Security] Added package_policy.id and package_policy.revision

---

.github/PULL_REQUEST_TEMPLATE.md

This brings the commit message section of the PULL_REQUEST_TEMPLATE.md into line with the text used in the beats repository.
-

github: give greater instructions for commit messages

---

packages/okta/changelog.yml
packages/okta/kibana/dashboard/okta-749203a0-67b1-11ea-a76f-bf44814e437d.json
packages/okta/kibana/tags.yml
packages/okta/manifest.yml

Add tags.yml file so that integration's dashboards and saved searches are tagged with 'Security Solution' and displayed in the Security Solution UI.
- Relates https://github.com/elastic/integrations/issues/7483

[okta] Add tags.yml file so that integration's dashboards and saved searches are tagged with 'Security Solution' 

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/kibana/csp_rule_template/00bb0b02-fe51-5b6b-a2b5-d51608ec7d4c.json
packages/cloud_security_posture/kibana/csp_rule_template/1e4f8b50-90e4-5e99-8a40-a21b142eb6b4.json
packages/cloud_security_posture/kibana/csp_rule_template/27acd88e-c64f-5e9e-9cff-2de649f92ccf.json
packages/cloud_security_posture/kibana/csp_rule_template/37fc1edc-a59d-5e63-a530-d3d088195865.json
packages/cloud_security_posture/kibana/csp_rule_template/8f88e7f7-6924-5913-bc18-95fcdc5ae744.json
packages/cloud_security_posture/kibana/csp_rule_template/a9f473e3-a8b4-5076-b59a-f0d1c5a961ba.json
packages/cloud_security_posture/kibana/csp_rule_template/e06f9ef1-eedb-5f95-b8d4-36d27d602afd.json
packages/cloud_security_posture/manifest.yml

Adds rule templates
- Closes https://github.com/elastic/csp-security-policies/issues/305

[Cloud Security] Add GCP rule templates

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/0678bc9c-b71a-433b-87e6-2f664b6b3131_1.json
packages/security_detection_engine/kibana/security_rule/18a5dd9a-e3fa-4996-99b1-ae533b8f27fc_1.json
packages/security_detection_engine/kibana/security_rule/19e9daf3-f5c5-4bc2-a9af-6b1e97098f03_1.json
packages/security_detection_engine/kibana/security_rule/2377946d-0f01-4957-8812-6878985f515d_1.json
packages/security_detection_engine/kibana/security_rule/301571f3-b316-4969-8dd0-7917410030d3_1.json
packages/security_detection_engine/kibana/security_rule/36c48a0c-c63a-4cbc-aee1-8cac87db31a9_1.json
packages/security_detection_engine/kibana/security_rule/3e0561b5-3fac-4461-84cc-19163b9aaa61_1.json
packages/security_detection_engine/kibana/security_rule/3f4e2dba-828a-452a-af35-fe29c5e78969_1.json
packages/security_detection_engine/kibana/security_rule/814d96c7-2068-42aa-ba8e-fe0ddd565e2e_1.json
packages/security_detection_engine/kibana/security_rule/8d366588-cbd6-43ba-95b4-0971c3f906e5_1.json
packages/security_detection_engine/kibana/security_rule/a74c60cb-70ee-4629-a127-608ead14ebf1_1.json
packages/security_detection_engine/kibana/security_rule/a8d35ca0-ad8d-48a9-9f6c-553622dca61a_1.json
packages/security_detection_engine/kibana/security_rule/be4c5aed-90f5-4221-8bd5-7ab3a4334751_1.json
packages/security_detection_engine/kibana/security_rule/e0cc3807-e108-483c-bf66-5a4fbe0d7e89_1.json
packages/security_detection_engine/kibana/security_rule/e9b0902b-c515-413b-b80b-a8dcebc81a66_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.7.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/aee487db92fb7ed22dfd210fba80fe70c1747c74
* https://github.com/elastic/ia-trade-team/issues/185
None

[Security Rules] Update security rules package to v8.7.14-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/0678bc9c-b71a-433b-87e6-2f664b6b3131_1.json
packages/security_detection_engine/kibana/security_rule/18a5dd9a-e3fa-4996-99b1-ae533b8f27fc_1.json
packages/security_detection_engine/kibana/security_rule/19e9daf3-f5c5-4bc2-a9af-6b1e97098f03_1.json
packages/security_detection_engine/kibana/security_rule/2377946d-0f01-4957-8812-6878985f515d_1.json
packages/security_detection_engine/kibana/security_rule/301571f3-b316-4969-8dd0-7917410030d3_1.json
packages/security_detection_engine/kibana/security_rule/36c48a0c-c63a-4cbc-aee1-8cac87db31a9_1.json
packages/security_detection_engine/kibana/security_rule/3e0561b5-3fac-4461-84cc-19163b9aaa61_1.json
packages/security_detection_engine/kibana/security_rule/3f4e2dba-828a-452a-af35-fe29c5e78969_1.json
packages/security_detection_engine/kibana/security_rule/814d96c7-2068-42aa-ba8e-fe0ddd565e2e_1.json
packages/security_detection_engine/kibana/security_rule/8d366588-cbd6-43ba-95b4-0971c3f906e5_1.json
packages/security_detection_engine/kibana/security_rule/a74c60cb-70ee-4629-a127-608ead14ebf1_1.json
packages/security_detection_engine/kibana/security_rule/a8d35ca0-ad8d-48a9-9f6c-553622dca61a_1.json
packages/security_detection_engine/kibana/security_rule/be4c5aed-90f5-4221-8bd5-7ab3a4334751_1.json
packages/security_detection_engine/kibana/security_rule/e0cc3807-e108-483c-bf66-5a4fbe0d7e89_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_105.json
packages/security_detection_engine/kibana/security_rule/e9b0902b-c515-413b-b80b-a8dcebc81a66_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.9.7-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dcc720a2590c970fe199850986bd898dc8b377cf
* https://github.com/elastic/ia-trade-team/issues/185
None

[Security Rules] Update security rules package to v8.9.7-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/0678bc9c-b71a-433b-87e6-2f664b6b3131_1.json
packages/security_detection_engine/kibana/security_rule/18a5dd9a-e3fa-4996-99b1-ae533b8f27fc_1.json
packages/security_detection_engine/kibana/security_rule/19e9daf3-f5c5-4bc2-a9af-6b1e97098f03_1.json
packages/security_detection_engine/kibana/security_rule/2377946d-0f01-4957-8812-6878985f515d_1.json
packages/security_detection_engine/kibana/security_rule/301571f3-b316-4969-8dd0-7917410030d3_1.json
packages/security_detection_engine/kibana/security_rule/36c48a0c-c63a-4cbc-aee1-8cac87db31a9_1.json
packages/security_detection_engine/kibana/security_rule/3e0561b5-3fac-4461-84cc-19163b9aaa61_1.json
packages/security_detection_engine/kibana/security_rule/3f4e2dba-828a-452a-af35-fe29c5e78969_1.json
packages/security_detection_engine/kibana/security_rule/814d96c7-2068-42aa-ba8e-fe0ddd565e2e_1.json
packages/security_detection_engine/kibana/security_rule/8d366588-cbd6-43ba-95b4-0971c3f906e5_1.json
packages/security_detection_engine/kibana/security_rule/a74c60cb-70ee-4629-a127-608ead14ebf1_1.json
packages/security_detection_engine/kibana/security_rule/a8d35ca0-ad8d-48a9-9f6c-553622dca61a_1.json
packages/security_detection_engine/kibana/security_rule/be4c5aed-90f5-4221-8bd5-7ab3a4334751_1.json
packages/security_detection_engine/kibana/security_rule/e0cc3807-e108-483c-bf66-5a4fbe0d7e89_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_105.json
packages/security_detection_engine/kibana/security_rule/e9b0902b-c515-413b-b80b-a8dcebc81a66_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.8.12.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/4aeafd9af83ea43c0a9b5df5cf23443501438cf3
* https://github.com/elastic/ia-trade-team/issues/185
None

[Security Rules] Update security rules package to v8.8.12-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/0678bc9c-b71a-433b-87e6-2f664b6b3131_1.json
packages/security_detection_engine/kibana/security_rule/18a5dd9a-e3fa-4996-99b1-ae533b8f27fc_1.json
packages/security_detection_engine/kibana/security_rule/19e9daf3-f5c5-4bc2-a9af-6b1e97098f03_1.json
packages/security_detection_engine/kibana/security_rule/2377946d-0f01-4957-8812-6878985f515d_1.json
packages/security_detection_engine/kibana/security_rule/301571f3-b316-4969-8dd0-7917410030d3_1.json
packages/security_detection_engine/kibana/security_rule/36c48a0c-c63a-4cbc-aee1-8cac87db31a9_1.json
packages/security_detection_engine/kibana/security_rule/3e0561b5-3fac-4461-84cc-19163b9aaa61_1.json
packages/security_detection_engine/kibana/security_rule/3f4e2dba-828a-452a-af35-fe29c5e78969_1.json
packages/security_detection_engine/kibana/security_rule/814d96c7-2068-42aa-ba8e-fe0ddd565e2e_1.json
packages/security_detection_engine/kibana/security_rule/8d366588-cbd6-43ba-95b4-0971c3f906e5_1.json
packages/security_detection_engine/kibana/security_rule/a74c60cb-70ee-4629-a127-608ead14ebf1_1.json
packages/security_detection_engine/kibana/security_rule/a8d35ca0-ad8d-48a9-9f6c-553622dca61a_1.json
packages/security_detection_engine/kibana/security_rule/be4c5aed-90f5-4221-8bd5-7ab3a4334751_1.json
packages/security_detection_engine/kibana/security_rule/e0cc3807-e108-483c-bf66-5a4fbe0d7e89_1.json
packages/security_detection_engine/kibana/security_rule/e72f87d0-a70e-4f8d-8443-a6407bc34643_105.json
packages/security_detection_engine/kibana/security_rule/e9b0902b-c515-413b-b80b-a8dcebc81a66_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.10.4-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/e38cb6ee58cf4daa9e1b334df1d94dd7d126f35d
* https://github.com/elastic/ia-trade-team/issues/185
None

[Security Rules] Update security rules package to v8.10.4-beta.1

---

packages/spring_boot/changelog.yml
packages/spring_boot/data_stream/audit_events/agent/stream/stream.yml.hbs
packages/spring_boot/data_stream/gc/agent/stream/stream.yml.hbs
packages/spring_boot/data_stream/gc/fields/ecs.yml
packages/spring_boot/data_stream/gc/manifest.yml
packages/spring_boot/data_stream/gc/sample_event.json
packages/spring_boot/data_stream/http_trace/agent/stream/stream.yml.hbs
packages/spring_boot/data_stream/memory/agent/stream/stream.yml.hbs
packages/spring_boot/data_stream/memory/fields/ecs.yml
packages/spring_boot/data_stream/memory/manifest.yml
packages/spring_boot/data_stream/memory/sample_event.json
packages/spring_boot/data_stream/threading/agent/stream/stream.yml.hbs
packages/spring_boot/data_stream/threading/fields/ecs.yml
packages/spring_boot/data_stream/threading/manifest.yml
packages/spring_boot/data_stream/threading/sample_event.json
packages/spring_boot/docs/README.md
packages/spring_boot/manifest.yml

- Bug
- Tags support was not provided earlier so adding tags support to the datastreams
- Updating title from the manifest file
- Closes https://github.com/elastic/integrations/issues/8088
- Relates https://github.com/elastic/integrations/issues/7289

[O11y] [Springboot] support tags to gc, memory and threading datastreams

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Update ARM link to be linked to latest revision of the 8.11 branch, not main.

[Cloud Security] Azure: Link to 8.11 ARM template

---

packages/cloud_defend/_dev/build/build.yml

ref v8.10.0 ecs tag instead of 8.10 ecs branch

---

packages/panw/_dev/benchmark/system/threat-logs.yml
packages/panw/_dev/benchmark/system/traffic-logs.yml
packages/panw/validation.yml

[panw] address linting in `_dev/benchmark/system` configs

---

.ci/schedule-daily.groovy

Update daily integration tests to run against 8.11 snapshot.

run daily job with 8.11

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.10.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/045de05e46881fd5dabaaab87afc273f8b852147
None
None

[Security Rules] Update security rules package to v8.10.4

---

packages/slack/_dev/deploy/docker/docker-compose.yml
packages/slack/_dev/deploy/docker/files/config.yml
packages/slack/changelog.yml
packages/slack/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/slack/manifest.yml
packages/slack/validation.yml

The cursor does not include the oldest limit information, so this needs to be included in requests when paginating through responses.
- Fixes #8163
- Depends elastic/stream#59

slack: fix handling of oldest parameter when paginating

---

packages/aws/data_stream/ec2_metrics/_dev/deploy/tf/main.tf

Currently, aws package is failing due to a terraform failure: https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/2902/pipeline
This PR adds the required tags to be able to create the needed AWS resources for testing.
No version updated since it just updates the terraform files.
- Relates https://github.com/elastic/elastic-package/pull/1505

Add tags for aws package resources

---

packages/panw/_dev/benchmark/system/threat-benchmark/config.yml
packages/panw/_dev/benchmark/system/traffic-benchmark/config.yml
packages/panw/changelog.yml

Bug
`elastic-package@v0.90.0` updated to v0.7.0 of the corpora generator tool
the new version introduced several changes in the config yaml format.
this PR fixes the `panw` package system benchmark assets for that
without this fix random data would be generated breaking the test because the events will be generate an error in the ingest pipeline
Run with the latest elastic-package release from a local checkout of this branch inside the `panw` integration folder the following command:
`elastic-package …

update generator configs content to v0.7.0 format

---

packages/nats/changelog.yml
packages/nats/data_stream/connection/manifest.yml
packages/nats/data_stream/connections/manifest.yml
packages/nats/data_stream/route/manifest.yml
packages/nats/data_stream/routes/manifest.yml
packages/nats/data_stream/stats/manifest.yml
packages/nats/data_stream/subscriptions/manifest.yml
packages/nats/manifest.yml

Enable TSDB for metrics data streams.
- Relates #7745

[NATS] Enable TSDB

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Add version check in Cloudformation to ensure that the elastic-agent version is always greater than or equal to Cloudformation template version.
-

CloudFormation version hardening

---

packages/microsoft_sqlserver/_dev/build/docs/README.md
packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/docs/README.md
packages/microsoft_sqlserver/manifest.yml

Addresses feedback provided after #8240 was merged. See review comments: https://github.com/elastic/integrations/pull/8240#pullrequestreview-1705490249
Update documentation
View [the README](https://github.com/colleenmcginnis/integrations/blob/pr-8240-follow-up/packages/microsoft_sqlserver/docs/README.md).
Related to https://github.com/elastic/integrations/pull/8240

[docs] Update MSSQL README

---

packages/prisma_cloud/changelog.yml
packages/prisma_cloud/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
packages/prisma_cloud/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/prisma_cloud/data_stream/audit/sample_event.json
packages/prisma_cloud/docs/README.md
packages/prisma_cloud/manifest.yml

[Prisma Cloud] Extract user.name from user.email in audit data_stream

---

packages/apache_tomcat/_dev/build/docs/README.md
packages/apache_tomcat/changelog.yml
packages/apache_tomcat/docs/README.md
packages/apache_tomcat/manifest.yml

Update README with the latest version of Prometheus support and add a line in the troubleshooting section for Timezone.
- Relates #7363

[O11y][Apache Tomcat] Update description in README.md

---

.buildkite/hooks/pre-command
.buildkite/pipeline.schedule-daily.yml
.buildkite/scripts/common.sh

Fix Buildkite schedule-daily job definition.
Error:
https://buildkite.com/elastic/integrations-schedule-daily/builds/15#018bb6da-1288-4d21-ae29-53cd44430aaf/69-74
- Follow-up #8316

[Buildkite] Remove duplicated keys from steps in schedule-daily

---

.buildkite/pipeline.schedule-daily.yml

Update pipeline triggered in schedule-daily job to test packages using local Elastic stacks (elastic-package)

[Buildkite] Fix pipeline triggered to test local packages in schedule-daily

---

.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/scripts/common.sh
.buildkite/scripts/find_oldest_supported_version.py
.buildkite/scripts/test_integrations_with_serverless.sh
.buildkite/scripts/test_one_package.sh
.buildkite/scripts/trigger_integrations_in_parallel.sh

This PR updates hooks and scripts used by Buildkite
-

[Buildkite] Update hooks and scripts

---

packages/entityanalytics_okta/_dev/deploy/docker/files/config.yml
packages/entityanalytics_okta/changelog.yml
packages/entityanalytics_okta/data_stream/user/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_okta/data_stream/user/manifest.yml
packages/entityanalytics_okta/manifest.yml

Test infrastructure is added for device/all datasets to be tested, but this is not enabled to allow retention of users below 8.11.
Note: running tests against v8.11 with dataset=all passes locally. When kibana.version is bumped to 8.11+ we can add the all case system test config.
- Fixes #8468

entityanalytics_okta: allow dataset selection

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Add cloudbeat azure credentials configuration.
- Closes https://github.com/elastic/cloudbeat/issues/1292

Add cloudbeat Azure Credentials config

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/kibana/csp_rule_template/0d5ddd5f-749b-516b-89ca-b5bf18ba4861.json
packages/cloud_security_posture/manifest.yml

[CSP] Add CIS Azure 5.3.1

---

.buildkite/pipeline.serverless.yml
.buildkite/scripts/trigger_integrations_in_parallel.sh

This PR updates the list of paths to be uploaded as artifacts. It adds the same paths as in Jenkins: https://github.com/elastic/integrations/blob/9fc2ebcc8957cea8ba53f5901f59b21cfcadc7b0/.ci/Jenkinsfile#L143C29-L143C29
-

[Buildkite] Update paths to be uploaded as artifacts in Buildkite

---

packages/cisco_ise/changelog.yml
packages/cisco_ise/data_stream/log/_dev/test/pipeline/test-pipeline-cise-alarm.log
packages/cisco_ise/data_stream/log/_dev/test/pipeline/test-pipeline-cise-alarm.log-expected.json
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_alarm.yml
packages/cisco_ise/data_stream/log/fields/ecs.yml
packages/cisco_ise/data_stream/log/fields/fields.yml
packages/cisco_ise/docs/README.md
packages/cisco_ise/manifest.yml

cisco_ios: support CISE_Alarm events

---

packages/fortinet_fortigate/changelog.yml
packages/fortinet_fortigate/data_stream/log/agent/stream/log.yml.hbs
packages/fortinet_fortigate/data_stream/log/agent/stream/tcp.yml.hbs
packages/fortinet_fortigate/data_stream/log/agent/stream/udp.yml.hbs
packages/fortinet_fortigate/manifest.yml

fortigate_fortigate: fix indentation in hbs templates

---

packages/elastic_package_registry/_dev/deploy/docker/packages/test_package/0.0.1/manifest.yml
packages/elastic_package_registry/changelog.yml
packages/elastic_package_registry/data_stream/metrics/fields/fields.yml
packages/elastic_package_registry/kibana/dashboard/elastic_package_registry-313c2700-099b-11ed-91b6-3b1f9c2b2771.json
packages/elastic_package_registry/manifest.yml

Update package format to 3.0.1, and fix issues with legacy visualizations and lack of filter.

[elastic_package_registry] Fix legacy visualization

---

packages/system/changelog.yml
packages/system/data_stream/auth/agent/stream/log.yml.hbs
packages/system/data_stream/syslog/agent/stream/log.yml.hbs
packages/system/manifest.yml

In the case that the user has configured no tags, but has configured preserve original event, no tags configuration fields is included in the rendered configuration. This results in the preserve_original_event being added as a sub-array to the add_locale filebeat processor and apparently not failing, but not informing ingest to retain the event. It is not possible to test the fix here due to this absence of policy failure.
Also fix exclude_files pattern in syslog and auth.
Note: this was tested manually.
-

system: fix handling of tags in syslog datastream

---

packages/sonicwall_firewall/changelog.yml
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-drizzthacker.log-expected.json
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-general.log-expected.json
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-nat.log-expected.json
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-sonicos70-aws.log-expected.json
packages/sonicwall_firewall/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/sonicwall_firewall/data_stream/log/fields/ecs.yml
packages/sonicwall_firewall/data_stream/log/sample_event.json
packages/sonicwall_firewall/docs/README.md
packages/sonicwall_firewall/manifest.yml

sonicwall_firewall: log host identity and syslog priority

---

packages/aws/_dev/benchmark/rally/ec2logs-benchmark/fields.yml
packages/aws/_dev/benchmark/rally/ec2logs-benchmark/template.ndjson
packages/kubernetes/_dev/benchmark/rally/container-benchmark/config.yml
packages/kubernetes/_dev/benchmark/rally/container-benchmark/template.ndjson
packages/kubernetes/_dev/benchmark/rally/pod-benchmark/config.yml
packages/kubernetes/_dev/benchmark/rally/pod-benchmark/template.ndjson

Enhancement
Fix timestamp range from/to for kubernetes integrations
Remove event.ingested for aws ec2logs
-

fix rally assets

---

packages/azure_billing/changelog.yml
packages/azure_billing/kibana/dashboard/azure_billing-d3efeb30-c1c7-11ea-b7e7-0f48178cdb3c.json
packages/azure_billing/manifest.yml

Fix missing reference for filter in azure billing dashboard.

[Bug] fix missing reference for filter in dashboard

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
packages/infoblox_nios/data_stream/log/fields/fields.yml
packages/infoblox_nios/docs/README.md
packages/infoblox_nios/manifest.yml

infoblox_nios: fix handling of messages containing view field

---

packages/network_traffic/changelog.yml
packages/network_traffic/data_stream/amqp/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/cassandra/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/dhcpv4/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/dns/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/flow/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/http/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/icmp/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/memcached/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/mongodb/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/mysql/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/nfs/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/pgsql/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/redis/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/sip/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/thrift/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/data_stream/tls/elasticsearch/ingest_pipeline/compatibility.yml
packages/network_traffic/manifest.yml

network_traffic: add process.parent.pid remapping to compatibility pipelines

---

.buildkite/pipeline.yml
.buildkite/scripts/trigger_publish_packages.sh
.ci/Jenkinsfile

Reverts elastic/integrations#8638

Revert "[Buildkite] Enable buildkite publishing"

---

.buildkite/pipeline.yml
.buildkite/scripts/trigger_publish_packages.sh
.ci/Jenkinsfile

Reverts elastic/integrations#8698

[Buildkite] Enable buildkite publishing

---

.buildkite/scripts/common.sh

Revisited how errors from `elastic-package stack up` command are managed. If that command, fails, there is no need to run the other tests since there is no Elastic stack running.
Example of build where this happened: https://buildkite.com/elastic/integrations/builds/7291#018c59fa-1dca-47c5-8968-bbbf11a506ac

[Buildkite] Manage errors if any from elastic-package stack up

---

packages/cloud_security_posture/kibana/csp_rule_template/b4133ca4-32f1-501e-ad0a-a22700208a4f.json

Add CIS Azure 6.1 Rule Template [(implementation)](https://github.com/elastic/cloudbeat/pull/1637)
Implement Azure CIS benchmarks
- Part of https://github.com/elastic/cloudbeat/issues/1419

Add CIS Azure 6.1 Rule Template

---

catalog-info.yaml

Update settings to avoid canceling the builds in backport branches as it happens with main branch.

[Buildkite] Update settings for integrations pipeline

---

.buildkite/hooks/pre-command

This PR updates the bucket settings to upload as artifacts the internal logs.

[Buildkite] Update bucket settings

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/fields/resource.yml
packages/cloud_security_posture/data_stream/findings/fields/result.yml
packages/cloud_security_posture/manifest.yml

Revert changes of https://github.com/elastic/integrations/pull/8679/ due to mappings issues on those fields in serverless environment. 
- https://github.com/elastic/security-team/issues/8328

[Cloud security] rollback disabled fields mappings

---

packages/cribl/changelog.yml
packages/cribl/manifest.yml

Bumping the integration version so that the updated docs from https://github.com/elastic/integrations/pull/8746 are published
-

[cribl] bumping integration version

---

packages/ti_anomali/changelog.yml
packages/ti_anomali/data_stream/threatstream/_dev/test/system/test-integrator-http-config.yml
packages/ti_anomali/data_stream/threatstream/_dev/test/system/test-webhook-http-config.yml
packages/ti_anomali/data_stream/threatstream/_dev/test/system/test-webhook-https-config.yml
packages/ti_anomali/data_stream/threatstream/agent/stream/http_endpoint.yml.hbs
packages/ti_anomali/data_stream/threatstream/elasticsearch/ingest_pipeline/default.yml
packages/ti_anomali/data_stream/threatstream/sample_event.json
packages/ti_anomali/docs/README.md
packages/ti_anomali/manifest.yml
packages/ti_otx/_dev/deploy/docker/config.yml
packages/ti_otx/changelog.yml
packages/ti_otx/data_stream/pulses_subscribed/_dev/test/system/test-default-config.yml
packages/ti_otx/data_stream/pulses_subscribed/agent/stream/cel.yml.hbs
packages/ti_otx/data_stream/pulses_subscribed/elasticsearch/ingest_pipeline/default.yml
packages/ti_otx/data_stream/pulses_subscribed/sample_event.json
packages/ti_otx/docs/README.md
packages/ti_otx/manifest.yml
packages/ti_threatq/_dev/deploy/docker/files/config.yml
packages/ti_threatq/changelog.yml
packages/ti_threatq/data_stream/threat/_dev/test/system/test-default-config.yml
packages/ti_threatq/data_stream/threat/agent/stream/httpjson.yml.hbs
packages/ti_threatq/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/ti_threatq/data_stream/threat/sample_event.json
packages/ti_threatq/docs/README.md
packages/ti_threatq/manifest.yml

Fixes the bug explained in https://github.com/elastic/integrations/issues/8785.
- Closes https://github.com/elastic/integrations/issues/8785

[Threat Intel] Fix IOC expiration duration character casting in painless script

---

packages/vsphere/_dev/build/docs/README.md
packages/vsphere/changelog.yml
packages/vsphere/docs/README.md
packages/vsphere/manifest.yml

This PR proposes a less confusing and more specific wording on the logs configuration details.
Closes https://github.com/elastic/integrations/issues/7244

vSphere - update details on logs configuration

---

packages/fortinet_fortigate/changelog.yml

Fix PR number in changelog

---

catalog-info.yaml

Update catalog-info settings to add current dependsOn relationships and enable comments with the status of each Pull Request.

[Buildkite] Update catalog-info settings

---

packages/aws/changelog.yml

Update the main AWS integration changelog with new backport releases on the `backport-aws-1.51` [^1] branch.
According to the updated backport workflow [^2] (step 4), we must update the main changelog when backport releases occur.
[^1]: https://github.com/elastic/integrations/tree/backport-aws-1.51
[^2]: https://github.com/elastic/integrations/blob/main/docs/developer_workflow_bug_fix_older_package_version.md
- Relates #8888 
- Relates #7438

AWS: Update integration changelog with backports releases

---

packages/ti_crowdstrike/_dev/deploy/docker/files/config.yml
packages/ti_crowdstrike/changelog.yml
packages/ti_crowdstrike/data_stream/intel/agent/stream/cel.yml.hbs
packages/ti_crowdstrike/data_stream/ioc/agent/stream/cel.yml.hbs
packages/ti_crowdstrike/manifest.yml

The pagination logic currently accesses the meta.pagination field, which
apparently may not exist. So protect against access in that case.
Also clean up CEL code and make test input data clearer.
- Fixes #8916

ti_crowdstrike: prevent eval failure when pagination is absent

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log-expected.json
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
packages/infoblox_nios/data_stream/log/fields/fields.yml
packages/infoblox_nios/docs/README.md
packages/infoblox_nios/manifest.yml

See title.
- [c] I have added an entry to my package's `changelog.yml` file.
- For #8930

infoblox_nios: handle rpz hit log messages

---

packages/mongodb/_dev/build/docs/README.md
packages/mongodb/changelog.yml
packages/mongodb/docs/README.md
packages/mongodb/manifest.yml

This PR modifies the documentation for the MongoDB integration, updating the tested version and ensuring consistency with beats.
- Closes #8973

Update metrics datastreams tested compatibility version in docs.

---

.github/CODEOWNERS
packages/beat/manifest.yml
packages/elasticsearch/manifest.yml
packages/enterprisesearch/manifest.yml
packages/kibana/manifest.yml
packages/logstash/manifest.yml
packages/platform_observability/manifest.yml

Replaced with Stack Monitoring.

Remove references to infra-monitoring-ui team

---

packages/cisco_secure_endpoint/changelog.yml
packages/cisco_secure_endpoint/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/cisco_secure_endpoint/manifest.yml

cisco_secure_endpoint: fix handling of potentially null method call receivers

---

packages/sonicwall_firewall/changelog.yml
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-drizzthacker.log-expected.json
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-general.log-expected.json
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-nat.log-expected.json
packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-sonicos70-aws.log-expected.json
packages/sonicwall_firewall/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/sonicwall_firewall/data_stream/log/fields/ecs.yml
packages/sonicwall_firewall/data_stream/log/sample_event.json
packages/sonicwall_firewall/docs/README.md
packages/sonicwall_firewall/manifest.yml

Bug
* Add fields event.sequence, event.severity, host.ip, and http.request.body.bytes to the ECS mappings
* Data Quality check finds default mapping of these fields (defaults to keyword) incompatible with ECS expected mapping types.
1. Add mappings to component template.
2. Ingest data
3. Validate mappings through devtools and correlate with ECS OR run Data Quality check in Security dashboard.

[Sonicwall] Add missing ECS field mappings

---

packages/cisco_ise/changelog.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_ad_connector.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_administrative_and_operational_audit.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_authentication_flow_diagnostics.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_failed_attempts.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_guest.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_identity_stores_diagnostics.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_internal_operations_diagnostics.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_mydevices.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_passed_authentications.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_policy_diagnostics.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_posture_and_client_provisioning_audit.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_radius_accounting.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_radius_diagnostics.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_system_statistics.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_tacacs_accounting.yml
packages/cisco_ise/data_stream/log/elasticsearch/ingest_pipeline/pipeline_threat_centric_nac.yml
packages/cisco_ise/manifest.yml

cisco_ise: fix handling of potentially null method call receivers

---

packages/zeek/changelog.yml
packages/zeek/data_stream/kerberos/elasticsearch/ingest_pipeline/default.yml
packages/zeek/data_stream/known_certs/elasticsearch/ingest_pipeline/default.yml
packages/zeek/data_stream/known_hosts/elasticsearch/ingest_pipeline/default.yml
packages/zeek/data_stream/known_services/elasticsearch/ingest_pipeline/default.yml
packages/zeek/data_stream/ntp/elasticsearch/ingest_pipeline/default.yml
packages/zeek/data_stream/signature/elasticsearch/ingest_pipeline/default.yml
packages/zeek/data_stream/software/elasticsearch/ingest_pipeline/default.yml
packages/zeek/manifest.yml

zeek: fix handling of potentially null method call receivers

---

packages/cel/changelog.yml
packages/cel/docs/README.md
packages/cel/manifest.yml
packages/httpjson/_dev/build/docs/README.md
packages/httpjson/changelog.yml
packages/httpjson/docs/README.md
packages/httpjson/manifest.yml

Make finding CEL easier and guide users to the new input if they are starting a new project.
-

cel,httpjson: advise to use CEL over HTTPJSON for new projects

---

packages/aws_logs/changelog.yml
packages/aws_logs/manifest.yml

This PR is to promote AWS custom logs package to GA 1.0.0 version.

Promote AWS custom logs package to GA

---

packages/apm/changelog.yml
packages/apm/data_stream/sampled_traces/fields/base-fields.yml
packages/apm/data_stream/service_destination_10m_metrics/fields/fields.yml
packages/apm/data_stream/service_destination_1m_metrics/fields/fields.yml
packages/apm/data_stream/service_destination_60m_metrics/fields/fields.yml
packages/apm/data_stream/service_summary_10m_metrics/fields/fields.yml
packages/apm/data_stream/service_summary_1m_metrics/fields/fields.yml
packages/apm/data_stream/service_summary_60m_metrics/fields/fields.yml
packages/apm/data_stream/service_transaction_10m_metrics/fields/fields.yml
packages/apm/data_stream/service_transaction_1m_metrics/fields/fields.yml
packages/apm/data_stream/service_transaction_60m_metrics/fields/fields.yml
packages/apm/data_stream/transaction_10m_metrics/fields/fields.yml
packages/apm/data_stream/transaction_1m_metrics/fields/fields.yml
packages/apm/data_stream/transaction_60m_metrics/fields/fields.yml
packages/apm/manifest.yml

Port apm constant keyword fix from 8.12
- https://github.com/elastic/apm-server/pull/12219

[apm] Port apm constant keyword fix from 8.12

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/035a6f21-4092-471d-9cda-9e379f459b1e_1.json
packages/security_detection_engine/kibana/security_rule/0369e8a6-0fa7-4e7a-961a-53180a4c966e_1.json
packages/security_detection_engine/kibana/security_rule/202829f6-0271-4e88-b882-11a655c590d4_1.json
packages/security_detection_engine/kibana/security_rule/2f95540c-923e-4f57-9dae-de30169c68b9_1.json
packages/security_detection_engine/kibana/security_rule/5c6f4c58-b381-452a-8976-f1b1c6aa0def_9.json
packages/security_detection_engine/kibana/security_rule/71d6a53d-abbd-40df-afee-c21fff6aafb0_1.json
packages/security_detection_engine/kibana/security_rule/7405ddf1-6c8e-41ce-818f-48bea6bcaed8_109.json
packages/security_detection_engine/kibana/security_rule/79124edf-30a8-4d48-95c4-11522cad94b1_2.json
packages/security_detection_engine/kibana/security_rule/86c3157c-a951-4a4f-989b-2f0d0f1f9518_1.json
packages/security_detection_engine/kibana/security_rule/97fc44d3-8dae-4019-ae83-298c3015600f_110.json
packages/security_detection_engine/kibana/security_rule/9c865691-5599-447a-bac9-b3f2df5f9a9d_8.json
packages/security_detection_engine/kibana/security_rule/9c951837-7d13-4b0c-be7a-f346623c8795_1.json
packages/security_detection_engine/kibana/security_rule/9f962927-1a4f-45f3-a57b-287f2c7029c1_112.json
packages/security_detection_engine/kibana/security_rule/a8afdce2-0ec1-11ee-b843-f661ea17fbcd_3.json
packages/security_detection_engine/kibana/security_rule/ad959eeb-2b7b-4722-ba08-a45f6622f005_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_3.json
packages/security_detection_engine/kibana/security_rule/c55badd3-3e61-4292-836f-56209dc8a601_2.json
packages/security_detection_engine/kibana/security_rule/d74d6506-427a-4790-b170-0c2a6ddac799_1.json
packages/security_detection_engine/kibana/security_rule/e707a7be-cc52-41ac-8ab3-d34b38c20005_2.json
packages/security_detection_engine/kibana/security_rule/eaef8a35-12e0-4ac0-bc14-81c72b6bd27c_1.json
packages/security_detection_engine/kibana/security_rule/eb44611f-62a8-4036-a5ef-587098be6c43_3.json
packages/security_detection_engine/kibana/security_rule/f3818c85-2207-4b51-8a28-d70fb156ee87_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.9.14-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/4ead9ee249e9428c2299ffe92f601268585ea646
* https://github.com/elastic/ia-trade-team/issues/288
None

[Security Rules] Update security rules package to v8.9.14-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/035a6f21-4092-471d-9cda-9e379f459b1e_1.json
packages/security_detection_engine/kibana/security_rule/0369e8a6-0fa7-4e7a-961a-53180a4c966e_1.json
packages/security_detection_engine/kibana/security_rule/202829f6-0271-4e88-b882-11a655c590d4_1.json
packages/security_detection_engine/kibana/security_rule/2f95540c-923e-4f57-9dae-de30169c68b9_1.json
packages/security_detection_engine/kibana/security_rule/5c6f4c58-b381-452a-8976-f1b1c6aa0def_9.json
packages/security_detection_engine/kibana/security_rule/71d6a53d-abbd-40df-afee-c21fff6aafb0_1.json
packages/security_detection_engine/kibana/security_rule/7405ddf1-6c8e-41ce-818f-48bea6bcaed8_109.json
packages/security_detection_engine/kibana/security_rule/79124edf-30a8-4d48-95c4-11522cad94b1_2.json
packages/security_detection_engine/kibana/security_rule/86c3157c-a951-4a4f-989b-2f0d0f1f9518_1.json
packages/security_detection_engine/kibana/security_rule/97fc44d3-8dae-4019-ae83-298c3015600f_110.json
packages/security_detection_engine/kibana/security_rule/9c865691-5599-447a-bac9-b3f2df5f9a9d_8.json
packages/security_detection_engine/kibana/security_rule/9c951837-7d13-4b0c-be7a-f346623c8795_1.json
packages/security_detection_engine/kibana/security_rule/9f962927-1a4f-45f3-a57b-287f2c7029c1_112.json
packages/security_detection_engine/kibana/security_rule/a8afdce2-0ec1-11ee-b843-f661ea17fbcd_3.json
packages/security_detection_engine/kibana/security_rule/ad959eeb-2b7b-4722-ba08-a45f6622f005_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_3.json
packages/security_detection_engine/kibana/security_rule/c55badd3-3e61-4292-836f-56209dc8a601_2.json
packages/security_detection_engine/kibana/security_rule/d74d6506-427a-4790-b170-0c2a6ddac799_1.json
packages/security_detection_engine/kibana/security_rule/e707a7be-cc52-41ac-8ab3-d34b38c20005_2.json
packages/security_detection_engine/kibana/security_rule/eaef8a35-12e0-4ac0-bc14-81c72b6bd27c_1.json
packages/security_detection_engine/kibana/security_rule/eb44611f-62a8-4036-a5ef-587098be6c43_3.json
packages/security_detection_engine/kibana/security_rule/f3818c85-2207-4b51-8a28-d70fb156ee87_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.10.11-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/98b7a409fca432612deafd33b9a36a70358d0d11
* https://github.com/elastic/ia-trade-team/issues/288
None

[Security Rules] Update security rules package to v8.10.11-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/035a6f21-4092-471d-9cda-9e379f459b1e_1.json
packages/security_detection_engine/kibana/security_rule/0369e8a6-0fa7-4e7a-961a-53180a4c966e_1.json
packages/security_detection_engine/kibana/security_rule/202829f6-0271-4e88-b882-11a655c590d4_1.json
packages/security_detection_engine/kibana/security_rule/2f95540c-923e-4f57-9dae-de30169c68b9_1.json
packages/security_detection_engine/kibana/security_rule/5c6f4c58-b381-452a-8976-f1b1c6aa0def_9.json
packages/security_detection_engine/kibana/security_rule/71d6a53d-abbd-40df-afee-c21fff6aafb0_1.json
packages/security_detection_engine/kibana/security_rule/7405ddf1-6c8e-41ce-818f-48bea6bcaed8_109.json
packages/security_detection_engine/kibana/security_rule/79124edf-30a8-4d48-95c4-11522cad94b1_2.json
packages/security_detection_engine/kibana/security_rule/86c3157c-a951-4a4f-989b-2f0d0f1f9518_1.json
packages/security_detection_engine/kibana/security_rule/97fc44d3-8dae-4019-ae83-298c3015600f_110.json
packages/security_detection_engine/kibana/security_rule/9c865691-5599-447a-bac9-b3f2df5f9a9d_8.json
packages/security_detection_engine/kibana/security_rule/9c951837-7d13-4b0c-be7a-f346623c8795_1.json
packages/security_detection_engine/kibana/security_rule/9f962927-1a4f-45f3-a57b-287f2c7029c1_112.json
packages/security_detection_engine/kibana/security_rule/a8afdce2-0ec1-11ee-b843-f661ea17fbcd_3.json
packages/security_detection_engine/kibana/security_rule/ad959eeb-2b7b-4722-ba08-a45f6622f005_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_3.json
packages/security_detection_engine/kibana/security_rule/c55badd3-3e61-4292-836f-56209dc8a601_2.json
packages/security_detection_engine/kibana/security_rule/d74d6506-427a-4790-b170-0c2a6ddac799_1.json
packages/security_detection_engine/kibana/security_rule/e707a7be-cc52-41ac-8ab3-d34b38c20005_2.json
packages/security_detection_engine/kibana/security_rule/eaef8a35-12e0-4ac0-bc14-81c72b6bd27c_1.json
packages/security_detection_engine/kibana/security_rule/eb44611f-62a8-4036-a5ef-587098be6c43_3.json
packages/security_detection_engine/kibana/security_rule/f3818c85-2207-4b51-8a28-d70fb156ee87_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.11.8-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/10d36f68728553ca1e5c8ec01644e45340d358f4
* https://github.com/elastic/ia-trade-team/issues/288
None

[Security Rules] Update security rules package to v8.11.8-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/035a6f21-4092-471d-9cda-9e379f459b1e_1.json
packages/security_detection_engine/kibana/security_rule/0369e8a6-0fa7-4e7a-961a-53180a4c966e_1.json
packages/security_detection_engine/kibana/security_rule/202829f6-0271-4e88-b882-11a655c590d4_1.json
packages/security_detection_engine/kibana/security_rule/2f95540c-923e-4f57-9dae-de30169c68b9_1.json
packages/security_detection_engine/kibana/security_rule/5c6f4c58-b381-452a-8976-f1b1c6aa0def_9.json
packages/security_detection_engine/kibana/security_rule/71d6a53d-abbd-40df-afee-c21fff6aafb0_1.json
packages/security_detection_engine/kibana/security_rule/7405ddf1-6c8e-41ce-818f-48bea6bcaed8_109.json
packages/security_detection_engine/kibana/security_rule/79124edf-30a8-4d48-95c4-11522cad94b1_2.json
packages/security_detection_engine/kibana/security_rule/86c3157c-a951-4a4f-989b-2f0d0f1f9518_1.json
packages/security_detection_engine/kibana/security_rule/97fc44d3-8dae-4019-ae83-298c3015600f_110.json
packages/security_detection_engine/kibana/security_rule/9c865691-5599-447a-bac9-b3f2df5f9a9d_8.json
packages/security_detection_engine/kibana/security_rule/9c951837-7d13-4b0c-be7a-f346623c8795_1.json
packages/security_detection_engine/kibana/security_rule/9f962927-1a4f-45f3-a57b-287f2c7029c1_112.json
packages/security_detection_engine/kibana/security_rule/a8afdce2-0ec1-11ee-b843-f661ea17fbcd_3.json
packages/security_detection_engine/kibana/security_rule/ad959eeb-2b7b-4722-ba08-a45f6622f005_1.json
packages/security_detection_engine/kibana/security_rule/b8f8da2d-a9dc-48c0-90e4-955c0aa1259a_3.json
packages/security_detection_engine/kibana/security_rule/c55badd3-3e61-4292-836f-56209dc8a601_2.json
packages/security_detection_engine/kibana/security_rule/d74d6506-427a-4790-b170-0c2a6ddac799_1.json
packages/security_detection_engine/kibana/security_rule/e707a7be-cc52-41ac-8ab3-d34b38c20005_2.json
packages/security_detection_engine/kibana/security_rule/eaef8a35-12e0-4ac0-bc14-81c72b6bd27c_1.json
packages/security_detection_engine/kibana/security_rule/eb44611f-62a8-4036-a5ef-587098be6c43_3.json
packages/security_detection_engine/kibana/security_rule/f3818c85-2207-4b51-8a28-d70fb156ee87_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.4-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/dadffb1d5cb44abb28680b6b45eed437fac89f91
* https://github.com/elastic/ia-trade-team/issues/288
None

[Security Rules] Update security rules package to v8.12.4-beta.1

---

packages/pulse_connect_secure/changelog.yml
packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log-expected.json
packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/pulse_connect_secure/data_stream/log/fields/fields.yml
packages/pulse_connect_secure/data_stream/log/sample_event.json
packages/pulse_connect_secure/docs/README.md
packages/pulse_connect_secure/manifest.yml

With #8873  a new field `pulse_secure.session` is introduced as a keyword. But there is an existing field that names `pulse_secure.session.id` having it as a session object.
Hence renaming the new field to `pulse_secure.session.id_short`. There is no clear documentation for this field but it has been referred from #8858 
- Closes #9043

[pulse_connect_secure] fix duplicate session field

---

packages/ti_recordedfuture/changelog.yml
packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-httpjson.log-expected.json
packages/ti_recordedfuture/data_stream/threat/_dev/test/pipeline/test-url-default.log-expected.json
packages/ti_recordedfuture/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/ti_recordedfuture/manifest.yml

Some detection rules depend on the presence of threat.indicator.url.full, so make it available in the document.
-

ti_recordedfuture: make threat.indicator.url.full available for rules

---

.buildkite/scripts/find_oldest_supported_version.py

Mostly code style change while investigating access to an unknown key.

Fix key access when looking for oldest supported version

---

.buildkite/hooks/pre-command

Add environment variables used in `elastic-package` to set variables to set variables for terraform.
-

[buildkite] Add environment variables to set variables in terraform

---

packages/netflow/changelog.yml
packages/netflow/kibana/dashboard/netflow-38012abe-c611-4124-8497-381fcd85acc8.json
packages/netflow/manifest.yml

Fixes duplicated dashboard items in Traffic Analysis dashboard.
- Relates elastic/sdh-beats#4374

[netflow] Fix duplicated names in dashboard

---

packages/vectra_detect/changelog.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-account-detection.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-account-lockdown.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-account-scoring.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-audit.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-host-detection.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-host-lockdown.yml
packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/pipeline-host-scoring.yml
packages/vectra_detect/manifest.yml

```
[vectra_detect] Clean up null handling (#)
- Combine alternate value checks into single contains check.
```

[vectra_detect] Clean up null handling

---

packages/azure_metrics/changelog.yml
packages/azure_metrics/manifest.yml

This PR updates the changelog and manifest files for https://github.com/elastic/integrations/pull/9065.

Update changelog and manifest for #9065

---

.buildkite/hooks/pre-command

This PR update how Terraform labels used for branch names are set.
Related issue: https://github.com/elastic/elastic-package/pull/1698

[Buildkite] Update branch name labels used in terraform

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.11.9.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c772b2a842a6551e83867f2ff58bc349e6c63de4
None
None

[Security Rules] Update security rules package to v8.11.9

---

packages/ti_crowdstrike/_dev/build/docs/README.md
packages/ti_crowdstrike/changelog.yml
packages/ti_crowdstrike/data_stream/intel/agent/stream/cel.yml.hbs
packages/ti_crowdstrike/data_stream/intel/sample_event.json
packages/ti_crowdstrike/data_stream/ioc/sample_event.json
packages/ti_crowdstrike/docs/README.md
packages/ti_crowdstrike/manifest.yml

Type of change
- BugFix
**1. TypeCast the cursor value to string**
Typecast the cursor value to string as it is throwing error after intervals -
```
"error": {
"message": "failed eval: no such overload"
},
```
**2. Update the Readme**
Add user roles and management documentation link in readme.
Move to integrations/packages/ti_crowdstrike directory.
[ti_crowdstrike-test-logs.txt](https://github.com/elastic/integrations/files/14374487/ti_crowdstrike-test-logs.txt)

[ti_crowdstrike] Typecast the Cursor Value and Update Readme.

---

packages/ti_crowdstrike/_dev/deploy/docker/files/config.yml
packages/ti_crowdstrike/changelog.yml
packages/ti_crowdstrike/data_stream/intel/agent/stream/cel.yml.hbs
packages/ti_crowdstrike/manifest.yml

Without the int conversion the timestamp will be rendered as a double using e-notation. Timestamps are under 1p53, so no special care is required to ensure no loss of precision.
- Closes #9287

ti_crowdstrike: ensure timestamp is rendered as an integer

---

packages/ti_otx/changelog.yml
packages/ti_otx/data_stream/pulses_subscribed/_dev/test/pipeline/test-otx-pulses-subscribed-json.log-expected.json
packages/ti_otx/data_stream/pulses_subscribed/elasticsearch/ingest_pipeline/default.yml
packages/ti_otx/data_stream/pulses_subscribed/fields/fields.yml
packages/ti_otx/data_stream/pulses_subscribed/sample_event.json
packages/ti_otx/data_stream/threat/sample_event.json
packages/ti_otx/docs/README.md
packages/ti_otx/elasticsearch/transform/latest_ioc/fields/fields.yml
packages/ti_otx/manifest.yml

ti_otx: fix type mapping inconsistency for otx.id field

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bump up package version from 1.8.0-preview to 1.8.0

[Cloud Security] Bump up version

---

packages/trendmicro/changelog.yml
packages/trendmicro/data_stream/deep_security/_dev/test/pipeline/test-trendmicro.json-expected.json
packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/default.yml
packages/trendmicro/manifest.yml

trendmicro: use CEF name as event.action if no action is specified

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/manifest.yml
packages/qualys_vmdr/data_stream/knowledge_base/manifest.yml
packages/qualys_vmdr/manifest.yml

Requests to the API may take significant time to complete, so increase the default and document that short timeouts may cause requests to fail to help users avoid this issue.
- Closes #9365

qualys_vmdr: increase request timeout and document

---

.buildkite/scripts/backport_branch.sh

Fix backport script to support different yaml expression of `version`. When it can be surrounded with double qoutes
-

Fixing versions surrounded by quotes

---

.buildkite/scripts/backport_branch.sh

Check the version of the package from the commit SHA introduced in the input step instead from the main branch.

Check version from BASE_COMMIT changeset to create backport branches

---

docs/generic_guidelines.md

This PR documents the field limit behavior for integrations as implemented in https://github.com/elastic/kibana/pull/178398

Document field limit

---

packages/barracuda/changelog.yml
packages/barracuda/manifest.yml
packages/barracuda_cloudgen_firewall/changelog.yml
packages/barracuda_cloudgen_firewall/manifest.yml

barracuda,barracuda_cloudgen_firewall: update manifest version format to v3.0.3

---

packages/carbonblack_edr/changelog.yml
packages/carbonblack_edr/data_stream/log/_dev/test/system/test-http-config.yml
packages/carbonblack_edr/data_stream/log/_dev/test/system/test-logfile-config.yml
packages/carbonblack_edr/data_stream/log/_dev/test/system/test-tcp-config.yml
packages/carbonblack_edr/data_stream/log/_dev/test/system/test-udp-config.yml
packages/carbonblack_edr/manifest.yml
packages/cribl/changelog.yml
packages/cribl/manifest.yml
packages/cyberark_pta/changelog.yml
packages/cyberark_pta/data_stream/events/_dev/test/system/test-tcp-config.yml
packages/cyberark_pta/data_stream/events/_dev/test/system/test-udp-config.yml
packages/cyberark_pta/manifest.yml
packages/cyberarkpas/changelog.yml
packages/cyberarkpas/data_stream/audit/_dev/test/system/test-logfile-config.yml
packages/cyberarkpas/data_stream/audit/_dev/test/system/test-tcp-config.yml
packages/cyberarkpas/data_stream/audit/_dev/test/system/test-tls-config.yml
packages/cyberarkpas/data_stream/audit/_dev/test/system/test-udp-config.yml
packages/cyberarkpas/manifest.yml

carbonblack_edr,cribl,cyberark_pta,cyberarkpas: update manifest version format to v3.0.3

---

packages/thycotic_ss/changelog.yml
packages/thycotic_ss/data_stream/logs/_dev/test/system/test-logfile-config.yml
packages/thycotic_ss/data_stream/logs/_dev/test/system/test-tcp-config.yml
packages/thycotic_ss/data_stream/logs/_dev/test/system/test-udp-config.yml
packages/thycotic_ss/manifest.yml
packages/ti_abusech/changelog.yml
packages/ti_abusech/data_stream/malware/_dev/test/system/test-default-config.yml
packages/ti_abusech/data_stream/malwarebazaar/_dev/test/system/test-default-config.yml
packages/ti_abusech/data_stream/threatfox/_dev/test/system/test-default-config.yml
packages/ti_abusech/data_stream/url/_dev/test/system/test-default-config.yml
packages/ti_abusech/manifest.yml
packages/ti_util/changelog.yml
packages/ti_util/manifest.yml
packages/tines/changelog.yml
packages/tines/data_stream/audit_logs/_dev/test/system/test-default-config.yml
packages/tines/data_stream/audit_logs/fields/fields.yml
packages/tines/data_stream/time_saved/_dev/test/system/test-default-config.yml
packages/tines/docs/README.md
packages/tines/manifest.yml
packages/zscaler_zpa/changelog.yml
packages/zscaler_zpa/data_stream/app_connector_status/_dev/test/system/test-default-config.yml
packages/zscaler_zpa/data_stream/audit/_dev/test/system/test-default-config.yml
packages/zscaler_zpa/data_stream/browser_access/_dev/test/system/test-default-config.yml
packages/zscaler_zpa/data_stream/user_activity/_dev/test/system/test-default-config.yml
packages/zscaler_zpa/data_stream/user_status/_dev/test/system/test-default-config.yml
packages/zscaler_zpa/manifest.yml

thycotic_ss,ti_abusech,ti_util,tines,zscaler_zpa: update manifest version format to v3.0.3

---

packages/log/changelog.yml
packages/log/manifest.yml

Update description of Custom Logs input to provide details to which settings can be used.
Enhance the Custom Logs input description with a pointer to the docs.

Update description of Custom Logs input

---

dev/codeowners/codeowners.go

Use standard library for errors wrapping in codeowners tool.

Re-wrap errors in codeowners tool

---

packages/cisco_ios/_dev/build/docs/README.md
packages/cisco_ios/changelog.yml
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-badauth.log
packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-badauth.log-expected.json
packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ios/docs/README.md
packages/cisco_ios/manifest.yml

cisco_ios: fix bad auth grok processor handling of missing MD5 sums

---

packages/okta/changelog.yml
packages/okta/data_stream/system/_dev/test/system/test-oauth2-pem-config.yml
packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
packages/okta/manifest.yml

okta: allow users to provide private key as a PEM block

---

packages/eset_protect/changelog.yml

Fixes changelog link for #9465.
@efd6

Fix changelog for previously merged PR

---

packages/cisco_ftd/changelog.yml
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-session.log
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-session.log-expected.json
packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ftd/manifest.yml

This PR fixes access to null network when calculating bytes for Event 113019
N/A
`cd integrations/packages/cisco_ftd && elastic-package test pipeline`
- Closes https://github.com/elastic/integrations/issues/9198
N/A

[cisco_ftd]: allocate network if null when calculating bytes for Event 113019

---

packages/cisco_ftd/changelog.yml
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ftd/manifest.yml

This PR makes FTD suffix optional
N/A
`cd integrations/packages/cisco_ftd && elastic-package test pipeline`
- Closes https://github.com/elastic/integrations/issues/9241
N/A

[cisco_ftd]: treat FTD suffix as optional

---

packages/tanium/changelog.yml
packages/tanium/data_stream/threat_response/_dev/test/pipeline/test-common-config.yml
packages/tanium/data_stream/threat_response/_dev/test/system/test-http-endpoint-config.yml
packages/tanium/data_stream/threat_response/_dev/test/system/test-tcp-config.yml
packages/tanium/data_stream/threat_response/fields/fields.yml
packages/tanium/docs/README.md
packages/tanium/manifest.yml

tanium: update manifest version format to v3.0.3

---

packages/vectra_detect/changelog.yml
packages/vectra_detect/data_stream/log/_dev/test/pipeline/test-common-config.yml
packages/vectra_detect/data_stream/log/_dev/test/system/test-tcp-config.yml
packages/vectra_detect/data_stream/log/_dev/test/system/test-tls-config.yml
packages/vectra_detect/data_stream/log/_dev/test/system/test-udp-config.yml
packages/vectra_detect/manifest.yml

vectra_detect: update manifest version format to v3.0.3

---

packages/nginx_ingress_controller/changelog.yml
packages/nginx_ingress_controller/data_stream/error/elasticsearch/ingest_pipeline/default.yml
packages/nginx_ingress_controller/manifest.yml

After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `nginx_ingress_controller`
```
detected ingest pipeline warnings: 1: regular expression has ']' without escape
```
N/A 
N/A
N/A

[nginx_ingress_controller]: escape bracket inside regex expression

---

packages/cisco_secure_email_gateway/changelog.yml
packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/pipeline_amp.yml
packages/cisco_secure_email_gateway/manifest.yml

After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `cisco_secure_email_gateway`
```
detected ingest pipeline warnings: 1: regular expression has ']' without escape
```
N/A 
N/A
N/A

[cisco_secure_email_gateway]: escape bracket inside regex expression

---

packages/pulse_connect_secure/changelog.yml
packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/pulse_connect_secure/manifest.yml

After tackling [this issue](https://github.com/elastic/integrations/issues/9489), a respective [PR](https://github.com/elastic/elastic-package/pull/1755) was created to `elastic-package` to mainstream the detection of similar warnings. Thus this PR fixes the following similar to the former issue regex-related warning for `pulse_connect_secure`
```
detected ingest pipeline warnings: 1: regular expression has redundant nested repeat operator * /(?:Agent login (?<WORD:_tmp.outcome>\b\w+\b) for (?:.*?)(?:\(session:(?:\s*)?(?<NOTSPACE:pulse_secure.session.id>\S+)\)) from (?:(?:(?:((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2}) …
```

[pulse_connect_secure]: remove redundant nested repeat operator *

---

packages/citrix_adc/changelog.yml
packages/citrix_adc/manifest.yml

Type of change
- Enhancement
- Update manifest description to remain in line with other integrations.
- Move to integrations/packages/citrix_adc directory.

[citrix_adc] Update description to include log processing

---

packages/azure_metrics/changelog.yml
packages/azure_metrics/data_stream/container_instance/fields/package-fields.yml
packages/azure_metrics/data_stream/storage_account/fields/agent.yml
packages/azure_metrics/data_stream/storage_account/fields/ecs.yml
packages/azure_metrics/docs/README.md
packages/azure_metrics/docs/container_instance.md
packages/azure_metrics/manifest.yml
packages/azure_metrics/validation.yml

- Define the `client_secret` variable as secret.
- Bump the package-spec version to `3.1.2` (secrets require at least 3.0.2)
- Bump Kibana version constraints to `^8.12.0` (`^8.10.0` to get secrets support, `^8.12.0` to avoid known bugs)
This ensures their values are encrypted and hidden from the settings UI in Kibana, significantly enhancing security.
- Relates #8610

Add secrets support to the Azure Metrics integration

---

packages/entityanalytics_entra_id/changelog.yml
packages/entityanalytics_entra_id/data_stream/entity/manifest.yml
packages/entityanalytics_entra_id/manifest.yml

Fix link to the Entity Analytics filebeat documentation.

entityanalytics_entra_id - Fix input link

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bump integration version - `1.9.0-preview04` with Cloud Provider templates updates for stack version 8.14

[Cloud Security] Bump integration

---

packages/system/changelog.yml
packages/system/kibana/dashboard/system-71f720f0-ff18-11e9-8405-516218e3d268.json
packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
packages/system/kibana/dashboard/system-Logs-syslog-dashboard.json
packages/system/kibana/dashboard/system-Metrics-system-overview.json
packages/system/kibana/dashboard/system-bae11b00-9bfc-11ea-87e4-49f31ec44891.json
packages/system/kibana/dashboard/system-bb858830-f412-11e9-8405-516218e3d268.json
packages/system/kibana/dashboard/system-d401ef40-a7d5-11e9-a422-d144027429da.json
packages/system/manifest.yml

Add a global filter to the dashboard and remove the subfilters on the dataset and a global filter on the dataset is introduced. Filters on data_stream.dataset are applied with a phrase type filter on the dataset that is being used in that particular dashboard.
- Relates https://github.com/elastic/integrations/issues/9323
<details>
<summary>System Windows Security  User Logons </summary>
Before:
After:
</summary>
</details>
<details>
<summary>System Windows Security  Group Management Events </summary>
Before:
After:
</summary>
</details>
<details>
<summary>System Windows Security  Failed and Blocked Accounts </summary>
Before:
After:
</summary>
</details>
<details>
<summary>Metrics System  Overview </summary>
Before:
After:
</summary>
</details>
<details>
<summary>Metrics System  Host …

[System] Add global filter in dashboard for System

---

packages/kibana/_dev/build/docs/README.md
packages/kibana/changelog.yml
packages/kibana/docs/README.md
packages/kibana/manifest.yml

Remove unnecessary mention of `xpack.enabled` property in the docs

[kibana] fix docs

---

packages/ti_threatconnect/changelog.yml
packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_threatconnect/manifest.yml

ti_threatconnect: refactor cel code

---

packages/ti_threatconnect/changelog.yml

ti_threatconnect: fix changelog entry

---

packages/juniper_junos/changelog.yml
packages/juniper_junos/data_stream/log/fields/base-fields.yml
packages/juniper_junos/docs/README.md
packages/juniper_junos/manifest.yml

This PR fixes the following error for juniper_junos integration
```
one or more errors found in documents stored in logs-juniper_junos.log-ep data stream: [0] field "log.file.device_id" is undefined [1] field "log.file.inode" is undefined
```
N/A
- Relates https://github.com/elastic/integrations/issues/9582
N/A

[juniper_junos]: include log.file.device_id and log.file.inode in base-fields

---

packages/juniper_netscreen/changelog.yml
packages/juniper_netscreen/data_stream/log/fields/base-fields.yml
packages/juniper_netscreen/docs/README.md
packages/juniper_netscreen/manifest.yml

This PR fixes the following error for juniper_netscreen integration
```
one or more errors found in documents stored in logs-juniper_netscreen.log-ep data stream: [0] field "log.file.device_id" is undefined
[1] field "log.file.inode" is undefined
```
N/A
- Relates https://github.com/elastic/integrations/issues/9582
N/A

[juniper_netscreen]: include log.file.device_id and log.file.inode in base-fields

---

catalog-info.yaml

Update `filter_condition` field to allow just pull requests which source is "webhook"

[Buildkite] Update filter condition to allow just from webhook source

---

catalog-info.yaml

Update filter condition to use api source
Follows #9714

[Buildkite] Update filter to use api source

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/25d917c4-aa3c-4111-974c-286c0312ff95_4.json
packages/security_detection_engine/kibana/security_rule/28f6f34b-8e16-487a-b5fd-9d22eb903db8_1.json
packages/security_detection_engine/kibana/security_rule/6ee947e9-de7e-4281-a55d-09289bdf947e_7.json
packages/security_detection_engine/kibana/security_rule/dffbd37c-d4c5-46f8-9181-5afdd9172b4c_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.10.17-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6938b486c377295c8221c2b3697e3448d70f0c6b
None
None

[Security Rules] Update security rules package to v8.10.17-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/25d917c4-aa3c-4111-974c-286c0312ff95_4.json
packages/security_detection_engine/kibana/security_rule/28f6f34b-8e16-487a-b5fd-9d22eb903db8_1.json
packages/security_detection_engine/kibana/security_rule/6ee947e9-de7e-4281-a55d-09289bdf947e_7.json
packages/security_detection_engine/kibana/security_rule/dffbd37c-d4c5-46f8-9181-5afdd9172b4c_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.11.14-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/809279b62b359d14c29383f4032aa115494fc8ce
None
None

[Security Rules] Update security rules package to v8.11.14-beta.1

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/25d917c4-aa3c-4111-974c-286c0312ff95_4.json
packages/security_detection_engine/kibana/security_rule/28f6f34b-8e16-487a-b5fd-9d22eb903db8_1.json
packages/security_detection_engine/kibana/security_rule/6ee947e9-de7e-4281-a55d-09289bdf947e_7.json
packages/security_detection_engine/kibana/security_rule/dffbd37c-d4c5-46f8-9181-5afdd9172b4c_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.5-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3d7af55efe22b9ef786be69f266c43b676ba2d09
None
None

[Security Rules] Update security rules package to v8.13.5-beta.1

---

catalog-info.yaml

Update branches in catalog-info for publish pipeline

Update branches in catalog-info for publish pipeline

---

.buildkite/hooks/pre-command
.buildkite/pipeline.publish.yml
.buildkite/pipeline.schedule-daily.yml
.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml
.buildkite/pull-requests.json
.buildkite/scripts/common.sh
.buildkite/scripts/run_sonar_scanner.sh

Update Buildkite pipelines in backport branch (backport-security_detection_engine-8.12)

Update Buildkite pipelines in backport branch (backport-security_detection_engine-8.12)

---

.buildkite/hooks/pre-command
.buildkite/pipeline.publish.yml
.buildkite/pipeline.schedule-daily.yml
.buildkite/pipeline.serverless.yml
.buildkite/pull-requests.json
.buildkite/scripts/common.sh
.buildkite/scripts/find_oldest_supported_version.py
.buildkite/scripts/test_integrations_with_serverless.sh
.buildkite/scripts/test_one_package.sh
.buildkite/scripts/trigger_integrations_in_parallel.sh

Update Buildkite pipelines in backport branch (backport-security_detection_engine-8.10)

Update Buildkite pipelines in backport branch (backport-security_detection_engine-8.10)

---

.buildkite/hooks/pre-command
.buildkite/pipeline.publish.yml
.buildkite/pipeline.schedule-daily.yml
.buildkite/pipeline.serverless.yml
.buildkite/pull-requests.json
.buildkite/scripts/common.sh
.buildkite/scripts/find_oldest_supported_version.py
.buildkite/scripts/test_integrations_with_serverless.sh
.buildkite/scripts/test_one_package.sh
.buildkite/scripts/trigger_integrations_in_parallel.sh

Update Buildkite pipelines in backport branch (backport-cloud_security_posture-1.7)

Update Buildkite pipelines in backport branch (backport-cloud_security_posture-1.7)

---

.buildkite/hooks/pre-command
.buildkite/pipeline.publish.yml
.buildkite/pipeline.schedule-daily.yml
.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml
.buildkite/pull-requests.json
.buildkite/scripts/common.sh

Update Buildkite pipelines in backport branch (backport-cloud_security_posture-1.8)

Update Buildkite pipelines in backport branch (backport-cloud_security_posture-1.8)

---

packages/aws_bedrock/_dev/build/docs/README.md
packages/aws_bedrock/changelog.yml
packages/aws_bedrock/docs/README.md
packages/aws_bedrock/manifest.yml

aws_bedrock: fix markdown

---

packages/aws_logs/changelog.yml
packages/aws_logs/data_stream/generic/_dev/deploy/tf/files/test.log
packages/aws_logs/data_stream/generic/_dev/deploy/tf/main.tf
packages/aws_logs/data_stream/generic/_dev/test/system/test-default-config.yml
packages/aws_logs/data_stream/generic/sample_event.json
packages/aws_logs/manifest.yml

aws_logs: improve clarity and validity of system testing

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/0cd2f3e6-41da-40e6-b28b-466f688f00a6_1.json
packages/security_detection_engine/kibana/security_rule/17261da3-a6d0-463c-aac8-ea1718afcd20_1.json
packages/security_detection_engine/kibana/security_rule/4f855297-c8e0-4097-9d97-d653f7e471c4_1.json
packages/security_detection_engine/kibana/security_rule/5f0234fd-7f21-42af-8391-511d5fd11d5c_1.json
packages/security_detection_engine/kibana/security_rule/b1773d05-f349-45fb-9850-287b8f92f02d_1.json
packages/security_detection_engine/kibana/security_rule/f4c2515a-18bb-47ce-a768-1dc4e7b0fe6c_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.6-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/ae23547065f6a75437adf6007653af8218b257d3
None
None

[Security Rules] Update security rules package to v8.13.6-beta.1

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-common-config.yml
packages/crowdstrike/data_stream/falcon/fields/fields.yml
packages/crowdstrike/docs/README.md
packages/crowdstrike/manifest.yml

See title.
- Depends elastic/elastic-package#1752
- For #9237

crowdstrike: update manifest version format to v3.0.3

---

packages/amazon_security_lake/changelog.yml
packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-common-config.yml
packages/amazon_security_lake/manifest.yml

See title.
- Depends elastic/elastic-package#1746
- For #9237

amazon_security_lake: update manifest version format to v3.0.3

---

packages/cloudflare/changelog.yml
packages/cloudflare/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/cloudflare/data_stream/audit/manifest.yml
packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
packages/cloudflare/data_stream/logpull/manifest.yml
packages/cloudflare/manifest.yml

cloudflare: allow user configuration of results per page

---

packages/ping_one/_dev/build/docs/README.md
packages/ping_one/changelog.yml
packages/ping_one/data_stream/audit/manifest.yml
packages/ping_one/docs/README.md
packages/ping_one/manifest.yml

```
[ping_one] Update setup documentation (#)
- Update the Setup section of the README to match PingOne's updated UI
and workflows, and enhance clarity.
- Update the titles of the `url` and `token_url` variables for clarity
and to match PingOne terminology.
```
I used a PingOne test account to find and check the new setup steps.
For collection via API I did check that the data was ingested successfully.
For collection via HTTP endpoint I set up the PingOne side and verified that it sent new activity to an external endpoint, at [webhook.site](https://webhook.site/), but I didn't expose a port on my local machine or do the SSL setup that may be necessary for that.
- Closes #9191
Rendered markdown:

[ping_one] Update setup documentation

---

packages/universal_profiling_collector/changelog.yml
packages/universal_profiling_collector/manifest.yml

This reverts commit 188bf87ef05688097b6655d57b065cac103dd889.
- https://github.com/elastic/integrations/issues/9845

[Universal profiling collector] revert use of secrets variables

---

.buildkite/hooks/pre-command
.buildkite/hooks/pre-exit
.buildkite/scripts/backport_branch.sh

Update backport pipeline to use git credentials to solve this error:
https://buildkite.com/elastic/integrations-backport/builds/89#018f7881-d28c-4943-a0b6-675dc41bce18
This PR adds also the parameters introduced in the step key as an annotation. This will help to find which parameters were used in each build.

[Buildkite] Update git config backports

---

packages/f5_bigip/_dev/build/docs/README.md
packages/f5_bigip/changelog.yml
packages/f5_bigip/docs/README.md
packages/f5_bigip/manifest.yml

f5_bigip: clarify event types

---

.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml
.buildkite/scripts/trigger_integrations_in_parallel.sh

Update GCP image used for steps in charge of testing packages.
- Relates https://github.com/elastic/integrations/pull/9885
- Relates https://github.com/elastic/elastic-package/issues/787

[Buildkite] Update image used for integration steps

---

packages/aws_bedrock/changelog.yml
packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
packages/aws_bedrock/manifest.yml
packages/google_scc/changelog.yml
packages/google_scc/data_stream/asset/elasticsearch/ingest_pipeline/pipeline_asset.yml
packages/google_scc/data_stream/asset/elasticsearch/ingest_pipeline/pipeline_prior_asset.yml
packages/google_scc/data_stream/finding/elasticsearch/ingest_pipeline/default.yml
packages/google_scc/manifest.yml
packages/microsoft_defender_cloud/changelog.yml
packages/microsoft_defender_cloud/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_defender_cloud/manifest.yml
packages/ti_threatconnect/changelog.yml
packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
packages/ti_threatconnect/manifest.yml

aws_bedrock,google_scc,microsoft_defender_cloud,ti_threatconnect: fix renameKeys

---

packages/cel/agent/input/input.yml.hbs
packages/cel/changelog.yml
packages/cel/manifest.yml

See title.
Note: At this point, this is too late, but I think it may have been a better initial choice to just expose the `oauth` config tree as a YAML field.
- Closes #9915

cel: enable okta oauth2.0

---

packages/ti_threatq/changelog.yml
packages/ti_threatq/data_stream/threat/agent/stream/httpjson.yml.hbs
packages/ti_threatq/data_stream/threat/manifest.yml
packages/ti_threatq/manifest.yml

threatq: add user configurable page size

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Add `security` capability to avoid showing this package into Observability projects in Elastic Serverless.
Example of the error shown when this package is installed in a Observability project:
> Error: error running package asset tests: could not complete test run: can't install the package: there was an apply error: installation failed: can't install the package: could not zip-install package; API status code = 400; response body = {"statusCode":400,"error":"Bad Request","message":"Encountered 5224 errors creating saved objects: ...
- Relates https://github.com/elastic/integrations/pull/9849

Add security capabilities for security_detection_engine

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/admin/_dev/test/pipeline/test-admin.log
packages/cisco_duo/data_stream/admin/_dev/test/pipeline/test-admin.log-expected.json
packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
packages/cisco_duo/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
packages/cisco_duo/data_stream/offline_enrollment/elasticsearch/ingest_pipeline/default.yml
packages/cisco_duo/data_stream/summary/_dev/test/pipeline/test-summary.log-expected.json
packages/cisco_duo/data_stream/summary/elasticsearch/ingest_pipeline/default.yml
packages/cisco_duo/data_stream/telephony/elasticsearch/ingest_pipeline/default.yml
packages/cisco_duo/manifest.yml

cisco_duo: improve error handling

---

packages/http_endpoint/changelog.yml
packages/http_endpoint/manifest.yml

http_endpoint: clarify supported HMAC header format

---

packages/proofpoint_tap/changelog.yml
packages/proofpoint_tap/data_stream/clicks_blocked/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/data_stream/clicks_permitted/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/data_stream/message_blocked/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/data_stream/message_delivered/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/manifest.yml

Prevent dropped events due to an insufficiently unique deduplication key.  The document `_id` computation now uses a hash over the `event.original` value.
Fixes #9966
This is how the Elasticsearch fingerprint processor computes this fingerprint: https://go.dev/play/p/uq8laCk7vSO
<details>
<summary>Sample event</summary>
```json
{
"_index": ".ds-logs-proofpoint_tap.message_blocked-ep-2024.05.24-000001",
"_id": "QoIvybP88HgYG+goW7lZ5M2ljHM=",
"_version": 1,
"_score": 0,
"_source": {
"agent": {
"name": "docker-fleet-agent",
"id": "6b5ca4ac-55fe-4a46-a9db-ba6012bf1cb8",
"type": "filebeat",
"ephemeral_id": "fabd8547-b1ce-49e9-8973-7933ac5ae2ce",
"version": "8.13.4"
},
"elastic_agent": {
"id": "6b5ca4ac-55fe-4a46-a9db-ba6012bf1cb8",
"version": "8.13.4",
"snapshot": false
},
"proofpoint_tap": { …
```

[proofpoint_tap] Hash event.original for doc _id

---

packages/cel/agent/input/input.yml.hbs
packages/cel/changelog.yml
packages/cel/manifest.yml

cel: add support for digest authentication

---

.buildkite/scripts/common.sh
packages/elastic_package_registry/docs/README.md

Filter docs folder to avoid testing all packages if just are modified those files.

[Buildkite] Filter docs folder

---

packages/cloudflare_logpush/_dev/build/docs/README.md
packages/cloudflare_logpush/changelog.yml
packages/cloudflare_logpush/docs/README.md
packages/cloudflare_logpush/manifest.yml

It adds a section in the integration's docs to explain how to configure it to ingest logs from Cloudflare R2.
- Closes https://github.com/elastic/integrations/issues/8412

[Cloudflare Logpush] Improve documentation on how to ingest data from Cloudflare R2

---

packages/airflow/_dev/build/docs/README.md
packages/airflow/changelog.yml
packages/airflow/docs/README.md
packages/airflow/manifest.yml

- Enhancement
- Update README as per documentation_guidelines.
- Closes #9805
<details>
<summary>Airflow Integration Page</summary>
</details>

[O11y][Airflow] Update documentation

---

packages/azure_openai/changelog.yml
packages/azure_openai/kibana/dashboard/azure_openai-473cae7c-5b4e-4a31-855d-26524a36a454.json
packages/azure_openai/manifest.yml

1. Remove unnecessary filter:
2. Revert format_version to 3.1.3
-

[Azure] [OpenAI] Remove requests.total filter from metrics dashboard

---

packages/azure_openai/changelog.yml
packages/azure_openai/kibana/dashboard/azure_openai-21d9a0d0-e6a0-4b34-bc6d-ce6560a1dab3.json
packages/azure_openai/kibana/dashboard/azure_openai-473cae7c-5b4e-4a31-855d-26524a36a454.json
packages/azure_openai/kibana/dashboard/azure_openai-5b98323b-7e41-408d-8b82-9cc41d4ed747.json
packages/azure_openai/manifest.yml

Add overview dashboard for both logs and metrics using common Azure fields.
Add navigation panel to all dashboards.
Currently there the limitation that the user needs to create the custom data view for the dashboard to work:
The ID of the Data View has to be exactly: `713624b0-5d1c-4c3a-a3a8-4a8a76c1d3b1`.
I am working on adding an ad-hoc data view similar to the one in Elastic Agent Overview Dashboard before merging this.
- 
Overview:
Logs:
Metrics:

[Azure] [OpenAI] Add Overview Dashboard for both logs and metrics

---

packages/zeek/changelog.yml
packages/zeek/data_stream/ntp/elasticsearch/ingest_pipeline/default.yml
packages/zeek/manifest.yml

Added null check conditional to date processors to prevent pipeline failures when fields not present. Since this pipeline calls the custom Zeek NTP pipeline, failure at this stage means that the custom pipelines are never called.
-

[Zeek] Bug in NTP pipeline

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/system/test-default-config.yml
packages/qualys_vmdr/data_stream/asset_host_detection/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/asset_host_detection/manifest.yml
packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
packages/qualys_vmdr/data_stream/knowledge_base/_dev/test/system/test-0_valid-config.yml
packages/qualys_vmdr/data_stream/knowledge_base/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/knowledge_base/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/knowledge_base/manifest.yml
packages/qualys_vmdr/data_stream/knowledge_base/sample_event.json
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

Exposed under advanced settings since this is likely to only be valuable in debugging.
- Ref #9998 for debugging.

qualys_vmdr: allow original event preservation

---

packages/snyk/changelog.yml
packages/snyk/data_stream/audit_logs/agent/stream/cel.yml.hbs
packages/snyk/data_stream/audit_logs/manifest.yml
packages/snyk/manifest.yml

The set-up was using state.event to hold the events filter parameter
list. This values is removed by the CEL input eval loop after the first
iteration and the input does not replace it. Change the name to avoid
this collision.
-

snyk: fix handling of event filter parameter in audit_logs data stream

---

packages/okta/_dev/build/docs/README.md
packages/okta/_dev/deploy/docker/files/config_oauth2.yml
packages/okta/changelog.yml
packages/okta/data_stream/system/_dev/test/system/test-oin-config.yml
packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
packages/okta/docs/README.md
packages/okta/manifest.yml

See title.
Note that this will need to be merged before OIN authentication is available.
- For #9608
New use
Tested on a cloud instance

okta: add support for OIN service API authentication

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml

Fix Cloud Assets Inventory dataset

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log-expected.json
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dhcp.yml
packages/infoblox_nios/data_stream/log/fields/ecs.yml
packages/infoblox_nios/data_stream/log/fields/fields.yml
packages/infoblox_nios/docs/README.md
packages/infoblox_nios/manifest.yml

infoblox_nios: handle REFUSED log messages

---

packages/proofpoint_tap/changelog.yml
packages/proofpoint_tap/data_stream/clicks_blocked/manifest.yml
packages/proofpoint_tap/data_stream/clicks_permitted/manifest.yml
packages/proofpoint_tap/data_stream/message_blocked/manifest.yml
packages/proofpoint_tap/data_stream/message_delivered/manifest.yml
packages/proofpoint_tap/manifest.yml

proofpoint_tap: improve query interval documentation to avoid request throttling

---

packages/azure_openai/changelog.yml
packages/azure_openai/data_stream/metrics/fields/fields.yml
packages/azure_openai/docs/README.md
packages/azure_openai/manifest.yml

Reverts #9944.
Many metrics appear to be counters, especially since they have the `.total` suffix. 
However, by looking at the documents from Azure OpenAI, these values never increment as a counter but rather are document-specific values that can go up or down depending on the document. 
The gauge metric type is more appropriate. Other Azure integrations are also using the gauge metric type for the majority/all metrics.
-

[Azure] [OpenAI] Revert metric types to gauges

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/fields/asset.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/kibana/index_pattern/cloud_asset_inventory-2773feaf-50bb-43f8-9fa9-8f9a5f85e566.json
packages/cloud_asset_inventory/kibana/index_pattern/cloud_asset_inventory-b4949290-465a-44ac-829a-099642147567.json
packages/cloud_asset_inventory/kibana/index_pattern/cloud_asset_inventory-c9edb0f7-b901-44b0-8a64-1110053bc9cc.json
packages/cloud_asset_inventory/manifest.yml

- Add `dynamic_dataset: true` so the integration can publish to multiple indexes
- Add data views to ease exploration
- Update field mapping
- Related https://github.com/elastic/security-team/issues/9066

Update Index Configuration, Mapping and Data Views

---

packages/aws/changelog.yml
packages/aws/data_stream/firewall_logs/manifest.yml
packages/aws/manifest.yml

Update the title and description for the input config that collects AWS Network Firewall logs using the `cloudwatch`. The input config should refer to "Network Firewall logs" instead of "ELB logs".

[AWS] Fix AWS Network Firewall logs title and description

---

packages/ti_misp/changelog.yml
packages/ti_misp/data_stream/threat/agent/stream/httpjson.yml.hbs
packages/ti_misp/data_stream/threat/manifest.yml
packages/ti_misp/manifest.yml

ti_misp: allow user configuration of event limit in threat data stream

---

packages/microsoft_exchange_server/changelog.yml
packages/microsoft_exchange_server/data_stream/httpproxy/fields/ecs.yml
packages/microsoft_exchange_server/data_stream/imap4_pop3/fields/ecs.yml
packages/microsoft_exchange_server/data_stream/messagetracking/fields/ecs.yml
packages/microsoft_exchange_server/data_stream/smtp/fields/ecs.yml
packages/microsoft_exchange_server/manifest.yml

Adjust mapping to include related & error field to avoid mapping conflicts

Adjust mapping to include related & error field

---

packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/user_activity/agent/stream/cel.yml.hbs
packages/qualys_vmdr/manifest.yml

Also hoist the state.with call and clean up CEL syntax.
- Fixes #10184

qualys_vmdr: fix date format to match user activity api behaviour

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/_dev/test/pipeline/test-stringly-json-events.json
packages/o365/data_stream/audit/_dev/test/pipeline/test-stringly-json-events.json-expected.json
packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/o365/manifest.yml

In some cases, this field may be a string. This results in a mapping failure. So in cases where the field is a string, conditionally parse out the JSON.
- Fixes #10177

o365: improve handling of o365.audit.AdditionalInfo

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Fixes: https://github.com/elastic/kibana/issues/181217
Changed the field type on data_stream from type: text to type: password where secret: true

[Cloud Security] Update type text to password when isSecret is True

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
Increase request tracer log count to 10.
For large tenants, when CEL program makes a series of requests,
we have seen cases where the tracer logs wouldn't capture a full 
list of responses even during a single interval because of limitation 
on number of tracer logs. This leads to lack of visibility if certain 
requests return non-200 response, leading to data loss. Increasing 
the tracer logs count to 10 from 5.
```

o365: Increase CEL tracer log count

---

packages/winlog/changelog.yml

[winlog] Fix PR number for Change link

---

packages/auditd_manager/changelog.yml
packages/auditd_manager/data_stream/auditd/manifest.yml
packages/auditd_manager/manifest.yml

Added `multi: true` to `audit_rule_files`
This was accidentally missed, but the field is intended to be a list.
- Closes #10000

Added `multi: true` to `audit_rule_files`

---

packages/symantec_edr_cloud/changelog.yml
packages/symantec_edr_cloud/data_stream/incident/agent/stream/cel.yml.hbs
packages/symantec_edr_cloud/data_stream/incident/elasticsearch/ingest_pipeline/default.yml
packages/symantec_edr_cloud/manifest.yml

symantec_edr_cloud: improve http error handling

---

packages/entityanalytics_entra_id/_dev/build/build.yml
packages/entityanalytics_entra_id/changelog.yml
packages/entityanalytics_entra_id/data_stream/device/fields/beats.yml
packages/entityanalytics_entra_id/data_stream/entity/fields/beats.yml
packages/entityanalytics_entra_id/data_stream/user/fields/beats.yml
packages/entityanalytics_entra_id/docs/README.md
packages/entityanalytics_entra_id/manifest.yml

```
Migration performed with
go run github.com/andrewkroh/go-examples/ecs-update@014b35dfe4c9832b51e7c909a39a48257d6a005d \
-ecs-version=8.11.0 \
-ecs-git-ref=v8.11.0 \
-fields-yml-drop-ecs \
-kibana-version=^8.13.0 \
-drop-import-mappings \
-pr=1 \
-owner=elastic/security-service-integrations \
./packages/entityanalytics_entra_id
git restore packages/entityanalytics_entra_id/data_stream/{entity,user}/fields/ecs.yml
(cd packages/entityanalytics_entra_id; elastic-package build)
and manual changelog addition.
```
-

entityanalytics_entra_id: migrate to ecs@mappings

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/alert/_dev/test/pipeline/test-alert.log-expected.json
packages/crowdstrike/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-event-stream.log-expected.json
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-detection-summary.log-expected.json
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-mobile-detection-summary.log-expected.json
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-xdr-detection-summary.log-expected.json
packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/detection_summary.yml
packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/mobile_detection_summary.yml
packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/xdr_detection_summary.yml
packages/crowdstrike/manifest.yml

```
Derive threat.framework from prefix and custom tactics.
Crowdstrike adds custom tactics based on Falcon Detection framework.
The ID of tactics starts with prefix `CS`. In cases where this is 
missing, all the custom Crowdstrike tactics names are used to set 
`threat.framework` as `CrowdStrike Falcon Detections Framework`.
```
`elastic-package test pipeline --generate -v --data-streams=alert`
```
--- Test results for package: crowdstrike - START ---
╭─────────────┬─────────────┬───────────┬────────────────┬────────┬──────────────╮
│ PACKAGE     │ DATA STREAM │ TEST TYPE │ TEST NAME      │ RESULT │ TIME ELAPSED │
├─────────────┼─────────────┼───────────┼────────────────┼────────┼──────────────┤
│ crowdstrike │ alert       │ pipeline  │ test-alert.log │ PASS   │   3.428458ms │ …
```

crowdstrike: Modify threat.framework based on prefix and custom tactic names

---

packages/wiz/changelog.yml
packages/wiz/data_stream/audit/agent/stream/cel.yml.hbs
packages/wiz/data_stream/issue/agent/stream/cel.yml.hbs
packages/wiz/data_stream/vulnerability/agent/stream/cel.yml.hbs
packages/wiz/manifest.yml

wiz: handle missing fields in API responses

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/_dev/test/pipeline/test-asset-host-detection.log-expected.json
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/asset_host_detection/fields/fields.yml
packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/kibana/search/qualys_vmdr-4119cae0-100e-11ee-b28e-615808a979fd.json
packages/qualys_vmdr/manifest.yml

See title.
```
$ cat pats
qualys_vmdr\??\.asset_host_detection\??\.dns\??\.value
qualys_vmdr\??\.asset_host_detection\??\.cloud\??\.resource_id
qualys_vmdr\??\.asset_host_detection\??\.cloud\??\.service
qualys_vmdr\??\.asset_host_detection\??\.cloud\??\.provider\??\.name
qualys_vmdr\??\.asset_host_detection\??\.qg_host_id
qualys_vmdr\??\.asset_host_detection\??\.os\??\.cpe
qualys_vmdr\??\.asset_host_detection\??\.os\??\.value
qualys_vmdr\??\.asset_host_detection\??\.last\??\.pc_scanned_date
qualys_vmdr\??\.asset_host_detection\??\.last\??\.scan_datetime
qualys_vmdr\??\.asset_host_detection\??\.last\??\.vm\??\.auth\??\.scanned_date
qualys_vmdr\??\.asset_host_detection\??\.last\??\.vm\??\.scanned_date
qualys_vmdr\??\.asset_host_detection\??\.last\??\.vm\??\.auth\??\.scanned_duration …
```

qualys_vmdr: use field names matching Qualys names

---

.buildkite/pipeline.yml
sonar-project.properties

On elastic-package 0.100.0 we revamped coverage reports and coverage for more files is reported now. Update exclusion list accordingly.

Update exclusion list of sonarqube

---

packages/hadoop/_dev/deploy/docker/Dockerfile
packages/hadoop/_dev/deploy/docker/files/CentOS-Base.repo

- Fixes system tests for Hadoop package
- There we some updates in the CentOS 7 mirrors which are now changed to `http://vault.centos.org` and this change we need to do manually as the docker image of hadoop comes with older mirrors. Prior to this fix the tests were failing due to the yum repo not able to identify the expired mirrors.
```
#10 24.23 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/tcp_wrappers-libs-7.6-77.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.23 Trying other mirror.
#10 24.31 http://mirror.ash.fastserv.com/centos/7.6.1810/os/x86_64/Packages/fipscheck-1.4.1-6.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
#10 24.31 Trying other mirror.
#10 24.38 http://mirrors.advancedhosters.com/centos/7.6.1810/os/x86_64/Packages/fipscheck-lib- …
```

[O11y][Hadoop] Fix system tests

---

packages/elastic_agent/changelog.yml

Fix missing changelog link to PR

---

packages/cisco_aironet/changelog.yml
packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log
packages/cisco_aironet/data_stream/log/_dev/test/pipeline/test-aironet-messages.log-expected.json
packages/cisco_aironet/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_aironet/manifest.yml

This PR enables cisco_aironet integration to parse correctly dates that have more than one whitespace characters between the month and monthday
N/A
```elastic-package test pipeline -v```
- Closes https://github.com/elastic/integrations/issues/10423
N/A

[cisco_aironet] fix handling multiple whitespace characters between month and monthday

---

.buildkite/hooks/pre-command

Update Vault path used for AWS credentials.

[CI] Update vault path secret

---

.buildkite/scripts/common.sh
README.md
docs/ci_pipelines.md
packages/elastic_package_registry/docs/README.md

Added documentation about the different CI pipelines available in this repository.
- Closes #9262

[CI] Add ci pipeline docs

---

packages/kubernetes/changelog.yml
packages/kubernetes/kibana/dashboard/kubernetes-3912d9a0-bcb2-11ec-b64f-7dd6e8e82013.json
packages/kubernetes/manifest.yml

- Bug
WHAT: Fixing a typo in Title of the [Metrics Kubernetes] Volumes"

fixing title in volume dashboard

---

.github/ISSUE_TEMPLATE/integration_bug.yml

To improve the quality of bug reports, create a Github issue template.
Automation to keep the integration package names updated will be handled
separately. The initial list was generated using the command below. Having
the package name is important if we to automate labeling issues with
`Integration:<package_name>`.
```
for i in $(ls packages); do
title=$(yq .title packages/$i/manifest.yml)
pkg=$i
echo "- $title [$pkg]"
done
```
Closes #10284
- Closes #10284

Add integration bug issue template

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/audit_logs/agent/stream/stream.yml.hbs
packages/kubernetes/manifest.yml

* Fix missing processors block in kubernetes.audit_logs integration
* Update changelog.yml
- Bug
- WHAT: Fix missing processors block in kubernetes.audit_logs integration
- WHY: User cannot add new processors in the kubernetes.audit_logs data stream through Kibana anymore
-

Fix missing processors block in kubernetes.audit_logs integration (#10548)

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_asa/manifest.yml

This PR add support in `cisco_asa` integration for parsing IPv4 and IPv6 for messages with ids 721016 and 721018
N/A
`elastic-package test pipeline`
- Closes https://github.com/elastic/integrations/issues/10506
N/A

[cisco_asa]: support parsing IPv4 and IPv6 for ids 721016 and 721018

---

packages/fortinet_fortigate/changelog.yml
packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet-6-2.log-expected.json
packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet-7-4.log-expected.json
packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/login.yml
packages/fortinet_fortigate/manifest.yml

N/A 
`elastic-package test pipeline`
- Closes https://github.com/elastic/integrations/issues/10193
N/A

[fortinet_fortigate]: parse correctly alternative logs for Administrator logins

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs
packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Introduce condition support to Cloud Security Posture integrations
Closes https://github.com/elastic/cloudbeat/issues/2144
<details> <summary>Setting `condition` variable using API</summary>
</details>
<details> <summary>`condition` evaluated to `true`, CIS K8s KSPM stream present</summary>
</details>
<details> <summary>`condition` evaluated to `false`, CIS K8s KSPM stream absent</summary>
</details>

Add support for conditions in Cloud Security Posture

---

.buildkite/scripts/common.sh

buildkite: don't test packages for changes in issue and pr templates

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/data_stream/host/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/manifest.yml

crowdstrike: add fingerprint processors to alert and host data streams

---

.github/ISSUE_TEMPLATE/integration_bug.yml

Provide mandatory fields that allow the user to describe the discordance between what was expected and what was observed.
-

Enhance issue templates to include problem descriptions

---

packages/microsoft_exchange_online_message_trace/_dev/build/docs/README.md
packages/microsoft_exchange_online_message_trace/changelog.yml
packages/microsoft_exchange_online_message_trace/docs/README.md
packages/microsoft_exchange_online_message_trace/manifest.yml

microsoft_exchange_online_message_trace: clarify configuration documentation

---

.github/dependabot.yml
.github/workflows/bump-elastic-stack-version.yml
.github/workflows/updatecli.d/bump-latest-7x-version.yml
.github/workflows/updatecli.d/bump-latest-snapshot-version.yml
.github/workflows/updatecli.d/scm.yml

Add github action that uses updatecli to automate bump of stack snapshots used for testing.

Add github action to bump stack versions

---

packages/box_events/changelog.yml
packages/box_events/data_stream/events/_dev/test/pipeline/test-empty.log
packages/box_events/data_stream/events/_dev/test/pipeline/test-empty.log-expected.json
packages/box_events/data_stream/events/elasticsearch/ingest_pipeline/default.yml
packages/box_events/manifest.yml

box: fix handling of empty api responses

---

packages/mysql/changelog.yml

- Fixes PR link for the latest merged change of `replica_status` data stream

[O11y][MySQL] Update PR link for `replica_status` data stream

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bump up package version from 1.10.0-preview* to release 1.10.0
it closes https://github.com/elastic/security-team/issues/10136

[Cloud Security] Release version 1.10.0

---

.github/ISSUE_TEMPLATE/integration_bug.yml

Add a data stream name input field to bug template

---

packages/cisco_ftd/changelog.yml
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_ftd/manifest.yml

This PR allows `cisco_ftd` to parse correctly usernames with a space for log entries that wrap the username with angle brackets.
N/A
`elastic-package test pipeline`
- Closes https://github.com/elastic/integrations/issues/10505
N/A

[cisco_ftd]: support usernames with spaces for message ids 716002 and 722051

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/access_transparency/_dev/test/pipeline/test-access-transparency.log-expected.json
packages/google_workspace/data_stream/access_transparency/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/access_transparency/sample_event.json
packages/google_workspace/data_stream/admin/sample_event.json
packages/google_workspace/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/alert/sample_event.json
packages/google_workspace/data_stream/context_aware_access/_dev/test/pipeline/test-context-aware-access.log-expected.json
packages/google_workspace/data_stream/context_aware_access/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/context_aware_access/sample_event.json
packages/google_workspace/data_stream/device/_dev/test/pipeline/test-device.log-expected.json
packages/google_workspace/data_stream/device/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/device/sample_event.json
packages/google_workspace/data_stream/drive/sample_event.json
packages/google_workspace/data_stream/gcp/_dev/test/pipeline/test-gcp.log-expected.json
packages/google_workspace/data_stream/gcp/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/gcp/sample_event.json
packages/google_workspace/data_stream/group_enterprise/_dev/test/pipeline/test-group-enterprise.log-expected.json
packages/google_workspace/data_stream/group_enterprise/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/group_enterprise/sample_event.json
packages/google_workspace/data_stream/groups/sample_event.json
packages/google_workspace/data_stream/login/sample_event.json
packages/google_workspace/data_stream/rules/sample_event.json
packages/google_workspace/data_stream/saml/sample_event.json
packages/google_workspace/data_stream/token/_dev/test/pipeline/test-token.log-expected.json
packages/google_workspace/data_stream/token/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/token/sample_event.json
packages/google_workspace/data_stream/user_accounts/sample_event.json
packages/google_workspace/docs/README.md
packages/google_workspace/manifest.yml

Some of the data streams did not have geoip processors, so add them.
-

google_workspace: add geoip processors to data streams without

---

packages/auth0/_dev/build/docs/README.md
packages/auth0/_dev/deploy/docker/docker-compose.yml
packages/auth0/_dev/deploy/docker/files/config-logs.yml
packages/auth0/changelog.yml
packages/auth0/data_stream/logs/_dev/test/pipeline/test-pull-responses.json
packages/auth0/data_stream/logs/_dev/test/pipeline/test-pull-responses.json-expected.json
packages/auth0/data_stream/logs/_dev/test/system/test-auth0-cel-config.yml
packages/auth0/data_stream/logs/agent/stream/cel.yml.hbs
packages/auth0/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
packages/auth0/data_stream/logs/fields/fields.yml
packages/auth0/data_stream/logs/manifest.yml
packages/auth0/data_stream/logs/sample_event.json
packages/auth0/docs/README.md
packages/auth0/manifest.yml

auth0: add auth0 v2 api input

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.12.19.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/504f3bea7fc8a7fa8530680bca665535cf6fe178
None
None

[Security Rules] Update security rules package to v8.12.19

---

docs/ecs@mappings_migration_guide.md

Add history, usage, and recommendations for using the `ecs@mappings` component template in integrations.

[Docs] Add ecs@mappings migration guide for integration developers

---

packages/universal_profiling_agent/changelog.yml
packages/universal_profiling_agent/docs/README.md
packages/universal_profiling_agent/manifest.yml

- Minimum supported kernel version is 4.19
- With 8.10 Profiling did become GA - versions prior to 8.10 are not fully supported.
-

Profiling: Update requirements

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/event/_dev/test/pipeline/test-device.log-expected.json
packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
packages/m365_defender/manifest.yml

On `sslconnectioninspected` events, the `network.protocol` field was getting set to `dns`. Updated processor to properly set the protocol to `ssl`.
-

m365_defender network.transport bug

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/fields/related.yml
packages/cloud_security_posture/manifest.yml

Based on the decision made in https://github.com/elastic/security-team/issues/10152 we would like to implement the proposed `related.entity` field.
- Fixes https://github.com/elastic/security-team/issues/9800
- Counterpart of https://github.com/elastic/cloudbeat/pull/2397

Add `related.entity` field

---

packages/entityanalytics_okta/changelog.yml
packages/entityanalytics_okta/data_stream/user/_dev/test/pipeline/test-user.json
packages/entityanalytics_okta/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_okta/data_stream/user/fields/fields.yml
packages/entityanalytics_okta/docs/README.md
packages/entityanalytics_okta/manifest.yml

entityanalytics_okta: record whether a user's credentials include a recovery question

---

packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/knowledge_base/agent/stream/input.yml.hbs
packages/qualys_vmdr/manifest.yml

```
According to the Qualys documentation, the time format for query parameters
does not include sub-second resolution:
The date/time is specified in YYYY-MM-DD[THH:MM:SSZ] format (UTC/GMT).
https://cdn2.qualys.com/docs/qualys-api-vmpc-user-guide.pdf
```
-

qualys_vmdr: use correct time format for last_modified_after parameter

---

packages/trend_micro_vision_one/_dev/build/docs/README.md
packages/trend_micro_vision_one/changelog.yml
packages/trend_micro_vision_one/docs/README.md
packages/trend_micro_vision_one/manifest.yml

```
Update doc for setting up API Keys.
API Keys for TrendMicro Vision One can be created without a user 
tied to them. This PR updates README with this new approach.
```
Reference documentation: https://automation.trendmicro.com/xdr/Guides/First-steps-toward-using-the-APIs#Obtain-authentication-tokens

trend_micro_vision_one: Update doc for setting up API Keys.

---

packages/amazon_security_lake/_dev/build/docs/README.md
packages/amazon_security_lake/changelog.yml
packages/amazon_security_lake/docs/README.md
packages/amazon_security_lake/manifest.yml

amazon_security_lake: remove confusing documentation remnant

---

packages/checkpoint/changelog.yml
packages/checkpoint/kibana/dashboard/checkpoint-259c5770-bd5b-11ed-b58e-dda7b2de7340.json
packages/checkpoint/kibana/dashboard/checkpoint-71094a90-bd49-11ed-b58e-dda7b2de7340.json
packages/checkpoint/kibana/dashboard/checkpoint-840b87b0-bd68-11ed-bda5-b56d80cf13c4.json
packages/checkpoint/kibana/dashboard/checkpoint-e4daa100-bcb1-11ed-b8ec-2fbdd87e0d2f.json
packages/checkpoint/kibana/tag/checkpoint-security-solution-default.json
packages/checkpoint/manifest.yml
packages/checkpoint/validation.yml

- Migrated the log stream visualization to a saved search (embedded in dashboard)
- Re-exported dashboards at 8.10.1
- Raised minimum version to 8.10.1 to address SVR00005
```
cd packages/checkpoint
```
- Relates #10516
- Relates elastic/sdh-beats#4959

[checkpoint] Migrate log stream to saved search

---

packages/proofpoint_tap/changelog.yml
packages/proofpoint_tap/kibana/dashboard/proofpoint_tap-3ad578f0-b5a6-11ec-a9d0-e94ed15a14b9.json
packages/proofpoint_tap/kibana/dashboard/proofpoint_tap-770903b0-b5aa-11ec-a9d0-e94ed15a14b9.json
packages/proofpoint_tap/kibana/dashboard/proofpoint_tap-9899aae0-b5ad-11ec-a9d0-e94ed15a14b9.json
packages/proofpoint_tap/kibana/dashboard/proofpoint_tap-ee5bc100-b5c8-11ec-a9d0-e94ed15a14b9.json
packages/proofpoint_tap/kibana/search/proofpoint_tap-00dd5660-af9b-11ec-bf43-c372803d141d.json
packages/proofpoint_tap/kibana/search/proofpoint_tap-717803c0-b130-11ec-8e58-3fc548a48fe4.json
packages/proofpoint_tap/kibana/tag/proofpoint_tap-security-solution-default.json
packages/proofpoint_tap/manifest.yml

proofpoint_tap: set default search period to one day

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/agent/stream/httpjson.yml.hbs
packages/panw_cortex_xdr/manifest.yml

panw_cortex_xdr: use Cortex XDR SIEM ingestion time for cursor progression

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/alert/agent/stream/cel.yml.hbs
packages/crowdstrike/data_stream/alert/sample_event.json
packages/crowdstrike/data_stream/host/agent/stream/cel.yml.hbs
packages/crowdstrike/data_stream/host/sample_event.json
packages/crowdstrike/docs/README.md
packages/crowdstrike/manifest.yml

Simplify and clarify the logic around timestamp selection between stateful
cursor and pagination by separating them and making pagination timestamps not
persist over periodic evalutations. Also do not look back except when there
is no cursor timestamp.
---
I do not believe that this is a complete fix for #10693, but I think it will cover the vast majority of duplicates due to the removal of the look-back in the pagination cursor. I would like to have this merged prior to any further work suggested in the original issue since I suspect that the proposed change there may result in some data loss and so want to see whether this more conservative approach will be good enough.
- For #10693

crowdstrike: prevent api duplicate responses

---

packages/entityanalytics_okta/changelog.yml
packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml
packages/entityanalytics_okta/data_stream/user/agent/stream/entity-analytics.yml.hbs
packages/entityanalytics_okta/data_stream/user/manifest.yml
packages/entityanalytics_okta/manifest.yml

entityanalytics_okta: add support for request trace logging

---

packages/cisco_asa/changelog.yml

[cisco_asa] Fix changelog PR number
- Relates https://github.com/elastic/integrations/pull/10864#discussion_r1731113927

[cisco_asa] Fix changelog PR number

---

packages/gigamon/_dev/build/docs/README.md
packages/gigamon/changelog.yml
packages/gigamon/data_stream/ami/elasticsearch/ingest_pipeline/default.yml
packages/gigamon/docs/README.md
packages/gigamon/kibana/dashboard/gigamon-032aab7b-87b2-444c-8c86-956d092598fb.json
packages/gigamon/kibana/dashboard/gigamon-3523b534-7525-44a7-808f-6a9f3235a67d.json
packages/gigamon/kibana/dashboard/gigamon-46931a21-a33e-43af-aadf-da8d6446b9cc.json
packages/gigamon/kibana/dashboard/gigamon-4ae2cd9a-3eef-42c6-a02c-731ce74d94ac.json
packages/gigamon/kibana/dashboard/gigamon-62291e9e-8b75-4f23-9121-79959da99b3b.json
packages/gigamon/kibana/dashboard/gigamon-64ca15b3-8327-4940-8b35-0e75ab3a73c6.json
packages/gigamon/kibana/dashboard/gigamon-855a64dc-1a72-403f-932b-a5b848378f7e.json
packages/gigamon/kibana/dashboard/gigamon-8f772203-64e0-4d1b-bb0e-14fa57b4b754.json
packages/gigamon/kibana/dashboard/gigamon-d6cecabb-f026-4823-914d-b4d61fd61787.json
packages/gigamon/kibana/dashboard/gigamon-d866be49-47b2-4306-a2be-d5cb6b6ab9c8.json
packages/gigamon/kibana/dashboard/gigamon-e192a946-8287-450a-a8f0-e23de9f95dae.json
packages/gigamon/kibana/dashboard/gigamon-e733c64e-6ea9-4dd6-a8ca-3914274598f3.json
packages/gigamon/manifest.yml

Update package description and readme cleanup.
Current package refers to be ingesting data from `Filebeat`. 
Updated this to `Elastic Agent` inside the package description.
Other Cleanup:
- Fix comments positioning in ingest pipeline.
- Fix `README` indentation.
- Fix dashboards containing undefined index-pattern.
After `README` update, the properties are indented properly:

gigamon: Update package description and cleanup

---

packages/wiz/changelog.yml
packages/wiz/manifest.yml

In the https://github.com/elastic/integrations/pull/10790 I added the screenshot to the integration but didn't add it to the manifest file. Fixing it
see https://github.com/elastic/integrations/pull/10790
- follow up for https://github.com/elastic/integrations/pull/10790
- contributes to https://github.com/elastic/security-team/issues/9662

[Cloud Security] Add Cloud Configuration Finding dashboard screenshot reference to the manifest

---

packages/zeek/changelog.yml
packages/zeek/data_stream/known_certs/_dev/test/pipeline/test-known-certs.log
packages/zeek/data_stream/known_certs/_dev/test/pipeline/test-known-certs.log-expected.json
packages/zeek/data_stream/known_certs/elasticsearch/ingest_pipeline/default.yml
packages/zeek/manifest.yml

The `grok` processors that extract the Common Name from the subject and issuer fields in TLS certificates fails when the Common Name is not present. While not valid, this can still happen in a few cases like self signed certificates. To solve this I added a condition to the processor to check that `CN=` is present in the source field before executing the processor. 
-

Zeek known certs grok fix

---

packages/oracle/data_stream/memory/_dev/test/system/test-memory-config.yml
packages/oracle/data_stream/performance/_dev/test/system/test-performance-config.yml
packages/oracle/data_stream/sysmetric/_dev/test/system/test-sysmetric-config.yml
packages/oracle/data_stream/system_statistics/_dev/test/system/test-systemstatistics-config.yml
packages/oracle/data_stream/tablespace/_dev/test/system/test-tablespace-config.yml

Add support to run the system tests with the Elastic Agent wolfi images. Those images require to install the needed software with `apk`.

[oracle] Add support to run system tests with Elastic Agent images based on Wolfi

---

packages/entityanalytics_ad/changelog.yml
packages/entityanalytics_ad/data_stream/user/_dev/test/pipeline/test-user.json-expected.json
packages/entityanalytics_ad/data_stream/user/elasticsearch/ingest_pipeline/entity.yml
packages/entityanalytics_ad/manifest.yml

entityanalytics_ad: format SID and GUID in canonical formats

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/infoblox_nios/manifest.yml

infoblox_nios: fix handling of MARK log entries

---

packages/cloud_security_posture/changelog.yml

Adding 1.10.1 changelog entry to main.
Following the [backporting docs](https://www.elastic.co/guide/en/integrations-developer/current/developer-workflow-support-old-package.html) adding the changelog entry as a follow up for https://github.com/elastic/integrations/pull/11017 
- Relates https://github.com/elastic/kibana/issues/188802

[Cloud Security] add backported 1.10.1 version changelog entry to main

---

packages/cloud_security_posture/changelog.yml

follow up after https://github.com/elastic/integrations/pull/11017 , adding PR link to the changelog to the backport branch
- relates https://github.com/elastic/kibana/issues/188802

add PR link to 1.10.1 changelog

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/agent/stream/gcp.yml.hbs
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml

See title
- closes https://github.com/elastic/security-team/issues/10437

[Cloud Security][Assets Inventory] Add GCP policy template

---

.buildkite/pipeline.yml

To be merged after this repository uses at least upcoming elastic-package v0.104.0.

Enable creation of issues in LogsDB daily

---

.github/CODEOWNERS

Update code owner for Citrix ADC logs and metrics data streams.

[Citrix ADC] Update code-owner for logs and metrics data stream

---

packages/azure/changelog.yml
packages/azure/manifest.yml

This PR updates the changelog and manifest for #10984.

Update changelog and manifest for 10984

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/fdr/fields/fields.yml
packages/crowdstrike/docs/README.md
packages/crowdstrike/manifest.yml

crowdstrike: map command line fields as multi-fields with match_only_text

---

.buildkite/scripts/common.sh

Remove dependencies that are already defined in `go.mod` when calling `with_mage` in buildkite scripts.
-

[CI] Remove dependencies from with_mage

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml

Forgot to bump patch version and add changelog to previous PR
[Previous PR](https://github.com/elastic/integrations/pull/11167)

[Cloud Security][Asset Inventory] update manifest and changelog

---

packages/log/changelog.yml
packages/log/manifest.yml

See title
Build the integration
Use it in a policy
- Closes https://github.com/elastic/integrations/issues/11176

Update the Custom Logs integration to package spec V3.1.5

---

packages/azure_metrics/_dev/build/docs/database_account.md
packages/azure_metrics/changelog.yml
packages/azure_metrics/docs/database_account.md
packages/azure_metrics/manifest.yml

Add the list of databases and namespaces supported by the Azure Database Account integration.
Set the right expectations about the namespaces and supported databases. Without this list, users may expect this integration to support all database types available in Azure.

azure metrics: add list of supported databases and namespaces

---

packages/docker/changelog.yml
packages/docker/data_stream/container_logs/manifest.yml
packages/docker/data_stream/memory/fields/fields.yml
packages/docker/manifest.yml

Bump package-spec version to 3.2.2.
Reasons:
- Align with best practices and requirements in package-spec v3.
- Serverless requires a package-spec version of 3.0.x.
Notes: 
- As of today, to test the Docker integration on non-serverless stack version 9.0, you must build the package with a `conditions.kibana.version: >= 8.8.0`.
- Future elastic-package version https://github.com/elastic/elastic-package/pull/2116 will allow test the integration on stack version `9.0.0-SNAPSHOT` without changing `conditions.kibana.version`.
-

Docker: bump package-spec version to 3.2.2

---

packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/asset_host_detection/sample_event.json
packages/qualys_vmdr/data_stream/knowledge_base/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/knowledge_base/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/knowledge_base/sample_event.json
packages/qualys_vmdr/data_stream/user_activity/sample_event.json
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

In real use of the API, the XML document that is sent may be hundreds of megabytes resulting in inability to ingest the resulting event documents. Even with compression, the XML is on the order of tens of megabytes. So do not retain the full XML, but only the original generated JSON when preserve_original_event is enabled.
-

qualys_vmdr: retain event.original as json

---

packages/keycloak/changelog.yml
packages/keycloak/data_stream/log/agent/stream/filestream.yml.hbs
packages/keycloak/data_stream/log/manifest.yml
packages/keycloak/manifest.yml

Please label as Enhancement
This PR adds the concition field as configurable option to the Keycloak log datastream

Add condition field to Keycloak log datastream

---

packages/google_workspace/_dev/build/docs/README.md
packages/google_workspace/changelog.yml
packages/google_workspace/docs/README.md
packages/google_workspace/manifest.yml

Remove link to unpublished security-labs blog from README.
_NOTE:_ The link gives a 404. After checking with security-labs team, the blog remains a work-in-progress and is unpublished.

[google_workspace]: Remove link to unpublished security-labs blog from README.

---

packages/microsoft_dnsserver/changelog.yml
packages/microsoft_dnsserver/manifest.yml

Release microsoft_dnsserver as GA
- Relates #10985
- Relates #11214

GA microsoft_dnsserver integration

---

packages/salesforce/_dev/build/docs/README.md
packages/salesforce/changelog.yml
packages/salesforce/docs/README.md
packages/salesforce/manifest.yml

This PR fixes the doc structure to make it compliant with the [documentation guidelines ](https://www.elastic.co/guide/en/integrations-developer/current/documentation-guidelines.html)and suggests some edits.
Closes https://github.com/elastic/integration-docs/issues/519

[Salesforce] Editing for GA

---

packages/azure_frontdoor/changelog.yml
packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
packages/azure_frontdoor/data_stream/access/fields/fields.yml
packages/azure_frontdoor/data_stream/access/sample_event.json
packages/azure_frontdoor/data_stream/waf/fields/fields.yml
packages/azure_frontdoor/docs/README.md
packages/azure_frontdoor/manifest.yml

This PR fix wrong types for the following fields:
-  azure.frontdoor.access.time_to_first_byte
-  azure.frontdoor.access.time_taken
-  azure.frontdoor.access.time
-  azure.frontdoor.waf.time
Reason: wrong types blocks usage of numeric function to build visualizations e.g. percentile
- [ x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ x ] I have verified that all data streams collect metrics or logs.
- [ x ] I have added an entry to my package's `changelog.yml` file.
- [ x ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#w …

Frontdoor integration types fix

---

packages/hid_bravura_monitor/changelog.yml
packages/hid_bravura_monitor/data_stream/winlog/elasticsearch/ingest_pipeline/default.yml
packages/hid_bravura_monitor/manifest.yml
packages/microsoft_dhcp/changelog.yml
packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcp.yml
packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcpv6.yml
packages/microsoft_dhcp/manifest.yml
packages/microsoft_dnsserver/changelog.yml
packages/microsoft_dnsserver/data_stream/analytical/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_dnsserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_dnsserver/manifest.yml

```
swp_all: use triple-brace templating in complex templates
This is a second pass at replacing double brace template marks with triple brace
marks. It addresses more complex uses that the sed rewrite did not find by using
PCRE via perl.
[git-generate]
for f in $(
(
for p in $(
yq 'select(.owner.github == "elastic/sec-windows-platform")|.name' packages/**/manifest.yml \
| grep -v -- '---'
); do
rg -l -g '*.yml' "[^{]\{\{[^{][ .a-zA-Z0-9_]*[^}]}}[^}]" packages/$p
done
)|grep "elasticsearch/ingest_pipeline"|sort|uniq
); do
perl -pi -e 's/(?<!\{)(\{\{[^{][ .a-zA-Z0-9_]*[^}]}})(?!\})/{$1}/g' $f
done
for p in $(git diff --name-only HEAD~1|cut -d/ -f1,2|sort|uniq); do
(
cd $p
elastic-package test pipeline -g
elastic-package changelog add \
--description "Use triple-brace Mustache templating …
```

swp_all: use triple-brace templating in complex templates

---

packages/salesforce/changelog.yml
packages/salesforce/manifest.yml

Preparation for GA release.
Note: We have made the minimum stack version 8.16.0 as we have [fixed a bug](https://github.com/elastic/beats/pull/41015) when responses with non-200 status codes should be discarded and not processed as the response might not be as expected. This will help in correct debugging. Along with this change, we have added some logs that could be helpful in debugging. Currently, this will go as 1.0.0-next and only be released when the 8.16.0 stack is released to the public.
More info on `-next` tag is here: https://github.com/elastic/integrations/blob/927d060c0d1d394c1c05f84520891eee4d780d6c/docs/developer_workflow_design_build_test_integration.md#remember-to-bump-up-the-version
> We will bump the version in the manifest to 1.0.0 and remove `-next` suffix when 8.16.0 …

packages/salesforce: preparation for GA release

---

packages/squid/_dev/build/docs/README.md
packages/squid/changelog.yml
packages/squid/docs/README.md
packages/squid/manifest.yml

- Add section to documentation to note supported formats.
- Relates #11279

[squid] Add documentation on supported formats

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.19.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/13d3f198099002f907e8cafa1277efeec9031843
None
None

[Security Rules] Update security rules package to v8.13.19

---

packages/aws/changelog.yml

This PR is to add changelog entry into the main branch for：
https://github.com/elastic/integrations/pull/11281
https://github.com/elastic/integrations/pull/11369
https://github.com/elastic/integrations/pull/11368

Add changelog for backport versions into main

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

See title.
> [!NOTE]
> There is room for code simplification in this package. This is left for a future PR.
-

o365: format CEL code

---

packages/aws_bedrock/_dev/build/docs/README.md
packages/aws_bedrock/changelog.yml
packages/aws_bedrock/data_stream/invocation/fields/fields.yml
packages/aws_bedrock/docs/README.md
packages/aws_bedrock/kibana/dashboard/aws_bedrock-2a19b571-251b-487b-84b2-abd887efb8a4.json
packages/aws_bedrock/manifest.yml

- Bug
- Add a field description for the field `input.input_token_count`
- Fix documentation issues
- Fix dashboard panel visibility issues
- manual verification of dashboard and readme
- 
closes https://github.com/elastic/integrations/issues/11168

Fix AWS Bedrock documentation and dashboard issues

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.13.20.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cd593eab57473e0298737bb61ceec543d1d146c6
None
None

[Security Rules] Update security rules package to v8.13.20

---

packages/vsphere/changelog.yml
packages/vsphere/data_stream/host/sample_event.json
packages/vsphere/docs/README.md
packages/vsphere/manifest.yml

Update sample event of host datastream using 8.15.2-SNAPSHOT stack version.
IPs are just local that vcsim is running on.
-

[vSphere][host] Update sample event

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/docs/README.md
packages/cloud_asset_inventory/manifest.yml

Provides a new README for Cloud Asset Inventory package.
Fixes https://github.com/elastic/security-team/issues/10828

[Cloud Security][Asset Inventory] Update README

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/_dev/test/pipeline/test-findings-log.json
packages/cloud_security_posture/data_stream/findings/_dev/test/pipeline/test-findings-log.json-expected.json
packages/cloud_security_posture/data_stream/findings/elasticsearch/ingest_pipeline/default.yml
packages/cloud_security_posture/data_stream/vulnerabilities/_dev/test/pipeline/test-findings-log.json
packages/cloud_security_posture/data_stream/vulnerabilities/_dev/test/pipeline/test-findings-log.json-expected.json
packages/cloud_security_posture/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
packages/cloud_security_posture/manifest.yml

According to [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-name) it's recommended that host.name is lowercased. Adding lowercase processor for both misconfiguration and vulnerability ingest pipeline
run pipeline tests
```
elastic-package test pipeline --data-streams vulnerabilities && elastic-package test pipeline --data-streams findings
```
- fixes https://github.com/elastic/security-team/issues/10360

[Cloud Security] lowercase host.name for cloud_secrity_posture

---

packages/ti_misp/data_stream/threat_attributes/_dev/test/pipeline/test-misp-sample-ndjson.log-expected.json

Time has passed since this event was added and so it has decayed. It will remain decayed mod the ioc_expiration_duration being extended in the future, so this should no longer be flaky.
> [!NOTE]
> Changelog entry intentionally omitted.
- Fixes #11410

ti_misp: update decayed status to reflect the passage of time

---

packages/trend_micro_vision_one/changelog.yml
packages/trend_micro_vision_one/manifest.yml

trend_micro_vision_one: improve regional domain config documentation

---

packages/prometheus/_dev/build/docs/README.md
packages/prometheus/changelog.yml
packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
packages/prometheus/data_stream/collector/fields/fields.yml
packages/prometheus/data_stream/collector/manifest.yml
packages/prometheus/data_stream/remote_write/agent/stream/stream.yml.hbs
packages/prometheus/data_stream/remote_write/fields/fields.yml
packages/prometheus/data_stream/remote_write/manifest.yml
packages/prometheus/docs/README.md
packages/prometheus/manifest.yml

Add `metrics_count` to collector and remote_write datasets if `metrics_count: true`. This fields in calculating Prometheus metrics per Elasticsearch document.
Testing the collector with 8.16-SNAPSHOT is straightforward. You can use elastic-package directly to collect metrics from a Prometheus exporter running on the host. Simply use host.docker.internal from Prometheus collector and EA running EA/Fleet would be able to fetch the metrics from the exporter running on host.
For remote_write, the process differs. Since a standalone agent isn't an option with the unreleased 8.16-SNAPSHOT version. For Prometheus remote_write, it opens a port and listens on it inside the EA container. The Prometheus server running on the host is expected to remote_write the metrics to this opened port inside the …

packages/prometheus: Add `metrics_count` to collector and remote_write if `metrics_count: true`

---

packages/akamai/_dev/build/docs/README.md
packages/akamai/changelog.yml
packages/akamai/data_stream/siem/manifest.yml
packages/akamai/docs/README.md
packages/akamai/manifest.yml

akamai: remove stale experimental/beta warnings

---

packages/slack/changelog.yml
packages/slack/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
packages/slack/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/slack/data_stream/audit/fields/fields.yml
packages/slack/data_stream/audit/sample_event.json
packages/slack/docs/README.md
packages/slack/manifest.yml

slack: map details.url_private and actor.* fields, and improve pipeline efficiency

---

.github/CODEOWNERS
packages/synthetics/manifest.yml
packages/synthetics_dashboards/manifest.yml

it has been moved to ux-management team from ux infra !!

Update synthetics code ownership !!

---

.buildkite/pipeline.schedule-daily.yml

This image is not available yet, prepare a revert.

Revert "chore: [updatecli] Update 7.x snapshot to 7.17.26-SNAPSHOT (#11516)"

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/data_stream/asset_inventory/manifest.yml
packages/cloud_asset_inventory/manifest.yml

The PR:
- Adds support for organization-wide deployment in AWS and Azure
- Reworks deployment type selection to use a drop-down menu
- Adds descriptions to credential fields, highlighting which ones to fill
Fixes https://github.com/elastic/security-team/issues/10606
_Screenshot showing the new deployment type drop-down and credential field descriptions_

[Asset Inventory] Organization Support

---

packages/okta/changelog.yml
packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
packages/okta/data_stream/system/fields/fields.yml
packages/okta/docs/README.md
packages/okta/manifest.yml

ref: https://developer.okta.com/docs/api/openapi/okta-management/management/tag/SystemLog/#tag/SystemLog/operation/listLogEvents!c=200&path=target&t=response
- Closes #11049

okta: make okta.target use dynamic objects instead of flattened

---

packages/azure_billing/_dev/build/docs/README.md
packages/azure_billing/changelog.yml
packages/azure_billing/data_stream/billing/agent/stream/stream.yml.hbs
packages/azure_billing/docs/README.md
packages/azure_billing/manifest.yml

Add the `resource_manager_audience` config option in the "Advance options" section. 
The `resource_manager_audience` was already available in Metricbeat, but we never exposed it in the integration settings before today.
- n/a

[azure_billing] Add resource_manager_audience config option

---

packages/sublime_security/changelog.yml
packages/sublime_security/data_stream/audit/agent/stream/cel.yml.hbs
packages/sublime_security/manifest.yml

The API does not appear to offer any way to filter events by timestamp and while it offers an offset into a set of events, it does not document that this offset is valid over arbitrarily long periods, so this adds a timestamp to a cursor to keep an indication of events that have already been seen and so which can be dropped.
- Closes #11363

sublime_security: add high-water mark timestamp to prevent duplicate event ingestion

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Issue: https://github.com/elastic/integrations/issues/11542
This PR adds in logs for HPE Aruba CFM log types.
These were hand-crafted based on HPE's CFM log page: https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/ETH_OAM_CFM.htm
-

[Aruba] Add CFM log processing

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/11553
This PR adds DNS Client event and DPSE events handling.
Note DPSE events are hand-crafted from the example shown in https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/DPSE.htm
-

[ARUBA] Add support for DNS and DPSE events

---

packages/sublime_security/changelog.yml
packages/sublime_security/data_stream/audit/agent/stream/cel.yml.hbs
packages/sublime_security/manifest.yml

The current implementation never makes use of the water mark. So duplicates will continue to occur. Fix this.
- Ref #11623
- Fixes #11363

sublime_security: fix water mark use

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Adding dissect parsing for Aruba Container events
Also fixed a field in the CFM docs.
Fabricated the new logs from this page: https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/CONTAINER.htm
-

[hpe_aruba_cx] Add parsing for container event logs

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/11553
This PR adds ECMP types described in https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/ECMP.htm
-

[Aruba] Add ecmp type

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bump up package version from 1.11.0-preview* to release 1.11.0

[Cloud Security] Release version 1.11.0

---

packages/salesforce/changelog.yml
packages/salesforce/manifest.yml

Make Salesforce GA release. Followed [this](https://github.com/elastic/integrations/blob/927d060c0d1d394c1c05f84520891eee4d780d6c/docs/developer_workflow_design_build_test_integration.md#remember-to-bump-up-the-version).

packages/salesforce: GA Release

---

packages/endace/_dev/build/docs/README.md
packages/endace/changelog.yml
packages/endace/data_stream/flow/_dev/test/pipeline/test-flow-events.json
packages/endace/data_stream/flow/_dev/test/pipeline/test-flow-events.json-expected.json
packages/endace/data_stream/flow/agent/stream/flow.yml.hbs
packages/endace/data_stream/flow/elasticsearch/ingest_pipeline/endace.yml
packages/endace/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json
packages/endace/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
packages/endace/data_stream/log/agent/stream/netflow.yml.hbs
packages/endace/data_stream/log/elasticsearch/ingest_pipeline/endace-netflow.yml
packages/endace/data_stream/log/manifest.yml
packages/endace/docs/README.md
packages/endace/manifest.yml

- [x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x ] I have verified that all data streams collect metrics or logs.
- [ x] I have added an entry to my package's `changelog.yml` file.
- [ x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
Endace Integration was QAed and passed with 100% rate. 
Field event.reference is being created for Netflow traffic and local interface capture.
Pivot-to-vision was tested successfully. 
- 
[roberto@elk-partner-8 endace]$ elastic-package test pipeline …

Enhancement - Endace Integration v0.1.0

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Issue: https://github.com/elastic/integrations/issues/11542
This PR adds in logs for HPE Aruba CoPP log types.
The logs were hand-crafted based on HPE's page: https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/COPP.htm
-

[Aruba] Add parsing of CoPP events

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/alert/agent/stream/cel.yml.hbs
packages/crowdstrike/data_stream/alert/manifest.yml
packages/crowdstrike/data_stream/host/agent/stream/cel.yml.hbs
packages/crowdstrike/data_stream/host/manifest.yml
packages/crowdstrike/manifest.yml

FQL syntax is described at https://www.falconpy.io/Usage/Falcon-Query-Language.html.
- Closes #11628

crowdstrike: add support for FQL queries in alert and host data streams

---

packages/ti_crowdstrike/changelog.yml
packages/ti_crowdstrike/data_stream/ioc/fields/fields.yml
packages/ti_crowdstrike/docs/README.md
packages/ti_crowdstrike/elasticsearch/transform/latest_ioc/fields/fields.yml
packages/ti_crowdstrike/elasticsearch/transform/latest_ioc/transform.yml
packages/ti_crowdstrike/manifest.yml

The ingest pipeline handles both IP and hash IOCs, but the fields definitions state that the field is an ip type. This prevents users from being able to make use of this field for hash IOCs. So change the type to a keyword. This is a breaking change.
- Fixes #11688

ti_crowdstrike: fix mapping type for ioc.value field

---

packages/cyberarkpas/_dev/deploy/docker/docker-compose.yml

```
v0.17.1 of stream includes a fix for an issue with TCP and TLS closure[1].
[1] elastic/stream#123
```
- Closes #11557

cyberarkpas: bump stream version

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

This PR adds https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/EXTERNAL-STORAGE.htm
https://github.com/elastic/integrations/issues/11553
-

[Aruba] Add external drive event

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/docs/README.md

Issue: https://github.com/elastic/integrations/issues/11542
This PR adds in logs for HPE Aruba DHCP Relay log types.
Note: No further processing was needed for the two log types.
The logs were hand-crafted based on HPE's page: https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/DHCP-RELAY.htm
-

[Aruba] Add DHCP Relay events

---

packages/nginx_ingress_controller_otel/changelog.yml
packages/nginx_ingress_controller_otel/docs/README.md
packages/nginx_ingress_controller_otel/kibana/dashboard/nginx_ingress_controller_otel-05a72585-3900-4944-b648-2f15907872d1.json
packages/nginx_ingress_controller_otel/kibana/dashboard/nginx_ingress_controller_otel-30277d32-7af7-4a29-b5e2-a77e707d8471.json
packages/nginx_ingress_controller_otel/manifest.yml

Use `body.structured` namespace instead of `attributes` for dashboards.
In addition, some fields for the `nginx_ingress_controller.error` event has been mapped to the proposed semantic convetnion version: https://github.com/open-telemetry/semantic-conventions/pull/982 (without the `error` prefix)
-

[Nginx Otel] Fix body structured field in dashboards

---

packages/microsoft_exchange_server/changelog.yml
packages/microsoft_exchange_server/data_stream/messagetracking/fields/fields.yml
packages/microsoft_exchange_server/manifest.yml

Fix relatedrecipientaddress mapping
- Closes #11335

[microsoft_exchange_server] Fix relatedrecipientaddress mapping

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/ecs.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Adding fault monitor event handling based on https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/FAULT_MONITOR.htm
https://github.com/elastic/integrations/issues/11553

[Aruba] added Fault monitor event

---

packages/azure_app_service/changelog.yml
packages/azure_app_service/manifest.yml

Removes metrics reference from the manifest.yml file as the integration currently only supports logs.
-

[Azure] [App Service] Remove metrics reference from manifest

---

packages/aws_logs/changelog.yml
packages/aws_logs/data_stream/generic/agent/stream/aws-cloudwatch.yml.hbs
packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs
packages/aws_logs/data_stream/generic/manifest.yml
packages/aws_logs/manifest.yml

Reverts elastic/integrations#11681

Revert "[Custom AWS logs] Remove ingest pipeline option"

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/audit_events/_dev/test/pipeline/test-audit-events.log-expected.json
packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
packages/mimecast/data_stream/audit_events/fields/field.yml
packages/mimecast/docs/README.md
packages/mimecast/manifest.yml

This only fails on stack version v8.17, so fixing it required running on that stack.
Run the elastic-package tests on a v8.17.0-SNAPSHOT stack.
- Fixes #11722
- Fixes #11785
- Fixes #11842

mimecast: prevent contamination of time values with short timezone IDs

---

packages/zscaler_zia/changelog.yml
packages/zscaler_zia/data_stream/alerts/manifest.yml
packages/zscaler_zia/data_stream/audit/agent/stream/http_endpoint.yml.hbs
packages/zscaler_zia/data_stream/audit/manifest.yml
packages/zscaler_zia/data_stream/dns/agent/stream/http_endpoint.yml.hbs
packages/zscaler_zia/data_stream/dns/manifest.yml
packages/zscaler_zia/data_stream/endpoint_dlp/agent/stream/http_endpoint.yml.hbs
packages/zscaler_zia/data_stream/endpoint_dlp/manifest.yml
packages/zscaler_zia/data_stream/firewall/agent/stream/http_endpoint.yml.hbs
packages/zscaler_zia/data_stream/firewall/manifest.yml
packages/zscaler_zia/data_stream/sandbox_report/manifest.yml
packages/zscaler_zia/data_stream/tunnel/agent/stream/http_endpoint.yml.hbs
packages/zscaler_zia/data_stream/tunnel/manifest.yml
packages/zscaler_zia/data_stream/web/agent/stream/http_endpoint.yml.hbs
packages/zscaler_zia/data_stream/web/manifest.yml
packages/zscaler_zia/manifest.yml

Adding the ability to specify custom options for the HTTP endpoint input. That's very useful in some situations or for debugging

[Zscaler ZIA] Add custom input options to http input

---

packages/ti_custom/_dev/deploy/docker/files/config.yml
packages/ti_custom/changelog.yml
packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_custom/data_stream/indicator/manifest.yml
packages/ti_custom/manifest.yml

Changes in this PR contain:
- SSL and Proxy settings are added to the available options. This should help users that want to set client certificates and proxy URLs.
- Feed name and Feed reference are added to the available options when configuring the integration to connect to external APIs. Alerts are enriched with these values, and feed name is used in the Intelligence UI dashboard to populate the Trend visualisation.
- Some fixed to follow the TAXII 2.1 specification:
- TAXII servers can reply with `206 Partial content`: http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#_Toc496542717
- `added_after` is the right query parameter to filter data by timestamp: https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107539
- The correct form of the URL …

ti_custom: fixes for TAXII communication in Custom TI

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.17.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d4a9561b8ee26fddd06aa0d0809db2934c47fff1
None
None

[Security Rules] Update security rules package to v8.14.17

---

packages/prisma_cloud/changelog.yml
packages/prisma_cloud/data_stream/alert/agent/stream/input.yml.hbs
packages/prisma_cloud/data_stream/audit/agent/stream/input.yml.hbs
packages/prisma_cloud/data_stream/host/agent/stream/input.yml.hbs
packages/prisma_cloud/data_stream/host_profile/agent/stream/input.yml.hbs
packages/prisma_cloud/manifest.yml

```
This change fixes the login endpoint path for the host data sources, the
logging location for request trace logs, and prevents the authentication
token from leaking into debug logs.
```
-

prisma_cloud: fix trace log location, don't leak access token into debug logs and fix login endpoint path

---

packages/tines/changelog.yml
packages/tines/data_stream/audit_logs/_dev/test/pipeline/test-audit-logs.json
packages/tines/data_stream/audit_logs/_dev/test/pipeline/test-audit-logs.json-expected.json
packages/tines/data_stream/audit_logs/elasticsearch/ingest_pipeline/default.yml
packages/tines/data_stream/audit_logs/fields/fields.yml
packages/tines/docs/README.md
packages/tines/manifest.yml
packages/tines/validation.yml

tines: fix handling of multimorphic tines.audit_log.inputs.inputs.options fields

---

packages/servicenow/changelog.yml
packages/servicenow/data_stream/event/_dev/test/pipeline/test-event.log-expected.json
packages/servicenow/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/servicenow/data_stream/event/fields/fields.yml
packages/servicenow/data_stream/event/sample_event.json
packages/servicenow/docs/README.md
packages/servicenow/manifest.yml

This has value for being able to differentiate data sources in an index.
-

servicenow: retain the servicenow.event.table_name field

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/11552
This PR adds pipeline process for DHCPv4 Snooping events.
The logs were hand-crafted based on HPE's page: https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/DHCPv4-SNOOPING.htm
-

[Aruba] DHCPv4 snooping events

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/docs/README.md

Change Log:
Added docs pipeline tests for the MVRP event type (310x)
Test Case:
ran and passed pipeline tests
validated that fields are parsed properly

#11921-2 MVRP events (310x)

---

packages/symantec_edr_cloud/_dev/build/docs/README.md
packages/symantec_edr_cloud/changelog.yml
packages/symantec_edr_cloud/docs/README.md
packages/symantec_edr_cloud/manifest.yml

symantec_edr_cloud: deprecate package

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/docs/README.md

Issue: https://github.com/elastic/integrations/issues/11542
This PR adds in logs for HPE Aruba DHCPv6 Relay and Snooping Events.  The Relay events needed no extra processing.
The logs were hand-crafted based on HPE's page: 
* https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/DHCPv6-RELAY.htm
* https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-8214/Content/events/DHCPv6-SNOOPING.htm
-

[Aruba] Add DHCPv6 Relay and Snooping events

---

packages/microsoft_exchange_online_message_trace/changelog.yml
packages/microsoft_exchange_online_message_trace/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/microsoft_exchange_online_message_trace/manifest.yml

Replace event.outcome with microsoft.online_message_trace.Status from which it is derived and which can take more different values.
- Fixes #11911

microsoft_exchange_online_message_trace: improve document fingerprinting resolution

---

packages/nginx_ingress_controller_otel/changelog.yml
packages/nginx_ingress_controller_otel/kibana/dashboard/nginx_ingress_controller_otel-05a72585-3900-4944-b648-2f15907872d1.json
packages/nginx_ingress_controller_otel/manifest.yml

[nginx_ingress_controller_otel] fix range for successful HTTP response status code
The breakdown for HTTP response status code is incorrect for successful responses, range should be between [200, 299] instead of [300, 399]
-

fix: invalid range for successful HTTP response status code

---

packages/ti_mandiant_advantage/changelog.yml
packages/ti_mandiant_advantage/data_stream/threat_intelligence/agent/stream/httpjson.yml.hbs
packages/ti_mandiant_advantage/data_stream/threat_intelligence/manifest.yml
packages/ti_mandiant_advantage/manifest.yml

ti_mandiant_advantage: add support for proxy configuration

---

packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml

This removes the `-` values in the `aruba.sequence` field since they are not valid values.
-

[Aruba] Remove dash sequence values

---

packages/prisma_cloud/changelog.yml
packages/prisma_cloud/data_stream/host/agent/stream/input.yml.hbs
packages/prisma_cloud/data_stream/host/manifest.yml
packages/prisma_cloud/data_stream/host_profile/agent/stream/input.yml.hbs
packages/prisma_cloud/data_stream/host_profile/manifest.yml
packages/prisma_cloud/manifest.yml

Change was incorrect[1]. Also improve documentation in the config UI.
[1]https://pan.dev/prisma-cloud/api/cwpp/post-authenticate/
- Ref #11885

Revert: prisma_cloud: fix login endpoint path (#11885)

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Parent Issue:
https://github.com/elastic/integrations/issues/11921
Change Log:
Added NAE events and NAE Alerts
Added documentation, fabricated logs, pipeline tests and autogenerated read-me
Test:
Validated that message from 6001 - 6010 and 6801 are parsing the proper fields within the pipeline tests

#11921-3/4 NAE events (60xx) and NAE Agents events (690x)

---

packages/http_endpoint/_dev/test/system/test-http-cel-config.yml
packages/http_endpoint/agent/input/http.yml.hbs
packages/http_endpoint/changelog.yml
packages/http_endpoint/manifest.yml

http_endpoint: add program option to the configuration user interface

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Parent Ticket:
https://github.com/elastic/integrations/issues/11921
Change Log:
- ND snooping events (840x)
- NDM events (61xx)
- Added docs, pipeline-generated logs, and parsing logic
Test Cases:
validated expected both in generated and real logs fields are parsed properly based upon documentation

#11921-6/7 Added NDM and ND Snooping Events

---

.github/ISSUE_TEMPLATE/integration_feature_request.yml
.github/workflows/updatecli/updatecli.d/sync-packages-to-bug-issue-template.yml

Add a template to help support users making new feature requests for existing integrations.
-

issues: add feature request template

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/696015ef-718e-40ff-ac4a-cc2ba88dbeeb_5.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.18-beta.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/c0b531026a629d3d412b0938ef269b37cb931f31
None
None

[Security Rules] Update security rules package to v8.14.18-beta.2

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/696015ef-718e-40ff-ac4a-cc2ba88dbeeb_5.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.15.12-beta.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3169b1d8d7b7c44ebeece36f2c462ea1b76b99cc
None
None

[Security Rules] Update security rules package to v8.15.12-beta.2

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/28eb3afe-131d-48b0-a8fc-9784f3d54f3c_105.json
packages/security_detection_engine/kibana/security_rule/696015ef-718e-40ff-ac4a-cc2ba88dbeeb_5.json
packages/security_detection_engine/kibana/security_rule/ff9bc8b9-f03b-4283-be58-ee0a16f5a11b_107.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.16.3-beta.2.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/44aa52d03f0124be8d209188d82ab3e8661ebb96
None
None

[Security Rules] Update security rules package to v8.16.3-beta.2

---

.buildkite/pipeline.yml

Enable the creation of issues for flaky tests in the daily builds triggered using 9.0.0 as stack release.

[CI] [daily builds] Enable creation issues for daily builds with 9.0.0-SNAPSHOT

---

packages/google_workspace/_dev/deploy/docker/docker-compose.yml

Credential construction by the v3.21 alpine results in system test failures with the error:
`private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: structure error: tags don't match (16 vs {class:0 tag:13 length:45 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2`
Pin alpine to v3.20 until the root of the issue is identified and fixed.
-

google_workspace: pin the alpine image version to v3.20

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
packages/mimecast/manifest.yml

The source.ip field is never set, so this is redundant.
- Ref https://github.com/elastic/integrations/pull/12076#pullrequestreview-2499913947

mimecast: remove invalid remove processor

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/access_transparency/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log-expected.json
packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/context_aware_access/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/device/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/gcp/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/group_enterprise/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/rules/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/data_stream/token/elasticsearch/ingest_pipeline/default.yml
packages/google_workspace/manifest.yml

google_workspace: fix string literal syntax in painless scripts

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml
packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bump Cloud Security Posture and Asset Inventory versions for v8.17.0 release

[Cloud Security][CSPM][Asset Inventory] Update versions for 8.17 release

---

.github/workflows/updatecli/updatecli.d/sync-packages-to-bug-issue-template.yml

ci: enable updates to the feature request template

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12118
- Redundant Management events (220x)
- Replication Manager events (270x)
- RBAC events (1030x)
Added docs, fields, generated logs and parsing logic

#12118-5/6/7 RBAC, Redundant Management and Replication Manager events

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/docs/README.md

Change Log:
- Noticed that rendering of event fields were a problem due to `< >` (angle brackets)
- For all event id that have parsing logic updated the documentation

update documentation to align with markup schema

---

packages/azure_frontdoor/changelog.yml
packages/azure_frontdoor/manifest.yml

Just noticed, same as in https://github.com/elastic/integrations/pull/12112 also applies here

[Azure Frontdoor] change connection_string to secret

---

packages/jolokia_input/agent/input/input.yml.hbs
packages/jolokia_input/changelog.yml
packages/jolokia_input/manifest.yml

- Enhancement
Added HTTP Options [...]
The jolokia unsecured agent might be useful for a quick evaluation. It should not be used for production environments.
This PR enabled the use of a Jolokia secured agent by implementing the same HTTP options from the [Prometheus Integration](https://github.com/elastic/integrations/blob/main/packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs#L41)
[...]  and http_method parameter (default to GET).
The http_method parameter was hardcoded (as GET).
Here is the [doc ](https://jolokia.org/reference/html/manual/jolokia_protocol.html) suggesting the use of POST method for more complex ObjectNames.
Having a configurable option could add more capabilities for this integration as well.
1. Setup a Jolokia Agent (secured) endpoint
2. Install …

[Jolokia Input] Add HTTP Options

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/ecs.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12185
- SYS events (7xx)
- Supportability events (12xx)
- SYSMON events (63xx)
- TCAM events (102xx)
- Telnet server events (1290x)
Note: based off of OS 10.15 version

#12185-5/6/7/8/9 5 new event types for Aruba (SYS, SYSMON, Supportability, TCAM, TELNET Server)

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

https://github.com/elastic/integrations/issues/12192
Traffic Insight events (1400x)
TPM events (1360x)
Time management events (620x)
Temperature events (8xx)
Note: Against OS 10.15

#12192-1/2/3/4 4 new event types for Aruba (Traffic Insight, TPM, Time Management and Temperature)

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Parent Ticket:
https://github.com/elastic/integrations/issues/12192
- User management events (470x)
- User-based tunnels events (97xx)
added generated logs, throttle messages, parsing and docs
Note: Based upon OS 10.15

#12192 9/10 Added two additional event types (User management, User-based tunnels Events)

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

Parent Ticket:
https://github.com/elastic/integrations/issues/12192
Transceiver events (38xx)
UDLD events (410x)
UFD events (1200x)
added docs, pipeline logs and testing and parsing logic
Based upon OS 10.15

#12192-5/6/7/8 Added three new event types (Transceiver, UDLD and UFD)

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.19.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/6cd01806baeca326854d877ea206ddbdfbe27f06
None
None

[Security Rules] Update security rules package to v8.14.19

---

packages/aws/changelog.yml

Add changelog entry for backport version 2.30.3 
- https://github.com/elastic/integrations/pull/12237
- https://github.com/elastic/integrations/issues/11806

[aws] Add changelog entry for backport version 2.30.3 

---

packages/docker/_dev/build/docs/README.md
packages/docker/changelog.yml
packages/docker/docs/README.md
packages/docker/manifest.yml

- WHAT: Add note in docker integration docs about podman compatibility
- WHY:  It must be clear to users that podman support is available in stack version 8.16.2, 8.17.1 and above. Not in 8.17.0
- Relates https://github.com/elastic/beats/pull/41889

Update docker documentation with note about podman compatibility

---

packages/microsoft_exchange_online_message_trace/changelog.yml

- Bug
Updated a previous invalid PR number. No new version updates were made for this change.
- Relates https://github.com/elastic/integrations/pull/12239

[microsoft_exchange_online_message_trace] - Updated invalid PR number

---

packages/okta/changelog.yml
packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
packages/okta/manifest.yml

```
network is wrongly mapped to event.type when 
okta.event_type: "security.request.blocked". It also appends values 
multiple times.
Assign network to event.category. Also add allow_duplicates: false in 
all append processors to remove duplicate entries.
```
Don't have sample log/event for this event type to simulate test.
- Closes https://github.com/elastic/integrations/issues/12370

okta: Fix ECS event.category and event.type mappings

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated Fan Events (2xx)
- updated Hardware Health Monitor events (30xx), added event 3014-3024, 13801/2
- updated Firmware Update events (44xx), added events 4408-4411
- updated External Storage events (78xx)
- updated Fault Monitor Events (111xx)
- added Forwarding and Queuing for Time-Sensitive Streams (FQTSS) events (1390x)
- added Feature Pack events (144xx)

#12249-3 Updated and added new event types to 10.15 spec (Part 3)

---

.buildkite/pipeline.schedule-daily.yml
.buildkite/pipeline.yml
.buildkite/scripts/common.sh

Follows #12399 
<Actions>
<action id="5b52466a5e522f46d53d6c35cf475f8f4584a74e77212fb66e91a711c0f7bc6e">
<h3>Bump 7.x test version</h3>
<details id="434cce0f444679ad8dc96e925567966e9fb9820fd903d6c521eb5d875116d6b1">
<summary>[updatecli] Update 7.x snapshot to 7.17.28-SNAPSHOT</summary>
<p>1 file(s) updated with &#34;$1 7.17.28-SNAPSHOT&#34;:&#xA;&#x9;* .buildkite/pipeline.schedule-daily.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/integrations/actions/runs/12859209651">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p>
<details><summary>Options:</summary>
<br />
<p>Most of Updatecli configuration is done via <a …

Updatecli main bump elastic stack 7x version

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.14.20.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/0f9b714470ca9c908785564b38b301e71c0750b9
None
None

[Security Rules] Update security rules package to v8.14.20

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/ecs.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated Interface events (40x), tags and field consolidation added 409-410,14201-14203
- updated IRDP events (350x), tags, added 3503
- updated IPv6 Router Advertisement events (39xx), added 3920-3922
- updated HTTPS Server events (560x)
- updated In-System Programming events (72xx)
- updated IP-SLA events (740x) docs and tags
- updated Hardware switch controller sync events (88xx)
- updated Internal storage events (910x)
- updated IP tunnels events (96xx)
- updated IP source lockdown events (980x) docs and tags
- added new event type Job scheduler events (1220x && 1370x)
- added new event type Hot Patch events (132xx)
- updated Config validator events (1340x) tags
- added new event type ISSU events (135xx)
- added new event type …

#12249-4 OS 10.15 support part 4

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated LLDP events (1xx)
- updated LED events (50x)
- updated LACP events (13xx), added throttle message, and support for 1326-1328
- updated LAG events (14xx)
- updated Layer 3 Interface events (17xx), added events 1732, 15804-5
- updated Loop Protect events (280x), added events 2809-2811
- updated L3 Encap capacity events (1060x)
- updated L3 Resource Manager events (1150x), added message 11501-11506
- added new event Launch Daemon (LaunchD) events (1490x)

#12249-5 Update to OS 10.15 (part 5)

---

packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/event/_dev/test/pipeline/test-device.log-expected.json
packages/m365_defender/data_stream/event/elasticsearch/ingest_pipeline/pipeline_device.yml
packages/m365_defender/manifest.yml

Enrich IP addresses with ASN info.
-

M365defender ASN enrichment

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated MSDP events (86xx), added event 8610
- added new event Message Session Relay Protocol events (155xx)
- added new event Multicast HelperD events (159xx)

#12249-7 Update events to OS 10.15 (part 7)

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

The CEL input will do this, but it complains in the DEBUG logs, so add it in the integration to reduce log noise.
- Closes #12397

o365: ensure URL is included in returned state

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-cx.log-expected.json
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/ecs.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- added NTP events (110x)
- updated Multiple spanning tree protocol events (20xx)
- updated OSPFv2 events (24xx), added events 2409-2411
- updated MVRP events (310x), added throttled messages
- updated Multicast Traffic Manager events (400x), added 4002-4003
- updated OSPFv3 events (490x), added 4906-4908
- updated PIM events (51xx), added 5127-5133
- added NAE Scripts events (55xx)
- updated NAE events (60xx)
- updated NDM events (61xx)
- updated NAE Agents events (690x)
- updated ND snooping events (840x)
- updated Policies events (1010x)
- updated PORT_ACCESS events (1050x), added 10509-10537
- added NAE script generation events (1270x)
- added Packet capture events (152xx)

#12249- Part 8 of OS 10.15 updating

---

packages/hpe_aruba_cx/_dev/build/docs/README.md
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log
packages/hpe_aruba_cx/data_stream/log/_dev/test/pipeline/test-aruba-fabricated.log-expected.json
packages/hpe_aruba_cx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/hpe_aruba_cx/data_stream/log/fields/fields.yml
packages/hpe_aruba_cx/docs/README.md

- updated Power events (3xx), added 320-324
- updated Port events (60x), added 608-609
- updated Redundant Management events (220x)
- updated Replication Manager events (270x)
- updated Proxy ARP events (420x)
- updated Rapid per VLAN Spanning Tree Protocol events (500x), added event 5018
- updated Quality of Service events (570x), added event 5703-5704
- updated QoS ASIC Provider events (580x), added 5807
- updated Port Statistics events (660x)
- updated Power over Ethernet events (79xx), added 7941
- updated Port access roles events (930x), added event 9303
- updated Port security events (940x), added throttle message
- updated RBAC events (1030x)
- added new events PTP events (1210x)
- added new events Port access application-based …

#12249 Last change for OS 10.15 support

---

packages/ti_opencti/changelog.yml
packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_opencti/manifest.yml

```
[ti_opencti] Allow proxy configuration
```

[ti_opencti] Allow proxy configuration

---

packages/imperva_cloud_waf/data_stream/event/_dev/test/system/test-default-config.yml

Accidentally removed in #10374.
> [!NOTE]
> No changelog entry as this is not user-facing.
- Ref #10374

imperva_cloud_waf: re-add removed system test definition

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-audit.log-expected.json
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dhcp.log-expected.json
packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dhcp.yml
packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
packages/infoblox_nios/manifest.yml

Add `network.protocol` for dns and dhcp pipelines.
`cd packages/infoblox_nios && elastic-package build && elastic-package stack up --version=8.13.0 -d -v  && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v`
```
--- Test results for package: infoblox_nios - START ---
╭───────────────┬─────────────┬───────────┬───────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE       │ DATA STREAM │ TEST TYPE │ TEST NAME                                 │ RESULT │ TIME ELAPSED │
├───────────────┼─────────────┼───────────┼───────────────────────────────────────────┼────────┼──────────────┤
│ infoblox_nios │ log         │ pipeline  │ (ingest pipeline warnings test-audit.log) │ PASS   │ 338.475875ms │
│ infoblox_nios │ log         │ pipeline  │ …
```

infoblox_nios: Add network.protocol for dns and dhcp pipelines

---

.github/CODEOWNERS
packages/o365_metrics/data_stream/subscriptions/_dev/test/pipeline/test-common-config.yml
packages/o365_metrics/data_stream/subscriptions/_dev/test/pipeline/test-subscriptions.json
packages/o365_metrics/data_stream/subscriptions/_dev/test/pipeline/test-subscriptions.json-expected.json
packages/o365_metrics/data_stream/subscriptions/agent/stream/cel.yml.hbs
packages/o365_metrics/data_stream/subscriptions/elasticsearch/ingest_pipeline/default.yml
packages/o365_metrics/data_stream/subscriptions/fields/agent.yml
packages/o365_metrics/data_stream/subscriptions/fields/base-fields.yml
packages/o365_metrics/data_stream/subscriptions/fields/fields.yml
packages/o365_metrics/data_stream/subscriptions/manifest.yml
packages/o365_metrics/data_stream/subscriptions/sample_event.json

Add subscriptions data stream.
-

[MS365] [Subscriptions] Add Subscriptions data stream

---

.github/workflows/block-paths.yml

```
Add new temporary workflow to prevent changes to specific
integration files from being changed.
```

.github/workflows - new workflow

---

packages/sublime_security/changelog.yml
packages/sublime_security/data_stream/audit/manifest.yml
packages/sublime_security/data_stream/email_message/manifest.yml
packages/sublime_security/data_stream/message_event/manifest.yml
packages/sublime_security/manifest.yml

sublime_security: improve file selectors config documentation

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/manifest.yml

```
Improve error reporting for non-200 responses and also ensure that the
password is redacted.
```
> [!NOTE]
> The cel input is not tested due to limitations in elastic package (only one deployment).
-

imperva_cloud_waf: improve error reporting for API requests

---

packages/logstash/changelog.yml
packages/logstash/manifest.yml

Enhancement
Fixed documentation problem with versions to get the health report integration to get picked up

[Logstash] bump patch release to fix release publishing

---

packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/data_stream/event/agent/stream/cel.yml.hbs
packages/imperva_cloud_waf/manifest.yml

imperva_cloud_waf: fix syntax for error message construction

---

packages/openai/changelog.yml
packages/openai/manifest.yml

- Enhancement
OBS package for 9.0.0 enablement activities of O11y OpenAi integration.
1. update manifest.yml, package minor version upgrade and kibana dependency addition ` || ^9.0.0`.
2. build package
3. run package tests
4. install integration from kibana
5. check for any issues
Pass: Successfully Passed
Pending: Either permission issue or agent will stuck on 0 hits
Failed: Failed because of beats and integration changes are not in sync
Not Available: Tests are not available
No. | Packages | build & check | pipeline | system | asset | static
-- | -- | -- | -- | -- | -- | --
1 | OpenAi | Pass | Pass | Pass | Pass | Pass
- Relates https://github.com/elastic/obs-integration-team/issues/148

Enablement & Sanity test run for OpenAi OBS integration package for 9.0.0

---

packages/synthetics/changelog.yml
packages/synthetics/manifest.yml

Upgrade synthetic condition for v9.0.0 !!

[Synthetics] Upgrade synthetic condition for v9.0.0 !!

---

packages/checkpoint_harmony_endpoint/changelog.yml
packages/checkpoint_harmony_endpoint/data_stream/forensics/agent/stream/cel.yml.hbs
packages/checkpoint_harmony_endpoint/manifest.yml

Fix indentation in forensics CEL program caused by #12778

checkpoint_harmony_endpoint: Fix indentation in forensics CEL program

---

packages/aws/changelog.yml
packages/aws/data_stream/cloudtrail/fields/fields.yml
packages/aws/manifest.yml

aws: ignore long cloudtrail.{request_parameters,response_elements} fields

---

packages/auth0/changelog.yml
packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-failure.json-expected.json
packages/auth0/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
packages/auth0/data_stream/logs/sample_event.json
packages/auth0/docs/README.md
packages/auth0/manifest.yml

auth0: fix event.type and event.category for failed authentication events

---

.github/CODEOWNERS
packages/containerd/manifest.yml
packages/docker/manifest.yml
packages/istio/manifest.yml
packages/kubernetes/manifest.yml
packages/kubernetes_otel/manifest.yml
packages/nginx_ingress_controller/manifest.yml

Update the code owner file to adjust with the latest org changes.

update codeowners to fit with the new O11y ownership

---

packages/filestream/changelog.yml
packages/filestream/manifest.yml

See title
- Build the integration package
- Start a stack with `elastic-package` from the Filestream integration folder
- Open Kibana
- Click on "Add integrations"
- Search for "Filestream"
- Ensure it can be found *without* selecting "Display beta integrations"
- Ensure it does not have the "technical preview" badge.
~~## Related issues~~

Make the Filestream integration GA

---

packages/o365_metrics/changelog.yml
packages/o365_metrics/data_stream/onedrive_usage_storage/agent/stream/cel.yml.hbs
packages/o365_metrics/manifest.yml

Fix typo in cel code for OneDrive Usage Storage.
-

[O365] [OneDrive Usage Storage] Fix cel code

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Fix: https://github.com/elastic/security-team/issues/11925
CSPM remove azure.credentials.client_certificate_password from required_vars
-

CSPM remove azure.credentials.client_certificate_password from required_vars

---

packages/filestream/changelog.yml
packages/filestream/manifest.yml

Custom Filestream: fix version conflict

---

packages/prisma_access/changelog.yml
packages/prisma_access/data_stream/event/_dev/test/pipeline/test-event.json
packages/prisma_access/data_stream/event/_dev/test/pipeline/test-event.json-expected.json
packages/prisma_access/data_stream/event/elasticsearch/ingest_pipeline/default.yml
packages/prisma_access/manifest.yml

prisma_access: handle array PanOSDNSResponse values

---

packages/azure/changelog.yml
packages/azure/data_stream/events/manifest.yml
packages/azure/manifest.yml

Update the description for the custom storage account container name in the Azure Logs integration v2.
The existing description comes from the integration v1, and do not fit the nature of v2.

[azlogs] Fix the custom storage container description for the Azure Logs integration v2

---

packages/ess_billing/_dev/build/docs/README.md
packages/ess_billing/changelog.yml
packages/ess_billing/docs/README.md
packages/ess_billing/manifest.yml

Enables agentless deployment mode for the `ess_billing` integration.

Agentless deployment of `ess_billing` integration

---

packages/winlog/agent/input/winlog.yml.hbs
packages/winlog/changelog.yml
packages/winlog/manifest.yml

Add `xml_query` and `level` options
- Closes https://github.com/elastic/integrations/issues/9450

[winlog] Add xml_query and level options

---

packages/tenable_io/_dev/build/docs/README.md
packages/tenable_io/changelog.yml
packages/tenable_io/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
packages/tenable_io/data_stream/plugin/elasticsearch/ingest_pipeline/default.yml
packages/tenable_io/data_stream/scan/elasticsearch/ingest_pipeline/default.yml
packages/tenable_io/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
packages/tenable_io/docs/README.md
packages/tenable_io/manifest.yml
packages/tenable_io/validation.yml

Enable agentless data collection with tenable_io, and make some required ingest pipeline updates to work with the newer package spec version.

[tenable_io] Enable agentless collection

---

packages/microsoft_defender_endpoint/_dev/build/docs/README.md
packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/docs/README.md
packages/microsoft_defender_endpoint/manifest.yml

Parent Ticket:
https://github.com/elastic/integrations/issues/11810
- Updated the documentation based upon agreed upon language to highlight that the integration now supports Agentless deployment
- Upgraded the `format_version` to latest, 3.2.3
- Updated Kibana version constraints to ^8.18 || ^9.0.0

#11810 - Enabling Microsoft Defender for Endpoint with Agentless deployment

---

packages/system/changelog.yml
packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml
packages/system/manifest.yml
packages/windows/changelog.yml
packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security_standard.yml
packages/windows/manifest.yml

Fix boolean key in security pipelines

Fix boolean key in security pipelines

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/agent/stream/cel.yml.hbs
packages/panw_cortex_xdr/manifest.yml

```
Fix CEL error: unsupported type conversion from 'int' to string
``` 
Reproduced and tested the fix with live data. System tests didn't catch the issue.

panw_cortex_xdr: Fix CEL type conversion in alerts v2.

---

packages/panw/changelog.yml
packages/panw/manifest.yml

- Add support for stack version 9.0
- Relates #13039
- Relates elastic/detection-rules#4502

[panw] Support stack version 9.0

---

packages/admin_by_request_epm/changelog.yml
packages/admin_by_request_epm/manifest.yml
packages/beyondinsight_password_safe/changelog.yml
packages/beyondinsight_password_safe/manifest.yml
packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/manifest.yml
packages/panw_cortex_xdr/data_stream/incidents/manifest.yml
packages/panw_cortex_xdr/manifest.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/manifest.yml
packages/sailpoint_identity_sc/changelog.yml
packages/sailpoint_identity_sc/manifest.yml
packages/zscaler_zia/changelog.yml
packages/zscaler_zia/manifest.yml

Updates description field on ssl nodes in package level manifest.yml file to include links to online documentation and to be consistent with other integrations. This captures packages that were missed in an earlier PR
Originally, we updated the descriptions on all the files in integration. This created some issues with so many teams needing to validate the files. This is currently a partial update with files that are owned by security-service-integrations
git diff main | grep description: | grep + | sort -u
- Closes #12994
- Relates #12992, #11792

Update ssl option descriptions in manifest.yml files. Cleanup and missed packaged owned by Security Service Integrations

---

packages/citrix_adc/_dev/build/docs/README.md
packages/citrix_adc/changelog.yml
packages/citrix_adc/docs/README.md
packages/citrix_adc/manifest.yml

Previously, the documentation stated that both CEF and RFC5424 compliant syslog was the recommended format to ingest data, which could be confusing to users.
This rewrites the docs to make it more clear that CEF is the most preferred way to ingest data, but if syslog is used then RFC-5424 formatted is preferred.

[citrix_adc] Clarify preferred ingest method in documentation

---

packages/system/changelog.yml
packages/system/data_stream/security/manifest.yml
packages/system/manifest.yml
packages/windows/changelog.yml
packages/windows/data_stream/applocker_exe_and_dll/manifest.yml
packages/windows/data_stream/applocker_msi_and_script/manifest.yml
packages/windows/data_stream/applocker_packaged_app_deployment/manifest.yml
packages/windows/data_stream/applocker_packaged_app_execution/manifest.yml
packages/windows/data_stream/forwarded/manifest.yml
packages/windows/data_stream/powershell/manifest.yml
packages/windows/data_stream/powershell_operational/manifest.yml
packages/windows/data_stream/sysmon_operational/manifest.yml
packages/windows/data_stream/windows_defender/manifest.yml
packages/windows/manifest.yml

Remove dynamic template to avoid ECS overrides.

{system,windows} Remove dynamic template to avoid ECS overrides.

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Promote version `1.13.0` of `cloud_security_posture` integration
-

[Cloud Security] Promote `cloud_security_posture` 1.13.0

---

packages/o365_metrics/_dev/build/docs/README.md
packages/o365_metrics/changelog.yml
packages/o365_metrics/data_stream/sharepoint_site_usage_detail/_dev/test/pipeline/test-sharepoint-site-usage-detail.json-expected.json
packages/o365_metrics/data_stream/sharepoint_site_usage_detail/elasticsearch/ingest_pipeline/default.yml
packages/o365_metrics/data_stream/subscriptions/elasticsearch/ingest_pipeline/default.yml
packages/o365_metrics/docs/README.md
packages/o365_metrics/manifest.yml

Pipeline fix for documents being dropped in certain scenarios.
-

[O365 Metrics] Fix pipeline for better handling of field name in site_usage_details & subscriptions data stream

---

packages/filestream/changelog.yml
packages/filestream/data_stream/generic/agent/stream/filestream.yml.hbs
packages/filestream/data_stream/generic/manifest.yml
packages/filestream/manifest.yml

Enhancement
- WHAT: Adds condition support
- WHY: Allows for conditionally specifying when integration runs
- Closes #12853

feat: [filestream] add support for condition

---

packages/ti_custom/changelog.yml
packages/ti_custom/data_stream/indicator/_dev/test/system/test-taxii-basic-auth-config.yml
packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
packages/ti_custom/data_stream/indicator/manifest.yml
packages/ti_custom/manifest.yml

See title.
- Closes https://github.com/elastic/integrations/issues/12874

ti_custom: make Accept and Content-Type headers configurable

---

packages/ess_billing/changelog.yml
packages/ess_billing/manifest.yml

Added 9.0.0+ support for the ESS billing integration

9x compatibility

---

packages/kafka/changelog.yml
packages/kafka/data_stream/log/_dev/test/pipeline/test-authlog.log
packages/kafka/data_stream/log/_dev/test/pipeline/test-authlog.log-expected.json
packages/kafka/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/kafka/manifest.yml

Added a new grok pattern to Kafka integration to cover a case of parsing auth logs.
- Closes https://github.com/elastic/sdh-beats/issues/5732
-

add missing grok pattern for kafka logs

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/manifest.yml

Closes https://github.com/elastic/integrations/issues/13133 
-

Update Elastic agent constraint for 9.0.0

---

packages/imperva_cloud_waf/_dev/build/docs/README.md
packages/imperva_cloud_waf/changelog.yml
packages/imperva_cloud_waf/docs/README.md
packages/imperva_cloud_waf/manifest.yml

See title.
Apparently it is possible for people to interpret the original text as a conditional imperative rather than an imperative with an explanatory clause as is intended, resulting in incorrect configuration.
-

imperva_cloud_waf: clarify imperva file compression configuration

---

.github/CODEOWNERS
packages/universal_profiling_agent/changelog.yml
packages/universal_profiling_agent/manifest.yml

Reflect reorg and update responsibilities.

[chore] CODEOWNERS: update profiling to ingest-otel-data

---

packages/problemchild/changelog.yml
packages/problemchild/kibana/ml_module/problemchild-ml.json
packages/problemchild/manifest.yml

Changed the description of problemchild `high_sum` jobs.
- Changed the description of problemchild `high_sum` jobs to reflect that the job detects unusual host names, user names and parent process names with set of suspicious child processes.
- Updated changelog.yml and manifest.yml
-

[problemchild] Update description of `high_sum` ML jobs

---

packages/github/_dev/deploy/docker/files/config.yml
packages/github/changelog.yml
packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/github/manifest.yml

```
The URL path is changed from "/enterprise/"
to "/enterprises/" with a final "s".
Ref:
- https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/billing?apiVersion=2022-11-28
```

github.audit: Fix URL for enterprises.

---

packages/o365_metrics/_dev/deploy/docker/docker-compose.yml
packages/o365_metrics/_dev/deploy/docker/files/config.yml
packages/o365_metrics/data_stream/teams_call_quality/_dev/test/system/test-default-config.yml

add simple system test to o365_metrics teams_call_quality datastream
this doesn't test pagination - it's just a starting point for adding more comprehensive system tests.

add simple system test to o365_metrics teams_call_quality datastream

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_asa/manifest.yml

This handles another variation of Cisco ASA message type 315011, which includes a message about terminating an SSH connection normally.
-

[cisco_asa] Handle another variation of message 315011

---

packages/qualys_vmdr/_dev/build/docs/README.md
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/data_stream/knowledge_base/elasticsearch/ingest_pipeline/default.yml
packages/qualys_vmdr/docs/README.md
packages/qualys_vmdr/manifest.yml

Enable agentless integration for Qualys_VMDR, and make some required updates to ingest pipelines to work with the updated package spec.
1. Using 8.18 ECH on Staging
2. Setup the integration using:
username: `<username>`
password: `<password>`
Asset Host Detection data url: `https://qualysguard.qg2.apps.qualys.com/`
Knowledge Base data url: `https://qualysguard.qg2.apps.qualys.com/`
User Activity Log url: `https://qualysguard.qg2.apps.qualys.com/`
4. Validate that data flowed for the 3 datastreams
5. Validated that the hidden indexes for agentless were created (3) for the different data streams and are populated with …

#11810 Enabled agentless deployment for Qualys_VMDR

---

packages/azure_network_watcher_vnet/_dev/build/docs/README.md
packages/azure_network_watcher_vnet/changelog.yml
packages/azure_network_watcher_vnet/docs/README.md
packages/azure_network_watcher_vnet/manifest.yml

azure_network_watcher_vnet: Document the limitation around tuples.

---

packages/kubernetes_otel/docs/README.md

+ Docs change to update the broken onboarding guide.

docs: fix k8s otel setup link

---

packages/ti_abusech/_dev/build/docs/README.md
packages/ti_abusech/changelog.yml
packages/ti_abusech/docs/README.md

- Docs
Added changelog entry and doc updates to retain context of back-port PR_#13317.
This update is in line with the back-port PR suggestions outlined in [this document](https://www.elastic.co/guide/en/integrations-developer/current/developer-workflow-support-old-package.html).
- Relates https://github.com/elastic/integrations/pull/13317

[Ti_AbuseCH] - Added changelog entry and doc updates to retain context of back-port PR_#13317

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
packages/crowdstrike/data_stream/fdr/manifest.yml
packages/crowdstrike/manifest.yml

Backport of https://github.com/elastic/integrations/pull/13196 for fixing in stack versions `8.16` and `8.17`. 
Exposes missing `number_of_workers` setting for the user.
- Relates https://github.com/elastic/integrations/issues/13193

crowdstrike.fdr: Backport 1.56.1 - Expose missing setting for the user

---

packages/crowdstrike/changelog.yml

```
Updates changelog in main from backport fix #13296.
This is inline with the guidelines for backporting[1].
Ref:
- [1] https://www.elastic.co/guide/en/integrations-developer/current/developer-workflow-support-old-package.html
```
- Relates https://github.com/elastic/integrations/pull/13296

crowdstrike.fdr: Add backport's changelog entry into main

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/archive_search_logs/agent/stream/httpjson.yml.hbs
packages/mimecast/data_stream/archive_search_logs/sample_event.json
packages/mimecast/data_stream/audit_events/agent/stream/httpjson.yml.hbs
packages/mimecast/data_stream/audit_events/sample_event.json
packages/mimecast/data_stream/cloud_integrated_logs/sample_event.json
packages/mimecast/data_stream/dlp_logs/agent/stream/httpjson.yml.hbs
packages/mimecast/data_stream/dlp_logs/sample_event.json
packages/mimecast/data_stream/message_release_logs/sample_event.json
packages/mimecast/data_stream/siem_logs/sample_event.json
packages/mimecast/data_stream/threat_intel_malware_customer/sample_event.json
packages/mimecast/data_stream/threat_intel_malware_grid/sample_event.json
packages/mimecast/data_stream/ttp_ap_logs/agent/stream/httpjson.yml.hbs
packages/mimecast/data_stream/ttp_ap_logs/sample_event.json
packages/mimecast/data_stream/ttp_ip_logs/agent/stream/httpjson.yml.hbs
packages/mimecast/data_stream/ttp_ip_logs/sample_event.json
packages/mimecast/data_stream/ttp_url_logs/agent/stream/httpjson.yml.hbs
packages/mimecast/data_stream/ttp_url_logs/sample_event.json
packages/mimecast/docs/README.md
packages/mimecast/manifest.yml

Fix the configuration issues in the required data streams of Mimecast integration.
This change improves response status validation by checking the `fail` array in the response body to detect errors in data. The fix has been applied to `archive_search_logs`, `audit_events`, `dlp_logs`, `ttp_ap_logs`,  `ttp_ip_logs`, and `ttp_url_logs`. More details about the `fail` array can be found under the **response body** section in the [Mimecast API documentation](https://integrations.mimecast.com/documentation/api-overview/api-concepts/). 
Pagination handling has been improved by implementing proper end-of-pagination logic for `audit_events`, `archive_search_logs`, `dlp_logs`, `ttp_ap_logs`, `ttp_ip_logs`, and `ttp_url_logs`. The use of `do_not_log_failure` helps prevent excessive logging of …

[Mimecast] Fix the configuration issue

---

packages/kafka/_dev/build/docs/README.md
packages/kafka/changelog.yml
packages/kafka/docs/README.md
packages/kafka/manifest.yml

Updated supported kafka versions in README.
-

chore: update list of supported kafka versions in README

---

packages/vsphere/_dev/build/docs/README.md
packages/vsphere/changelog.yml
packages/vsphere/docs/README.md
packages/vsphere/manifest.yml

update vSphere supported versions in documentation

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

- Enhancement
Bump cloud security posture pre-release 1.14.0-preview01.
-

[CSPM] bump cspm prerelease 1.14.0-preview01

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Revert using the branch 8.19 in pre-release since its not yet created.
-

cspm: fix nightly for pre-release

---

packages/unifiedlogs/changelog.yml
packages/unifiedlogs/manifest.yml

[unifiedlogs] Downgrade package spec version

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/739e7658a8d449952f05293b8920dec12966cbbc
None
None

[Security Rules] Update security rules package to v9.0.1

---

packages/panw/changelog.yml
packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/traffic.yml
packages/panw/manifest.yml

The logic within the traffic pipeline was being based off `_temp_external/internal_zones` fields, but these fields were never actually populated. The values were being saved to `_conf` only instead.
This copies the values into `_temp_` fields before they are used, correcting this logic.

[panw] Fix network traffic direction logic

---

packages/windows/changelog.yml
packages/windows/kibana/dashboard/windows-c77e06c0-9e7c-11ea-af6f-cfdb1ee1d6c8.json
packages/windows/manifest.yml

Fix Powershell dashboard incorrect filters

[windows] Fix PS dashboard filters

---

packages/splunk/changelog.yml
packages/splunk/manifest.yml

Adding the `siem` category to the splunk integration per https://github.com/elastic/security-team/issues/12103
Relates https://github.com/elastic/security-team/issues/12103

[splunk] adding `siem` category to splunk

---

packages/google_secops/changelog.yml
packages/google_secops/manifest.yml
packages/microsoft_sentinel/changelog.yml
packages/microsoft_sentinel/manifest.yml

Release `microsoft_sentinel` and `google_secops` packages as GA.
- Relates https://github.com/elastic/integrations/issues/13249

microsoft_sentinel, google_secops: Make packages GA

---

docs/extend/dashboard-guidelines.md
docs/extend/developer-workflow-support-old-package.md
docs/extend/quick-start.md

Fixes image paths to work with docs-assembler.

[docs] Fix image paths for docs-assembler

---

packages/system/changelog.yml
packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml
packages/system/manifest.yml
packages/windows/changelog.yml
packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security_standard.yml
packages/windows/kibana/dashboard/windows-c77e06c0-9e7c-11ea-af6f-cfdb1ee1d6c8.json
packages/windows/manifest.yml

Make security pipeline robust against wrong type fields
Fix powershell dashboard

[system,windows] Fix security pipeline and powershell dashboard

---

packages/websocket/agent/input/websocket.yml.hbs
packages/websocket/changelog.yml
packages/websocket/manifest.yml

- Enhancement
Added support for retry configuration options some of which were were introduced in this [PR](https://github.com/elastic/beats/pull/42225). Since these changes are only available in 8.16.3 & 8.17.1 and above the version bumps have been made accordingly.
```
Added support for retry configuration. Since some of these changes are
only available in 8.16.3 & 8.17.1 and above the version bumps have been
made accordingly.
```
- Relates https://github.com/elastic/beats/pull/42225

[integrations][websocket] - Added support for retry configuration options

---

packages/filestream/_dev/build/docs/README.md
packages/filestream/changelog.yml
packages/filestream/docs/README.md
packages/filestream/manifest.yml
packages/log/changelog.yml
packages/log/docs/README.md
packages/log/manifest.yml

See title
Build the `filestream` and `log` packages, look at their docs/readme
~~## Related issues~~
TODO

Add warning about migrating from log to filestream

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.2
Generated from commit  https://github.com/elastic/detection-rules/tree/517f9420c1850bceb5f2c67695a34cf4d9de737c
None
None

[Security Rules] Update security rules package to v9.0.2

---

packages/ti_abusech/changelog.yml
packages/ti_abusech/data_stream/malware/agent/stream/cel.yml.hbs
packages/ti_abusech/data_stream/malwarebazaar/agent/stream/cel.yml.hbs
packages/ti_abusech/data_stream/threatfox/agent/stream/cel.yml.hbs
packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
packages/ti_abusech/manifest.yml

```
ti_abusech: Report API errors inside CEL programs.
Currently some of the CEL programs inside ti_abusech don't check if 
API returns success. There are also certain checks missing on empty
data. These lead to CEL execution errors. 
Add checks where necessary and report errors inside all data-streams.
Also update remove the conversion of bytes for resp.Body as it is 
no longer required after 8.16.
```

ti_abusech: Handle API errors inside CEL

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/976204f40a757a3450d6310624144f59f44c2f8d
None
None

[Security Rules] Update security rules package to v9.0.3

---

packages/azure_frontdoor/_dev/build/docs/README.md
packages/azure_frontdoor/changelog.yml
packages/azure_frontdoor/docs/README.md
packages/azure_frontdoor/manifest.yml

```
azure_frontdoor: update README to specify supported Azure Frontdoor log types.
This change updates the README to explain that the integration retrieves Access Logs (FrontDoorAccessLog) 
and Web Application Firewall Logs (FrontDoorWebApplicationFirewallLog), and clarifies that 
Activity Logs and Health Probe logs are not currently supported.
```
Move to integrations/packages/azure_frontdoor directory.
- Relates #7017

[azure_frontdoor] Clarify supported log types in README

---

packages/opencanary/data_stream/events/_dev/test/pipeline/test-common-config.yml
packages/opencanary/data_stream/events/_dev/test/pipeline/test-events.log-expected.json

```
opencanary: do not test redact-enabled pipeline
This is a temporary work-around until elastic/elastic-package#2543 is
implemented.
```
> [!NOTE]
> This is not user-facing, so no changelog entry is added.
- For #13503
- For #13505
- Ref elastic/elastic-package#2543

opencanary: do not test redact-enabled pipeline

---

catalog-info.yaml

Grant access to the obs11 CI team.
-

catalog-info: grant manage access to the CI robots team

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

o365: improve clarity of CEL code

---

packages/beyondinsight_password_safe/changelog.yml
packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/managedaccount/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/managedsystem/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/session/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
packages/beyondinsight_password_safe/manifest.yml

```
beyondinsight_password_safe: improve error reporting for API request failures
Return a meaningful error when the initial POST request fails instead of just
giving a CEL key indexing failure.
```
Exercise the error handling by breaking the deploy config file so that there is no POST rule to fire and then look at logs, or wait for elastic-package to timeout and print the errors.
- Fixes #13794

beyondinsight_password_safe: improve error reporting for API request failures

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/88b8d8c6c931eb1d1d60b25d4b6454d02653d0f2
None
None

[Security Rules] Update security rules package to v9.0.4

---

packages/azure/_dev/build/docs/events.md
packages/azure/changelog.yml
packages/azure/docs/events.md
packages/azure/manifest.yml

Align typefaces in logs routing docs and update change log.
- Relates #13863

[azure logs] Align typefaces in logs routing docs and update change log

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/admin/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/auth/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/auth/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/offline_enrollment/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/summary/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/telephony/agent/stream/httpjson.yml.hbs
packages/cisco_duo/data_stream/telephony_v2/agent/stream/cel.yml.hbs
packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
packages/cisco_duo/manifest.yml

cisco_duo: add support for http proxy configuration

---

packages/zscaler_zpa/changelog.yml
packages/zscaler_zpa/data_stream/user_activity/_dev/test/pipeline/test-user-activity.log-expected.json
packages/zscaler_zpa/data_stream/user_activity/elasticsearch/ingest_pipeline/default.yml
packages/zscaler_zpa/data_stream/user_activity/sample_event.json
packages/zscaler_zpa/docs/README.md
packages/zscaler_zpa/manifest.yml

```
zscaler_zpa: fix IPProtocol mapping
The ingest pipeline was previously incorrectly mapping the values of
IPProtocol to network.type when it should be mapped to network.transport.
```
- Fixes #13980

zscaler_zpa: fix IPProtocol mapping

---

packages/beelzebub/changelog.yml
packages/beelzebub/data_stream/logs/_dev/test/pipeline/test-logs-ndjson.log-expected.json
packages/beelzebub/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
packages/beelzebub/manifest.yml

```
beelzebub: implement password redaction via gsub
The redact processor is not available for basic subscriptions, so
replace it with gsub to prevent CI failing when testing with that
subscription.
```
- Closes #14023
- Closes #14025

beelzebub: implement password redaction via gsub

---

packages/ti_anomali/changelog.yml
packages/ti_anomali/elasticsearch/transform/latest_intelligence/fields/ecs.yml
packages/ti_anomali/elasticsearch/transform/latest_intelligence/transform.yml
packages/ti_anomali/manifest.yml

See the title.
- Closes #14080

ti_anomali: add missing event.ingested ECS field in transform

---

packages/tenable_io/_dev/build/docs/README.md
packages/tenable_io/changelog.yml
packages/tenable_io/docs/README.md
packages/tenable_io/manifest.yml

```
This PR documents breaking-changes introduced in 4.0.0
with intention to provide users sufficient knowledge 
before upgrading to this version.
```
- Relates https://github.com/elastic/integrations/pull/13636#discussion_r2121410544

tenable_io: Document breaking-changes introduced in 4.0.0.

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml

Adding `direct-access-key `in Cloud Asset Inventory's Cloud Formation template links.  This is for when selecting the agentless deployment option we should only be creating an access and secret key for the agent to access the AWS account.
1.  Build version 18 of the cloud_asset_inventory integration package.
2. Deploy the zip to the docker-hosted elastic-package
3. Restart Kibana with `NODE_TLS_REJECT_UNAUTHORIZED=0 node --no-warnings scripts/kibana --dev`
4. Navigate to the `Cloud Asset Discovery` integration and click add integration
5. Choose Organization or Single Account
6. Choose Agentless deployment
7. Click the Cloud Formation link
8. The Cloud FOrmation template should load without any issues and create the access and secret key
```
Using the organization account may require …
```

[Cloud Security] Adding direct-access-key in Cloud Asset Inventory's Cloud Formation template links.

---

packages/zscaler_zpa/changelog.yml
packages/zscaler_zpa/data_stream/user_activity/elasticsearch/ingest_pipeline/default.yml
packages/zscaler_zpa/manifest.yml

[zscaler_zpa] `Fix related.host` to be `related.hosts`

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.17.14.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/02a55e99c8fdaa10d824d1a6e40d1418c9c4847f
None
None

[Security Rules] Update security rules package to v8.17.14

---

packages/synthetics/manifest.yml

Follow up to https://github.com/elastic/integrations/pull/12820 !!

Enable Maintenance windows field on 8.19.0 !!

---

packages/mysql/_dev/build/docs/README.md
packages/mysql/changelog.yml
packages/mysql/docs/README.md
packages/mysql/manifest.yml

This PR updates the https://www.elastic.co/docs/reference/integrations/mysql page to:
- Fix the compatibility table 
- Improve the text
Closes https://github.com/elastic/docs-content/issues/1824

Fix table and edits on MySQL Integration 

---

packages/ded/changelog.yml
packages/ded/docs/README.md
packages/ded/elasticsearch/transform/pivot_transform/fields/fields.yml
packages/ded/elasticsearch/transform/pivot_transform/transform.yml
packages/ded/kibana/ml_module/ded-ml.json
packages/ded/manifest.yml

Clarify OS support for DED
Tested the updated transform locally with elastic package:
-

Clarify OS support for DED

---

packages/abnormal_security/_dev/build/docs/README.md
packages/abnormal_security/changelog.yml
packages/abnormal_security/data_stream/ai_security_mailbox/manifest.yml
packages/abnormal_security/data_stream/ai_security_mailbox_not_analyzed/manifest.yml
packages/abnormal_security/data_stream/audit/manifest.yml
packages/abnormal_security/data_stream/case/manifest.yml
packages/abnormal_security/data_stream/threat/fields/fields.yml
packages/abnormal_security/data_stream/threat/manifest.yml
packages/abnormal_security/data_stream/vendor_case/manifest.yml
packages/abnormal_security/docs/README.md
packages/abnormal_security/kibana/dashboard/abnormal_security-37ed5d19-c753-43a0-b0a2-f8e6437ddfe5.json
packages/abnormal_security/kibana/dashboard/abnormal_security-6a8e53ac-7759-4564-bcd6-03c6a9792eac.json
packages/abnormal_security/kibana/dashboard/abnormal_security-7997c0a4-da55-4090-b24f-586dbd19aff4.json
packages/abnormal_security/kibana/dashboard/abnormal_security-a0e8aab9-b870-4903-a966-7195fd6cee9c.json
packages/abnormal_security/kibana/dashboard/abnormal_security-a4364503-ada3-4fe6-a054-d152accf207c.json
packages/abnormal_security/kibana/dashboard/abnormal_security-f6562262-e429-470d-af45-4c80afdcf664.json
packages/abnormal_security/kibana/search/abnormal_security-5a32aa45-1ea0-4b68-9c06-53425f4e2deb.json
packages/abnormal_security/kibana/search/abnormal_security-a2d86921-d69f-4f99-a9eb-88a7ba0b2923.json
packages/abnormal_security/kibana/search/abnormal_security-b154b107-1350-48fe-b50e-d5427c5169ff.json
packages/abnormal_security/kibana/search/abnormal_security-e34b2986-68c2-4de9-8601-7bdefab429bc.json
packages/abnormal_security/kibana/search/abnormal_security-ecec7bf6-c7a6-4fb4-8054-863c5a1a666e.json
packages/abnormal_security/kibana/search/abnormal_security-f9b16544-6009-42fa-b569-ff029cc5c019.json
packages/abnormal_security/kibana/tag/abnormal_security-1c95de21-1f0d-4245-bdc6-3cf701a1743f.json
packages/abnormal_security/kibana/tag/abnormal_security-security-solution-default.json
packages/abnormal_security/manifest.yml

```
abnormal_security: rebrand Abnormal Security integration to Abnormal AI
This is a superficial branding update only and does not affect
existing functionalities. The changes include display names, 
reference links, documentation and dashboards to align
with the new brand name.
```
> Note: The dashboard screenshot has not been updated with the latest changes because I don’t have enough data to fully populate the dashboards.
- Closes #14156 
**Integration Display**
Before:
After:
**Integration Details**
Before:
After:
**Integration Assets**
Before:
After:

abnormal_security: rebrand Abnormal Security integration to Abnormal AI

---

packages/windows_etw/changelog.yml
packages/windows_etw/manifest.yml

The underlying input was made GA on 8.17
- Relates https://github.com/elastic/integrations/issues/13249

[windows_etw] Make windows_etw ga

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml

[Cloud Asset Discovery] Fix cloudformation version and params

---

packages/ti_recordedfuture/changelog.yml
packages/ti_recordedfuture/data_stream/triggered_alert/elasticsearch/ingest_pipeline/default.yml
packages/ti_recordedfuture/manifest.yml

ti_recordedfuture: fingerprint id and log fields

---

.buildkite/hooks/pre-command
.buildkite/pipeline.backport.yml
.buildkite/pipeline.serverless.yml
.buildkite/pipeline.yml

Use https://github.com/elastic/vault-github-token-buildkite-plugin instead of using pre-command hooks with complicated conditions.
This helps to know what Buildkite step uses `VAULT_GITHUB_TOKEN` and self-document those sensitive details as it's a declarative syntax.
NA - only in the CI
-

bk: use a buildkite plugin and be declarative

---

packages/entityanalytics_entra_id/changelog.yml
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-users.json
packages/entityanalytics_entra_id/data_stream/entity/_dev/test/pipeline/test-users.json-expected.json
packages/entityanalytics_entra_id/data_stream/entity/elasticsearch/ingest_pipeline/default.yml
packages/entityanalytics_entra_id/data_stream/entity/elasticsearch/ingest_pipeline/device.yml
packages/entityanalytics_entra_id/data_stream/entity/elasticsearch/ingest_pipeline/user.yml
packages/entityanalytics_entra_id/data_stream/entity/fields/fields.yml
packages/entityanalytics_entra_id/docs/README.md
packages/entityanalytics_entra_id/manifest.yml

```
entityanalytics_entra_id: ingest extra fields selected via select in Custom Options
This change updates the ingest pipeline to preserve extra fields selected 
through custom options. Previously, it only mapped the default fields
and removed remaining fields under the azure_ad field. Now, it
automatically maps the extra fields to the appropriate location
under the entityanalytics_entra_id field.
```
- Closes #14432

entityanalytics_entra_id: Ingest extra field selected via select option

---

packages/sql_input/docs/README.md

This PR suggests some edits to the SQL Input integration page.
Relates:
- https://github.com/elastic/integrations/pull/14237
- https://github.com/elastic/obs-integration-team/issues/291#issuecomment-3043589731

[sql_input] Improve docs

---

packages/aws/changelog.yml
packages/aws/data_stream/cloudtrail/agent/stream/aws-cloudwatch.yml.hbs
packages/aws/data_stream/cloudtrail/agent/stream/aws-s3.yml.hbs
packages/aws/manifest.yml

aws: fix agent template typo

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml

Separate cloudformation files for cloud connectors, using the correct `cloudbeat-asset-inventory-root` role name.
-

[cloud asset discovery]: fix cloudformation for cloud connectors

---

packages/auth0/_dev/build/docs/README.md
packages/auth0/changelog.yml
packages/auth0/data_stream/logs/manifest.yml
packages/auth0/docs/README.md
packages/auth0/manifest.yml

See title.
Here's what the policy editor UI form looks like with the manifest changes:

[auth0] Improve webhook setup instructions

---

packages/ti_greynoise/_dev/build/docs/README.md
packages/ti_greynoise/changelog.yml
packages/ti_greynoise/data_stream/ip/elasticsearch/ingest_pipeline/default.yml
packages/ti_greynoise/docs/README.md
packages/ti_greynoise/elasticsearch/transform/ip/fields/ecs.yml
packages/ti_greynoise/elasticsearch/transform/ip/transform.yml
packages/ti_greynoise/manifest.yml

- Enhancement
Add support for version 9.0.0 and enable agentless deployment

[ti_greynoise] Add Agentless deployment

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

* Update cloud formation link for cloud connectors to `9.1.0`
* Update GCP cloud shell branch to `8.19`
* Update Azure ARM branch to `8.19`
-

[cloud security posture]: fix link versions for 8.19.0 and 9.1.0

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

[cloud security posture]: release version 3.0.0

---

packages/cloud_asset_inventory/changelog.yml
packages/cloud_asset_inventory/manifest.yml

[cloud_asset_inventory] Version 1.0.0

---

packages/infoblox_nios/_dev/build/docs/README.md
packages/infoblox_nios/changelog.yml
packages/infoblox_nios/docs/README.md
packages/infoblox_nios/manifest.yml

```
infoblox_nios: update integration for compatibility with NIOS 9.0
Update reference links and compatibility section in the
documentation to specify the supported NIOS 9.0 version.
The integration is tested against NIOS 9.0.3 version.
```
- Closes #14134

infoblox_nios: update integration for compatibility with NIOS 9.0

---

packages/azure_ai_foundry/changelog.yml
packages/azure_ai_foundry/kibana/dashboard/azure_ai_foundry-09e1aa79-9d15-4bbe-a32c-85766864fa6a.json
packages/azure_ai_foundry/manifest.yml

- Bug
Fixes the typo in billing dashboard summary. The dashboard image is already up-to date.

[Azure AI Foundry] Fix typo in the billing dashboard summary

---

packages/cloud_security_posture/changelog.yml

Changes included:
- added a note to the version map that it doesn't apply to serverless
- cleaned up changelog by aggregating preview changes for 2.0.0, 3.0.0 and 1.12.0 , the step we missed when we released these versions
-

Add a note to version map of CSP integration about serverless kibana.version constraint

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/75c53838-5dcd-11f0-829c-f661ea17fbcd_2.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.18.9-beta.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3abfb33f8ee24c6c38110fc9d39794da9aed120d
None
None

[Security Rules] Update security rules package to v8.18.9-beta.3

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/75c53838-5dcd-11f0-829c-f661ea17fbcd_2.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.0.9-beta.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/a7d0e52025c1ce8b49e648fd6dcd9d70ada1492f
None
None

[Security Rules] Update security rules package to v9.0.9-beta.3

---

packages/sql_input/changelog.yml
packages/sql_input/manifest.yml

Add `fips_compatible`  flag to sql input package

---

packages/ded/changelog.yml
packages/ded/docs/README.md
packages/ded/elasticsearch/transform/pivot_transform/transform.yml
packages/ded/manifest.yml

Clarify network and file events in Data Exfiltration Detection 
-

[DED] Add info to clarify network and file events

---

packages/rapid7_insightvm/changelog.yml
packages/rapid7_insightvm/data_stream/asset/agent/stream/httpjson.yml.hbs
packages/rapid7_insightvm/data_stream/asset/sample_event.json
packages/rapid7_insightvm/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
packages/rapid7_insightvm/data_stream/vulnerability/sample_event.json
packages/rapid7_insightvm/docs/README.md
packages/rapid7_insightvm/manifest.yml

```
rapid7_insightvm: avoid logging failures for empty HTTPJSON template value evaluation
Template execution failures are expected when the template result is empty in
pagination and cursor cases. So, avoid logging these as failures to prevent
updating the health status to degraded. The changes been applied to the
asset and vulnerability data streams.
```
References:
- #14525
- https://github.com/elastic/beats/pull/45361
- For #14301 
- #14330 
- Relates #14491

rapid7_insightvm: avoid logging failure for empty HTTPJSON template value evaluation

---

packages/o365/_dev/build/docs/README.md
packages/o365/changelog.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

```
[o365] Explain data latency in the documentation
```

[o365] Explain data latency in the documentation

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.19.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/9dd7762ccc8df365c0d40ccf4f322ca3fc87edcc
None
None

[Security Rules] Update security rules package to v8.19.3

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 9.1.3.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/50ccb8828a5ace63000788a4260f100bb2dc5f98
None
None

[Security Rules] Update security rules package to v9.1.3

---

packages/elastic_security/_dev/build/docs/README.md
packages/elastic_security/changelog.yml
packages/elastic_security/docs/README.md
packages/elastic_security/manifest.yml

Addresses https://github.com/elastic/kibana/issues/230402 and fixes a typo in the alert index referenced in the main README.md.
cc @mohitjha-elastic @kgeller

[Elastic Security] Update alert index in README.md

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.19.4.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d16d04404cb01d0cdb9dc070b74e82fb6404ae21
None
None

[Security Rules] Update security rules package to v8.19.4

---

packages/jolokia_input/changelog.yml
packages/jolokia_input/docs/README.md
packages/jolokia_input/manifest.yml

Update Jolokia Input Documentation.
-

[Jolokia Input] Update Documentation

---

packages/awsfirehose/changelog.yml
packages/awsfirehose/manifest.yml

[AWS Data Firehose] Fixing link

---

packages/awsfirehose/changelog.yml
packages/awsfirehose/manifest.yml

[AWS Firehose] Firehose link for changelog

---

packages/crowdstrike/data_stream/alert/_dev/test/policy/test-default.expected
packages/crowdstrike/data_stream/alert/_dev/test/policy/test-default.yml
packages/crowdstrike/data_stream/alert/_dev/test/policy/test-traced.expected
packages/crowdstrike/data_stream/alert/_dev/test/policy/test-traced.yml
packages/crowdstrike/data_stream/alert/agent/stream/cel.yml.hbs
packages/crowdstrike/data_stream/falcon/_dev/test/policy/test-default.expected
packages/crowdstrike/data_stream/falcon/_dev/test/policy/test-default.yml
packages/crowdstrike/data_stream/falcon/_dev/test/policy/test-streaming.expected
packages/crowdstrike/data_stream/falcon/_dev/test/policy/test-streaming.yml
packages/crowdstrike/data_stream/fdr/_dev/test/policy/test-default.expected
packages/crowdstrike/data_stream/fdr/_dev/test/policy/test-default.yml
packages/crowdstrike/data_stream/host/_dev/test/policy/test-default.expected
packages/crowdstrike/data_stream/host/_dev/test/policy/test-default.yml
packages/crowdstrike/data_stream/vulnerability/_dev/test/policy/test-default.expected
packages/crowdstrike/data_stream/vulnerability/_dev/test/policy/test-default.yml
packages/crowdstrike/data_stream/vulnerability/_dev/test/policy/test-traced.expected
packages/crowdstrike/data_stream/vulnerability/_dev/test/policy/test-traced.yml
packages/crowdstrike/data_stream/vulnerability/agent/stream/cel.yml.hbs

```
crowdstrike: add basic policy tests
[git-generate]
cd packages/crowdstrike
parallel 'celfmt -agent -i {} -o {}' ::: data_stream/{alert,vulnerability}/agent/stream/cel.yml.hbs
parallel '(
mkdir -p {}/_dev/test/policy/
cat > {}/_dev/test/policy/test-default.yml << END
vars:
url: http://host.tld
client_id: test_client_id
client_secret: test_client_secret
token_url: http://host.tld/oauth2/token
data_stream:
vars:
preserve_original_event: true
preserve_duplicate_custom_fields: true
END
)' ::: data_stream/*
parallel '(
cat > {}/_dev/test/policy/test-traced.yml << END
vars:
url: http://host.tld
client_id: test_client_id
client_secret: test_client_secret
token_url: http://host.tld/oauth2/token
data_stream:
vars:
enable_request_tracer: true
preserve_original_event: true …
```

crowdstrike: add basic policy tests

---

packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/data_stream/log/agent/stream/httpjson.yml.hbs
packages/microsoft_defender_endpoint/data_stream/log/manifest.yml
packages/microsoft_defender_endpoint/manifest.yml

microsoft_defender_endpoint: add SSL configuration for log data stream

---

packages/qualys_vmdr/_dev/deploy/docker/files/config.yml
packages/qualys_vmdr/changelog.yml
packages/qualys_vmdr/data_stream/asset_host_detection/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/knowledge_base/agent/stream/input.yml.hbs
packages/qualys_vmdr/data_stream/user_activity/agent/stream/cel.yml.hbs
packages/qualys_vmdr/manifest.yml

qualys_vmdr: implement X-RateLimit header handling

---

packages/o365_metrics/_dev/build/docs/README.md
packages/o365_metrics/changelog.yml
packages/o365_metrics/docs/README.md
packages/o365_metrics/manifest.yml

This PR:
- Applies the new template structure
- Suggests some edits to improve readability
Please complete the following sections, where applicable:
- Compatibility
- How it works
- What do I need to use this integration?
- Troubleshooting
- Scaling
- Reference content

Review the Microsoft Office 365 Metrics Integration documentation

---

packages/splunk/changelog.yml
packages/splunk/data_stream/alert/agent/stream/cel.yml.hbs
packages/splunk/manifest.yml

```
splunk: use config auth instead of manual header handling
There is no reason to use the constructed request approach to API
requests in this data stream, so avoid it and the complication and
secret-leak risks that it brings.
```

splunk: use config auth instead of manual header handling

---

packages/cel/_dev/test/system/test-basic-auth-config.yml
packages/cel/_dev/test/system/test-get-config.yml
packages/cel/_dev/test/system/test-oauth-config.yml
packages/cel/_dev/test/system/test-oauth-scope-config.yml
packages/cel/agent/input/input.yml.hbs
packages/cel/changelog.yml
packages/cel/manifest.yml

cel: add missing resource timeout template snippet and improve docs

---

packages/elastic_agent/changelog.yml
packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
packages/elastic_agent/manifest.yml

Change memory source field to `component.id` to calculate the correct memory values in Agent metrics dashboard
- Relates https://github.com/elastic/kibana/issues/223292
Before:
After:

[Elastic Agent] use `component.id` instead of `elastic_agent.process` in memory visualisations

---

CODE_OF_CONDUCT.md

conduct: fix markdown

---

packages/ti_greynoise/_dev/deploy/docker/files/config.yml
packages/ti_greynoise/changelog.yml
packages/ti_greynoise/data_stream/ip/agent/stream/cel.yml.hbs
packages/ti_greynoise/data_stream/ip/sample_event.json
packages/ti_greynoise/docs/README.md
packages/ti_greynoise/elasticsearch/transform/ip/transform.yml
packages/ti_greynoise/elasticsearch/transform/rule/transform.yml
packages/ti_greynoise/manifest.yml

- Enhancement
The previous endpoint was timing out quickly, causing user disruption.
This changes the endpoint to avoid that problem.

[ti_greynoise] Update data collection endpoint

---

packages/linux/changelog.yml
packages/linux/data_stream/pageinfo/manifest.yml
packages/linux/manifest.yml

```
[linux] require root privileges for pageinfo
```
- ~~[ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~
see images below on the _Screenshots_ section for more details
- spin up a Elastic Stack
- install this PR version of the linux integration
```
cd packages/linux/
elastic-package install -v
```
- add linux integration
- confirm the linux integration is on version 0.73 
- confirm the integration page states it need root privileges
- confirm the add …

[linux] require root privileges for pageinfo

---

packages/o365_metrics/_dev/build/docs/README.md
packages/o365_metrics/changelog.yml
packages/o365_metrics/docs/README.md
packages/o365_metrics/manifest.yml

Make O365 Metrics integration GA.
-

[O365 Metrics] Make O365 Metrics integration GA

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
packages/cloud_security_posture/manifest.yml

Fixes https://github.com/elastic/integrations/issues/14790
See https://github.com/elastic/integrations/issues/14793

[backport 1.13] [Cloud Security] Cast GCP and azure project/client IDs as strings

---

packages/system/changelog.yml
packages/system/manifest.yml

Enable journald input instead of log input when running on Debian 13.
- Closes https://github.com/elastic/integrations/issues/15084

Use journald input by default when running system integration for Debian 13

---

packages/cel/_dev/deploy/docker/files/config.yml
packages/cel/_dev/test/policy/test-auth-and-headers.expected
packages/cel/_dev/test/policy/test-auth-and-headers.yml
packages/cel/_dev/test/policy/test-default.expected
packages/cel/_dev/test/policy/test-default.yml
packages/cel/_dev/test/policy/test-headers.expected
packages/cel/_dev/test/policy/test-headers.yml
packages/cel/_dev/test/system/test-basic-auth-config.yml
packages/cel/_dev/test/system/test-get-config.yml
packages/cel/_dev/test/system/test-oauth-config.yml
packages/cel/_dev/test/system/test-oauth-scope-config.yml
packages/cel/agent/input/input.yml.hbs
packages/cel/changelog.yml
packages/cel/manifest.yml

cel: add support for global header configuration

---

packages/jamf_protect/changelog.yml
packages/jamf_protect/data_stream/alerts/_dev/test/pipeline/test-common-config.yml
packages/jamf_protect/data_stream/alerts/_dev/test/pipeline/test-jamf-protect-alerts-sample-logs.log-expected.json
packages/jamf_protect/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/jamf_protect/manifest.yml

```
jamf_protect: fix handling of tags in alerts data stream
The old code assumes that the tags field is not populated, resulting in
the tags that were set being clobbered. This fixes that.
Also simplify and move the conditions for related processors out into if
processor config fields.
```
-

jamf_protect: fix handling of tags in alerts data stream

---

.github/CODEOWNERS
docs/extend/documentation-guidelines.md
packages/osquery/manifest.yml

Update code owner for osquery integration

Update osquery codeowner

---

packages/ti_greynoise/_dev/build/docs/README.md
packages/ti_greynoise/changelog.yml
packages/ti_greynoise/docs/README.md
packages/ti_greynoise/elasticsearch/transform/ip/transform.yml
packages/ti_greynoise/elasticsearch/transform/rule/transform.yml
packages/ti_greynoise/manifest.yml

- Enhancement
add note to filter GreyNoise threat intel data in detection rules and section on updating integration in README.

[ti_greynoise] Add GreyNoise detection rule filter note and integration update section

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-106023-iface-with-prefix.log
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-106023-iface-with-prefix.log-expected.json
packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_asa/manifest.yml

There was a bug in the pipeline where empty access-group name would result in parsing error. 
This PR makes the access-group optional to support the the above case.  
- Closes #11236

[cisco_asa][bugfix] allow empty access-group

---

packages/proofpoint_tap/_dev/build/docs/README.md
packages/proofpoint_tap/changelog.yml
packages/proofpoint_tap/data_stream/clicks_blocked/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/data_stream/clicks_permitted/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/data_stream/message_blocked/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/data_stream/message_delivered/elasticsearch/ingest_pipeline/default.yml
packages/proofpoint_tap/docs/README.md
packages/proofpoint_tap/manifest.yml

```
proofpoint_tap: add agentless deployment
```
- Install the elastic package locally.
- Start the elastic stack using the elastic package.
- Move to integrations/packages/proofpoint_tap directory.
- Closes https://github.com/elastic/integrations/issues/14976
**Note**: These changes are not tested on serverless project.

[proofpoint_tap] Add Agentless Deployment

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/cel.yml.hbs
packages/o365/manifest.yml

```
o365: Fix 429 due to multiple subscription start attempts.
Right now, the code makes multiple requests to API:
"/subscriptions/start?contentType=" which causes the error:
"Too many frequent subscription start requests. Please retry again after 14m 56s"
Update CEL program to call "/subscriptions/start?contentType=" only
when the contentType is not already started. This was checked
using presence of contentType inside "cursor.last_for".
```

o365: Fix 429 due to multiple subscription start attempts.
