elastic/integrations

testing/environments/kibana.config.yml

According to the suggestion in https://github.com/elastic/kibana/issues/65464 .

testing Kibana: disable TLS check

---

.ci/Jenkinsfile
.ci/jobs/integrations.yml

The repository to checkout is incorrect.

fix: set correct repository

---

dev/import-beats-resources/aws/README.md

This PR adds static resources for `aws` integration.
Original PR: https://github.com/elastic/package-registry/pull/437

Add static resources for AWS integration

---

dev/packages/alpha/aws/0.0.3/docs/README.md
dev/packages/alpha/aws/0.0.3/manifest.yml

This PR is to add example json events for all datasets under AWS package.
Also changed some aws to AWS.

Add example events for datasets under aws package

---

CONTRIBUTING.md

Update CONTRIBUTING.md to add some additional notes about fields files.

Update CONTRIBUTING.md to add some additional notes about dataset fields files.

---

dev/update-package-storage/README.md
dev/update-package-storage/git.go
dev/update-package-storage/github.go
dev/update-package-storage/main.go
dev/update-package-storage/packages.go

Issue: https://github.com/elastic/integrations/issues/46
This PR adds support for automatically opening pull requests against https://github.com/elastic/package-storage .
Sample "fake" PR created: https://github.com/elastic/package-storage/pull/55

Open pull request using Github API

---

packages/system/kibana/dashboard/79ffd6e0-faa0-11e6-947f-177f697178b8-ecs.json
packages/system/manifest.yml

This fixes https://github.com/elastic/integrations/issues/26 This isn't a huge issue, but it's more a cleanliness thing.

Fix system dashboard query

---

dev/import-beats/requirement.go

This PR updates the `import-beats` script to recent changes in https://github.com/elastic/package-registry/pull/516

Update version requirements to recent changes

---

CONTRIBUTING.md

Adds notes about package release versions and possible ignorable error on Mac OS X.

Minor improvements to CONTRIBUTING guide

---

dev/import-beats/variables.go
packages/mysql/dataset/error/manifest.yml
packages/mysql/dataset/slowlog/manifest.yml

Drop support for OS variables and adjust all packages.

Drop support for OS variables

---

.ci/Jenkinsfile
.ci/distribution/Dockerfile

* Start using withMageEnv step 
* Push a Docker image with the master package registry and the current packages build

feat: build docker image

---

CONTRIBUTING.md

This PR adds a "Tips" section to the CONTRIBUTING guide.
Preview link: https://github.com/mtojek/integrations/blob/tips-for-devs/CONTRIBUTING.md#tips-for-building-integrations
In the next step I will prepare a pull-request template.

Add Tips section

---

packages/log/manifest.yml

Issue: https://github.com/elastic/integrations/issues/106

Fix: typo in custom logs

---

dev/import-beats/icons.go

Update kibanaLogosPath in icons.go to address issue #128

Update kibanaLogosPath in icons.go to address issue #128

---

CONTRIBUTING.md

This PR adds tips for empty fields files.
Preview: https://github.com/mtojek/integrations/blob/tips-2-fields/CONTRIBUTING.md#fields

Add tips for fields files

---

dev/import-beats/streams_config_parser.go

Add functions tojson and inList.
Note that it will let the program to run and finish, but it does not create anything equivalent in the handlebars template.

Address issue #127 function tojson not defined

---

dev/import-beats/kibana.go

Fixes: https://github.com/elastic/integrations/issues/126

Fix: add request.body.version

---

magefile.go

I am currently making a few changes to the import-beats script and I want to have assurance in CI that I did not break it. So this makes sure, that the script at least still builds after changes.

Add build check for import-beats script

---

packages/aws/dataset/cloudtrail/elasticsearch/ingest-pipeline/default.yml
packages/aws/dataset/cloudtrail/fields/fields.yml
packages/aws/docs/README.md

- session_context fix
- geoip AS for source.ip
- event.category & event.type expansion
Closes #79

Sync with current Filebeat aws/cloudtrail

---

CONTRIBUTING.md
packages/apache/manifest.yml
packages/aws/manifest.yml
packages/cisco/manifest.yml
packages/kafka/manifest.yml
packages/kubernetes/manifest.yml
packages/log/manifest.yml
packages/mongodb/manifest.yml
packages/mysql/manifest.yml
packages/netflow/manifest.yml
packages/nginx/manifest.yml
packages/postgresql/manifest.yml
packages/rabbitmq/manifest.yml
packages/redis/manifest.yml
packages/system/manifest.yml
packages/windows/manifest.yml

The PR updates categories of existing integrations to ones defined in the Package Registry.
- https://github.com/elastic/integrations/pull/144

Define missing categories

---

CONTRIBUTING.md
dev/import-beats/conditions.go
dev/import-beats/packages.go
packages/apache/manifest.yml
packages/aws/manifest.yml
packages/cisco/manifest.yml
packages/kafka/manifest.yml
packages/kubernetes/manifest.yml
packages/mongodb/manifest.yml
packages/mysql/manifest.yml
packages/netflow/manifest.yml
packages/nginx/manifest.yml
packages/postgresql/manifest.yml
packages/rabbitmq/manifest.yml
packages/redis/manifest.yml
packages/system/manifest.yml
packages/windows/manifest.yml

What does this PR do?
This PR sets the condition for kibana version (^7.9.0)

Set required kibana version to ^7.9.0

---

packages/system/kibana/visualization/3d65d450-a9c3-11e7-af20-67db8aecb295-ecs.json
packages/system/kibana/visualization/855899e0-1b1c-11e7-b09e-037021c4f8df-ecs.json
packages/system/kibana/visualization/System-Navigation-ecs.json
packages/system/kibana/visualization/fe064790-1b1f-11e7-bec4-a5e9ec5cab8b-ecs.json
packages/system/manifest.yml

See https://github.com/elastic/integrations/issues/163. This PR updates the links used by the system integration dashboards.
- run `mage build`
- startup test environment in `testing/environment`
- Make sure the markdown links in the various system dashboards work.

Update link IDs in system dashboards

---

packages/mongodb/manifest.yml

This PR is to fix mongodb package. It was working before but I think something changed for the config template.

Change datasources to config_templates in manifest.yml

---

testing/environments/kibana.config.yml

Updates the `kibana.config.yml` file used by the Docker container, per guidance from @skh here: https://github.com/elastic/package-storage/pull/133#issuecomment-658371941

Updating kibana config

---

testing/environments/kubernetes/snapshot.yml

Updates the kibana configuration file used by the Kibana Pod.
Similar to https://github.com/elastic/integrations/pull/177

Update Kibana epr config

---

CONTRIBUTING.md
magefile.go
testing/environments/Dockerfile.package-registry
testing/environments/package-registry.config.yml
testing/environments/snapshot.yml

1. Update the image reference to the Package Registry
2. Don't use development mode from EPR as it's buggy (will be deprecated)
3. Add new target: `mage reload` to rebuild and restart the package registry.
4. Update docs.
~- [ ] I have verified that all datasets collect metrics or logs.~
-

Do not use volumes, but rebuild container

---

CONTRIBUTING.md

Adds a clarification for people starting up on this that their checkouts for the dependent projects need to be in the same parent directory as the `integrations` project.
- ~~[] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.~~
- ~~[ ] I have verified that all datasets collect metrics or logs.~~

[Documentation] Update contribution guide with mage ImportBeats clarification

---

testing/environments/7.9.0.yml

Add docker cluster definitions for 7.9.0

Define cluster with 7.9.0

---

packages/kubernetes/dataset/apiserver/manifest.yml
packages/kubernetes/dataset/container/manifest.yml
packages/kubernetes/dataset/node/manifest.yml
packages/kubernetes/dataset/pod/manifest.yml
packages/kubernetes/dataset/system/manifest.yml
packages/kubernetes/dataset/volume/manifest.yml
packages/kubernetes/manifest.yml

This PR changes `Ssl` to `SSL` in configuration options' tittles

Fix minor capitalisation issue

---

packages/mongodb/manifest.yml

This PR improves MongoDB configuration fields.
-

MongoDB: Improve field definitions

---

packages/kubernetes/dataset/state_container/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_cronjob/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_deployment/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_node/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_persistentvolume/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_persistentvolumeclaim/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_pod/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_replicaset/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_resourcequota/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_service/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_statefulset/agent/stream/stream.yml.hbs
packages/kubernetes/dataset/state_storageclass/agent/stream/stream.yml.hbs

Follow up of https://github.com/elastic/integrations/pull/197.

Add missing settings for agent config

---

packages/log/dataset/log/agent/stream/stream.yml.hbs
packages/log/manifest.yml

should not have double quotes. It should use single quotes or omit the quotes entirely
Fixes: https://github.com/elastic/kibana/issues/73075
-

Fix encoding issues

---

dev/update-package-storage/main.go

Do not skip first release of packages (not released yet)

Fix: properly handle first release

---

dev/import-beats-resources/system/docs/README.md
packages/system/docs/README.md
packages/system/manifest.yml

This fixes some Readme markdown issues that never made it back to `integrations`.

[system] fix readme in system package

---

dev/import-beats-resources/kafka/docs/README.md
dev/import-beats-resources/redis/docs/README.md
packages/kafka/docs/README.md
packages/kafka/manifest.yml
packages/mysql/manifest.yml
packages/nginx/manifest.yml
packages/redis/docs/README.md
packages/redis/manifest.yml

This PR fixes broken markdown links in few integrations.
-

Fix: markdown links

---

packages/windows/manifest.yml

Fixes issue where windows datasets were not visible

Update config option in the windows manifest file

---

packages/crowdstrike/manifest.yml

When I initially created this I followed the contributing docs which talk about making a beta package, but, since we're still in the experimental phase this needs to be "experimental" still.

Update CrowdStrike package to say experimental v. beta

---

dev/update-package-storage/github.go

This PR checks if the requested team has been assigned to the PR. API doesn't respond with 422 if the reviewer can't be assigned (will research it later).
-

Fix: check if requested team has been assigned to the PR

---

packages/microsoft/manifest.yml

Add owner information to microsoft package

---

packages/aws/dataset/cloudtrail/elasticsearch/ingest_pipeline/default.yml
packages/aws/manifest.yml

Removes duplicate ListGroupsForUser in aws/cloudtrail dataset

remove duplicate LIstGroupsForUser

---

dev/import-beats-resources/system/docs/README.md
packages/system/dataset/diskio/manifest.yml
packages/system/dataset/socket/manifest.yml
packages/system/docs/README.md
packages/system/manifest.yml

This fixes a few documentation-related issues in the system module that @EricDavisX noticed.

Fix a few docs issues in the system integration

---

testing/environments/Dockerfile.package-registry

Update the testing environment with the correct image reference for EPR distribution.
-

Fix image reference for EPR distribution

---

packages/mongodb/manifest.yml

`ssl.enabled` should be bool type instead of text.

Fix mongodb ssl.enabled type

---

CONTRIBUTING.md

Use 7.10 as the baseline for integrations.

Recommend 7.10 as the baseline

---

packages/system/manifest.yml

The system package will be GA in 7.10, so we're bumping the version to 1.0.0, and also raising the minimum version.

Promote system package for 7.10.0

---

packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
packages/crowdstrike/manifest.yml

- set ecs.version to 1.6.0
- bump package version

sync crowdstrike package with beat module

---

packages/checkpoint/data_stream/firewall/agent/stream/log.yml.hbs
packages/checkpoint/data_stream/firewall/agent/stream/syslog.yml.hbs
packages/checkpoint/manifest.yml

Sync checkpoint with beats module
- updated ecs.version
- bumped package version

Sync checkpoint package with beats module

---

packages/panw/data_stream/panos/agent/stream/log.yml.hbs
packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
packages/panw/data_stream/panos/fields/base-fields.yml
packages/panw/data_stream/panos/fields/beats.yml
packages/panw/data_stream/panos/fields/ecs.yml
packages/panw/data_stream/panos/fields/fields.yml
packages/panw/docs/README.md
packages/panw/manifest.yml

Changes
- Update package version to 0.3.0.
- Update ecs.version to 1.6.0.
- Add related.host field.
- Add panw.panos.endreason.
- Add panw.panos.type.
- Add panw.panos.sub_type.

Sync Panw package with Beats

---

doc/development/README.md
doc/development/guidelines/README.md

Placeholder to start adding the development guidelines.

Guidelines placeholder

---

packages/azure/manifest.yml

Bump `azure` to 0.0.2

---

dev/import-beats-resources/azure/docs/README.md
packages/azure/docs/README.md
packages/azure/kibana/dashboard/azure-41e84340-ec20-11e9-90ec-112a988266d5.json
packages/azure/manifest.yml

Fix for azure Overview dashboard

Fix for azure Overview dashboard

---

go.mod
go.sum

This PR updates dependency on elastic-package to enable pattern matching on field values.
- Closes https://github.com/elastic/elastic-package/issues/113

Update dependency on elastic-package

---

.ci/jobs/folders.yml
.ci/jobs/integrations.yml

it moves jobs to ingest-manager folder

ci: move jobs to ingest-manager folder

---

packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
packages/azure/manifest.yml

Fix the set processor inside the pipelines

Fix the set processor inside the pipelines

---

packages/windows/kibana/dashboard/windows-d9eba730-c991-11e7-9835-2f31fe08873b.json
packages/windows/manifest.yml

Provides a fix for windows services dashboard
- Closes https://github.com/elastic/integrations/issues/398

Fix for windows services dashboard

---

packages/checkpoint/data_stream/firewall/agent/stream/log.yml.hbs
packages/checkpoint/data_stream/firewall/agent/stream/udp.yml.hbs
packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
packages/checkpoint/data_stream/firewall/fields/agent.yml
packages/checkpoint/data_stream/firewall/fields/beats.yml
packages/checkpoint/data_stream/firewall/fields/ecs.yml
packages/checkpoint/docs/README.md
packages/checkpoint/manifest.yml

This updates the checkpoint package to use ECS 1.7, including the network direction changes recently introduced in beats.
~~[ ] I have verified that all datasets collect metrics or logs.~~

Update checkpoint integration to ECS 1.7

---

packages/azure/kibana/dashboard/azure-0f559cc0-f0d5-11e9-90ec-112a988266d5.json
packages/azure/kibana/dashboard/azure-41e84340-ec20-11e9-90ec-112a988266d5.json
packages/azure/kibana/dashboard/azure-87095750-f05a-11e9-90ec-112a988266d5.json
packages/azure/manifest.yml

Updates Azure dashboard text
- Relates https://github.com/elastic/observability-test-plans/issues/178

Update Azure dashboard text

---

.github/ISSUE_TEMPLATE/integration-checklist.md
doc/development/README.md
doc/development/guidelines/README.md

Checklist is pointing to an empty doc, remove the empty doc and point to contributing guidelines

Fix issue template, remove empty folders to avoid confusion

---

packages/iis/data_stream/access/manifest.yml
packages/iis/data_stream/application_pool/manifest.yml
packages/iis/data_stream/error/manifest.yml
packages/iis/data_stream/webserver/manifest.yml
packages/iis/data_stream/website/manifest.yml
packages/iis/manifest.yml

Set IIS package to beta

---

packages/stan/manifest.yml

This PR improves the STAN package description so as to indicate its streaming functionality.

Improve STAN description and category

---

packages/nats/_dev/build/docs/README.md
packages/nats/docs/README.md

This PR fixes a small issue in package's docs that would compile wrong dataset's sample event.

Fix nats package docs

---

go.mod
go.sum

Updates the version of the `package-registry` dependency.

Updating package registry version

---

.ci/Jenkinsfile
go.mod
go.sum
packages/aws/data_stream/ec2_metrics/_dev/deploy/tf/main.tf
packages/aws/data_stream/ec2_metrics/_dev/test/system/test-default-config.yml

This PR enables the AWS service deployer and adds sample tests for AWS EC2.
The CI will verify it.
- https://github.com/elastic/elastic-package/issues/89

Define sample tests for AWS EC2 module

---

packages/fleet_server/elasticsearch/index_template/.fleet-agents.json
packages/fleet_server/manifest.yml

Update .fleet-agents mapping, add "local_metadata" mapping

Update .fleet-agents mapping, add "local_metadata" mapping

---

packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
packages/cisco/data_stream/asa/agent/stream/stream.yml.hbs
packages/cisco/data_stream/asa/agent/stream/udp.yml.hbs
packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
packages/cisco/data_stream/ftd/agent/stream/stream.yml.hbs
packages/cisco/data_stream/ftd/agent/stream/udp.yml.hbs
packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
packages/cisco/manifest.yml

Syncs ftd and asa data streams with latest changes from beats module

[cisco] Sync ftd and asa data streams with beats

---

packages/cef/data_stream/log/_dev/test/pipeline/test-cef-event.json-expected.json
packages/cef/data_stream/log/agent/stream/log.yml.hbs
packages/cef/data_stream/log/agent/stream/syslog.yml.hbs
packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cef/data_stream/log/fields/ecs.yml
packages/cef/docs/README.md
packages/cef/manifest.yml

Syncs cef with latest changes in beats

[cef] Sync cef data streams with beats

---

packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/admin/agent/stream/log.yml.hbs
packages/google_workspace/data_stream/admin/fields/ecs.yml
packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/drive/agent/stream/log.yml.hbs
packages/google_workspace/data_stream/drive/fields/ecs.yml
packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/groups/agent/stream/log.yml.hbs
packages/google_workspace/data_stream/groups/fields/ecs.yml
packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/login/agent/stream/log.yml.hbs
packages/google_workspace/data_stream/login/fields/ecs.yml
packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/saml/agent/stream/log.yml.hbs
packages/google_workspace/data_stream/saml/fields/ecs.yml
packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/user_accounts/agent/stream/log.yml.hbs
packages/google_workspace/data_stream/user_accounts/fields/ecs.yml
packages/google_workspace/docs/README.md
packages/google_workspace/manifest.yml

Syncs google_workspace package with changes done in beats

[google_workspace] Sync google_workspace data streams with beats

---

packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
packages/juniper/data_stream/srx/agent/stream/logfile.yml.hbs
packages/juniper/data_stream/srx/agent/stream/tcp.yml.hbs
packages/juniper/data_stream/srx/agent/stream/udp.yml.hbs
packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
packages/juniper/manifest.yml

Syncs juniper src with changes made in beats

[juniper] Sync juniper src data stream with beats

---

.ci/Jenkinsfile

It changes the timeout of the job to 2 hours.

ci: increase timeout

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/agent/stream/log.yml.hbs
packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
packages/o365/data_stream/audit/fields/ecs.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

Syncs o365 package with latest changes made in beats

Sync o365 package with beats

---

packages/fleet_server/manifest.yml

Bump Kibana version condition to ^7.12.0

[Fleet Server] Bump Kibana version condition to ^7.12.0

---

go.mod
go.sum

Brings in changes from the following PRs:
- https://github.com/elastic/elastic-package/pull/277
- https://github.com/elastic/elastic-package/pull/280
- https://github.com/elastic/elastic-package/pull/275
- https://github.com/elastic/elastic-package/pull/283

Updating dependency on elastic-package

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
packages/google_workspace/manifest.yml

Fix Google workspace pagination

---

docs/developer_workflow_promote_release_integration.md

Add mention about needing a fork of package store in the docs for promoting.

Mention the need of a fork of package-storage in the docs

---

go.mod
go.sum
packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-config.json
packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-config.yml
packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log-config.json
packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log-config.yml
packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-config.json
packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-config.yml

This PR will adjusts some leftovers in pipeline tests (switch from JSON to YML configs).
- Spotted in https://github.com/elastic/integrations/pull/797

Fix: adjust configs for pipeline tests (replace json with yml)

---

packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-config.yml

This PR refactors the pipeline config for GCP to use YAML structure instead of JSON.

Fix: use YAML struct

---

go.mod
go.sum

This PR bumps up dependency on elastic-package to fix the agent's healthcheck issue.

Update elastic-package to fix agent's healthcheck issue

---

go.mod
go.sum

This PR updates dependency on elastic-package to bring this change: https://github.com/elastic/elastic-package/pull/310

Update elastic-package dependency

---

go.mod
go.sum

Update `elastic-package` dep so as to include https://github.com/elastic/elastic-package/pull/314

Bump up elastic-package

---

packages/windows/changelog.yml
packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs

This PR updates the windows package to use ecs 1.9.0.

Update windows to ecs 1.9.0

---

packages/osquery_manager/manifest.yml

Update osquery_manager package to beta and add config_management category

Update osquery_manager package to beta and add config_management category

---

packages/windows/changelog.yml
packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
packages/windows/manifest.yml

Adds support for Sysmon v13 events

Add support for Sysmon v13 events

---

go.mod
go.sum

Updates dep of elastic-package so as to include https://github.com/elastic/elastic-package/pull/326

Update elastic-package dep

---

packages/winlog/changelog.yml

Add missing PR number in changelog

Add missing PR number to winlog changelog

---

.ci/Jenkinsfile

This PR enables nightly builds, so we can receive daily feedback on test execution.

Enable nightly builds

---

packages/nats/changelog.yml
packages/nats/kibana/visualization/nats-d80d4c30-2a81-11eb-9625-31ed579c09b3.json
packages/nats/kibana/visualization/nats-dff743a0-1f1c-11e9-a673-d9577e5e50eb.json
packages/nats/manifest.yml

Fixes filters in 2 visualisations of nats package.

Fix nats dashboards

---

packages/osquery/changelog.yml
packages/osquery_manager/docs/README.md
packages/osquery_manager/manifest.yml

Update README for osquery manager.
-

Update README for osquery-manager

---

packages/fleet_server/changelog.yml
packages/fleet_server/manifest.yml

Fleet server itself will be released as beta so the package itself should also be in beta.

[fleet_server] Push to beta release

---

packages/nginx_ingress_controller/changelog.yml
packages/nginx_ingress_controller/manifest.yml

Sets proper compatibility with Stack

Set proper stack version

---

packages/nats/changelog.yml
packages/nats/manifest.yml

Sets proper compatibility with Stack

Set compatabiltiy with stack

---

packages/kubernetes/manifest.yml

Properly updates package's version. (it was not properly updated at https://github.com/elastic/integrations/pull/998)

Update k8s package version

---

CONTRIBUTING.md
docs/generic_guidelines.md

This PR moves generic guidelines for developing integrations from private repository to public space.

Add generic guidelines for developing integrations

---

packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
packages/windows/changelog.yml
packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
packages/windows/manifest.yml

[windows] Fix security pipeline to support string event.code

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/state_statefulset/fields/fields.yml
packages/kubernetes/docs/README.md
packages/kubernetes/manifest.yml

Fixes https://github.com/elastic/integrations/issues/1110

Add mapping for kubernetes.statefulset.replicas.ready

---

packages/zeek/changelog.yml
packages/zeek/data_stream/http/fields/ecs.yml
packages/zeek/data_stream/sip/fields/ecs.yml
packages/zeek/docs/README.md
packages/zeek/manifest.yml

Uses wildcard field type for relevant ECS fields.

[zeek] Use wildcard type

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/fields/ecs.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

Uses wildcard field type for the relevant ECS fields.

[o365] Use wildcard type

---

packages/cisco/changelog.yml
packages/cisco/data_stream/asa/fields/ecs.yml
packages/cisco/data_stream/ftd/fields/ecs.yml
packages/cisco/data_stream/meraki/fields/ecs.yml
packages/cisco/data_stream/nexus/fields/ecs.yml
packages/cisco/docs/README.md
packages/cisco/manifest.yml

Uses wildcard field type for relevant ECS fields.

[cisco] Use wildcard type

---

packages/panw/changelog.yml
packages/panw/data_stream/panos/fields/ecs.yml
packages/panw/docs/README.md
packages/panw/manifest.yml

Uses wildcard field type for the relevant ECS fields.

[panw] Use wildcard type

---

.ci/Jenkinsfile

This PR updates Jenkinsfile to use kind v0.11.1.

Update kind to v0.11.1

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/data_stream/result/fields/osquery.yml
packages/osquery_manager/docs/README.md
packages/osquery_manager/manifest.yml

Updates Osquery Manager mapping and readme for osquery 4.8.0

Osquery manager: Update schema and readme for osquery 4.8.0

---

packages/auditd/changelog.yml
packages/auditd/data_stream/log/fields/base-fields.yml
packages/auditd/data_stream/log/manifest.yml
packages/auditd/docs/README.md
packages/auditd/manifest.yml

Makes the package GA with v1.0.0

[auditd] Make auditd package GA with v1.0.0

---

packages/okta/changelog.yml
packages/okta/data_stream/system/fields/base-fields.yml
packages/okta/data_stream/system/manifest.yml
packages/okta/docs/README.md
packages/okta/manifest.yml

Makes the package GA with v1.0.0

[okta] Make okta package GA with v1.0.0

---

packages/panw/changelog.yml
packages/panw/data_stream/panos/fields/base-fields.yml
packages/panw/data_stream/panos/manifest.yml
packages/panw/docs/README.md
packages/panw/manifest.yml

Makes the package GA with v1.0.0

[panw] Make panw package GA with v1.0.0

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/fields/base-fields.yml
packages/o365/data_stream/audit/manifest.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

[o365] Make o365 package GA with v1.0.0

---

packages/windows/changelog.yml
packages/windows/data_stream/forwarded/fields/base-fields.yml
packages/windows/data_stream/forwarded/fields/ecs.yml
packages/windows/data_stream/forwarded/manifest.yml
packages/windows/data_stream/perfmon/fields/base-fields.yml
packages/windows/data_stream/perfmon/manifest.yml
packages/windows/data_stream/powershell/fields/base-fields.yml
packages/windows/data_stream/powershell/fields/ecs.yml
packages/windows/data_stream/powershell/manifest.yml
packages/windows/data_stream/powershell_operational/fields/base-fields.yml
packages/windows/data_stream/powershell_operational/fields/ecs.yml
packages/windows/data_stream/powershell_operational/manifest.yml
packages/windows/data_stream/service/fields/base-fields.yml
packages/windows/data_stream/service/manifest.yml
packages/windows/data_stream/sysmon_operational/fields/base-fields.yml
packages/windows/data_stream/sysmon_operational/fields/ecs.yml
packages/windows/data_stream/sysmon_operational/manifest.yml
packages/windows/docs/README.md
packages/windows/manifest.yml

Make the package GA with v1.0.0

[windows] Make windows package GA with v1.0.0

---

packages/fortinet/changelog.yml
packages/fortinet/data_stream/clientendpoint/_dev/test/pipeline/test-generated.log-expected.json
packages/fortinet/data_stream/clientendpoint/fields/base-fields.yml
packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-expected.json
packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
packages/fortinet/data_stream/firewall/fields/base-fields.yml
packages/fortinet/data_stream/firewall/manifest.yml
packages/fortinet/data_stream/fortimail/_dev/test/pipeline/test-generated.log-expected.json
packages/fortinet/data_stream/fortimail/fields/base-fields.yml
packages/fortinet/data_stream/fortimanager/_dev/test/pipeline/test-generated.log-expected.json
packages/fortinet/data_stream/fortimanager/fields/base-fields.yml
packages/fortinet/docs/README.md
packages/fortinet/manifest.yml

Makes the package GA with v1.0.0 and sets event.module and event.dataset

[fortinet] Make fortinet package GA with v1.0.0

---

packages/rabbitmq/changelog.yml
packages/rabbitmq/data_stream/connection/fields/base-fields.yml
packages/rabbitmq/data_stream/exchange/fields/base-fields.yml
packages/rabbitmq/data_stream/log/fields/base-fields.yml
packages/rabbitmq/data_stream/node/fields/base-fields.yml
packages/rabbitmq/data_stream/queue/fields/base-fields.yml
packages/rabbitmq/docs/README.md
packages/rabbitmq/manifest.yml

[RabbitMQ] Set event.module and event.dataset

---

packages/iis/changelog.yml
packages/iis/data_stream/access/fields/base-fields.yml
packages/iis/data_stream/application_pool/fields/base-fields.yml
packages/iis/data_stream/error/fields/base-fields.yml
packages/iis/data_stream/webserver/fields/base-fields.yml
packages/iis/data_stream/website/fields/base-fields.yml
packages/iis/docs/README.md
packages/iis/manifest.yml

This PR adds event.module and event.dataset to the integration.

[iis] set event.module and event.dataset

---

packages/kafka/_dev/build/build.yml
packages/kafka/changelog.yml
packages/kafka/data_stream/broker/fields/base-fields.yml
packages/kafka/data_stream/broker/fields/ecs.yml
packages/kafka/data_stream/consumergroup/fields/base-fields.yml
packages/kafka/data_stream/consumergroup/fields/ecs.yml
packages/kafka/data_stream/log/fields/base-fields.yml
packages/kafka/data_stream/log/fields/ecs.yml
packages/kafka/data_stream/partition/fields/base-fields.yml
packages/kafka/data_stream/partition/fields/ecs.yml
packages/kafka/docs/README.md
packages/kafka/manifest.yml

* Add external ECS fields.
* Add module and dataset fields.

Add external and module fields for Kafka package

---

packages/postgresql/_dev/build/build.yml
packages/postgresql/changelog.yml
packages/postgresql/data_stream/activity/fields/base-fields.yml
packages/postgresql/data_stream/activity/fields/ecs.yml
packages/postgresql/data_stream/bgwriter/fields/base-fields.yml
packages/postgresql/data_stream/bgwriter/fields/ecs.yml
packages/postgresql/data_stream/database/fields/base-fields.yml
packages/postgresql/data_stream/database/fields/ecs.yml
packages/postgresql/data_stream/log/fields/base-fields.yml
packages/postgresql/data_stream/log/fields/ecs.yml
packages/postgresql/data_stream/statement/fields/base-fields.yml
packages/postgresql/data_stream/statement/fields/ecs.yml
packages/postgresql/docs/README.md
packages/postgresql/manifest.yml

* Add dataset and module fields to postgresql package.
* Add references to external ECS fields.
-

Add dataset and module fields to postgresql package

---

packages/bluecoat/changelog.yml
packages/bluecoat/data_stream/director/fields/base-fields.yml
packages/bluecoat/manifest.yml

[bluecoat] Set event.module and event.dataset

---

packages/cef/changelog.yml
packages/cef/data_stream/log/fields/base-fields.yml
packages/cef/docs/README.md
packages/cef/manifest.yml

[cef] Set event.module and event.dataset

---

packages/checkpoint/changelog.yml
packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
packages/checkpoint/data_stream/firewall/fields/base-fields.yml
packages/checkpoint/data_stream/firewall/fields/ecs.yml
packages/checkpoint/docs/README.md
packages/checkpoint/manifest.yml

[checkpoint] Set event.module and event.dataset

---

packages/cyberark/changelog.yml
packages/cyberark/data_stream/corepas/fields/base-fields.yml
packages/cyberark/manifest.yml

- Sets event.module nad event.dataset
- Adds deprecation notes to title and description

[cyberark] Set event.module and event.dataset

---

packages/cylance/changelog.yml
packages/cylance/data_stream/protect/fields/base-fields.yml
packages/cylance/manifest.yml

[cylance] Set event.module and event.dataset

---

packages/f5/changelog.yml
packages/f5/data_stream/bigipafm/fields/base-fields.yml
packages/f5/data_stream/bigipapm/fields/base-fields.yml
packages/f5/manifest.yml

[f5] Set event.module and event.dataset

---

packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/admin/fields/base-fields.yml
packages/google_workspace/data_stream/admin/fields/ecs.yml
packages/google_workspace/data_stream/drive/fields/base-fields.yml
packages/google_workspace/data_stream/drive/fields/ecs.yml
packages/google_workspace/data_stream/groups/fields/base-fields.yml
packages/google_workspace/data_stream/groups/fields/ecs.yml
packages/google_workspace/data_stream/login/fields/base-fields.yml
packages/google_workspace/data_stream/login/fields/ecs.yml
packages/google_workspace/data_stream/saml/fields/base-fields.yml
packages/google_workspace/data_stream/saml/fields/ecs.yml
packages/google_workspace/data_stream/user_accounts/fields/base-fields.yml
packages/google_workspace/data_stream/user_accounts/fields/ecs.yml
packages/google_workspace/docs/README.md
packages/google_workspace/manifest.yml

[google_workspace] Set event.module and event.dataset

---

packages/imperva/changelog.yml
packages/imperva/data_stream/securesphere/fields/base-fields.yml
packages/imperva/manifest.yml

[imperva] Set event.module and event.dataset

---

packages/infoblox/changelog.yml
packages/infoblox/data_stream/nios/fields/base-fields.yml
packages/infoblox/manifest.yml

[infoblox] Set event.module and event.dataset

---

packages/iptables/changelog.yml
packages/iptables/data_stream/log/fields/base-fields.yml
packages/iptables/data_stream/log/fields/ecs.yml
packages/iptables/docs/README.md
packages/iptables/manifest.yml

[iptables] Set event.module and event.dataset

---

packages/microsoft/changelog.yml
packages/microsoft/data_stream/defender_atp/fields/base-fields.yml
packages/microsoft/data_stream/defender_atp/fields/ecs.yml
packages/microsoft/data_stream/dhcp/fields/base-fields.yml
packages/microsoft/docs/README.md
packages/microsoft/manifest.yml

[microsoft] Set event.module and event.dataset

---

packages/netscout/changelog.yml
packages/netscout/data_stream/sightline/fields/base-fields.yml
packages/netscout/manifest.yml

[netscout] Set event.module and event.dataset

---

packages/proofpoint/changelog.yml
packages/proofpoint/data_stream/emailsecurity/fields/base-fields.yml
packages/proofpoint/manifest.yml

[proofpoint] Set event.module and event.dataset

---

packages/radware/changelog.yml
packages/radware/data_stream/defensepro/fields/base-fields.yml
packages/radware/manifest.yml

[radware] Set event.module and event.dataset

---

packages/santa/changelog.yml
packages/santa/data_stream/log/fields/base-fields.yml
packages/santa/data_stream/log/fields/ecs.yml
packages/santa/docs/README.md
packages/santa/manifest.yml

[santa] Set event.module and event.dataset

---

packages/sophos/changelog.yml
packages/sophos/data_stream/utm/fields/base-fields.yml
packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log-expected.json
packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
packages/sophos/data_stream/xg/fields/base-fields.yml
packages/sophos/data_stream/xg/fields/ecs.yml
packages/sophos/docs/README.md
packages/sophos/manifest.yml

[sophos] Set event.module and event.dataset

---

packages/winlog/changelog.yml
packages/winlog/data_stream/winlog/fields/base-fields.yml
packages/winlog/docs/README.md
packages/winlog/manifest.yml

[winlog] Set event.module and event.dataset

---

packages/zoom/changelog.yml
packages/zoom/data_stream/webhook/fields/base-fields.yml
packages/zoom/docs/README.md
packages/zoom/manifest.yml

[zoom] Set event.module and event.dataset

---

packages/zscaler/changelog.yml
packages/zscaler/data_stream/zia/fields/base-fields.yml
packages/zscaler/manifest.yml

[zscaler] Set event.module and event.dataset

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/053a0387-f3b5-4ba5-8245-8002cca2bd08.json
packages/security_detection_engine/kibana/security_rule/119c8877-8613-416d-a98a-96b6664ee73a5.json
packages/security_detection_engine/kibana/security_rule/12051077-0124-4394-9522-8f4f4db1d674.json
packages/security_detection_engine/kibana/security_rule/2045567e-b0af-444a-8c0b-0b6e2dae9e13.json
packages/security_detection_engine/kibana/security_rule/26f68dba-ce29-497b-8e13-b4fde1db5a2d.json
packages/security_detection_engine/kibana/security_rule/378f9024-8a0c-46a5-aa08-ce147ac73a4e.json
packages/security_detection_engine/kibana/security_rule/3efee4f0-182a-40a8-a835-102c68a4175d.json
packages/security_detection_engine/kibana/security_rule/5e87f165-45c2-4b80-bfa5-52822552c997.json
packages/security_detection_engine/kibana/security_rule/6506c9fd-229e-4722-8f0f-69be759afd2a.json
packages/security_detection_engine/kibana/security_rule/863cdf31-7fd3-41cf-a185-681237ea277b.json
packages/security_detection_engine/kibana/security_rule/8b4f0816-6a65-4630-86a6-c21c179c0d09.json
packages/security_detection_engine/kibana/security_rule/c1812764-0788-470f-8e74-eb4a14d47573.json
packages/security_detection_engine/kibana/security_rule/c292fa52-4115-408a-b897-e14f684b3cb7.json
packages/security_detection_engine/kibana/security_rule/c4818812-d44f-47be-aaef-4cfb2f9cc799.json
packages/security_detection_engine/kibana/security_rule/c82b2bd8-d701-420c-ba43-f11a155b681a.json
packages/security_detection_engine/kibana/security_rule/c8cccb06-faf2-4cd5-886e-2c9636cfcb87.json
packages/security_detection_engine/kibana/security_rule/d461fac0-43e8-49e2-85ea-3a58fe120b4f.json
packages/security_detection_engine/kibana/security_rule/e919611d-6b6f-493b-8314-7ed6ac2e413b.json
packages/security_detection_engine/kibana/security_rule/ee5300a7-7e31-4a72-a258-250abb8b3aa1.json
packages/security_detection_engine/kibana/security_rule/f30f3443-4fbb-4c27-ab89-c3ad49d62315.json
packages/security_detection_engine/kibana/security_rule/f766ffaf-9568-4909-b734-75d19b35cbf4.json
packages/security_detection_engine/manifest.yml

Another update to the Security Rules package
- Same as #1177 
- Same as #1177
None
None

[Security Rules] Update rules package to 0.13.2

---

.ci/Jenkinsfile

This PR bumps up Elastic stack versions used for testing.

Bump up Elastic stack for testing

---

CONTRIBUTING.md
README.md
docs/testing_and_validation.md

This PRs updates project documentation and describes test coverage.

Docs: test coverage

---

packages/auditd/_dev/build/build.yml
packages/auditd/changelog.yml
packages/auditd/data_stream/log/fields/agent.yml
packages/auditd/data_stream/log/fields/ecs.yml
packages/auditd/docs/README.md
packages/auditd/manifest.yml

auditd generate ecs.yml

---

packages/apache/_dev/build/build.yml
packages/apache/changelog.yml
packages/apache/data_stream/access/fields/agent.yml
packages/apache/data_stream/access/fields/ecs.yml
packages/apache/data_stream/error/fields/agent.yml
packages/apache/data_stream/error/fields/ecs.yml
packages/apache/data_stream/status/fields/ecs.yml
packages/apache/docs/README.md
packages/apache/manifest.yml
packages/auditd/data_stream/log/fields/ecs.yml

apache generate ecs.yml

---

packages/azure/_dev/build/build.yml
packages/azure/changelog.yml
packages/azure/docs/README.md
packages/azure/docs/activitylogs.md
packages/azure/docs/adlogs.md
packages/azure/docs/platformlogs.md
packages/azure/docs/springcloudlogs.md
packages/azure/manifest.yml

azure generate ecs.yml

---

packages/cef/_dev/build/build.yml
packages/cef/changelog.yml
packages/cef/data_stream/log/fields/agent.yml
packages/cef/data_stream/log/fields/ecs.yml
packages/cef/docs/README.md
packages/cef/manifest.yml

cef generate ecs.yml

---

packages/checkpoint/_dev/build/build.yml
packages/checkpoint/changelog.yml
packages/checkpoint/data_stream/firewall/fields/ecs.yml
packages/checkpoint/docs/README.md
packages/checkpoint/manifest.yml

checkpoint generate ecs.yml

---

packages/gcp/_dev/build/build.yml
packages/gcp/changelog.yml
packages/gcp/data_stream/audit/fields/agent.yml
packages/gcp/data_stream/audit/fields/ecs.yml
packages/gcp/data_stream/firewall/fields/agent.yml
packages/gcp/data_stream/firewall/fields/ecs.yml
packages/gcp/data_stream/vpcflow/fields/agent.yml
packages/gcp/data_stream/vpcflow/fields/ecs.yml
packages/gcp/docs/README.md
packages/gcp/manifest.yml

gcp generate ecs.yml

---

packages/haproxy/_dev/build/build.yml
packages/haproxy/changelog.yml
packages/haproxy/data_stream/info/fields/ecs.yml
packages/haproxy/data_stream/log/fields/agent.yml
packages/haproxy/data_stream/log/fields/ecs.yml
packages/haproxy/data_stream/stat/fields/ecs.yml
packages/haproxy/docs/README.md
packages/haproxy/manifest.yml

haproxy generate ecs.yml

---

packages/iis/_dev/build/build.yml
packages/iis/changelog.yml
packages/iis/data_stream/access/fields/ecs.yml
packages/iis/data_stream/application_pool/fields/ecs.yml
packages/iis/data_stream/error/fields/ecs.yml
packages/iis/data_stream/webserver/fields/ecs.yml
packages/iis/data_stream/website/fields/ecs.yml
packages/iis/docs/README.md
packages/iis/manifest.yml

iis generate ecs.yml

---

packages/nats/_dev/build/build.yml
packages/nats/changelog.yml
packages/nats/data_stream/connection/fields/ecs.yml
packages/nats/data_stream/connections/fields/ecs.yml
packages/nats/data_stream/log/fields/ecs.yml
packages/nats/data_stream/route/fields/ecs.yml
packages/nats/data_stream/routes/fields/ecs.yml
packages/nats/data_stream/stats/fields/ecs.yml
packages/nats/data_stream/subscriptions/fields/ecs.yml
packages/nats/docs/README.md
packages/nats/manifest.yml

nats generate ecs.yml

---

packages/iptables/_dev/build/build.yml
packages/iptables/changelog.yml
packages/iptables/data_stream/log/fields/agent.yml
packages/iptables/data_stream/log/fields/ecs.yml
packages/iptables/docs/README.md
packages/iptables/manifest.yml

iptables generate ecs.yml

---

packages/google_workspace/_dev/build/build.yml
packages/google_workspace/changelog.yml
packages/google_workspace/data_stream/admin/fields/agent.yml
packages/google_workspace/data_stream/admin/fields/ecs.yml
packages/google_workspace/data_stream/drive/fields/agent.yml
packages/google_workspace/data_stream/drive/fields/ecs.yml
packages/google_workspace/data_stream/groups/fields/agent.yml
packages/google_workspace/data_stream/groups/fields/ecs.yml
packages/google_workspace/data_stream/login/fields/agent.yml
packages/google_workspace/data_stream/login/fields/ecs.yml
packages/google_workspace/data_stream/saml/fields/agent.yml
packages/google_workspace/data_stream/saml/fields/ecs.yml
packages/google_workspace/data_stream/user_accounts/fields/agent.yml
packages/google_workspace/data_stream/user_accounts/fields/ecs.yml
packages/google_workspace/docs/README.md
packages/google_workspace/manifest.yml

google generate ecs.yml

---

packages/windows/_dev/build/build.yml
packages/windows/changelog.yml
packages/windows/data_stream/forwarded/fields/ecs.yml
packages/windows/data_stream/powershell/fields/ecs.yml
packages/windows/data_stream/powershell_operational/fields/ecs.yml
packages/windows/data_stream/sysmon_operational/fields/ecs.yml
packages/windows/docs/README.md
packages/windows/manifest.yml

windows generate ecs.yml

---

packages/traefik/_dev/build/build.yml
packages/traefik/changelog.yml
packages/traefik/data_stream/access/fields/ecs.yml
packages/traefik/data_stream/access/fields/fields.yml
packages/traefik/data_stream/health/fields/ecs.yml
packages/traefik/docs/README.md
packages/traefik/manifest.yml

traefik generate ecs.yml

---

packages/stan/_dev/build/build.yml
packages/stan/changelog.yml
packages/stan/data_stream/channels/fields/ecs.yml
packages/stan/data_stream/log/fields/ecs.yml
packages/stan/data_stream/stats/fields/ecs.yml
packages/stan/data_stream/subscriptions/fields/ecs.yml
packages/stan/docs/README.md
packages/stan/manifest.yml

stan generate ecs.yml

---

packages/santa/_dev/build/build.yml
packages/santa/changelog.yml
packages/santa/data_stream/log/fields/agent.yml
packages/santa/data_stream/log/fields/ecs.yml
packages/santa/docs/README.md
packages/santa/manifest.yml

santa generate ecs.yml

---

packages/redis/_dev/build/build.yml
packages/redis/changelog.yml
packages/redis/data_stream/info/fields/ecs.yml
packages/redis/data_stream/key/fields/ecs.yml
packages/redis/data_stream/keyspace/fields/ecs.yml
packages/redis/data_stream/log/fields/ecs.yml
packages/redis/docs/README.md
packages/redis/manifest.yml

redis generate ecs.yml

---

packages/radware/_dev/build/build.yml
packages/radware/changelog.yml
packages/radware/data_stream/defensepro/fields/ecs.yml
packages/radware/data_stream/defensepro/fields/fields.yml
packages/radware/manifest.yml

radware generate ecs.yml

---

packages/rabbitmq/_dev/build/build.yml
packages/rabbitmq/changelog.yml
packages/rabbitmq/data_stream/connection/fields/ecs.yml
packages/rabbitmq/data_stream/exchange/fields/ecs.yml
packages/rabbitmq/data_stream/log/fields/ecs.yml
packages/rabbitmq/data_stream/node/fields/ecs.yml
packages/rabbitmq/data_stream/queue/fields/ecs.yml
packages/rabbitmq/docs/README.md
packages/rabbitmq/manifest.yml

rabbitmq generate ecs.yml

---

packages/okta/_dev/build/build.yml
packages/okta/changelog.yml
packages/okta/data_stream/system/fields/ecs.yml
packages/okta/docs/README.md
packages/okta/manifest.yml

okta generate ecs.yml

---

packages/o365/_dev/build/build.yml
packages/o365/changelog.yml
packages/o365/data_stream/audit/fields/ecs.yml
packages/o365/docs/README.md
packages/o365/manifest.yml

o365 generate ecs.yml

---

packages/nginx/_dev/build/build.yml
packages/nginx/changelog.yml
packages/nginx/data_stream/access/fields/agent.yml
packages/nginx/data_stream/access/fields/ecs.yml
packages/nginx/data_stream/error/fields/agent.yml
packages/nginx/data_stream/error/fields/ecs.yml
packages/nginx/data_stream/stubstatus/fields/ecs.yml
packages/nginx/docs/README.md
packages/nginx/manifest.yml

nginx generate ecs.yml

---

packages/barracuda/_dev/build/build.yml
packages/barracuda/changelog.yml
packages/barracuda/data_stream/spamfirewall/fields/ecs.yml
packages/barracuda/data_stream/spamfirewall/fields/fields.yml
packages/barracuda/data_stream/waf/fields/ecs.yml
packages/barracuda/data_stream/waf/fields/fields.yml
packages/barracuda/manifest.yml

barracuda generate ecs.yml

---

packages/bluecoat/_dev/build/build.yml
packages/bluecoat/changelog.yml
packages/bluecoat/data_stream/director/fields/ecs.yml
packages/bluecoat/data_stream/director/fields/fields.yml
packages/bluecoat/manifest.yml

bluecoat generate ecs.yml

---

packages/cylance/_dev/build/build.yml
packages/cylance/changelog.yml
packages/cylance/data_stream/protect/fields/ecs.yml
packages/cylance/data_stream/protect/fields/fields.yml
packages/cylance/manifest.yml

cylance generate ecs.yml

---

packages/cyberark/_dev/build/build.yml
packages/cyberark/changelog.yml
packages/cyberark/data_stream/corepas/fields/ecs.yml
packages/cyberark/data_stream/corepas/fields/fields.yml
packages/cyberark/manifest.yml

cyberark generate ecs.yml

---

packages/f5/_dev/build/build.yml
packages/f5/changelog.yml
packages/f5/data_stream/bigipafm/fields/ecs.yml
packages/f5/data_stream/bigipafm/fields/fields.yml
packages/f5/data_stream/bigipapm/fields/ecs.yml
packages/f5/data_stream/bigipapm/fields/fields.yml
packages/f5/manifest.yml

f5 generate ecs.yml

---

packages/imperva/_dev/build/build.yml
packages/imperva/changelog.yml
packages/imperva/data_stream/securesphere/fields/ecs.yml
packages/imperva/data_stream/securesphere/fields/fields.yml
packages/imperva/manifest.yml

imperva generate ecs.yml

---

packages/infoblox/_dev/build/build.yml
packages/infoblox/changelog.yml
packages/infoblox/data_stream/nios/fields/ecs.yml
packages/infoblox/data_stream/nios/fields/fields.yml
packages/infoblox/manifest.yml

infoblox generate ecs.yml

---

packages/netscout/_dev/build/build.yml
packages/netscout/changelog.yml
packages/netscout/data_stream/sightline/fields/ecs.yml
packages/netscout/data_stream/sightline/fields/fields.yml
packages/netscout/manifest.yml

netscout generate ecs.yml

---

packages/tomcat/data_stream/log/sample_event.json

- Clone Branch and move to tomcat package directory.
- Run following command to verify sample_event.json file. `elastic-package test static -v`
- Related #1439

#1439-sample_event-tomcat

---

dev/import-beats/kibana.go

Add support for ndjson dashboards in beats importer.
Implementation for old format used kibana APIs to convert to saved objects and then it applied some transformations on these objects. Implementation added here applies the transformations directly on the objects in the ndjson files.
- Fixes #1536.

Support ndjson dashboards in beats importer

---

packages/proofpoint/_dev/build/build.yml
packages/proofpoint/changelog.yml
packages/proofpoint/data_stream/emailsecurity/fields/ecs.yml
packages/proofpoint/data_stream/emailsecurity/fields/fields.yml
packages/proofpoint/manifest.yml

proofpoint generate ecs.yml

---

packages/sophos/_dev/build/build.yml
packages/sophos/changelog.yml
packages/sophos/data_stream/utm/fields/ecs.yml
packages/sophos/data_stream/utm/fields/fields.yml
packages/sophos/data_stream/xg/fields/agent.yml
packages/sophos/data_stream/xg/fields/ecs.yml
packages/sophos/data_stream/xg/fields/fields.yml
packages/sophos/docs/README.md
packages/sophos/manifest.yml

sophos generate ecs.yml

---

packages/squid/_dev/build/build.yml
packages/squid/changelog.yml
packages/squid/data_stream/log/fields/ecs.yml
packages/squid/data_stream/log/fields/fields.yml
packages/squid/manifest.yml

squid generate ecs.yml

---

packages/zscaler/_dev/build/build.yml
packages/zscaler/changelog.yml
packages/zscaler/data_stream/zia/fields/ecs.yml
packages/zscaler/data_stream/zia/fields/fields.yml
packages/zscaler/manifest.yml

zscaler generate ecs.yml

---

packages/tomcat/_dev/build/build.yml
packages/tomcat/changelog.yml
packages/tomcat/data_stream/log/fields/ecs.yml
packages/tomcat/data_stream/log/fields/fields.yml
packages/tomcat/docs/README.md
packages/tomcat/manifest.yml

tomcat generate ecs.yml

---

packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json

Remove default filter on host.name  from elastic agent dashboard. Added by mistake in #1529

[Fleet] Remove default filter from elastic agent

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/data_stream/result/fields/osquery.yml
packages/osquery_manager/docs/README.md
packages/osquery_manager/manifest.yml

Updates mapping and readme for osquery 4.9.0

Update mapping and readme for osquery 4.9.0

---

dev/import-beats/kibana.go

Follow up to https://github.com/elastic/beats/pull/27553, to support the changes in format introduced there. It replaces previous changes to support NDJSON format introduced in https://github.com/elastic/integrations/pull/1537.
Old format is still supported.
- Import a module from Beats, e.g. `PACKAGES=postgresql mage importBeats`.
- Check if dashboards are properly migrated.
- Relates to https://github.com/elastic/beats/pull/27553
- Replaces https://github.com/elastic/integrations/pull/1537

Support decoded saved objects when importing from Beats

---

.ci/Jenkinsfile
.ci/jobs/integrations-daily.yml
.ci/schedule-daily.groovy

Add parameter to Jenkinsfile to select a version of the stack to use for testing.
- Needed to detect issues with 7.x after #1541.
- Fixes #1581.

Add parameter to choose stack version to use in CI

---

.ci/schedule-daily.groovy

`https://beats-ci.elastic.co/job/Ingest-manager/job/Integrations/job/master/` does not exist
`https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/` does exist

Fix daily job name

---

docs/developer_workflow_fleet_ui.md

This PR adds a markdown with instructions on how to set up a development environment for Fleet UI.
A lot of information in this markdown have been taken from https://docs.elastic.dev/kibana-dev-docs/tutorial/setup-dev-env and https://github.com/elastic/kibana/tree/master/x-pack/plugins/fleet#running-fleet-server-locally-in-a-container

Add markdown with workflow for fleet ui development

---

packages/kubernetes/changelog.yml
packages/kubernetes/data_stream/apiserver/manifest.yml
packages/kubernetes/data_stream/container/manifest.yml
packages/kubernetes/data_stream/controllermanager/manifest.yml
packages/kubernetes/data_stream/event/manifest.yml
packages/kubernetes/data_stream/node/manifest.yml
packages/kubernetes/data_stream/pod/manifest.yml
packages/kubernetes/data_stream/proxy/manifest.yml
packages/kubernetes/data_stream/scheduler/manifest.yml
packages/kubernetes/data_stream/state_container/manifest.yml
packages/kubernetes/data_stream/state_cronjob/manifest.yml
packages/kubernetes/data_stream/state_daemonset/manifest.yml
packages/kubernetes/data_stream/state_deployment/manifest.yml
packages/kubernetes/data_stream/state_job/manifest.yml
packages/kubernetes/data_stream/state_node/manifest.yml
packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
packages/kubernetes/data_stream/state_pod/manifest.yml
packages/kubernetes/data_stream/state_replicaset/manifest.yml
packages/kubernetes/data_stream/state_resourcequota/manifest.yml
packages/kubernetes/data_stream/state_service/manifest.yml
packages/kubernetes/data_stream/state_statefulset/manifest.yml
packages/kubernetes/data_stream/state_storageclass/manifest.yml
packages/kubernetes/data_stream/system/manifest.yml
packages/kubernetes/data_stream/volume/manifest.yml
packages/kubernetes/manifest.yml

Make Kubernetes GA

---

packages/zookeeper/changelog.yml
packages/zookeeper/data_stream/connection/manifest.yml
packages/zookeeper/data_stream/mntr/manifest.yml
packages/zookeeper/data_stream/server/manifest.yml
packages/zookeeper/manifest.yml

Make Zookeeper GA

---

packages/rabbitmq/changelog.yml
packages/rabbitmq/data_stream/connection/manifest.yml
packages/rabbitmq/data_stream/exchange/manifest.yml
packages/rabbitmq/data_stream/log/manifest.yml
packages/rabbitmq/data_stream/node/manifest.yml
packages/rabbitmq/data_stream/queue/manifest.yml
packages/rabbitmq/manifest.yml

Make RabbitMQ GA

---

packages/mysql/changelog.yml
packages/mysql/data_stream/error/manifest.yml
packages/mysql/data_stream/galera_status/manifest.yml
packages/mysql/data_stream/performance/manifest.yml
packages/mysql/data_stream/slowlog/manifest.yml
packages/mysql/data_stream/status/manifest.yml
packages/mysql/manifest.yml

Make MySQL GA

---

packages/redis/changelog.yml
packages/redis/data_stream/info/manifest.yml
packages/redis/data_stream/key/manifest.yml
packages/redis/data_stream/keyspace/manifest.yml
packages/redis/data_stream/log/manifest.yml
packages/redis/data_stream/slowlog/manifest.yml
packages/redis/manifest.yml

Make Redis GA

---

packages/postgresql/changelog.yml
packages/postgresql/data_stream/activity/manifest.yml
packages/postgresql/data_stream/bgwriter/manifest.yml
packages/postgresql/data_stream/database/manifest.yml
packages/postgresql/data_stream/log/manifest.yml
packages/postgresql/data_stream/statement/manifest.yml
packages/postgresql/manifest.yml

Make Postresql GA

---

packages/mongodb/changelog.yml
packages/mongodb/data_stream/collstats/manifest.yml
packages/mongodb/data_stream/dbstats/manifest.yml
packages/mongodb/data_stream/log/manifest.yml
packages/mongodb/data_stream/metrics/manifest.yml
packages/mongodb/data_stream/replstatus/manifest.yml
packages/mongodb/data_stream/status/manifest.yml
packages/mongodb/manifest.yml

Make Mongodb GA

---

packages/tomcat/changelog.yml
packages/tomcat/data_stream/log/manifest.yml
packages/tomcat/manifest.yml

Make Tomcat GA

---

packages/traefik/changelog.yml
packages/traefik/data_stream/access/manifest.yml
packages/traefik/data_stream/health/manifest.yml
packages/traefik/manifest.yml

Make Traefik GA

---

packages/nats/changelog.yml
packages/nats/data_stream/connection/manifest.yml
packages/nats/data_stream/connections/manifest.yml
packages/nats/data_stream/log/manifest.yml
packages/nats/data_stream/route/manifest.yml
packages/nats/data_stream/routes/manifest.yml
packages/nats/data_stream/stats/manifest.yml
packages/nats/data_stream/subscriptions/manifest.yml
packages/nats/manifest.yml

Make NATS GA

---

packages/stan/changelog.yml
packages/stan/data_stream/channels/manifest.yml
packages/stan/data_stream/log/manifest.yml
packages/stan/data_stream/stats/manifest.yml
packages/stan/data_stream/subscriptions/manifest.yml
packages/stan/manifest.yml

Make Stan GA

---

packages/zoom/changelog.yml
packages/zoom/data_stream/webhook/manifest.yml
packages/zoom/manifest.yml

Updates the Zoom package from Beta to GA.

Zoom: Release version 1.0.0 as GA

---

packages/microsoft/_dev/deploy/docker/docker-compose.yml
packages/microsoft/_dev/deploy/docker/http-mock-config.yml
packages/microsoft/changelog.yml
packages/microsoft/data_stream/defender_atp/_dev/test/system/test-httpjson-config.yml
packages/microsoft/data_stream/defender_atp/agent/stream/httpjson.yml.hbs
packages/microsoft/data_stream/defender_atp/fields/fields.yml
packages/microsoft/data_stream/defender_atp/manifest.yml
packages/microsoft/manifest.yml

GA Microsoft Defender integration
- add httpjson tests
- make login_url and request_url configurable for testing, also allows
geo located servers.
- remove beta & experimental tags
- kibana.version to 7.15.0
```
```

GA Microsoft Defender integration

---

packages/bluecoat/changelog.yml
packages/bluecoat/manifest.yml

updates description & version for bluecoat integration.

[bluecoat] update title and description

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/manifest.yml

updates description & version for cisco_asa integration.

[cisco_asa] update title and description

---

packages/cisco_ios/changelog.yml
packages/cisco_ios/manifest.yml

updates description & version for cisco_ios integration.

[cisco_ios] update title and description

---

packages/cisco_secure_endpoint/changelog.yml
packages/cisco_secure_endpoint/manifest.yml

updates description & version for cisco_secure_endpoint integration.

[cisco_secure_endpoint] update title and description

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/manifest.yml

updates description & version for crowdstrike integration.

[crowdstrike] update title and description

---

packages/imperva/changelog.yml
packages/imperva/manifest.yml

updates description & version for imperva integration.

[imperva] update title and description

---

packages/okta/changelog.yml
packages/okta/manifest.yml

updates description & version for okta integration.

[okta] update title and description

---

packages/radware/changelog.yml
packages/radware/manifest.yml

updates description & version for radware integration.

[radware] update title and description

---

packages/squid/changelog.yml
packages/squid/manifest.yml

updates description & version for squid integration.

[squid] update title and description

---

packages/suricata/changelog.yml
packages/suricata/manifest.yml

updates description & version for suricata integration.

[suricata] update title and description

---

packages/tomcat/changelog.yml
packages/tomcat/manifest.yml

updates description & version for tomcat integration.

[tomcat] update title and description

---

packages/winlog/changelog.yml
packages/winlog/manifest.yml

updates description & version for winlog integration.

[winlog] update title and description

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/manifest.yml

updates the description
* #1900

update integration description

---

packages/synthetics/changelog.yml
packages/synthetics/docs/README.md
packages/synthetics/manifest.yml

Fixes elastic/uptime#376
Updates README to include tutorial documentation.
Current content.
```
React to availability issues across your apps and services before they affect users.
While a service being "up" or "down" might seem binary, the data surrounding each data point isn't. Give your team the context they need to go well beyond status codes. With Elastic Uptime, powered by open source Heartbeat(opens in a new tab or window), your availability data works in concert with rich context provided by logs(opens in a new tab or window), metrics(opens in a new tab or window), and APM(opens in a new tab or window) — making it simpler to connect the dots, correlate activity, and solve problems quickly.
Organizations need to track the performance and availability of a rapidly expanding list of …
```

[Synthetics] update README to include instructions

---

packages/windows/_dev/build/docs/README.md
packages/windows/changelog.yml
packages/windows/docs/README.md
packages/windows/manifest.yml
packages/winlog/_dev/build/docs/README.md
packages/winlog/changelog.yml
packages/winlog/docs/README.md
packages/winlog/manifest.yml

Updates the Splunk input description for the Windows integrations to
give more information and links to configuration.
- Closes #1563

update splunk input desc for windows integrations

---

packages/kibana/changelog.yml
packages/kibana/manifest.yml

kibana: changes for unified integration UI

---

packages/linux/changelog.yml
packages/linux/manifest.yml

linux: changes for unified integration UI

---

packages/zscaler/changelog.yml
packages/zscaler/manifest.yml

zscaler: changes for unified integration UI

---

packages/barracuda/changelog.yml
packages/barracuda/manifest.yml

barracuda: changes for unified integration UI

---

packages/bluecoat/changelog.yml
packages/bluecoat/manifest.yml

bluecoat: changes for unified integration UI

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/manifest.yml

crowdstrike: changes for unified integration UI

---

packages/log/changelog.yml
packages/log/manifest.yml

log: changes for unified integration UI

---

packages/logstash/changelog.yml
packages/logstash/manifest.yml

logstash: changes for unified integration UI

---

packages/netscout/changelog.yml
packages/netscout/manifest.yml
packages/zeek/changelog.yml

netscout: changes for unified integration UI

---

packages/synthetics/changelog.yml
packages/synthetics/manifest.yml

synthetics: changes for unified integration UI

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/manifest.yml

panw_cortex_xdr: changes for unified integration UI

---

packages/zerofox/changelog.yml
packages/zerofox/manifest.yml

zerofox: changes for unified integration UI

---

packages/nginx/changelog.yml
packages/nginx/manifest.yml

nginx: changes for unified integration UI

---

packages/zeek/changelog.yml
packages/zeek/manifest.yml

zeek: changes for unified integration UI

---

packages/zoom/changelog.yml
packages/zoom/manifest.yml

zoom: changes for unified integration UI

---

packages/cloudflare/changelog.yml
packages/cloudflare/manifest.yml

cloudflare: changes for unified integration UI

---

packages/fortinet/changelog.yml
packages/fortinet/manifest.yml

fortinet: changes for unified integration UI

---

packages/pfsense/changelog.yml
packages/pfsense/manifest.yml

pfsense: changes for unified integration UI

---

packages/proofpoint/changelog.yml
packages/proofpoint/manifest.yml

proofpoint: changes for unified integration UI

---

packages/radware/changelog.yml
packages/radware/manifest.yml

radware: changes for unified integration UI

---

packages/santa/changelog.yml
packages/santa/manifest.yml

santa: changes for unified integration UI

---

packages/sonicwall/changelog.yml
packages/sonicwall/manifest.yml

sonicwall: changes for unified integration UI

---

packages/sophos/changelog.yml
packages/sophos/manifest.yml

sophos: changes for unified integration UI

---

packages/suricata/changelog.yml
packages/suricata/manifest.yml

suricata: changes for unified integration UI

---

packages/tomcat/changelog.yml
packages/tomcat/manifest.yml

tomcat: changes for unified integration UI

---

packages/winlog/changelog.yml
packages/winlog/manifest.yml

winlog: changes for unified integration UI

---

packages/logstash/changelog.yml
packages/logstash/data_stream/log/manifest.yml
packages/logstash/data_stream/node/manifest.yml
packages/logstash/data_stream/node_stats/manifest.yml
packages/logstash/data_stream/slowlog/manifest.yml
packages/logstash/manifest.yml

Revert logstash package to experimental atm

Revert Logstash experimental

---

packages/squid/changelog.yml
packages/squid/manifest.yml

squid: changes for unified integration UI

---

packages/network_traffic/changelog.yml
packages/network_traffic/manifest.yml

network_traffic: changes for unified integration UI

---

packages/google_workspace/changelog.yml
packages/google_workspace/manifest.yml

google_workspace: changes for unified integration UI

---

packages/f5/changelog.yml
packages/f5/manifest.yml

f5: changes for unified integration UI

---

packages/osquery/changelog.yml
packages/osquery/manifest.yml

osquery: changes for unified integration UI

---

packages/juniper/changelog.yml
packages/juniper/manifest.yml

juniper: changes for unified integration UI

---

packages/imperva/changelog.yml
packages/imperva/manifest.yml

imperva: changes for unified integration UI

---

packages/infoblox/changelog.yml
packages/infoblox/manifest.yml

infoblox: changes for unified integration UI

---

packages/iptables/changelog.yml
packages/iptables/manifest.yml

iptables: changes for unified integration UI

---

packages/okta/changelog.yml
packages/okta/manifest.yml

okta: changes for unified integration UI

---

packages/o365/changelog.yml
packages/o365/manifest.yml

o365: changes for unified integration UI

---

packages/stan/changelog.yml
packages/stan/manifest.yml

stan: changes for unified integration UI

---

packages/system/changelog.yml
packages/system/manifest.yml

system: changes for unified integration UI

---

packages/netflow/changelog.yml
packages/netflow/manifest.yml

netflow: changes for unified integration UI

---

packages/iis/changelog.yml
packages/iis/manifest.yml

iis: changes for unified integration UI

---

packages/system/changelog.yml
packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
packages/system/manifest.yml

[system] Add missing null check in security pipeline

---

packages/hashicorp_vault/changelog.yml
packages/hashicorp_vault/manifest.yml

hashicorp_vault: changes for unified integration UI

---

packages/windows/changelog.yml
packages/windows/manifest.yml

windows: changes for unified integration UI

---

packages/ti_abusech/changelog.yml
packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
packages/ti_abusech/data_stream/malware/manifest.yml
packages/ti_abusech/data_stream/malware/sample_event.json
packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
packages/ti_abusech/data_stream/malwarebazaar/elasticsearch/ingest_pipeline/default.yml
packages/ti_abusech/data_stream/malwarebazaar/manifest.yml
packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
packages/ti_abusech/data_stream/url/manifest.yml
packages/ti_abusech/data_stream/url/sample_event.json
packages/ti_abusech/kibana/dashboard/ti_abusech-2457fb50-3bc3-11ec-ae8c-7d00429ad420.json
packages/ti_abusech/kibana/dashboard/ti_abusech-6a90c980-3b32-11ec-ae50-2fdf1e96c6a6.json
packages/ti_abusech/kibana/dashboard/ti_abusech-c0d8d1f0-3b20-11ec-ae50-2fdf1e96c6a6.json
packages/ti_abusech/kibana/tag/ti_abusech-320c5c80-3b0c-11ec-ae50-2fdf1e96c6a6.json
packages/ti_abusech/kibana/tag/ti_abusech-73511520-3b32-11ec-ae50-2fdf1e96c6a6.json
packages/ti_abusech/manifest.yml

This PR adds dashboards to the AbuseCH package, and performs some minor tweaks to the integration pipeline.

[AbuseCH Package] Adding dashboards and minor tweaks

---

packages/cylance/changelog.yml
packages/cylance/manifest.yml

cylance: changes for unified integration UI

---

packages/fleet_server/changelog.yml
packages/fleet_server/manifest.yml

fleet_server: changes for unified integration UI

---

packages/cyberarkpas/changelog.yml
packages/cyberarkpas/manifest.yml

cyberarkpas: changes for unified integration UI

---

packages/nats/changelog.yml
packages/nats/manifest.yml

Releases nats package for v8.0.0

Release nats package for v8.0.0

---

packages/nginx/changelog.yml
packages/nginx/manifest.yml

Release nginx package for v8.0.0

Release nginx package for v8.0.0

---

packages/azure/changelog.yml
packages/azure/manifest.yml

Release azure package for v8.0.0

Release azure package for v8.0.0

---

packages/cassandra/changelog.yml
packages/cassandra/manifest.yml

Release cassandra package for v8.0.0

Release cassandra package for v8.0.0

---

packages/nginx_ingress_controller/changelog.yml
packages/nginx_ingress_controller/manifest.yml

Release nginx_ingress_controller package for v8.0.0

Release nginx_ingress_controller package for v8.0.0

---

packages/prometheus/changelog.yml
packages/prometheus/manifest.yml

Releases prometheus package for v8.0.0

Release prometheus package for v8.0.0

---

packages/haproxy/changelog.yml
packages/haproxy/manifest.yml

Releases haproxy package for v8.0.0

Release haproxy package for v8.0.0

---

packages/traefik/changelog.yml
packages/traefik/manifest.yml

Release traefik package for 8.0.0

---

packages/postgresql/changelog.yml
packages/postgresql/manifest.yml

Release postgresql package for 8.0.0

---

packages/mongodb/changelog.yml
packages/mongodb/manifest.yml

Release mongodb package for v8.0.0

Release mongodb package for v8.0.0

---

packages/aws/changelog.yml
packages/aws/manifest.yml

This PR is to release the `aws` package for Kibana 8.0.0.

Release AWS Package for Kibana 8

---

packages/synthetics/changelog.yml
packages/synthetics/manifest.yml

Make it compatible with 7.16 and 8.x

[Synthetics] update compatibility of synthetics package

---

packages/mysql/changelog.yml
packages/mysql/manifest.yml

Release mysql package for v8.0.0

---

packages/redis/changelog.yml
packages/redis/manifest.yml

Release redis package for v8.0.0

---

packages/azure_billing/changelog.yml
packages/azure_billing/manifest.yml

This PR is to release the `azure_billing` package for Kibana 8.0.0.

Release Azure billing Package for Kibana 8

---

packages/azure_application_insights/changelog.yml
packages/azure_application_insights/manifest.yml

This PR is to release the `azure_application_insights` package for Kibana 8.0.0.

Release Azure application insights Package for Kibana 8

---

packages/activemq/changelog.yml
packages/activemq/manifest.yml

This PR is to release the `activemq` package for Kibana 8.0.0.

Release activemq package for Kibana 8

---

packages/zookeeper/changelog.yml
packages/zookeeper/manifest.yml

This PR is to release the `zookeeper` package for Kibana 8.0.0.

Release zookeeper package for Kibana 8

---

packages/journald/changelog.yml
packages/journald/manifest.yml

Set description to "Collect logs from journald with Elastic Agent."
Relates: #1901
- Relates: #1901

[journald] Update package description

---

packages/ti_abusech/changelog.yml
packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
packages/ti_abusech/data_stream/malware/fields/base-fields.yml
packages/ti_abusech/data_stream/malware/sample_event.json
packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
packages/ti_abusech/data_stream/malwarebazaar/fields/base-fields.yml
packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
packages/ti_abusech/data_stream/url/fields/base-fields.yml
packages/ti_abusech/data_stream/url/sample_event.json
packages/ti_abusech/docs/README.md
packages/ti_abusech/manifest.yml

Updates a typo in base-fields.yml for threat ECS fields

[AbuseCH] Update typo on base-fields.yml

---

.ci/Jenkinsfile

This PR adjusts the Jenkinsfile to prevent bug: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/1346/pipeline/

Fix: isPrAffected forbids 7x package on 8x stack

---

packages/azure/changelog.yml
packages/azure/manifest.yml
packages/azure_application_insights/changelog.yml
packages/azure_application_insights/manifest.yml
packages/azure_billing/changelog.yml
packages/azure_billing/manifest.yml
packages/azure_metrics/changelog.yml
packages/azure_metrics/manifest.yml

This PR is to move azure packages to GA.

Move azure packages to GA

---

packages/osquery_manager/changelog.yml
packages/osquery_manager/manifest.yml

[osquery_manager] GA

---

packages/log/changelog.yml
packages/log/manifest.yml

Enhancement
Release Custom Logs as GA
-
Closes #2195

Release Custom Logs as GA

---

packages/aws/_dev/build/docs/README.md
packages/aws/changelog.yml
packages/aws/docs/README.md
packages/aws/manifest.yml

This PR is to update the AWS permission list for enabling all metrics and logs collection in AWS integration.

Update AWS permissions for enabling all metrics and logs collection

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/manifest.yml
packages/cisco_asa/manifest.yml

This adds documentation to the listen address config option.
Can this go into 8.1?
- Closes #2647

cisco_asa: clarify config option

---

packages/synthetics/changelog.yml

Synthetics - Update changelog.yml

---

packages/auth0/changelog.yml

Update missing PR# in changelog.

[auth0]: Update changelog entry

---

packages/zscaler_zpa/_dev/build/docs/README.md
packages/zscaler_zpa/changelog.yml
packages/zscaler_zpa/docs/README.md
packages/zscaler_zpa/manifest.yml

- Updated the section describing the Zscaler ZPA setup process. 
- Move to integrations/packages/zscaler_zpa directory.
`elastic-package test`
- N/A

[zscaler_zpa] Updated user-guide of the package

---

packages/panw/_dev/build/docs/README.md
packages/panw/changelog.yml
packages/panw/docs/README.md
packages/panw/manifest.yml

panw: improve package doc text

---

.ci/Jenkinsfile

Fix https://github.com/elastic/integrations/issues/2788

Changes in CODEOWNERS don't trigger integration builds

---

packages/aws_logs/changelog.yml
packages/aws_logs/manifest.yml

This PR is to add kibana version condition for aws_logs package.

[aws_logs] Add conditions for kibana version

---

packages/aws/changelog.yml
packages/aws/kibana/dashboard/aws-3367c170-921f-11e9-aa19-159bf182e06f.json
packages/aws/manifest.yml

Reverts elastic/integrations#2826

Revert "[aws] fix missing reference to metricbeat-"

---

docs/developer_workflow_promote_release_integration.md

Updates some README docs about how to promote changes to an integration/package.

Updating package promotion docs

---

packages/o365/changelog.yml
packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-sts-logon-events.json-expected.json
packages/o365/data_stream/audit/_dev/test/pipeline/test-parameter-string.json-expected.json
packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/o365/manifest.yml

This fixes ECS compliance for the o365 package.
- Closes #3048

o365: replace invalid field value from pipeline

---

packages/o365/changelog.yml

Update PR link to include PR number

[o365]: Update PR link in changelog

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
packages/cisco_duo/manifest.yml

Simplifies the grok pattern for ports.
- Relates https://github.com/elastic/integrations/pull/3117#discussion_r855626013.

cisco_duo: simplify grok expression for handling ports

---

packages/carbon_black_cloud/_dev/build/docs/README.md
packages/carbon_black_cloud/changelog.yml
packages/carbon_black_cloud/docs/README.md
packages/carbon_black_cloud/manifest.yml

This PR updates the title to `VMware Carbon Black Cloud` from `Carbon Black Cloud` to make it consistent with other VMware Carbon Black products.
- Closes #3195

[Carbon Black Cloud] Update the title of CBC connector.

---

packages/kibana/_dev/build/docs/README.md
packages/kibana/changelog.yml
packages/kibana/docs/README.md
packages/kibana/manifest.yml

added link to Kibana documentation
Type of change
- Enhancement
added link to Kibana documentation
-

update Kibana readme

---

packages/cis_kubernetes_benchmark/kibana/index_pattern/cloud_security_posture-303eea10-c475-11ec-af18-c5b9b437dbbe.json
packages/cloud_security_posture/kibana/index_pattern/cloud_security_posture-303eea10-c475-11ec-af18-c5b9b437dbbe.json

Add a "latest findings" data view to the CSP integrations

[Cloud Posture] Add latest findings data view

---

packages/1password/_dev/build/docs/README.md
packages/1password/changelog.yml
packages/1password/docs/README.md
packages/1password/kibana/dashboard/1password-item-usages-full-dashboard.json
packages/1password/kibana/dashboard/1password-signin-attempts-full-dashboard.json
packages/1password/kibana/map/1password-item-usages-source-IPs-map.json
packages/1password/kibana/map/1password-signin-attempts-source-IPs-map.json
packages/1password/kibana/search/1password-all-events.json
packages/1password/kibana/search/1password-item-usages.json
packages/1password/kibana/search/1password-signin-attempts.json
packages/1password/kibana/visualization/1password-item-usages-hot-items.json
packages/1password/kibana/visualization/1password-item-usages-hot-users.json
packages/1password/kibana/visualization/1password-item-usages-hot-vaults.json
packages/1password/kibana/visualization/1password-item-usages-over-time.json
packages/1password/kibana/visualization/1password-signin-attempts-categories-over-time.json
packages/1password/kibana/visualization/1password-signin-attempts-count-over-time.json
packages/1password/kibana/visualization/1password-signin-attempts-failed-gauge.json
packages/1password/kibana/visualization/1password-signin-attempts-hot-users.json
packages/1password/manifest.yml

This changes the name of the package to just be the name of the vendor.
- Closes #2722

1password: change name of package "1Password Event Reporting" => "1Password"

---

packages/panw/changelog.yml
packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-globalprotect-sample.log-expected.json
packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
packages/panw/manifest.yml

Add GeoIP/ASN data for `*.nat.ip` fields
- Closes #3290

[PANW] Add GeoIP/ASN data for `*.nat.ip` fields

---

.ci/packer_cache.sh

Cache docker images in the CI workers to speed up the build process

packer_cache: pull and tag middleware/weblogic:12.2.1.3-dev

---

packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-expected.json
packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log-expected.json
packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log-expected.json
packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.yml

This commit fixes the ECS schema on system/auth package.
~~## How to test this PR locally~~
- Closes #3051

fix ECS schema on system package

---

packages/symantec_endpoint/changelog.yml
packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-traffic.log-expected.json
packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-remove-mapped-fields.log-expected.json
packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc3164.log-expected.json
packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc5424.log-expected.json
packages/symantec_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/symantec_endpoint/data_stream/log/sample_event.json
packages/symantec_endpoint/docs/README.md
packages/symantec_endpoint/manifest.yml

This cleans up items missed in the previous pass in #3244. Now verified by the tool's check.
- Closes #3050

symantec_endpoint: use valid ECS values for fields

---

packages/fortinet/_dev/deploy/docker/docker-compose.yml
packages/fortinet/changelog.yml
packages/fortinet/data_stream/firewall/_dev/test/system/test-tls-config.yml
packages/fortinet/data_stream/firewall/agent/stream/tcp.yml.hbs
packages/fortinet/data_stream/firewall/manifest.yml
packages/fortinet/manifest.yml

- Add TLS support and custom TCP options
```
cd packages/fortinet && elastic-package test
```
- Relates #1878

[fortinet] Improve firewall input options

---

packages/system/changelog.yml
packages/system/data_stream/security/_dev/test/pipeline/test-security-windows2012-4778.json
packages/system/data_stream/security/_dev/test/pipeline/test-security-windows2012-4778.json-expected.json
packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
packages/system/data_stream/security/fields/ecs.yml
packages/system/data_stream/security/sample_event.json
packages/system/docs/README.md
packages/system/manifest.yml

This add GeoIP enrichment for the source.ip if it's available.
- Closes #3369

system/security: add GeoIP enrichment

---

packages/ti_abusech/changelog.yml
packages/ti_abusech/manifest.yml
packages/ti_anomali/changelog.yml
packages/ti_anomali/manifest.yml
packages/ti_cybersixgill/changelog.yml
packages/ti_cybersixgill/manifest.yml
packages/ti_misp/changelog.yml
packages/ti_misp/manifest.yml
packages/ti_otx/changelog.yml
packages/ti_otx/manifest.yml
packages/ti_recordedfuture/changelog.yml
packages/ti_recordedfuture/manifest.yml
packages/ti_threatq/changelog.yml
packages/ti_threatq/manifest.yml

Updates the descriptions on all TI packages defined in https://github.com/elastic/integrations/issues/2831
- Relates #2831

Update TI Package descriptions

---

packages/akamai/changelog.yml
packages/akamai/manifest.yml
packages/auth0/changelog.yml
packages/auth0/manifest.yml
packages/carbon_black_cloud/changelog.yml
packages/carbon_black_cloud/manifest.yml
packages/cisco_umbrella/changelog.yml
packages/cisco_umbrella/manifest.yml
packages/github/changelog.yml
packages/github/manifest.yml
packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/manifest.yml
packages/modsecurity/changelog.yml
packages/modsecurity/manifest.yml
packages/netskope/changelog.yml
packages/netskope/manifest.yml
packages/pulse_connect_secure/changelog.yml
packages/pulse_connect_secure/manifest.yml
packages/symantec_endpoint/changelog.yml
packages/symantec_endpoint/manifest.yml
packages/ti_recordedfuture/changelog.yml
packages/ti_recordedfuture/manifest.yml
packages/zscaler_zia/changelog.yml
packages/zscaler_zia/manifest.yml
packages/zscaler_zpa/changelog.yml
packages/zscaler_zpa/manifest.yml

Makes the following integrations GA:
Akamai
Auth0
Cisco Umbrella
Github
Microsoft SQL Server
Modsecurity
Netskope
Pulse Connect Secure
Recorded Future
Symantec Endpoint Protection
VMware Carbon Black Cloud
Zscaler Internet Access
Zscaler Private Access
Closes https://github.com/elastic/integrations/issues/2989

GA security integrations

---

.ci/Jenkinsfile

Use `withSecretVault` step
Requires https://github.com/elastic/apm-pipeline-library/pull/1704
The steps were configured as expected

ci: use withSecretVault

---

packages/cyberarkpas/_dev/build/docs/README.md
packages/cyberarkpas/changelog.yml
packages/cyberarkpas/docs/README.md
packages/cyberarkpas/manifest.yml

added link to vendor documentation
added link to vendor documentation
-

update Cyberasrkpas readme

---

packages/prometheus/_dev/build/docs/README.md
packages/prometheus/changelog.yml
packages/prometheus/docs/README.md
packages/prometheus/manifest.yml

reworded a link to related documentation so it is clearer
Type of change
- Enhancement
reworded a link to related documentation so it is clearer
-

updated Prometheus readme

---

packages/aws_logs/_dev/build/docs/README.md
packages/aws_logs/changelog.yml
packages/aws_logs/docs/README.md
packages/aws_logs/manifest.yml

updated readme to add links to AWS documentation
Type of change
- Enhancement
updated readme to add links to AWS documentation
-

 update AWS-Logs readme

---

packages/azure_billing/_dev/build/docs/README.md
packages/azure_billing/changelog.yml
packages/azure_billing/docs/README.md
packages/azure_billing/manifest.yml

Revised links to Microsoft documentation
Type of change
- Enhancement
Revised links to Microsoft documentation
-

Update Azure Billing Readme

---

packages/gcp_pubsub/_dev/build/docs/README.md
packages/gcp_pubsub/changelog.yml
packages/gcp_pubsub/docs/README.md
packages/gcp_pubsub/manifest.yml

added see before links
Type of change
- Enhancement
added see before links
-

Update gcp_pubsub readme

---

packages/cyberark/changelog.yml
packages/cyberark/docs/README.md
packages/cyberark/manifest.yml

added link to vendor documentation
- Enhancement
added link to vendor documentation
-

update Cyberark Readme

---

packages/github/changelog.yml
packages/github/data_stream/audit/_dev/test/pipeline/test-audit-json.log
packages/github/data_stream/audit/_dev/test/pipeline/test-audit-json.log-expected.json
packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/github/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/github/manifest.yml

Resolve issue of paignation and missing `created_at` field. I also updated the `event.*` categorization fields to be more accurate.
- Closes #3350

[Github] Fix pagination and missing fields

---

packages/linux/_dev/build/docs/README.md
packages/linux/changelog.yml
packages/linux/docs/README.md
packages/linux/manifest.yml

Fixes a typo in the docs that I introduced in https://github.com/elastic/integrations/pull/3359. 🙈 
- https://github.com/elastic/integrations/pull/3359

[docs] Fix typo in Linux docs

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/agent/stream/httpjson.yml.hbs
packages/panw_cortex_xdr/manifest.yml

Adds a condition to only paginate if there are more results.

[panw_cortex_xdr] Fix possible endless pagination

---

packages/akamai/changelog.yml
packages/akamai/data_stream/siem/_dev/test/pipeline/test-http-json.log-expected.json
packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
packages/akamai/data_stream/siem/fields/fields.yml
packages/akamai/data_stream/siem/sample_event.json
packages/akamai/docs/README.md
packages/akamai/kibana/dashboard/akamai-e7568320-066a-11ed-9f6c-cb8079f147f7.json
packages/akamai/manifest.yml

This adds a dashboard to the Akamai SIEM integration.
- Updates #3102.

akamai: add dashboard

---

packages/aws/_dev/build/docs/README.md
packages/aws/docs/README.md

[AWS] Added Redshift to README.md

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Change integration name to "Kubernetes Security Posture Management"

[Cloud Posture] Update display name

---

packages/cisco_umbrella/changelog.yml
packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
packages/cisco_umbrella/data_stream/log/manifest.yml
packages/cisco_umbrella/manifest.yml

Add missing proxy config
- Closes #3803

[Cisco Umbrella] Add missing proxy config

---

packages/aws/changelog.yml
packages/aws/data_stream/redshift/fields/fields.yml
packages/aws/manifest.yml

Remove beta flag for Amazon Redshift integration

[Amazon Redshift] Remove beta flag 

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/siem_logs/agent/stream/httpjson.yml.hbs
packages/mimecast/manifest.yml

Fixes the compression requested after the first interval.

[mimecast] Fix compression for SIEM logs

---

packages/aws/_dev/build/docs/vpn.md

Update VPN.MD First draft of AWS integration edits

---

packages/aws/_dev/build/docs/transitgateway.md

 Update AWS Transit Gateway - First draft of AWS integration edits

---

packages/aws/_dev/build/docs/sqs.md

Update SQS First draft of AWS integration edits

---

packages/aws/_dev/build/docs/natgateway.md

Update NAT Gateway - first draft of AWS integration edits

---

packages/pfsense/_dev/build/build.yml
packages/pfsense/changelog.yml
packages/pfsense/data_stream/log/_dev/test/pipeline/test-opensense.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-bsd.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-dhcp.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-haproxy.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-ipsec.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-openvpn.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-squid.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-syslog.log-expected.json
packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-unbound.log-expected.json
packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/pfsense/data_stream/log/sample_event.json
packages/pfsense/docs/README.md
packages/pfsense/manifest.yml

[pfsense] Update ECS to 8.4.0

---

packages/osquery_manager/_dev/build/build.yml
packages/osquery_manager/changelog.yml
packages/osquery_manager/data_stream/result/fields/ecs.yml
packages/osquery_manager/manifest.yml

Fix Field conflicts
- Closes #3724

[OSQuery] Fix Field Mapping Conflicts

---

packages/ti_misp/_dev/build/build.yml
packages/ti_misp/changelog.yml
packages/ti_misp/data_stream/threat/_dev/test/pipeline/test-misp-attributes-ndjson.log-expected.json
packages/ti_misp/data_stream/threat/_dev/test/pipeline/test-misp-sample-ndjson.log-expected.json
packages/ti_misp/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/ti_misp/data_stream/threat/sample_event.json
packages/ti_misp/docs/README.md
packages/ti_misp/manifest.yml

Update ti_misp to ECS 8.4.0
Closes #3890

[ti_misp] Update ECS to 8.4.0

---

packages/awsfargate/changelog.yml

Updates the changelog replacing the placeholder with the actual PR number 🙄

[AWS Fargate] Update link to PR

---

packages/jamf_compliance_reporter/_dev/build/build.yml
packages/jamf_compliance_reporter/changelog.yml
packages/jamf_compliance_reporter/data_stream/log/_dev/test/pipeline/test-pipeline-app-metrics.log-expected.json
packages/jamf_compliance_reporter/data_stream/log/_dev/test/pipeline/test-pipeline-audit.log-expected.json
packages/jamf_compliance_reporter/data_stream/log/_dev/test/pipeline/test-pipeline-event.log-expected.json
packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/jamf_compliance_reporter/data_stream/log/elasticsearch/ingest_pipeline/pipeline_aue_execve.yml
packages/jamf_compliance_reporter/docs/README.md
packages/jamf_compliance_reporter/manifest.yml

- Use ECS allowed values for `host.os.type`
- Update ECS version to 8.4.0
Closes #3885

[jamf_compliance_reporter] Update ECS to 8.4.0

---

packages/ibmmq/changelog.yml
packages/ibmmq/manifest.yml

- Bug
Update changelog entry for automatic promotion of package to snapshot.

[IBM MQ] Update changelog entry for automatic promotion of package to snapshot

---

packages/oracle_weblogic/changelog.yml
packages/oracle_weblogic/manifest.yml
packages/websphere_application_server/changelog.yml
packages/websphere_application_server/manifest.yml

- Bug
Update changelog entry for automatic promotion of packages to snapshot.
- Relates https://github.com/elastic/integrations/pull/3970

[oracle_weblogic][websphere_application_server] Update changelog entry for automatic promotion of packages to snapshot

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/elasticsearch/ilm/default_policy.json
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

In this PR I created new ILM policy and attached it to the findings data stream.

[Cloud Posture] Add ILM policy

---

packages/infoblox_nios/_dev/build/docs/README.md
packages/infoblox_nios/_dev/deploy/docker/docker-compose.yml
packages/infoblox_nios/changelog.yml
packages/infoblox_nios/data_stream/log/_dev/test/system/test-logfile-config.yml
packages/infoblox_nios/data_stream/log/agent/stream/log.yml.hbs
packages/infoblox_nios/data_stream/log/fields/ecs.yml
packages/infoblox_nios/data_stream/log/manifest.yml
packages/infoblox_nios/docs/README.md
packages/infoblox_nios/manifest.yml

This adds support for file inputs.
`elastic-package test`
- Closes #4114

infoblox_nios: add support for file inputs

---

.ci/Jenkinsfile

Runs benchmarks for all integrations as part of the CI
~- [ ] Benchmarks diffs get compared with last run~
~- [ ] Report is included as part of the GH bot in PRs~
Edit: these will be done in a new PR

Add benchmark step to CI

---

packages/ti_util/changelog.yml
packages/ti_util/manifest.yml

This adds the ti_util package to the `threat_intel` category.
- Closes #4176

ti_util: include package in threat_intel category

---

packages/windows/changelog.yml
packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
packages/windows/manifest.yml

The user-provided YAML is deindented before being appended to the existing lines from the agent template. This results in an indentation disagreement such as this:
processors:
- translate_sid:
field: winlog.event_data.MemberSid
account_name_target: winlog.event_data._MemberUserName
domain_target: winlog.event_data._MemberDomain
account_type_target: winlog.event_data._MemberAccountType
ignore_missing: true
ignore_failure: true
- add_fields:
target: project
fields:
name: myproject
id: '574734885120952459'
This results in a YAML parse failure. So deindent the translate_sid processor.
Attempt to add the `add_fields` processor to any of the `powershell`, `powershell_operational` or `sysmon_operational` datastreams when installing the windows integration here.
- Fixes #4170

windows: fix support for user-provided processors

---

dev/benchreport/report.go

Fixes the percentage calculation and shortens the report of packages without bad benchmarks.

[ci] Fix percentage calculation and shorten report

---

.ci/Jenkinsfile

ci: debug what's the gitHubCommentWithBenchmarkReport step doing

---

README.md

To be merged after https://github.com/elastic/package-spec/pull/384.

Update links in README for spec

---

packages/iis/changelog.yml
packages/iis/data_stream/access/agent/stream/log.yml.hbs
packages/iis/data_stream/error/agent/stream/log.yml.hbs
packages/iis/manifest.yml

Removed the space in the if condition for ignore_older flag. This allows the condition check to happen successfully.
Add a new IIS integration and check the data flow.
Update the integration from existing one and validate the use-case.

IIS ignore_older flag condition check updated

---

packages/fim/changelog.yml
packages/fim/manifest.yml

Bring the docs into line with the documentation for the auditbeat file integrity modules which does the work.
- Closes #4367

fim: fix path configuration documentation

---

packages/cisco_secure_email_gateway/changelog.yml
packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_secure_email_gateway/data_stream/log/sample_event.json
packages/cisco_secure_email_gateway/docs/README.md
packages/cisco_secure_email_gateway/manifest.yml

Instead of emitting the grok failure to the user, provide an error message that indicates the root cause of the failure to help them identify and rectify the problem.
For example with an incorrectly set up log file path the new behaviour is shown in the following screen shot — note the `error.message`: "log filepath does not match required glob pattern '\<category>.@*.s': '/tmp/service_logs/log.log'" instead of `error.message`: "Provided Grok expressions do not match field value: [/tmp/service_logs/sdh.log]".
-

cisco_secure_email_gateway: improve error handling for log filepath

---

packages/azure_metrics/changelog.yml
packages/azure_metrics/data_stream/compute_vm/_dev/test/pipeline/test-azure-metrics-compute-vm.json
packages/azure_metrics/data_stream/compute_vm/_dev/test/pipeline/test-azure-metrics-compute-vm.json-expected.json
packages/azure_metrics/data_stream/compute_vm/_dev/test/pipeline/test-common-config.yml
packages/azure_metrics/manifest.yml

Adds `compute_vm` pipeline test.
- Closes #4409

[azure_metrics] add compute_vm pipeline test

---

packages/cloud_security_posture/docs/README.md

Adding compatibility information for elastic agent - only README file fix
-

Added elastic-agent compatibility

---

packages/lastpass/changelog.yml
packages/lastpass/kibana/dashboard/lastpass-975ecef0-2450-11ed-80ca-25e921dc7ac2.json
packages/lastpass/kibana/dashboard/lastpass-fa6ad220-2458-11ed-80ca-25e921dc7ac2.json
packages/lastpass/manifest.yml

Fix minor grammar issues in dashboards.
- Closes #4460

lastpass: fix grammar errors in dashboards

---

.ci/Jenkinsfile

Restore publish to package storage V1 step

Revert remove publish

---

packages/azure_metrics/changelog.yml
packages/azure_metrics/data_stream/container_instance/_dev/test/pipeline/test-azure-metrics-container-instance.json
packages/azure_metrics/data_stream/container_instance/_dev/test/pipeline/test-azure-metrics-container-instance.json-expected.json
packages/azure_metrics/data_stream/container_instance/_dev/test/pipeline/test-common-config.yml
packages/azure_metrics/manifest.yml

Adds `container_instance` pipeline test.
- Closes: #4412

Add container instance pipeline tests

---

packages/trend_micro_vision_one/changelog.yml
packages/trend_micro_vision_one/data_stream/alert/agent/stream/httpjson.yml.hbs
packages/trend_micro_vision_one/data_stream/alert/sample_event.json
packages/trend_micro_vision_one/data_stream/audit/agent/stream/httpjson.yml.hbs
packages/trend_micro_vision_one/data_stream/audit/sample_event.json
packages/trend_micro_vision_one/data_stream/detection/agent/stream/httpjson.yml.hbs
packages/trend_micro_vision_one/data_stream/detection/sample_event.json
packages/trend_micro_vision_one/docs/README.md
packages/trend_micro_vision_one/manifest.yml

Type of change
- Enhancement
Update the Pagination Termination Condition for Trend Micro Vision One connector.
Current condition for pagination termination contains `[[else]][[.last_response.terminate_pagination]][[end]]` which results in error logs when pagination is completed.
Removing this `else` condition will not result in error logs.
- Move to integrations/packages/trend_micro_vision_one directory.
- Relates https://github.com/elastic/integrations/issues/4527

[Enhancement] [Trend Micro Vision One] Update the Pagination Termination Condition

---

packages/lastpass/changelog.yml
packages/lastpass/data_stream/event_report/agent/stream/httpjson.yml.hbs
packages/lastpass/data_stream/user/agent/stream/httpjson.yml.hbs
packages/lastpass/manifest.yml

Type of change
- Enhancement
Update the Pagination Termination Condition for Lastpass connector.
Current condition for pagination termination contains `[[else]][[.last_response.terminate_pagination]][[end]]` which results in error logs when pagination is completed.
Removing this `else` condition will not result in error logs.
- Move to integrations/packages/lastpass directory.
- Relates https://github.com/elastic/integrations/issues/4527

[Enhancement] [Lastpass] Update the Pagination Termination Condition

---

packages/proofpoint_tap/changelog.yml
packages/proofpoint_tap/data_stream/clicks_blocked/agent/stream/httpjson.yml.hbs
packages/proofpoint_tap/data_stream/clicks_permitted/agent/stream/httpjson.yml.hbs
packages/proofpoint_tap/data_stream/message_blocked/agent/stream/httpjson.yml.hbs
packages/proofpoint_tap/data_stream/message_delivered/agent/stream/httpjson.yml.hbs
packages/proofpoint_tap/manifest.yml

Type of change
- Enhancement
Update the Pagination Termination Condition for Proofpoint TAP connector.
Current condition for pagination termination contains `[[else]][[.last_response.terminate_pagination]][[end]]` which results in error logs when pagination is completed.
Removing this `else` condition will not result in error logs.
- Move to integrations/packages/proofpoint_tap directory.
- Relates https://github.com/elastic/integrations/issues/4527

[Enhancement] [Proofpoint TAP] Update the Pagination Termination Condition

---

.ci/Jenkinsfile
packages/elastic_package_registry/changelog.yml

Check whether or not integrations stage has been restarted.
It requires to checkout the git repository first.
Example of pipeline that has been executed after pressing "Restart check integrations"
https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-4748/7/pipeline

Check whether or not integrations stage has been restarted

---

packages/lastpass/changelog.yml
packages/lastpass/data_stream/detailed_shared_folder/sample_event.json
packages/lastpass/data_stream/event_report/fields/ecs.yml
packages/lastpass/data_stream/event_report/sample_event.json
packages/lastpass/data_stream/user/sample_event.json
packages/lastpass/docs/README.md
packages/lastpass/manifest.yml

Type of change
- Bug
In this PR, I updated the ECS field to `source.geo.location` for the `geo_point` type.
- Move to integrations/packages/lastpass directory.
- Closes #4759 
- Closes https://github.com/elastic/sdh-beats/issues/2798

[LastPass] Update ECS `source.geo.location` field.

---

packages/tenable_sc/_dev/build/docs/README.md
packages/tenable_sc/changelog.yml
packages/tenable_sc/data_stream/asset/agent/stream/httpjson.yml.hbs
packages/tenable_sc/data_stream/asset/sample_event.json
packages/tenable_sc/data_stream/plugin/agent/stream/httpjson.yml.hbs
packages/tenable_sc/data_stream/plugin/sample_event.json
packages/tenable_sc/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
packages/tenable_sc/data_stream/vulnerability/sample_event.json
packages/tenable_sc/docs/README.md
packages/tenable_sc/manifest.yml

Type of change
- Bug
Sync build version in user-agent header with package version.
- Move to integrations/packages/tenable_sc directory.

[Tenable SC] Sync build version in user-agent header with package version

---

packages/azure_metrics/_dev/build/docs/compute_vm.md
packages/azure_metrics/_dev/build/docs/compute_vm_scaleset.md
packages/azure_metrics/_dev/build/docs/container_instance.md
packages/azure_metrics/_dev/build/docs/container_registry.md
packages/azure_metrics/_dev/build/docs/container_service.md
packages/azure_metrics/_dev/build/docs/database_account.md
packages/azure_metrics/_dev/build/docs/monitor.md
packages/azure_metrics/_dev/build/docs/storage_account.md
packages/azure_metrics/changelog.yml
packages/azure_metrics/docs/compute_vm.md
packages/azure_metrics/docs/compute_vm_scaleset.md
packages/azure_metrics/docs/container_instance.md
packages/azure_metrics/docs/container_registry.md
packages/azure_metrics/docs/container_service.md
packages/azure_metrics/docs/database_account.md
packages/azure_metrics/docs/monitor.md
packages/azure_metrics/docs/storage_account.md
packages/azure_metrics/manifest.yml

Change link from indonesian Azure documentation to englisch

Azure Storage Account - Replace link to indonesian docs

---

packages/docker/docs/README.md

This PR updates the README file in docker package. Due to some unexpected issues in the latest PR from this package (related PR #4748), checks were not executed and this file was merged without being updated accordingly.
Checked that latest docker version published 2.3.0 has this README file with the right descriptions in these fields. Version checked obtained by:
```bash
curl -o  docker.zip -s "https://epr.elastic.co/epr/docker/docker-2.3.0.zip"
```

Update docker README 

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser_network/agent/stream/browser.network.yml.hbs
packages/synthetics/data_stream/browser_screenshot/agent/stream/browser.screenshot.yml.hbs
packages/synthetics/manifest.yml

Remove remaining geo processors

[Synthetics] Remove remaining geo processors

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/fields/cloudbeat.yml
packages/cloud_security_posture/data_stream/findings/fields/rule.yml
packages/cloud_security_posture/manifest.yml

Update mapping of newly introduced fields in cloudbeat's output
- Closes https://github.com/elastic/cloudbeat/issues/639
- Related https://github.com/elastic/cloudbeat/issues/552
Relevant fields:

[Cloud Posture] Update CSP mapping

---

packages/docker/changelog.yml
packages/docker/data_stream/container_logs/fields/fields.yml
packages/docker/docs/README.md
packages/docker/manifest.yml

Small package improvements in description and titles.

Improve docker package description

---

packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/data_stream/performance/agent/stream/stream.yml.hbs
packages/microsoft_sqlserver/data_stream/performance/sample_event.json
packages/microsoft_sqlserver/docs/README.md
packages/microsoft_sqlserver/manifest.yml

- Bug
Please refer to the #4902 
- Closes #4902

[Microsoft SqlServer]Fixed Performance Query for connection reset per second

---

.ci/Jenkinsfile

Use `flattenMap` from apm-pipeline-library
Relates https://github.com/elastic/apm-pipeline-library/pull/1985

Use flattenMap from apm-pipeline-library

---

packages/gcp/_dev/build/docs/README.md
packages/gcp/_dev/build/docs/redis.md
packages/gcp/changelog.yml
packages/gcp/docs/README.md
packages/gcp/docs/redis.md
packages/gcp/manifest.yml

Updates main README with metrics data streams and bump to `2.15.2`.
-

Update GCP docs with metrics data stream

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/0d160033-fab7-4e72-85a3-3a9d80c8bff7.json
packages/security_detection_engine/kibana/security_rule/54a81f68-5f2a-421e-8eed-f888278bb712.json
packages/security_detection_engine/kibana/security_rule/6aace640-e631-4870-ba8e-5fdda09325db.json
packages/security_detection_engine/kibana/security_rule/ac5012b8-8da8-440b-aaaf-aedafdea2dff.json
packages/security_detection_engine/kibana/security_rule/b946c2f7-df06-4c00-a5aa-1f6fbc7bb72c.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.3.4-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/cb77d7b0af952de9178cf8476731efc3f5e58aa2
None
None

[Security Rules] Update security rules package to v8.3.4-beta.1

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
packages/mimecast/data_stream/audit_events/sample_event.json
packages/mimecast/docs/README.md
packages/mimecast/manifest.yml

This fingerprints audit event documents based on their event ID to prevent duplicate document ingestion.
- Closes #5010

mimecast: fingerprint audit events based on their event ID

---

packages/pfsense/_dev/build/docs/README.md
packages/pfsense/changelog.yml
packages/pfsense/docs/README.md
packages/pfsense/manifest.yml

Fixes misspelling of HAProxy from "HAPrxoy"

[pfSense] Fix misspelling of HAProxy

---

packages/cisco_meraki/changelog.yml
packages/cisco_meraki/data_stream/events/sample_event.json
packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log
packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-flows.log-expected.json
packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/flows.yml
packages/cisco_meraki/data_stream/log/fields/fields.yml
packages/cisco_meraki/data_stream/log/sample_event.json
packages/cisco_meraki/docs/README.md
packages/cisco_meraki/manifest.yml

This captures flows' firewall rules.
- Fixes #5086

cisco_meraki: capture flows firewall rules

---

packages/aws/changelog.yml
packages/aws/kibana/dashboard/aws-07d67a60-d872-11eb-8220-c9141cc1b15c.json
packages/aws/kibana/dashboard/aws-0eb5a6a0-694f-11ea-b0ac-95d4ecb1fecd.json
packages/aws/kibana/dashboard/aws-234aeda0-43b7-11e9-8697-530f39afc6eb.json
packages/aws/kibana/dashboard/aws-3367c170-921f-11e9-aa19-159bf182e06f.json
packages/aws/kibana/dashboard/aws-3d3dbe00-f79f-11ec-aa7f-c173c0f9e267.json
packages/aws/kibana/dashboard/aws-44ce4680-b7ba-11e9-8349-f15f850c5cd0.json
packages/aws/kibana/dashboard/aws-67c9f900-693e-11ea-b0ac-95d4ecb1fecd.json
packages/aws/kibana/dashboard/aws-68ba7bd0-20b6-11ea-8f72-2f8d21e50b0c.json
packages/aws/kibana/dashboard/aws-7ac8e1d0-28d2-11ea-ba6c-49a884eb104f.json
packages/aws/kibana/dashboard/aws-80ed1380-41a6-11ec-a605-bff67d9b7872.json
packages/aws/kibana/dashboard/aws-81f2c980-e743-11ec-93f6-9b98f71110cd.json
packages/aws/kibana/dashboard/aws-917a07b0-178e-11ea-8650-fb606deb5be4.json
packages/aws/kibana/dashboard/aws-9c09cd20-7399-11ea-a345-f985c61fe654.json
packages/aws/kibana/dashboard/aws-c2b1cbc0-6891-11ea-b0ac-95d4ecb1fecd.json
packages/aws/kibana/dashboard/aws-e6776b10-1534-11ea-841c-01bf20a6c8ba.json
packages/aws/kibana/dashboard/aws-e74bf320-b3ce-11e9-87a4-078dbbae220d.json
packages/aws/manifest.yml

Adds data stream filters for the following dashboards:
-

[AWS] Add dashboards data stream filters

---

packages/okta/changelog.yml
packages/okta/data_stream/system/fields/fields.yml
packages/okta/docs/README.md
packages/okta/manifest.yml

Fix typo in field description.
-

okta: fix typo

---

packages/system_audit/_dev/build/docs/README.md
packages/system_audit/changelog.yml
packages/system_audit/docs/README.md
packages/system_audit/manifest.yml

Fixes documentation bug, syncs readme, and bumps version.
* Also for https://github.com/elastic/integrations/pull/5188

bump version and sync readme

---

packages/microsoft_sqlserver/_dev/build/docs/README.md
packages/microsoft_sqlserver/changelog.yml
packages/microsoft_sqlserver/docs/README.md
packages/microsoft_sqlserver/manifest.yml

- Enhancement
This PR updates the Readme.md to specify URL encoding for passwords with special character.
- Relates [4198](https://github.com/elastic/integrations/issues/4198)

Update documentation for password

---

packages/airflow/_dev/build/docs/README.md
packages/airflow/changelog.yml
packages/airflow/docs/README.md
packages/airflow/kibana/dashboard/airflow-a3aa42d0-a465-11ed-9ff0-ab4dd59e4c75.json
packages/airflow/manifest.yml

- Enhancement
This PR adds overview dashboard for Airflow.
Setup and configure airflow to send metrics to statsd server. 
Add integration with set host and port.
Metrics should start coming and confirm in dashboard
- Closes #5001

[Airflow] Add Airflow Dashboard

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
packages/cloud_security_posture/manifest.yml

Add RDS fetcher to the AWS CSPM hbs file

[Cloud Posture] Add RDS fetcher to AWS hbs file

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bumping version for first QA cycle - 8.7.0 BC1

[Cloud Security] cloud_security_posture version bump - beta1

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bumping next version to include the fix for `multiple` input streams

Bumping version of next

---

packages/tenable_io/_dev/build/docs/README.md
packages/tenable_io/changelog.yml
packages/tenable_io/data_stream/asset/agent/stream/httpjson.yml.hbs
packages/tenable_io/data_stream/asset/manifest.yml
packages/tenable_io/data_stream/plugin/manifest.yml
packages/tenable_io/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
packages/tenable_io/data_stream/vulnerability/manifest.yml
packages/tenable_io/docs/README.md
packages/tenable_io/manifest.yml

Type of change
- Enhancement
- Add Max Retries parameter in asset and vulnerability data stream to increase wait time.
- Move to integrations/packages/tenable_io directory.
- Closes #5165

[tenable.io] Add Max Retries parameter to increase wait time

---

docs/developer_tsdb_migration_guidelines.md

Type of Change
- Enhancement
Adding documentation of : A Developers guide for TSDB migration

[Documentation] Developers guide for TSDB migration

---

packages/cisco_asa/changelog.yml
packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-non-canonical.log-expected.json
packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_asa/manifest.yml

- Removed `ignore_failure` and uses `if` conditionals to avoid failures in most processors having `ignore_failure: true`
- Adds `on_failure` to append errors onto `error.message` to potentially problematic processors
- Closes https://github.com/elastic/integrations/issues/5349

[Cisco ASA] Remove ignore_failure causing performance impact

---

packages/m365_defender/_dev/build/docs/README.md
packages/m365_defender/changelog.yml
packages/m365_defender/data_stream/event/manifest.yml
packages/m365_defender/data_stream/incident/manifest.yml
packages/m365_defender/data_stream/log/manifest.yml
packages/m365_defender/docs/README.md
packages/m365_defender/manifest.yml

Type of change
- Enhancement
- Update m365 ReadMe as well as data streams titles.
- Move to integrations/packages/m365_defender directory.
- Closes #5408

[m365_defender] Document and Title Updates

---

packages/tcp/changelog.yml
packages/tcp/data_stream/generic/agent/stream/tcp.yml.hbs
packages/tcp/data_stream/generic/manifest.yml
packages/tcp/manifest.yml
packages/udp/changelog.yml
packages/udp/data_stream/generic/agent/stream/udp.yml.hbs
packages/udp/data_stream/generic/manifest.yml
packages/udp/manifest.yml

Adds a YAML configuration to the custom TCP and UDP packages.
- Closes #5229

tcp,udp: allow YAML custom configuration

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser/elasticsearch/ilm/default_policy.json
packages/synthetics/data_stream/browser/fields/common.yml
packages/synthetics/data_stream/browser_network/elasticsearch/ilm/default_policy.json
packages/synthetics/data_stream/browser_screenshot/elasticsearch/ilm/default_policy.json
packages/synthetics/data_stream/http/elasticsearch/ilm/default_policy.json
packages/synthetics/data_stream/http/fields/common.yml
packages/synthetics/data_stream/icmp/elasticsearch/ilm/default_policy.json
packages/synthetics/data_stream/icmp/fields/common.yml
packages/synthetics/data_stream/tcp/elasticsearch/ilm/default_policy.json
packages/synthetics/data_stream/tcp/fields/common.yml
packages/synthetics/docs/README.md
packages/synthetics/manifest.yml

Reverts elastic/integrations#5235

Revert "synthetics - add max size to browser and screenshot ILM policies"

---

packages/cloudflare_logpush/changelog.yml
packages/cloudflare_logpush/data_stream/http_request/_dev/test/pipeline/test-pipeline-http-request.log-expected.json
packages/cloudflare_logpush/data_stream/http_request/elasticsearch/ingest_pipeline/default.yml
packages/cloudflare_logpush/data_stream/http_request/sample_event.json
packages/cloudflare_logpush/docs/README.md
packages/cloudflare_logpush/manifest.yml

Use a consistent and meaningful timestamp for events.
- Fixes #5571

cloudflare_logpush: use EdgeStartTimestamp event timestamp

---

packages/cloud_security_posture/manifest.yml

Resolves https://github.com/elastic/integrations/issues/5434
-

[Cloud Security][Vulnerability Management] Add CloudFormation template link

---

packages/winlog/_dev/build/docs/README.md
packages/winlog/changelog.yml
packages/winlog/docs/README.md
packages/winlog/manifest.yml

Improves documentation for obtaining channel names.
- Closes #5673

winlog: improve documentation for obtaining channel names

---

packages/crowdstrike/changelog.yml
packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
packages/crowdstrike/manifest.yml

Adds fingerprint processors to ensure uniqueness of documents (where possible — some Falcon events do not allow this, in particular Commandline-only events).
- Fixes #5668

crowdstrike: prevent ingestion of duplicate event IDs

---

packages/oracle/changelog.yml
packages/oracle/data_stream/memory/fields/ecs.yml
packages/oracle/data_stream/performance/fields/ecs.yml
packages/oracle/data_stream/sysmetric/fields/ecs.yml
packages/oracle/data_stream/system_statistics/fields/ecs.yml
packages/oracle/data_stream/tablespace/fields/ecs.yml
packages/oracle/docs/README.md
packages/oracle/manifest.yml

Type of change
- Enhancement
- Removed `host.ip` as dimension field
- Added `host.name` as dimension field
- Closes [#5695](https://github.com/elastic/integrations/issues/5695)

[Oracle] [TSDB] Updated dimension field mapping

---

packages/cloud_security_posture/manifest.yml

Update the link being used for vulnerability management cloudformation templates to a prod S3 bucket.
-

Prod S3 bucket for vulnerability management integration

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
packages/synthetics/data_stream/browser/manifest.yml
packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
packages/synthetics/manifest.yml

- Bug
Adds `response.include_body_max_bytes` to http.yml.hbs

[Synthetics] include body max bytes

---

packages/couchdb/changelog.yml
packages/couchdb/data_stream/server/fields/ecs.yml
packages/couchdb/docs/README.md
packages/couchdb/manifest.yml

Type of change
- Enhancement
-

[TSDB] Couchdb add dimension fields

---

packages/airflow/changelog.yml
packages/airflow/data_stream/statsd/fields/agent.yml
packages/airflow/data_stream/statsd/fields/ecs.yml
packages/airflow/data_stream/statsd/fields/fields.yml
packages/airflow/docs/README.md
packages/airflow/manifest.yml

- Enhancement
This PR adds dimension fields for airflow statsd datastream to support TSDB.
- Relates #5275

Added dimension fields for airflow to enable tsdb

---

packages/oracle_weblogic/_dev/build/docs/README.md
packages/oracle_weblogic/changelog.yml
packages/oracle_weblogic/data_stream/admin_server/fields/ecs.yml
packages/oracle_weblogic/data_stream/deployed_application/fields/ecs.yml
packages/oracle_weblogic/data_stream/threadpool/fields/ecs.yml
packages/oracle_weblogic/docs/README.md
packages/oracle_weblogic/manifest.yml

- Bug
This PR is raised to update Oracle WebLogic package to resolve conflict of host.ip field by adding it in ECS mapping and the required steps to reindex data for [troubleshoot](https://github.com/elastic/integrations/pull/5764/files#:~:text=%60%60%60-,%23%23%23%20Troubleshooting,-Conflicts%20in%20any). 
- https://github.com/elastic/sdh-beats/issues/3197#issuecomment-1473169693

[Oracle WebLogic] Add host.ip field

---

packages/cloud_defend/changelog.yml
packages/cloud_defend/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/cloud_defend/data_stream/file/elasticsearch/ingest_pipeline/default.yml
packages/cloud_defend/data_stream/process/elasticsearch/ingest_pipeline/default.yml
packages/cloud_defend/docs/README.md
packages/cloud_defend/manifest.yml

- documentation updates/examples
- missing fields added to injest pipe

[D4C] Doc updates

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/4b4e9c99-27ea-4621-95c8-82341bc6e512_1.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.8.1-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/003b8c4aba5b215c519c981ead1ac7bff72c266a
None

[Security Rules] Update security rules package to v8.8.1-beta.1

---

packages/cloud_security_posture/data_stream/vulnerabilities/fields/ecs.yml

At the moment, Cloudbeat doesn't report these fields and so there is no reason to keep them as part of the integration.
-

[Vulnerability Management] Remove unused ECS fields

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Set a new version of our CloudFormation template.
-

[Vulnerability Management] Update CloudFormation template address

---

packages/google_workspace/_dev/build/docs/README.md
packages/google_workspace/changelog.yml
packages/google_workspace/docs/README.md
packages/google_workspace/manifest.yml

Adds links to the security labs blog series about google workspace and some clarification for the Delegated Account value also in the README.

[google_workspace] Link security labs blog post in the readme

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-common-config.yml
packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr-bioc.log-expected.json
packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr.log-expected.json
packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
packages/panw_cortex_xdr/data_stream/alerts/fields/ecs.yml
packages/panw_cortex_xdr/data_stream/alerts/fields/fields.yml
packages/panw_cortex_xdr/data_stream/alerts/sample_event.json
packages/panw_cortex_xdr/docs/README.md
packages/panw_cortex_xdr/manifest.yml

Maps Mitre Att&ck fields to Threat ECS fields.
- Closes #5991

[panw_cortex_xdr] Map Mitre to Threat ECS fields

---

.ci/schedule-daily.groovy

Update the stack in the daily job from 8.7 to 8.8.

Run daily job with 8.8.

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

- Resolves: https://github.com/elastic/cloudbeat/issues/937
-

[Vulnerability Management] CloudFormation template populate ElasticArtifactServer param (1.3.0)

---

packages/synthetics/changelog.yml
packages/synthetics/manifest.yml

[Synthetics] GA

---

packages/cloud_defend/changelog.yml
packages/cloud_defend/docs/README.md
packages/cloud_defend/manifest.yml

Fixes some examples in the documentation.

[D4C] fixes to some examples in the documentation

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/474fd20e-14cc-49c5-8160-d9ab4ba16c8b.json
packages/security_detection_engine/kibana/security_rule/96d11d31-9a79-480f-8401-da28b194608f.json
packages/security_detection_engine/kibana/security_rule/a00681e3-9ed6-447c-ab2c-be648821c622.json
packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.6.4-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/67c31074e94e0cb3e0a0ba10a0f38b8a0cea067f
* https://github.com/elastic/ia-trade-team/issues/122
None

[Security Rules] Update security rules package to v8.6.4-beta.1

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Release
This PR updates the Cloud Security Posture package to the `1.3.0` release.

[1.3.0] [Cloud Security Posture] Release version 1.3.0

---

.github/CODEOWNERS
packages/universal_profiling_collector/changelog.yml
packages/universal_profiling_collector/docs/README.md
packages/universal_profiling_collector/img/profiler-logo-color-48px.svg
packages/universal_profiling_collector/manifest.yml

Add a package for Universal Profiling Collector

Add a package for Universal Profiling Collector

---

packages/slack/data_stream/audit/elasticsearch/ingest_pipeline/default.yml

Align comment script param comments with content.
Remove trailing spaces.
Switch script source to literal instead of using a folded block chomping indicator (`>-`).
- https://github.com/goccy/go-yaml/issues/374

[Slack] minor ingest pipeline YAML changes

---

packages/zeronetworks/changelog.yml
packages/zeronetworks/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/zeronetworks/manifest.yml

Fix formatting of params passed to the script processor.
Remove trailing spaces.
Align comment to related content.
Fixes #6376
- Fixes #6376
- Works around: https://github.com/goccy/go-yaml/issues/374 (comment align fix will workaround this bug)

[Zero Networks] Fix pipeline script params

---

packages/universal_profiling_collector/agent/input/input.yml.hbs
packages/universal_profiling_collector/changelog.yml
packages/universal_profiling_collector/manifest.yml

Add minimal input configuration for the service.

Universal Profiling Collector: Add input configuration

---

packages/prometheus_input/changelog.yml
packages/prometheus_input/manifest.yml

- Bug
This PR rectifies some spelling mistakes in the Prometheus Input Package

Rectify the  typos

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/474fd20e-14cc-49c5-8160-d9ab4ba16c8b.json
packages/security_detection_engine/kibana/security_rule/96d11d31-9a79-480f-8401-da28b194608f.json
packages/security_detection_engine/kibana/security_rule/a00681e3-9ed6-447c-ab2c-be648821c622.json
packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.6.5-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/7e66b301db4657aadd6e53a4bd030b38d6102f38
* https://github.com/elastic/ia-trade-team/issues/130
None

[Security Rules] Update security rules package to v8.6.5-beta.1

---

docs/developer_workflow_bug_fix_older_package_version.md

- Bug
Fix typo and clear up language

[Docs] Fix typo and clear up language

---

docs/fine_tune_integration.md

[Docs] Update fine_tune_integration.md

---

packages/universal_profiling_symbolizer/changelog.yml
packages/universal_profiling_symbolizer/manifest.yml

Universal Profiling Symbolizer: update to 8.8.1

---

packages/ibmmq/changelog.yml
packages/ibmmq/data_stream/qmgr/fields/ecs.yml
packages/ibmmq/data_stream/qmgr/fields/fields.yml
packages/ibmmq/docs/README.md
packages/ibmmq/manifest.yml

- Enhancement
Added TSDB dimensions related changes as beta release for IBM MQ package

IBM-MQ added dimension fields

---

packages/oracle_weblogic/_dev/build/docs/README.md
packages/oracle_weblogic/changelog.yml
packages/oracle_weblogic/docs/README.md
packages/oracle_weblogic/manifest.yml

- Bug
- Fix typo errors in descriptions of README.md
- Closes #6383

[O11y][Oracle WebLogic] Fix descriptions in README.md

---

packages/couchbase/changelog.yml
packages/couchbase/manifest.yml

- Enhancement
Migrates the integration from BETA to GA
The testing guidelines are captured in this [issue](https://github.com/elastic/integrations/issues/6049).
- Closes #6049

[Couchbase] Migrate to GA

---

.github/CODEOWNERS
packages/system/manifest.yml

change ownership of system package
N/A
-

Change ownership of system package

---

packages/github/_dev/build/docs/README.md
packages/github/changelog.yml
packages/github/docs/README.md
packages/github/manifest.yml

Updates documentation with additional prerequisites for Audit Log such as [Enterprise Cloud](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization#using-the-audit-log-api) and also `read:audit_log scope` permissions 
- Closes https://github.com/elastic/integrations/issues/6422

[Github] Update documentation containing audit log prerequisites

---

.buildkite/pipeline.yml
.buildkite/pull-requests.json
catalog-info.yaml

This PR onboards this repository into Buildkite and creates a dummy first pipeline

Onboard repository into Buildkite

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

This adds a working link to the CSPM integration variables, to close https://github.com/elastic/cloudbeat/issues/596.
Changelog is to be updated when
https://github.com/elastic/kibana/issues/157761 is done.

Cloud Security - Add CloudFormation url to CSPM

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/17b0a495-4d9f-414c-8ad0-92f018b8e001.json
packages/security_detection_engine/kibana/security_rule/474fd20e-14cc-49c5-8160-d9ab4ba16c8b.json
packages/security_detection_engine/kibana/security_rule/7fb500fa-8e24-4bd1-9480-2a819352602c.json
packages/security_detection_engine/kibana/security_rule/96d11d31-9a79-480f-8401-da28b194608f.json
packages/security_detection_engine/kibana/security_rule/a00681e3-9ed6-447c-ab2c-be648821c622.json
packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
packages/security_detection_engine/kibana/security_rule/ff10d4d8-fea7-422d-afb1-e5a2702369a9.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.6.6-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/d7e75ef890b8ece3149381cdce8620b3841f401f
* https://github.com/elastic/ia-trade-team/issues/131
None

[Security Rules] Update security rules package to v8.6.6-beta.1

---

packages/nagios_xi/changelog.yml
packages/nagios_xi/manifest.yml

- Enhancement
Migrates the integration from BETA to GA
The testing guidelines and execution results are captured in this [issue](#6052)
- Closes #6052

[Nagios XI] Migrate to GA

---

packages/oracle_weblogic/changelog.yml
packages/oracle_weblogic/manifest.yml

- Enhancement
Migrates the integration from BETA to GA
The testing guidelines and execution results are captured in this [issue](#6054)
- Closes #6054

[Oracle Weblogic] Migrate to GA

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
packages/cloud_security_posture/manifest.yml

Sends the correct configuration to cloudbeat for CIS 1.1.19 rule to work correctly. See related PR/issue.
- Related to https://github.com/elastic/cloudbeat/pull/981

[Cloud Security] Update vanilla.yml to scan pki folder recursively

---

packages/cisco_nexus/_dev/deploy/docker/sample_logs/test-nexus.log
packages/cisco_nexus/changelog.yml
packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-nexus.log
packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-nexus.log-expected.json
packages/cisco_nexus/data_stream/log/elasticsearch/ingest_pipeline/default.yml
packages/cisco_nexus/data_stream/log/elasticsearch/ingest_pipeline/pipeline_extract_message.yml
packages/cisco_nexus/data_stream/log/fields/fields.yml
packages/cisco_nexus/data_stream/log/sample_event.json
packages/cisco_nexus/docs/README.md
packages/cisco_nexus/manifest.yml

Type of change
- Enhancement
Add support for new log format
Move to integrations/packages/cisco_nexus directory.
[Elastic Package Test.txt](https://github.com/elastic/integrations/files/11829667/Elastic.Package.Test.txt)

[cisco_nexus] Add support for new log format

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
packages/cloud_security_posture/manifest.yml

Update the `cis_gcp` hbs file to reflect the auth options we'll support in GCP.
- https://github.com/elastic/integrations/issues/5354

[Cloud Security] Update cis gcp config file

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Updates the cloudformation template to use a new one. see https://github.com/elastic/cloudbeat/pull/1070

[Cloud Security] Update CloudFormation template

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/17b0a495-4d9f-414c-8ad0-92f018b8e001.json
packages/security_detection_engine/kibana/security_rule/474fd20e-14cc-49c5-8160-d9ab4ba16c8b.json
packages/security_detection_engine/kibana/security_rule/53617418-17b4-4e9c-8a2c-8deb8086ca4b.json
packages/security_detection_engine/kibana/security_rule/7fb500fa-8e24-4bd1-9480-2a819352602c.json
packages/security_detection_engine/kibana/security_rule/96d11d31-9a79-480f-8401-da28b194608f.json
packages/security_detection_engine/kibana/security_rule/a00681e3-9ed6-447c-ab2c-be648821c622.json
packages/security_detection_engine/kibana/security_rule/aebaa51f-2a91-4f6a-850b-b601db2293f4.json
packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
packages/security_detection_engine/kibana/security_rule/ff10d4d8-fea7-422d-afb1-e5a2702369a9.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.6.7-beta.1.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/5f9e269636ffce2b7035f7775264c71585a08833
None

[Security Rules] Update security rules package to v8.6.7-beta.1

---

.github/CODEOWNERS

codeowners: sort package list and add request to maintain order

---

packages/security_detection_engine/changelog.yml
packages/security_detection_engine/kibana/security_rule/17b0a495-4d9f-414c-8ad0-92f018b8e001.json
packages/security_detection_engine/kibana/security_rule/474fd20e-14cc-49c5-8160-d9ab4ba16c8b.json
packages/security_detection_engine/kibana/security_rule/53617418-17b4-4e9c-8a2c-8deb8086ca4b.json
packages/security_detection_engine/kibana/security_rule/7fb500fa-8e24-4bd1-9480-2a819352602c.json
packages/security_detection_engine/kibana/security_rule/96d11d31-9a79-480f-8401-da28b194608f.json
packages/security_detection_engine/kibana/security_rule/a00681e3-9ed6-447c-ab2c-be648821c622.json
packages/security_detection_engine/kibana/security_rule/aebaa51f-2a91-4f6a-850b-b601db2293f4.json
packages/security_detection_engine/kibana/security_rule/df0fd41e-5590-4965-ad5e-cd079ec22fa9.json
packages/security_detection_engine/kibana/security_rule/ff10d4d8-fea7-422d-afb1-e5a2702369a9.json
packages/security_detection_engine/manifest.yml

Update the Security Rules package to version 8.6.8.
Autogenerated from commit  https://github.com/elastic/detection-rules/tree/3292df53189bb92ddf8601146cad7bae2f6f9bc9
* https://github.com/elastic/ia-trade-team/issues/135
None

[Security Rules] Update security rules package to v8.6.8

---

packages/iptables/changelog.yml
packages/iptables/kibana/dashboard/iptables-ceefb9e0-1f51-11e9-93ed-f7e068f4aebb.json
packages/iptables/kibana/dashboard/iptables-d39f0980-1ff3-11e9-ae2a-939083c6a64e.json
packages/iptables/kibana/search/iptables-b3f1b010-1f26-11e9-8ec4-cf5d91a864b3.json
packages/iptables/kibana/search/iptables-c4e80aa0-1fd4-11e9-ae2a-939083c6a64e.json
packages/iptables/manifest.yml

iptables: convert visualisations to lens

---

packages/cisco_secure_email_gateway/changelog.yml
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-3e3a4de0-b00b-11ec-8a45-8d83ac55242a.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-6a11cbc0-b513-11ec-aa3c-afc0e710666b.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-97ab0d40-b63e-11ec-b665-f79f0daaad54.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-a1060e90-b025-11ec-8a45-8d83ac55242a.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-b9591cf0-b640-11ec-b665-f79f0daaad54.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-be7e9c00-b055-11ec-8a45-8d83ac55242a.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-c19f7c50-b05b-11ec-8a45-8d83ac55242a.json
packages/cisco_secure_email_gateway/kibana/dashboard/cisco_secure_email_gateway-c94a00a0-b0a7-11ec-8a45-8d83ac55242a.json
packages/cisco_secure_email_gateway/manifest.yml

cisco_secure_email_gateway: convert visualisations to lens

---

packages/cisco_ise/changelog.yml
packages/cisco_ise/kibana/dashboard/cisco_ise-44afda90-3991-11ed-bb16-3b8b6259e7b8.json
packages/cisco_ise/kibana/dashboard/cisco_ise-506e8200-39a5-11ed-a2b2-1d4b9d412e28.json
packages/cisco_ise/kibana/dashboard/cisco_ise-6b611af0-39a0-11ed-a2b2-1d4b9d412e28.json
packages/cisco_ise/kibana/dashboard/cisco_ise-a42bdb60-39a8-11ed-a2b2-1d4b9d412e28.json
packages/cisco_ise/kibana/dashboard/cisco_ise-db12cdf0-3a2f-11ed-a2b2-1d4b9d412e28.json
packages/cisco_ise/kibana/dashboard/cisco_ise-e0ca7fa0-398e-11ed-bb16-3b8b6259e7b8.json
packages/cisco_ise/kibana/dashboard/cisco_ise-e2146a20-39a1-11ed-a2b2-1d4b9d412e28.json
packages/cisco_ise/kibana/dashboard/cisco_ise-fcb9bc40-3a32-11ed-a2b2-1d4b9d412e28.json
packages/cisco_ise/kibana/search/cisco_ise-2c7c0eb0-a505-11ec-ab9d-4b8e737a22d9.json
packages/cisco_ise/kibana/search/cisco_ise-39e47010-a09b-11ec-a0a2-1598702abf83.json
packages/cisco_ise/kibana/search/cisco_ise-47c77dc0-a065-11ec-a0a2-1598702abf83.json
packages/cisco_ise/kibana/search/cisco_ise-5f739b70-a0a6-11ec-a0a2-1598702abf83.json
packages/cisco_ise/kibana/search/cisco_ise-ac5b9ba0-a02d-11ec-a0a2-1598702abf83.json
packages/cisco_ise/kibana/search/cisco_ise-d1ba7b80-a075-11ec-a0a2-1598702abf83.json
packages/cisco_ise/kibana/search/cisco_ise-eecf4510-a058-11ec-a0a2-1598702abf83.json
packages/cisco_ise/kibana/search/cisco_ise-f681d1f0-a09f-11ec-a0a2-1598702abf83.json
packages/cisco_ise/manifest.yml

cisco_ise: convert dashboard visualisations to lens

---

packages/cisco_duo/changelog.yml
packages/cisco_duo/kibana/dashboard/cisco_duo-2eb22f90-34c3-11ed-81dc-5d9e1bd8e06a.json
packages/cisco_duo/kibana/dashboard/cisco_duo-7e997350-34c9-11ed-81dc-5d9e1bd8e06a.json
packages/cisco_duo/kibana/dashboard/cisco_duo-f4c25e10-3420-11ed-a766-d751fb2ca0fe.json
packages/cisco_duo/kibana/dashboard/cisco_duo-fc635930-342f-11ed-8943-5bb82a29aed1.json
packages/cisco_duo/manifest.yml

cisco_duo: convert to lens

---

.ci/schedule-daily.groovy

Propose to update the daily job from using stack version 8.8-SNAPSHOT to 8.9-SNAPSHOT.

Run daily job with 8.9

---

packages/system/changelog.yml
packages/system/data_stream/network/fields/agent.yml
packages/system/data_stream/syslog/manifest.yml
packages/system/manifest.yml

Revert back changes from issue https://github.com/elastic/kibana/pull/157897. 
Removing the following configs from the system package manifest
```
elasticsearch.dynamic_dataset: true
elasticsearch.dynamic_namespace: true
```
We would like to revert these permissions in favour of creating a separate input package to reroute traffic from Syslog. 
Also, syslog datastream is enabled by default when you create a new agent policy. By having these permissions here, we were accidentally giving any elastic-agent permissions to write `logs-*-*`.
The idea is that we would like to have datastream-based integrations to monitor a specific application, while we should have input packages instead to reroute "mixed" traffic (from different sources) from that application.
- Relates …

System package: revert back change to dynamic_dataset/namespace

---

packages/f5/changelog.yml
packages/f5/manifest.yml

f5: deprecate package

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Change CNVM CloudFormation template to increase the disk size of the created EC2 instance.
-

[CNVM] CloudFormation template increase disk size

---

packages/auditd_manager/changelog.yml
packages/auditd_manager/kibana/dashboard/auditd_manager-693a5f40-c243-11e7-8692-232bd1143e8a.json
packages/auditd_manager/kibana/dashboard/auditd_manager-7de391b0-c1ca-11e7-8995-936807a28b16.json
packages/auditd_manager/kibana/dashboard/auditd_manager-c0ac2c00-c1c0-11e7-8995-936807a28b16.json
packages/auditd_manager/kibana/search/auditd_manager-0f10c430-c1c3-11e7-8995-936807a28b16.json
packages/auditd_manager/kibana/search/auditd_manager-5438b030-c246-11e7-8692-232bd1143e8a.json
packages/auditd_manager/kibana/search/auditd_manager-b4c93470-c240-11e7-8692-232bd1143e8a.json
packages/auditd_manager/kibana/search/auditd_manager-d382f5b0-c1c6-11e7-8995-936807a28b16.json
packages/auditd_manager/kibana/search/auditd_manager-e8734160-c24c-11e7-8692-232bd1143e8a.json
packages/auditd_manager/manifest.yml

auditd_manager: convert visualisations to lens

---

packages/github/changelog.yml
packages/github/kibana/dashboard/github-4da91aa0-12fc-11ed-af77-016e1a977d80.json
packages/github/kibana/dashboard/github-591d69e0-17b6-11ed-809a-7b4be950fe9c.json
packages/github/kibana/dashboard/github-6197be80-220c-11ed-88c4-e3caca48250a.json
packages/github/kibana/dashboard/github-6a6d7c40-17ab-11ed-809a-7b4be950fe9c.json
packages/github/kibana/dashboard/github-8bfd8310-205c-11ec-8b10-11a4c5e322a0.json
packages/github/kibana/dashboard/github-dcee84c0-2059-11ec-8b10-11a4c5e322a0.json
packages/github/kibana/dashboard/github-f0104680-ae18-11ed-83fa-df5d96a45724.json
packages/github/kibana/search/github-173f1050-20ae-11ec-8b10-11a4c5e322a0.json
packages/github/kibana/search/github-a5f3d9b0-20af-11ec-8b10-11a4c5e322a0.json
packages/github/manifest.yml

See title.
- For #6787
Only two dashboards have conversions: User Change Audit (2×) and Audit Log Activity (6×)

github: convert visualisations to lens

---

packages/zeek/changelog.yml
packages/zeek/kibana/dashboard/zeek-7cbb5410-3700-11e9-aa6d-ff445a78330c.json
packages/zeek/manifest.yml

zeek: convert visualisations to lens

---

packages/ti_rapid7_threat_command/changelog.yml
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-0ee0c5f0-7208-11ed-af6f-3913a325a746.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-1abe9f50-591c-11ed-a133-234996671b18.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-20735802-0864-485a-8b6f-e138aae5900d.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-2388d940-f6b4-11ec-ad26-2fb998639a1e.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-24d08610-7227-11ed-af6f-3913a325a746.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-7fdae3b0-590a-11ed-abd0-858c1d0aec26.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-8dea15b0-f3a3-11ec-aff5-576c7e430437.json
packages/ti_rapid7_threat_command/kibana/dashboard/ti_rapid7_threat_command-8f985fb0-6988-11ed-8bdb-110ff35bc478.json
packages/ti_rapid7_threat_command/manifest.yml

ti_rapid7_threat_command: convert visualisations to lens

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/data_stream/findings/manifest.yml
packages/cloud_security_posture/manifest.yml

Refactored the variables of GCP to the datastream
-

[Cloud Security] Moved gcp params to datastream

---

packages/microsoft_defender_endpoint/changelog.yml
packages/microsoft_defender_endpoint/kibana/dashboard/microsoft_defender_endpoint-65402c30-ca6a-11ea-9d4d-9737a63aaa55.json
packages/microsoft_defender_endpoint/manifest.yml

microsoft_defender_endpoint: convert visualisations to lens

---

packages/infoblox_nios/changelog.yml
packages/infoblox_nios/kibana/dashboard/infoblox_nios-27c573b0-b4d8-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/dashboard/infoblox_nios-c3abc8b0-b4dd-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/dashboard/infoblox_nios-f8d86480-b4c9-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-4559ff50-b4e1-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-5cc295e0-b4d6-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-7103abb0-b4e1-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-71f7a570-b4dd-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-854739b0-b735-11ec-8ec2-49017af276c3.json
packages/infoblox_nios/kibana/search/infoblox_nios-8d55bb50-b4e1-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-b3b496f0-b4e5-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/kibana/search/infoblox_nios-f3899090-b4d7-11ec-80e1-4bd67c5762eb.json
packages/infoblox_nios/manifest.yml

infoblox_nios: convert visualisations to lens

---

packages/okta/changelog.yml
packages/okta/kibana/dashboard/okta-749203a0-67b1-11ea-a76f-bf44814e437d.json
packages/okta/kibana/search/okta-21028750-67ca-11ea-a76f-bf44814e437d.json
packages/okta/manifest.yml

okta: convert visualisations to lens

---

packages/qnap_nas/changelog.yml
packages/qnap_nas/kibana/dashboard/qnap_nas-32e28700-4b0c-11ec-b2cc-b9a3cc301b75.json
packages/qnap_nas/kibana/search/qnap_nas-50acdec0-4b0c-11ec-b2cc-b9a3cc301b75.json
packages/qnap_nas/manifest.yml

qnap_nas: convert visualisations to lens

---

packages/tenable_io/changelog.yml
packages/tenable_io/kibana/dashboard/tenable_io-0d902a50-edec-11ed-b550-bd5e656b580f.json
packages/tenable_io/kibana/dashboard/tenable_io-4d784610-1ec2-11ed-bad4-551c615a34d1.json
packages/tenable_io/kibana/dashboard/tenable_io-84586900-1ed4-11ed-bad4-551c615a34d1.json
packages/tenable_io/kibana/dashboard/tenable_io-a5395ac0-eb94-11ed-8b7d-ef1c8f105a1d.json
packages/tenable_io/kibana/dashboard/tenable_io-f2dacba0-1e22-11ed-bad4-551c615a34d1.json
packages/tenable_io/manifest.yml

tenable_io: convert visualisations to lens

---

packages/azure/changelog.yml
packages/azure/kibana/dashboard/azure-1e5c9b50-f24a-11ec-a5a8-bf965bcd5646.json
packages/azure/kibana/dashboard/azure-8731b980-f1aa-11ec-a5a8-bf965bcd5646.json
packages/azure/kibana/dashboard/azure-91224490-f1a6-11ec-a5a8-bf965bcd5646.json
packages/azure/manifest.yml

This PR fixes a typo, replacing `azure.account.id` with `cloud.account.id`.
-

Fix Firewall dashboards

---

docs/developer_workflow_bug_fix_older_package_version.md

This PR adds more detailed information into the docs related to backport fixes to old versions.

Add more information to backports docs

---

.github/CODEOWNERS

Removes no-longer-existing packages from the CODEOWNERS file.
-

CODEOWNERS: remove deleted packages from list

---

packages/postgresql/changelog.yml
packages/postgresql/data_stream/activity/manifest.yml
packages/postgresql/data_stream/bgwriter/manifest.yml
packages/postgresql/data_stream/database/manifest.yml
packages/postgresql/data_stream/statement/manifest.yml
packages/postgresql/manifest.yml

- Enhancement
This PR enables TSDB by default for the Postgresql package.
- Closes #5429

[Postgresql] TSDB Enablement

---

packages/lyve_cloud/changelog.yml
packages/lyve_cloud/data_stream/audit/fields/base-fields.yml
packages/lyve_cloud/data_stream/audit/sample_event.json
packages/lyve_cloud/docs/README.md
packages/lyve_cloud/manifest.yml

```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/lyve_cloud
```

[lyve_cloud] - update package-spec to 2.9.0

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Release
This PR updates the Cloud Security Posture package to the `1.4.0` release.
-

Release version 1.4

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
packages/synthetics/data_stream/browser/manifest.yml
packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
packages/synthetics/data_stream/http/manifest.yml
packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
packages/synthetics/data_stream/icmp/manifest.yml
packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
packages/synthetics/data_stream/tcp/manifest.yml
packages/synthetics/manifest.yml

Added test run ID field !!
This is needed to support run once/test now mode in private locations !!
No testing is required. Only code review is desired.

[Synthetics] Added test run ID field

---

packages/network_traffic/LICENSE.txt
packages/network_traffic/changelog.yml
packages/network_traffic/manifest.yml

Fixes license notice.
- Fixes #7149

network_traffic: explicitly license under Elastic 1.0

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
packages/synthetics/data_stream/browser/manifest.yml
packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
packages/synthetics/data_stream/http/manifest.yml
packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
packages/synthetics/data_stream/icmp/manifest.yml
packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
packages/synthetics/data_stream/tcp/manifest.yml
packages/synthetics/manifest.yml

Add field to override monitor.id !!
processor is getting ugly, i think we will probably just need to use yaml in future to add processors. But for now this is the way to go

[Synthetics] Add field to override monitor.id

---

packages/mimecast/changelog.yml
packages/mimecast/data_stream/audit_events/sample_event.json
packages/mimecast/data_stream/dlp_logs/sample_event.json
packages/mimecast/data_stream/siem_logs/_dev/test/pipeline/test-siem-logs.log-expected.json
packages/mimecast/data_stream/siem_logs/elasticsearch/ingest_pipeline/default.yml
packages/mimecast/data_stream/siem_logs/sample_event.json
packages/mimecast/data_stream/threat_intel_malware_customer/_dev/test/pipeline/test-threat-intel-malware-customer.log-expected.json
packages/mimecast/data_stream/threat_intel_malware_customer/elasticsearch/ingest_pipeline/default.yml
packages/mimecast/data_stream/threat_intel_malware_customer/sample_event.json
packages/mimecast/data_stream/threat_intel_malware_grid/_dev/test/pipeline/test-threat-intel-malware-grid.log-expected.json
packages/mimecast/data_stream/threat_intel_malware_grid/elasticsearch/ingest_pipeline/default.yml
packages/mimecast/data_stream/threat_intel_malware_grid/sample_event.json
packages/mimecast/data_stream/ttp_ap_logs/sample_event.json
packages/mimecast/data_stream/ttp_ip_logs/sample_event.json
packages/mimecast/data_stream/ttp_url_logs/sample_event.json
packages/mimecast/docs/README.md
packages/mimecast/kibana/dashboard/mimecast-042d5620-5411-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-0ebd21e0-5422-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-6c61f080-541f-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-7790e470-541a-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-87fba310-5413-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-b4585cb0-541c-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-bca36430-540f-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-f22e62f0-5417-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/kibana/dashboard/mimecast-f8933590-541b-11ec-bd43-b5e1f9a9c8d5.json
packages/mimecast/manifest.yml

- Ensure email.from.address is an array
- Ensure email.to.address is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.8.0 -ecs-git-ref=v8.8.0 -format-version=2.9.0 packages/mimecast
```

[mimecast] - update package-spec to 2.9.0

---

packages/panw_cortex_xdr/changelog.yml
packages/panw_cortex_xdr/data_stream/alerts/manifest.yml
packages/panw_cortex_xdr/manifest.yml

- Adds description for SSL config with link to allowed options.
- Avoids confusion of how SSL properties needs to be set.
- Community post: https://discuss.elastic.co/t/issues-configuring-ssl-tcp-syslog-collection-palo-alto-integration/339572

[Panw Cortex XDR] Add description and default for ssl options

---

packages/jumpcloud/_dev/deploy/docker/docker-compose.yml
packages/jumpcloud/_dev/deploy/docker/files/config.yml
packages/jumpcloud/changelog.yml
packages/jumpcloud/data_stream/events/_dev/test/system/test-default-config.yml
packages/jumpcloud/data_stream/events/elasticsearch/ingest_pipeline/default.yml
packages/jumpcloud/data_stream/events/fields/agent.yml
packages/jumpcloud/data_stream/events/fields/fields.yml
packages/jumpcloud/data_stream/events/sample_event.json
packages/jumpcloud/docs/README.md
packages/jumpcloud/manifest.yml

Add a basic system test that exercises the authentication and checks for an event. The event is taken from the pipeline test data as the API docs do not provide any concrete examples.
To make the test pass, `input.type` and `jumpcloud.event.version` needed to be defined - changed name of `version` from `@version` for improved user experience.
- Closes #6811

jumpcloud: add system test and fix identified issues

---

packages/ping_one/changelog.yml
packages/ping_one/data_stream/audit/sample_event.json
packages/ping_one/docs/README.md
packages/ping_one/manifest.yml

```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/ping_one
```

[ping_one] - update package-spec to 2.9.0

---

packages/slack/changelog.yml
packages/slack/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
packages/slack/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
packages/slack/data_stream/audit/sample_event.json
packages/slack/docs/README.md
packages/slack/manifest.yml

```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.9.0 packages/slack
```

[slack] - update package-spec to 2.9.0

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Bumping version of integration

[cloud_security_posture] Bump version

---

packages/azure/changelog.yml
packages/azure/kibana/dashboard/azure-0f559cc0-f0d5-11e9-90ec-112a988266d5.json
packages/azure/kibana/dashboard/azure-1adf52d0-f50f-11eb-a831-732d3e9bbd43.json
packages/azure/kibana/dashboard/azure-280493a0-f1a1-11ec-a5a8-bf965bcd5646.json
packages/azure/kibana/dashboard/azure-32aedb00-f524-11eb-b9f3-73fa29f35762.json
packages/azure/kibana/dashboard/azure-3cdf69c0-32d9-11ed-a2e6-916b60bbea71.json
packages/azure/kibana/dashboard/azure-5ad41d90-f50e-11eb-a831-732d3e9bbd43.json
packages/azure/kibana/dashboard/azure-5ee36c30-32dc-11ed-a2e6-916b60bbea71.json
packages/azure/kibana/dashboard/azure-91224490-f1a6-11ec-a5a8-bf965bcd5646.json
packages/azure/manifest.yml

- Low
- Enhancement
The aim of this PR is to fix/enhance titles and descriptions for the Azure Logs dashboards due to inconsistencies:
Add the Azure Logs integration and check the dashboards titles/descriptions.
Closes #7384

[Azure Logs] Clean up dashboard titles and descriptions

---

packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs

Fixed conditionals, previously conditionals was using old property name

[Cloud Security] Fixing conditionals 

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

On my previous PR (https://github.com/elastic/integrations/pull/7537) I forgot to include the changelog and manifest yml change
as such It didnt trigger the build to see my changes

Refactoring GCP credentials -Fix continuation

---

packages/ti_cybersixgill/changelog.yml
packages/ti_cybersixgill/data_stream/threat/_dev/test/pipeline/test-cybersixgill-ndjson.log-expected.json
packages/ti_cybersixgill/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
packages/ti_cybersixgill/data_stream/threat/fields/fields.yml
packages/ti_cybersixgill/data_stream/threat/sample_event.json
packages/ti_cybersixgill/docs/README.md
packages/ti_cybersixgill/manifest.yml

- Ensure event.category is an array
- Ensure threat.tactic.name is an array
- Ensure threat.tactic.id is an array
- Ensure threat.tactic.reference is an array
```
[git-generate]
go run github.com/andrewkroh/go-examples/ecs-update@latest -ecs-version=8.9.0 -ecs-git-ref=v8.9.0 -format-version=2.10.0 packages/ti_cybersixgill
```

[ti_cybersixgill] - update package-spec to 2.10.0

---

packages/cloud_security_posture/changelog.yml
packages/cloud_security_posture/manifest.yml

Validate that the `OrganizationalUnitIds` parameter is as expected, see https://github.com/elastic/cloudbeat/pull/1285
- https://github.com/elastic/cloudbeat/issues/1265

[Cloud Security] [AWS Orgs] CloudFormation: Validate OrganizationalUnitIds

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
packages/synthetics/data_stream/browser/fields/summary.yml
packages/synthetics/data_stream/browser/manifest.yml
packages/synthetics/data_stream/browser_network/fields/summary.yml
packages/synthetics/data_stream/browser_screenshot/fields/summary.yml
packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
packages/synthetics/data_stream/http/fields/summary.yml
packages/synthetics/data_stream/http/manifest.yml
packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
packages/synthetics/data_stream/icmp/fields/summary.yml
packages/synthetics/data_stream/icmp/manifest.yml
packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
packages/synthetics/data_stream/tcp/fields/summary.yml
packages/synthetics/data_stream/tcp/manifest.yml
packages/synthetics/manifest.yml

Added max attempts field and mappings
In anticipation of https://github.com/elastic/beats/pull/36147/files#

[Synthetics] Added max attempts field and mappings

---

packages/synthetics/changelog.yml
packages/synthetics/data_stream/browser/manifest.yml
packages/synthetics/data_stream/http/manifest.yml
packages/synthetics/data_stream/icmp/manifest.yml
packages/synthetics/data_stream/tcp/manifest.yml
packages/synthetics/manifest.yml

Set max attempts default value to 2

[Synthetics] Set max attempts default value to 2

---

.ci/schedule-daily.groovy

Update daily integration tests to run against 8.10 branch.

run daily job with 8.10
